### ISSUE TITLE
Testing the tests - with mocks

### ISSUE THREAD

**Issue by michalporeba** [pester/Pester#1004]
Recently I got involved in a very interesting (for me) project dbachecks (https://dbachecks.io) which is using pester a lot, not only to test the code itself, but to deliver the functionality. It runs well and I'm really impressed with both tools, but...

The problems started when I tried to test the tests. We have a scenario where there is a pester test implemented, let say in `DatabaseCollation.Tests.ps1` file. When you do `Invoke-Pester -Script DatabaseCollation.Tests.ps1` it will execute the tests and as part of that it will connect to a remote SQL Server instance, check collations settings on the instance and databases and report success or failure. It works. Now I started writing tests to make sure those 'external' tests (we call them checks) work correctly. I was able to write integration tests without any problems, but when I tried to improve on it and create unit tests using mocks I ran into problems. 

Here is what I'm trying to do

```
Describe "Test checks" {
    InModuleScope dbachecks {
        Mock Get-SqlInstance { return @("specificvalue") }
        Context "Test specific check" {
            $result = (Invoke-Pester -Script $checksScript -Tag DatabaseCollation -PassThru)
            
            Assert-MockCalled Get-SqlInstance -Times 1
            $result.PassedCount | Should -BeGreaterThan 0 
        }
    }
}
```

and here is what I get
```
 [-] Error occurred in Context block 142ms
        RuntimeException: You did not declare a mock of the 86b29b26-66c9-4203-84e7-e954d777c70c Command in module dbachecks.
        at <ScriptBlock>, D:\Dev\dbachecks\tests\checks\Test.Database.Tests.ps1: line 13
        at DescribeImpl, C:\Program Files\WindowsPowerShell\Modules\Pester\4.3.1\Functions\Describe.ps1: line 161
```

I don't think it is a bug, so I'm not following the bug report protocol. The reason to rise this issue to find out if this is something that could be achieved with pester in other way, is that something that you have thought about, perhaps something on the roadmap, or at all achievable?

**Comment by michalporeba** [comment]
I am now looking at http://jakubjares.com/2017/12/07/testing-your-environment-tests/
to see if that is something that will address my problem

**Comment by nohwnd** [comment]
I think the post should cover most of what you want. If there are more questions either ping me on twitter/slack or re-open this issue. 😊

**Comment by michalporeba** [comment]
I have done a lot since then and somehow forgot about this ticket. The post didn't solve the problem but I found other ways to work about that limitation. I'm good with closing this ticket. I plan to review some of the other open tickets when I'm off work for the last two weeks of the year.
