### ISSUE TITLE
Pester tests with unicode strings in code

### ISSUE THREAD

**Issue by NickDMax** [pester/Pester#1005]
## 1. Provide a general summary of the issue in the Title above

I am running a test to see that a function based upon the  String.Normalize() function works -- but "under pester" the test fails - outside of pester the assertion works fine. Pester seems to be performing some encoding of the strings within the code (or just the code itself).

Please review https://github.com/pester/Pester/wiki/Contributing-to-Pester prior to submitting an issue.

## 2. Describe Your Environment

Operating System, Pester version and PowerShell version:

Pester version     : 4.2.0 C:\Users\nickdmax\Documents\WindowsPowerShell\Modules\Pester\Pester.psm1
PowerShell version : 4.0
OS version         : Microsoft Windows NT 6.1.7601 Service Pack 1

## 3. Expected Behavior

```powershell
Describe 'String.Normalize' {
    Context 'Testing wide Chars' {
        It '＆' { 
            '＆'.Normalize("FormKD") | Should -Be "&"
        }
    }
}
```

Here the ampersands in the single quotes ('＆') are Unicode Fullwidth Ampersand (U+FF06) and the one in double quotes ("&") is a normal width (shift+7) ampersand (the two different kind of quotes were just used here to make them easier to talk about).

If we use the analog code: `('＆'.Normalize("FormKD") -eq '&')` we get True and so I would expect the above Pester test to work.

## 4.Current Behavior

```powershell
Describe 'String.Normalize' {
    Context 'Testing wide Chars' {
        It '＆' { 
            '＆'.Normalize("FormKD") | Should -Be "&"
        }
    }
}
```
This returns the following:

```
    Context Testing wide Chars
      [-] ï¼† 183ms
        Expected strings to be the same, but they were different.
        Expected length: 1
        Actual length:   6
        Strings differ at index 0.
        Expected: '&'
        But was:  'ï1⁄4†'
```
So it seems that the fullwidth ampersand was encoded as 'ï¼†' before it was passed to the normalize function which did indeed normalize the string making the ¼ become 1⁄4 which makes sense -- but why did Pester cause '＆' to become 'ï¼†'?

I have found that many Unicode characters are re-encoded. for example trying to test that 'ï¼†' results in 'ï1⁄4†' fails because the string 'ï¼†' becomes 'Ã¯Â¼â€' under Pester.

## 6. Context

Perhaps I should not be trying to add the Unicode characters directly to my tests and instead put them into some file -- but for simplicity this would have been nice. It looks as though I will need to put all of my test strings into a file and run them line for line - but then I need tests for my tests and its turtles all the way down. I was trying to keep it simple.

**Comment by NickDMax** [comment]
'ï¼' is EF BC 86  which is the UTF8 code point used to encode U+FF06 -- So it looks like pester is reading the UTF8 - encoded powsershell code byte-for-byte rather than as UTF8.

**Comment by NickDMax** [comment]
Well I took a guess that the problem was that Powershell will read and execute UTF8 encoded code - but when it reads a scriptblock it does not decode the code properly:

```function Display-ScriptBlock {
    param(
        [scriptblock]$script
    )
    $script.ToString()
}

Display-ScriptBlock -script { "＆" }
```

This shows the same behavior.

**Comment by alx9r** [comment]
The comparison seems to take place on [this line](https://github.com/pester/Pester/blob/b8fa450b30eacce1318c9a0e81f5617f6babc471/Functions/Assertions/Be.ps1#L228).

@NickDMax I've invoked 

```PowerShell
Describe 'String.Normalize' {
    Context 'Testing wide Chars' {
        It '＆' { 
            '＆'.Normalize("FormKD") | Should -Be "&"
        }
    }
}
```

under WMF 5.1's PowerShell 5.1 and PowerShell 2 (I don't have a PowerShell 4 test system available right now).  It passes in both cases.  Can you confirm whether you see this behavior in any version of PowerShell other than 4?

**Comment by NickDMax** [comment]
I can confirm that it works under:

```
Describing String.Normalize
   Context Testing wide Chars
    [+] ＆ 38ms
Pester version     : 3.4.0 C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Pester.psm1
PowerShell version : 5.1.16299.248
OS version         : Microsoft Windows NT 10.0.16299.0
```

**Comment by nohwnd** [comment]
Can we do something about this, or is it most likely a general problem with PowerShell?
