### ISSUE TITLE
Should -Not -Throw doesn't print or display the actual exception if caught

### ISSUE THREAD

**Issue by ChrisLynchHPE** [pester/Pester#1009]
## 1. Provide a general summary of the issue in the Title above

I recently upgraded Pester from 3.x to 4.x, and have noticed a different behavior with catching exceptions that should not be thrown.  In 3.x and older, when an unexpected exception was caught within an It block, the exception message would be displayed.

## 2. Describe Your Environment

Operating System, Pester version and PowerShell version:

```powershell
Pester version     : 4.3.1 C:\Users\clynch\Documents\WindowsPowerShell\Modules\pester\Pester.psm1
PowerShell version : 5.1.16299.248
OS version         : Microsoft Windows NT 10.0.16299.0
```

## 3. Expected Behavior
It is expected the caught exception message be displayed in the output.

```PowerShell
Describe "Unit Test 1" {

    It "Will not throw an error" {

        { gci C:\temp\nonexistingfile.txt -ErrorAction Stop } | Should -Not -Throw

    }

    It "Will be true" {

        $true | Should -Be $true

    }

}

```

And should generate the following output:
```PowerShell
Describing Unit Test 1
  [-] Will not throw an error 163ms
    Expected no exception to be thrown, but an exception "gci : Cannot find path 'C:\temp\nonexistingfile.txt' because it does not exist." was thrown from line:5 char:11
        +         { gci C:\temp\nonexistingfile.txt -ErrorAction Stop } | Shoul ...
        +           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
    5:         { gci C:\temp\nonexistingfile.txt -ErrorAction Stop } | Should -Not -Throw
  [+] Will be true 74ms
```

## 4.Current Behavior

The current behavior does not show the exception message caught.  

```powershell
Describing Unit Test 1
  [-] Will not throw an error 163ms
    Expected no exception to be thrown, but an exception was thrown from line:5 char:11
        +         { gci C:\temp\nonexistingfile.txt -ErrorAction Stop } | Shoul ...
        +           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
    5:         { gci C:\temp\nonexistingfile.txt -ErrorAction Stop } | Should -Not -Throw
  [+] Will be true 74ms
```

## 6. Context

When dealing with 1000+ unit tests, where exceptions should not be thrown, it is difficult to go back and refactor all tests to try to capture the exception message for each test that should not throw an exception.

Forgot to mention this is very similar to #138, which was seen way back in the 2.x days.

**Comment by nohwnd** [comment]
@ChrisLynchHPE you are right, the exception should be visible when the test fails. I will add it.

**Comment by nohwnd** [comment]
@ChrisLynchHPE the next one :) Hopefully I will get to releasing it till the next week.

**Comment by ChrisLynchHPE** [comment]
Just saw `4.4.0-Beta` published.  I saved and started testing my Pester tests with it, and can confirm `Should -Not -Throw` is working as it used to in the 3.x release.
