### ISSUE TITLE
Let CodeCoverage exclude Pester Tests by default

### ISSUE THREAD

**Issue by Remco-74** [pester/Pester#1014]
## Describe Your Environment

Operating System, Pester version and PowerShell version:

```powershell
Pester version     : 4.3.1 C:\Program Files\WindowsPowerShell\Modules\Pester\4.3.1\Pester.psm1
PowerShell version : 5.1.16299.251
OS version         : Microsoft Windows NT 10.0.16299.0
```

## Expected Behavior

When using `-CodeCoverage *`, Pester test scripts (`*.Tests.ps1`) should be excluded from code coverage reoprting. 

## Current Behavior

When using `-CodeCoverage *`, Pester test scripts (`*.Tests.ps1) are included in code coverage reporting.

```powershell
Invoke-Pester -Path . -CodeCoverage *
WARNING: CodeCoverage path '*' resolved to a non-PowerShell file 'Some.psd1'; this path will not be part of the coverage report.
WARNING: CodeCoverage path '*' resolved to a non-PowerShell file 'Some.pssproj'; this path will not be part of the coverage report.
WARNING: CodeCoverage path '*' resolved to a non-PowerShell file 'Some.zip'; this path will not be part of the coverage report.```
```

## Possible Solution

Exclude `*.Tests.ps1` file from CodeCoverage, just like module manifests (`*.psd1`) or other non-PowerShell files.

Replace line 131 of Coverage.ps1 with:

```powershell
    if (
        ($item -is [System.IO.FileInfo]) -and 
        (('.ps1','.psm1') -contains $item.Extension) -and 
        (-not $item.Name.ToLower().EndsWith('.tests.ps1'))
    )
```

## Context

When using Code Coverage, it is desirable to just use `-CodeCoverage *`, and not having to create a file set with the files to be covered up front.

Reporting code coverage over test scripts (by default) is not very useful.

**Comment by it-praktyk** [comment]
I like that idea.

**Comment by nohwnd** [comment]
I like it as well. I think skipping *.tests.ps1 files is a good default. Marking this as help wanted, possible implementer should check that tests can be included if needed.

**Comment by ChrisLGardner** [comment]
I'll try to pick this up in the next few days, sounds like a fun challenge.

**Comment by fflaten** [comment]
@ChrisLGardner Are you still working on this? Had some spare time during my vacation and played with this while getting to know the Pester-module. I won't submit anything if you're already working on it. :)

**Comment by ChrisLGardner** [comment]
I got distracted by other things and haven't had a chance to look at it. Feel free to submit a PR if you've something working.
________________________________
