### ISSUE TITLE
Mocking cmdlets with Transformation Attributes

### ISSUE THREAD

**Issue by AlexGagne** [pester/Pester#1015]
Pester version     : 4.3.1 C:\Program Files\WindowsPowerShell\Modules\Pester\4.3.1\Pester.psm1
PowerShell version : 5.1.15063.966
OS version         : Microsoft Windows NT 10.0.15063.0

I am trying to mock a cmdlet that has a transformation attribute, coming from a strongly-typed function.

 I am trying to test this function:

``` powershell
function Do-Something {
    param([Parameter(Mandatory=$true)] [String] $something)
    return Get-Something -Name $something
}
```

I want to mock the Get-Something cmdlet.

Internally, the Something parameter gets transformed into a Library.Something object using ArgumentTransformationAttribute, so the Cmdlet expects a Library.Something object as a parameter.

I have tried Mocking and overriding the Name parameter from the Get-Something Cmdlet, but I keep getting this error:

`PSInvalidCastException: Cannot convert the "test1" value of type "System.String" to type "Library.Something".`

Short of modifying the Do-Something function so that it isn't strongly typed anymore, is there anything I can do with Pester to properly mock the Get-Something cmdlet?

**Comment by alx9r** [comment]
Do you have a repro that you can post?  This example seems to successfully mock function `f` which uses `ArgumentTransformationAttribute`:

```PowerShell
class Always2Attribute : System.Management.Automation.ArgumentTransformationAttribute
{
    [object] Transform(
        [System.Management.Automation.EngineIntrinsics] $engineIntrinsics,
        [object] $inputData
    )
    {
        return 2
    }
}

function f {
    param([Always2()]$x)
    $x
}


Describe ArgumentTransformationAttribute {
    It 'outputs 2' {
        f -x 1 | Should -be 2
    }
    Context 'mock' {
        function g {
            f -x 1
        }
        Mock f -Verifiable
        It 'calls mock' {
            g
            Assert-MockCalled f
        }
    }
}
```

**Comment by AlexGagne** [comment]
```class DoesNotConvert : System.Management.Automation.ArgumentTransformationAttribute
{
    [object] Transform(
        [System.Management.Automation.EngineIntrinsics] $engineIntrinsics,
        [object] $inputData
    )
    {
        #Imagine this does processing that cannot be done during tests 
        return $inputData
    }
}

function f{
    param([String] $x)
    g($x)
}

function h{ # Same function as f, no type restriction
    param($x)
    g($x)
}

function g{
    param([int32] [DoesNotConvert()]$y)
    $y
}



Describe ArgumentTransformationAttribute {
    
    Mock g {
        param($y)
		Write-Host "Value is $y" #Should print $y regardless of g's transformation
    }

    It 'Testing the Mock'{
		$name = "test1"
		f -x $name
    }

    It 'Can be circumvented by removing the type restriction on the function and giving the type the called function needs'{
		$name = 1
		h($name)
    }
}
```

So, I think I didn't understand properly my problem, but I now see what my problem is. The problem is that the Transformation attribute fails because it does work that cannot be done during tests (simulated here by simply failing the convert). Is there a way to skip the transformation/mock the transform attribute?

**Comment by alx9r** [comment]
"Testing the Mock" fails because you are trying to convert `"test1"` to `[int32]` when it is passed to `g`.  That is same as the statement `[int32]"test1"`, which fails with the same error.  Changing `"test1"` to `"1"` (which is a string that is convertible to `[int32]`) causes the test to pass.

As a side note, for out-of-the-box PowerShell, `h($name)` invokes `Get-History` because of the built-in `h` alias.  Replacing the function name `h` with `k` in your repro avoids that.  Here is your code with those changes:

```PowerShell
class DoesNotConvert : System.Management.Automation.ArgumentTransformationAttribute
{
    [object] Transform(
        [System.Management.Automation.EngineIntrinsics] $engineIntrinsics,
        [object] $inputData
    )
    {
        #Imagine this does processing that cannot be done during tests 
        return $inputData
    }
}

function f{
    param([String] $x)
    g($x)
}

function l{ # Same function as f, no type restriction
    param($x)
    g($x)
}

function g{
    param([int32] [DoesNotConvert()]$y)
    $y
}



Describe ArgumentTransformationAttribute {
    
    Mock g {
        param($y)
		Write-Host "Value is $y" #Should print $y regardless of g's transformation
    }

    It 'Testing the Mock'{
		$name = "1"
		f -x $name
    }

    It 'Can be circumvented by removing the type restriction on the function and giving the type the called function needs'{
		$name = 1
		l($name)
    }
}
```

Both those tests pass:

```none
Describing ArgumentTransformationAttribute
Value is 1
  [+] Testing the Mock 76ms
Value is 1
  [+] Can be circumvented by removing the type restriction on the function and giving the type the called functi
on needs 16ms
```

**Comment by it-praktyk** [comment]
I assume that the issue can be closed now. Feel free to reopen if you need more assistance.
