### ISSUE TITLE
Filtered Mock of 'Get-ADComputer' Not Being Applied to Call of 'Get-ADComputer' in ForEach Loop

### ISSUE THREAD

**Issue by adamfortuno** [pester/Pester#1018]
OS: Windows 10 64-bit
Powershell: 5.1.15063
Pester: 4.2.0

I am testing a function that has the following snippet:

```powershell
$server_names = @('foo', 'bar')
$ServerNames | ForEach-Object { Get-ADComputer -Identity $_ }
```

I have the following mock setup in a context block:

```powershell
$server_names = @('foo', 'bar')
Mock 'Get-ADComputer' { $thing } -ParameterFilter { $PSBoundParameters.Identity -eq ${server_names}[0] }
Mock 'Get-ADComputer' { $otherthing } -ParameterFilter { $PSBoundParameters.Identity -eq ${server_names}[1] }
```

I'd expect my mocks to be called, but they're not. If I add an unfiltered mock, 

```powershell
Mock 'Get-ADComputer' { $stuff; Write-Host 'test' }
```

The unfiltered mock is called for both iterations of the call to 'Get-ADComputer'.

![image](https://user-images.githubusercontent.com/30395811/38445505-e1a6d40e-39c1-11e8-98e1-1d46487e7ca5.png)

I'm more frustrated with this than Snookie trying to get laid during the first season of Jersey Shore.

**Comment by alx9r** [comment]
@adamfortuno 

I haven't been able to reproduce your issue.  Do you have a repro you can post?

For reference, below is example that invokes mocks using parameter filters in a similar manner to what you describe.  Obviously there would be differences from your situation, but I thought it might help narrow in on those differences.

The example is as follows:

```PowerShell
Describe 'PSBoundParameters in Mock ParameterFilter' {
    function f {param($x)}
    function g {
        $names = @('foo', 'bar')
        $names | ForEach-Object { f -x $_ }
    }
    $names = @('foo', 'bar')
    Mock f { Write-Host 'filter for foo'} -ParameterFilter { 
        $PSBoundParameters.x -eq $names[0] 
    }
    Mock f { Write-Host 'filter for bar'} -ParameterFilter { 
        $PSBoundParameters.x -eq $names[1]
    }
    g
    It 'calls both mocks' {
        Assert-MockCalled f -Times 2
    }
}
```

That outputs the following:

```none
Describing PSBoundParameters in Mock ParameterFilter
filter for foo
filter for bar
  [+] calls both mocks 95ms
```

**Comment by adamfortuno** [comment]
I posted this issue on StackExchange as well - see [Mock with ParameterFilter Not Being Called (Pester)](https://stackoverflow.com/questions/49701142/mock-with-parameterfilter-not-being-called-pester/49701942#49701942).  Patrick Meinecke helped me resolve the issue. The parameter in the commandlet I was mocking took an object. I was supplying a string. It was converting the string to a new object, and the objects were never truly equal. Not a Pester problem. More of a user problem.

**Comment by nohwnd** [comment]
similar issue #973
