### ISSUE TITLE
Code Coverage for proxy functions/steppablePipelines

### ISSUE THREAD

**Issue by Aorimn** [pester/Pester#1028]
## 1. Provide a general summary of the issue in the Title above

In proxy functions, a steppable pipeline is created from a scriptblock:
```
$scriptCmd = {& $wrappedCmd @PSBoundParameters }
$steppablePipeline = $scriptCmd.GetSteppablePipeline($myInvocation.CommandOrigin)
```

Each pipeline phase (begin/process/end) is then called on this object, thus actually executing the scriptblock.

However, when executing Pester with the CodeCoverage option, the scriptblock is reported as not being executed:
```
Missed commands:

File        Function      Line Command
----        --------      ---- -------
Module.psm1 Select-String   71 $scriptCmd = {& $wrappedCmd @PSBoundParameters }
Module.psm1 Select-String   71 & $wrappedCmd @PSBoundParameters
```

## 2. Describe Your Environment

Operating System, Pester version and PowerShell version:

```powershell
Pester version     : 3.4.0 C:\Program Files\WindowsPowerShell\Modules\pester\3.4.0\Pester.psm1
PowerShell version : 5.1.16299.251
OS version         : Microsoft Windows NT 10.0.16299.0
```

## 3. Expected Behavior

Pester should check the pipeline is executed (`$steppablePipeline`'s Begin, Process and End methods should be called) and if so, mark the code in the scriptblock as executed.

## 4. Current Behavior

Pester doesn't recognise steppable pipelines execution and marks the code as not having been executed.

## 5. Possible Solution

Not sure how code coverage is implemented in Pester, so I'll not venture into a possible solution and its corner cases.

## 6. Context

This issue is for statistic purpose only, having two lines by function not being reported as covered isn't a big deal, but that's still erroneous-ish.

**Comment by it-praktyk** [comment]
@Aorimn, thank you for the report.

Can you confirm it using the current version (4.3.1) of Pester? The version 3.4.* will be deprecated soon.

**Comment by Aorimn** [comment]
Sorry for the delay, I confirm it for the version 4.3.1

**Comment by nohwnd** [comment]
Marked this as help wanted. Code coverage works by putting breakpoint on a "line" automaticaly and checking if it was hit. It's possible that breakpoint cannot be set in that place or is not set at all.
