### ISSUE TITLE
OutputFile does not resolve PSDrive

### ISSUE THREAD

**Issue by lipkau** [pester/Pester#1029]
## 1. Provide a general summary of the issue in the Title above

When writing the results of `Invoke-Pester` to a file (eg: `-OutputFormat NUnitXml -OutputFile "Test:\foo.xml"`), it fails to write to a path that uses a PSDrive.

## 2. Describe Your Environment

Operating System, Pester version and PowerShell version:

```
Pester version     : 4.1.1 C:\Users\olive\Documents\PowerShell\Modules\Pester\4.1.1\Pester.psd1
PowerShell version : 6.0.2
OS version         : Microsoft Windows NT 6.2.9200.0
```

## 3. Expected Behavior

NUnitXML is written.

## 4.Current Behavior

NUnitXML is not written - `Invoke-Pester` throws

```powershell
New-PSDrive Test FileSystem $Home
Invoke-Pester -Script <a very small pester test file> -OutputFormat NUnitXml -OutputFile "Test:\foo.xml"
```
```
Exception calling "Create" with "1" argument(s): "The given path's format is not supported."
At C:\Users\olive\Documents\WindowsPowerShell\Modules\Pester\4.3.1\Functions\TestResults.ps1:63 char:9
+         $xmlFile = [IO.File]::Create($Path)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NotSupportedException
```

**Comment by it-praktyk** [comment]
Something like doesn't mean 'exactly' ;-)

`Join-Path -Path $(resolve-path (Split-Path Test:\foo.xml)).ProviderPath -ChildPath $(Split-Path Test:\foo.xml -Leaf)`

It works under PSCore 6.1.0-preview.2

**Comment by nohwnd** [comment]
@it-praktyk so what was the problem exactly? :)
