### ISSUE TITLE
Tags should not split on whitespace

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#1039]
Implementing wildcards for Tags I noticed that tags provided to `Invoke-Pester` will be split on whitespace. Is this for historical reasons? Does anyone use this? To me it's just an awkward non-standard behavior.

I would expect that any valid string could be provided as a tag, and that providing multiple tags is done by using a comma, as with any other PowerShell cmdlet. Thoughts?

@Jaykul gherking is doing the same (probably following how `Invoke-Pester` did it, would it makes sense to remove the splitting to make the behavior less surprising?

**Comment by nohwnd** [comment]
related #557

**Comment by Jaykul** [comment]
Yes, the tags parameter in `Invoke-Gherkin` was mostly copied from `Invoke-Pester` I think. 
I wouldn't make a big deal of it myself (never even noticed, guess I use WordsSmashedTogether) for backward compatibility reasons, but I don't mind changing it -- I agree with Dave that for new users, it's confusing to take an array, _and **also**_ split the input...

**Comment by johlju** [comment]
@nohwnd  I don't think anyone would expect it to behave like that, splitting on whitespace. Also, it is undocumented (?) so if someone is using it they probably read the code, come across it by accident or just didn't notice. My thoughts. :)

**Comment by nohwnd** [comment]
Great that is what I wanted to hear. I will remove it and update the documentation.
