### ISSUE TITLE
Pester hangs when invoking xclip on Ubuntu 16.04

### ISSUE THREAD

**Issue by mklement0** [pester/Pester#1045]
# 1. Provide a general summary of the issue in the Title above

`xclip` is a clipboard utility for X11-based desktop environments.

You can install it with `sudo apt-get install xclip`.

Interactive use or use in regular scripts works fine, but in the context of a Pester test it _hangs_ when trying to _copy_ something to the clipboard.

It returns once something _else_ is copied to the clipboard, externally.

## 2. Describe Your Environment

The OS is 64-bit Ubuntu 16.04.04 LTS

```powershell
Pester version     : 4.3.1 /usr/local/share/powershell/Modules/Pester/4.3.1/Pester.psd1
PowerShell version : 6.1.0-preview.2
OS version         : Unix 4.13.0.41
```

## 3. Expected Behavior

A command such as `'foo' | xclip -selection clipboard -in`, which copies string `foo` to the clipboard - should succeed.

## 4.Current Behavior

Said command, in the context of an `It` test, _hangs indefinitely_.

It seems that copying per se succeeds, but the test doesn't return until you externally copy something else to the clipboard.

```powershell
it "invokes xclip" { 
  # The following command hangs.
  'foo' | xclip -selection clipboard -in
}
```

Adding `-loops 1` makes the command return _eventually_, but (a) without copying anything to the clipboard and (b) returning after widely varying amounts of time, from 1 second to 30+ seconds.

## 6. Context

I'm trying to implement a cross-platform clipboard module, and I want to test its functionality on Linux platforms.

**Comment by nohwnd** [comment]
Weird, thanks for reporting. I am not able to replicate this in docker, because it cannot open a display, so I will have to install a full blown virtual machine :)

**Comment by mklement0** [comment]
Thanks for giving it a shot, @nohwnd.

Turns out poor Pester isn't to blame; it only surfaced the problem, whose reproduction is as simple as:

```powershell
$null = 'foo' | xclip -selection clipboard -in
```

I.e., simply trying to _capture_ the output (even though there is none) causes the hang.

I've opened https://github.com/PowerShell/PowerShell/issues/6875 and I'm closing this.

**Comment by mklement0** [comment]
Turns out it was `xclip` itself, as @BrucePay discovered:

It apparently never closes the stdout stream when used in a pipe, which also applies to capturing the result in a variable in PowerShell, such as the `$null = ...` idiom that Pester uses behind the scenes.

The workaround from PowerShell is to call `xclip` via `sh -c` and to explicitly close stdout with `>&-`:

```powershell
$null = 'foo1' | sh -c 'xclip -selection clipboard -in >&-'
```
