### ISSUE TITLE
Allow Mock to target nonexistent external programs to facilitate testing cross-platform code

### ISSUE THREAD

**Issue by mklement0** [pester/Pester#1047]
## 1. Provide a general summary of the issue in the Title above

Currently, `Mock` requires the targeted command to _exist_.

However, cross-platform code may involve calls to platform-specific external utilities (programs) that aren't available on _all_ supported platforms - e.g., `cmd.exe` vs. `/bin/sh`.

Currently, you can work around that problem in two ways:

* Define dummy functions for all utilities getting invoked across platforms before calling `Mock`

* Use _conditional_ `Mock` definitions based on conditionals such as `if ($IsWindows) { ... }`.

A more convenient alternative would be to allow targeting nonexistent commands - and then assume that they're _external programs_ - by way of an opt-in mechanism such as a new `-AssumeExternal` switch:

```powershell
Mock -AssumeExternal sh { /bin/sh -c '...' }
```

This has two benefits:

* The test code is less cluttered with conditionals.

* It allows you to run tests even in the absence of the mocked-up utilities (albeit only with unconditional mocks or a set of related mocks that cover all invocation scenarios).

## 2. Describe Your Environment

Written as of Pester v4.3.1

## 3. Desired Behavior

```powershell
Describe ExternalUtilityTest {

  Mock -AssumeExternal cmd { & $env:SystemRoot\System32\cmd.exe /c 'nosuchexe' } 
  Mock -AssumeExternal sh { /bin/sh -c 'nosuchutil' }

  It "Fails if a required external utility is missing." {
     # ... | Should -Throw
  }

```

## 4. Current Behavior

```powershell
Describe ExternalUtilityTest {

  if ($env:OS -eq 'Windows_NT') {
    Mock cmd { & $env:SystemRoot\System32\cmd.exe /c 'nosuchexe' } 
  } else {
    Mock sh { /bin/sh -c 'nosuchutil' }
  }

  It "Fails if a required external utility is missing." {
     # ... | Should -Throw 
  }

```

**Comment by nohwnd** [comment]
This issue is not limited to only Mocks and non-existing command, there are also environment variables that are defined on one system and not the other, paths, case sensitivity issues etc. Testing code cross-platform is complex and this complexity should not hide in Mock. This proposal covers only one aspect in a way that does not align with Mocks behavior that does not permit mocking someting that does not exist. Won't implement this. Sorry.
