### ISSUE TITLE
Pester 4.3.1 points to internal cmdlet when test is failing instead of tested cmdlet.

### ISSUE THREAD

**Issue by Stephanevg** [pester/Pester#1053]
## 1. Provide a general summary of the issue in the Title above

Please review https://github.com/pester/Pester/wiki/Contributing-to-Pester prior to submitting an issue.

## 2. Describe Your Environment

```powershell
Pester version     : 4.0.3 3.4.3 3.4.0 3.3.5 C:\Program Files\WindowsPowerShell\Modules\Pester\4.0.3\Pester.psd1 C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.3\Pester.psd1 C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Pester.psd1 C:\Program Files\WindowsPowerShell\Modules\Pester\3.3.5\Pester.psd1
PowerShell version : 5.1.14393.2189
OS version         : Microsoft Windows NT 10.0.14393.0

```

## 3. Expected Behavior

I would expect that the test that is failing actually outputs the information related to the test, not tot the internal cmdlet from Pester.

This is  the correct output:

![image](https://user-images.githubusercontent.com/6302961/40574465-7ef93198-60d2-11e8-98f4-471f21be5012.png)

## 4.Current Behavior

This is powershell version 5.1, and pester 4.3.1, in Appveyor.

I have a test that is failing, but instead of displaying what is failing, It displays which internal Pester cmdlet throws the error. this is what I get on the screen:

![image](https://user-images.githubusercontent.com/6302961/40574442-4d19244e-60d2-11e8-8387-9ddccb8bdd38.png)

The error points to line number of the ```should.ps1```cmdlet. I would expect that it points the error in the cmdlet failing.

## 5. Possible Solution

Have a solution in mind?

Nope

**Comment by it-praktyk** [comment]
@nohwnd , maybe is it a good time to add a deprecation warning?

**Comment by nohwnd** [comment]
Marked this as Help Wanted, the problem should be solved by adding appropite regex to Output.ps1 where the ErrorLines are filtered.

**Comment by nohwnd** [comment]
Assertions in legacy mode are no longer a thing in v5.
