### ISSUE TITLE
"Dot sourcing" / "using module" into test file - Issue with classes

### ISSUE THREAD

**Issue by njmaeff** [pester/Pester#1054]
## 2. Describe Your Environment

Operating System, Pester version and PowerShell version:

```powershell
Pester version: 4.3.1 3.4.0 
C:\Program Files\WindowsPowerShell\Modules\Pester\4.3.1\Pester.psd1 
C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Pester.psd1
PowerShell version : 5.1.16299.431
OS version : Microsoft Windows NT 10.0.16299.0
```

## 3. Expected Behavior

I would like to add the dot source at the beginning of the script and for the class definitions to be recognized.

## 4.Current Behavior

If I dot source the system under test before running pester, it works as expected. If I'm running a new session and Invoke-Pester, I get an error. The "using module" import does not seem to work even if entered in the shell prior to invoke-pester. That is with the system under test being a module.

Currently, I get a type error when running directly from Invoke-Pester.

![image](https://user-images.githubusercontent.com/31554476/40592368-28106962-61d3-11e8-9ae7-397c08656830.png)

### With scripts

Example.ps1
```powershell
class Example {
    [string] $test
    Example() {
        $this.test = "Hello"
    }
}
```

Example.Tests.ps1
```powershell
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path) -replace '\.Tests\.', '.'
. "$here\$sut"

Describe "Example" {
    BeforeAll {
        [Example]$example = [Example]::new()
    }
    It "does something useful" {
        $example | Should -BeOfType [Example]
    }
}
```

### With modules:

Example.psm1
```powershell
class Example {
    [string] $test
    Example() {
        $this.test = "Hello"
    }
}
```

Example.Tests.ps1
```powershell
using module <path-to-example.psm1>

Describe "Example" {
    BeforeAll {
        [Example]$example = [Example]::new()
    }
    It "does something useful" {
        $example | Should -BeOfType [Example]
    }
}
```

## 5. Possible Solution

Sorry...

## 6. Context

It seems like an unnecessary step having to dot source the system under test before invoke-pester?

**Comment by nohwnd** [comment]
Pester does not work well with  `using` because the module is imported too early. You should use Import-Module in your BeforeAll

**Comment by dglambert** [comment]
Import-Module does not work with classes, so not sure how this would work?

**Comment by johlju** [comment]
You import the module then you could use InModuleScope to use the classes with InModuleScope having `using module` as the first line in a ScriptBlock. Maybe this can help someone, or find a smarter way:

https://github.com/dsccommunity/DscResource.Base/blob/59021edd7236a6c06a84727547e572b9b62643ac/tests/Unit/Classes/ResourceBase.Tests.ps1#L147-L196
