### ISSUE TITLE
Longer Tests Break Problem Matcher

### ISSUE THREAD

**Issue by awickham10** [pester/Pester#1062]
## 1. Provide a general summary of the issue in the Title above
The VSCode problem matcher is hard coded to match against tests that take milliseconds (searching for the string "ms"). 

## 2. Describe Your Environment
Operating System, Pester version and PowerShell version:
```powershell
Pester version     :  
PowerShell version : 5.1.17686.1003
OS version         : Microsoft Windows NT 10.0.17686.0
```

## 3. Expected Behavior
The problem matcher should match tests that take a second or longer to run.

## 4.Current Behavior
The problem matcher does not match against tests that take 1 second or longer to run.

```powershell
# This will not show up in the problem matcher
It "takes longer than a second" {
    Sleep-Task -Seconds 2
}
```

## 5. Possible Solution
It appears the regular expression is hard coded to match against ms. 

```
^\s*(\[-\]\s*.*?)(\d+)ms\s*$
```

can be changed to
```
^\s*(\[-\]\s*.*?)(\d+)(?:s|ms)\s*$
```

## 6. Context
Some tests take longer to run than 1 second and this issue prevents those from showing up.

**Comment by awickham10** [comment]
This is actually an issue for PowerShell/vscode-powershell, not Pester. My apologies.

**Comment by it-praktyk** [comment]
> This is actually an issue for PowerShell/vscode-powershell

@awickham10, thank you for the report. Can you reference the mentioned issue? Thank you.

**Comment by awickham10** [comment]
The PowerShell/vscode-powershell is can be found here: https://github.com/PowerShell/vscode-powershell/issues/1291
