### ISSUE TITLE
Mocking the dynamic command

### ISSUE THREAD

**Issue by Mallappays** [pester/Pester#1067]
I have a situation. The Poweshell script will pick a function name from the xml file that suppose to get execute. Wondering how to mock the command that read from the xml.

Running Pester 4.3.1 on Windows Server 2008 R Standard Edition and using Powershell 4.0

This is my Powershell script to be unit tested
```

$actionXml = New-Object xml
$actionXml.PreserveWhitespace = $true
$actionXml.Load($XmlPath) 
foreach($action in $actionXml.SubActions.Action)
   {
          $funParams = & $($action.Api)
   }

```
"& $($action.Api) " is dynamic command. The $action.Api will be a command name. How do I mock the call?

If I try to mock with name as from the xml file

`MOCK ThisIsSampleAPI -MockWith {return ""}`

I get error saying could not find "ThisIsSampleAPI"

**Comment by johlju** [comment]
You need something for the mock to "attach to", so if you create a `function ThisIsSampleAPI {}` before you call `Mock` it will have something to "attach to".

**Comment by Mallappays** [comment]
Thank you.
