### ISSUE TITLE
Mocking Functions of an object

### ISSUE THREAD

**Issue by Mallappays** [pester/Pester#1068]
I would like to mock a inner function/command for an object.  Let me give you a background. I am processing a xml file. The xml object will have a Load and Save as a inner function. I would like to mock the Save and Load.

Running Pester 4.3.1 on Windows Server 2008 R Standard Edition and using Powershell 4.0

This is my Powershell script to be unit tested

```
$actionXml = New-Object xml
$actionXml.PreserveWhitespace = $true
$actionXml.Load($XmlPath) 
```

I dont know how to mock the .Load(xmlfilePath)

Could you please me how I do it?

**Comment by mikeclayton** [comment]
Hi @Mallappays,

You can't mock members of CLR objects, so you'll need to wrap the call in your own function, and then you can mock that. For example:

**Your Code**
```powershell
function Invoke-MyLoadXml
{
    param( [xml] $XmlDoc, [string] $Xml )
    $XmlDoc.LoadXml($Xml);
}

function Invoke-MyFunction
{
    param( [string] $Xml )
    $actionXml = New-Object xml;
    $actionXml.PreserveWhitespace = $true;
    Invoke-MyLoadXml -XmlDoc $actionXml -Xml $Xml;
    return $actionXml.OuterXml;
}
```

**Your Tests**
```powershell
Describe "Invoke-MyFunction Tests" {

    Context "Load" {

        Mock "Invoke-MyLoadXml" {
            param( [xml] $XmlDoc, [string] $Xml )
            $xmlDoc.LoadXml("<mock_root></mock_root>");
        }

        It "should load mocked xml" {
            $expected = "<mock_root></mock_root>";
            $actual   = Invoke-MyFunction -Xml "<real_root><real_root>";
            $actual | Should Be $expected;
        }

    }

}
```

Hope this helps.

Cheers,

Mike
