### ISSUE TITLE
How to test a function within a script

### ISSUE THREAD

**Issue by DarkLite1** [pester/Pester#1069]
This is more a question than it is an issue. Suppose I have a script file that contains some functions in the `Begin` clause. However, the script has also some actions defined in the `Process` clause and some mandatory parameters in the `Parameters`.

Under normal circumstances I would move the functions to a module and test the module for proper functionality of the containing functions. But in this case, that's not possible. Because we need these functions to be in the script file. The script file will later be called with `Invoke-Command -FilePath Script.ps1 -ComputerName xxx` to run on remote machines where there's no module folder available. 

Consider the following example:

```powershell
Param (
    [Parameter(Mandatory)]
    [String]$Name
)

Begin {
    Function Test-NumberIsFive {
        Param (
            [Parameter(Mandatory)]
            [Int]$Number
        )

        if ($Number -eq 5) {
            $true
        }
    }
}

Process {
    (0..10).ForEach({ Test-NumberIsFive -Number $_ })
}
```

What is the best way to test the function `Test-NumberIsFive` without invoking the script?

**Comment by alexjordan6** [comment]
Hey, this is pretty similar to #247, want to give that read?

**Comment by nohwnd** [comment]
@DarkLite1 I wrote [this concept](https://github.com/nohwnd/script-tester) a while ago, maybe you can do something with it. Pretty much it just manipulates your script to have a main function so that your script is just functions, and then puts stuff back where it was. This way the script becomes testable for a moment, and then becomes shippable again.

**Comment by DarkLite1** [comment]
Thx guys I'll give it a go 👍

**Comment by DarkLite1** [comment]
It would be really cool if there was something like this:

Mock Test-NumberIsFive -InScriptScope

**Comment by dlwyatt** [comment]
Not possible, I'm afraid.  If there's no break between the code that loads the function and the code that calls it, Pester doesn't have any chance to inject mocks.

**Comment by dlwyatt** [comment]
That’s a good point. We used to create mock functions that would be overwritten when the script ran in your example, but now we use aliases instead.

**Comment by nohwnd** [comment]
@DarkLite1  @dlwyatt 😮 omg that's right... So that also means we can use it with `&` operator, as long as the aliases are not overwritten.

```powershell
# --- file t1.ps1 
param (
    [Parameter(Mandatory)]
    $name
)

function a {
    param ($name) 
    Write-Host "this is $name"
}

a $name

# --- file t1.tests.ps1
Describe "mock in script" {
    It "mocks a" {
        function a () {}
        mock a { Write-Host "this is mock" }
        # notice that I am invoking it with & here
        & "$psScriptRoot/t1.ps1" -name "jakub"

        Assert-MockCalled a -Exactly 1
    }
}

## output.ps1
# Describing mock in script
# this is mock
#  [+] mocks a 103ms
```

**Comment by nohwnd** [comment]
@DarkLite1  🎉 🍾 👍 Can you confirm it works? Tested only on PSCore on macOs.

```powershell
Add-Type -TypeDefinition @'
using System.Collections.ObjectModel;
using System.Management.Automation;
using System.Reflection;

namespace ScriptMocking
{
    [Cmdlet(VerbsData.Import, "Script")]
    public sealed class ImportScriptCommand : PSCmdlet
    {
        private static string Body = @"
            function ____placeholder {{ }}
            # alias to prevent main from running
            Set-Alias {0} '____placeholder'
            
            . {1} {2}
            # remove the alias, now we have all functions
            # from the script dot-sourced in this scope
            Remove-Item 'alias:{0}' -Force
            Remove-Item 'function:____placeholder' -Force";

        [Parameter(Position = 0, Mandatory = true)]
        public string Path { get; set; }

        [Parameter(Position = 1)]
        public string EntryPoint { get; set; } = "Main";

        [Parameter]
        public string[] ArgumentList { get; set; } = new string[0];

        protected override void ProcessRecord()
        {
            var body =  string.Format(Body, EntryPoint, Path, string.Join(" ", ArgumentList));

            var sb = InvokeCommand.NewScriptBlock(body);

            var method = sb.GetType()
                .GetMethod("InvokeUsingCmdlet", BindingFlags.Instance | BindingFlags.NonPublic);

            var emptyArray = new object[0];
            var automationNull = new PSObject();
            const int writeToCurrentErrorPipe = 1;

            var @params = new object[]
                {this, false, writeToCurrentErrorPipe, automationNull, emptyArray, automationNull, new object[0]};

            method.Invoke(sb, @params);
        }
    }
}
'@

Import-Module ([ScriptMocking.ImportScriptCommand].Assembly)
Import-Script -Path "$psScriptRoot/t1.ps1" -EntryPoint 'Main' -ArgumentList '-Name Jakub'

Describe "t1.ps1" {
    It "Can test 'Main' function" {
        Main -Name 'Pester' | Should -Be 'Hello, Pester!'
    }

    It "Can test 'Get-Greeting' function" {
        Get-Greeting -Name 'Pester' | Should -Be 'Hello, Pester!'
    }

    It "Can mock Get-GreetingText that is used by Get-GreetingFunction" {
        Mock Get-GreetingText { '{0} is getting better at mocking!'  }
        Get-Greeting -Name 'Pester' | Should -Be 'Pester is getting better at mocking!'
    }
}
```

**Comment by DarkLite1** [comment]
Hi @nohwnd , when I run your example in your second last post with file `t1.ps1` and file `t1.Tests.ps1` it is successful. However, When I try your last post and put it all in file `t1.Tests.ps1` (the part with `Add-Type`) it fails:

```powershell
[Add-Type : c:\Users\bgijbels\AppData\Local\Temp\39\cvdeisu1\cvdeisu1.0.cs(25) : Invalid token '=' 
in class, struct, or interface member declaration
c:\Users\bgijbels\AppData\Local\Temp\39\cvdeisu1\cvdeisu1.0.cs(24) :         [Parameter(Position =
 1)]
c:\Users\bgijbels\AppData\Local\Temp\39\cvdeisu1\cvdeisu1.0.cs(25) : >>>         public string Ent
ryPoint { get; set; } = "Main";
c:\Users\bgijbels\AppData\Local\Temp\39\cvdeisu1\cvdeisu1.0.cs(26) : 
At S:\Test\Brecht\Pester\t1.tests.ps1:1 char:1](url)
```
I think I might have misunderstood how you wanted me to test...

**Comment by nohwnd** [comment]
@DarkLite1 seem that PowerShell 5 supports only older C# syntax, fixed the code.

**Comment by DarkLite1** [comment]
Can you verify the edit you made? I only get red errors when copying the code starting with `using System.Collections.ObjectModel; ...` in the file `t1.tests.ps1`.

**Comment by DarkLite1** [comment]
No prob, works perfectly fine now. Thank you for your help :)
