### ISSUE TITLE
Tweaks to "Pester 3 -> 4 migration" wiki page

### ISSUE THREAD

**Issue by mikeclayton** [pester/Pester#1076]
Hi,

I've made a couple of micro-edits to the https://github.com/pester/Pester/wiki/Migrating-from-Pester-3-to-Pester-4 wiki page to fix some markdown (terminate powershell script section) and change "Be" to "-Be" in the New Syntax section.

See here for changes:

https://github.com/pester/Pester/wiki/Migrating-from-Pester-3-to-Pester-4/_compare/afca08324277f67868c8de580e83c03e1f1b0b63...ff718112905e1fc154f8d47f78b25d8f5d45c921

This ticket is just to raise visibility with the core dev team - please feel free to close it if the changes look ok, or revert them if it's wrong.

(Also, let me know if there's a better way to submit documentation changes for review before applying them to the wiki).

Cheers,

M

**Comment by it-praktyk** [comment]
Thank you @mikeclayton!
