### ISSUE TITLE
Why does the Pester file Coverage section contains one line multiple times?

### ISSUE THREAD

**Issue by BlackAngelTiger** [pester/Pester#1077]
Pester version         : 3.4.3 4.1.1 
PowerShell version : 5.0.10586.117
OS version              : Microsoft Windows NT 6.1.7601 Service Pack 1

Lets take this line of PowerShell Code:
```$hasFunktionName = (($command.PSObject.Properties.name -Contains "Function") -And -Not([String]::IsNullOrWhiteSpace($command.Function)))```

In the Pester file under Coverage there are the following entries (in this case hit):
```
{
    "File":  "D:\\Git\\DevOps\\powershell_report\\scripts\\data\\Add-CommandList.ps1",
    "Line":  41,
    "Function":  "Add-CommandList",
    "Command":  "$hasFunktionName = (($command.PSObject.Properties.name -Contains \"Function\") -And -Not([String]::IsNullOrWhiteSpace($command.Function)))"
},
{
    "File":  "D:\\Git\\DevOps\\powershell_report\\scripts\\data\\Add-CommandList.ps1",
    "Line":  41,
    "Function":  "Add-CommandList",
    "Command":  "($command.PSObject.Properties.name -Contains \"Function\") -And -Not([String]::IsNullOrWhiteSpace($command.Function))"
},
{
    "File":  "D:\\Git\\DevOps\\powershell_report\\scripts\\data\\Add-CommandList.ps1",
    "Line":  41,
    "Function":  "Add-CommandList",
    "Command":  "$command.PSObject.Properties.name -Contains \"Function\""
},
{
    "File":  "D:\\Git\\DevOps\\powershell_report\\scripts\\data\\Add-CommandList.ps1",
    "Line":  41,
    "Function":  "Add-CommandList",
    "Command":  "[String]::IsNullOrWhiteSpace($command.Function)"
}
```

Why do you split this in by () and one time the complete line?
Do you try to split this in branches there or does this splitting behavior ave different purposes?
If this would be the branches of the Line, we could possibly also calculate the branch coverage here and not only the execution coverage.

I am asking, because I am working on a PowerShell report i found and want to extend this so that we can see the Pester Test and Coverage information better and evaluate them for Quality purposes.

**Comment by nohwnd** [comment]
Code coverage is not line based, instead it looks for commands. I don't think there is any advanced detection of sub expressions on a line because there are too many edge cases (e.g. when you use an if or a while, part of the line might not execute.)
