### ISSUE TITLE
Pester Mock issue with Nested Modules

### ISSUE THREAD

**Issue by denys-voronovych** [pester/Pester#1082]
## 1. Provide a general summary of the issue in the Title above

While testing a function from a psm1 file in NestedModules of a big Module I cannot mock other similar functions used by it.

## 2. Describe Your Environment

Operating System, Pester version and PowerShell version:

Pester version     : 4.4.0 3.4.0 C:\Program Files\WindowsPowerShell\Modules\Pester\4.4.0\Pester.psd1 C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Pester.psd1
PowerShell version : 5.1.17134.165
OS version         : Microsoft Windows NT 10.0.17134.0

## 3. Example Source

https://github.com/denys-voronovych/PSPesterModuleIssue/tree/master/MyModule

Example test is in https://github.com/denys-voronovych/PSPesterModuleIssue/blob/master/MyModule/Test/MyTestFunction.Tests.ps1

## 4.Current Behavior

I'm trying to write tests for my module which is made of a regular module with a bunch of functions in psm1 files included as nested modules. When I write tests and try to mock a function, like shown in the example I get "CommandNotFoundException: Could not find Command Log-Info" error:
```
Executing all tests in '.'

Executing script C:\_scripts\MyModule\Test\MyTestFunction.Tests.ps1
Module Imported successfully!

  Describing Get-Lolz

    Context When the imput parameter is ' ' (Working)
      [+] returns string of numbers 96ms

    Context When the imput parameter is ' ' (Failing)
      [-] Error occurred in Context block 82ms
        CommandNotFoundException: Could not find Command Log-Info
        at Validate-Command, C:\Program Files\WindowsPowerShell\Modules\Pester\4.4.0\Functions\Mock.ps1: line 851
        at Mock, C:\Program Files\WindowsPowerShell\Modules\Pester\4.4.0\Functions\Mock.ps1: line 168
        at <ScriptBlock>, C:\_scripts\MyModule\Test\MyTestFunction.Tests.ps1: line 23
        at DescribeImpl, C:\Program Files\WindowsPowerShell\Modules\Pester\4.4.0\Functions\Describe.ps1: line 171
Tests completed in 179ms
Tests Passed: 1, Failed: 1, Skipped: 0, Pending: 0, Inconclusive: 0
```

Could you please help figure out what's going on?
Thank you!

**Comment by it-praktyk** [comment]
Please use [InModuleScope](https://github.com/pester/Pester/wiki/InModuleScope).

**Comment by denys-voronovych** [comment]
Tried that too. I've updated the code in the source and here's an output:
```
Executing all tests in '.'

Executing script C:\_git\PSPesterModuleIssue\MyModule\Test\MyTestFunction.Tests.ps1
C:\_git\PSPesterModuleIssue\MyModule\MyModule.psd1
If you want to see debug messages please use 'False = True'
Module Imported successfully!

  Describing Get-Lolz

    Context When the imput parameter is ' ' (Working)
      [+] returns string of numbers 1.03s

    Context When the imput parameter is ' ' (Failing)
      [-] Error occurred in Context block 202ms
        CommandNotFoundException: Could not find Command Log-Info
        at Validate-Command, C:\Program Files\WindowsPowerShell\Modules\Pester\4.4.0\Functions\Mock.ps1: line 851
        at Mock, C:\Program Files\WindowsPowerShell\Modules\Pester\4.4.0\Functions\Mock.ps1: line 168
        at <ScriptBlock>, C:\_git\PSPesterModuleIssue\MyModule\Test\MyTestFunction.Tests.ps1: line 24
        at DescribeImpl, C:\Program Files\WindowsPowerShell\Modules\Pester\4.4.0\Functions\Describe.ps1: line 171
Tests completed in 1.23s
Tests Passed: 1, Failed: 1, Skipped: 0, Pending: 0, Inconclusive: 0
```

**Comment by mikeclayton** [comment]
Hi @denys-voronovych,

I think the problem might be in your code - if I import your module into a new PowerShell command prompt and call your function I get a similar error:

```
PS C:\src\scratch\pester\issue-1082> import-module .\MyModule\MyModule.psd1
If you want to see debug messages please use '$global:DebugFlag = True'
...
PS C:\src\scratch\pester\issue-1082> Get-Lolz " "
...
Log-Info : The term 'Log-Info' is not recognized as the name of a cmdlet, function, script file, or operable program.
```

Looking at your repo, I think there's a typo in the "Log-Info.ps1" file - it's redefining the ```Log-Debug``` function rather than defining a new ```Log-Info``` function....

**[Log-Info.ps1](https://github.com/denys-voronovych/PSPesterModuleIssue/blob/master/MyModule/Log/Log-Info.psm1)**
```
function Log-Debug
...
```
So the error message from PowerShell and Pester is correct - there's no command called "Log-Info" defined in your module!

If you fix this typo the Pester tests get further, but fail with an exception thrown from inside your ```Get-Lolz``` function.

Cheers,

M

**Comment by denys-voronovych** [comment]
Hi Mike,
You're absolutely right, thanks for spotting it! I've changed the code and fixed function definition, my output now looks like:
```
If you want to see debug messages please use '$global:DebugFlag = True'                                                      
Module Imported successfully!                                                                                                
                                                                                                                             
  Describing Get-Lolz                                                                                                        
                                                                                                                             
    Context When the imput parameter is ' ' (Working)                                                                        
      [+] returns string of numbers 1.3s                                                                                     
                                                                                                                             
    Context When the imput parameter is ' ' (Failing)                                                                        
2018-07-27T12:40:58 DBG: Function Get-Lolz <start>                                                                           
2018-07-27T12:40:58 DBG: SomeString : ''                                                                                     
2018-07-27T12:40:58 INF: Doing something with ' '                                                                            
2018-07-27T12:40:58 INF: Doing something with ' '                                                                            
2018-07-27T12:40:58 DBG: 8361863748044471180170107680225586351331761358855627364861615481615731538817651138818727155431077671
2018-07-27T12:40:58 DBG: Function Get-Lolz <end>                                                                             
      [+] returns string of numbers 334ms                                                                                    
Tests completed in 1.64s                                                                                                     
Tests Passed: 2, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0                                                          
```
All is great, however the functions did not get mocked. Which is my problem.

(Again apologies for the code errors, I was trying to recreate an example module of what we have at work and due to security reasons I could not copy-paste)

Thank you!

**Comment by mikeclayton** [comment]
@denys-voronovych - I was able to reproduce the same behaviour using your updated repo. I also tried various combinations of ```InModuleScope``` and ```Mock -ModuleName "MyModule" / "Log-Info" -CommandName "..."``` but wasn't able get the mocks to execute either.

What I *did* get to work was renaming the *.psm1 files in the "Log", "Test" and "Utility" subfolders to *.ps1, (and the filenames in the MyModule.psd1). This seems to change how PowerShell imports the nested modules and affects how Pester hooks into the functions, but I'm not sure if I'm missing something, or if it's a bug in Pester or a limitation in PowerShell.

If you're able to use *.ps1 files instead of *.psm1 files in your subfolders it might let you work around the issue regardless of what's causing it.

**Comment by mikeclayton** [comment]
Digging a bit further, it looks like the NestedModules export their commands if you use *.psm1, but *not* if you use *.ps1 files. I'm wondering if this is what is causes the difference in behaviour with nested *.psm1 files?

**NestedModules using \*.psm1 files**

``` powershell
PS> import-module .\MyModule\MyModule.psd1

PS> (get-module mymodule).ExportedCommands

Key               Value
---               -----
Format-LogMessage Format-LogMessage
Get-Lolz          Get-Lolz
Log-Debug         Log-Debug
Log-Error         Log-Error
Log-Info          Log-Info
Out-DebugVariable Out-DebugVariable
Write-Log         Write-Log

PS C:\src\scratch\pester\issue-1082> (get-module mymodule).NestedModules

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        Format-LogMessage                   Format-LogMessage
Script     0.0        Log-Debug                           Log-Debug
Script     0.0        Log-Error                           Log-Error
Script     0.0        Log-Info                            Log-Info
Script     0.0        Write-Log                           Write-Log
Script     0.0        MyTestFunction                      Get-Lolz
Script     0.0        Out-DebugVariable                   Out-DebugVariable
```

**NestedModules using \*.ps1 files**

``` powershell
PS> import-module .\MyModule\MyModule.psd1

PS> (get-module mymodule).ExportedCommands

Key               Value
---               -----
Format-LogMessage Format-LogMessage
Get-Lolz          Get-Lolz
Log-Debug         Log-Debug
Log-Error         Log-Error
Log-Info          Log-Info
Out-DebugVariable Out-DebugVariable
Write-Log         Write-Log


PS> (get-module mymodule).NestedModules

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        Format-LogMessage
Script     0.0        Log-Debug
Script     0.0        Log-Error
Script     0.0        Log-Info
Script     0.0        Write-Log
Script     0.0        MyTestFunction
Script     0.0        Out-DebugVariable
```

**Comment by mikeclayton** [comment]
Having re-read it-praktyk's post, you can also just do this in your "TestFunction.Tests.ps1":

```InModuleScope "MyTestFunction" {```

That's the scope you want the Mock to take effect in.

**Comment by denys-voronovych** [comment]
@mikeclayton This is great! Thank you very much! I'll use the last solution and will keep in mind reworking the module into using ps1 instead of psm1.
