### ISSUE TITLE
Result attribute of Test-Suite element in Nunit output should be 'Failed' instead of 'Failure' for failed tests

### ISSUE THREAD

**Issue by tehsuk** [pester/Pester#1083]
## 2. Describe Your Environment

Operating System, Pester version and PowerShell version:

Pester version     :  4.4.0
PowerShell version : 5.1.14409.1012
OS version         : Microsoft Windows NT 6.1.7601 Service Pack 1

## 3. Expected Behavior
Based on https://github.com/nunit/docs/wiki/Test-Result-XML-Format , Nunit formatted  XML output should have result="Failed" for test-suite element for failed tests.

## 4.Current Behavior

Nunit output has result="Failure" for test-suite element for failed tests.

```XML
<test-suite type="TestFixture" name="test name" executed="True" result="Failure" success="False" time="44.9173" asserts="0" description="Local User: ProgAdminUser">
```

## 5. Possible Solution

Change XML to return 'Failed' instead of 'Failure'

## 6. Context

I am importing Nunit-formatted XML files generated by Pester into the Xray plugin for Jira.  Failed tests are showing up as 'ToDo' instead of 'Failed' because of the incorrect failure string that Pester is generating.

If i replace all instances of ```result="Failure"``` with ```result="Failed"``` in the pester-generated nunit xml, the tests show up properly flagged as failed.

**Comment by it-praktyk** [comment]
@tehsuk, thank you for the report. Please test the updated code - PR #1085.

**Comment by nohwnd** [comment]
My problem with this is that you are referencing nunit 3.0 documentation and we are using nunit 2.5 schema. And even the linked documentation fails to be consistent with the naming (see [result and label](https://github.com/nunit/docs/wiki/Test-Result-XML-Format#test-suite)): 

result  The basic result of the test. May be Passed, **Failed**, Inconclusive or Skipped.
label ... Currently, NUnit may use the following labels in combination with the **Failure result**: Error, Cancelled or Invalid. <- here they refer to Failure result, but no such result is present in the list of possible results.


I cannot find a description of how the correct output should look like in 2.5. (Can you help me find it?) And our output is correctly validated against the official nunit 2.5 xml schema, so I would be careful changing it to accomodate a single plugin.

**Comment by nohwnd** [comment]
Maybe you can just ask in their repository, and we can keep this open till then.

**Comment by nohwnd** [comment]
Should be solved in related issue. Closing this. Thanks for the anlysis.
