### ISSUE TITLE
NUnit 3.0 Support

### ISSUE THREAD

**Issue by rdbartram** [pester/Pester#1087]
## 1. Description
I would like to bring in support for NUnit 3.0 among other reasons, I just wrote the whole thing to extend the Export-NUnitReport cmdlet to include properties and output fields. I noticed after writing that that we are currently NUnit 2.5 compliant and that means I can't include the output property

## 3. Expected Behavior
should be able to export NUnit 3.0 report

## 4.Current Behavior
Only exports NUnit 2.5

## 5. Possible Solution
I can rewrite the testresults.ps1 to either replace support for 2.5 with 3.0 or we provide a parameter somewhere for the user to choose. 

Have a solution in mind?

https://github.com/rdbartram/pester/

## 6. Context

After the test file has been uploaded in VSTS it is easier troubleshoot when more information is saved in the test file.

**Comment by nohwnd** [comment]
That would be nice. The [OutputFormat](https://github.com/pester/Pester/blob/055bb3e4cfe20a165300f12b882807a35e3f286a/Pester.psm1#L789) allows the user to choose the output format, to be used, please add `NUnitXML30` and implement your changes.

**Comment by rdbartram** [comment]
Understood. I'll start working on it

**Comment by nohwnd** [comment]
@rdbartram Are you still interested in doing this?

**Comment by nohwnd** [comment]
Related #301

**Comment by nohwnd** [comment]
This migration should also address the problem raised in #1083 , should the fail be reported with `Failed` or `Failure`?

**Comment by rdbartram** [comment]
I had this as part of my TestCase Output PR but then removed it for separation of concern. As soon as I get the other PR in and I know that I can get a PR into pester, I'll create the next one. The code is still on my machine working internally

**Comment by nohwnd** [comment]
@rdbartram it's still unclear to me how to do the testcases properly, that's why it's still not merged. If you already have the code for this issue, could you PR that? /cc @davinci26
