### ISSUE TITLE
Add video link to Wiki resources

### ISSUE THREAD

**Issue by tmack8080** [pester/Pester#1092]
Microsoft Channel 9 has a great video course with Adam Bertram: Testing PowerShell with Pester

https://mva.microsoft.com/en-US/training-courses/17650?l=mg8oBM9vD_8811787177

**Comment by it-praktyk** [comment]
I've added the proposed link to the wiki article [Articles and other resources](https://github.com/pester/Pester/wiki/Articles-and-other-resources).
