### ISSUE TITLE
Should -Exist fails when mocking a function that is called multiple times and results in different output

### ISSUE THREAD

**Issue by KyleMartin901** [pester/Pester#1094]
## 1. Provide a general summary of the issue in the Title above

When I use the Should -Exist feature on a function that calls a mocked function twice within the function and each time that mocked function returns a different output, the test fails.

## 2. Describe Your Environment

Operating System, Pester version and PowerShell version:

```powershell
Pester version     : 4.4.0 /usr/local/share/powershell/Modules/Pester/4.4.0/Pester.psd1
PowerShell version : 6.0.4
OS version         : Unix 17.7.0.0
```

## 3. Expected Behaviour
I am writing an API wrapper module and in this module I have a function that downloads a file from a website. I have created a wrapper function around  Invoke-RestMethod so it sets up all the common variables related to my module. 

In my download file function there is an option to accept the license of the downloaded file, when the accept licenses option is enabled it calls the wrapper function with a POST request and returns nothing. It then proceeds to call the wrapper function again this time with a GET request and returns the file to download.

I have created an example pester test setup to demonstrate the issue bellow.

```powershell
function httpRequest {
  return
}

function acceptLicense {
  httpRequest
}

function fileDownload {
  param (
    [Parameter(Mandatory = $true,
      ValueFromPipelineByPropertyName = $true,
      HelpMessage = "The full path to save the file includes the file name with no extension. Eg C:\directory\file")]
    [string]$DownloadPath,

    [Parameter(Mandatory = $false)]
    [switch]$AcceptLicense
  )

  if ($AcceptLicense) {
    acceptLicense
  }

  httpRequest | New-Item -Path $DownloadPath -ItemType File -Force
  
}

Describe 'fileDownload - UnitTest' -Tag UnitTest {
  Context '1 mock call' {
    Mock -CommandName httpRequest -MockWith { 'file contents' }
    $param = @{ 
      "DownloadPath" = (Join-Path $TestDrive -ChildPath 'filename')
    }

    It 'Downloads requested file' {
      fileDownload @param | Should -Exist
    }
  } # Context '1 mock calls'

  Context '2 mock calls' {
    Mock -CommandName httpRequest -MockWith { 'file contents' }
    $param = @{ 
      "DownloadPath" = (Join-Path $TestDrive -ChildPath 'filename');
      "Option" = $true;
    }

    It 'Downloads requested file' {
      fileDownload @param | Should -Exist
    }
  } # Context '2 mock calls'
```

I would expect for both tests to pass as a file download is returned in both cases.

## 4.Current Behaviour

When I run the above code I get an error on the test where the Mocked function is called twice.

```powershell
Describing testShould - UnitTest

  Context 1 mock call
    [+] Downloads requested file 144ms

  Context 2 mock calls
    [-] Downloads requested file 129ms
      Expected path 'file contents' to exist, but it did not exist.
      48:       fileDownload @param | Should -Exist

```

The 2 mock call test fails because the should is expecting the first call to the httpRequest wrapper to produce a downloaded file rather than return nothing. I would of thought that it would only test the final returned value of the fileDownload function should exist.

When I inspect what is being returned when I call `fileDownload @param` within the `It` block, it is returning an array of objects. The first object in the array being the return from the `acceptLicense` method call and the second from the `httpRequest | New-Item -Path $DownloadPath -ItemType File -Force`.

When I run the same code out side of Pester it only returns the output from `httpRequest | New-Item -Path $DownloadPath -ItemType File -Force`

**Comment by mikeclayton** [comment]
I think the issue is that your ```fileDownload``` function is not capturing or suppressing the return value from ```acceptLicense``` when it gets called, so it's being returned as part of the output from fileDownload.

For example, if you eliminate pester from your example and just run the following you'll see your function **is** actually returning an array of two objects:

```
function httpRequest {
  return "file content"
}

function acceptLicense {
  httpRequest
}

function fileDownload {
  param (
    [string]$DownloadPath,
    [switch]$AcceptLicense
  )
  if ($AcceptLicense) {
    acceptLicense
  }
  httpRequest | New-Item -Path $DownloadPath -ItemType File -Force
}

$result = fileDownload -DownloadPath "aaa" -AcceptLicense

write-host ("result type     = " + $result.GetType().FullName)
write-host ("result length   = " + $result.Length)
write-host ("result[0] type  = " + $result[0].GetType().FullName)
write-host ("result[0] value = " + $result[0])
write-host ("result[1] type  = " + $result[1].GetType().FullName)
write-host ("result[1] value = " + $result[1])
```

On my (Windows) machine I get this output:

```
c:\src\scratch\pester\issue-1094>powershell .\My.Tests.ps1
result type     = System.Object[]
result length   = 2
result[0] type  = System.String
result[0] value = file content
result[1] type  = System.IO.FileInfo
result[1] value = C:\src\scratch\pester\issue-1094\aaa
```

So in your pester tests, you're basically asking "Should -Exist" to confirm that both items exist, which explains the ```Expected path 'file contents' to exist, but it did not exist.``` error you're seeing.

What you need to do is "capture" the return value from acceptLicense so it doesn't leak out of fileDownload...

```powershell
$myTempVar = acceptLicense
```
or
```powershell
$null = acceptLicense
```
or
```powershell
acceptLicense | Out-Null
```

or maybe capture the return value from httpRequest in acceptLicense instead

```
function acceptLicense {
  $null = httpRequest
}
```

Hope this helps.

M

**Comment by KyleMartin901** [comment]
Thanks Mike,

Thought it would be my mistake :( 

Thanks for showing me how to fix it, it is greatly appreciated and sorry for the inconvenience.
