### ISSUE TITLE
Is there a way to run particular block of code only if describe passed?

### ISSUE THREAD

**Issue by SamPosh** [pester/Pester#1096]
## 1. Provide a general summary of the issue in the Title above

I would like to run a block of code ,if describe section succeeded without any failure. Is there any option available?

## 2. Describe Your Environment

Operating System, Pester version and PowerShell version:

Pester version     : 4.0.8 4.3.1 4.0.8 C:\Users\Administrator\Documents\WindowsPowerShell\Modules\Pester\4.0.8\Pester.psd1 C:\Program Files\WindowsPowerShell\Modules\Pester\4.3.1\Pester.psd1 C:\Program Files\WindowsPowerShell\Modules\Pester\4.0.8\Pester.psd1
PowerShell version : 5.1.14409.1012
OS version         : Microsoft Windows NT 6.3.9600.0

## 3. Possible Solution

if there is an option to run a code block on Describe -onSuccess { } and -OnFailure { }  then it can be good.

## 4. Context

I am trying to add pester test cases in our organization existing framework. The framework has function to call in case of success. But in Pester , I don't know how to achieve it.

**Comment by it-praktyk** [comment]
Please run your test with the `-EnableExit` parameter and check and output.

**Comment by SamPosh** [comment]
@it-praktyk I am running with -EnableExit ,but the problem is , i am running all the scripts in my folder and getting a result for each describe is very tough

**Comment by it-praktyk** [comment]
@SamPosh,
you can run `Invoke-Pester -Path <one_file_file> -EnableExit` or use the parameter `PassThru` and parse the PowerShell object returned.

**Comment by SamPosh** [comment]
@it-praktyk  Or is there a way to add Describe inside try {} catch{} and if error occurs can we redirect it to catch block? is it possible?

**Comment by johlju** [comment]
It is possible to catch an error in the error variable for the It-block. Maybe you can rig that up on a describe or context block too? Or you could count errors on the it-blocks and then do something with it (like a “onSuccess”) ? 

https://github.com/PowerShell/SqlServerDsc/blob/f72dd2c40ffb43782a5969b3a51803ccf2c027f1/Tests/Integration/MSFT_SqlSetup.Integration.Tests.ps1#L388

**Comment by nohwnd** [comment]
@SamPosh if you need more help please re-open this issue.
