### ISSUE TITLE
Can Pester run all Arrange first, then a single "shared" Act, then run all the Asserts?

### ISSUE THREAD

**Issue by o-o00o-o** [pester/Pester#1099]
Hi guys, we have a data warehouse/BI solution and ultimately we would like to write gherkin style tests for it. 

We essentially need to be able to batch up all the GIVEN's to be run once all together (to populate the data in the database), then run our ETL and Cube process (which will take some time so we only want to run it once for all tests), then run all the asserts then for each WHEN/THEN combination for these to be run 

Is there any way for us to do this using Pester? 

In detail I would like a test to look something like 

```
Background: 
    Given the following Customers in the DW 
      | Customer Code | Primary Village | 
      | BV-A          | BV              | 
      | BV-B          | BV              | 
      | BV-C          | BV              | 
      | FV-D          | FV              | 
      | FV-E          | FV              | 
     
    And the following Tracked Sales in the DW  
      | Customer Code | Dates      | Lease Code | Sales | 
      | BV-A          | 01/01/2018 | BV-Gucci   | 100   | 
      | BV-B          | 01/01/2018 | BV-Gucci   | 200   | 
      | BV-B          | 01/02/2018 | BV-Gucci   | 200   | 
      | BV-B          | 01/03/2018 | BV-Gucci   | 200   | 
      | BV-B          | 01/05/2018 | BV-Gucci   | 100   | 
      | BV-B          | 01/10/2018 | BV-Gucci   | 300   | 
      | BV-B          | 01/12/2018 | BV-Gucci   | 300   | 
      | BV-C          | 01/01/2018 | BV-Gucci   | 300   | 
      | BV-C          | 01/10/2018 | BV-Gucci   | 0     | 
      | FV-D          | 01/02/2018 | BV-Gucci   | 300   | 
      | FV-D          | 01/11/2018 | BV-Gucci   | 200   | 
       
Scenario: [Visit Band Tracked Sales Net] for a year 
    When I set a filter of Year = 2018  
    Then Cube results are 
      | Customer Code | Tracked Footfall | Tracked Sales Net | 
      | BV-A          | 1                | 100               | 
      | BV-B          | 6                | 1300              | 
      | BV-C          | 2                | 300               | 
      | FV-D          | 2                | 500               | 
    And Cube results are 
      | Visit Band | Visit Band Tracked Sales Net | 
      | 1          |   100                        | 
      | 2-5        |   800                        | 
      | >=6        | 1,300                        |

```
You'll notice that the ACT part (ETL and Cube processing execution ) is not explicitly mentioned and that is because I guess it will be implicit in these kinds of tests and is only getting run once for *all* tests.

I'm sorry that I haven't done much digging myself on this yet but I guess that this is probably an advanced usage scenario and so thought someone probably has the "Yes/No/Perhaps look at X/Y/X" answer to help me move forward on this.

Thanks in advance!

**Comment by nohwnd** [comment]
@fourpastmidnight Could you have a look please?

**Comment by fourpastmidnight** [comment]
What you're attempting to do using the Gherkin language is not in the spirit of Behavioral Driven Design, and is therefore not possible. But please read on before giving up.

The Gherkin language is a Domain Specific Language which aims to provide an idiomatic way of expressing the given state of a system, an action taken against the system, and the behavior of the system in response to the action, expressed in a Given, When, Then syntax.

Many times when testing software, you will want to test several "examples" of inputs, especially when testing the boundary conditions of methods and functions. This is one of the usages behind supplying tables for step definitions. In this sense, each row in the table becomes a test case representing an input or an expected output. If you're familiar with NUnit, think of a step definition table row as a synonym for the `[TestCase]` attribute, with each column of the row representing an argument (or expected output) to the test.

In other cases, tables for step definitions can simply be used as a way to provide multiple inputs or outputs for a given test case.

I think you may get better mileage out of your tests by reformulating them, for example:

```gherkin
Background: The data warehouse contains customer and tracked sales historical data

  Given the data warehouse contains historical customer data
  And the data warehouse contains historical tracked sales data

Scenario: The data warehouse can show tracked sales by customer by year
  # Using a table on this step, you can provide "multiple inputs" which can be used
  # to build up your MDX cube query
  Given the dimensions
    | Dimension    |
    | CustomerCode |
    | Year         |
  # It seemed to make sense to me to use one step for the dimensions
  # of the query and another for the measures
  And the measures
    | Measure           |
    | Tracked Footfall  |
    | Tracked Sales Net |
  # This when step is still an action--you're filtering the cube.
  # If you didn't perform this "action", you would return the
  # entire cube!
  When the results are filtered by 'Year'
  And the filter value is '2018'
  # After executing your query (generated from the Given and When steps), the table in
  # this step details the results you should obtain for each customer code.
  Then the following tracked sales net by customer by year results should be returned
    | CustomerCode  | Tracked Footfall | Tracked Sales Net |
    | BV-A          | 1                | 100               | 
    | BV-B          | 6                | 1300              | 
    | BV-C          | 2                | 300               | 
    | FV-D          | 2                | 500               |

Scenario: The data warehouse can show tracked sales by visit band by year
  Given the dimensions
    | Dimension  |
    | Visit Band |
  And the measures
    | Masure                       |
    | Visit Band Tracked Sales Net |
  When the results are filtered by 'Year'
  And the filter value is '2018'
  Then the following tracked sales net by visit band by year should be returned
    | Visit Band | Visit Band Tracked Sales Net | 
    | 1          |   100                        | 
    | 2-5        |   800                        | 
    | >=6        | 1,300                        |
```

This is much more declarative and in the spirit of BDD tests. The Background step definitions is where you would "pre-load" all of your data for each of your scenarios. In the scenarios, the given steps are specifying the various dimensions and measures to be queried from the data warehouse cube, the when step allows you to specify any filtering criteria (or perhaps allows you to specify other dimensions or measures for further slicing the (hyper)cube?), and the then steps still use a table, where each row of the table becomes an assertion against the results obtained from querying the cube. You'd basically assert that the results contained a record for each row in the table with the expected data.

Depending on who the audience is for reading the feature files, you may want to use language that is less data warehouse specific and more business oriented (what reports are the endusers/stakeholders interested in, or KPIs, etc.).
