### ISSUE TITLE
Feature request: Summary at the end

### ISSUE THREAD

**Issue by DarkLite1** [pester/Pester#1102]
## 1. Summary result at the end

Would it be possible to have a summary with how many tests were successful or failed when the test file is run? I know this is shown in the powershell console but not when run in the `PowerShell ISE` or 'VS Code`. 

This would really be helpful, when pressing F5 and the script is executed to see at the bottom the end result. It might be that we're not watching during all tests to see if a red line pops-up.

![image](https://user-images.githubusercontent.com/10828570/45679196-6b720f80-bb38-11e8-95fa-18eb1a0527d8.png)

Thank you for having a look at this.

**Comment by nohwnd** [comment]
Problem is that we don't know which describe is the last one, and hence the one that should print the summary. 😒

**Comment by nohwnd** [comment]
It boils down to this kind of problem:
```powershell
$script:count = 0

function desc ($Name, $ScriptBlock) {
    Write-Host $Name
    $script:count++
    &$ScriptBlock

    # how to implement this condition
    # to only run in the last desc block?
    if (??????) {
        summary
    }  
}

function summary { "desc run $script:count times" }

desc "stands for describe" { 
    desc "runs inside" {
        desc "runs one level deeper" { }
    }

    desc "is everywhere" { }
}
```

**Comment by SeeminglyScience** [comment]
Here's a possibly.  As is it won't catch everything and can probably be optimized a bit, but it gives the general idea.

```powershell
$script:count = 0

function desc ($Name, $ScriptBlock) {
    Write-Host $Name
    $script:count++
    &$ScriptBlock

    # how to implement this condition
    # to only run in the last desc block?

    # Get the root AST of the supplied ScriptBlock
    $root = $ScriptBlock.Ast
    for (; $null -ne $root.Parent; $root = $root.Parent) { }

    # Iterate statements looking for a describe block
    $statements = $root.EndBlock.Statements
    for ($i = $statements.Count - 1; $i -gt -1; $i--) {
        # Skip statements that aren't pipeline elements containing a command AST
        if ($statements[$i].PipelineElements[0] -isnot [System.Management.Automation.Language.CommandAst]) {
            continue
        }

        # This check would need to be expanded to look for aliases of Describe
        if ($statements[$i].PipelineElements[0].GetCommandName() -ne $MyInvocation.InvocationName) {
            continue
        }
        
        # If the last statement calls this command, check if it's script block matches ours.
        foreach ($element in $statements[$i].PipelineElements[0].CommandElements) {
            if ($element.StaticType -eq [scriptblock] -and $element.ScriptBlock -eq $ScriptBlock.Ast) {
                summary
                return
            }
        }

        return
    }
}

function summary { "desc run $script:count times" }

desc "stands for describe" { 
    desc "runs inside" {
        desc "runs one level deeper" { }
    }

    desc "is everywhere" { }
}

desc "there can be multiple desc blocks in one file" {

}
```

```raw
stands for describe
runs inside
runs one level deeper
is everywhere
there can be multiple desc blocks in one file
desc run 5 times
```

**Comment by saladproblems** [comment]
Does using PassThru not effectively do this already?

**Comment by nohwnd** [comment]
@saladproblems `-PassThru` is a parameter of `Invoke-Pester` when you run in what we call interactive mode (simply pressing F5 in a file, or running the code directly in console), you are not running via `Invoke-Pester` and so you cannot specify this parameter. But the parameter is not a problem. Knowing which describe is the last, so it should print the describe, is the problem.

**Comment by fflaten** [comment]
Not planned for Pester v4, but this type of summary is available in Pester v5. Default output will show something like the image below. This includes when invoking using F5 in VSCode and using "Run Tests" codelens-links.
![image](https://user-images.githubusercontent.com/3436158/118729170-bbe42280-b835-11eb-8ed8-3a32a118dfee.png)
