### ISSUE TITLE
Link to "PowerShell 3 and 4 install instructions" redirects to a 404 error page

### ISSUE THREAD

**Issue by alaeddinejebali** [pester/Pester#1104]
##  Broken link (404 Error)
In this [wiki page](https://github.com/pester/Pester/wiki/Installation-and-Update), in the `PowerShell 3 and 4` section, a click on `instructions here` open the page [https://docs.microsoft.com/en-us/powershell/gallery/how-to/getting-support/health-status](https://docs.microsoft.com/en-us/powershell/gallery/how-to/getting-support/health-status) which shows a **404 - Page not found** page.

**Comment by mikeclayton** [comment]
The broken link points to:

https://docs.microsoft.com/en-us/powershell/gallery/psget/get_psget_module

It looks like it might have moved to here:

https://docs.microsoft.com/en-us/powershell/gallery/installing-psget#get-powershellget-module-for-powershell-versions-30-and-40

**Comment by nohwnd** [comment]
Thanks, fixed.
