### ISSUE TITLE
Code Formatting - Style Guide/Settings for VSCode

### ISSUE THREAD

**Issue by andikrueger** [pester/Pester#1110]
Yesterday I browsed through the pester code to understand it more deeply and help with issue #402, as it would help me to write simplified tests for a project I'm working on.
I'm working a lot with DSC Resources and am using VSCode to write my code. Many DSC projects use a vscode settings file (based on the [style guideline](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)) to ensure code formatting. It would be great to add this settings file for Pester too: [VSCode Settings for DSC Repoistories](https://github.com/PowerShell/DscResources/blob/master/DscResource.Template/.vscode/settings.json)

What's your opinion?

**Comment by fflaten** [comment]
Really agree. I've added my own locally to try an avoid errors as trailing whitespace. There are tests for it in `Pester.Tests.ps1`, so making it automatic would just help everyone pass it.

**Comment by nohwnd** [comment]
@andikrueger interesting that they don't enable new-line after opening brace even though it is in their styleguide. 

```
if { "abc" }
```
 then becomes 
```
if 
{ "abc"
}
```

In Pester I would remove the PSScriptAnalyzer setting, add tab size 4 and enable format on save. What do you think?

**Comment by nohwnd** [comment]
Should probably just use the preset. Now the question is Stroustrup or Allman? I'd vote for Stroustrup because that is how I normally write my code, and it makes for shorter files. 

```json
{
  "powershell.codeFormatting.preset": "Stroustrup",

  "files.trimTrailingWhitespace": true,
  "files.insertFinalNewline": true,

  "editor.tabSize": 4,
  "editor.formatOnSave": true
}
```

**Comment by andikrueger** [comment]
@nohwnd  maybe we should change the following setting  from this:
```
powershell.codeFormatting.newLineAfterOpenBrace": false,
```
to this:
```
powershell.codeFormatting.newLineAfterOpenBrace": true,
```
This would fix the issue you mentioned.

**Comment by nohwnd** [comment]
@andikrueger  I did, see my comments above. I think I edited if after you read it. I will probably go with the preset anyway. Which one do you vote for?

**Comment by fflaten** [comment]
Since I've already commented on this, I'll add a vote for my favorite, Stroustrup, which Jakub already has open PR for :)
