### ISSUE TITLE
Weird behaviour in Mocks in functions outside It 

### ISSUE THREAD

**Issue by richardnagle** [pester/Pester#1117]
## 1. General summary of the issue

We are trying to extract duplicated mock set-ups into external functions. But we have found that the mock cannot use parameter or variable values defined within that function. The following test better describes this issue:

```powershell
Describe "Something" {
    function MockItWithVariable{
        $a="foobar"
        Mock Get-Content {return $a}
    }

    function MockItWithoutVariable{
        Mock Get-Content {return "foobar"}
    }

    It "Variable in scope of It passes" {
        $a="foobar"
        Mock Get-Content {return $a}
        Get-Content "C:\temp.txt" | Should -Be "foobar"
    }

    It "Function without variable passes" {
        MockItWithoutVariable
        Get-Content "C:\temp.txt" | Should -Be "foobar"
    }

    It "Function with variable fails (should IMO pass)" {
        MockItWithVariable
        Get-Content "C:\temp.txt" | Should -Be "foobar"
    }
}
```

## 2. Describe Your Environment

Pester version : 4.4.0 3.4.0 3.3.5 C:\Program Files\WindowsPowerShell\Modules\Pester\4.4.0\Pester.psd1 C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Pester.psd1 C:\Program Files\WindowsPowerShell\Modules\Pester\3.3.5\Pester.psd1
PowerShell version : 5.1.15063.1292
OS version : Microsoft Windows NT 10.0.15063.0

**Comment by dlwyatt** [comment]
It'll work if you do it like this:

```posh
    function MockItWithVariable{
        $a="foobar"
        Mock Get-Content {return $a}.GetNewClosure()
    }
```

**Comment by richardnagle** [comment]
That fixed it thanks.
