### ISSUE TITLE
Should broken in Mocks?

### ISSUE THREAD

**Issue by scorpionlion** [pester/Pester#1118]
## 1. General summary of the issue

"Should" assertion not working correctly inside parameter filter of Mock assertion.
I am using 4.3.1 version of Pester.

## 2. Describe Your Environment

```
Describe "Write-host-test" {
    It "Outputs correctly formatted message" {
        # Arrange
        $expectedText = "test message"
        Mock Write-Host 
        
        # Act
        Write-Host $expectedText
        # Assert
        Assert-MockCalled Write-Host -Times 1 -ParameterFilter{$true | Should -Be $true} 
       
    }
}
```

## 3. Expected Behavior

the test should pass

## 4.Current Behavior

the test fails, whereas below test works 

```
Describe "Write-host-test" {
    It "Outputs correctly formatted message" {
        # Arrange
        $expectedText = "test message"
        Mock Write-Host 
        
        # Act
        Write-Host $expectedText
        # Assert
        Assert-MockCalled Write-Host -Times 1 -ParameterFilter{$true -eq $true} 
        
    }
}
```

## 5. Possible Solution

No idea yet

## 6. Context

my existing tests are broken

**Comment by dlwyatt** [comment]
You shouldn't be using `Should` there.  Its purpose is to do nothing when the assertion passes, and to throw an exception when it fails (which is what the `It` command treats as its success / failure conditions).  `-ParameterFilter`, on the other hand, wants you to return `$true` or `$false`.

**Comment by dlwyatt** [comment]
I have no idea why that worked in 3.4.  It was never a supported way of doing the parameter filters, sorry.

**Comment by scorpionlion** [comment]
Seems Assertion functions did return `$true` in 3.4, they are changed now. - I looked at both version scripts.
Now I just worked around by wrapping it with an or with `$true`

like this (`$Object | Should -Be $expectedText ) -or $true`

**Comment by nohwnd** [comment]
> Seems Assertion functions did return $true in 3.4, they are changed now.
Yes, that is correct, there was a similar issue discussed in another thread. I cannot find it sadly.

Why do you need to use assertions in the parameter filter? a simple comparison (with `-eq` or `-like`) would work.

**Comment by scorpionlion** [comment]
Actually it's just a pattern of choice to test the behaviour of underlying functions.  I use this pattern to make sure that my functions are behaving and passing correct values to mocked functions. If I just use the equality check, then I don't get the failure in a very helpful way should explains - like where the values are different etc. which speeds up fixing my functions. 

I use equality where I am just stubbing.

**Comment by scorpionlion** [comment]
exactly - it makes easier to debug - in c#  unit tests I used Rhino Mocks and general Assertions  in parameter checking - then returned `true`  in the last explicitly.  I was happy to see that 3.4  `Should ` was returning the bool itself... but it did not last long!

**Comment by nohwnd** [comment]
Related to #1160 , we most likely won't support running Should in the filters. Let's continue the discussion in  a single issue #1160
