### ISSUE TITLE
Single-Column Tables don't appear to be parsed correctly when working with Gherkin style tests

### ISSUE THREAD

**Issue by fourpastmidnight** [pester/Pester#1119]
## 1. General summary of the issue

Using a table with a step results in an `ArgumentException` when attempting to add items to the dictionary.

Here are the relevant file samples:

```gherkin
Scenario: The hashtable must contain values for the properties Property1, Property2 and Property3

    Given the hashtable has the following keys:
        | PropertyName |
        | Property1    |
        | Property2    |
        | Property3    |
    Then the properties must not be null or the empty string
```

```powershell
Given "the hashtable has the following keys:?" {
    Param($table)

    # You don't have to actually do anything here...
    # An exception will be thrown
}
```

The exception that is thrown is:

```
    [-] Given the hashtable has the following keys:
      ArgumentException: Item has already been added. Key in dictionary: 'r'  Key being added: 'r'
      MethodInvocationExcepction: Exception calling "Add" with "2" argument(s): "Item has already been added. Key in dictionary: 'r'  Key being added: 'r'"
      at ConvertTo-HashTableArray<Process>, C:\Program Files\WindowsPowerShell\Modules\Pester\4.4.2\Functions\Gherkin.ps1: line840
      at Get-StepParameters, C:\Program Files\WindowsPowerShell\Modules\Pester\4.4.2\Gherkin.ps1: line 780
    [+] Then the properties must not be null or the empty string
```

## 2. Describe Your Environment

Pester version     : 4.4.2 C:\Program Files\WindowsPowerShell\Modules\Pester\4.4.2\Pester.psd1
PowerShell version : 5.1.17134.165
OS version         : Microsoft Windows NT 10.0.17134.0

## 3. Expected Behavior

I expected that the table rows would be added to the `$table` hashtable.

## 4.Current Behavior

It appears from the errors that `Gherkin.ps1` is attempting to add data to the table using a duplicate key. Further investigation reveals that the issue is a bit stranger. I attempted the following:

```gherkin
Given the following keys exist in the dictionary:
    | Key  |
    | Key1 |
    | Key2 |
    | Key3 |
```

This worked without issue. Then I tried the next simplest thing closest to the example above:

```gherkin
Given the following keys exist in the dictionary:
    | PropertyName |
    | Key1         |
    | Key2         |
    | Key3         |
```

Again, this resulted in an error, as I expected--but still didn't know quite why. So, I tried the next simplest thing:

```gherkin
GIven the following keys exist in the dictionary:
    | Property |
    | Key1     |
    | Key2     |
    | Key3     |
```

This also threw the same exception. Finally, one more test to confirm my hypothesis:

```gherkin
Given the following keys exist in the dictionary:
    | Prop |
    | Key1 |
    | Key2 |
    | Key3 |
```

This did not result in the exception. Lastly, how much of the word _Property_ is required to trigger the error? Good question&mdash;I ran some tests. `Prope` _does not_ throw an exception, but `Proper` does. And to further clarify, `Propery` (yes, it's misspelled) also causes an exception. So it's definitely due to the sequence `Proper` being part of the table row header name. Also, this is very strange, the table row header does not need to simply start with `Proper` to trigger the error, but `Proper` must only appear within the table row header. For example: `aProper` caused an exception to occur, but `aPrope` did not. I did not expect this. I also tested that this _only_ occurs when the text `Proper.*` appears in a column header&mdash;i.e. table row cell values are not affected.

## 6. Context

I'm unable to use a table with a column header that includes the text `Proper.*` without Pester throwing an `ArgumentException`.

**Comment by fourpastmidnight** [comment]
Hmm, the same thing seems to be happening with table row headers containing the text `eFile`. The original table header name was `TypeFile`. I've tried many other combinations of table header names: `TypesFile`, `Ps1XmlFile`. I finally had to settle for something extremely generic, like `Document` which is unfortunate because it's not even remotely close to the domain language I want to convey. However, it would seem that there apparently are issues with table row header parsing.

**Comment by fourpastmidnight** [comment]
I have determined why this is happening, and it's because of something that can be seen in #1121. Using the same example from #1121, it is plain what's happening and that single-column tables do not appear to be parsed correctly:

### Feature File

```gherkin
Given the module manifest has the following properties:
    | PropertyName  |
    | ModuleVersion |
    | GUID          |
    | Author        |
    | CompanyName   |
    | Copyright     |
    | Description   |
```

### Step Definition

```powershell
Given "the module manifest has the following properties:?" {
    Param($tableRows)

    Write-Debug "Table has $($tableRows.Keys.Count) keys:"
    Write-Debug $($tableRows | Out-String)
}
```

### Example Output

```
Table has 48 keys:
Name    Version
----    -------
e
m
a
r
N
P       ModuleVersion
p
o
e
m
a
r
N
P       GUID
p
o
e
m
a
r
N
P       Author
p
o
e
m
a
r
N
P       CompanyName
p
o
e
m
a
r
N
P       Description
p
o
```

The reason the exception is being thrown is because the Key/Name column is not being parsed correctly. The word `Property` has two `r`'s in it, thus the source of the `InvalidOperationException` due to a duplicate key.

And, based on this relevation, it also explains why the column header `FileType` also caused the same error to be thrown: that column header contains two `e`'s.

**Comment by mikeclayton** [comment]
I think the problem is in this line of Gherkin.ps1.

https://github.com/pester/Pester/blob/master/Functions/Gherkin.ps1#L833

```powershell
${Column Names} = ${InputObject Header}.Cells | & $SafeCommands["Select-Object"] -ExpandProperty Value
```

When there's only one column in the table, ```Select-Object``` returns a ```[string]``` instead of an ```Object[]```.

By sheer dumb luck, both ```[string]``` and ```Object[]``` have a ```Length``` member and can be indexed with ```[$n]``` so the rest of the Pester code in Gherkin.ps1 doesn't crash, but instead treats the string as if each character in it were a separate column name.

In other words, because of a bug it treats this:

```text
| PropertyName |
| Property1    |
| Property2    |
| Property3    |
```

as if it were this:

```text
| P            | r | o | p | e | r | t | y | N | a | m | e |
| Property1    |   |   |   |   |   |   |   |   |   |   |   |
| Property2    |   |   |   |   |   |   |   |   |   |   |   |
| Property3    |   |   |   |   |   |   |   |   |   |   |   |
```

And then suddenly all of your symptoms make sense - an error about duplicate a column name "r", and a very large hashtable of values, with most of them blank.

I think the fix is to force the result of ```Select-Object``` to be an array regardless of the number of columns by wrapping the expression in ```@( ... )```:

```powershell
${Column Names} = @( ${InputObject Header}.Cells | & $SafeCommands["Select-Object"] -ExpandProperty Value )
```

Interestingly, a similar line of code elsewhere in Gherkin.ps1 already does this, so presumably got fixed there at some point but missed above:

https://github.com/pester/Pester/blob/master/Functions/Gherkin.ps1#L411
```powershell
${Column Names} = @($ExampleSet.TableHeader.Cells | & $SafeCommands["Select-Object"] -ExpandProperty Value)
```

I'll send a PR with this fix in it for the project owners to review but in the meantime you could either patch your local copy of Pester as above, or maybe add a dummy column to your data to avoid triggering the bug:

```text
| PropertyName | DummyColumn |
| Property1    |             |
| Property2    |             |
| Property3    |             |
```

**Comment by fourpastmidnight** [comment]
@mikeclayton Thanks for taking look. After looking through _The Cucumber Book_, I saw an example that did the same thing, returned a single-column table as a list of strings. And in fact, the sample table had no header in this case, as well.

Looking at the code, and having used other tables, I also came to the conclusion I _could have_ appended an additional empty column which would have resolved the immediate issue in a hack-ish sort of way, but despite my not being able to directly pinpoint a problem, I still felt there might be one even if I had misunderstood how the single-column table would be passed.

I appreciate you looking into this and replying with such a thorough answer.  Thanks!

**Comment by fourpastmidnight** [comment]
I tried using the table parameter as a simple array and removed the column header so it doesn't become a list item. But, due to the identified bug, if your first "row" text contains more than one of the same character, the `InvalidOperationException` for the "duplicate key" is being thrown. So, yeah, I think you hit the nail on the head, the call to `Select-Object` needs to force the result to be an array to prevent this error.

**Comment by fourpastmidnight** [comment]
Since #1127 has been merged, this issue is now closed. Thank you @mikeclayton for the contribution to fix this rather painful issue! Thanks @nohwnd for merging this. Hope you all have wonderful holidays.
