### ISSUE TITLE
Pester does not print Tables or DocStrings that are part of steps

### ISSUE THREAD

**Issue by fourpastmidnight** [pester/Pester#1124]
## 1. General summary of the issue

When using DocString or tables as part of steps, this data is not printed to the console during the test run, unlike in cucumber (for Ruby) or SpecFlow for .NET.

## 2. Describe Your Environment

Pester version : 4.4.2 C:\Program Files\WindowsPowerShell\Modules\Pester\4.4.2\Pester.psd1
PowerShell version : 5.1.17134.165
OS version : Microsoft Windows NT 10.0.17134.0

## 3. Expected Behavior

For this step in a gherkin file:

```gherkin
Then  it should be displayed as:
  """

  Major Minor Patch PreReleaseTag BuildMetadataTag
  ----- ----- ----- ------------- ----------------
      1     4     5 rc.1



  """
```

when running the tests, it should be displayed on the console as

```
    [+] Then it should be displayed as:

      Major Minor Patch PreReleaseTag BuildMetadataTag
      ----- ----- ----- ------------- ---------------
          1     4     5 rc.1


```

Per _The Cucumber Book_ on page 78:

> Just like a data table, the entire string between the `"""` triple quotes is attached to the step above it.

## 4.Current Behavior

Currently, only the main text of the step is displayed:

```
    [+] Then it should be displayed as:
```

## 5. Possible Solution

For steps containing tables or DocStrings, display the table or DocString with the step text just as Cucumber does.

## 6. Context

While it's nice that the Gherkin style tests for Pester have reused much of the existing Pester test framework, some nice details about using Gherkin for BDD style tests was "lost in translation" (or perhaps, just not quite finished). This issue merely exists to track/record the desire to bring the Gherkin style tests in Pester up to parity with Cucumber, where possible.

The value in displaying this data, though it does take up considerable console real-estate, is that these style of tests are meant to be more readable than compact.

**Comment by Jaykul** [comment]
I'll have to look at it, but with the new `-Show` replacing `-Quiet` it should be possible to output these as a new output type that's (on by default but) controllable, I think.

@nohwnd you could assign this one to me and tag it #Gherkin

**Comment by fourpastmidnight** [comment]
So, I agree that perhaps an option parameter would be best. But now I'm wondering what the name of it should be (ah, one of the hardest problems in Computer Science: naming things). So, tables can be part of both a step definition _and_ a scenario (for Scenario Outlines). DocStrings, on the other hand, are only associated with step definitions.

I was thinking of something like `[switch] $HideScenarioData`, with a description (in the comment help) of:

> If this flag is specified, scenario outline tables or step definition tables and/or DocStrings will not be output to the console.

I don't think we could add this to the existing `OutputTypes` enum because this "feature" would not apply to standard Pester tests.

**Comment by fourpastmidnight** [comment]
Got too close to the problem. Example tables do not need to be printed since `Scenario Outline`s result in one scenario per example row. So now naming becomes easier.

**Comment by Jaykul** [comment]
Could we just add "Details" or "Docs" to the `-Show` switch?  

I mean, I guess we might be able to just always output them (I haven't tried yet, to see what it would look like. My problem is that I use those docstrings to embed code examples sometimes, and I just imagine it being very _noisy_ without even having tried it.

**Comment by fourpastmidnight** [comment]
I could. The only reason I didn’t was because this “feature” doesn’t apply to Pester at large—just for Gherkin tests. The worst that would happen is it'd be a no-op for Pester, and of course the documentation would detail that. I’m easy on this one.

Just let me know, do you definitely want me to add the additional enum value to Show? I can have that turned around in no time.

Thanks for your comments.

Sent from my Windows 10 phone

**Comment by fourpastmidnight** [comment]
@nohwnd , @Jaykul  Question for you: I see in the code that _a lot_ of common PowerShell cmdlets are placed into the `$SafeCommands` array, and I understand conceptually why that is. But, I do see inconsistencies&mdash;where the "naked" cmdlet is used. Is there any rhyme or reason for when `$SafeCommands` should be used over the "naked" cmdlet, or is this simply an "oversight" and contributors should _always_ use `$SafeCommands`?

For the life of me, I can't figure out why my PowerShell v2 build continues to break even though the changes I have made are not significant. But it dawned on me today that perhaps it's not the unit test that's "broken", but it's the updated code I pushed earlier this week to fix a display bug&mdash;and I noticed that I forgot to use the `$SafeCommand` "versions" of several cmdlets, e.g. `ForEach-Object`, `Select-Object`, etc.

**Comment by Jaykul** [comment]
Well, there are a few places where you don't have to use SafeCommands -- but in general, most Pester code is running in tests and with so many things mocked that it gets crazy 🤨

**Comment by fourpastmidnight** [comment]
Ok, so I spun up a Win2k8 R2 SP1 VM on Azure. I ran the tests against my PR for this issue, and sure enough, they fail in the same way as on the TC build server for PS v2. So, that's good, it's consistent. However, the commit referenced above also passes the tests on this VM, even though the test code is identical (from a behavior point of view), so, I'm no closer to an answer other than 1) I know I can trust the TC build servers 😉 and 2) I have a VM I can play around on instead of waiting an hour for answers between builds. lol.

**Comment by fourpastmidnight** [comment]
Ok, finally found it. I know where it's broken, but not how--yet. I should have this fixed by the end of the weekend at the latest. Yay.

**Comment by fourpastmidnight** [comment]
And, yeah, it got me. PowerShell 2 doesn't always return an array when you think it should. Ugh. Wow, that took long enough.

**Comment by fourpastmidnight** [comment]
@Jaykul, @nohwnd I resolved the build issue with the PR associated with this issue. But I want to return to the question of whether or not I should have added another parameter to `Invoke-Gherkin` versus adding an enum value to the `OutputTypes` enumeration which is used for both `Invoke-Gherkin` and `Invoke-Pester`, as has been suggested by @Jaykul.

The reason for my original choice of implementing a new parameter for `Invoke-Gherkin` is that the option to show this information _is only_ applicable for Gherkin-style tests; so I didn't think it would be good to have, basically, an ignored/no-op value in the `OutputTypes` enumeration for RSpec-style tests. I'm open to changing this--it wouldn't take long. But I'd like to have the question settled so that this PR can be considered for merging.

**Comment by nohwnd** [comment]
@fourpastmidnight I don't pay attention to all issues here, but we could get in touch on twitter or some other place where you can DM me when you have problems so you don't have to struggle by yourself 😊 I don't know much about Gherkin, but at least I can learn and help you work on it. 

As for the output I plan to reorganize things in the code into core, above which rspec and gherkin style Pester would be written, so then we can hopefully share the important parts without bumping into such problems. I haven't thought it through yet, so I cannot spell it out in more detail. 

I would not add another option in the OutputTypes enum, because then the option would show up in Invoke-Pester api. Instead you should probably duplicate the type and make the internal code accomodate both options without being tied to either of those types.

**Comment by fourpastmidnight** [comment]
@nohwnd I agree, which is why I added a new parameter to `Invoke-Gherkin` to control this. However, I think (actually, I'm pretty sure) my attempt to provide "pretty-printed" DocStrings and tables in the console broke the VS Code problem matcher--so I'll need to find a way to fix that--and failing that, perhaps this will just be one of those unfortunate things where the two options are mutually exclusive. But then, that raises an interesting question: perhaps `-HideStepData` could be part of an options object much like `-IncludeVSCodeMarker` is? And it could be documented that the two options are mutually exclusive (assuming I can't find a way to make them work together).

**Comment by Jaykul** [comment]
It makes sense to me that `-IncludeVSCodeMarker` would be sensitive to the extra output. Of course, if you're making it so that you output the details by default, and the switch is to hide it, then you could just have `-IncludeVSCodeMarker` _also_ hide it ...
