### ISSUE TITLE
Invoke-Gherkin attempts to "re-load" Pester?

### ISSUE THREAD

**Issue by fourpastmidnight** [pester/Pester#1130]
## 1. General summary of the issue

I logged #1129 two days ago. That issue was a bit of a show-stopper for me and how I want to organize my test files for my module project. So, I created a `Dependencies` folder in my project and copied the Pester module to it and made the appropriate manual modifications (per my second comment on #1129, since that was the easiest to implement) to at least get me unblocked until I (or someone else) has time to act further on #1129. My modifications to Pester were working just fine. However, with no further modifications, it just stopped working at some point! I have no idea what happened to cause it to stop working, so I started looking into it.

## 2. Describe Your Environment

Pester version : 4.4.2 C:\Program Files\WindowsPowerShell\Modules\Pester\4.4.2\Pester.psd1
PowerShell version : 5.1.17134.165
OS version : Microsoft Windows NT 10.0.17134.0

It should also be noted that I'm running the Pester Gherkin tests using a VS Code task defined in `tasks.json`. Here's the relevant `tasks.json` task data:

```json
{
  "version": "2.0.0",

  "windows": {
    "options": {
      "shell": {
        "executable": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
        "args": [ "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command" ]
      }
    }
  },

  "tasks": [
    {
      "label": "Test",
      "group": "test",
      "type": "shell",
      "command": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
      "args": [
        "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", ".\\My.Module.Name\\build.ps1 -Task Test"
      ],
      "presentation": {
        "reveal": "always",
        "panel": "new"
      },
      "problemMatcher": [
        {
          "owner": "powershell",
          "fileLocation": ["absolute"],
          "severity": "error",
          "pattern": [
            {
              "regexp": "^\\s*(\\[-\\]\\s*.*?)(\\d+)ms\\s*$",
              "message": 1
            },
            {
              "regexp": "^\\s+at\\s+[^,]+,\\s*(.*?):\\s+line\\s+(\\d+)$",
              "file": 1,
              "line": 2
            }
          ]
        }
      ]
    }
  ]
}
```

And, yes, the `problemMatcher` definition is probably not correct since I bummed most of this task file from somewhere else and modified it to get me started--I hadn't gotten around to defining the `problemMatcher` correctly yet due to this issue.

## 3. Expected Behavior

I expected that once I imported the Pester module in my psake build task that `Invoke-Gherkin` would use the loaded module. However, the module is not loaded as of line 262 in `Gherkin.ps1` inside of `Invoke-Gherkin`, which is strange. However, it's completely possible I'm misunderstanding something about PowerShell here.

## 4.Current Behavior

As stated, I made a private copy of Pester and modified `Gherkin.ps1` according to my second comment on #1129 until I (or someone else) has time to implement a solution to at least get me unblocked. I also gave my customized Pester module a new version: 4.4.2.1. These changes were working great--and then, all of a sudden without any further modifications, they are now not working. So I started looking into it.

I have the following `psake` task:

```powershell
Task Test -Depends InstallDependencies, Init {
    Import-Module -Name "$ProjectRoot\Dependencies\Pester\4.4.2.1\Pester.psd1" -Force

    # These two lines are here for debugging purposes
    Get-Module | Out-Host
    Pause

    $testArtifactPath = "$Artifacts\TestResult"
    if (!(Test-Path -Path $testArtifactPath)) {
        New-Item -ItemType Directory -Path $testArtifactPath
    }

    $pesterOptions = New-PesterOption -TestSuiteName 'Almac.Ixrs3.Deploy Module Tests' -IncludeVSCodeMarker

    $testParams = @{
        Path = "$ProjectRoot\Specs\features"
        OutputFormat = "NUnitXml"
        OutputFile = (Join-Path $testArtifactPath $TestFile)
        PesterOption = $pesterOptions
        EnableExit = $False
        Strict = $True
        PassThru = $True
        Verbose = $VerbosePreference
        Debug = $DebugPreference
    }

    $testResults = Invoke-Gherkin @testParams
    if ($testResults.FailedCount -gt 0) {
        $testResults | Format-List
        Write-Error -Message "Failed '$($testResults.FailedCount)' tests."
    }
}
```

Furthermore, during debugging, I modified `Gherkin.ps1` once more to help me figure out what's going on. Within the `Invoke-Gherkin` function, on line 262, right before Pester's about to create a `PesterState` object, I added this:

```powershell
<# 262: #> Get-Module | Out-Host
<# 263: #> $pester = New-PesterState -TagFilter ...
```

Now, when running my psake task above, here's the output that I get:

```
psake version 4.7.4
Copyright (c) 2010-2017 James Kovacs & Contributors

Executing InstallDependencies
Executing Init
Executing Test

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     1.0.0.0    CimCmdlets                          {Export-BinaryMiLog, Get-CimAssociatedInstance, Get-CimClass, Get-CimInstance...}
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Script     4.4.2.1    Pester                              {Add-AssertionOperator, AfterAll, AfterEach, AfterEachFeature...}
Script     4.7.4      psake                               {Assert, Exec, FormatTaskName, Framework...}


Press Enter to continue...:
I'm about to create a new PesterState object!

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        Axiom                               {Verify-AssertionFailed, Verify-Equal, Verify-False, Verify-NotNull...}
Binary     1.0.0.0    CimCmdlets                          {Export-BinaryMiLog, Get-CimAssociatedInstance, Get-CimClass, Get-CimInstance...}
Script     0.0        Format                              {Format-Boolean, Format-Collection, Format-Date, Format-Dictionary...}
Binary     1.0.0.0    Gherkin
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Script     4.7.4      psake                               {Assert, Exec, FormatTaskName, Framework...}
Script     0.0        TypeClass                           {Is-Collection, Is-DecimalNumber, Is-Dictionary, Is-Hashtable...}


Pester\SafeGetCommand : The module 'Pester' could not be loaded. For more information, run 'Import-Module Pester'.
At C:\src\git\My.Module.Name\Dependencies\Pester\4.4.2.1\Functions\PesterState.ps1:73 char:58
+ ... afeCommands['New-Object']          = & (Pester\SafeGetCommand) -Name  ...
+                                             ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Pester\SafeGetCommand:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CouldNotAutoLoadModule

Error: 10/24/2018 16:00:30:
 +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~ [<<==>>] Exception: Cannot bind argument to parameter 'PesterState' because it is null.

Press any key to close the terminal.
```

You can see that the list of modules loaded at the point I'm inside the psake task is different from the list of modules loaded from within `Invoke-Gherkin`. This is very strange--but again, I may not have a true understanding of how PowerShell is working here. But, the error message from attempting to create the `PesterState` object is indicative of the fact that the Pester module is indeed not loaded. Looking at the error: line 73 ff. of `PesterState.ps1`:

```powershell
$script:SafeCommands['New-Object']          = & (Pester\SafeGetCommand) -Name New-Object          -Module Microsoft.PowerShell.Utility -CommandType Cmdlet
$script:SafeCommands['Select-Object']       = & (Pester\SafeGetCommand) -Name Select-Object       -Module Microsoft.PowerShell.Utility -CommandType Cmdlet
$script:SafeCommands['Export-ModuleMember'] = & (Pester\SafeGetCommand) -Name Export-ModuleMember -Module Microsoft.PowerShell.Core    -CommandType Cmdlet
$script:SafeCommands['Add-Member']          = & (Pester\SafeGetCommand) -Name Add-Member          -Module Microsoft.PowerShell.Utility -CommandType Cmdlet
```

The error is complaining that `Pester\SafeGetCommand` cannot be found. I can confirm that from within the psake task, since the module is loaded, that the function exists. However, from within `Invoke-Gherkin`, since the Pester module is not loaded, of course, the function does not exist.

So again, very strange. I'm hoping someone can either point me in the right direction or confirm that this is a problem with Pester.

## 5. Possible Solution

I'm unsure what the exact nature of the problem is, so I'm unable to speculate on a potential solution.

## 6. Context

Well, this is now blocking me from running my tests. So any help would be greatly appreciated.

**Comment by dlwyatt** [comment]
Does it work if you add -Global to your call to Import-Module in the psake script?

**Comment by fourpastmidnight** [comment]
Good call. When running in that psake task, it's a script block....ugh. That worked. Funny that it was working before--but maybe I still had the module loaded in the session somewhere and it was getting "reused". Thanks!
