### ISSUE TITLE
Pester output showing 0 tests run even when tests run

### ISSUE THREAD

**Issue by DamianBis** [pester/Pester#1132]
## 1. General summary of the issue

When running my pester tests against a folder it runs the tests but the output at the end shows 0 tests run.

If i run just against the individiual functions it works.

## 2. Describe Your Environment

Operating System, Pester version, and PowerShell version:

Pester version     : 4.4.2 C:\Program Files\WindowsPowerShell\Modules\Pester\4.4.2\Pester.psd1
PowerShell version : 5.1.17134.228
OS version         : Microsoft Windows NT 10.0.17134.0

## 
3. Expected Behavior

Tests completed summary to be correct

## 4.Current Behavior

Executing script C:\Users\*********\Documents\gtawscommon\Add-LambdaNotificationToS3Bucket.Tests.ps1

Describing Add-LambdaNotificationToS3Bucket
  [+] Adds the correct object to the S3 Bucket 120ms

Executing script C:\Users\*********\Documents\Functions.Tests.ps1

Describing Generic Tests Function Enter-ASGStandby
******
*******
*******
Some tests failing. some passing.
******
******
******
Tests completed in 0ms
Tests Passed: 0, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0

## 6. Context

Means we can't report on test failures.

##

I believe the issue may have something to do with how my tests run

Below file is Functions.Tests.ps1

``
    $here = Split-Path -Parent $MyInvocation.MyCommand.Path
    Import-Module "$here\GTPester.psm1", Pester

    $Modules = Get-ChildItem $here | Where-Object {$_.Name -like "*.psm1"}

    foreach($module in $modules)
    {
    $ModuleName = $Module.Name.replace(".psm1","")
    $Functions = Get-ChildItem "$here\$moduleName\" | Where-Object {$_.Name -notlike "*.Tests.ps1"}
    if($null -ne $functions)
    {
        Import-Module "$here\$ModuleName.psm1" -force

        foreach($function in $functions)
        {
            $functionName = $function.Name.replace(".ps1", "")
            $functionPath = $function.FullName
            . $functionPath
            
            Invoke-GenericFunctionTests $functionName $functionPath
        }
    }
    }
``

then "Invoke-GenericFunctionsTests" is 

``
    function Invoke-GenericFunctionTests
    {
	param (
		[Parameter(Mandatory=$true)][string] $FunctionName,
        [Parameter(Mandatory=$true)][string] $FunctionPath
	)
    Describe -Tags "Unit" "Generic Tests Function $FunctionName" {
        $Help = Get-Help $FunctionName
        $HelpExamples = Get-Help $FunctionName -Examples    
        $DetailedHelp = Get-Help $FunctionName -Detailed
        
        It "Get-Help has examples" {
            $HelpExamples.Examples | Should Not Be $null
        }
        
        It "Get-Help has documentation for all parameters" {
            $DetailedHelp.Parameters | Should Not Be $null
            
            foreach($Parameter in $DetailedHelp.Parameters.Parameter)
            {
                if($Parameter.Description -eq $null)
                {
                    Write-Host $Parameter
                }
                $Parameter.Description | Should Not Be $null
            }
        }
        
        It "Get-Help has a Synopsis or a Description" {
            ( ($DetailedHelp.Description -eq $null) -and ($DetailedHelp.Details.Description -eq $null) ) | Should Not Be $true
        }

        $Code = Get-Content $FunctionPath
        It "Function has CmdletBinding" {
            $Code | Select-String "CmdletBinding()" | Should Not Be $null
        }
        
        $Variables = $Code -split " " | Select-String "\$"
        It "Variables are all named with an uppercase letter at start" {
            ($Variables | Where-Object {$_ -match "\$[a-z,0-9]" -and $_ -cmatch "\$[^(A-Z,0-9)]" -and $_ -notmatch "(\`$true)|(\`$False)|(\`$null)|(\`$_)|(\`$args)"}) | Should Be $null
        }
        
        It "Variables don't have underscore in name" {
            ($Variables | Where-Object {$_ -match "\$[a-z]+_[a-z]+"}) | Should Be $null
        }
    }
}
``

The weird thing is that if i just run a single script (say i just run functions.Tests.ps1) i get the output properly.

**Comment by dlwyatt** [comment]
You’re importing Pester from your test script; don’t do that.

**Comment by DamianBis** [comment]
Wow. easy fix. thanks for that.

I was under the impression (i guess i just made it up) that i'd import pester as part of the test scripts to ensure it's imported. But i guess when i'm doing a -force as well i'm forcing it to reload and then it must lose it's state.
