### ISSUE TITLE
Start-Process Error Not Captured

### ISSUE THREAD

**Issue by natescherer** [pester/Pester#1134]
## 1. General summary of the issue

I recently ran into an issue where an error in a Start-Process generated an error that wasn't captured by Pester on Linux. Specifically, I was attempting to start a process with an invalid FilePath.

Here's the Pester output:

```PowerShell
    [-] Error occurred in Describe block 212ms
      ValidationMetadataException: The attribute cannot be added because variable Result with value  would no longer be valid.
      MethodInvocationException: Exception calling "AddTestResult" with "8" argument(s): "The attribute cannot be added because variable Result with value  would no longer be valid."
```

## 2. Describe Your Environment

Environment is AppVeyor with Ubuntu1804:

Pester version     : 4.4.2 /home/appveyor/.local/share/powershell/Modules/Pester/4.4.2/Pester.psd1
PowerShell version : 6.1.0-rc.1
OS version         : Unix 4.15.0.1014

## 3. Expected Behavior

Run:

```PowerShell
It 'Mandatory Params' {
    $Process = Start-Process -FilePath "$env:GOPATH\bin\badpath" -PassThru
}
```

Output:

```PowerShell
Start-Process : No such file or directory
```

## 4.Current Behavior

Run:

```PowerShell
It 'Mandatory Params' {
    $Process = Start-Process -FilePath "$env:GOPATH\bin\badpath" -PassThru
}
```

Output:

```PowerShell
ValidationMetadataException: The attribute cannot be added because variable Result with value  would no longer be valid.
MethodInvocationException: Exception calling "AddTestResult" with "8" argument(s): "The attribute cannot be added because variable Result with value  would no longer be valid."
```

## 5. Possible Solution

I'm afraid I don't understand the internals of Pester enough to offer a possible solution.

## 6. Context

Not a huge issue; I was able to figure out the error by unwrapping my test code from Pester and running it manually, but it would be nice if Pester itself could capture this error.

**Comment by nohwnd** [comment]
@natescherer I am trying to replicate this but I can't. I get: 
```
Describing a
  [-] Mandatory Params 590ms
    InvalidOperationException: This command cannot be run due to the error: No such file or directory.
```
Running on current `microsoft/powershell` docker image: 
```
Pester version     : 4.4.2 /usr/local/share/powershell/Modules/Pester/4.4.2/Pester.psd1
PowerShell version : 6.1.0
OS version         : Unix 4.9.93.0
```

To me it looks like the only difference here is that I am running on 6.1 and you on 6.1-rc. could you maybe update and see if that helps?

**Comment by natescherer** [comment]
Sorry for the delay on this, I was waiting for Appveyor to update their images to use 6.1 final and lost track of this. I tested and this doesn't appear to be an issue on 6.1, so I'm closing. Sorry for the trouble.

**Comment by nohwnd** [comment]
@natescherer no problem 🙂
