### ISSUE TITLE
AfterEach* hooks throw an exception in Gherkin.ps1

### ISSUE THREAD

**Issue by fourpastmidnight** [pester/Pester#1135]
## 1. General summary of the issue

I am trying to figure out why a function under test is not able to find the `$PSBoundParameters` dictionary when testing it under Pester (see #1133). During the course of my investigation, I began to wonder if my `AfterEachFeature` hook was running (not that that had anything to do with my failing tests). So I added some `Write-Host` statements to the hook. Sure enough, it's not being run. And actually, what I failed to realize for the longest time is that Pester is actually throwing an exception on these hooks.

## 2. Describe Your Environment

Pester version : 4.4.2 C:\Program Files\WindowsPowerShell\Modules\Pester\4.4.2\Pester.psd1
PowerShell version : 5.1.17134.165
OS version : Microsoft Windows NT 10.0.17134.0

## 3. Expected Behavior

I expected the `AfterEach*` hooks to run.

## 4.Current Behavior

Here are my hooks that are failing:

```powershell
AfterEachScenario -Tags "Get-ParameterValues" {
    Write-Host "In AfterEachScenario hook."
}

AfterEachFeature -Tags "Get-ParameterValues" {
    Write-Host "In AfterEachFeature hook:"
    if ((Get-Item 'Function:\Test')) {
        Write-Host "Removing function Test."
        Remove-Item 'Function:\Test'
    } else {
        Write-Host "Function 'Test' not found."
    }
}
```

Pester is throwing an exception when attempting to run these hooks, not a single line of output is displayed via any calls to `Write-Host` in these hooks:

```
    [-] Error occurred in scenario 'Get-ParameterValues returns a dictionary with the expected key and value
  Examples:Examples using parameter ValueWithNoDefault' 21ms
      at Invoke-GherkinHook, C:\src\git\My-Module\Dependencies\Pester\4.4.2\Functions\Gherkin.ps1: line 38
      The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo object.
```

This appears to occur only if the hook(s) have tags associated with them.

## 5. Possible Solution

I'm not sure what the solution is.

## 6. Context

I'm unable to use tags to determine which hooks are relevant hooks to be run for various features and/or scenarios.

**Comment by nohwnd** [comment]
@Jaykul pls :)

**Comment by Jaykul** [comment]
Oops!

They work if you don't tag them -- obviously I don't have any tests cases where I'm tagging them. 

I will try to fix this. In the meantime, don't tag them (can we change the title to say "Tagged hooks throw ...")
