### ISSUE TITLE
BeforeEach/All doen't execute when -ScriptBlock is used as named parameter.

### ISSUE THREAD

**Issue by kvprasoon** [pester/Pester#1140]
## 1. General summary of the issue

BeforeEach and BeforeAll functions doesn't execute when -ScriptBlock parameter is used.

![image](https://user-images.githubusercontent.com/12897753/47966869-05f0c880-e07d-11e8-8f2b-fe65c37da958.png)

## 2. Describe Your Environment

```powershell
Pester version     : 4.4.2 C:\Program Files\WindowsPowerShell\Modules\Pester\4.4.2\Pester.psd1
PowerShell version : 5.1.18272.1000
OS version         : Microsoft Windows NT 10.0.18272.0

```

## 3. Expected Behavior

![image](https://user-images.githubusercontent.com/12897753/47967235-52d69e00-e081-11e8-956c-fc3010af18c4.png)

## 4.Current Behavior

![image](https://user-images.githubusercontent.com/12897753/47967225-363a6600-e081-11e8-866e-73970ebdf9bd.png)

**Comment by dlwyatt** [comment]
Current behavior is expected. It’s not intended to be used like a cmdlet; it’s more of a fake keyword like “if” / etc.

**Comment by nohwnd** [comment]
I still think this should be considered a bug and fixed.
