### ISSUE TITLE
How to verify that mocked object's function was called

### ISSUE THREAD

**Issue by deadlydog** [pester/Pester#1145]
This is a question, not an issue. I'm mocking out a windows `Process` using:
```PowerShell
$mockProcess = New-MockObject -Type System.Diagnostics.Process
Mock -CommandName New-Object -MockWith { return $mockProcess } -ParameterFilter { $TypeName -eq 'System.Diagnostics.Process' }
```
I am able to verify that the mocked process properties get set correctly with:
```PowerShell
$mockProcess.StartInfo.FileName | Should -Be $executableToRun
$mockProcess.StartInfo.Arguments | Should -Be $executableArguments
```
But how can I test that the $mockProcess.Start() function was actually called? I've looked over the documentation, but haven't found anything relating to this. The closes I've found is `Assert-MockCalled`, but that seems to be just for mocking out function/cmdlet calls, not functions on mocked objects.

Essentially I'm looking to be able to do something like this:
```PowerShell
Assert-MockCalled $mockProcess.Start() -Exactly 1
```

Is it possible to do this somehow? Or is it not yet supported in Pester? Thanks!

**Comment by mikeclayton** [comment]
Hi @deadlydog,

You can't mock methods of CLR objects - there's no way for Pester to intercept the call to the real method and substitute it with a mock. What you can do instead is wrap the method call in a PowerShell function and then mock the PowerShell function instead.

There was a similar issue raised here a while ago that might help:

#1068 - Mocking Functions of an object

Cheers,

Mike

**Comment by nohwnd** [comment]
You might be able to leverage the extended type system to shadow the actual method like this: 

```powershell
function Tested-Function ([Diagnostics.Process]$Process) {
    $Process.Start()
} 

describe "a" { it "b" {
    # make a function so we have something to work with
    function Start1 () { }
    # mock the function so we can levarage Assert-MockCalled
    Mock Start1 { Write-Host "this is mock" }
    $mockProcess = New-MockObject -Type System.Diagnostics.Process
    # shadow the actual method on the object with ours that calls the mock
    $mockProcess | 
        Add-Member -MemberType ScriptMethod -Name Start -Value { Start1 } -Force 
    
    # call the function we are testing
    Tested-Function -Process $mockProcess

    # assert we called the function
    Assert-MockCalled Start1 -Times 1 -Exactly
}}
```
It of course depends heavily on what you are doing :) You did not share any code so I am just guessing. If you are passing the process to a .NET method it won't be fooled by powershells ETS and this won't work :)

**Comment by nohwnd** [comment]
The workaround should be enough, if you need more assistance please reopen this issue of file a new one.
