### ISSUE TITLE
Pester will not install - Not signed in PSGallery

### ISSUE THREAD

**Issue by Gale52** [pester/Pester#1147]
PS C:\> install-module pester -Force
PackageManagement\Install-Package : The version '4.4.2' of the module
'Pester' being installed is not catalog signed. Ensure that the version
'4.4.2' of the module 'Pester' has the catalog file 'Pester.cat' and signed
with the same publisher 'CN=Microsoft Root Certificate Authority 2010,
O=Microsoft Corporation, L=Redmond, S=Washington, C=US' as the
previously-installed module '4.4.2' with version '3.4.0' under the directory
'C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0'. If you still want
to install or update, use -SkipPublisherCheck parameter.
At C:\Program
Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809
char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallP
   ackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : ModuleIsNotCatalogSigned,Validate-ModuleAuthen
   ticodeSignature,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPa
  ckage

**Comment by nohwnd** [comment]
@Gale52 Moved your issue here from the repository of our empty website :) Please see the [Installation](https://github.com/pester/Pester#installation) section of our readme.

**Comment by Gale52** [comment]
Thank You,  Several hundred of us attended classes at PASS Summit last week and were introduced to Pester and I am sure you will see a lot of traffic from those classes now that we are back at work.

Gale

**Comment by Gale52** [comment]
Jakub,

  To give you a better picture.  At PASS Summit Rob Sewell taught a full day class on Power Shell and talked up Pester.  During the actual conference he taught 3 additional 70 minute classes.  One was on DBAChecks.  He taught us how to load it so we could just load the dbachecks module and since pester is a dependent with in dba checks they will all be loaded at that time.  There were well over a hundred attendees in each of the sessions.  He talked up Pester in all 4 classes.  Most of the attendees were new to powershell and I am sure they are like I have been pounding their heads on the desk because they cannot get dbachecks to load because when it gets to pester it fails.  I assume I must be the first to get so frustrated that I found the Pester page and stumbled on the field I filled out.  So if there is any way to get Pester properly signed in PSGallery there will be hundreds of SQL DBA’s and Developers that will be greatly appreciative.

Thanks
Gale Mecham
BYU SQL Server Lead Engineer

**Comment by nohwnd** [comment]
@Gale52 Thanks for the info, I am currently waiting for Digicert to approve my certificate request, after that I should be able to publish a signed beta package, and if that works fine I can publish a signed stable version.

**Comment by Gale52** [comment]
Thanks
Gale

**Comment by bergmeister** [comment]
@nohwnd I guess we can close this now after the recent release?

**Comment by nohwnd** [comment]
Version 4.4.3 is the first signed version, now I just need to keep them signed in the future as well.

**Comment by Gale52** [comment]
Thanks

Gale
