### ISSUE TITLE
Redirecting output to user specified function

### ISSUE THREAD

**Issue by davinci26** [pester/Pester#1151]
Hey everyone,

Many thanks for your project!

I have the following question:

_Is it possible to modify the  `SafeCommands` variable from another module?_

For context what I want to do is to redirect the output from  `Write-Host` (etc.)  to another function that will pre-process the output prior to printing it.

I was thinking, that if there was no way to achieve that with the current implementation then this feature could be implemented using parameter during the module installation.

1. The user can provide a dictionary that maps the Pester output function to custom functions. Something like the following example:
```
    'Write-Error'= Get-Command -Name Write-Error-Custom -Module MyModule
    'Write-Host'= Get-Command -Name Write-Host-Custom -Module MyModule  
    'Write-Progress'= Get-Command -Name Write-Progress-Custom -Module MyModule   
    'Write-Verbose'= Get-Command -Name Write-Verbose-Custom -Module MyModule
    'Write-Warning'= Get-Command -Name Write-Warning-Custom -Module MyModule    
```
2. If no dictionary is provided by the user then the `SafeCommands` defaults to the existing value.

What are your thoughts on the subject?

**Comment by nohwnd** [comment]
@davinci26 hi, are you talking about `SafeCommands`?  What you is your goal? Do you want to have custom output from the tests? :)

**Comment by davinci26** [comment]
Thank you for your answer :)

Yes I am talking about `SafeCommands` (Ill edit my initial issue for clarity). 
My goal is to edit this variable to redirect the output to a custom `Write-*` function.

**Comment by nohwnd** [comment]
@davinci26 okay, but why? :) 

You can peek into any module by `&(Get-Module 'ModuleName'){ <code to run inside of the module> }`. So here you could replace the `Write-Host` by doing 
```powershell
Import-Module Pester
&(Get-Module Pester) { $script:SafeCommands['Write-Host']=(Get-Command Write-Host-Custom) }
```

**Comment by davinci26** [comment]
@nohwnd This did the trick.
Thanks a lot for your help! I am adding one more comment to you answer for future readers
```
Import-Module Pester
# Make sure that Write-Host-Custom is visible with the scope
&(Get-Module Pester) { $script:SafeCommands['Write-Host']=(Get-Command Write-Host-Custom) }
```
