### ISSUE TITLE
Assert-MockCalled return false when using -ParameterFilter

### ISSUE THREAD

**Issue by LawrenceHwang** [pester/Pester#1152]
## 1. General summary of the issue
When I was using `Assert-MockCalled` with `-ParameterFilter` to test whether a function wrapped inside a custom function is called with specific a parameter value, I got failed test result when I expected it to pass.

I searched existing issues and found the [issue 1008](https://github.com/pester/Pester/issues/1008) to be similar but the workaround, move functions to module, does not seem to work for my case. The [issue 1007](https://github.com/pester/Pester/issues/1007) might have some relation but the mock subsystem is really not my strength. Please see the example code below and help me understand pester better. Thank you. 👍

```powershell
Get-Module ModuleHolder | Remove-Module
New-Module ModuleHolder {
    function Set-Foo {
        param ()
        Set-KungFoo -Name 'BruceL'
    }
} | Import-Module

Describe 'Set-Foo test describe' {
    context 'Set-Foo test context' {
        It 'Test with Assert-MockCalled' {
            function Set-KungFoo {$true}
            mock -CommandName Set-KungFoo -MockWith {'hi'} -ModuleName ModuleHolder -Verifiable
            
            Set-Foo
            Assert-MockCalled -CommandName Set-KungFoo -ModuleName ModuleHolder -Times 1
        }
    }
    context 'Set-KungFoo test context' {
        It 'Assert-MockCalled with ParameterFilter' {
            function Set-KungFoo {$true}
            mock -CommandName Set-KungFoo -MockWith {'hi'} -ModuleName ModuleHolder -Verifiable
            
            Set-Foo
            Assert-MockCalled -CommandName Set-KungFoo -ParameterFilter {$name -like 'BruceL'} -ModuleName ModuleHolder -Times 1
        }
    }
}
```

## 2. Describe Your Environment

```powershell
Pester version     : 4.4.2 
PowerShell version : 5.1.17134.407
OS version         : Microsoft Windows NT 10.0.17134.0
```

## 3. Expected Behavior

Test should pass.

## 4.Current Behavior

```powershell
PS C:\windows\system32> Invoke-Pester -Script "c:\Users\lawre\Code\Temp\PesterBug.tests.ps1"
Executing all tests in 'c:\Users\lawre\Code\Temp\PesterBug.tests.ps1'

Executing script c:\Users\lawre\Code\Temp\PesterBug.tests.ps1

  Describing Set-Foo test describe

    Context Set-Foo test context
      [+] Test with Assert-MockCalled 221ms

    Context Set-KungFoo test context
      [-] Assert-MockCalled with ParameterFilter 130ms
        Expected Set-KungFoo in module ModuleHolder to be called at least 1 times but was called 0 times
        25:             Assert-MockCalled -CommandName Set-KungFoo -ParameterFilter {$name -like 'BruceL'} -ModuleName ModuleHolder -Times 1
        at <ScriptBlock>, C:\Users\lawre\Code\Temp\PesterBug.tests.ps1: line 25
Tests completed in 351ms
Tests Passed: 1, Failed: 1, Skipped: 0, Pending: 0, Inconclusive: 0
```

**Comment by nohwnd** [comment]
@LawrenceHwang Debugging this is relatively easy. `Write-Host` is a great tool for debugging mock filters. 

```powershell
Assert-MockCalled -CommandName Set-KungFoo -ParameterFilter { Write-Host "-$name-";  $name -like 'BruceL'} -ModuleName ModuleHolder -Times 1
```
Shows in output as: 
```
Context Set-KungFoo test context
--
    [-] Assert-MockCalled with ParameterFilter 145ms
```
Okay so the $name is not defined within the mock. Mocking defines parameters for the script block based on the parameters of the mocked function, and your function does not define a `$Name` parameter. Your function also does not have `[CmdletBinding()]` so any extra param simply becomes an item in `$args`. Probably not what you want so defining a parameter for your function is a better solution. :)

```powershell
It 'Test with Assert-MockCalled' {
    function Set-KungFoo () {$true}
    Mock -CommandName Set-KungFoo -ModuleName ModuleHolder
            
    Set-Foo
    Assert-MockCalled -CommandName Set-KungFoo -ModuleName ModuleHolder -Times 1
}
```
Out of curiosity, what are you testing that needs an externally defined function to be callable by a module scope? 

Also the verifiable parameter allows the mocks to be inspected automatically, you don't need to use it when you do `Assert-MockCalled` and not `Assert-VerifiableMock`.

**Comment by LawrenceHwang** [comment]
@nohwnd  Thanks so much for the tip for debugging the pointing me to the right direction. I updated the function definition before mock and the tests are looking good and green.

```powershell
function Set-KungFoo {
    [cmdletbinding()]
    param ($Name)
   $true
}
```

```powershell
Executing script c:\Users\lawre\Code\Temp\PesterBug.tests.ps1
  Describing Set-Foo test describe
    Context Set-Foo test context
      [+] Test with Assert-MockCalled 267ms
    Context Set-KungFoo test context
-BruceL-
      [+] Assert-MockCalled with ParameterFilter 275ms
Tests completed in 543ms
Tests Passed: 2, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0
```

> Out of curiosity, what are you testing that needs an externally defined function to be callable by a module scope?

Sorry that was probably caused by my late night without coffee. When hitting this gap, I was writing tests for one of the pre-written custom functions in a .ps1 file. The .ps1 file is currently used through dot sourcing. The custom function wraps around another not-built-in module provided cmdlet, say..., `Set-ADComputer`. I was looking through the open issues and trying the suggestions I found in there, which includes putting the function into a module. Hope that makes the context less murky. 😅

**Comment by maartenkools** [comment]
I'm probably (a little) late to the party, but in case anyone reads this in the future. One solution would be to use an argument captor, like so:

```
class ArgumentCaptor {
    $Value = $null

    [boolean]Capture($value) {
        $this.Value = $value
        return $true
    }
}

$queryArgumentCaptor = [ArgumentCaptor]::new()
Assert-MockCalled -CommandName "Invoke-SqlCommand" -Times 1 -ParameterFilter { $queryArgumentCaptor.Capture($Query) }

$queryArgumentCaptor.Value | Should -Be "UPDATE [Settings] SET [Value] = 'value' WHERE [Key] = 'Setting'"
```

This not only asserts that the mock is called, but also asserts the value of the parameter and gives you a clear error message if it doesn't match.

**Comment by nohwnd** [comment]
@maartenkools could you explain a bit more about how it is supposed to work? I see a reference that will keep the value and then return true, so the `-ParameterFilter` will always pass, even if the ParameterFilter would normally be false. I see how it can work for you, but it also seems a bit confusing.

**Comment by maartenkools** [comment]
@nohwnd Sure, consider the following example:

```powershell
BeforeAll{
    function Build ($version) {
        Write-Host "a build was run for version: $version"
    }
    
    function Get-Version{
        return 'Version'
    }
    
    function Get-NextVersion {
        return 'NextVersion'
    }
    
    function BuildIfChanged {
        $thisVersion = Get-Version
        $nextVersion = Get-NextVersion
        if ($thisVersion -ne $nextVersion) { Build $nextVersion }
        return $nextVersion
    }
}

Describe "BuildIfChanged" {
    Context "When there are no Changes" {
        BeforeEach{
            Mock Get-Version { return 1.1 }
            Mock Get-NextVersion { return 1.2 }
            Mock Build {}
    
            BuildIfChanged
        }

        It "Should build the next version" {
            class ArgumentCaptor {
                $Value = $null
            
                [boolean]Capture($value) {
                    $this.Value = $value
                    return $true
                }
            }

            # Will fail with an error "Expected Build to be called at least 1 times but was called 0 times"
            # Assert-MockCalled Build -Times 1 -ParameterFilter {$version -eq 1.1}

            $argumentCaptor = [ArgumentCaptor]::new()
            # Will succeed, as Build is indeed called once
            Assert-MockCalled Build -Times 1 -ParameterFilter {$argumentCaptor.Capture($version)}
            # Will fail, but with an error "Expected 1.1, but got 1.2."
            $argumentCaptor.Value | Should -Be 1.1
        }
    }
}
```

In this example, the `Build` function is called with version 1.2, but I'm testing for 1.1.

If I were to use the assert like this: `Assert-MockCalled Build -Times 1 -ParameterFilter {$version -eq 1.1}`, it will fail, but with an unclear error: _Expected Build to be called at least 1 times but was called 0 times_. In this case I have no idea whether there is a bug in the code that causes `Build` not to be invoked at all, or whether it _is_ invoked, but simply with different parameters than expected.

If I use the argument captor I first assert that the `Build` method is actually invoked, and after that I test whether the `$version` it was invoked with has the expected value:
```powershell
$argumentCaptor = [ArgumentCaptor]::new()
# Will succeed, as Build is indeed called once
Assert-MockCalled Build -Times 1 -ParameterFilter {$argumentCaptor.Capture($version)}
# Will fail, but with an error "Expected 1.1, but got 1.2."
$argumentCaptor.Value | Should -Be 1.1
```
This way my test result will immediately tell me what the problem actually is: `Build` is invoked, but with an unexpected version parameter.

Of course this will not work for everything, but for things like this it can make your test results much clearer.
