### ISSUE TITLE
Support all natural languages which Gherkin provides

### ISSUE THREAD

**Issue by cgnuechtel** [pester/Pester#1165]
## 1. General summary of the issue

Pester should also execute all non-English feature files.

## 2. Describe Your Environment

```
Pester version     : 4.4.3 D:\Documents\WindowsPowerShell\Modules\Pester\Pester.psm1
PowerShell version : 5.1.15063.1446
OS version         : Microsoft Windows NT 10.0.15063.0
```

## 3. Expected Behavior

If Pester executes an non-English feature file, it should just work

## 4.Current Behavior

If Pester executes a German feature file for example, the following output occurs:

```
WARNING: Unexpected Feature Child: Szenario
WARNING: Unexpected Feature Child: Szenariogrundriss
```

And more following errors ...

## 5. Possible Solution

Pull Request will be provided very soon.

**Comment by fourpastmidnight** [comment]
I really like the changes in this PR. Adding in the languages file, in addition to getting us support for feature files in different languages, also gets us the ability to use the "Business Need" and "Ability" feature keyword synonyms and the "Example" scenario keyword synonym (which I myself was going to add!).

There are only two things which I would like to potentially see changed:

1. The location of the `gherkin-languages.json` file
2. The mechanism by which the `gherkin-languages.json` file is obtained/kept up to date

## The location of the `gherkin-languages.json` file

Currently, `Gherkin.dll` is distributed in the `lib/{core,legacy}` folder. I think this folder could use a bit of organization and that the JSON languages file should really be located here, too, e.g.:

```text
─ lib
  └─ Gherkin
    ├ core
    │  └ Gherkin.dll
    ├ legacy
    │  ├ Gherkin.dll
    │  └ Newtonsoft.Json.dll
    └ gherkin-languages.json
```

I believe this organization:

1. Better reflects the source of the libraries
2. Better groups together the dependencies
3. Could potentially better support a mechanism to automatically keep the languages file up to date.

## A Mechanism by Which to Keep the Languages File Up To Date

I would love to see some mechanism by which Pester can attempt to keep the languages file up to date. It could be something as simple as attempting to download the language file via `Invoke-WebRequest` from the Cucumber GitHub repo via the build scripts when building and releasing a new version of Pester (see `release.ps1` and associated scripts). A failure to retrieve the file should not result in a failure to build a release of Pester--Pester should just be released with the existing languages file. Though a warning should be emitted by the build script in case, for example, the Cucumber project decides to move the location of the file.

It should be noted that this file is located in several places within the Cucumber repository. It appears that `https://github.com/cucumber/gherkin/gherkin-languages.json` may be the canonical source.

**Comment by fourpastmidnight** [comment]
P.S. No matter what we decide on my proposed changes above, I would merge this before #1168.

**Comment by fourpastmidnight** [comment]
I deleted my comments here, because they belonged on the Pull Request. Sorry, but I had a browser tab mix up.
