### ISSUE TITLE
v5: Should run phase overwrite test data? 

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#1205]
In v5 test data are first captured during discovery, and then re-used for Run. This makes the data slightly stale when they reach Run because some time passed (based on how long test discovery took) between when the data were captured and run. On the other hand the data are available in the `Find-Test` result which does not run the `Run` phase.

So to make the data more up-to-date we can rewrite them on Run (this also enables defering the test data evaluation by wrapping them into `{}` that is ASTed on Discovery) really simple to implement. 

On the other hand it might be interesting to rewrite the test data after discovery, for example to be able to tell the test that it should be Skipped. But this is probably better implemented as a plugin or a custom filter that will have access to the whole discovered test so it can judge based on the data captured in discovery. 

So the conclusion is that it should overwrite the data, unless there is some other usecase that would be very practical but impossible otherwise.

**Comment by michalporeba** [comment]
Can you point me to the code where this data is captured and run? Are you referring to the data describing test? It sounds very interesting

**Comment by nohwnd** [comment]
@michalporeba  In this case `Data` = `TestCases` (or your `-ForEach` in #832). Here is [where the overwriting happens](https://github.com/pester/Pester/blob/4748eaabd2d035c403f54e0e9267fa024139575e/new-runtimepoc/Pester.Runtime.psm1#L347) and for completeness [here is where](https://github.com/pester/Pester/blob/4748eaabd2d035c403f54e0e9267fa024139575e/new-runtimepoc/Pester.Runtime.psm1#L1517) one test per entry in data is generated. The core function `New-Test` does not handle it itself, instead it's one layer above to keep the core simple, and to permit different implementations of multiplying the tests.

**Comment by nohwnd** [comment]
Data are kept because the whole way of running tests changed multiple times and I no longer evaluate the hashtable twice.
