### ISSUE TITLE
Should Contains for evaluating arrays

### ISSUE THREAD

**Issue by tribou** [pester/Pester#121]
It would be nice if the following were possible:

``` powershell
$array | Should Contain $item
```

Instead of:

``` powershell
$array -contains $item | Should Be $true
```

The former would help if it responded with a more specific failure message for better troubleshooting. (Instead of the latter's "Expected: {True} but was {False}")

**Comment by Jaykul** [comment]
To wake up this thread ... that sounds about right.

**Comment by pcgeek86** [comment]
+1 to OP
