### ISSUE TITLE
How to understand Parameters in mock scriptblock?

### ISSUE THREAD

**Issue by Jeffrey-zhao** [pester/Pester#1215]
I try it out with your case, it works, Now I have an issue. the scenario: for an example:

```powershell
function A ($p1, $p2) {
    # some logic handling with paramters p1 and p2
    # i give an easy logic,but it is complext in fact,just make it easy.
    $p33 = $p1 + 1;
    $p44 = $p2 + 1;

    return B -P3 $p33 -P4 $P44
};

function B ($p3, $p4) {
    return $p3 + $p4
}

Describe "Tesing A" {
    Context "valid value" {
        # this two only differences are 'param()'
        mock B { return $p3 + $p4 } -filterparamter {$p3 -eq 1}
        mock B { param($p3, $p4) return $p3 + $p4 } -ParameterFilter {$p3 -eq 2}

        It "p3 -eq 1" {
            $ret = A -P1 0 -P2 1 # it means it passes 1 to B function's P3
            $ret |should -Be 3
        }

        It "p3 -eq 2 " {
            $ret = A -P1 1 -P2 1 # it means it passes 2 to B function's P3
            $ret |should -Be 4
        }
    }
}
```
when it executes in the line 1111 

```powershell
& ${Script Block} @___BoundParameters___ @___ArgumentList___
```
or 1123
```powershell
& $scriptBlock @Splat
``` 
in mock.ps1, debugging get different parameters values
it mainly points at $BoundParameters and $BoundParameters
so how can I know these above two arguments' differences?
very glad to get all of you help.
I test 'Its' all passed

_edit (nohwnd): formatted your code a bit better_

**Comment by nohwnd** [comment]
@Jeffrey-zhao Hello, I reformatted your code but I am still not sure what you question is, or which case (in the first sentence) you are talking about. 

What is the problem? Are you asking what the line 1111 means? 

Also on the first Mock of `B` you are specifying -FilterParameter which is probably a typo. The name of the parameter is `-ParameterFilter`.

**Comment by Jeffrey-zhao** [comment]
> @Jeffrey-zhao Hello, I reformatted your code but I am still not sure what you question is, or which case (in the first sentence) you are talking about.
> 
> What is the problem? Are you asking what the line 1111 means?
> 
> Also on the first Mock of `B` you are specifying -FilterParameter which is probably a typo. The name of the parameter is `-ParameterFilter`.

>@nohwnd 
>thanks, well there is a typo.
> I mean when I use these two mock functions and debug in the  line `1111`  in mock.ps1
>it is  `& ${Script Block} @___BoundParameters___ @___ArgumentList___`
>but sometimes these values like `$___BoundParameters___ =@{P3=1;P4=1}` and `$___ArgumentList___=@()`
or `$___BoundParameters___ =@{}` and `$___ArgumentList___=@('-P3',1,'-P4',1)`

>so it is about `param($p3,$p4)` that exists or not ? maybe it is anthor reason?

>and what is the key point to this scriptblock `parameters` if i want to get parameters in mock scriptblock?

**Comment by nohwnd** [comment]
How the parameters are passed depends on what the scriptblock defines and what the function defines. But the bottom line is that there is currently no parameter to Mock that allows you to pass parameters from the test to the insides of the mockWith scriptblock. You can get variables there only by defining them in the upper scope. There is also a difference between where the parameter filter script block runs (in the test) and where the mockWith script block runs (in the module scope) when you define -ModuleName or mock a function from a module. Yes, it is a bit complicated and I currently work on adding explicit parameters to pass values into the parameter filter and mock with to make the code simple to understand.

**Comment by Jeffrey-zhao** [comment]
@nohwnd  thanks, it sounds very useful,now i am trying to add `param` for all `scriptblock` parts
