### ISSUE TITLE
5.0.0-alpha2: Feedback when running it on PSSA

### ISSUE THREAD

**Issue by bergmeister** [pester/Pester#1222]
I ran `5.0.0-alpha2` against PSSA's `development` branch [here](https://github.com/powershell/PSScriptAnalyzer) on PSCore 6.1.2, which one can do by just running `.\build.ps1; .\build.ps1 -Test`
The output log is attached at the end. The first failures might be hard to debug as they're probably quite test specific but common errors are around the `-skip` parameter that does not seem to be available any more. Is this by design?
```
Pester.Runtime\New-Block : A parameter cannot be found that matches parameter name 'skip'.
At C:\Users\cberg\Documents\PowerShell\Modules\Pester\5.0.0\Functions\Context.ps1:65 char:5
+     Pester.Runtime\New-Block -Name $Name -ScriptBlock $Fixture -Tag $ ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [New-Block], ParameterBindingException
+ FullyQualifiedErrorId : NamedParameterNotFound,New-Block
```

There also seem to be some Pester internal problems where it falls over:
```
At C:\Users\cberg\Documents\PowerShell\Modules\Pester\5.0.0\new-runtimepoc\Pester.Runtime.psm1:1353 char:9
+         throw "Did not find the block '$($Name)', how is this possibl ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Did not find th... this possible?:String) [], RuntimeException
+ FullyQualifiedErrorId : Did not find the block 'Test Invoke-ScriptAnalyzer with customized rules', how is this possible?
```

```
At C:\Users\cberg\Documents\PowerShell\Modules\Pester\5.0.0\new-runtimepoc\Pester.Runtime.psm1:1100 char:9
+         throw "Found more than one test that starts on line $($Script ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Found more than...de in one line?:String) [], RuntimeException
+ FullyQualifiedErrorId : Found more than one test that starts on line 286 and has Id '' (name: gets help for parameter: Range : in Invoke-Formatter). How is that possible are you putting all your code in one line?
```

```
lock AvoidUsingAlias failed Did not find the block 'Settings file provides whitelist', how is this possible?
At C:\Users\cberg\Documents\PowerShell\Modules\Pester\5.0.0\new-runtimepoc\Pester.Runtime.psm1:1353 char:9
+         throw "Did not find the block '$($Name)', how is this possibl ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Did not find th... this possible?:String) [], RuntimeException
+ FullyQualifiedErrorId : Did not find the block 'Settings file provides whitelist', how is this possible?
```

[PSSA_PesterLog.txt](https://github.com/pester/Pester/files/2776946/PSSA_PesterLog.txt)

I hope that helps and gives some feedback. Let me know if you need more specific information but I though that should be enough for the moment, especially since 5.0 is only in its early days.

**Comment by nohwnd** [comment]
@bergmeister I added the skip and pending params to It, and transformed the analyzer tests to put all code in Pester controlled blocks (I kept some strings out of it, but those are harmless). Now it can discover tests in almost all files, but not run them yet. The only offender is ` ModuleHelp.____Tests.ps1` that I renamed. I did not look too deep why it fails. I also had to change one place in the module code, because it fails to import the module twice, because an assembly of the same name is already loaded, not sure how to solve that ellegantly.

**Comment by nohwnd** [comment]
Changes to Pester v5.0 are pushed, and my changes to pssa [are here](https://github.com/nohwnd/PSScriptAnalyzer/tree/pester-v5-compatibility).

**Comment by nohwnd** [comment]
I don’t think you need to do that for a while, I first need to make the setups work similarly to how they work in v4 (so they setup before the first It or Describe), and make them recursive, and also make mocks recursive.  And then I can start attempting to run your tests. So merging upstream is not critical :)

**Comment by nohwnd** [comment]
migtated
