### ISSUE TITLE
Pester version on NuGet gallery is not up-to-date

### ISSUE THREAD

**Issue by Outlivier** [pester/Pester#1228]
Hi, 

The last Pester version available on [NuGet Gallery](https://www.nuget.org/packages/Pester) is 4.4.1 (and not 4.6.0).

Is the distribution via the NuGet Gallery is abandoned or is it an anomaly ?

**Comment by nohwnd** [comment]
Anomaly, I forgot to publish there when I changed build process. Sorry. Will fix over the weekend hopefuly.

**Comment by clcaldwell** [comment]
Both the version on Nuget and the PSGallery are 4.8.0 . This issue should be closed.
