### ISSUE TITLE
TestRegistry documentation is missing

### ISSUE THREAD

**Issue by renehernandez** [pester/Pester#1236]
The *TestRegistry* drive is released since version 4.5.0, but there is no documentation of it in the wiki. 

Could the documentation be similar to [TestDrive](https://github.com/pester/Pester/wiki/TestDrive) or even integrated in that wiki page?

Or would the differences  require a completely separated wiki page?

**Comment by nohwnd** [comment]
I think new page with the basics, and possibly linking back to testDrive for the moree advanced parts would be easy to write and discoverable.

**Comment by deejaygraham** [comment]
I'd like to volunteer for this one.

**Comment by nohwnd** [comment]
@deejaygraham it's all yours :)

**Comment by deejaygraham** [comment]
done.
