### ISSUE TITLE
v5: Problem with Pester TestDrive in v5-alpha2?

### ISSUE THREAD

**Issue by fourpastmidnight** [pester/Pester#1249]
## 1. General summary of the issue

When using the Pester TestDrive, I'm getting an error after running my tests. The error doesn't cause the test to fail, but it is unsightly 😉:

```text
0 scenarios
0 steps
0m0.000s
      [+] Returns 0 scenarios and 0 steps executed taking 0m0.000s 138ms
Remove-Item : Cannot remove item C:\Users\<MyUsername>\AppData\Local\Temp\bdba0435-055b-4ffb-86b0-23450388a395: The process cannot access the file 'C:\Users\Craig\AppData\Local\Temp\bdba0435-055b-4ffb-86b0-23450388a395' 
because it is being used by another process.
At D:\Projects\GitRepos\Pester\Functions\TestDrive.ps1:137 char:9
+         & $SafeCommands['Remove-Item'] -Path $Path -Force -Recurse
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\<MyUsername>\...b0-23450388a395:DirectoryInfo) [Remove-Item], IOException
    + FullyQualifiedErrorId : RemoveFileSystemItemIOError,Microsoft.PowerShell.Commands.RemoveItemCommand
Tests completed in 2.68s
Tests Passed: 3, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0
```

## 2. Describe Your Environment
Pester Version: 5.0.0-alpha2
PowerShell Version: 5.1
Windows: Windows 10, October 2018 Update

## 3. Current Behavior

Here's the test I'm trying to run. I'm thinking I'm using the TestDrive incorrectly.

```powershell
Describe 'Invoke-Gherkin3' {
    Context 'A ./features directory is present with no feature files' {
        #BeforeEach {
        #    $CWD = Get-Location -PSProvider FileSystem
        #    Set-Location $TestDrive
        #}

        #AfterEach {
        #    Set-Location $CWD
        #}

        It 'Returns 0 scenarios and 0 steps executed in 0m0.000s' {
            # Adding a try/finally block since BeforeEach/AfterEach seem not to be working as expected
            #try {
            #   $CWD = Get-Location -PSProvider FileSystem
            #   Set-Location $TestDrive
            In $TestDrive {
                Invoke-Gherkin3 -Init

                $Results = Invoke-Gherkin3 -PassThru
            #} finally {
            #    Set-Location $CWD
            #}

                $Results | Should -Not -BeNullOrEmpty
                $Results.TotalScenarios | Should -BeExactly 0
                $Results.TotalSteps | Should -BeExactly 0
                $Results.TestRunDuration | Should -Be ([TimeSpan]::Zero)
            }
        }
    }
}
```

I first tried using `BeforeEach` and `AfterEach` to get into the TestDrive path, and after the test, leave the path before everything was torn down. But that wasn't working, so I then tried using a try/finally directly inside the `It` block. But the same error occurred. **UPDATE**: The code above is updated to show me also using the `In { .. }` block, which I didn't know about until I saw it elsewhere in Pester. The same error occurs when using that, too.

## 4. Expected Behavior

I expected that calling `Set-Location $CWD` inside the `It`, or at latest inside some `After*` block prior to the test being torn down would result in the Test Drive being successfully cleaned up.

## 5. Possible Solution

Even if I hadn't left the TestDrive location, the framework should probably handle ensuring that you are not left in the Test Drive so that it can be correctly cleaned up after the test run (assuming that this is not, in fact, occurring currently due to the current behavior I'm experiencing).

## 6. Context

This seems like it _could_ be related to #986, except that I'm not creating/using a `FileSystemWatcher`. But the error is exactly the same. However, the error in my case is persistent.

**Comment by nohwnd** [comment]
I can't replicate this in alpha2 nor alpha3. To me it looks like you have something using the resource, exactly as the error says. This is what I am using to reproduce the error: 

```powershelll
Describe 'A describe' {
    BeforeAll {
       Push-Location 'TestDrive:\'
    }

    Context 'Context 1' {
        It 'Some test here' {
            $true | Should -Be $true
        }
    }

    Context 'Cotnext 2' {
        It 'Another test here' {
            $true
        }
    }
}

Pop-Location
```

**Comment by nohwnd** [comment]
Please re-open if you get more info. I haven't seen this issue a single time I am working on v5 :)
