### ISSUE TITLE
The Should operator BeGreaterThan/BeGreaterOrEqual fails on comparing [Version]

### ISSUE THREAD

**Issue by johlju** [pester/Pester#1261]
## 1. General summary of the issue

When comparing `[Version]` the Should operator fails with an error.

Code to reproduce:

```powershell
Describe 'Test' {
    Context 'When' {
        It 'Test 1' {
            1 | Should -BeGreaterThan 0
        }

        It 'Test 2' {
            [Version] '10.0.0.0'  | Should -BeGreaterThan [Version] '9.0.0.0'
        }

        It 'Test 3' {
            [Version] '10.0.0.0' | Should -BeGreaterOrEqual [Version] '9.0.0.0'
        }

        It 'Test 4' {
            $isCorrectVersion = [Version] '10.0.0.0' -ge [Version] '9.0.0.0'
            $isCorrectVersion | Should -BeTrue
        }
    }
}
```

## 2. Describe Your Environment

```powershell
Pester version     : 4.7.2 C:\Program Files\WindowsPowerShell\Modules\Pester\4.7.2\Pester.psd1
PowerShell version : 5.1.18850.1000
OS version         : Microsoft Windows NT 10.0.18850.0
```
## 3. Expected Behavior

Two variables of type `[Version]` should be able to be compared.

## 4.Current Behavior

Fails with the errors below.

```
Describing Test

  Context When
    [+] Test 1 4ms
    [-] Test 2 3ms
      ParameterBindingException: Parameter 'BeGreaterThan' cannot be specified in parameter set 'Legacy'.
    [-] Test 3 3ms
      ParameterBindingException: Parameter 'BeGreaterOrEqual' cannot be specified in parameter set 'Legacy'.
    [+] Test 4 7ms
```

## 5. Possible Solution

None. *I have no looked at the code.* 

## 6. Context

Workaround is to use something similar to `Test 4` in the example code above.

**Comment by dlwyatt** [comment]
Looks like you’re just missing parentheses around ([version]’whatever’) on your command lines.

**Comment by johlju** [comment]
@dlwyatt Thanks! I like easy solutions. 😄 This works perfectly `[Version] '10.0.0.0' | Should -BeGreaterOrEqual ([Version] '9.0.0.0')`. Didn't even thought about it since I didn't need to write it like that when using `-ge`, but guess it tries to use both statements as parameters. 🙂
