### ISSUE TITLE
Tags on Blocks do not make them run

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#1267]
in v3-alpha filtering on tag that is on describe does not run it's child tests. It's probably because having $true filter pass on the parent is not inherited to the children when they are maybed ($null) but not rejected ($false). 

```powershell
$result = Invoke-Pester -ScriptBlock {
    Describe 'Passing test cases' -Tag 'a', 'b' {

        It 't1' -Tag 'c', 'd', 'e' {
            $true | Should -Be $true
        }

        It 't2' -Tag 'f' {
            $true | Should -Be $true
        }
    }
    Describe "a" {
        It "throw" { throw }
    }
} -PassThru -tag 'b'


"Describe tags: $($result.Blocks[0].Tag -join ', ')"
"it1 tags: $($result.Blocks[0].Tests[0].Tag -join ', ')"
"it2 tags: $($result.Blocks[0].Tests[1].Tag -join ', ')"
```

**Comment by fourpastmidnight** [comment]
In Gherkin, you had a Convert-Tags function that propagated all the tags from Features down to Scenarios. Could you use a similar mechanism here?

**Comment by nohwnd** [comment]
This is fixed in v5.
