### ISSUE TITLE
Pester v5:  invoke-Pester -Path doesn't execute pester scripts without .Tests.ps1 in their name.

### ISSUE THREAD

**Issue by Stephanevg** [pester/Pester#1271]
## 1. General summary of the issue

This is concerning pester v5. I was just playing around with it a bit, so, if this is already a know issue, please forgive me for opening another issue.

Example:

`C:\MyTestfile.ps1`

Containing a simple test:

```powershell
Context "Context Block"{

    Describe "My Describe Block"{

        it "simple it block"{
            $true | should be $false
        }

        it "Second it block"{
            $true | should be $false
        } -Pending
        
    }
}

```

When I do:

```powershell
invoke-pester -Path `C:\MyTestfile.ps1`

```

this is the output:

![image](https://user-images.githubusercontent.com/6302961/54885759-182ea000-4e80-11e9-955f-c1c172e50c24.png)

## 2. Describe Your Environment

Operating System, Pester version, and PowerShell version:

```powershell
Pester version     :  pester v5 -> Master branch
PowerShell version : 5.1.16299.967
OS version         : Microsoft Windows NT 10.0.16299.0

```

## 3. Expected Behavior

It should launch tests, as in Pester v4.

## 4.Current Behavior

See above

## 5. Possible Solution

I don't have a fix for this (yet?) but I am pretty confident the source of this is located in 'Find-RSpecTestFile` located in `Pester.RSpec.psm1`

we could potentially remove the -filter `*.Tests.ps1` in the find-RSPectTestFile when `-Path` is used on invoke-Item. And use it when the `-Path` is not used.

Cheers

**Comment by nohwnd** [comment]
Thanks for reporting, I’ll fix it :)

**Comment by nohwnd** [comment]
And yes, it’s a problem of the code you pointed out.

**Comment by nohwnd** [comment]
Fixed
