### ISSUE TITLE
NunitXml does not reflect proper status of non-passing scenarios

### ISSUE THREAD

**Issue by fourpastmidnight** [pester/Pester#1285]
## 1. General summary of the issue

As I continue to work on PR #1276, I discovered that the NUnitXml emitted for Gherkin-style tests does not emit it in such a way that scenarios with failing steps appear as failed `test-suite`s. And this would also go for Pending and Undefined scenarios (which would probably both be Inconclusive for Nunit??).

This is more of a "note to self" to fix this on the Gherkin side of things once the initial scope for PR #1276 is complete. I will fix this as part of PR #1276 since I'm in there making a good amount of changes.

## 2. Describe Your Environment

All that's relevant here is the version of Pester, which is the latest 4.x version.

## 3. Expected Behavior

If you were to clone and build the [NUnit-HTML-Report-Generator](https://github.com/JatechUK/NUnit-HTML-Report-Generator) project, and assuming it's local to the directory where you're running your Pester tests from, and then execute the following:

```powershell
Import-Module .\Pester.psd1
Invoke-Gherkin .\Examples\Gherkin\JustForReporting1.feature -OutFile TestResults-temp.xml
.\NUnitHtmlReportGenerator.exe TestResults-temp.xml TestResults-temp.html
```

When you open the generated `TestResults-temp.html` file in your browser, **Scenario 2 [Example 1 1]** and **Scenario 3** should display as Failed.

## 4.Current Behavior

Instead, _ALL_ scenarios show as Passed.

## 5. Possible Solution

Fix NUnitXml report generation to properly show the true result of scenarios. If someone were to open up such a report (say, as generated for their CI build), they could misleadingly think that all scenarios are passing.

**Comment by fourpastmidnight** [comment]
@nohwnd Is it possible for you to assign this to me?

**Comment by fourpastmidnight** [comment]
You know, it would be more helpful if I actually attached a report showing the current behavior. Sorry about that. Find it attached. Just rip off the `.txt` extension.

[TestResults-temp.html.txt](https://github.com/pester/Pester/files/3040655/TestResults-temp.html.txt)

**Comment by nohwnd** [comment]
@fourpastmidnight it's all yours.

**Comment by glennsarti** [comment]
I'm seeing this on Pester 5.0.3 which was confusing at first.

For example, running `Invoke-Pester` in CI (Azure DevOps)

```
Starting discovery in 4 files.
Discovery finished in 356ms.
[+] /home/vsts/work/1/s/Tests/Scripts/Convert-CSVtoARMTemplate.Tests.ps1 3.35s (2.64s|519ms)
[-] /home/vsts/work/1/s/Tests/Scripts/Deploy-NSGAutomation.Tests.ps1 failed with:
CommandNotFoundException: The term '/home/vsts/work/1/s/Scripts/Convert-CSVtoArmTemplate.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
at <ScriptBlock>, /home/vsts/work/1/s/Scripts/Deploy-NSGAutomation.ps1:60
at <ScriptBlock>, /home/vsts/work/1/s/Tests/Scripts/Deploy-NSGAutomation.Tests.ps1:6
[+] /home/vsts/work/1/s/Tests/Scripts/Resolve-AzureIP.Tests.ps1 885ms (688ms|168ms)
Tests completed in 4.44s
Tests Passed: 39, Failed: 12, Skipped: 0 NotRun: 0
Container failed: 1
  - /home/vsts/work/1/s/Tests/Scripts/Deploy-NSGAutomation.Tests.ps1
```

Note it was 39 Passed and 12 Failed tests.

However when Azure DevOps processes the NUnintXML file it gets

```
Result Attachments will be stored in LogStore
Run Attachments will be stored in LogStore
Async Command Start: Publish test results
Publishing test results to test run '152'.
TestResults To Publish 39, Test run id:152
Test results publishing 39, remaining: 0. Test run id: 152
```

I haven't managed to pare-down the test suite so I can use it as a issue reproduction yet

**Comment by glennsarti** [comment]
Trouble is this isn't Gherkin related.  @nohwnd Did you want me to create a new, but related, issue for this?

**Comment by nohwnd** [comment]
@glennsarti  yes pls.
