### ISSUE TITLE
Deserialized Type Cannot Be Mocked

### ISSUE THREAD

**Issue by luckerby** [pester/Pester#1288]
```
Pester version     : 4.7.3 C:\Program Files\WindowsPowerShell\Modules\Pester\4.7.3\Pester.psd1
PowerShell version : 5.1.17134.590
OS version         : Microsoft Windows NT 10.0.17134.0
```
I've used Pester successfully to mock functions from the Active Directory module. All working as expected.

Now I'm trying to use Pester against functions from a remote Powershell session, but I'm having trouble doing so. Case in point: trying to mock the Get-Mailbox cmdlet from within Exchange Online. 

Trying to create an object of the type Get-Mailbox returns - which is `Microsoft.Exchange.Data.Directory.Management.Mailbox` - fails to work as expected, as seen below.

```
PS C:\Users\malbert\Desktop\box\MockSpin> Invoke-Pester
Executing all tests in '.'

Executing script C:\Users\malbert\Desktop\box\MockSpin\myCode.Tests.ps1

  Describing Exactly 2 mailboxes returned
    [-] Ensure we only get 2 mailboxes 1.29s
      PSArgumentException: Cannot find type [Microsoft.Exchange.Data.Directory.Management.Mailbox]: verify that the assembly containing this type is loaded.
      at SpawnTestMailbox, C:\Users\malbert\Desktop\box\MockSpin\myCode.Tests.ps1: line 4
      at ExecuteBlock, C:\Program Files\WindowsPowerShell\Modules\Pester\4.4.2\Functions\Mock.ps1: line 1123
      at Invoke-Mock, C:\Program Files\WindowsPowerShell\Modules\Pester\4.4.2\Functions\Mock.ps1: line 966
      at <ScriptBlock><Process>, <No file>: line 118
      at GetDaveyMailbox, C:\Users\malbert\Desktop\box\MockSpin\Functions.myCode.ps1: line 2
      at <ScriptBlock>, C:\Users\malbert\Desktop\box\MockSpin\myCode.Tests.ps1: line 18
Tests completed in 1.29s
```

Though the PSSession towards Exchange Online has been imported locally, most likely the trouble is that only the results are passed down the wire, and re-hydrated on my machine. Thus the type returned by Get-Mailbox is:

```
PS C:\Users\malbert\Desktop\box\MockSpin> get-mailbox JohnDoe | gm

   TypeName: Deserialized.Microsoft.Exchange.Data.Directory.Management.Mailbox
```

For Active Directory, it's a whole different issue, since I'm using the locally loaded PS module, thus the type required for provisioning a user (`Microsoft.ActiveDirectory.Management.ADUser`) is readily available, and Pester has no issue building mocks based on such objects.

Any way I can "point" Pester to the type for the Get-Mailbox cmdlet ?

**Comment by nohwnd** [comment]
@luckerby hard to guess what you are doing in the test :) Can you show me a simple test code that would replicate the issue so I can get some idea? To me it seems that you simply don't have that type that you are creating. 

If you have the `Get-Mailbox` cmdlet locally then you should be able to look at the types it uses as output types quite easily. `Get-Command Get-Mailbox` will show you the c# type and the assembly that implements the cmdlet functionality. Process or EndProcessing methods then will use the appropriate return types.

**Comment by luckerby** [comment]
@nohwnd: Indeed, I didn't give out much info :) My mistake. Let us address this: based on the model shown [here](https://devblogs.microsoft.com/scripting/testing-script-modules-with-pester/), and my own successful experimenting with the ActiveDirectory module, I've built 2 files:

First, the function that I'm using (mimicking some complex filtered parsing that one would expect in production):
```
function GetJoeMailbox {
    $mbx = Get-Mailbox joe*

    # Emit the mailboxes found
    $mbx
}
```

Secondly, the test itself:
```
. .\Functions.myCode.ps1

function SpawnTestMailbox([string]$displayName) {
    $mbx = New-Object Microsoft.Exchange.Data.Directory.Management.Mailbox
    $mbx.$DisplayName = $displayName

    return $mbx
}

Describe 'Exactly 2 mailboxes returned' {
    # Build mocks
    Mock Get-Mailbox {
        SpawnTestMailbox -DisplayName "John Doe"
        SpawnTestMailbox -DisplayName "John Carl"
    }

    It 'Ensure we only get 2 mailboxes' {
        (GetJoeMailbox | Measure-Object).count | Should -Be 2
    }
}
```

The problem is that the way Exchange Online cmdlets are used is through building a separate Powershell remote session, then importing it, like so:

```
$ps=New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://ps.outlook.com/Powershell -AllowRedirection -Authentication Basic -Credential (Get-Credential)
Import-PSSession $ps
```

Doing a `Get-Command Get-Mailbox` results in the following output (long list of arguments and end of function definition cut for readability):
```
PS C:\Users\malbert> Get-Command Get-Mailbox | fl


Name        : Get-Mailbox
CommandType : Function
Definition  :
                  param(
                  <...>
                  Begin {
                      try {
                          $positionalArguments = & $script:NewObject collections.arraylist
                          foreach ($parameterName in $PSBoundParameters.BoundPositionally)
                          {
                              $null = $positionalArguments.Add( $PSBoundParameters[$parameterName] )
                              $null = $PSBoundParameters.Remove($parameterName)
                          }
                          $positionalArguments.AddRange($args)

                          $clientSideParameters = Get-PSImplicitRemotingClientSideParameters $PSBoundParameters $True

                          $scriptCmd = { & $script:InvokeCommand `
                                          @clientSideParameters `
                                          -HideComputerName `
                                          -Session (Get-PSImplicitRemotingSession -CommandName 'Get-Mailbox') `
                                          -Arg ('Get-Mailbox', $PSBoundParameters, $positionalArguments) `
                                          -Script { param($name, $boundParams, $unboundParams) & $name @boundParams @unboundParams } `
                                       }

                          $steppablePipeline = $scriptCmd.GetSteppablePipeline($myInvocation.CommandOrigin)
                          $steppablePipeline.Begin($myInvocation.ExpectingInput, $ExecutionContext)
                      } catch {
                          throw
                      }
                     <...>
```
Essentially, the function looks to be a simple stub that invokes `Get-Mailbox` remotely (on the Exchange Online servers), passing the arguments received locally. There's not even a return type for the function.

Contrast the output above with the one returned by `Get-ADUser`, for which there's a specific return type and .NET assembly that implements its functionality.
```
PS C:\Users\malbert> Get-Command Get-ADUser | fl


Name             : Get-ADUser
CommandType      : Cmdlet
Definition       :
                   Get-ADUser -Filter <string> [-AuthType <ADAuthType>] [-Credential <pscredential>] [-Properties <string[]>] [-ResultPageSize <int>] [-ResultSetSize <int>] [-SearchBase
                   <string>] [-SearchScope <ADSearchScope>] [-Server <string>] [<CommonParameters>]

                   Get-ADUser [-Identity] <ADUser> [-AuthType <ADAuthType>] [-Credential <pscredential>] [-Partition <string>] [-Properties <string[]>] [-Server <string>]
                   [<CommonParameters>]

                   Get-ADUser -LDAPFilter <string> [-AuthType <ADAuthType>] [-Credential <pscredential>] [-Properties <string[]>] [-ResultPageSize <int>] [-ResultSetSize <int>]
                   [-SearchBase <string>] [-SearchScope <ADSearchScope>] [-Server <string>] [<CommonParameters>]


Path             :
AssemblyInfo     :
DLL              : C:\WINDOWS\Microsoft.Net\assembly\GAC_64\Microsoft.ActiveDirectory.Management\v4.0_10.0.0.0__31bf3856ad364e35\Microsoft.ActiveDirectory.Management.dll
HelpFile         : Microsoft.ActiveDirectory.Management.dll-Help.xml
ParameterSets    : {-Filter <string> [-AuthType <ADAuthType>] [-Credential <pscredential>] [-Properties <string[]>] [-ResultPageSize <int>] [-ResultSetSize <int>] [-SearchBase <string>]
                   [-SearchScope <ADSearchScope>] [-Server <string>] [<CommonParameters>], [-Identity] <ADUser> [-AuthType <ADAuthType>] [-Credential <pscredential>] [-Partition <string>]
                   [-Properties <string[]>] [-Server <string>] [<CommonParameters>], -LDAPFilter <string> [-AuthType <ADAuthType>] [-Credential <pscredential>] [-Properties <string[]>]
                   [-ResultPageSize <int>] [-ResultSetSize <int>] [-SearchBase <string>] [-SearchScope <ADSearchScope>] [-Server <string>] [<CommonParameters>]}
ImplementingType : Microsoft.ActiveDirectory.Management.Commands.GetADUser
Verb             : Get
Noun             : ADUser
```

So it's pretty clear why the error that the `Microsoft.Exchange.Data.Directory.Management.Mailbox` type is unknown gets thrown, however I'm not sure how can I actually get Pester to see the assembly where Get-Mailbox is defined, since that never makes it to my machine.

**Comment by rdbartram** [comment]
I've had similar issues when testing stuff with either SQL or AD types. You either need to replicate the class locally (as much as needed) or you need to make sure the dll is available. You could copy it out of the exchange server (probably isn't 100% legal) or you could make sure that the exchange management tools are installed on the machine where you run your tests. We haven't seen too much of your code, so I can't say where exactly you're using the types but if you're importing remotely, you can't strongly type params anywhere since powershell is serializing and deserializing. If you're just looking to return a object with a couple of properties similar to a mailbox, i would just use a pscustomobject. If you need methods you can use add-member but if you are strongly typing somewhere, you'll have to make sure the dlls are available during the pester run

**Comment by luckerby** [comment]
@rdbartram The code I'm using is rather straighforward and it's in my latest reply (my mistake for not placing this in the original post). I can't really get the .dlls used - or at least I think I can't - since we're talking about Exchange Online, not the on-premises version of Exchange, where one has access to the management tools. All I get back through the remote PS session is Desearialized.XXX types.

I wanted to avoid building a PSCustomObject if possible, given the resulting code would be much more readable as such.

**Comment by nohwnd** [comment]
Can't try it right now, but I think this is enough info for me to replicate it. I will try it in the evening or in couple of days. :)

**Comment by rdbartram** [comment]
As you say, all you're getting is a PSCustomObject back called Deserialized.XXX. Creating you're own PSCustomObject is really you're only option. I don't see too much of an issue with the readability and cleanliness of the code since you already have a SpawnTestMailbox function. If you really want to have all the properties available but don't want to see them all in the tests.ps1, you could write a ps class. Does make things a little complicated but at least standardised. Maybe @nohwnd comes back with a much cooler idea.

**Comment by nohwnd** [comment]
Looks like I never get chance to investigate this. So I am going with the suggestions above.
