### ISSUE TITLE
Cannot use ${function:}s for ParameterFilters anymore

### ISSUE THREAD

**Issue by sobjornstad** [pester/Pester#1291]
## 1. General summary of the issue

Sometimes I need to use a mock input in multiple places, so I will define it as a function. PowerShell allows you to refer to a function using the syntax `${function:MyFunctionName}` where the ScriptBlock would be expected. This worked great in previous versions of Pester.

As of pull request #1240, introduced 2 months ago, I can no longer specify a parameter filter using this syntax.

## 2. Describe Your Environment

```
Operating System, Pester version, and PowerShell version:
Pester version     : 4.7.2 C:\Users\e404sib\Documents\WindowsPowerShell\Modules\Pester\4.7.2\Pester.psd1
PowerShell version : 5.1.15063.1746
OS version         : Microsoft Windows NT 10.0.15063.0
```

While I have 4.7.2 on my system, the issue is also present in `master` as of today (commit `ead3cbd67e31b2994192b060558395e2313af859`).

## 3. Expected Behavior

The function is mocked with an appropriate parameter filter. Here is a minimal test case.

File `test.psm1`:

```
function Write-TestMessage ([string]$User) {
    Write-Output "Hi $User, this is the original function!"
}
```

File `test.Tests.ps1`:

```
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path).Replace('.Tests.ps1', '.psm1')
Import-Module -Force "$here\$sut"

Describe "Demonstration of the parameter filter bug" {
    $MY_USER = "Soren"

    function myTestMock {
        Write-Output "Mock output"
    }
    function myParameterFilter {
        "$User" -match $MY_USER
    }

    # Passes
    Context "The original unmocked function" {
        It "uses the output defined in the module" {
            Write-TestMessage -User $MY_USER | should -Be "Hi $MY_USER, this is the original function!"
        }
    }

    # Passes
    Context "This Mock works" {
        Mock Write-TestMessage ${function:myTestMock} -ParameterFilter {
            "$User" -match $MY_USER
        }

        It "uses the output defined in our mock" {
            Write-TestMessage -User $MY_USER | should -Be "Mock output"
        }
    }

    # Fails
    Context "This Mock throws an exception when created in the Context block" {
        Mock Write-TestMessage ${function:myTestMock} -ParameterFilter ${function:myParameterFilter}

        It "uses the output defined in our mock" {
            Write-TestMessage -User $MY_USER | should -Be "Mock output"
        }
    }
}
```

## 4. Current Behavior

An exception is thrown:

```
Context This Mock throws an exception when created in the Context block
      [-] Error occurred in Context block 0ms
        RuntimeException: You cannot call a method on a null-valued expression.
        at New-BlockWithoutParameterAliases, C:\Workspaces\Git\toolslang_powershell_TfsServerDeploy\pestertmp\Functions\Mock.ps1: line 1664
        at Mock, C:\Workspaces\Git\toolslang_powershell_TfsServerDeploy\pestertmp\Functions\Mock.ps1: line 350
        at <ScriptBlock>, C:\Workspaces\Git\toolslang_powershell_TfsServerDeploy\test.Tests.ps1: line 35
        at DescribeImpl, C:\Workspaces\Git\toolslang_powershell_TfsServerDeploy\pestertmp\Functions\Describe.ps1: line 199
```

## 5. Possible Solution

The error is on this line in master: https://github.com/pester/Pester/blame/master/Functions/Mock.ps1#L1664

I set a breakpoint here and it appears that with a true ScriptBlock, `$Block.Ast.EndBlock` is defined, but with a function there is no `Ast` member; instead, the same information is called `$Block.Body.Ast.EndBlock`. As a result, `$ast` is left null and the attempt to call the `.FindAll()` method on it yields the exception.

I don't know enough about PowerShell internals to know the best way to check for this case.

Off the top of my head, seems that it might be worth double-checking that closures work here as well, if you want to support them. I have not investigated.

## 6. Context

I don't think this is related to issue #1275 since it doesn't involve dynamic parameters, but that's the closest thing I see in open issues.

**Comment by nohwnd** [comment]
@renehernandez ideas?:)

**Comment by clcaldwell** [comment]
This should be relatively easy to fix.
 
    $( {Get-Service} ).Ast
is type [System.Management.Automation.Language.ScriptBlockAst]

While:

    function getsvc { get-service }
    $( ${function:getsvc} ).Ast

is type [System.Management.Automation.Language.FunctionDefinitionAst]

It might be as simple as adding this this line:

    if ($Block.Ast -is [System.Management.Automation.Language.FunctionDefinitionAst]) {
        $Block = $Block.Ast.Body
    }

I can verify this doesn't break anything elsewhere, and write up a PR with the fix and a test for this later this week, if no-one else beats me to it.
