### ISSUE TITLE
How to test parameter is prompt when missing?

### ISSUE THREAD

**Issue by edouard-lopez** [pester/Pester#1296]
I want to write a test in order to ensure a feature I'm adding will be preserved by future refactor.

The feature is to [prompt the user](https://github.com/edouard-lopez/lesspass-powershell/issues/20) for the value of the required parameter. Implementation is quite easy:

    [string][Parameter(Mandatory=$true)]$master_password,

But I don't know how to test this as my tests got stuck to the prompt if I don't provide said parameter:

```
Describing Get-LessPass

  Context Simple rule
    [+] Run 234ms
    [+] Expects length in [5-35] 22ms
cmdlet Get-LessPass at command pipeline position 1
Supply values for the following parameters:
master_password: <stuck-here>
```

Python has a `pexpect` module, does Pester has something similar ?

**Comment by edouard-lopez** [comment]
This might help https://www.powershellgallery.com/packages/Await/

> Await - A modern implementation of EXPECT for Windows. 
> For a demo, see: https://www.youtube.com/watch?v=tKyAVm7bXcQ

**Comment by ChrisLGardner** [comment]
The method I use is to check the parameter attributes to ensure Mandatory is still set:

`(Get-Command Blah).Parameteres['ParameterName'].Attributes.Mandatory | Should -Be $true`

Works very well for my needs.

**Comment by edouard-lopez** [comment]
Fixed thanks to @halbarad from Slack:

    It 'Prompt for MasterPassword when missing' {
        (Get-Command Get-LessPass).Parameters['master_password'].Attributes.Mandatory | Should -Be $true
    }
