### ISSUE TITLE
Old Powershell version support

### ISSUE THREAD

**Issue by clcaldwell** [pester/Pester#1302]
## 1. Roadmap for supporting older version of Powershell

Just opening this to have a discussion on what the plan is for future development of Pester, specifically on maintaining or dropping compatibility for older version of Powershell.

Do we have any plans to drop support for older versions of Powershell? It appears we support all the way back to Powershell 2.

Also for discussion - what are we missing by supporting older versions? Would using newer features make the code significantly faster, more maintainable, or have more complete features?

**Comment by clcaldwell** [comment]
To start this off, Windows Server 2008 SP2, which as far as I can find is the oldest, still currently supported OS available from Microsoft, allows for installation of Powershell 3. If we target Powershell 4 or 5, Pester could still be run on Windows Server 2008 R2 or Windows 7 SP1 .

Since Pester, as a Unit Test framework used by developers, is most likely to be run from either a relatively new build server, or from a developer's computer - I personally don't think we gain anything by supporting older versions. Is there anyone who is still developing PoSH code on Win XP or 2003?

**Comment by nohwnd** [comment]
Pester currently supports PowerShell 2+ and in version 5 will support PowerShell 3+. 

The important thing is that we can run tests the same way over the whole range of officially supported PowerShell versions. That way modules that run on any powershell can be tested via a single version of Pester.

**Comment by FISHMANPET** [comment]
Server 2008 and 2008 R2 will leave extended support in January of 2020.  To my knowledge, there are currently no supported Microsoft operating systems that will only support up to Powershell 2.  In January 2020 there will be no supported operating systems that only support Powershell 3.  So I'm wondering what the rationale is for currently supporting Powershell 2 (other than Powershell 2 was supported when 4.0 was released?) and depending on the timeline for 5.0, what the rationale would be for supporting 3.

Would it be reasonable to release 5.0 with support for 4 and up, and leave the 4.x branch in maintenance mode (major bug fixes only) until 2008 and 2008 R2 fully go out of support fully?

I know I've had to rewrite code in my one PR to support PS2, whereas in PS4 I could do something like `$collection.$attribute` to get `$attribute` of every item in $`collection`, to support PS2 I had to use `$collection | Select-Object -ExpandProperty $attribute`.

I just tried measure-command with a random 100 item collection I had in my environment, either way took about 2-7 Milliseconds so maybe that's not a great example, but I'm sure there others.

**Comment by nohwnd** [comment]
@FISHMANPET what you described is a powershell v3 feature.

I thought about it and I've already decided to support powershell v3 in pester v5, moving it on to powershell v4 does not bring anything in terms of functionality that would be critical for pester, but it  stops people from testing with it when they need to support all oficially supported versions of powershell.

**Comment by clcaldwell** [comment]
Targeting 5.X to PoSH 3 sounds reasonable to me.

Looking over [this page](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-windows-powershell-50?view=powershell-6) , I don't really see much that would make a difference to Pester between 3 & 4 - most of the changes / improvements to 4 deal with DSC / Remoting. 

PoSH 5.1 would probably add value ( Classes, improved runspace support/debugging), but the concern of allowing devs to test their module against all supported versions of PoSH makes sense.

**Comment by nohwnd** [comment]
Good, I am glad you agree. :)
