### ISSUE TITLE
Request: Add more options to Invoke-Pester -Show

### ISSUE THREAD

**Issue by f0rt** [pester/Pester#1304]
Team,

Please add more options to Invoke-Pester -Show parameter to be able to hide:
- Executing all tests in 'my.Tests.ps1' with Tags mytag
- Executing script mytest.ps1

This will make reports easier to read in some cases. For example when I re-run the same script file with different parameters like 100 times these strings add only noise to the output.

Thanks,
Nedko

**Comment by nohwnd** [comment]
Hi thanks for the suggestion, I don't thinks this will happen in v4, and it won't happen soon in v5 (not-released yet), there I changed the -Show to be Normal, Short and None, hopefully in the future there will be configuration where you can define what exactly you want.
