### ISSUE TITLE
String comparison message is not useful

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#1313]
In #532 the output of the string was changed to show only a short excerpt, this excerpt is too short that it is hard to tell where exactly the difference is, and the output is not useful when reviewing message that holds interesting data such as when comparing expected error messages.

I think that a better approach would be to return to the previous functionality combined with a much longer excerpt. 

The host size could be used to determine how wide the output should be, or a sensible default of 80 characters. 

As a first step I would make the excerpt longer to make it a bit more useful.

**Comment by alan0609** [comment]
I am hitting this same problem.  Is it possible to have the full string (or at least more of it) shown as an option?  Possibly when the output verbosity is set to detailed or adding a dedicated configuration item for it?  I am working on a project with very long strings (HTML) and it is often hard to pinpoint the location from the small snippet.
