### ISSUE TITLE
Don't use Mandatory Parameters. Instead throw if not provided

### ISSUE THREAD

**Issue by ghostsquad** [pester/Pester#132]
Mandatory parameters force a prompt if that parameter is not provided, which makes situations including when tests are NOT running hard to debug. Instead functions like "Describe" should throw an exception if specific mandatory parameters are not provided.

A recent project of mine had a malformed test. If you can find the bug, +extra credit.

``` powershell
Describe "Stuff" 
{
    It "should do stuff" {
        $true | Should Be $false
    }
}
```

**Comment by yecril71pl** [comment]
Please reopen, we have a regression in ``SHOULD -ERRORID:X`` (without ``-THROW``).

**Comment by ghostsquad** [comment]
@yecril71pl probably just file a new issue...
