### ISSUE TITLE
$emptyFile | Should -FileContentMatch '' fails

### ISSUE THREAD

**Issue by rjmholt** [pester/Pester#1320]
## 1. General summary of the issue

(Updated to working example)
```powershell
Describe "Empty file match" {
  BeforeAll {
    $filePath = "$TestDrive/empty.txt"
    New-Item $filePath
  }

  It "Exists but has no content" {
    # Also tried -FileContentMatchExactly and -FileContentMatchMultiline
    $filePath | Should -FileContentMatch ''
  }
}
```

## 2. Describe Your Environment

Operating System, Pester version, and PowerShell version:

```
Pester version     : 4.8.1 C:\Users\roholt\Documents\PowerShell\Modules\Pester\4.8.1\Pester.psd1
PowerShell version : 7.0.0-preview.1
OS version         : Microsoft Windows NT 10.0.18913.0
```

## 3. Expected Behavior

The test should pass

## 4.Current Behavior

Something like:
```
Expected <empty> to be found in file 'C:\Users\roholt\AppData\Local\Temp\f910d019-7456-48e4-b246-5f6d80e0cc45/3.txt', but it was not found.
At C:\Users\roholt\Documents\Dev\PowerShell\src\powershell-win-core\bin\Debug\netcoreapp2.1\win7-x64\publish\Modules\Pester\4.8.0\Functions\Assertions\Should.ps1:186 char:9
+         throw ( New-ShouldErrorRecord -Message $testResult.FailureMes ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidResult: (System.Collections.Hashtable:Hashtable) [], Exception
+ FullyQualifiedErrorId : PesterAssertionFailed
```

## 5. Possible Solution

Possible special case in the function?

## 6. Context

PowerShell codebase tests

**Comment by rjmholt** [comment]
Would be happy to submit a PR for this if that's desired :)

**Comment by renehernandez** [comment]
@rjmholt Your code does not work for me as is in PowerShell version 5.1 and 6.2.1. It throws a **ParseException** in the path definition. I had to change the code to:

```
Describe "Empty file match" {
  BeforeAll {
    $filePath = "$TestDrive/empty.txt"
    '' > $filePath
  }

  It "Exists but has no content" {
    # Also tried -FileContentMatchExactly and -FileContentMatchMultiline
    $filePath | Should -FileContentMatch ''
  }
}
```

And by using quotes, the test passes both in PS 5.1 and PS 6.2.1

Could this be an issue particularly with PS 7? We currently do not support it yet, but it is something that we need to start thinking about

**Comment by rjmholt** [comment]
Oh sorry, I tried to hard to come up with a nice-looking example. I just tried this one in 6.2:

```powershell
$path = "${env:TMP}/file.txt"; New-Item $path -Force; (Get-Item $path).Length | % { Write-Host "`n`n### File Length: $_ ###`n`n" }; $path | Should -FileContentMatchMultiline ''
```

**Comment by rjmholt** [comment]
> Could this be an issue particularly with PS 7

The example you've written also passes in PS7.

**But**, that's because I implemented it with a bug: `'' > $path` creates a file of length 2.

Creating an actual empty file with `New-Item $path` does not pass:

```powershell
Describe "Empty file match" {
  BeforeAll {
    $filePath = "$TestDrive/empty.txt"
    New-Item $filePath
  }

  It "Exists but has no content" {
    # Also tried -FileContentMatchExactly and -FileContentMatchMultiline
    $filePath | Should -FileContentMatch ''
  }
}
```

**Comment by rjmholt** [comment]
Just tested that one in 5.1.18913.1000, 6.2.1 and 7.0.0-preview.1 -- same result everywhere

**Comment by nohwnd** [comment]
I trying to understand what the value of such test is to understand what the desired result should be. And I am having a hard time. :)

What would be the expected result of file that has no content and you ask it to contain empty string?  (guessing result should be True)
What if the file has content? (Guessing True as well)

So looking at those any time I ask a file if it contains empty string the result should be True, which seems reasonable, we can see constant functions like this in many places (like any number * 0 = 0). And I am all for making it work properly. 

Now the thing is, when such a test returns a constant value no matter the input, what is the practical value of having such test?

**Comment by nohwnd** [comment]
Maybe this is also confusing because the functions uses `-match` (and hence regular expressions) to check the file content, and so `''` is just an empty string, and an empty string matches everywhere. 

```powershell
'abc' -match '' # -> true
'' -match '' # -> true
```

But you are trying to check that the file has no content, so in regex words there is nothing in between the start `^` and the end `$` of the content, and you'd match that like this:

```powershell
'abc' -match '^$' # -> false
'' -match '^$' # -> true
```

**Comment by rjmholt** [comment]
Here's the particular test: https://github.com/PowerShell/PowerShell/blob/bb535bcfb1ebdb0bb6c05bcdc506487b78b2c041/test/powershell/Language/Operators/BashControlOperator.Tests.ps1#L191-L216

> But you are trying to check that the file has no content, so in regex words there is nothing in between the start ^ and the end $ of the content, and you'd match that like this

Yeah I think you're quite right. Really I suppose this is more of a feature request to check literal file content; I don't know if Pester currently considers it more idiomatic to use `Get-Content -Raw ./file.txt | Should -BeExactly $expected` or `'./file.txt' | Should -FileContentMatchExactly $expected`. I want file testing without jumping straight into regex

**Comment by nohwnd** [comment]
@rjmholt both of them are fine, just different approaches. You don't need to use regex (but `- FileContentMatchExactly` still uses regex, just case sensitively, so keep that in mind) so you can just use `-BeExactly` or `-Be`.
