### ISSUE TITLE
Build on PowerShell 7

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#1328]
It would be nice to start building Pester on PowerShell 7 as well to see if it is compatible and keep it that way. To achieve that we need to research on which build servers v7 is already available. Right now we are building on TravisCI (Linux and MacOS), on AppVeyor (PowerShell 4+) and AzureDevOps (PowerShell 2&3).

Not sure if the build task needs to run on all three platforms, but it would be nice.

The change should apply to Pester v4, and then be adopted for v5 as well.

**Comment by kilasuit** [comment]
There's no reason you could not add a task in sideload v7 in either build service using the release zip deployment method and invoking pwsh from the extracted directory.

**Comment by fflaten** [comment]
I'd say the primary focus of this should be Pester v5 now.
@nohwnd considering you now build with local runners in AzDO only then you probably have to fix assign yourself :)

**Comment by nohwnd** [comment]
v5 CI already builds on every version since ps3. with PS 3, 4 and 6.2 being self-hosted and the rest is on hosted agents.
