### ISSUE TITLE
Infinite Pester run

### ISSUE THREAD

**Issue by DarkLite1** [pester/Pester#1331]
So I found a strange thing when there's a space at the ending of the filename of the test file. We had one file called 'Remove used printer ports .ps1' and it kept on repeating tests in an infinite loop. 

A more simple example to clarify things:

**Test.Tests.ps1**
```powershell
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path) -replace '\.Tests\.', '.'

Describe $sut {
    it 'should pass' {
        ."$here\$sut"
        1 | Should -Be 1
    }
}
```
Output:
```powershell
Describing Test.ps1
  [+] should pass 13ms
```

Now when we run the same file content but change the filename to '**Test.Tests .ps1**' there is different output than before:
```powershell
Describing Test.Tests .ps1

  Describing Test.Tests .ps1
    [-] should pass 57ms
      RuntimeException: You are already in a test case.
      RuntimeException: You are already in a test case.
      MethodInvocationException: Exception calling "EnterTest" with "0" argument(s): "You are already in a test case."
  [+] should pass 0ms
```

In this case it's only repeated once, But we had a case where the tests went on an infinite loop. Glad I saw the extra space at the end, Could've been bug hunting in a more complex file for a much longer time :)

**Comment by mikeclayton** [comment]
I think the problem is that in your second example, your test script is dot-sourcing itself, and then *that* tries to dot-source itself, then *that* does as well, etc, and there's your infinite recursion.

I tried your examples with the addition of a write-host to see what filename it's dot-sourcing...

**Tests.Test.ps1**

```Tests.Tests.ps1``` tries to dot-source ```Tests.ps1``` - I don't have this file on my system so the test fails, but presumably the file exists in your setup and works fine.

```text
C:\src\scratch\pester\issue-1331>powershell .\issue-1331.ps1
Executing all tests in '.\Tests.Tests.ps1'

Executing script .\Tests.Tests.ps1
*** dot-source filename is "C:\src\scratch\pester\issue-1331\Tests.ps1" ***

  Describing Tests.ps1
    [-] should pass 222ms
      CommandNotFoundException: The term 'C:\src\scratch\pester\issue-1331\Tests.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
      at <ScriptBlock>, C:\src\scratch\pester\issue-1331\Tests.Tests.ps1: line 8
Tests completed in 1.32s
Tests Passed: 0, Failed: 1, Skipped: 0, Pending: 0, Inconclusive: 0
```

**Tests.Test .ps1 (with a space)**

```Tests.Test .ps1``` tries to dot-source ```Tests.Test .ps1``` (i.e. itself) because your ```-replace '\.Tests\.', '.'``` doesn't replace anything in the filename.

```text
C:\src\scratch\pester\issue-1331>powershell .\issue-1331.ps1
Executing all tests in '.\Tests.Tests .ps1'

Executing script .\Tests.Tests .ps1
*** dot-source filename is "C:\src\scratch\pester\issue-1331\Tests.Tests .ps1" ***

  Describing Tests.Tests .ps1
C:\src\scratch\pester\issue-1331\Tests.Tests .ps1

    Describing Tests.Tests .ps1
      [-] should pass 452ms
        RuntimeException: You are already in a test case.
        RuntimeException: You are already in a test case.
        MethodInvocationException: Exception calling "EnterTest" with "0" argument(s): "You are already in a test case."
    [+] should pass 0ms
Tests completed in 1.3s
Tests Passed: 1, Failed: 1, Skipped: 0, Pending: 0, Inconclusive: 0
```

Hope this helps.

M
