### ISSUE TITLE
Test summary output displays all zeros

### ISSUE THREAD

**Issue by Cirzen** [pester/Pester#1336]
## 1. Summary
When using Invoke-Pester on a tests file containing a given number of tests, my summary output always displays that zero tests have been run (totalCount), zero pass, and zero fail, even when I can see in the output from the test file that this is not true.

## 2. Describe Your Environment
Operating System, Pester version, and PowerShell version:

Pester version     : 4.8.1 C:\Program Files\PowerShell\Modules\Pester\4.8.1\Pester.psd1
PowerShell version : 6.2.1                                                             
OS version         : Microsoft Windows NT 10.0.18362.0                                 

## 3. Expected Behavior

Given my test script:
TotalCount | Should be 22
PassedCount | Should be 21
FailedCount | Should be 1

## 4.Current Behavior

All values are zero:
![image](https://user-images.githubusercontent.com/13346199/61706722-b2282b80-ad40-11e9-931c-d89c7810a41f.png)

**Comment by nohwnd** [comment]
Thanks for reporting. Are you able to replicate this on a different version of PowerShell? Are you doing anything special in your tests? Like using InModuleScope or something? Could you provide a simple repro please?

**Comment by Cirzen** [comment]
Sorry Jakub, this appears to have been my error. I had "Import-Module Pester" as the first line in my test script, which I think was loading an earlier version of Pester (probably the one that comes pre-installed?)
I've removed that line and I get the expected results.
Closing and filing under PEBKAC :)

**Comment by nohwnd** [comment]
I was expecting something like that, it can also happen that you confuse Pester into running tests, which will run code that will not see the loaded Pester and will autoload other Pester which will run the test via "interactive mode" (when we invoke file with a `Describe` directly) which writes to the screen but the counting is done in a different instance of Pester, and so the result reports 0 tests run. :) 

I think the colors of the output should have been the giveaway. One more reason to add ASCII art banner before the tests run :D
