### ISSUE TITLE
Azure Build Pipeline Warning

### ISSUE THREAD

**Issue by alexrysgsprct** [pester/Pester#1339]
I'm using currently using the lastest version(8.13.3) on azure build pipeline and I'm getting this warning.

`[warning]Task 'Pester' (8.13.3) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib
Preparing task execution handler.`

how can I fix this?

**Comment by nohwnd** [comment]
@rfennel is this already reported in your repo?

**Comment by rfennell** [comment]
It is not reported for the Pester task, but it is a problem for all Azure DevOps tasks that have not been ported to the PS3 execution engine. I am currently addressing the problem with other tasks.

FYI: Though the code for this in my Github instance @ChrisLGardner does the support for the Pester task.

I wonder if this is good point to re-home this task and place it in this Pester Github instance?

This would mean depricating my copy in the marketplace and replacing with a new one (of the same code base) but supported from here?

This breaking change might be the right time?

**Comment by nohwnd** [comment]
Ah okay, I was originally thinking to ping Chris but then I saw your name, and was not sure if this is the task that Chris manages or a different one, and did not dig deeper. He actually wanted to talk with me about moving it here. I am going to talk with him about it. Thanks for the response.  :)

**Comment by rfennell** [comment]
No problem, the work should be 
- a tiny edit in the manifest to change the agent execution engine
- Update the way properties are read in, you used to use a param() call, now it is function
- Include the Azure DevOps SDK library to get the function

It should be simple, but the ones I have done thus far have had interesting knock on effects, never seem to be able to tell.

**Comment by ChrisLGardner** [comment]
I'll look at doing this later this week, to at least do the deprecation steps and update to v3. There's a few open issues on it that I should look at fixing too as part of the same work. 

I'll chat to @nohwnd about moving it over to the Pester org and setting up pipelines etc.

**Comment by renehernandez** [comment]
Will this be added as a separate repo under the Pester org?

**Comment by nohwnd** [comment]
Yes, more likely than adding it to the Pester repo. It should have its own release cycle, and should keep compatibility with Pester releases, rather than the other way around.

**Comment by ChrisLGardner** [comment]
This should be fixed in one of the releases of the original task and the new repo is over at https://github.com/pester/AzureDevOpsExtension. Should have a new version of the new extension out soon with various fixes in.

@nohwnd you can probably close this issue now.

**Comment by nohwnd** [comment]
@ChrisLGardner please link the release back in here once it is done, for future reference.

**Comment by ChrisLGardner** [comment]
Extension is now live at: https://marketplace.visualstudio.com/items?itemName=Pester.PesterRunner and the release on the repo is: https://github.com/pester/AzureDevOpsExtension/releases/tag/9.1.10

Version number is so high due to weird issues with installing it on organisations that had the other extension installed. So we'll just start from 9 and count up from there.

**Comment by rfennell** [comment]
Great I will blog about the change and get my old version deprecated

**Comment by ChrisLGardner** [comment]
Already working on the deprecation, will get that released soon and write up a short intro in the readme on the new repo about moving across.
