### ISSUE TITLE
CodeCoverage fails to exclude pester tests when using -Tag or -ExcludeTag

### ISSUE THREAD

**Issue by eedwards-sk** [pester/Pester#1349]
## 1. Overview

This is a follow-up to #1014

Pester fails to exclude its own test files when the list of tests is curated using `-Tag` or `-ExcludeTag`

## 2. Describe Your Environment

Operating System, Pester version, and PowerShell version:

```
Pester version     : 4.8.1 /Users/eedwards/.local/share/powershell/Modules/Pester/4.8.1/Pester.psd1
PowerShell version : 7.0.0-preview.2
OS version         : Unix 18.7.0.0
```

Given `-Tag 'foo'` or `-ExcludeTag 'foo'` in combination with `-CodeCoverage` and a list of files including test files (`*.tests.ps1`) and script files (`*.ps1`)

```
Invoke-Pester -CodeCoverage $ListOfScripts -ExcludeTag 'foo'
Invoke-Pester -CodeCoverage $ListOfScripts -Tag 'foo'
```

## 3. Expected Behavior

Test files are not in the coverage report.

## 4.Current Behavior

Test files are included in the coverage report.

## 5. Possible Solution

`¯\_(ツ)_/¯`

## 6. Context

I'm trying to leverage tags to distinguish between slow running system tests and fast unit tests. This throws a small 🔧 in there because I lose accurate coverage reporting.

**Comment by nohwnd** [comment]
This works in Pester, won't be fixing this in v4.
