### ISSUE TITLE
Issue using indexof method on a PSCustomObject in a function that is being tested

### ISSUE THREAD

**Issue by scott1138** [pester/Pester#1350]
## 1. General summary of the issue

My function pulls data from a CSV file then uses foreach to step through each record and confirm that specific fields meet desired criteria, like not null or empty.  When an issue is found a  noteproperty is added to the record with line number of the record.  I calculate the line number by adding 2 to the record's index in the array, accounting for the CSV header and ordinal numbering.  This works fine when I execute the function directly and I get the desired output.  It is only during the Pester test it presents a problem.

## 2. Describe Your Environment

Pester version     : 4.8.1 C:\Users\heaths\Documents\PowerShell\Modules\Pester\4.8.1\Pester.psd1
PowerShell version : 6.1.3
OS version         : Microsoft Windows NT 10.0.17763.0

-->

## 3. Expected Behavior

I expect the code to be executed and an array of bad data to be created and output using the OutVariable parameter so that I can analyze the output to confirm the correct data issue was caught.

## 4.Current Behavior

Receive this error:
[-] Detects issues with FirstName 20ms
        RuntimeException: Method invocation failed because [System.Management.Automation.PSCustomObject] does not contain a method named 'IndexOf'.
        at New-FreemanUser, C:\git\FreemanUtilities\FreemanUtilities\New-FreemanUser\New-FreemanUser.ps1: line 152
        at <ScriptBlock>, C:\git\FreemanUtilities\FreemanUtilities\New-FreemanUser\tests\New-FreemanUser.tests.ps1: line 30

## 5. Possible Solution

Sorry, I got nothing.  : (

## 6. Context

Just trying to validate that given a specific set of data that is known to be bad it is caught and identified to the end user correctly.

**Comment by scott1138** [comment]
Just wanted to add that in addition to $Array.IndexOf($Object) - which has been my standard method for this sort of thing - I tried [array]::IndexOf($Array,$Object) and get a similar error.

[-] Detects issues with FirstName 16ms
        MethodException: Cannot find an overload for "indexof" and the argument count: "2".
        at New-FreemanUser, C:\git\FreemanUtilities\FreemanUtilities\New-FreemanUser\New-FreemanUser.ps1: line 152
        at <ScriptBlock>, C:\git\FreemanUtilities\FreemanUtilities\New-FreemanUser\tests\New-FreemanUser.tests.ps1: line 30

**Comment by scott1138** [comment]
I was able to resolve the issue using the following method:
`$Users = @(Import-Csv -Path $UserFile)`
I tried declaring $Users as an array, but it didn't like that.  So while this isn't a Pester question, I'd really like to know what the suggestions might be for this.

**Comment by nohwnd** [comment]
The error tells you that `IndexOf` cannot be found on type `PSCustomObject`. Are you mocking the function that returns the output and simply returning the wrong type (or possibly just a single item)? The `IndexOf` method is present on collections, so theoretically you are just not returning array. Plus the powershell unwraps the array on function return if I remember correctly, so you need to wrap it twice for single item or something like that: 
 
In a simplfied example:
```powershell
function a { [PsCustomObject]@{ Name = "jakub" } }
$a = a
$a.IndexOf(1)
```
Fails with `Method invocation failed because [System.Management.Automation.PSCustomObject] does not contain a method named 'IndexOf'.`

```powershell
function a { ,(,([PsCustomObject]@{ Name = "jakub" } )) }
$a = a
$a.IndexOf(1)
```
Note the extra `,(,( ))` in the code which wraps it in two arrays.

**Comment by mikeclayton** [comment]
Import-Csv returns a System.Management.Automation.PSCustomObject if there's only one row in your input file. or a System.Object[] if there's more than one row:

**single-row.csv**
```
"col1", "col2", "col3"
"aaa", "bbb", "ccc"
```

**multple-rows.csv**
```
"col1", "col2", "col3"
"aaa", "bbb", "ccc"
"xxx", "yyy", "zzz"
```

**test**
```
PS> $s = import-csv ".\single-row.csv"
PS> $s.gettype().fullname
System.Management.Automation.PSCustomObject

PS> $m = import-csv ".\multiple-rows.csv"
PS> $m.gettype().fullname
System.Object[]
```

In the first example, wrapping the ```import-csv``` in ```@( ... )``` converts the PSCustomObject into an System.Object[] array that contains one item - the original PSCustomObject. The resulting array now has an ```IndexOf``` method that you can call.

There's also another "feature" in PowerPoint where it will "unroll" arrays that contain a single item when you return them from a function - it will remove the outer array and just return the first item:

```
PS> function Invoke-Unroll { $result = @(1); return $result; }
PS> write-host (Invoke-Unroll).GetType().FullName
System.Int32 # i.e. the literal value 1
```

You can work around this by wrapping your value in a "sacrificial array" (see https://stackoverflow.com/questions/28702588/in-what-conditions-does-powershell-unroll-items-in-the-pipeline for origins of the term) to stop PowerShell modifying your original value:

```
PS> function Invoke-DontUnroll { $result = @(1); return @(, $result); }
PS> write-host (Invoke-DontUnroll).GetType().FullName
System.Object[] # i.e. the array @( 1 )
```

If you're returning an array from a Pester Mock function you might need to wrap your current return value in a "sacrificial array" so PowerShell returns your original array *after* it's "helpfully" unrolled the sacrificial array for you...

**Comment by scott1138** [comment]
@mikeclayton Ah, that must be it.  My Pester test data was just a single item CSV.  When I was executing the process manually I was using a CSV I had pre-populated with other test scenarios.  To prevent the issue from happening with single item CSV input in the future I just cast the Import-CSV results as an array immediately.  Thank you for pointing that out!

**Comment by mikeclayton** [comment]
No worries. Glad it helped :-)
