### ISSUE TITLE
PSBreakpoint make Pester tests extremely slow

### ISSUE THREAD

**Issue by ili101** [pester/Pester#1352]
## 1. General summary of the issue
When session have any type of PSBreakpoint Pester becomes extremely slow even when the break point never gets activated and even when it's outside the test.
## 2. Describe Your Environment
Pester version     : 4.8.1 D:\ILI\Profile\Documents\WindowsPowerShell\Modules\Pester\4.8.1\Pester.psd1
PowerShell version : 5.1.17763.592
OS version         : Microsoft Windows NT 10.0.17763.0
## 3. Expected Behavior
Breakpoint will not effect preference.  
## 4.Current Behavior
``` Powershell
Set-PSBreakpoint -Variable NotEvenUsed
Describe 'Test' {
    for ($i = 0; $i -lt 10; $i++) {
        Context 'Context' {
            It "10 Tests" {
                1 | Should -Be 1
            }
        }
    }
}
```
Test with the Breakpoint takes ~20 Seconds, Without it it's less then ~100 Milliseconds

**Comment by nohwnd** [comment]
Thank you for the report, this issue affects some builds of windows and is reported in issue #1318. It should currently be fixed in the latest beta of PowerShell 7 and later back-ported to PowerShell 5.1 (without any promises about when that will be done).

**Comment by ili101** [comment]
Thank you, Somehow didn't see this issue. I can confirm that with the Nightly version the test is only twice as slow for my code instead of 25 times slower 👍
