### ISSUE TITLE
How to install Pester on Windows Server 2012R3/PowerShell 4

### ISSUE THREAD

**Issue by aenagy** [pester/Pester#1358]
## 1. General summary of the issue
I am unable to use the instructions at https://github.com/pester/Pester/wiki/Installation-and-Update.

## 2. Describe Your Environment

Pester version     :
PowerShell version : 4.0
OS version         : Microsoft Windows NT 6.3.9600.0

## 3. Expected Behavior

How to install Pester on Windows Server 2012 R2/PowerShell 4.

## 4.Current Behavior

PS C:\Users\UserName\Desktop> Install-Module -Name Pester
Install-Module : The term 'Install-Module' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Install-Module -Name Pester
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Install-Module:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Is there some way to install this from the zip file (https://github.com/pester/Pester/archive/master.zip)? If so, how?

Using this link (https://docs.microsoft.com/en-us/powershell/gallery/installing-psget#get-powershellget-module-for-powershell-versions-30-and-40) doesn't help as this has a dependency on PowerShellGet (https://docs.microsoft.com/en-us/powershell/gallery/installing-psget#get-powershellget-module-for-powershell-versions-30-and-40) which in turn has a dependency on "PackageManagement MSI" (https://www.microsoft.com/download/details.aspx?id=51451) which results in "We're sorry, this download is no longer available."

## 5. Possible Solution

Need steps to install Pester.

## 6. Context

Trying to install and run GetSTFolderSize (https://github.com/EliteLoser/GetSTFolderSize)

**Comment by nohwnd** [comment]
Not an expert on various Windows Server versions, but PowerShell 4 should ship with the Install-Module capability so you can install modules easily from the PowerShell Gallery. So it is possible that someone removed from your system, or you have Module auto loading disabled and so you have the module available locally but it does not load when you issue the Install-Module command. 

You can totally install it from the zip file. A guide to installation is [available here](https://github.com/pester/Pester/wiki/Installation-and-Update#installing-from-sources).

**Comment by Monte-Hazboun** [comment]
PowerShellGet is an seperate installation on PS3/4.   Install Module only works natively on PS5+

https://github.com/PowerShell/PowerShellGet/blob/development/README.md

**Comment by fflaten** [comment]
Closing. Fixed dead link and install manually-steps @ https://pester.dev/docs/introduction/installation  in pester/docs#111
