### ISSUE TITLE
Mock not working in 5.1 but does in 6+

### ISSUE THREAD

**Issue by ChrisLGardner** [pester/Pester#1359]
## 1. General summary of the issue

I have the following test file (and another similar one with the same mock in it): https://github.com/ChrisLGardner/ArmTemplateValidation/blob/90eac193039726e7f7dce708b2269f0a7a760ba9/tests/unit/030-TemplateParameterAst.Tests.ps1 but when I run it locally or via Azure Pipelines the mock isn't working in Win PS but does in PS Core and PS 7. 

When I debug into it the mock exists in the scope of the test but as soon as I step into my method it is no longer there. I've not seen this behaviour before, I'd expect it to either fail for all platforms or work on all platforms.

## 2. Describe Your Environment

Pester 4.8.1 on Win PS 5.1, PS Core 6.2.x and PS 7.

## 3. Expected Behavior
Mock works correctly on all platforms

## 4.Current Behavior

See this Azure Pipelines build for current behaviour: https://halbaradkenafin.visualstudio.com/Github/_build/results?buildId=805

## 6. Context

I could merge the PRs I've got open where I'm seeing this behaviour as it's not really a blocker (knowing that it'll do what I want) but I'd prefer to get to the bottom of what's going on here and only merge if I really need to.

**Comment by nohwnd** [comment]
I am trying to figure out what is wrong with this but I don't see any fail related to mock. The tests only fail with: 

![image](https://user-images.githubusercontent.com/5735905/64485455-7d553280-d221-11e9-9ed4-e1c08d988351.png)

Where the ${function} seems to expand into a name of the function that does not exist. 

Or they fail with expecting single ast object but getting an array of them, which is a different type. 
![image](https://user-images.githubusercontent.com/5735905/64485476-b68da280-d221-11e9-8d62-936e03a04d6f.png)

Could you point me to the relevant failure? Maybe I am just looking into a wrong place :)

**Comment by ChrisLGardner** [comment]
That first one is the issue as it should have mocked out the function that would normally call that, if you check line 114 in the logs on any of the pwsh builds then it's correctly mocked it and passed the test correctly.

**Comment by nohwnd** [comment]
This is for Pester 4, let me know if the same problem occurs in v5.
