### ISSUE TITLE
Suggestion: Create a new block to wrap non-testing (ie setup) code so it can output execution time to the console

### ISSUE THREAD

**Issue by stetan** [pester/Pester#1366]
## 1. General summary of the suggestion
When running Pester tests, it's great to see how long each test takes, but it would also be nice to see how long the code part takes so that you can see total execution times from test-to-test, not just how long individual "it" tests took as they can be the quick parts.

For example, I'm doing integration testing whereby the code i'm testing runs against the real system. 

Eg: 
Describe "Test deploying my custom VM" {
  $MyNewVM = New-MyCustomVM @ParameterInput

  It "deploys my custom VM" {
    $MyNewVM.Name | Should -be 'MyTestVM'
  }
 (etc ...)
}

Whilst we get timing for the "It" blocks, we have no visibility of the effects of changes in relation to how long my "New-MyCustomVM" cmdlet takes to execute. This is a crucial part of testing.

I've tried nesting "It" blocks so that scoping outputs flows, but pester complains about that.

## 2. Possible Solutions:

Something along the lines of the "It" block so it can have tags and a name, call it "Code" or something? (I'm sure there'd be a better name.)

Or could extend upon the existing "It" block and add an extra parameter eg. -Code or something like that.

Although the issue with having it inside it's own "Code" block is one of scope. The $MyNewVM is not visible outside of it with the current way Pester does scopes.

Any other ideas?

Eg's: 
Describe "Test deploying my custom VM" {
    It -RunCode "deploys my custom VM" {
        $MyNewVM = New-MyCustomVM @ParameterInput
    }

    Code "deploys my custom VM" {
        $MyNewVM = New-MyCustomVM @ParameterInput
    }

    It "deployed my custom VM" {
        $MyNewVM.Name | Should -be 'MyTestVM'
    }
 (etc ...)
}

**Comment by nohwnd** [comment]
I won't be adding that because it does not fit in how v5 does setups and counts the time, but if you wanted you could implement it yourself, you just need to do few clever tricks to make sure your code imports outside of the function not in it. https://www.youtube.com/watch?v=6d0K2i7pgQs the content in this talk should give you some insight how you'd do that and how pester does it itself :)
