### ISSUE TITLE
BeforeAll missing from Wiki?

### ISSUE THREAD

**Issue by KristofStroobants** [pester/Pester#1373]
I am currently trying to wrap my head around Pester. Trying to write my first little tests.
Someone over at Slack provided me with an example in which he used "BeforeAll".
I tried to look for that command in the documentation over at the Wiki but couldn't find it.

It is mentioned in the help in Powershell itself.

Just thought i'd mention it, maybe this was forgotten?

Kind regards

**Comment by nohwnd** [comment]
I could not find it on the wiki either. Do you want to write that article? The wiki is open for editing by anyone. 🙂

**Comment by fflaten** [comment]
Closing. Covered in https://pester.dev/docs/usage/setup-and-teardown
