### ISSUE TITLE
v5 Merge Question

### ISSUE THREAD

**Issue by Stephanevg** [pester/Pester#1377]
Hi,

I was preparing the stuff to integrate https://github.com/pester/Pester/issues/1322 via this PR https://github.com/pester/Pester/pull/1338 into v5

But bumped in the following merge conflict:

In **pester.psm1 - Invoke-pester function**

![image](https://user-images.githubusercontent.com/6302961/65812545-c8cb8280-e1c8-11e9-81c5-8bad49b42f9a.png)

It might simply mean just that ```outputformat``` was forgoten to be added in v5, but I actualyl doubt that.

(I also didn't see the ```JunitFormat``` added in 4.9. (I guess that that work has not been merge in v5 yet)).

If it was intentionally removed I do have the following question:

How are you planning to migrate the ```-OutputFormat``` 
If that parameter is not suppose the be entry point for the output format that the end user wants to have, where should I add it to instead?

**Comment by nohwnd** [comment]
The v5 interface is currently cut down to absolute basics. The conversion to xml and jacoco will be implemented and published as separate functions that consume the result obejct. That way the Invoke-Pester interface is not bloated by trying to do  20 things at the same time. That is why I was not sure what benefits will adding the json function have.

**Comment by Stephanevg** [comment]
ok intresting, do you have a diagram / or written down the function dependencies somewhere?

How are you planning to organize that, something along these lines?

```powershell
invoke-pester .\ | Export-PesterResults -format NunitXML
```

or more like having the functions beeing called interenally?

```powershell
invoke-pester -OutputFormat NunitXMl

#Invoke-pester containing a switch like this

Switch($OutputFormat){
     'NunitXML'{
        ConvertTo-PesterNunitXML -Inputobject $PesterObject
     }
}
```

Could you please let me know, so I can implement the code accordingly (or should I just push it as in v4.9 for now?)

-------------------------
Regarding 

```json
That is why I was not sure what benefits will adding the json function have.
```

I still think it will be beneficial. Especially for frameworks that depends on the pester object. People have a common and trusted way to persist the Pester object to the filesystem, as this object is quite different than the other formats it is possible to export to in pester today. (And especially, easier to work with than in XML for instance).
I really do think this would bring a lot - at least for us at work where we work with the JSON format rather than the XML ones. (WhereI speak for an IT company of around 20k employees).

**Comment by nohwnd** [comment]
The first one. Piping stuff together. At least in the first release. 

--- 

What I still don't get is why you'd need to work with the raw format? You can persist the object, and then rehydrate it back to a powershell object so you just work with that directly. If you saved it as json or as clixml does not matter as long as all the info is persisted.

**Comment by fflaten** [comment]
I know #1338 is still up, but closing this issue as it feels outdated. Will reopen if wrong. 
In current version, Pester-object can be exported in multiple ways:
- Passing the reuslt-object obtained from `-Passthru` to the `Export-NUnitReport` and `Export-JUnitReport` public functions or the built-in `ConvertTo-Json/Export-CliXml` cmdlets in PowerShell for that matter.
- Enabling TestResult and OutputFormat in Advanced configuration, ex. `$c = [PesterConfiguration]::Default; $c.TestResult.Enabled = $true; $c.TestResult.OutputFormat = 'JUnitXml'`
- OR use `Invoke-Pester -OutputFormat` which was re-added after v5 release in a legacy parameter-set

The last two methods invokes the export-process by calling a private `Export-PesterResult` helper which again call the public export-functions depending on selected format.
