### ISSUE TITLE
Invoke-Pester -Script: Only Works with Quotes Around 'Path'

### ISSUE THREAD

**Issue by midacts** [pester/Pester#1381]
## 1. General summary of the issue

When running Pester and passing in parameters, it only works if you have quotes around the path.

```text
# Bad: Without quotes around `-Path`. It prompts for the parameter, even though we are providing the value for the parameter in `-Parameters`.
C:\> Invoke-Pester -Script @{ Path = .\ted.tests.ps1; Parameters=@{Request = 'Name'} }

cmdlet ted.tests.ps1 at command pipeline position 1
Supply values for the following parameters:
Request:

# Good: It works if you add quotes around `-Path`
C:\> Invoke-Pester -Script @{ Path = '.\ted.tests.ps1'; Parameters=@{Request = 'Name'} }
Executing all tests in System.Collections.Hashtable

Executing script .\ted.tests.ps1
```

## 2. Describe Your Environment

```powershell
Pester version:             4.9.0
PowerShell version:         5.1.14409.1018
OS version:                 Microsoft Windows NT 6.3.9600.0
```

## 3. Expected Behavior

`Invoke-Pester -Script @{ Path = .\ted.tests.ps1; Parameters=@{Request = $Params} }`

This should work without quotes.

## 4.Current Behavior

Quotes are required around the `Path` parameters or else it does not respect the `Parameters`.

## 5. Possible Solution

I haven't looked at the Pester codebase much.

## 6. Context

We are trying to run "dynamic" tests meaning the values we test for should be passed in via parameters.

Example: Deploying a VM and running a generic/parameterized test so we can use one test to dynamically validate each VM deployed.

**Comment by nohwnd** [comment]
This is caused by how PowerShell hashtables work and has nothing to do with Pester itself. When you provide the path without the quotes, you are telling PowerShell to execute the script, and put the Output of that script into the Path key in the hashtable.

**Comment by midacts** [comment]
I think you are saying that because of the `.\` added in front of `.\ted.tests.ps1`?

a fully qualified path without quotes does not work either:
```text
C:\> Invoke-Pester -Script @{ Path = C:\users\midacts\desktop\ted\ted.tests.ps1; Parameters=@{Request = 'ted'} }

cmdlet ted.tests.ps1 at command pipeline position 1
Supply values for the following parameters:
Request:
```

**Comment by nohwnd** [comment]
It's the same situation imho. The script is executed and the output of the script is written into the Path key in the hashtable. The output is most likely null, (or something else that is not a valid path) and so Pester can't execute it. If you put the quotes around the Path it will remain just a normal string and Pester will interpret it as the path to the test file. So you __need__ to provide the quotes.

**Comment by midacts** [comment]
Makes sense. I ran into this last week and it took me a few minutes to figure out I needed quotes to get it to work.
