### ISSUE TITLE
Output gets butchered if Invoke-Pester is called with 6>&1

### ISSUE THREAD

**Issue by abbbi** [pester/Pester#1384]
If stream 6 is redirected via 6>&1 the output includes additional newlines and looks like:

```
       [?] test1
     , is inconclusive, because Skip test on linux
     11ms
     Describing testcaess
      [+] test2
      73ms
       [+] test3
     351ms
```

**Comment by nohwnd** [comment]
@abbbi Why do you need that redirect? Maybe you can work around that in a different way. 

@fflaten Both your suggestions are valid, but as you pointed out are also not without their downsides. Unless there is a really good reason for that redirect I'd say we should close this as won't fix.

**Comment by fflaten** [comment]
Correction about my ANSI-suggestion. Even redirected, you'd keep the formatting. I'd suggest implementing it at some point to support colors in CI/CD logs too as mentioned in the related issue.

**Comment by nohwnd** [comment]
Moved that comment to #1953

**Comment by abbbi** [comment]
> @abbbi Why do you need that redirect? Maybe you can work around that in a different way.

its not a requirement. I was executing pester via vagrant provisioning scripts, and noticed that the output format is quite broken then.

**Comment by nohwnd** [comment]
In that case we won't fix that because it would just replace this issue with another. Sorry.
