### ISSUE TITLE
Docs: Assert-VerifiableMock(s) not updated with changes from pester 3 to 4

### ISSUE THREAD

**Issue by minid33** [pester/Pester#1385]
## 1. General summary of the issue

The Wiki references calls to Assert-VerifiableMocks but when you call this in pester 4 then you get a deprecation error

```
      [-] There is only one matching engine association for this project 68ms
        at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\Pester\4.9.0\Pester.psm1: line 1514
        1514:     Throw "This command has been renamed to 'Assert-VerifiableMock' (without the 's' at the end), please update your code. For more information see: https://github.com/pester/Pester/wiki/Migrating-from-Pester-3-to-Pester-4"

        This command has been renamed to 'Assert-VerifiableMock' (without the 's' at the end), please update your code. For more information see: https://github.com/pester/Pester/wiki/Migrating-from-Pester-3-to-Pester-4
```

## 2. Describe Your Environment

https://github.com/pester/Pester/wiki/Mock
https://github.com/pester/Pester/wiki/Assert%E2%80%90VerifiableMocks

## 3. Expected Behavior

Documentation should be updated with the current version 
## 4.Current Behavior

Documentation is accurate for an older version of Pester
## 5. Possible Solution

Remove the s from all places in the wiki when referencing calls to Assert-VerifiableMock(s)

## 6. Context

I'm writing mocks and the docs are not updated.

**Comment by nohwnd** [comment]
Wiki is open for editing. You can make the change yourself. Could you do it please? 🙂
