### ISSUE TITLE
Import-Module resets all mocks inside Context

### ISSUE THREAD

**Issue by Ace-Lightning** [pester/Pester#1388]
## 1. General summary of the issue

Command `Import-Module -Name 'ModuleName' -Force` reset all mocks and I cannot to mock functions again

### Module 'TestModule.psm1`

```powershell
function Get-MockedDate
{
    return (Get-Date -UFormat "%Y-%m-%d %r")
}

Export-ModuleMember -Function *
```

### Tests

```powershell
Import-Module -Name .\TestModule.psm1

Describe "Unit Tests for module 'TestModule' # 1" {

    $dateEntry = "2019-04-15 08:45:26 PM"

    Context "Unit Tests for function 'Get-MockedDate'" {

        BeforeEach {

            Import-Module -Name .\TestModule.psm1 -Force
        }

        It "Test #1" {

            Mock -CommandName 'Get-Date' -MockWith ( & {
                    Param($date)
                    return {
                        return $date
                    }.GetNewClosure()
                } $dateEntry) -ParameterFilter { $UFormat -eq "%Y-%m-%d %r" } -ModuleName TestModule    
   
            (Get-MockedDate) | Should -Be $dateEntry
        }

        It "Test #2" {

            Mock -CommandName 'Get-Date' -MockWith ( & {
                    Param($date)
                    return {
                        return $date
                    }.GetNewClosure()
                } $dateEntry) -ParameterFilter { $UFormat -eq "%Y-%m-%d %r" } -ModuleName TestModule    

            (Get-MockedDate) | Should -Be $dateEntry
        }
    }
}

Describe "Unit Tests for module 'TestModule' # 2" {

    $dateEntry = "2019-04-15 08:45:26 PM"

    Context "Unit Tests for function 'Get-MockedDate'" {

        Mock -CommandName 'Get-Date' -MockWith ( & {
                Param($date)
                return {
                    return $date
                }.GetNewClosure()
            } $dateEntry) -ParameterFilter { $UFormat -eq "%Y-%m-%d %r" } -ModuleName TestModule    

        BeforeEach {

            Import-Module -Name .\TestModule.psm1 -Force
        }

        It "Test #1" {
 
            (Get-MockedDate) | Should -Be $dateEntry
        }

        It "Test #2" {

            (Get-MockedDate) | Should -Be $dateEntry
        }
    }
}
```

## 3. Expected Behavior

All test must be passed successfully 

### First Describe

`Test #2` failed due to mock of function `Get-Date` doesn't work due to `Import-Module` has been executed before this test

### Second Describe

Both tests failed due to mock of function `Get-Date` doesn't work due to `Import-Module` has been executed before these tests

## 5. Possible Solution

I don't have possible solution

## 6. Context

If I remove `-Force` parameter in function `Import-Module` then all works good. But in my project I need to re-import module fully to clear all variables in Module scope. Could you please help me here?

[Test.zip](https://github.com/pester/Pester/files/3773920/Test.zip)

**Comment by nohwnd** [comment]
Thanks for the awesome error report, I debugged this issue and it most likely has to do with the way we are setting up the mocks in Pester. Every Mock is made out of a bootstraper function, behavior and sessionstate. 

The bootstrapper is setup once, and saved based on the module name and function name. When you reimport the module, and add the mock again it will find it in the mock table and won't set up the bootstrapper function again. But the bootstrapper function is in the old module not the new one, and this causes the mock to be skipped.

I coiuld fix your tests by removing the ModuleName parameter from the Mock, but that won't work for all cases, so try it please. I won't be able to change how mocks are stored in v4, but I will investigate this further for v5.

**Comment by Ace-Lightning** [comment]
Hi @nohwnd 

Thank you for looking at my issue. So to mitigate it I've wrapped all `It` by `Context` and it works as expected. I look forward it will fixed in 5.* versions of `Pester` :-)

**Comment by nohwnd** [comment]
I tried it again and it is working okay in 5.2.1. The first test passes because you import the module before defining the mock. The second test fails because you define the mock and then drop the whole module when force re-importing. This drops the mock hook with it, so it never gets triggered. This is IMHO correct behavior. Solution would be to move the mock definition after the module import.

When debugging this your can look at which hooks are defined in the module by stopping at a breakpoint and calling: `& (Get-Module MyModule) { Get-Command Pester_* }`
