### ISSUE TITLE
Documentation: samples are lacking dashes on Should - is this by intention?

### ISSUE THREAD

**Issue by SetTrend** [pester/Pester#1391]
I noticed that many (if not all) of the code samples omit the leading dash character on Pester command parameters, e.g. `Should`:

```powershell
function Add-Numbers($a, $b) {
    return $a + $b
}

Describe "Add-Numbers" {

    It "adds positive numbers" {
        $sum = Add-Numbers 2 3
        $sum | should be 5
    }

    It "ensures that 2 + 2 does not equal 5" {
        $sum = Add-Numbers 2 2
        $sum | should not be 5
    }
}
```
(https://github.com/pester/Pester/wiki/Should#using-should-in-a-test)

Is this by intention? Isn't the leading dash a requirement in PowerShell?

**Comment by nohwnd** [comment]
It is not intention, but the syntax is a valid "legacy" should syntax. The wiki is editable by anyone, if you update it it will help the project :)

**Comment by asears** [comment]
Just used pester on a current project! Thanks for that! 

I cloned the wiki and made some changes, getting an authentication error publishing in bulk.
I will update manually, maybe I can get contributor rights in the future?

Would be happy to help out.

**Comment by nohwnd** [comment]
@asears I am sorry, but giving you rights just to the wiki is unfortunately not possible due to Github limitations. I could only give you push rights for the whole Pester repo and that is something I give up very carefully. Editing wiki efficiently has been a long running problem, and why moving all our documentation directly in our repo is long overdue.

**Comment by asears** [comment]
np!  Yes Github's limiting in that respect. Should be fairly straightforward to add docs to the repo / link from the wiki if that is the plan.  Let me send a pull request.

**Comment by fflaten** [comment]
Closing this as the wiki is no longer used. All examples on https://pester.dev are updated with correct Should-syntax for v5 and most of v4 docs. pester/docs#129 will fix the last ones in v4 docs.
