### ISSUE TITLE
Possible AfterAll block Scope Bug

### ISSUE THREAD

**Issue by xero399** [pester/Pester#1393]
## 1. General summary of the issue

After doing some AfterEach/BeforeEach test iterations, the AfterAll block is returning an initial value.

## 2. Describe Your Environment

Pester version     : 4.9.0 C:\Program Files\WindowsPowerShell\Modules\Pester\4.9.0\Pester.psd1
PowerShell version : 5.1.14393.3053
OS version         : Microsoft Windows NT 10.0.14393.0

Executing the code below:

```
 Describe "Before/After Blocks" {

        Context "BeforeEach/AfterAll" {

            BeforeAll {
                $value = 0
                Write-Host "->Initial value is $value"
            }

            BeforeEach {
                $value++
            }

            It "value is 1" {
                $value | Should -Be 1
            }

            It "value is 2" {
                $value | Should -Be 2
            }

            It "value is 3" {
                $value | Should -Be 3
            }

            AfterAll {
                Write-Host "->Final value is $value"
            }
        }
    }
```

## 3. Expected Behavior

The expected final value for $value in the AfterAll block is 3

This is the expected output:

> Context BeforeEach/AfterAll
> 
> ->Initial value is 0
> 
> [+] value is 1
> 
> [+] value is 2
> 
> [+] value is 3
> ->Final value is 3

## 4.Current Behavior

The $value final value is 0, the initialization value in the BeforeAll block.

This is the output:

> Context BeforeEach/AfterAll
> 
> ->Initial value is 0
> 
> [+] value is 1 
> 
> [+] value is 2 
> 
> [+] value is 3 
> ->Final value is 0

## 5. Possible Solution

I don't have a possible solution

## 6. Context

I'am learning how to use Pester and I am checking how scopes works and how I can isolate or make depencencies between tests. In my opinion, this results are incongruous and confusing.

**Comment by nohwnd** [comment]
This is not a bug, I understand why you think it might work this way, but it is better that it does not. The `BeforeAll` is executed in a scope that is above the scope where `BeforeEach` and `It` is executed. This way any values that are written by the test are discarded and don't influence the other tests. 

In the `$value` what actually happens is this:

```powershell 
&{ # this is BeforeAll, we are one scope deep
    $value = 0
    &{  # this is BeforeEach, we are two scopes deep
        # here $value is read from the parent scope, 
        # 1 is added to it, and then it is written into a new 
        # local variable with the same name
        $value = $value + 1
        "--> $value" # $value here is 1
    } # here the scope ends and the "local" $value variable dies with it
    # here $value is again 0 as it was at the start of the scope
    "-> $value"
}
```

I see that in some cases it might be useful to write to the value that was set in `BeforeAll` but then you'd need to do it via a reference, for example like this: 

```powershell
 Describe "Before/After Blocks" {

        Context "BeforeEach/AfterAll" {

            BeforeAll {
                $container = @{ Value = 0 }
                Write-Host "->Initial value is $($container.Value)"
            }

            BeforeEach {
                $container.Value++
            }

            AfterEach {
                Write-Host "after: $($container.Value)"
            }

            It "value is 1" {
                $container.Value | Should -Be 1
            }

            It "value is 2" {
                $container.Value | Should -Be 2
            }

            It "value is 3" {
                $container.Value | Should -Be 3
            }

            AfterAll {
                Write-Host "->Final value is $($container.Value)"
            }
        }
    }
```

This works because we are modifying the value directly in the same hashtable, and never run into the way powershell manages variables.

**Comment by xero399** [comment]
Thanks for your answer @nohwnd
