### ISSUE TITLE
Measuring time in Pester v5

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#1402]
In v5 I distinguish between the time spent running user code and time spent in the framework code. This helps me to identify where I am taking unreasonably long time to do something. For example Mocks.

In the result object those are currently represented as `Duration`, `FrameworkDuration`, and `DiscoveryDuration`, but there is no `TotalDuration`. This is imho the most important property and I should have named it `Duration` since the start and then split to `UserCodeDuration` and `FrameworkDuration`, but before I do the refactoring please help me with naming here. 

> To give some context, I am building on the "pit of success" rule that says that easy things should be obvious, and less easy things should be less obvious. Applied to naming properties, the first thing that pops to your mind should be the thing that is on the object, and represents what you want to know. So rather than forcing you to add Duration + FrameworkDuration and sometimes DiscoveryDuration I should rather publish Duration that would represent the total. It should also be called Duration and not TotalDuration, because then it is not the obvious name, and it is not clear to what the Total refers to. Unfortunately the whole text of the awesome Framework Design guidelines book is not reflected online, but here is at least a glimpse of the recommended naming guidelines for .net framework https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/general-naming-conventions

### Duration 
- use Duration or Time? I am more inclined to Duration because that is the first thing that pop to my mind (keep names obvious rule). But I have been working with this for a while so my mind might be spoiled. And I am also not a native speaker.

### FrameworkDuration 
- I am pretty happy about that name, be it FrameworkDuration of FrameworkTime it looks obvious. - I considered calling it DurationFramework, to keep the Duration* properties closer together, but that sounds non-english, non-obvious, and moves the property away from other related properties like `FrameworkData`. 

### DiscoveryDuration
- This name I also like. DiscoveryTime does not sound that nice. 

### UserCodeDuration
- Here I don't like the name at all, but don't have any better ideas. This should represent the time that is spent running the user code (so basically tests, setups and teardowns), but calling it `TestDuration` seems confusing to me. Please propose some names here.

**Comment by MarcoRossignoli** [comment]
Personally I like the term `time` in perf counters. You could inspire from win so counter "user time"(user code duration) and "privileged time"(framework duration), so for instance
"TotalTime" for duration
"FrameworkTime" and "DiscoveryTime" for framework(kernel) measures
"UserTime" for user code duration

![image](https://user-images.githubusercontent.com/7894084/71305501-8edbd800-23d5-11ea-8f39-b9cfeb6ba68f.png)

**Comment by vexx32** [comment]
I think if we're talking time taken to run a test, it may make sense to borrow terms from `Stopwatch` and go with something like `ElapsedTime`.

For `FrameworkTime` perhaps we could go with something like `ScaffoldTime`?

In terms of user test code itself... `TestActionTime` perhaps? `TestCoreTime`? 

There are probably a few better options, but these are the ones in my head at the moment. I'll check back and add more ideas if I think of some others that might work 🙂

**Comment by nohwnd** [comment]
Not a single complaint about this, won't do big rename.
