### ISSUE TITLE
Codecov cannot process JaCoCo reports generated by Pester

### ISSUE THREAD

**Issue by johlju** [pester/Pester#1419]
## 1. General summary of the issue

The JaCoCo format that is output by Pester does not follow the schema since it missing the attributes `mb` and `cb`, and the file is output with the encoding "UTF-8 with BOM".
 
See more information in the Codecov forum
https://community.codecov.io/t/error-while-processing-jacoco-reports-generated-by-pester-powershell/139/5

A good article explaining the different attributes.
https://stackoverflow.com/questions/33868761/how-to-interpret-the-jacoco-xml-file

## 2. Describe Your Environment

Using build worker in Azure Pipelines.

## 3. Expected Behavior

The JaCoCo format output by Pester should not need post-processing of the file.

## 4.Current Behavior

Need to pre-process the file before upload to Codecov.io.
```powershell
$xml = Select-Xml -Path './output/testResults/CodeCov*.xml' -XPath '.'

$nodes = $xml.Node.SelectNodes("/report/package/sourcefile/line");
foreach ($node in $nodes)
{
    $node.SetAttribute('mb', 0)
    $node.SetAttribute('cb', 0)
}

$xml.Node.Save("./output/testResults/JaCoCo_coverage.xml")

# This changes the encoding on the file to UTF-8 without BOM.
$fileContent = Get-Content -Path './output/testResults/JaCoCo_coverage.xml' -Encoding 'Unicode' -Raw
$fileContent | Out-File -FilePath './output/testResults/JaCoCo_coverage.xml' -Encoding 'ascii'
``` 

## 5. Possible Solution

Add the two missing attributes `mb` and `cb` and hard-code with `0` (not sure Pester can see branches).  

https://github.com/pester/Pester/blob/30c5f7e3f1a045589c0bbc4d34b0961fdfbd5b92/Functions/Coverage.ps1#L746-L750

Change the file that is written to use `'ASCII'` as the encoding (= "UTF-8 _without_ BOM")

https://github.com/pester/Pester/blob/9b314e4a74a943d8ab89a6755b583679007c768e/Pester.psm1#L1158

## 6. Context

Need to do pre-processing of the XML which unnecessarily complicates the pipeline.

**Comment by nohwnd** [comment]
Thanks for reporting, do you want to PR it? 🙂

**Comment by johlju** [comment]
I can send in a PR.

**Comment by nohwnd** [comment]
> Change the file that is written to use 'ASCII' as the encoding (= "UTF-8 without BOM") 

Okay I missed this, ASCII is 7byte encoding, so not the same as UTF-8. Is UTF8 generating the file with BOM? Does that depend on some system settings?

**Comment by johlju** [comment]
The file is saved as BOM on PS Core 6.x on the Ubuntu buidl worker in Azure Pipelines. But I added a new parameter so the user can control the behaviour, the parameter defaults to `'utf8'` so it is not a breaking change.

**Comment by johlju** [comment]
Sent in PR #1420.

**Comment by nohwnd** [comment]
So does that meant that UTF8 means UTF8 with BOM on PSCore 6.x on ubuntu? Wouldn't it then be better for us to make sure we are saving the file always without BOM (e.g. be stripping it) to not force the user to familiarize themselves with encoding problems on different platforms?

**Comment by nohwnd** [comment]
I am asking because PowerShell 6 has UTF8BOM so I am confused how is -Encoding UTF8 producing a file with BOM. https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-file?view=powershell-6

**Comment by johlju** [comment]
By saving with the encoding `ascii` the file becomes UTF-8 (without BOM), not utf7, there is also an 'utf7' encoding.  It also has an encoding that is called `UTF8NoBOM`. This behavior is different between PS versions.

I think it is better to let the user to choose the encoding that suits there objective and language.

**Comment by nohwnd** [comment]
I am taking that information from the docs: `ASCII: Uses the encoding for the ASCII (7-bit) character set.` Saving a smiley face into the file and reopening will not give me back smiley face, so imho that is not utf-8 even though Visual Studio code says that in it's status bar. 🙂 

I am just not very happy about adding yet another parameter for code coverage, because I don't see how it solves the problem you have with Codecov, you will have the treat that Ubuntu system separately as well right? Because now you are just setting the default to what was a hardcoded value before.

**Comment by johlju** [comment]
Yes, but providing the encoding I want in a parameter when calling `Invoke-Pester` is better than converting the file after. But if you want to hard-code to another encoding and you are okay with the breaking change I'm okay with it too. 

What do you want to change the encoding to that is compatible in all PS versions?

**Comment by johlju** [comment]
Or I can just skip the encoding part entirely in the PR. 🤔

**Comment by johlju** [comment]
@nohwnd Thank you 🙇
