### ISSUE TITLE
Not able to mock start-process powershell {} command?

### ISSUE THREAD

**Issue by saurabh2293** [pester/Pester#1424]
I am using a command where I am calling one ps1(dummy.ps1) file to another ps1 file, command I am using is :

start-process powershell{.\dummy.ps1}

I need to write the pester unit test to cover this line and I have to mock it but it not happening , so please help me to sort this out.

when I am checking the coverage its showing .\dummy.ps1 line is not covered.
I have mocked the command like this : Mock start-process{}
where I am doing wrong?

**Comment by fflaten** [comment]
It really depends on your code (module vs script import) etc, so we'd need a complete repro to help better.
Here's a working demo in Pester v5:

Demo.ps1
```powershell
function Demo {
   start-process powershell {.\dummy.ps1}
}
```

Demo.tests.ps1
```powershell
BeforeAll {
    . "$PSScriptRoot\Demo.ps1"
}

Describe "Demo" {
    It "Returns expected output" {
        Mock -CommandName 'Start-Process' -MockWith { }
        Demo
        Should -Invoke -CommandName 'Start-Process' -ParameterFilter { $Path -eq 'powershell' -and $ArgumentList -eq {.\dummy.ps1} }
    }
}
```
