### ISSUE TITLE
Implement Skip and Ignored

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#1430]
Reasons for -skip: 
- skip stuff that is work in progress
- skip test forever, ignoring tags (unless the test is explicitly run, e.g. by clicking _Run Test_ in Gui)
- skip based on condition that is determined without needing to specify tags

describe patters where to avoid skip and encourage tags: 
- avoid using for static things "like $isWindows"
- avoid using it to dynamically skip tests
- avoid ifs to skip tests

Changes:
- split ~ignored~ notRun (not-passing filter) from skipped (having -skip parameter)
- show skipped in output, but not ~ignored~ notRun

Related #1266

**Comment by jhoneill** [comment]
Bring the conversation back here rather than on twitter. 
This sounds good to me. Good examples saying "Use skip for ... but not for ..." as outlined above should encourage (not force) people to write better tests :-)

**Comment by nohwnd** [comment]
Small amendment here since Ignored has a different meaning. I will call the tests that were not run 'NotRun' and define it as `-not .ShouldRun`. This count will not include tests that `.ShouldRun -and -not .Executed` such tests already translate to `Error`. 

There should also be capability to run `-Skip` tests explicitly, at least when specified by "path" or some similarly narrow selector. So probably not by including a tag.

**Comment by nohwnd** [comment]
Ignored will not be a capability of Pester, because it should not be needed unless we allow including skipped tests by including a tag, then ignore would be a way to always skip a test.
