### ISSUE TITLE
Add Run Test to VSCode integration

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#1436]
- [x] Add filter by path:lineNumber
- [ ] Add VSCodeMarker
- [x] Make sure user PesterPreference is honored when set before tests are run
- [x] Make sure -Skip can be bypassed by Run Test on a test (but not on block)

- [x] Discuss how to avoid showing Run Tests from the lense to people who don't want it (option in settings)?
- [x] Discuss if there is a better way to communicate errors

/cc @bergmeister ^^^ would you have some more info for the two discussion points above? 🙂

**Comment by bergmeister** [comment]
Not showing the lense is something that would need to be PRd against the vscode-powershell repo. It should be quite easy but I am not sure how many people would want that and know about the setting (there are already so many settings that most people don't know about).

In terms on showing errors: my favourite would be to summarise the failures at the end because I have to keep scrolling up a long log when I run tests against a file with a lot of tests (sometimes this is not just for one test but to fix a handful of tests in a TDD fashion)

**Comment by nohwnd** [comment]
Thanks @bergmeister I will need to go PR against that repo and against powershell editor services to get this working. 

My concern is that because Pester v4 does not support running a single test and so it shouldn't show Run Test on It. I am guessing the lense does not know which pester version is loaded because it loads pester later during the execution. Maybe there is a good way to do this, and maybe not. Maybe checking which version of Pester would likely load without loading it? Or actually loading it and deciding based on that? Will probably ask in the repo. I just wanted to have a quick opinion from you. I need to stabilize the api in Pester first and then make PRs. 🙂

**Comment by bergmeister** [comment]
@nohwnd An approach that we'v used in the past for when you helped us with an additional API for running describe blocks using interpolated strings was to assume the latest version but do the check later and give an error to the user:
https://github.com/PowerShell/vscode-powershell/blob/723433b45584852514ae649aabec137a16769e02/InvokePesterStub.ps1#L79
It's not ideal but probably the best that one can do. For Pester v5: Would the existing APIs still work? If so, I'd suggest to make the change to the vs-code extension a but  later once people have had a few months to try and upgrade to v5.

**Comment by nohwnd** [comment]
The existing api would not work, but I am detecting the version in the stub and running it with the new api. Imho option for opt-in will be the best. you  can set that on the workspace level if prefered an we don't need to reinvent any wheels.

**Comment by bergmeister** [comment]
Ok, I see. Yes, I guess opt in to see the codelens via a setting might be the best in the initial phase and after a year you could potentially change the default of that setting.

**Comment by nohwnd** [comment]
Yup. PRed the repos to see what the maintainers there think. Thanks ☺️
