### ISSUE TITLE
Question / Next minor v4 release?

### ISSUE THREAD

**Issue by jtomkiew-mng** [pester/Pester#1439]
Is there a plan to release new minor version for v4 soon-ish? There are some fixes we would like to use that are not part of 4.9.0.

Thanks!

**Comment by nohwnd** [comment]
I am waiting for my certificate to be reissued and it should be today, they said... So I am really hoping 😁

**Comment by nohwnd** [comment]
released https://github.com/pester/Pester/blob/master/CHANGELOG.md#4100-february-2-2020
