### ISSUE TITLE
Missing 4.10 in Github releases

### ISSUE THREAD

**Issue by bgelens** [pester/Pester#1446]
## 1. General summary of the issue

I'm missing 4.10 in the releases :)

## 5. Possible Solution

Add it to releases (maybe automate as part of release process)

## 6. Context

Need to look elsewhere for latest version and release notes

**Comment by bgelens** [comment]
Also manifest releasenotes point to https://github.com/pester/Pester/releases/tag/4.10.0 which does not exist

**Comment by nohwnd** [comment]
Thanks. I said I will write it later and then did not do it. 👍

**Comment by nohwnd** [comment]
Done
