### ISSUE TITLE
Remove reference to pesterbdd.com domain

### ISSUE THREAD

**Issue by pbarsan** [pester/Pester#1447]
## 1. General summary of the issue

Hello,

Defender ATP flags calls to pesterbdd.com domain that is referenced into nuspec file.
I believe this domain once belonged to you, but now it's a chinese website.
Can you please remove the reference to that domain from file below?
https://github.com/pester/Pester/blob/master/Pester.nuspec

`<?xml` version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>Pester</id>
    <version>$version$</version>
    <title>Pester</title>
    <summary>A BDD style testing tool for Powershell</summary>
    <description>Pester provides a framework for running BDD style Tests to execute and validate PowerShell commands inside of PowerShell and offers a powerful set of Mocking Functions that allow tests to mimic and mock the functionality of any command inside of a piece of powershell code being tested. Pester tests can execute any command or script that is accesible to a pester test file. This can include functions, Cmdlets, Modules and scripts. Pester can be run in ad hoc style in a console or it can be integrated into the Build scripts of a Continuous Integration system.</description>
    <tags>powershell unit testing bdd tdd mocking admin</tags>
    <authors>Pester Team</authors>
    **<iconUrl>http://pesterbdd.com/images/Pester.png</iconUrl>**
    <projectUrl>https://github.com/Pester/Pester</projectUrl>
    <licenseUrl>http://www.apache.org/licenses/LICENSE-2.0.html</licenseUrl>
  </metadata>
`
Thanks!

**Comment by nohwnd** [comment]
Yikes. Assigned to a new patch release. The whole nuspec file needs a review. Hopefully will be able to release it today.

**Comment by nohwnd** [comment]
Released
