### ISSUE TITLE
The old domain (pesterbdd.com) was purchased last month & is raising flags in Microsoft Defender Security Center

### ISSUE THREAD

**Issue by Dan-o7** [pester/Pester#1455]

**Comment by nohwnd** [comment]
Hello, there is version 4.10.1 that does not mention the old domain. Hope it will solve your issue.

**Comment by Dan-o7** [comment]
Thank you for responding!

I agree with you that upgrading will resolve the issue.  My problem is Microsoft ships Windows 10 with the old version of Pester.  Can something be done about that, you know, get to the root of the matter?  That could very well be Microsoft's problem & not yours [I don't know - I'm ignorant! ;)], but then do you know who I can report this issue to at Microsoft?  I figured since you all are the Pester devs, you may have some insight.

Thank you again for your time.

**Comment by nohwnd** [comment]
You yourself can remove it from the systems that you manage using this script: https://gist.github.com/nohwnd/5c07fe62c861ee563f69c9ee1f7c9688

@JamesWTruher if I rememember correctly you pushed Pester into Windows last time? Can there be something done about this? e.g. removing it entirely, adding new version, adding exclusion? Who should I connect with?

**Comment by Dan-o7** [comment]
Thank you.  This is good.  Not what I was looking for, but based on this response, I guess this is our only option.  In other words, we don't have a way to contact Microsoft to have them either remove Pester or update Pester in PowerShell that ships with WIndows 10 because of potential security issues - that will be an action for us to take.

Please don't get me wrong, I appreciate your time & responses.  Have a good one!

**Comment by nohwnd** [comment]
@Dan-o7 we do have a way, this is the way. 🙂 Today is holiday in the US, so no-one is responding. I can also message the team internally tomorrow / day after, if no-one responds. They probably won't be able to do anything with this, but might be able to connect me with someone who might. Do you have an example of the warnings you are getting?

**Comment by Dan-o7** [comment]
Fantastic! You guys rock!

I understand when you say that probably won't be able to do anything with this, but at least we'll have taken this as far as we can.  

I attached a Word doc with pictures & infor of what we experience in our organization.  Please let me know if you need more.  I'm also available if Microsoft needs to speak with me.

[Pester Fix.docx](https://github.com/pester/Pester/files/4215681/Pester.Fix.docx)

Thank you again!
