### ISSUE TITLE
Add InModuleScope support for manifest module types

### ISSUE THREAD

**Issue by dalee-bis** [pester/Pester#1456]
## 1. General summary of the issue

When using a module of type "Manifest", InModuleScope gives error "Module 'MyModule' is not a Script module.". This looks to have been fixed previously in #933 but has been re-introduced.

The workaround is to add an empty psm1 file as the `RootModule` in the manifest. This causes the module to be loaded as a `Script` type instead.

## 2. Describe Your Environment

```plaintext
Pester version     : 4.8.1 C:\Users\dalee\Documents\WindowsPowerShell\Modules\Pester\4.8.1\Pester.psd1
PowerShell version : 5.1.18362.145
OS version         : Microsoft Windows NT 10.0.18362.0
```

## 3. Expected Behavior

InModuleScope should work with manifest module types.

## 4.Current Behavior

InModuleScope causes an error with manifest module types.

## 5. Possible Solution

Add support for manifest module types to https://github.com/pester/Pester/blob/master/Functions/InModuleScope.ps1#L72

## 6. Context

Had to use a workaround for manifest module types of adding an empty file as the root module. All other functionality seems to remain consistent.

**Comment by JustinGrote** [comment]
I ran into this issue as well when developing SecretManagement vault extensions, which are typically a manifest with a nested module. Thanks for the tip about the empty psm1!

**Comment by nohwnd** [comment]
This should be pretty simple to fix, just change how the modules are filtered in ResolveCommand in Mock. And also fix the Mock cleanup to use the same rule.
