### ISSUE TITLE
It's probably me, but Pester is not executing my tests

### ISSUE THREAD

**Issue by DarkLite1** [pester/Pester#1459]
## 1. General summary of the issue
There's this strange thing... I wrote some test code for a script. In the test the script is called correctly but the code after calling the script, the actual tests, are not executed. When the `it` clause is finished it's done in a green color stating `Success`. 

According to my logic, when tests are not executed, or there is an error in the script, the Pester test should fail.

See attachment for the files. When you set a breakpoint on a line after the script call (ex. line 46) in the test file it will never be reached. 
[Pester test.zip](https://github.com/pester/Pester/files/4266691/Pester.test.zip)

## 2. Describe Your Environment
```powershell
Pester version     : 4.10.1 C:\Program Files\WindowsPowerShell\Modules\Pester\4.10.1\Pester.psd1
PowerShell version : 5.1.14393.3471
OS version         : Microsoft Windows NT 10.0.14393.0
```

## 3. Expected Behavior

When the script fails or not all tests are ran, the test should fail not pass.

## 4.Current Behavior

The test passes.

**Comment by DarkLite1** [comment]
Figured it out, in the functiono `Get-FolderContentHC` I used:
```powershell
if ($scannedInheritedFolders.ContainsKey($Path)) {Continue}
```
instead of:
```powershell
if ($scannedInheritedFolders.ContainsKey($Path)) {Return}
```

This made the script exit the Pester test and not execute the test. Still, I believe that Pester should check in the `it` clause to see if there are any tests. If then, by reasons unknown, these tests are not executed it should flag the `it` clause as failed

A mistake like this would otherwise never be caught and the author would simply assume that all is correct, Which is not the case.

**Comment by nohwnd** [comment]
Just today I wrote a toy test framework that starts the test as inconclusive, and only marks it as success if there is a passing assertion. Is that what you meant by "Pester should check in the it clause to see if there are any tests." In this context tests = assertions?

**Comment by DarkLite1** [comment]
Indeed, that's what I mean. Pester should start with the status that a test, or assertion as you call it, is failed by default. 

In the example case above the assertions where never reached for execution, so Pester assumed all tests passed while they actually haven't been executed at all.

**Comment by nohwnd** [comment]
Imho this is built in in Pester v5, test is failed when it should run but it is not executed.
