### ISSUE TITLE
Link in documentation leads to 404

### ISSUE THREAD

**Issue by tomer-ds** [pester/Pester#1468]
## 1. General summary of the issue

In the documentation regarding support for mocking of public functions from modules there is a link described as follows:

> Note that module types are described more fully in the Understanding a Windows PowerShell Module page on the Microsoft TechNet website.

The link leads to [404 page](https://docs.microsoft.com/en-us/powershell/developer?redirectedfrom=MSDN):

**Comment by tomerMP** [comment]
Looks like it moved to [here](https://docs.microsoft.com/en-us/powershell/scripting/developer/module/understanding-a-windows-powershell-module?view=powershell-7)

Clearly with some relation to versions of PowerShell

**Comment by nohwnd** [comment]
Looks like the article was moved. The relation is for the view dropdown (notice it is a query parameter).

**Comment by nohwnd** [comment]
@bravo-kernel  was this wiki page not moved to pester.dev? I can't find it there :)

**Comment by bravo-kernel** [comment]
I cannot find the source :)

**Comment by nohwnd** [comment]
https://github.com/pester/Pester/wiki/Testing-different-module-types

**Comment by bravo-kernel** [comment]
Check, looks like a new page was indeed never created for this one. Feel free to give it a shot ;)

**Comment by fflaten** [comment]
When migrating, include necessary adjustments discussed in #1367
