### ISSUE TITLE
Show, Where and Foreach for the result object

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#1473]

**Comment by nohwnd** [comment]
The need for this is highly mitigates by the formatting changes in the result object. Moving to v5.1

**Comment by nohwnd** [comment]
Not as needed with all the clever properties there are on the result object.

**Comment by fflaten** [comment]
Close? Or add a description for whatever's remaining? 🙂

**Comment by nohwnd** [comment]
Close.
