### ISSUE TITLE
Counterintuitive variable behaviour in Should -Throw scriptblock and -PassThru parameter

### ISSUE THREAD

**Issue by ianwalkeruk** [pester/Pester#1486]
## 1. General summary of the issue

Assigning variables in the scriptblock passed to Should -Throw does not work without obscure variable declaration. Also the PassThru parameter to Should -Throw does not output the results of the scriptblock (which would be an 'intuitive' solution to the problem) unless the output is an excepton.

## 2. Describe Your Environment

Pester version     : 4.10.1 C:\Program Files\PowerShell\Modules\Pester\4.10.1\Pester.psd1
PowerShell version : 6.2.3
OS version         : Microsoft Windows NT 10.0.14393.0

## 3. Expected Behavior

For an 'average' user, all of these tests should pass, or it should be clearly documented why they won't.

Example.feature
```powershell
Feature: Setting variable values in Should-Throw scriptblocks

  Scenario: Assigning in the scriptblock
    When Test One is run

  Scenario: Pre-declaring the variable
    When Test Two is run

  Scenario: Trying to use PassThru
    When Test Three is run

  Scenario: Using New-Variable with the AllScopes option
    When Test Four is run

  Scenario: Pass-by-reference types work fine
    When Test Five is run

```

Example.steps.ps1
```powershell
When 'Test One is run' {
  {$var1 = "working"} | Should -Not -Throw
  $var1 | Should -Be "working"
}

When 'Test Two is run' {
  $var2 = $null
  {$var2 = "working"} | Should -Not -Throw
  $var2 | Should -Be "working"
}

When 'Test Three is run' {
  $var3 = {"working"} | Should -Not -Throw -PassThru
  $var3 | Should -Be "working"
}

When 'Test Four is run' {
  New-Variable -Name 'var4' -Value $null -Option AllScope
  {$var4 = "working"} | Should -Not -Throw
  $var4 | Should -Be "working"
}

When 'Test Five is run' {
  $var5 = @{}
  {$var5.Working = $true} | Should -Not -Throw
  $var5.Working | Should -Be $true
}
```

## 4.Current Behavior

The only test that passes is eitherwhen the variable is pre-declared using the pretty obscure 'AllScopes' parameter (I've been doing powershell for over a decade and I've never used it before), or  a pass-by-reference type (e.g. a hashtable) is the variable

```
Executing all tests in '.\Example.feature'

Feature: Setting variable values in Should-Throw scriptblocks

  Scenario: Assigning in the scriptblock
    [-] When Test One is run 8ms
      Expected 'working', but got $null.
      3:   $var1 | Should -Be "working"
      at <ScriptBlock>, C:\scripts\MSI_Tests\Steps\Example.steps.ps1: line 3

  Scenario: Pre-declaring the variable
    [-] When Test Two is run 8ms
      Expected 'working', but got $null.
      9:   $var2 | Should -Be "working"
      at <ScriptBlock>, C:\scripts\MSI_Tests\Steps\Example.steps.ps1: line 9

  Scenario: Trying to use PassThru
    [-] When Test Three is run 8ms
      Expected 'working', but got $null.
      14:   $var3 | Should -Be "working"
      at <ScriptBlock>, C:\scripts\MSI_Tests\Steps\Example.steps.ps1: line 14

  Scenario: Using New-Variable with the AllScopes option
    [+] When Test Four is run 6ms

  Scenario: Pass-by-reference types work fine
    [+] When Test Five is run 18ms
Tests completed in 152ms
Tests Passed: 2, Failed: 3, Skipped: 0, Pending: 0, Inconclusive: 0
```

## 5. Possible Solution

1) (quick) Document the AllScopes/hashtable approach above
2) (medium) Modify the behaviour of PassThru to return the output from the scriptblock if the test passes
3) (best) Modify the behaviour of Should-Throw to make the 'intuitive' usages work.

## 6. Context

I lost a whole day trying to get this to work. Luckily, "trying to get this to work" is my paid day job!

**Comment by nohwnd** [comment]
Is this about using Should -Throw or Should -Not -Throw? Using should -Not -Throw is not warranted in 99% of cases that I know of. 🙂

Returning the output of the scriptblock for Should -Throw would not make sense because the goal of that script block is to throw an exception.

So your problem pretty much is being able to assign variables in scope that is above the scriptblock.  The hashtable approach is great and reasonably well known. I would use that :)

The best I can do would be to add -NoNewScope switch to the assertion, and somehow insert the scriptblock into the parent scope while catching it's exceptions. But I would rather remove the -Not switch on that assertion, which would also make your problem go away and you would get more complete tests.

> (best) Modify the behaviour of Should-Throw to make the 'intuitive' usages work.

Intuitive is subjective in this case. I would for example not expect a variable defined in scriptblock to be visible outside of it in most cases.
