### ISSUE TITLE
v5: Breaking Change - missing -Show parameter

### ISSUE THREAD

**Issue by ThomasNieto** [pester/Pester#1493]
## 1. General summary of the issue

`Invoke-Pester -Show` parameter is missing. Please add back that parameter to customize console output.

## 2. Describe Your Environment

```powershell
Pester version     : 5.0.0 C:\Users\Thomas\Documents\PowerShell\Modules\Pester\5.0.0\Pester.psd1
PowerShell version : 7.0.0
OS version         : Microsoft Windows NT 10.0.18363.0
```

## 3. Expected Behavior

`-Show` parameter is available.

## 4.Current Behavior

```
Invoke-Pester: A parameter cannot be found that matches parameter name 'Show'.
```

## 5. Possible Solution

Add back `-Show` parameter.

## 6. Context

Users should be able to control console output. The `OperationValidation` module uses Pester to run infrastructure tests but outputs its own objects and suppresses Pester's console output by default.

**Comment by nohwnd** [comment]
there is -Output with Normal, Minimal, and None options. Is that enough?

**Comment by ThomasNieto** [comment]
Oh, I didn't know `-Output` replaced `Show`. Can we have output be an enum or validate set so it shows up in help?

**Comment by nohwnd** [comment]
It already is a validate set in rc1 I believe. It is a validate set in the codebase now, and I don't remember touching it since I don't know when. 🙂

**Comment by ThomasNieto** [comment]
I wonder what's causing the issue then. The help syntax shows output being a string not the values in validate set. I don't see any external help overriding the syntax generation either.

https://github.com/pester/Pester/blob/e0b6095facd61a13375c8e1b12f9d58e1131ce8f/Pester.psm1#L331-L333

Get-Help

```
Invoke-Pester [-Output <String>]
```

**Comment by nohwnd** [comment]
I see it in current code. Maybe because in rc1 there is still the comment based help that is outdated, and that I recently deleted? 

```powershell
PS C:\Projects\pester> gmo pester | remove-module ; import-module ./pester.psd1; get-help invoke-pester


NAME
    Invoke-Pester

SYNTAX
    Invoke-Pester [[-Path] <string[]>] [-ExcludePath <string[]>] [-TagFilter <string[]>] [-ExcludeTagFilter <string[]>] [-FullNameFilter <string[]>] [-CI] [-Output {Normal | Minimal | None}] [-PassThru]  [<CommonParameters>]

    Invoke-Pester [-Configuration <PesterConfiguration>]  [<CommonParameters>]
```
