### ISSUE TITLE
Add version to the result object

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#1501]
At work I use pester to do Infrastructure validation tests. In (very short) What we do, is we 'dehydrate' (Export-CliXML) the PesterObject, which we rehydrate to do some global parsing afterwards and some other stuff. This is done each time using the ```-PassThru``` parameter.

The object in Pester5 is very different than the one from v4. It is a good thing we have `ConvertTo-Pester4Result` (And btw, was that object introduced in v4 only? Was is not present before v3 ? If so, the name might be missleading then.).

In a scenario where I have already a lot of dehydrated pester 4 objects, and than I export new ones using pester 5, I realize that I need to somehow make a difference between the types of objects as the parsing logic I need to use is different according to the version of pester in which it got generated.

Wouldn't it make sense to add a property at the root of the pesterobject which can help to identify the major version of pester that was used to generate the object? 

Adding the same property (with a different value of course) on the v4 object in a version 4.11 for example could help solve this issue, and open the door to a standardisation towards the pester object as such.

Something like ```PesterObjectVersion``` or perhaps ```PesterVersion``` or anything in that direction would help to make a difference easily and quickly.
(I'd be happy to implement it also)

_Originally posted by @Stephanevg in https://github.com/pester/Pester/issues/1218#issuecomment-616968006_

**Comment by Stephanevg** [comment]
Also, as another comment, I noticed that the deserialized objects get pretty big in terms of space (according to the amount of tests that were called, it can get quickly pretty big - I can get more data from work if needed).

perhaps this is something we should take into considerations as well.

ps: I dont know about the schedule or so, but I would be happy to help to implement this one if you want :)

**Comment by nohwnd** [comment]
@Stephanevg sure, go ahead :) I would just call it Version

**Comment by Stephanevg** [comment]
Ok, so I had a look at it.
This story would invole the creation of two PR:
a) On the Pester RC4 branch
b) On the Pester 4.10.1 branch

# a) Pester version 5
If I understood the code correctly, the new output object is created in ```New-RSpecTestRunObject```
My idea was to simply add a parameter ```-version``` of type `[version]` to that function. It will directly be mapped to the internal `[PsCustomObject]` at the root that it returns

Also, the function `ConvertTo-Pester4Object` would need to a `version` property to the `PsCustomObject` with a value to `4.0.0`.

# b) Pester 4 branch

TBD

**Comment by Stephanevg** [comment]
Ok, it looks like the CI tests failed. Can anyone shed some light how I can launch the test process locally to debug this further?

**Comment by nohwnd** [comment]
Run the test.ps1 script :)

**Comment by nohwnd** [comment]
All the definitions for the build are in travis / appveyor / azuredevops yaml files in the repo :)

**Comment by nohwnd** [comment]
> Can you tell me how I force it to take the latest version? 

I don't think there is anything special that you need to do, it uses the .psd1 from the pester clone, it should no load pester module from the psmodulepath
