### ISSUE TITLE
[v5] TestDrive Scope Only works at "It" Scope

### ISSUE THREAD

**Issue by JustinGrote** [pester/Pester#1513]
## 1. General summary of the issue
In v5, testdrive only works at It scope (including BeforeEach) whereas before it worked at Describe and Context Scope

## 2. Describe Your Environment
Pester version     : 5.0.0 C:\Users\jgrote\Documents\PowerShell\Modules\Pester\5.0.0\Pester.psd1
PowerShell version : 7.0.0
OS version         : Microsoft Windows NT 10.0.19041.0

## 3. Expected Behavior

v4.1
![image](https://user-images.githubusercontent.com/15258962/80817721-d5f98700-8b86-11ea-8762-e79146b2ccbc.png)

## 4.Current Behavior

v5 (Note that only "Red" and "Cyan" Testdrives show up)
![image](https://user-images.githubusercontent.com/15258962/80817873-148f4180-8b87-11ea-8637-1ab305182240.png)

## 5. Possible Solution
Either enable TestDrive at higher scopes, or add this to the breaking change list.

## 6. Context

This broke some of my tests I'm trying to port.

**Comment by JustinGrote** [comment]
Related: The docs say it should work at context and describe, so I'm going to lean towards this being a bug
https://pester.dev/docs/usage/testdrive

**Comment by nohwnd** [comment]
Your Get-PSDrive code should be in a BeforeAll. This way it runs during discovery and at that time there indeed is no TestDrive. :)

**Comment by JustinGrote** [comment]
@nohwnd not sure what you mean, what I'm saying is that something that worked in 4.1 no longer works in 5 using the same code.

**Comment by JustinGrote** [comment]
Closing as "Not a bug" but a consequence of the new behavior.
https://github.com/pester/Pester/blob/v5.0/README.md#discovery--run

> Put all your code into It, BeforeAll, BeforeEach, AfterAll or AfterEach. Put no code directly into Describe, Context or on the top of your file, without wrapping it in one of these blocks, unless you have a good reason to do so.
> 
> All misplaced code will run during Discovery, and its results won't be available during Run.
