### ISSUE TITLE
False positive for PSReviewUnusedParameter

### ISSUE THREAD

**Issue by mlocati** [pester/Pester#1521]
## 1. General summary of the issue

I have a function that declares a parameter. Even if it's is used in the function body, Pester says it's unused (`PSReviewUnusedParameter` warning).

## 2. Describe Your Environment

```
Pester version     : 4.10.1
PowerShell version : 5.1.17763.1007
OS version         : Windows Server 2019 Datacenter
```

## 3. Expected Behavior

Consider this code (extracted from a [more complex file](https://github.com/mlocati/powershell-phpmanager/blob/1.22.5/PhpManager/public/Install-Php.ps1):

```PowerShell
function Install-Php() {
    [OutputType()]
    param (
        [Parameter(Mandatory = $true, Position = 2, HelpMessage = 'Install a Thread-Safe version?')]
        [bool] $ThreadSafe
    )
    process {
        $searchReleaseStates = @()
        $versionToInstall = $null
        foreach ($searchReleaseState in $searchReleaseStates) {
            $compatibleVersions = Get-PhpAvailableVersion -State $searchReleaseState | Where-Object { $_.FullVersion -match '...' -and $_.Architecture -eq '...' -and $_.ThreadSafe -eq $ThreadSafe }
        }
    }
    end {
    }
}
```

Pester should not mark the `$ThreadSafe` parameter as unised.

## 4.Current Behavior

Pester raises a `PSReviewUnusedParameter` warning.

| RuleName | Severity | ScriptName | Line | Message |
|:---:|:---:|:---:|:---:|:---:|
| PSReviewUnusedParameter | Warning | Install-Php.ps1 | 58 | The parameter 'ThreadSafe' has been declared but not used. |

(see [here](https://github.com/mlocati/powershell-phpmanager/pull/59/checks?check_run_id=645418905#step:5:213))

**Comment by nohwnd** [comment]
What you have there is a test written in Pester, but checking a https://github.com/PowerShell/PSScriptAnalyzer rule. I would not expect that rule to trigger either because you are using the variable on line [133](https://github.com/mlocati/powershell-phpmanager/blob/fb77d09653f2a8eabbb610f409972b78c0e3174c/PhpManager/public/Install-Php.ps1#L133).

@bergmeister is there anything that can be done differently? Or explicit exclusion is needed in some way?

```
RuleName                            Severity     ScriptName Line  Message                                              
--------                            --------     ---------- ----  -------                                              
PSReviewUnusedParameter             Warning      Install-Ph 58    The parameter 'ThreadSafe' has been declared but not 
                                                 p.ps1            used.                                                



    [-] D:\a\powershell-phpmanager\powershell-phpmanager\PhpManager\public\Install-Php.ps1 should pass PSScriptAnalyzer 185ms
      Expected 0, but got 1.
      21:             @($problems).Count | Should -Be 0
      at <ScriptBlock>, D:\a\powershell-phpmanager\powershell-phpmanager\test\tests\Syntax.Tests.ps1: line 21

```

**Comment by bergmeister** [comment]
This is a known PSSA issue as the new release added this new rule: https://github.com/PowerShell/PSScriptAnalyzer/issues/1472

This is because the rule does not inspect child scriptblock scopes because depending on the command, the scope is not guaranteed to be passed on. In your case, ForEach-Object uses the same scope, so you can suppress the specific usage here but if it was Invoke-Command then PSSA would be right.

**Comment by mlocati** [comment]
> What you have there is a test written in Pester, but checking a [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) rule

LOL, sorry! Long time passed since I wrote those tests, thanks for the heads-up btw, really appreciated!

**Comment by bergmeister** [comment]
@mlocati You're welcome. A parameter specific would be
```pwsh
function Install-Php() {
    [OutputType()]
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSReviewUnusedParameter', 'ThreadSafe',
        Justification = 'False positive as rule does not know that Where-Object operates within the same scope')]
    param (
        [Parameter(Mandatory = $true, Position = 2, HelpMessage = 'Install a Thread-Safe version?')]
        [bool] $ThreadSafe
    )
    process {
        $searchReleaseStates = @()
        $versionToInstall = $null
        foreach ($searchReleaseState in $searchReleaseStates) {
            $compatibleVersions = Get-PhpAvailableVersion -State $searchReleaseState | Where-Object { $_.FullVersion -match '...' -and $_.Architecture -eq '...' -and $_.ThreadSafe -eq $ThreadSafe }
        }
    }
    end {
    }
}
```
We are looking at making improvements in the next version to either white-list some known cmdlet that use the same scope or for the rule to be less strict by default (or both).

**Comment by mlocati** [comment]
Thank you again, @bergmeister, it worked out like a charm!
