### ISSUE TITLE
[5.0.0] Set-Itresult is broken and throws a ParameterBindingException

### ISSUE THREAD

**Issue by Vaevictus** [pester/Pester#1522]
## 1. General summary of the issue

When using Set-Itresult inside the body of an "It" block, it throws a parameter binding exception

`[-] should have the domain user retrievable with Get-User 58ms (57ms|0ms)                                         ParameterBindingException: A positional parameter cannot be found that accepts argument '                                       exception     = $exception                                                                                              errorId       = $errorID                                                                                                errorCategory = $errorCategory                                                                                          targetObject  = $targetObject                                                                                       '.                                                        
`
## 2. Describe Your Environment
PowerShell version : 7.0.0
OS version         : Microsoft Windows NT 10.0.18363.0

## 3. Expected Behavior

It should be able to set a test as skipped if certain criteria is met

## 4.Current Behavior
Throws exception

## 6. Context

All tests would dynamically skip/get set to inconclusive throw errors, to work around it I have had to get creating with use of tags

**Comment by nohwnd** [comment]
Thanks set-itresult is published but does not work there is a PR to fix it #1520
