### ISSUE TITLE
Support multiple exception types with `Should -Throw`

### ISSUE THREAD

**Issue by vexx32** [pester/Pester#1525]
## 1. General summary of the issue

Currently, `Should -Throw -ExceptionType` only supports one type of exception being provided. In most cases, this works well, but for modules that need to be cross-platform and work with older versions of PS or .NET as well as recent versions, some exception types expected may differ depending on the version of .NET the module ends up running on.

## 2. Describe Your Environment

N/A

## 3. Expected Behavior

`Should -Throw` should support multiple exception types and/or messages to be provided to simplify tests that need to work on more than one version of PS / .NET.

## 4.Current Behavior

Currently, `Should -Throw` only supports a single type name to be passed to `-ExceptionType` (and `-ExceptionMessage`).

## 5. Possible Solution

One or both of these could be possible:

```ps
$script | Should -Throw -ExceptionType $type1, $type2
```

```ps
$script | Should -Throw -Exception @(
    @{ Type = $type1; Message = $message1 }
    @{ Type = $type2; Message = $message2 }
)
```

**Comment by nohwnd** [comment]
Closing as not planned, this is easy to check by outputting the error from Should -Throw and doing any assertion you'd like on it.
