### ISSUE TITLE
V5 (rc8 and prior): Invoke-Pester throws when using -CI switch together with an array of Paths (happening only on PowerShell 5.1)

### ISSUE THREAD

**Issue by bergmeister** [pester/Pester#1526]
Full local bug repro is here: https://github.com/bergmeister/PesterV5BugRepro

Using .Net 4.8.0 on Windows 10 1909

cc @nohwnd 

This is where it happens in CI:
https://dev.azure.com/powershell/psscriptanalyzer/_build/results?buildId=51793&view=logs&j=873b4b40-df3a-56d8-66d1-ef5810ea11cb&t=84435a71-1ef3-583f-b877-ff8d25a10f11&l=22
https://github.com/PowerShell/PSScriptAnalyzer/pull/1444/checks?check_run_id=642234994

**Comment by nohwnd** [comment]
Thx, in powershell 5.1 it throws when you do `Resolve-Path "C:\temp\* C:\temp\*"` but not in other versions. I was casting to string in one place incorrectly.

**Comment by bergmeister** [comment]
Just to let you know this still happens with `rc7`:
https://dev.azure.com/powershell/psscriptanalyzer/_build/results?buildId=52415&view=logs&j=873b4b40-df3a-56d8-66d1-ef5810ea11cb&t=84435a71-1ef3-583f-b877-ff8d25a10f11&l=22

**Comment by nohwnd** [comment]
Thx, I remember trying the repro multiple times with the fixed version. Not sure what I did wrong.

**Comment by bergmeister** [comment]
It also still happens with the repro that I supplied btw, error message is very similar:
```
.\repro.ps1
Resolve-CoverageInfo : Could not resolve coverage path 'C:\Users\christoph.bergmeiste\git\PesterV5BugRepro\foo\*
C:\Users\christoph.bergmeiste\git\PesterV5BugRepro\bar\*': The filename, directory name, or volume label syntax is incorrect.
At C:\Users\christoph.bergmeiste\Documents\WindowsPowerShell\Modules\Pester\5.0.0\Pester.psm1:6574 char:5
+     Resolve-CoverageInfo -UnresolvedCoverageInfo $unresolvedCoverageI ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Resolve-CoverageInfo
```

**Comment by nohwnd** [comment]
Yeah I saw that, don't know why I did not see the error anymore. Maybe I forgot to save something somewhere. Will check later.

**Comment by bergmeister** [comment]
@nohwnd It seems, this is still happening with `rc8` with my provided repro and in the build:
https://dev.azure.com/powershell/psscriptanalyzer/_build/results?buildId=52662&view=logs&j=cb60fcf6-861c-58fd-f643-65917d204a1d&t=a4dac817-629d-5e4c-ef3c-ff9c911ada21&l=26

**Comment by bergmeister** [comment]
Fixed in `rc9`. Thanks
