### ISSUE TITLE
v5: -CI switch sets CodeCoverage.Enabled to true

### ISSUE THREAD

**Issue by bergmeister** [pester/Pester#1547]
This is a question of defaults but I think the `-CI` switch should not enable code coverage by default
- Not many projects use code coverage in their CI
- CodeCoverage adds significant overhead to the test run time (PSSA on PS 7: 2 -> 3 minutes and on 5.1 3 -> 8 minutes)

I think there should either be a dedicated switch on the simple interface for code coverage or users should use the configuration object, I don't have a strong opinion on either.

**Comment by nohwnd** [comment]
CC perf is something I want to re visit in 5.1, because the perf is the main problem here I would re-consider it after that milestone.

**Comment by nohwnd** [comment]
I revisited perf and there are some minor improvements that were done, but until there is PSProfiler there is no significant boost that can be achieved. I could add the patch that is done via harmony to use the trick I used in my PSProfiler talk to enable this in PowerShell 5, but it won't work in anything newer.

So I guess you are right, CC should be disabled in CI switch, even thought it is a breaking change.

I don't think we should add a dedicated switch to the simple interface at the moment.

Would you like to PR the change?
