### ISSUE TITLE
Reimplementation: Param Blocks in Tests

### ISSUE THREAD

**Issue by JustinGrote** [pester/Pester#1558]
## 1. General summary of the issue

With Pester 5 it appears support for test parameters and the hashtable syntax for specifying them has been dropped, so a lot of my refactoring has unfortunately been changing these to environment variables.

Params on tests make sense in testing for one-off items, or adjusting the environment such as using the same tests to test a built module vs a source module, or specify a tweak in a generalized test to a more specific environment.

## Potential Implementations

One approach I like a lot is how Invoke-Build reads the params from build scripts and then makes them available as dynamic parameters, so if a build script specifies $BuildPath in its param block, you can do:

`Invoke-Build -BuildPath 'path/to/my/thing'`
Which is very intuitive and dynamic params can easily be sanitized to not allow override of pester parameters (which is easier with the smaller surface area of parameters on `Invoke-Pester` now)

This gets tricky however since multiple tests can have different param blocks, this can be solved by prefixing the parameter with a sanitized name of the test file, or have the test file itself be the parameter that accepts a hashtable of parameters. I considered also just accepting param blocks at the various Describe/Context/It levels and use those names but that seems overly complicated.

Other options is drive it from a .psd1 settings file, or make it part of the PesterConfiguration schema.

Just wondering if there was a best practices approach to apply runtime parameters to Pester (environment variables and global variables are "ew" of course) before I look more into this.

**Comment by nohwnd** [comment]
I think the previous approach with a hashtable was generally okay, as long as the hashtable is documented or there is an object to represent it, or a function to generate it. The PesterConfiguration object is itself also just a fancy hashtable converter. I don't think we need to re-invent the wheel here, I just never got to implementing this, but I plan to support it.

It would be nice if this somehow aligned with the `-ForEach` that is planned to add Test Cases to describe https://github.com/pester/Pester/issues/832#issuecomment-453761887. Each row in the test cases is now represented as -Data on the test, and it would be the same for block, and so it should be the same for container. 

The scripts are a bit different in the regard that we specify parameters for a specific script, which on test level we would do by adding the -TestCases parameter to that exact test, so for containers we can do the exact same thing, by publishing the container object and allowing Invoke-Pester to consume it. It does the same thing internally, it just resolves the path to a test file for you / converts scriptblock for you.

**Comment by bormm** [comment]
I really miss this feature as other projects like your own [AzureDevOpsExtension](https://github.com/pester/AzureDevOpsExtension) do not support Pester < V5 anymore. So I have to use a old AzureDevOpsExtension to use the old Pester.

**Comment by almmechanics** [comment]
The `v5` changes have broken the mechanism i used to allow azsk results to be converted into NUnit tests. I would construct the testcases outside of Pester and pass them into pester as params see [Publish-AzskNUnit.ps1](https://github.com/almmechanics/azskhelper/blob/d3786524ac44d0bcb15e48a47facef98bd9bf2eb/cmdlets/interface/Publish-AzskNUnit.ps1#L23). 

This meant the processing of the azsk CSV data was made outside of the pester tests themselves, keeping the tests simple, it looks like i need to revisit this mechanism to support 5.x, and as @bormm mentioned this makes things difficult for any view to backwards compatibility  .

**Comment by nohwnd** [comment]
There is PR #1671 please give it a review.
