### ISSUE TITLE
[v5] Cannot add mocks to "global" BeforeAll block

### ISSUE THREAD

**Issue by JustinGrote** [pester/Pester#1559]
## 1. General summary of the issue

You cannot put mocks in a BeforeAll that isn't surrounded by at least one other block.

## 2. Describe Your Environment

```powershell
Pester version     : 5.0.0 C:\Users\jgrote\Documents\WindowsPowerShell\Modules\Pester\5.0.0\Pester.psd1
PowerShell version : 5.1.19041.1
OS version         : Microsoft Windows NT 10.0.19041.0
```
## 3. Expected Behavior

Mock works as expected

## 4.Current Behavior
![Capture](https://user-images.githubusercontent.com/15258962/82252490-f1dd8680-9903-11ea-89d6-c3009e90cc79.gif)

## 5. Possible Solution
Either fix so that the mock scopes work correctly or, if this is not supported, throw a `[NotSupportedException]` with a clearer explanation of the problem e.g. `Mocks are not supported unless surrounded by a Describe, Context, or It block. Please move your mock to a supported location`

**Comment by nohwnd** [comment]
Documented here https://github.com/pester/Pester/tree/v5.0#mocks-dont-work-in-top-level-beforeall , will fix in the next release. But will improve the error message for 5.0 at least.

**Comment by nohwnd** [comment]
It was easier to just fix it.

**Comment by JustinGrote** [comment]
@nohwnd thanks, I missed the note on it.

**Comment by nohwnd** [comment]
I did not remember it either. :)
