### ISSUE TITLE
v5: Invoke-Pester : A parameter cannot be found that matches parameter name 'Script'.

### ISSUE THREAD

**Issue by meizenga** [pester/Pester#1571]
## 1. General summary of the issue

Running the latest version of Pester
##[error]Invoke-Pester : A parameter cannot be found that matches parameter name 'Script'.

## 2. Describe Your Environment

Azure pipelines, hosted Agent on win2019

$script contains an object : `$script = @{ Path = $TestFilePath; Parameters = $parameters }`

## 3. Expected Behavior

Use an object in the -Script variable

## 4.Current Behavior

The Invoke-Pester task is failing 

## 5. Possible Solution

Installed Pester 4.10.1  `Install-Module -Name Pester -RequiredVersion 4.10.1` 
Using this version the task runs successfully, using the object for the -Script variable

## 6. Context
We always used to update Pester to the latest version using ` Install-Module -Name Pester -Force`
For now we'll stick to 4.10.1

**Comment by nohwnd** [comment]
Hello, 
there was update to a new major version this morning, that uses a slightly different syntax, and these parametric script calls are not implemented yet. It is documented here and scheduled for the next minor version. Sorry for the inconvenience. Please pin your version to `Import-Module -MaximumVersion 4.99.99` to avoid updating to 5.0.0 until you are ready to migrate, or until the feature is added. This way you will continue getting updates to Pester 4, while avoiding the breaking changes.

https://github.com/pester/Pester/issues/1485

More information about the new release is here: 
https://github.com/pester/Pester/releases/tag/5.0.0

**Comment by nohwnd** [comment]
Fix was published in 5.0.1 where a compatibility parameter set was added. https://github.com/pester/Pester/releases/tag/5.0.1

**Comment by meizenga** [comment]
Noted. I’ll wait for 5.1.0

**Comment by nohwnd** [comment]
@meizenga  it was in 5.0.1 and that is released for few hours already :)

**Comment by meizenga** [comment]
Release notes say that hashtable is supported from 5.1.0. Just to be clear, i raised this issue for  -Script not taking the object/hashtable

`neither -Script not -CodeCoverage take hashtables, they just take a collection of paths. This is scheduled for 5.1.0.`

**Comment by nohwnd** [comment]
Ha! Okay. Sorry did not notice that.

**Comment by nohwnd** [comment]
The Legacy param set was added. To provide parameters to the script use New-TestContainer (or New-PesterContainer if I rename it).
