### ISSUE TITLE
[Solved] v5: latest version pester lack of EnableExit

### ISSUE THREAD

**Issue by LiliDeng** [pester/Pester#1572]
Update pester module into latest version. 
Found lack of EnableExit parameter.  Do we have equivalate parameter instead? Thanks!
```
Invoke-Pester : A parameter cannot be found that matches parameter name 'EnableExit'.
```

**Comment by nohwnd** [comment]
Partially. There is either -CI which will enable producing testResults.xml and will try to automatically measure code coverage (coverage.xml), it will also enable exit on failure. Or you can use the Advanced interface where you provide a configuration object [see Simple and Advanced interface](https://github.com/pester/Pester/tree/v5.0#simple-and-advanced-interface).  Those are the three options that `-CI` enables. 

https://github.com/pester/Pester/blob/d59b6ca10b5031fea1c99107c25b774b2c8da1fd/src/Pester.ps1#L344

To enable just exit you would enable `$Configuration.Run.Exit = $true`

**Comment by cloneluke** [comment]
this was deprecated, but dont see in the release notes, breaking change

**Comment by nohwnd** [comment]
Fix was published in 5.0.1 where a compatibility parameter set was added. https://github.com/pester/Pester/releases/tag/5.0.1

**Comment by segraef** [comment]
Although -CI is given which sets $Configuration.Run.Exit = $true still does not exit if a test fails.
I'm using PowerShell Core 7.0.1 and Pester 5.0.1. Same for $Configuration.Should.ErrorAction.

![image](https://user-images.githubusercontent.com/19261257/84464722-98077c80-ac75-11ea-866b-810079823304.png)

Did I miss something?

**Comment by segraef** [comment]
Resolved, can be closed.

**Comment by nohwnd** [comment]
How did you solve it? Was it not broken?

**Comment by PrzemyslawKlys** [comment]
@nohwnd Can you extend -CI with -OutputPath so that one can decide where to save output without advanced configuration? Right now it saves 2 XML files in the root of my project and I am not really keen on that :-P

**Comment by fflaten** [comment]
Closing as `-EnableExit` was re-introduced in 5.0.1.

@PrzemyslawKlys Please create a new issue for your last comment if the feature request is still relevant 🙂
