### ISSUE TITLE
v5: ConvertTo-NUnitReport fails consistently

### ISSUE THREAD

**Issue by nyanhp** [pester/Pester#1573]
## 1. General summary of the issue
`Invoke-Pester | ConvertTo-NUnitReport` fails consistently every time.

## 2. Describe Your Environment

```output
Pester version     : 5.0.0 C:\Program Files\WindowsPowerShell\Modules\Pester\5.0.0\Pester.psd1
PowerShell version : 5.1.18362.752
OS version         : Microsoft Windows NT 10.0.18363.0
```

Issue is exactly the same on Linux (Which I had to upgrade, since Pester 4.10 does not work on Linux at all).

```output
Pester version     : 5.0.0 /home/jhp/.local/share/powershell/Modules/Pester/5.0.0/Pester.psd1
PowerShell version : 7.0.0
OS version         : Unix 4.4.0.18362
```
## 3. Expected Behavior

`Invoke-Pester | ConvertTo-NUnitReport` should return an XmlDocument without throwing an error.

## 4.Current Behavior

Currently, `Invoke-Pester | ConvertTo-NUnitReport` throws an error, which depending on the CI configuration results in total failure of the pipeline. Sometimes even regardless of the ErrorAction.
```output
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\Pester\5.0.0\Pester.psm1:12947 char:5
+     $XmlWriter.WriteAttributeString('date', $Result.ExecutedAt.ToStri ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

Terminating error in AppVeyor release pipeline on Linux, note the ErrorAction SilentlyContinue
```output
Error: 05/27/2020 12:15:30: 
At /home/appveyor/projects/automatedlab/.build/psake.ps1:82 char:61 + … ojectRoot\Tests | ConvertTo-NUnitReport -ErrorAction SilentlyContinue +                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [<<==>>] Exception: You cannot call a method on a null-valued expression.
```
## 6. Context

Trying to export test results, since it has become impossible to specify the name of the test result file in v5 otherwise. There are no apparent parameters or other documented ways of exporting the NUnit XML file with a custom name. If there are, please point me to the documentation.

**Comment by nohwnd** [comment]
The code above fails because there is not input provided, you should run Invoke-Pester with -PassThru. 

To define where you want your output, you can use the Advanced interface where you provide a configuration object [see Simple and Advanced interface](https://github.com/pester/Pester/tree/v5.0#simple-and-advanced-interface).   

```powershell
PS> [PesterConfiguration]::Default.TestResult


Enabled        : Enable TestResult. (False, default: False)
OutputFormat   : Format to use for test result report. Possible values: NUnit2.5 (NUnit2.5, default: NUnit2.5)
OutputPath     : Path relative to the current directory where test result report is saved. (testResults.xml, default: testResults.xml)
OutputEncoding : Encoding of the output file. (UTF8, default: UTF8)
TestSuiteName  : Set the name assigned to the root 'test-suite' element. (Pester, default: Pester)
```

An example config would look like this:

```powershell
$c = [PesterConfiguration]::Default
$c.Run.Path = "C:\example\tests"
$c.Run.Exit = $true
$c.TestResult.Enabled = $true
$c.TestResult.OutputPath = "C:\example\abc.xml"


Invoke-Pester -Configuration $c
```

You can also use `-CI` to enable test results and code coverage by default, with the output in the current folder. Those are the three options that `-CI` enables. In the TestResult option you can set the path, and encoding of the results file.

https://github.com/pester/Pester/blob/d59b6ca10b5031fe

Admittedly the advanced interface is powerful, but far from perfect, and the simple interface is too limited. But it will get better over time, believe me.

**Comment by nyanhp** [comment]
Ah, my bad. Yes, with PassThru it works as expected of course! The advanced options are what I needed, thank you.

I liked the new CI parameter, but there are times when I would like to have more control over the output. Maybe a cmdlet like Get-PesterConfiguration or New-PesterConfiguration would help? On the other hand, the way of constructing the PesterConfiguration object you outlined is also fine, albeit a bit harder to memorize ;)

**Comment by nohwnd** [comment]
@nyanhp it will happen at some point in time but I did not want to push the new features out, and create a whole new set of API at the same time :) 

Re-opening this, as I expect this will bite more people and want it to be on the first page of issues.
