### ISSUE TITLE
v5: Variable handover inconsistencies when using the BeforeAll block

### ISSUE THREAD

**Issue by FelixBorst** [pester/Pester#1579]
## 1. General summary of the issue

When using variables in the BeforeAll block, I get some some weird but reproducable behavior.
The variable seems to be not handed over the first time the tests are run, but on the second and following runs it does.

Not sure if this is a bug or I am using it wrong?

I've tried it on PowerShell v6 and v7 and was able to reproduce the behavior consistently.

## 2. Describe Your Environment

Operating System, Pester version, and PowerShell version:

```powershell
Pester version     : 5.0.0 C:\Users\<user>\Documents\PowerShell\Modules\Pester\5.0.0\Pester.psd1
PowerShell version : 7.0.0
OS version         : Microsoft Windows NT 10.0.19041.0
```

## 3. Expected Behavior

I am expecting the behavior to be consistent no matter how often I run the tests.

I am expecting the following output each and every time:

```powershell
Invoke-Pester @PesterSettings
Discovery: Starting test discovery in 1 test containers.

Starting discovery in 1 files.
Discovery: Discovering tests in C:\Users\<user>\Desktop\Untitled-1.ps1
Discovering in C:\Users\<user>\Desktop\Untitled-1.ps1.
Found 1 tests. 25ms
Discovery: Found 1 tests in 29 ms
Discovery: Processing discovery result objects, to set root, parents, filters etc.
Filter: (my testing stuff) Block will be included in the run, because there were no include filters, and will let its children to determine whether or not it should run.
Filter: (my testing stuff.test numero uno) Block will be included in the run, because there were no include filters, and will let its children to determine whether or not it should run.
Filter: (my testing stuff.test numero uno.Testing if another filepath exists: C:\Users\<user>\Desktop) Test will be included in the run, because there were no include filters so all tests are included unless they match exclude rule.
Discovery finished in 52ms.
Discovery: Test discovery finished.

Running tests from 'C:\Users\<user>\Desktop\Untitled-1.ps1'
Describing my testing stuff
 Context test numero uno
   [+] Testing if another filepath exists: C:\Users\<user>\Desktop 12ms (5ms|7ms)
Tests completed in 192ms
Tests Passed: 1, Failed: 0, Skipped: 0 NotRun: 0
```
## 4.Current Behavior

This is the script I am executing:

```powershell
BeforeAll {
    $here2 = $PSCommandPath | Split-Path -Parent
}


Describe "my testing stuff" {

    Context "test numero uno" {

        It "Testing if another filepath exists: $here2" {
            $here2 | Should -Exist
        }
        
    }

}
```

Pester settings:
```powershell
$PesterSettings  = @{
>>               Path        = "C:\Users\<user>\Desktop\Untitled-1.ps1"
>>               Output      = "Diagnostic"
>>               Verbose     = $true
>>             }
```

Right now I get the following output on the first test run:

```powershell
Invoke-Pester @PesterSettings
Discovery: Starting test discovery in 1 test containers.

Starting discovery in 1 files.
Discovery: Discovering tests in C:\Users\<user>\Desktop\Untitled-1.ps1
Discovering in C:\Users\<user>\Desktop\Untitled-1.ps1.
Found 1 tests. 155ms
Discovery: Found 1 tests in 212 ms
Discovery: Processing discovery result objects, to set root, parents, filters etc.
Filter: (my testing stuff) Block will be included in the run, because there were no include filters, and will let its children to determine whether or not it should run.
Filter: (my testing stuff.test numero uno) Block will be included in the run, because there were no include filters, and will let its children to determine whether or not it should run.
Filter: (my testing stuff.test numero uno.Testing if another filepath exists: ) Test will be included in the run, because there were no include filters so all tests are included unless they match exclude rule.
Discovery finished in 353ms.
Discovery: Test discovery finished.

Running tests from 'C:\Users\<user>\Desktop\Untitled-1.ps1'
Describing my testing stuff
 Context test numero uno
   [+] Testing if another filepath exists:  201ms (148ms|53ms)
Tests completed in 1.27s
Tests Passed: 1, Failed: 0, Skipped: 0 NotRun: 0
```

And here's the output of the second run:

```powershell
Invoke-Pester @PesterSettings
Discovery: Starting test discovery in 1 test containers.

Starting discovery in 1 files.
Discovery: Discovering tests in C:\Users\<user>\Desktop\Untitled-1.ps1
Discovering in C:\Users\<user>\Desktop\Untitled-1.ps1.
Found 1 tests. 25ms
Discovery: Found 1 tests in 29 ms
Discovery: Processing discovery result objects, to set root, parents, filters etc.
Filter: (my testing stuff) Block will be included in the run, because there were no include filters, and will let its children to determine whether or not it should run.
Filter: (my testing stuff.test numero uno) Block will be included in the run, because there were no include filters, and will let its children to determine whether or not it should run.
Filter: (my testing stuff.test numero uno.Testing if another filepath exists: C:\Users\<user>\Desktop) Test will be included in the run, because there were no include filters so all tests are included unless they match exclude rule.
Discovery finished in 52ms.
Discovery: Test discovery finished.

Running tests from 'C:\Users\<user>\Desktop\Untitled-1.ps1'
Describing my testing stuff
 Context test numero uno
   [+] Testing if another filepath exists: C:\Users\<user>\Desktop 12ms (5ms|7ms)
Tests completed in 192ms
Tests Passed: 1, Failed: 0, Skipped: 0 NotRun: 0
```

Notice how the $here2 variable seems to reach the actual test case only the second run?
Why is this behavior different?

## 6. Context

We are currently planning to upgrade our existing Pester v4 tests to Pester v5. Therefore I am trying to understand the changes from v4 to v5, especially on how variables work in combination with the BeforeAll block.

**Comment by nohwnd** [comment]
I am blind, where is the difference please? :)

**Comment by FelixBorst** [comment]
sorry a bit too much text from my side :D

This part is the interesting one:
It "Testing if another filepath exists: **$here2**" {...}

Output first run:
[+] Testing if another filepath exists:  201ms (148ms|53ms)

Output second run:
[+] Testing if another filepath exists: C:\Users\<user>\Desktop 12ms (5ms|7ms)

**Comment by nohwnd** [comment]
Okay gotcha. That would be a bug. The variable is left in the session because I dot-source the BeforeAll body directly into the top-level scope. Yikes.

Should be pretty easy to fix, adding to 5.0.x

**Comment by FelixBorst** [comment]
So this means the variable should not be returned at all, because BeforeAll runs as a function, right?
Can you tell me the best practice on how to return the variable $here2 in this case? Tried out multiple things already, but without success so far.

**Comment by nohwnd** [comment]
By return you mean expand the variable from BeforeAll it into the test name? Right now you probably would not be able to do it, because the name is expanded automatically be PowerShell during discovery, when $here2 is not defined yet :/

**Comment by FelixBorst** [comment]
ah gotcha. 

Do you have any best practice on how to expand the variables defined in the beforeAll into the test itself?

In v4 we did not use any blocks like BeforeEach and just put pure PowerShell code before the actual test case. So the test case was able to retrieve the variables defined beforehand.

In v5 this behavior is not supported if I understand it correctly, because the beforeAll now runs in a separate scope...

Now I am not sure what the pester best practice recommends? Stripping the tests of variables completely?

**Comment by SilverknightMel** [comment]
Yeah, we have experienced chaos of changing variable runs different time.

**Comment by nohwnd** [comment]
By tests you mean the test name? All the variables from BeforeAll scriptblock will be available in the test scriptblock, so there is nothing that needs to change. For the test name you can't expand the variables from the BeforeAll into the test name, unless you peek into the internals.

**Comment by thisjustin816** [comment]
I'm also seeing this and trying to upgrade my tests to v5. Is there a suggested workaround?

**Comment by FelixBorst** [comment]
> All the variables from BeforeAll scriptblock will be available in the test scriptblock, so there is nothing that needs to change. For the test name you can't expand the variables from the BeforeAll into the test name, unless you peek into the internals.

Thanks! That was the answer I was looking for! 💯

**Comment by TigerBoom** [comment]
@thisjustin816 Looking at #1596 I think a workaround is to move your BeforeAll out of the top script level into a Describe block.  I may be wrong, but I believe they are basically equivalent if your file only has one Describe block.

**Comment by thisjustin816** [comment]
> @thisjustin816 Looking at #1596 I think a workaround is to move your BeforeAll out of the top script level into a Describe block. I may be wrong, but I believe they are basically equivalent if your file only has one Describe block.

That's a different issue. And when prepping my scripts for v5 I did move my BeforeAll blocks inside Describe blocks.

**Comment by AspenForester** [comment]
@aaronboock and I are experiencing what I think is a similar issue. 
module version: 5.0.2
PS version: 7.0.3
Windows 10 Build 18363

```
BeforeAll {
    $root = Get-Location
    $outputsFile = Get-ChildItem -File -Name -filter "output*.tf" -Path $root
    $variablesFile = Get-ChildItem -File -Name -filter "variable*.tf" -Path $root 
    $resourceFiles = Get-ChildItem -File -Name -filter "*.tf" -Exclude $outputsFile,$variablesFile -Path $root 
}

$testCases = $resourceFiles | Foreach {@{file = $_}}

Describe "Terraform Unit Tests" -Tags "Unit" {

    Context "Terraform Setup" {
        It "Has a Terraform configuration" {
            $resourceFiles.Count | Should -BeGreaterThan 0
        }

        It "Has a Terraform outputs file" {
            $outputsFile.Count | Should -BeGreaterThan 0
        }

        It "Has a Terraform variables file" {
            $variablesFile.Count | Should -BeGreaterThan 0
        }

        It '<file> has resources' -TestCases $TestCases {
            #param($file)
            $resourceReferences = Select-String -Path (Join-Path $root $file) -Pattern 'resource'
            $resourceReferences.Count | Should -BeGreaterThan 0
        }
    }
}
```
The first three Its pass consistently, but the `It` block with the TestCases only passes on the second (and subsequent) invocation.
