### ISSUE TITLE
Tags in Describe block are ignored

### ISSUE THREAD

**Issue by joselcaguilar** [pester/Pester#1580]
## 1. General summary of the issue

I'm using Pester 5.0.1 with PowerShell 7.0.1, if I run `Invoke-Pester -Path $path -Tag "IT"`, and inside of my Pester script I have the tags in Describe block like this: `Describe "Integration Tests" -Tag "IT" {.....}`, the Tag parameter is ignored and all test are performed instead of only which matches the tag field in Describe block.

## 2. Describe Your Environment

Operating System, Pester version, and PowerShell version:

```
Pester version     : 5.0.1 C:\Users\<user>\Documents\PowerShell\Modules\Pester\5.0.1\Pester.psd1
PowerShell version : 7.0.1
OS version         : Microsoft Windows NT 10.0.19041.0
```

## 3. Expected Behavior

The Describe block to be run must be matched with the tag passed as parameter in Invoke-Pester. 

## 4.Current Behavior

All Describe blocks are tested.

## 5. Possible Solution

N/A

## 6. Context

We are currently planning to upgrade our existing Pester v4 tests to Pester v5. Therefore I am trying to understand the changes from v4 to v5.

**Comment by nohwnd** [comment]
I am trying it on this, with Pester 5.0.1: 

```powershell
Describe "Integration Tests" -Tag "IT" { 
    It "a" { }
}

Describe "b" { 
    It "a" { }
}

###

invoke-pester -Path .\tagerror.tests.ps1 -tag "IT"

Starting discovery in 1 files.
Discovery finished in 29ms.
Tests completed in 130ms
Tests Passed: 1, Failed: 0, Skipped: 0 NotRun: 1
```

And I don't see it happen.

**Comment by joselcaguilar** [comment]
It works as expected, the problem was raised by the code which runs out of "Describe" block, the behaviour is a little bit different from v4.
