### ISSUE TITLE
Legacy parameters should be hidden when the user tab cycles parameters

### ISSUE THREAD

**Issue by KevinMarquette** [pester/Pester#1586]
## 1. General summary of the issue
Several legacy parameters were reintroduced in Pester 5.0.1 to alleviate some migration pains. They still show up when you tab cycle the parameters. These should be suppressed so people can easily discover the correct tags to use from the shell.

## 5. Possible Solution
Adding `[parameter(DontShow)]` to the parameter will auto exclude it from tab complete. 

## 6. Context

The easy way should be the right way. I feel this helps the user discover the right parameters much easier.

**Comment by nohwnd** [comment]
Adding for re-visit to a later milestone.

**Comment by fflaten** [comment]
`DontShow` requires PowerShell v4 or later. Will have to wait until we drop PSv3 support
