### ISSUE TITLE
Chocolatey still using v4 Pester 

### ISSUE THREAD

**Issue by asears** [pester/Pester#1587]
## 1. General summary of the issue

https://chocolatey.org/packages/pester uses 4.1 version.

![image](https://user-images.githubusercontent.com/7253192/83422205-32a2c880-a3f7-11ea-99d8-d0ee7ede5d51.png)

## 2. Describe Your Environment
N/A

## 3. Expected Behavior
Upgrade to 5 with Chocolatey.

## 4.Current Behavior

```shell
PS C:\WINDOWS\system32> choco upgrade Pester
Chocolatey v0.10.8
Upgrading the following packages:
Pester
By upgrading you accept licenses for the packages.
Pester is not installed. Installing...
Progress: Downloading pester 4.10.1... 100%
Progress: Downloading pester 4.10.1... 100%

pester v4.10.1 [Approved]
```

## 5. Possible Solution

Upgrade Chocolatey definitions to latest

**Comment by nohwnd** [comment]
True, I changed the release but did not end up releasing to nuget and choco. Will need to fix that soon.

**Comment by nohwnd** [comment]
Pushed 5.0.4-beta1 to choco and nuget. Will release stable with 5.0.4 update.

PR #1654

**Comment by nohwnd** [comment]
Will review your messages on twitter as well.
