### ISSUE TITLE
v5: Functions defined in test script are out of scope for tests when using Invoke-Pester

### ISSUE THREAD

**Issue by michaelrgibbs** [pester/Pester#1589]
## 1. General summary of the issue

My test scripts define helper functions at the top, and these are called by the tests themselves.

This works in Pester 4, but in 5 the tests are now out of scope if run with Invoke-Pester.

## 2. Describe Your Environment

Pester version     : 5.0.1
PowerShell version : 5.1.18362.752
OS version         : Microsoft Windows NT 10.0.18362.0

## 3. Expected Behavior

```
function TestFunction()
{
    return 1
}

Describe 'tests'{
    It 'test1' {
        TestFunction | Should -Be 1
    }
}

```

The function should be seen by the test and no error occurs.

## 4.Current Behavior

When running through Invoke-Pester:
```
[-] tests.test1 128ms (120ms|8ms)
 CommandNotFoundException: The term 'TestFunction' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

When running the script directly there is no error.

## 5. Possible Solution

None

## 6. Context

Upgrading to Pester 5.

**Comment by nohwnd** [comment]
Yes that is how the execution works at the moment (but might get better in the future). You should put your function definition into `BeforeAll`.

**Comment by michaelrgibbs** [comment]
Thanks, that works.

**Comment by coreyFuller** [comment]
Hi! What did you mean by `before all`? Where is this found? @michaelrgibbs

**Comment by nohwnd** [comment]
@coreyFuller beforeAll is a function that is used to setup tests. https://pester.dev/docs/usage/setup-and-teardown

**Comment by coreyFuller** [comment]
I am still a novice to Pester testing. Would I put all of the function definitions of the functions being unit tested into a `beforeAll -ScriptBlock`?

**Comment by coreyFuller** [comment]
@nohwnd I am still a novice to Pester testing. Would I put all of the function definitions of the functions being unit tested into a beforeAll -ScriptBlock?

**Comment by michaelrgibbs** [comment]
This is the solution to getting my minimal example to work. Does that answer your question?

```
BeforeAll {
    function TestFunction()
    {
        return 1
    }
}

Describe 'tests'{
    It 'test1' {
        TestFunction | Should -Be 1
    }
}
```

**Comment by nohwnd** [comment]
@coreyFuller please read this. https://pester.dev/docs/quick-start This should give you a good starting point in learning Pester. Answer to you question is: You probably would not. You can but it would mean that the function would be contained in your test, and would not be usable otherwise. Instead you put the function into a separate file and dot-source it into the current scope. This way the tested function is still usable outside of the test.

**Comment by VectorBCO** [comment]
not working
tested on Pester 5.3.1

https://github.com/VectorBCO/windows-path-enumerate/pull/35/commits/ffbb9ed54bb9172f3e66ceff29b1d53c31a708c9
