### ISSUE TITLE
-ExcludeTag is not an available parameter as shown on the Release 5.0.0 documentation

### ISSUE THREAD

**Issue by guillene** [pester/Pester#1591]
## 1. General summary of the issue

At the time I try to use `-ExcludeTag` Parameter as shown on the [latest documentation](https://github.com/pester/Pester/releases/tag/5.0.0). The function runs but does not exclude the values. 

## 2. Describe Your Environment

```powershell

Pester version     : 5.0.1 C:\Users\guillen.e.1\Documents\PowerShell\Modules\Pester\5.0.1\Pester.psd1
PowerShell version : 7.0.1
OS version         : Microsoft Windows NT 10.0.18362.0   

```

## 3. Expected Behavior

`Invoke-Pester`  exclude the tags provided to the `-ExcludeTag` .

## 4.Current Behavior

`Invoke-Pester`  don't exclude the tags provided to the `-ExcludeTag` .

## 5. Possible Solution

After checking the function parameters it seems that `-ExcludeTag` was replaced for `-ExcludeTagFilter` and doesn't have a proper Alias for the old value `-ExcludeTag`. 

```

Name                           Aliases
----                           -------
Path                           {Script}
TagFilter                      {Tags, Tag}
ExcludeTagFilter               {}
CI                             {}
Output                         {}
PassThru                       {}
EnableExit                     {}
CodeCoverage                   {}
CodeCoverageOutputFile         {}
CodeCoverageOutputFileFormat   {}
Strict                         {}
```

## 6. Context

As this doesn't match with the documentation. I'm not sure if this is an error and I'm afraid that if I update all the required tests to `-ExcludeTagFilter` later on with an update a need to got back to `-ExcludeTag` or if this is just because the change was not added to the documentation or an Alias to the function parameter.

**Comment by nohwnd** [comment]
All PowerShell parameters are able to shorten their names as long as they are not ambiguous, so -ExcludeTag is just a part of -ExcludeTagFilter. In 5.0.1 Legacy parameter set was added. This parameter set aliases the parameters that remained the same, and fixes the parameters that did not. 

I did not add an explicit alias to ExcludeTagFilter because it is part of the name, but if you think it is needed it can be added. You could also PR it if you want. 🙂

---

As for the actual behavior, do you specify tags to be excluded and it does not work? Do you have a simple repro?

**Comment by guillene** [comment]
Thanks for the quick response. I forgot about that PS feature! :) 

I was working on migrating some tests from v3 to v5. The actual error was actually of some of the other breaking changes of making the setup to properly run the tests. So at first, I thought this was not getting the exclusions but then after running with `Diagnostic` mode I spot real the issue and there is not problem with the `-ExcludeTag`. Thanks again!

**Comment by nohwnd** [comment]
Awesome!
