### ISSUE TITLE
Mock CommandNotFoundException: Could not find Command Invoke-Sqlcmd

### ISSUE THREAD

**Issue by asears** [pester/Pester#1592]
## 1. General summary of the issue

The command
```powershell
 Mock 'Invoke-Sqlcmd' -MockWith { $true } 
```
worked in Pester 4, not in Pester 5.

## 2. Describe Your Environment
 
Pester 5.0.1

## 3. Expected Behavior
 
Allow mocking of Invoke-Sqlcmd or details on regression/deprecation/change.

## 4.Current Behavior
 
Previously working mock fails with error.

```powershell
Mock CommandNotFoundException: Could not find Command Invoke-Sqlcmd
```

## 6. Context

Found possible related issue, see #682

**Comment by nohwnd** [comment]
Could you run that with `Invoke-Pester -Output Diagnostic` please?

**Comment by asears** [comment]
Closing this as I think there's something wrong with local Powershell modules & vscode and not necessarily Pester.

**Comment by ertanergunswapfiets** [comment]
I have a similar issue. Here is the diagnotic log

> Mock: Setting up default mock for Invoke-Sqlcmd. 
Mock: We are in a block, one time setup or similar. Returning mock table from test block. 
Mock: Resolving command Invoke-Sqlcmd. 
Mock: Searching for command Invoke-Sqlcmd in the script scope. 
Mock: Did not find command Invoke-Sqlcmd in the script scope. 
Describing Test Script
[-] Describe Test Script failed
  CommandNotFoundException: Could not find Command Invoke-Sqlcmd
Tests completed in 8.2s
Tests Passed: 0, Failed: 1, Skipped: 0 NotRun: 0 

And here is where I call it 

> $params = @{
    'ServerInstance' = $TargetServer;
    'Database' = $TargetDatabaseName;
    'Username' = $sqlCredential.UserName;
    'Password' = $sqlCredential.GetNetworkCredential().Password;
    'Query' = $script
}
Invoke-Sqlcmd @params
