### ISSUE TITLE
[v5] Top-Level BeforeAll not cleaned up

### ISSUE THREAD

**Issue by JustinGrote** [pester/Pester#1596]
## 1. General summary of the issue

** Confirmed as bug: https://github.com/pester/Pester/issues/1596#issuecomment-641796710 **

If I define a BeforeAll above a describe block and put a function in it, that function persists in my powershell scope after the test has run. If I define it within the describe block, it is cleaned up after the test is run.

Related, a BeforeAll defined in one file stays in effect for all pester tests, even ones defined in other files.

## 2. Describe Your Environment

Pester version     : 5.0.0 C:\Users\jgrote\Documents\PowerShell\Modules\Pester\5.0.0\Pester.psd1
PowerShell version : 7.0.1
OS version         : Microsoft Windows NT 10.0.19041.0

## 3. Expected Behavior

```powershell
BeforeAll {
    function TestBAScope {write-host -fore green 'TopLevelBeforeAll!'} 
}
Describe "d" {
    BeforeAll {
        function TestDBAScope {write-host -fore magenta 'DescribeBeforeAll!'} 
    }
    Context "test" {
        
        BeforeEach {
            
        }
        It "shouldrun" {
            TestBAScope
            TestDBAScope
        }
    }

}
```

Trying to run TestBAScope and TestDBAScope should both fail with "function not found" after the test is complete

## 4.Current Behavior
TestBAScope still present after test, TestDBAScope is not.
![image](https://user-images.githubusercontent.com/15258962/84176130-d151a980-aa35-11ea-9dc9-40ae566c39da.png)

## 5. Possible Solution
Either introduce another child context potentially to clean this up or, if by design, add to the "Scope Notes" of the readme.

## 6. Context

Worried about dangling test info not cleaned up that may affect future tests

**Comment by nohwnd** [comment]
Yes this is a bug, caused by how I evolved the execution. The top-level BeforeAll is not invoked the same way other BeforeAll are invoked. 

Even worse, due to the fact how scripts are invoked, the script scoped variables persist even if I would add another scope. I am currently looking into solutions for this.

**Comment by TigerBoom** [comment]
Is a BeforeAll block before any number of Describe blocks supposed to be exactly the same as having the BeforeAll block actually nested in every Describe block?  And I mean "Exactly" the same in terms of scopes etc.

((I realize there is a defect currently.  Just trying to understand expected behaviour))

**Comment by TigerBoom** [comment]
I was trying to create a BeforeAll pattern that works compatibly with v4 and v5.  While experimenting, I found:

A script level BeforeAll scriptblock in v4 is never executed
A script level BeforeAll scriptblock in v5 is executed before every `It`, but definitions in the scriptblock are persisted incorrectly.

A Describe level BeforeAll scriptblock in v4 and v5 are executed before every `It`, and definitions in the scriptblock are scoped correctly.

One backward compatible "solution" is to mandate that BeforeAll is not allowed outside Describe and Context.  I guess it's too late for that approach now that v5 is live.

So instead, is your intention to make a script level BeforeAll obey the same rules as a Describe level BeforeAll?

**Comment by nohwnd** [comment]
> One backward compatible "solution" is to mandate that BeforeAll is not allowed outside Describe and Context. I guess it's too late for that approach now that v5 is live.

I can hopefully still add one extra scope in v5, this is one of the smaller issues with the v5 execution model.
