### ISSUE TITLE
Pester 5 - See tests that are executed

### ISSUE THREAD

**Issue by molinch** [pester/Pester#1597]
## 1. General summary of the issue
Please note that I am not sure if there is an option to change this behaviour.
In the past we could see the tests that have been executed, not just the failed ones, see this example with Pester 3.4.0
```
PS C:\Users\Fabien> Invoke-Pester .\test.ps1
Describing Demo
   Context ContextFoo
    [?] Foo 105ms
   Context ContextBar
    [?] Bar 46ms
Tests completed in 151ms
Passed: 0 Failed: 0 Skipped: 0 Pending: 2 Inconclusive: 0
```

However with Pester 5 we get
```
PS C:\Users\Fabien> Invoke-Pester .\test.ps1
Starting discovery in 1 files.
Discovery finished in 1.13s.
[+] C:\Users\Fabien\test.ps1 4.88s (455ms|3.43s)
Tests completed in 5.05s
Tests Passed: 2, Failed: 0, Skipped: 0 NotRun: 0
```

## 2. Describe Your Environment
Latest Pester, ie: 5.0.2
Powershell on windows or Linux, same behaviour

```powershell
PS /home/fabienm> $bugReport
Pester version     : 5.0.2 /home/fabienm/.local/share/powershell/Modules/Pester/5.0.2/Pester.psd1
PowerShell version : 7.0.1
OS version         : Unix 4.15.0.1083
```

## 3. Expected Behavior
Being able to see the tests that ran

## 4.Current Behavior
We can't see the tests that ran, only the failed ones.
Again: there might be an option to pass, I couldn't find it in the doc.

**Comment by JustinGrote** [comment]
@molinch See the README. Try -Output Detailed :)

**Comment by molinch** [comment]
Brilliant! 
![image](https://user-images.githubusercontent.com/5130190/84180573-071f7e00-aa88-11ea-8cc7-99a1fb8f89bf.png)

I was looking at [PesterConfiguration] I thought it might be there

**Comment by JustinGrote** [comment]
@molinch it is also configurable in [PesterConfiguration]. 
`([PesterConfiguration]::Default).Output.Verbosity`

Generally you choose one or the other. Command line arguments for ad-hoc stuff, the pester configuration object for structured environments like CI or build scripts.

**Comment by molinch** [comment]
That's awesome I much prefer the configuration object

**Comment by Omzig** [comment]
> That's awesome I much prefer the configuration object.
> We use an existing DevOps task, I don't have much control over how Invoke-Pester is invoked, so this way I can override it.
> 
> For reference that's what I do, on top of my test:
> 
> ```powershell
> $PesterPreference = [PesterConfiguration]::Default
> $PesterPreference.Output.Verbosity = 'Detailed'
> ```

Man, i wish this was in a Set-PesterConfig cmdlet or something, this secret stuff drives me nuts.

**Comment by JustinGrote** [comment]
@omzig it's not really secret, it's well documented in the 5 readme, and if you just look at the config object it is self-documented. Try this:
```
$PesterPreference = [PesterConfiguration]::Default
$PesterPreference
$PesterPreference.Output
```

**Comment by nohwnd** [comment]
@Omzig feel free to write a proposal in a new issue for that functionality, you are right it is not easy to discover :)
