### ISSUE TITLE
v5: variable empty in test on pipeline ci/cd tools

### ISSUE THREAD

**Issue by blindzero** [pester/Pester#1601]
### variable empty in test on pipeline ci/cd tools

Since my CI/CD tools (AppVeyor and Azure DevOps Pipelines) updated to Pester v5 I have an issue with one test which is running locally on my system (same Pester version as CI/CD tools):

I am using two variables within my test script.
One of these variable is working in all tests using it.
The second variable is not working within the one test using it, _although_ it holds its value correctly outside the test.

## 2. Describe Your Environment

Local System: issues doesn't occur:
```powershell
Pester version     : 5.0.2 C:\Users\matthias.fleschuetz\Documents\WindowsPowerShell\Modules\Pester\5.0.2\Pester.psd1
PowerShell version : 5.1.18362.752
OS version         : Microsoft Windows NT 10.0.18363.0
```

Azure Pipeline environment:
```powershell
Pester version     : 5.0.2 C:\Users\VssAdministrator\Documents\WindowsPowerShell\Modules\Pester\5.0.2\Pester.psd1
PowerShell version : 5.1.17763.1007
OS version         : Microsoft Windows NT 10.0.17763.0
```

## 3. Expected Behavior

`$ModuleManifestPath` should not be NULL when invoking `Test-ModuleManifest` in test.

## 4.Current Behavior

`$ModuleManifestPath` is NULL when invoking `Test-ModuleManifest` in test. Getting the error:
```powershell
[-] Connect-MS365 Integration Tests.Integrated Manifest Test.Passes Test-ModuleManifest 114ms (111ms|3ms)
 ParameterBindingValidationException: Cannot bind argument to parameter 'Path' because it is null.
 at <ScriptBlock>, D:\a\1\s\tests\Connect-MS365.Tests.ps1:136
```

## 5. Possible Solution

n/a

## 6. Context

The variable $ModuleManifestPath is defined on top of the test script, before first `Describe`:
```powershell
if (!($env:BHProjectPath)) {
    Set-BuildEnvironment -Path $PSScriptRoot\..
}

$moduleName = $env:BHProjectName
$ModuleManifestPath = "$($pwd)\$($moduleName).psd1"
```

For debugging I added some output of the variable outside if `It` but within `Context` and could see the value successfully.
```powershell
Describe "$moduleName Integration Tests" -Tags ('Integration') {
    Context "Integrated Manifest Test" {
        Write-Host $ModuleManifestPath
        It 'Passes Test-ModuleManifest' {
            Test-ModuleManifest -Path $ModuleManifestPath | Should -Not -Throw
        }
    }
    Context "Generated ExternalHelp XML Tests" {
        It "Has ExternalHelp XML generated" {
            "$pwd\en-us\$moduleName-help.xml" | Should -Exist
        }
    }
}
```
Here Test-ModuleManifest is failing because -Path is null (see issue desciption). The $moduleName test below works fine although it is defined in the same way.

**Comment by nohwnd** [comment]
In Pester version 5, the variables directly in script are not available in the the It block. please [move your test setup into BeforeAll block](https://jakubjares.com/2020/04/11/pester5-discovery-and-script-setup/).

**Comment by blindzero** [comment]
@nohwnd thanks a lot for that help, solved the issue, but I don't understand why it worked locally?

**Comment by nohwnd** [comment]
There is a bug where variables are persisted in the current session, when running the tests multiple times, so maybe it was connected to that?
