### ISSUE TITLE
Describe does not recognize the function when it is defined in the same file

### ISSUE THREAD

**Issue by JohnLeyva** [pester/Pester#1604]
## Describe does not recognize the function when it is defined in the same file in PESTER 5

This does not follow the guidelines where testes are declared separeted in its own .tests.ps1 files, but declaring the function and the describe in the same file help to understand better the code and promote the use of automated testing.

Up to this point I haven't been able to isolate the issue, but a segment like the following

```powershell

function Add-Prefix($prefix) {
    process {
        [string]$value =  "$_"
        if ( -not $value.StartsWith( $prefix) ) {
            $value = $prefix + $value
        }
        return $value
    }
}

Describe Add-Prefix { 
    it Test {
        'bcde' | Add-Prefix 'a' | Should -Be 'abcde'
        $null | Add-Prefix 'a' | Should -Be 'a'
    }
}

```

can generate the following error

```
[-] Add-Prefix.Test 125ms (121ms|4ms)
 CommandNotFoundException: The term 'Add-Prefix' is not recognized as the name of a cmdlet, function, script file, or operable program.
 Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
 at <ScriptBlock>, C:\code\PowerFrame\pf-string\pf-string.ps1:696
```

Interestingly when the segment is moved to the beginning of file the issue is not present.

An aspect that might be important is that this file is loaded by a module.

**Comment by nohwnd** [comment]
In v5 setup code should be in BeforeAll block, that way it will be available to your test. https://jakubjares.com/2020/04/11/pester5-discovery-and-script-setup/

**Comment by JohnLeyva** [comment]
In the example presented `Add-Prefix` is the function to test and it is exported by the module so cannot defined in an `BeforeAll` block. 

The expectation in this case is because the function the declared before the `describe`, it should be available.

Seems that a file that interleaves several Describes and module functions generates the issue.

**Comment by nohwnd** [comment]
@JohnLeyva 
Are you saying that you are importing a module that exports this function? That should work. 
Are you saying that you are dot-sourcing a function that a module will later export? That would not work, you would have to dot-source it in a BeforeAll. 
Are you saying that you have function directly in the same file as the tests? Then I don't know how you distribute this, because all tests would run on every import of your module.

**Comment by JohnLeyva** [comment]
Indeed I've noticed that tests ran when files are loaded, and  in my case that is not desirable. 

I want code and tests to be side by side (Same file) as it facilitates understanding and maintenance.

My expectation is that modules/file only define functions and tests. A test runner can discovers tests and execute them.  

Wondering if Pester 5 or even a previous version might allow this

**Comment by nohwnd** [comment]
@JohnLeyva Nope, that won't work, simple because Describe is a function call, no different from any other function call. So unless you'd be able to force it to not run you would always run tests on import. 

A better approach, and the one that is already used is to import the function into scope by dotsourcing it. OR by importing the module before testing it.

**Comment by EliiseS** [comment]
How can we encapsulate logic that needs to run in the middle of the test, but in multiple tests?

Here's an example:
```ps
function Get-ResourceState($address) {
    # Get state and resources after `terraform apply`
    $tfState = terraform show -json | ConvertFrom-Json
    $resources = $tfState.values.root_module.resources

    return $resources | Where-Object { $_.address -eq $address }
}

function Get-Project {
    return Get-ResourceState "azuredevops_project.test"
}

Describe "Terraform Deployment" -Tag 'Deploy' { 
    Context "with clean tfstate" {

        It "initialize terraform" {
            terraform init
        }

        # Run terraform
        It "applying terraform from scratch" {
            Write-Host ""
            $tfResult = terraform apply -auto-approve
            Write-Host $tfResult
            $LASTEXITCODE | Should -Be 0
        }

        It "returns state for all resources" {
            Get-Project | Should -Not -BeNullOrEmpty
            Get-Repository | Should -Not -BeNullOrEmpty
            Get-VariableGroup | Should -Not -BeNullOrEmpty
        }

        It "returns a valid repostiory for the repository ID" {
            $repository = Get-Project
            $repository.values.id | Should -Not -BeNullOrEmpty
            az repos show -r $repository.values.id -p $repository.values.project_id --org ${env:AZDO_ORG_SERVICE_URL}
            $LASTEXITCODE | Should -Be 0
        }
```


Right now the above test results the same error as OP:

```sh
[-] Terraform Deployment.with clean tfstate.returns state for all resources 12ms (10ms|2ms)
 CommandNotFoundException: The term 'Get-Project' is not recognized as the name of a cmdlet, function, script file, or operable program.
 Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by nohwnd** [comment]
@EliiseS Just put it in BeforeAll: 


```powershell 
BeforeAll {
    function Get-ResourceState($address) {
        # Get state and resources after `terraform apply`
        $tfState = terraform show -json | ConvertFrom-Json
        $resources = $tfState.values.root_module.resources

        return $resources | Where-Object { $_.address -eq $address }
    }

    function Get-Project {
        return Get-ResourceState "azuredevops_project.test"
    }
}

Describe "Terraform Deployment" -Tag 'Deploy' { 
    Context "with clean tfstate" {
```

**Comment by nohwnd** [comment]
> Also, doesn't this example here fail: https://github.com/pester/Pester#collect-all-should-failures?

Yes, good catch fixing.

**Comment by fflaten** [comment]
Closing as it seems to have been answered. Let me know if it's not.

**Comment by erikumhoefer** [comment]
Doesn't seem to be working in Pester 5.3.1
```
InModuleScope K8s-Framework-Scripts {
    BeforeAll {
        Mock Write-Host { }
        function New-MockGlobalInfo([string]$ServiceName, [string]$ChartVersion) {
            $globalInfo = @{
                Services = @{
                    $ServiceName = @{
                        ChartVersion = $ChartVersion
                    }
                }
            }
            $globalInfo
        }
    }
    Describe "Set-ServicesMatrix tests" {
        Context "When there is one service" {
            $globalInfo = New-MockGlobalInfo -ServiceName "My-Service" -ChartVersion "1.0.0.0"
            $services = Set-ServicesMatrix -GlobalInfo $globalInfo
            It "Should only have one service in the list" {
                $services.Couunt | Should -Be 1
            }
            It "Should have 'My-Service' as the AppName" {
                $services[0].AppName | Should -Be "My-Service"
            }
        }
    }
}
```

Running Invoke-Pester on this test file fails with 

```
System.Management.Automation.CommandNotFoundException: The term 'New-MockGlobalInfo' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

Is this an issue w/ InModuleScope? I saw someone else is having the same issue in pester 5.3.1 https://github.com/pester/Pester/issues/1589#issuecomment-983165852
