### ISSUE TITLE
prompt on SHOULD -ERRORID:X (without -THROW)

### ISSUE THREAD

**Issue by yecril71pl** [pester/Pester#1607]
## 1. General summary of the issue

The invocation  ``SHOULD -ERRORID:X`` prompts for parameter ``THROW``.

## 2. Describe Your Environment

<DL ><DT >Pester version     : <DD >5.0.2 <CODE >C:\Users\User\Documents\PowerShell\Modules\Pester\5.0.2\Pester.psd1</CODE >
<DT >PowerShell version : <DD >7.0.2
<DT >OS version         : <DD >Microsoft Windows NT 10.0.18363.0</DD >

## 3. Expected Behavior

<DL ><DT >OperationStopped: <DD >Input is not a ScriptBlock</DL >

## 4.Current Behavior

cmdlet Should at command pipeline position 1
Supply values for the following parameters:
<DL ><DT >Throw:</DL >

## 5. Possible Solution

Regression for #132 .
## 6. Context

The PowerShell team requires exception tests to specify ``ERRORID``.

**Comment by nohwnd** [comment]
Would you consider PRint this?

**Comment by yecril71pl** [comment]
Sure, I just wanted to make sure that you do not envisage any harmful interactions.

**Comment by nohwnd** [comment]
@yecril71pl Can we revisit this issue? 

> The PowerShell team requires exception tests to specify ERRORID.
Do you have an example?

I think the issue here is to throw when -ErrorId is specified by -Throw is not, instead of prompting for the mandatory -Throw value, and blocking the test run. 

The PR went a bit away from that.

**Comment by yecril71pl** [comment]
Why do you think requiring an explicit **Throw** would be beneficial?  To me, the syntax `Should -ErrorId` is clear enough.

**Comment by nohwnd** [comment]
The main operator name is what determines which assertion will be used, and even though the dynamic parameters can figure it out themselves if the parameter set is not ambiguous, it keeps a nice consistency to require the main parameter to be specified. In any case it should not block the pipeline from executing by waiting for -Throw to be provided, which is the main issue here. 🙂

**Comment by yecril71pl** [comment]
Nice to whom?  Certainly not to the programmer who is forced to write redundant stuff for no reason.

**Comment by nohwnd** [comment]
Fixed your PR to not make the switch mandatory. Let's see if it builds and let's hope it won't break existing tests that pople wrote :)
