### ISSUE TITLE
Top Level BeforeAll Not Executing - $PSCommandPath variable is empty

### ISSUE THREAD

**Issue by dorseytm** [pester/Pester#1608]
## 1. General summary of the issue

Top level BeforeAll is not being executed.   This BeforeAll only contains the setup line.    While debugging I noticed that $PSCommandPath variable returns empty in the Script context, but has values in the Local context.

BeforeAll {
    . $PSCommandPath.Replace('.Tests.ps1','.ps1')    
}

Describe "Install-GabModule" -Tag Unit {

    BeforeAll {
        $testModulePath = 'C:\Users\dorseytm\PS Scripts\Modules\ProdVersions\GabSQLFuncs'
        $moduleName = $testModulePath.Split('\')[-1]
        $modulePath = "$($env:PSModulePath.Split(';')[1])\$moduleName"
        Install-GabModule -modulePath $testModulePath
    }

    It "Should create a folder in machine's PSModulePath" {
        $modFdr = Test-Path -Path $modulePath -PathType Container
        $modFdr | Should -BeTrue
    }

    It "Folder should contain a .psm1 and .psd1 files" {
        $modFdrFiles = Test-Path -Path $modulePath\* -Include "*.psm1", "*.psd1"
        $modFdrFiles | Should -BeTrue
    }

    AfterAll {
        Write-Debug "Getting ready to remove test module folder"
        Remove-Item -Path $modulePath -Recurse -Debug
    }

}

## 2. Describe Your Environment
Windows 10.0.19041
PSVersion 5.1.1904.1
Pester Version:  5.0.2

**Comment by nohwnd** [comment]
Works for me both with Invoke-Pester and when invoking via F5. 

```powershell
BeforeAll {
    . $PSCommandPath.Replace('.Tests.ps1','.ps1')
    Write-Host $PSCommandPath -ForegroundColor Yellow
    }
    
#... rest of your code
```
![image](https://user-images.githubusercontent.com/5735905/85013763-69057500-b165-11ea-98ff-09130be7861d.png)

**Comment by dorseytm** [comment]
I tried change the code inside the BeforeAll block to a simple Write-Host statement and the BeforeAll block still wasn't processed.   Debugging shows the code just processing the BeforeAll statement and then jumping to the first Describe block.

BeforeAll {
    Write-Host "Testing BeforeAll"
    #. $PSCommandPath.Replace('.Tests.ps1','.ps1')    
    #Write-Host $PSCommandPath
}

Describe "Install-GabModule" -Tag Unit {

    BeforeAll {
        $testModulePath = 'C:\Users\dorseytm\PS Scripts\Modules\ProdVersions\GabSQLFuncs'
        $moduleName = $testModulePath.Split('\')[-1]
        $modulePath = "$($env:PSModulePath.Split(';')[1])\$moduleName"
        Install-GabModule -modulePath $testModulePath
    }

**Comment by dorseytm** [comment]
Gonna close this issue as I created a new test file from scratch and the BeforeAll was processed as expected.

**Comment by nohwnd** [comment]
Okay that is interesting. Hope it won't happen again.
