### ISSUE TITLE
v5: Provide Invoke-Discovery function to retrieve test metadata/counts without running test code

### ISSUE THREAD

**Issue by vexx32** [pester/Pester#1609]
## 1. General summary of the issue

In PSKoans we have a need to give users a progress counter, and to do this we need to be able to count the number of tests that there are in total. Up until now, I've been using an AST-based counter, but this method has limitations; it can't count -TestCases well for the majority of circumstances, and will never be able to reliably count tests if for some reason we have a file generating tests in a loop in some fashion, or if tests need to be conditionally skipped/omitted due to platform constraints.

## 4. Current Behavior

There is currently no supported way to get the discovery-time metadata. I'm currently using an adapted version of a code snippet provided by @nohwnd that does work quite well -- but only in practice:

```ps1
$Result = & (Get-Module Pester) {
    [CmdletBinding()]
    param(
        $Path,
        $ExcludePath,
        $SessionState
    )

    $_Pester_State_Backup = $state.PSObject.Copy()
    $state.Stack = [System.Collections.Stack]@()
    try {
        Reset-TestSuiteState

        # to avoid Describe thinking that we run in interactive mode
        $invokedViaInvokePester = $true

        $fileList = Find-File -Path $Path -ExcludePath $ExcludePath -Extension '.Koans.ps1'
        $containers = foreach ($file in $fileList) {
            New-BlockContainerObject -File (Get-Item $file)
        }

        Find-Test -BlockContainer $containers -SessionState $SessionState
    }
    finally {
        $state = $_Pester_State_Backup
        Remove-Variable -Name _Pester_State_Backup
    }
} -Path $KoanInfo.Path -SessionState $PSCmdlet.SessionState
```

The limitation here is that if you attempt to invoke Pester to _test_ a function containing this code, this code corrupts the internal Pester state, interrupting the ongoing test. I've observed:

- Mock table being empty / null
- Timers reporting negative times
- Test output failing to actually list errors as they occur, though the number of failed tests is (sometimes) still reported.

## 5. Possible Solution

Provide a (preferably completely stateless) discovery-only function for users to get this kind of metadata in advance of any kind of test run. I personally have no need to be able to reuse this for a test run, I just need the test counts ultimately, which I can get from this data. I'm sure someone will probably want that at some point though, so maybe having a way to put that back through to Invoke-Pester would be a good idea too.

I'd suggest a name like `Get-DiscoveryData` or `Invoke-Discovery` perhaps.

**Comment by fflaten** [comment]
Have you tried wrapping it in a job for now? It's ugly and slow (maybe 5sec total added for this), but might allow you to continue with the release until Pester provides a stateless option. Something like this (just a concept, not tested):

```
It 'correctly counts the number of tests in <Path>, including -TestCases' -TestCases @(
        @{ Path = 'TestDrive:\TestCases.Koans.ps1'; ExpectedValue = 3 }
        @{ Path = 'TestDrive:\JustIt.Koans.ps1'; ExpectedValue = 2 }
        @{ Path = 'TestDrive:\Mixed.Koans.ps1'; ExpectedValue = 3 }
        @{ Path = 'TestDrive:\MutlipleTestCases.Koans.ps1'; ExpectedValue = 6 }
    ) {
        
        $pesterModule = Get-Module Pester | Select-Object -ExpandProperty Path
        $psKoansModule = Get-Module PSKoans | Select-Object -ExpandProperty Path
        
        #Testdrive: won't be the same inside a job
        $PathFull = (Get-Item -Path $Path).FullName

        $job = Start-Job -Scriptblock {
            param($PesterModule, $PSKoansModule, $Path)

            Import-Module $PesterModule
            Import-Module $PSKoansModule

            $koanInfo = [PSCustomObject]@{
                Path       = $Path
                PSTypeName = 'PSKoans.KoanInfo'
            }

            InModuleScope 'PSKoans' -Parameters @{ Koan = $koanInfo } {
                param($Koan)
                Measure-Koan $Koan
            }
        } -ArgumentList $pesterModule, $psKoansModule, $PathFull
        
        $result = $job | Wait-Job | Receive-Job

        $result | Should -Be $ExpectedValue
}
```

**Comment by vexx32** [comment]
That's not a bad idea, thanks! I'll have to give that a try, but that looks pretty promising. 🙂

**Comment by fflaten** [comment]
👍 If it works as expected and execution time's an issue, you could also consider modifying it to execute all paths in the same job in BeforeAll and store the returned array. Then use It+Testcases only to evaluate the matching item in the array.
