### ISSUE TITLE
Issue with test cases on 5.0.2

### ISSUE THREAD

**Issue by efie45** [pester/Pester#1614]
## 1. Having difficulty setting up tests that run for multiple scenarios

Before updating to 5.0.2 I was using a foreach-object block to run tests for about 10 different scripts that I have. It seems that due to the new discovery phase this is no longer possible. Instead I put a BeforeAll block at the top of the script with some test cases. However, the test cases aren't working as a solution either. 
```

BeforeAll {
    [System.Collections.ArrayList]$testCases = @()
    $testDir = Split-Path $PSCommandPath -Parent
    $prod = Split-Path $testDir -Parent
    Get-ChildItem $prod -File | ForEach-Object {
        $testCase = @{
            filePath = $_.FullName 
            fileName = Split-Path $_.FullName -Leaf
        }
        $testCases.Add($testCase)
    }
}
Describe "Unit Tests" -Tag 'Unit' {
    It "Vars not declared or changed between function definitions" -TestCases $testCases {
        param (
            [string]$filePath
        )
        [System.Collections.ArrayList]$preSource = (Get-Variable).Name
        . $filePath -Sourcing
        [System.Collections.ArrayList]$postSource = (Get-Variable).Name
        $postSource.Remove('preSource')
        $postSource.Remove('Sourcing')
        [array]$diff = Compare-Object $preSource $postSource -PassThru
        $diff | Should -BeNullOrEmpty
    }
}
```

## 2. Describe Your Environment

Pester version     : 5.0.2 /Users/ethanfie/.local/share/powershell/Modules/Pester/5.0.2/Pester.psd1
PowerShell version : 7.0.0
OS version         : Unix 19.4.0.0 (PowerShell Core on Mac)

## 3. Expected Behavior

I would like to be able to run the same tests for all of the different files

## 6. Context

I've been using Pester to test out my production code - I'm still learning and wanted to stay on the cutting edge so I picked up 5.0.2 while figuring everything out. I'd like to keep all the cool features of 5 but really need the ability to program tests dynamically or use Test Cases. Any help/feedback is greatly appreciated.

**Comment by efie45** [comment]
Just for anyone that might be looking for the same thing:

Test cases appear to be an exception in that you need to still place those outside of a Pester control block (Describe, It, BeforeAll, etc...) because they are evaluated during discovery and then saved for test execution.

**Comment by nohwnd** [comment]
Yes that is true, the BeforeAll block will run during Run phase, but the parameters to Describe / Context and It are collected during Discovery, so $testCases variable won't be defined, because BeforeAll was not executed yet.
