### ISSUE TITLE
Can't mock Out-File

### ISSUE THREAD

**Issue by drache42** [pester/Pester#1617]
## 1. General summary of the issue
Mocking `Out-File` doesn't do anything and original `Out-File` is still called. 

## 2. Describe Your Environment
Pester version     : 5.0.2 C:\Users\sfroehlich\Documents\PowerShell\Modules\Pester\5.0.2\Pester.psd1
PowerShell version : 7.0.2
OS version         : Microsoft Windows NT 10.0.18362.0

## 3. Expected Behavior
When mocking `Out-File` it should not call the built in `Out-File` and try to write to disk

Example code that repros the issue

```
Describe 'Test-Out-File' {    
    BeforeAll{
        Mock Out-File { }
    }

    Context 'Testing Out-File' {

        "Hello World" | Out-File 'c:\test.txt'

        It 'Should work' {
            Assert-MockCalled Out-File -Exactly 1 
        }
    }
}
```

The above code fails at `"Hello World" | Out-File 'c:\test.txt'` with error
```
System.UnauthorizedAccessException: Access to the path 'C:\test.txt' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
```

## 4.Current Behavior
It tries to write to disk, fails because it doesn't have access

**Comment by asears** [comment]
Pester 5 has a change to require code to be within BeforeAll/BeforeEach/AfterAll/AfterEach blocks or within the It context.

This seems to be ok.

```powershell
Describe 'Test-Out-File' {    
    BeforeAll {
        Mock Out-File { }
    }

    Context 'Testing Out-File' {

        It 'Should work' {
            "Hello World" | Out-File 'c:\test.txt'
            Assert-MockCalled Out-File -Exactly 1 
        }
    }
}
```

Also see:

https://dsccommunity.org/blog/converting-tests-to-pester5/
https://github.com/pester/Pester/issues/1319

Some of the docs appear out of date.
https://pester.dev/docs/usage/mocking
