### ISSUE TITLE
Code Coverage report generates a blank file with -CI switch

### ISSUE THREAD

**Issue by vexx32** [pester/Pester#1621]
## 1. General summary of the issue

`Invoke-Pester -CI` is generating a blank code coverage file.

## 2. Describe Your Environment

```
Pester Version: 5.0.2
PowerShell Version: 7.0.1 - 7.0.2 (Azure devops agents, some variance in PS version)
OS Version: Windows 10, Ubuntu 18.04, Linux(?)
```

## 3. Expected Behavior

A coverage.xml file is generated which contains code coverage data.

## 4.Current Behavior

A coverage.xml file is generated with no content whatsoever.

## 6. Context

Trying to get PSKoans' CI pipeline moved over to Pester v5 🙁 

The relevant PR for that work contains some links to Azure Devops pipelines which have the artifacts from the run, which include the empty coverage file:

https://github.com/vexx32/PSKoans/pull/398

**Comment by RobFaie** [comment]
Getting the same issue in Azure Pipelines with the following combinations:
| Pester Version | Powershell Version | Operating System |
| --- | --- | --- |
| 5.0.2 | 7.0.3 | MacOS 10.14 |
| 5.0.2 | 7.0.3 | Ubuntu 18.04 |
| 5.0.2 | 7.0.3 | Windows Server 2019 |
| 5.0.2 | 7.0.3 | Windows Server 2016 |
| 5.0.2 | 5.1.14393.3471 | Windows Server 2016 |

Locally however I do not have this issue:
```
Pester Version: 5.0.2
PowerShell Version: 7.0.3
OS Version: MacOS 10.15
```

**Comment by Bidthedog** [comment]
If I run code coverage without the `CodeCoverage.Path` set, I get a report for all files in the root of my repo:

```
$configuration.CodeCoverage.Path = "$PSScriptRoot/scripts/*.ps1";
```

With it set, I get an empty file - both locally and in Azure DevOps.

**Comment by nohwnd** [comment]
Interesting, was looking at CC this morning, and hopefully will have some time to look at it in the evening as well. I was getting non-empty cc file, but did not test that it produces one on AzDO. It would be weird if it did not, but everyting is possible.

**Comment by Bidthedog** [comment]
Just for a little more context all my test files are in `/test/`, and I run the following script in the root of my repo to execute pester:

```
Set-PSDebug -Strict;
Import-Module Pester;

$ErrorActionPreference = 'Stop';

$configuration = [PesterConfiguration]::Default;
$configuration.Run.Path = $PSScriptRoot;
$configuration.Run.Exit = $true;
$configuration.Should.ErrorAction = "Continue";
$configuration.CodeCoverage.Enabled = $true
$configuration.CodeCoverage.OutputFormat = "JaCoCo";
$configuration.CodeCoverage.OutputPath = "$PSScriptRoot\coverage.xml";
$configuration.CodeCoverage.Path = "$PSScriptRoot/scripts/*.ps1";
$configuration.Output.Verbosity = "Detailed";

Invoke-Pester -Configuration $configuration;
```
This returns an empty file. Doesn't seem to matter what I pass to `CodeCoverage.Path`.

If I remove the `$configuration.CodeCoverage.Path` I get a file with data in it, but it doesn't seem to cover the files in `/test`, just the files in root, and its not much use beyond that:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE report PUBLIC "-//JACOCO//DTD Report 1.1//EN" "report.dtd">
<report name="Pester (07/30/2020 16:25:13)">
    <sessioninfo id="this" start="1596126268004" dump="1596126313619" />
    <package name="Client.BuildTemplates">
        <class name="Client.BuildTemplates/Invoke-PesterTests" sourcefilename="Invoke-PesterTests.ps1">
            <method name="&lt;script&gt;" desc="()" line="1">
                <counter type="INSTRUCTION" missed="12" covered="0" />
                <counter type="LINE" missed="12" covered="0" />
                <counter type="METHOD" missed="1" covered="0" />
            </method>
            <counter type="INSTRUCTION" missed="12" covered="0" />
            <counter type="LINE" missed="12" covered="0" />
            <counter type="METHOD" missed="1" covered="0" />
            <counter type="CLASS" missed="1" covered="0" />
        </class>
        <sourcefile name="Invoke-PesterTests.ps1">
            <line nr="1" mi="1" ci="0" mb="0" cb="0" />
            <line nr="2" mi="1" ci="0" mb="0" cb="0" />
            <line nr="4" mi="1" ci="0" mb="0" cb="0" />
            <line nr="6" mi="1" ci="0" mb="0" cb="0" />
            <line nr="7" mi="1" ci="0" mb="0" cb="0" />
            <line nr="8" mi="1" ci="0" mb="0" cb="0" />
            <line nr="9" mi="1" ci="0" mb="0" cb="0" />
            <line nr="10" mi="1" ci="0" mb="0" cb="0" />
            <line nr="11" mi="1" ci="0" mb="0" cb="0" />
            <line nr="12" mi="1" ci="0" mb="0" cb="0" />
            <line nr="14" mi="1" ci="0" mb="0" cb="0" />
            <line nr="16" mi="1" ci="0" mb="0" cb="0" />
            <counter type="INSTRUCTION" missed="12" covered="0" />
            <counter type="LINE" missed="12" covered="0" />
            <counter type="METHOD" missed="1" covered="0" />
            <counter type="CLASS" missed="1" covered="0" />
        </sourcefile>
        <counter type="INSTRUCTION" missed="12" covered="0" />
        <counter type="LINE" missed="12" covered="0" />
        <counter type="METHOD" missed="1" covered="0" />
        <counter type="CLASS" missed="1" covered="0" />
    </package>
    <counter type="INSTRUCTION" missed="12" covered="0" />
    <counter type="LINE" missed="12" covered="0" />
    <counter type="METHOD" missed="1" covered="0" />
    <counter type="CLASS" missed="1" covered="0" />
</report>
```

Note that not _all_ my test files test powershell code; some test the output of cli commands, another reads a .md file and tests all the links in it resolve, for example:

```
#requires -Version 5.1;
Set-PSDebug -Strict;

$global:solutionRoot = Resolve-Path "$PSScriptRoot\..";

Describe "YAML template validation" {
    BeforeAll {
        Push-Location $global:solutionRoot;
    }
    AfterAll {
        Pop-Location;
    }

    # Arrange
    $ymlFiles = Get-ChildItem $global:solutionRoot -Recurse -File -Include "*.yml" | Where-Object { $_.FullName -notlike "*\node_modules\*" } | ForEach-Object {
        @{
            path = $_.FullName;
        }
    };
    It "'<path>' is valid yaml" -TestCases $ymlFiles {
        param ($path)

        # Act
        & npm run yml -- $path;
        $exitcode = $LASTEXITCODE;

        # Assert
        $exitcode | Should -Be 0;
    }
}
```

**Comment by Bidthedog** [comment]
Btw I just want to say, I have been using Pester for a long time and I absolutely love it. I'm a C# and JS dev, but I also use a lot of PowerShell for DevOps stuff - great work on it, I really like the changes you've made in v5 so far :)

**Comment by vexx32** [comment]
@Bidthedog I was seeing the same, come to think of it. The automatic discovery would find files in the root folder only... but supplying a specific list of paths got me even less. 🤔

**Comment by pefoo** [comment]
Same issue here. Using Pester 5.0.3. 

Coverage file is empty, if tests are located in an arbitrary folder structure. Test cases are the same for both examples. 

Empty:
![image](https://user-images.githubusercontent.com/12524622/90473130-749ff880-e122-11ea-92f6-bc2290cc1e6f.png)

Working:
![image](https://user-images.githubusercontent.com/12524622/90473158-84b7d800-e122-11ea-9d62-81e6b85ff122.png)

**Comment by martinisaksenprogleasing** [comment]
The default behavior was to not traverse any subfolders and so Pester. I would expect, and it seems that others here would agree, that if no path is specified that Pester would traverse the whole folder structure to find tests for code coverage. I've put in a PR that does this.
https://github.com/pester/Pester/pull/1807

**Comment by nohwnd** [comment]
@vexx32 @martinisaksenprogleasing I actually wanted to automatic code coverage resolving to work like this: Resolve all the files that will be executed for the run. And from them take their parent folder and include it in code coverage.

The actual code did not reflect that and instead tried to figure out the covered files from the run path.

https://github.com/pester/Pester/pull/1846


Now I am torn between the two approaches. Because for simple projects simply saying: run it from this folder and include everything recursively from the run path / paths, seems like it's easier to intuitively grasp.

**Comment by nohwnd** [comment]
I think making the resolve recursive from the base path is actually better. Reviewing and fixing #1807.

**Comment by nohwnd** [comment]
Now this might be a breaking change, so I should probably revert the default to not recurse paths by default, but configure it to recurse in the -CI.

**Comment by nohwnd** [comment]
Decided to keep the recursing, it was not working till now anyway. And this is the better behavior.
