### ISSUE TITLE
v5: Improve documentation about importing script files

### ISSUE THREAD

**Issue by TigerBoom** [pester/Pester#1623]
Since the "Discovery & Run" breaking change is potentially very disruptive it is vital that the documentation helps users as much as possible to convert old tests.  I am an occasional user of Pester, and I found it very confusing that almost every internet tutorial is now invalid, and any fixtures created by New-Fixture in version 4 will now fail to run in version 5.

BTW, I fully support the change, but I almost rejected version 5 when I found all my old tests not working.

Specifically, the version 5 release notes say:

> **Put setup in BeforeAll**
> If your test suite already puts its setups and teardowns into Before* and After*. All you need to do is move the file setup into a BeforeAll block:
> 

```
BeforeAll {
    # DON'T use $MyInvocation.MyCommand.Path
    . $PSCommandPath.Replace('.Tests.ps1','.ps1')
}

Describe "Get-Cactus" {
    It "Returns 🌵" {
        Get-Cactus | Should -Be '🌵'
    }
}
```

This is informative but since I wasn't an experienced user, I assumed this did not apply to me since I don't even use BeforeAll for importing my script.  Not to mention that version 4 New-Fixture also produces fixtures that don't run under version 5.

I suggest that additional help is provided with particular focus on importing scripts.  

### Suggested addition:

**Importing Scripts**

If your existing tests.ps1 files import your scripts using syntax like either

```
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path) -replace '\.Tests\.', '.'
. "$here\$sut"
```
or 

```
BeforeAll {
    $here = Split-Path -Parent $MyInvocation.MyCommand.Path
    $sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path).Replace(".Tests.", ".")
    . "$here\$sut"
}
```

then both of the above must be changed to 

```
BeforeAll {
    . $PSCommandPath.Replace('.Tests.ps1','.ps1')
}

```
Note that all test files produced by New-Fixture in Pester version 4 must be updated in this way.

**Comment by fflaten** [comment]
New-Fixture was fixed (reintroduced in v5) in #1726 .
Docs about importing scripts has been updated at https://pester.dev/docs/usage/importing-tested-functions .

Issue solved?
@nohwnd, time to add the https://pester.dev homepage-link in this repo? 🙂
