### ISSUE TITLE
CodeCoverage summary report missing

### ISSUE THREAD

**Issue by hopenbr** [pester/Pester#1625]
## 1. General summary of the issue

When I run 
`invoke-pester -ci `
or 
`invoke-pester -configuration $config`
with codecoverage configuration set up  

I get the testresults.xml and coverage.xml 

Yet not code-coverage summery with coverage percentage and missing lines

passthru does not have code-coverage property 

How do I get code-coverage score (%) now? Do I need to push coverage.xml is some jacoco tool?  

## 2. Describe Your Environment

```powershell
Pester version     : 5.0.2 /root/.local/share/powershell/Modules/Pester/5.0.2/Pester.psd1
PowerShell version : 7.0.2
OS version         : Unix 4.19.76.0
```

[Base image: maven:3.6.3-jdk-11](https://hub.docker.com/_/maven)
[Docker File](https://github.com/carlossg/docker-maven/blob/26ba49149787c85b9c51222b47c00879b2a0afde/openjdk-11/Dockerfile)

we are testing our fortify integration module, that requires the fortify client to be installed 

the above image has Fortify and pwsh installed on top of it.  

## 3. Expected Behavior

CodeCoverage summary report in the output or the report data in passthru prop

```powershell
Code coverage report:
Covered 66.67 % of 3 analyzed commands in 1 file.

Missed commands:

File             Function    Line Command
----             --------    ---- -------
CoverageTest.ps1 FunctionOne    5 return 'SwitchParam was set'

```

## 4.Current Behavior

report is missing 

```powershell
Invoke-Pester -Configuration $configuration

Starting discovery in 1 files.
Discovery finished in 9ms.
[+] /module/Modules/XXXXX/classes/Payload.tests.ps1 1

NotRun                : {}
Tests                 : {[+] Test Payload to create project}
DiscoveryDuration     : 00:00:00.0138360
UserDuration          : 00:00:00.0134416
FrameworkDuration     : 00:00:00.0694685
Failed                : {}
FailedBlocks          : {}
FailedContainers      : {}
Passed                : {[+] Test Payload to create project}
Skipped               : {}
NotRun                : {}
Tests                 : {[+] Test Payload to create project}

```

```powershell
Invoke-Pester -ci

Starting discovery in 2 files.
Discovery finished in 23ms.
[+] /module/Modules/XXXX/classes/Payload.tests.ps1 74ms (21ms|37ms)
Tests completed in 84ms
Tests Passed: 1, Failed: 0, Skipped: 0 
```

## 6. Context

We use gitlab CI and use the report summary to pull the Coverage score from the output logs

No report no coverage,

**Comment by hopenbr** [comment]
Okay I see you are aware of this issue under [Additional Issues to be solved in 5.1](https://github.com/pester/Pester#additional-issues-to-be-solved-in-51) 
I see a mention of it.  

I will keep the issue open unless there is one already opened 

Any workarounds you know of?

**Comment by nohwnd** [comment]
> Any workarounds you know of?

None that I am aware of.

**Comment by GerritVK** [comment]
Any progress on this? Would love to be able to update coverage in markdown again.

**Comment by rifftual** [comment]
What's the status of this?

**Comment by GerritVK** [comment]
Just a followup from my workaround above. I moved away from updating the readme directly and moved to GitLab project badges. To do that my new workaround is to just read the XML and output the Instruction % to console. GitLab will regex that value and update my badge.

```Powershell
#read CodeCoverage.xml and find % of Instructions covered

[xml]$CR = Get-Content $(Join-Path -Path '..\release\Report' -ChildPath 'CodeCoverage.xml')

#Build a custom object that contains each type of coverage
$CRPercent = $CR.report.counter | Where-Object { $_.type -eq "INSTRUCTION" } | foreach-Object {
    $total = [int]$_.missed + [int]$_.covered
    return [Math]::Truncate([int]$_.covered / $total * 100)
}
write-host "Total $($CRPercent)%"
```

**Comment by nohwnd** [comment]
@GerritVK Please review #1860
