### ISSUE TITLE
Pester 5.0.2 - code coverage output options?

### ISSUE THREAD

**Issue by DaveKaretnyk** [pester/Pester#1627]
## 1. General summary of the issue

General/simple question - using Pester 5.0.2, the only option for code coverage is JaCoCo xml? Simple text or html is not possible yet? Alternatively, is there some way to convert the xml to html? 

## 2. Describe Your Environment

Using Pester 5.0.2 and PowerShell 5.1.

## 6. Context

Want to occasionally view the coverage of the PoSh code I'm writing while developing. I.e. for now not concerned about integration into CI/CD.

**Comment by asears** [comment]
Here's a tool which can be used in build pipeline, there's also a Devops task.

https://github.com/danielpalme/ReportGenerator
https://marketplace.visualstudio.com/items?itemName=Palmmedia.reportgenerator

**Comment by DaveKaretnyk** [comment]
@asears - 👍 Works well - that's all I need. Thanks.
