### ISSUE TITLE
Ability to pass array of values to TestCases parameter

### ISSUE THREAD

**Issue by maxim-lobanov** [pester/Pester#1628]
## 1. General summary of the issue

Feature request

## 2. Describe Your Environment

Pester 5.0

## 3. Expected Behavior

It would be great if we could pass array of simple values to `-TestsCases` parameter instead of array of objects.
For some cases, array of objects is overcomplicated option.

Example:
```pwsh
Describe "MyTestDescribe" {
  $arr = @(2, 5, 6, 8, 10)
  It "Test <Value>" -TestCases $arr {
    MyCustomFunction $Value | Should -Not -BeNullOrEmpty
  }
}
```

## 4.Current Behavior
Currently, code from 3. will fail and I have to write someting like that:
```pwsh
Describe "MyTestDescribe" {
  $arr = @(2, 5, 6, 8, 10) | ForEach-Object { @{ Value = $_ } }
  It "Test <Value>" -TestCases $arr {
    MyCustomFunction $Value | Should -Not -BeNullOrEmpty
  }
}
```

**Comment by nohwnd** [comment]
This has been requested few time already, I will try to look into it once v5 stabilizes a bit more.

**Comment by nohwnd** [comment]
Added #1679 to link all the pieces together, please comment.
