### ISSUE TITLE
Code coverage setup takes way longer when there are multiple analyzed files

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#1642]
![image](https://user-images.githubusercontent.com/5735905/88890874-8a687f00-d242-11ea-9a27-bf80e47dfdf4.png)

**Comment by asears** [comment]
Any way we can see the internal metrics time it takes to Analyze 104 of 104 commands in the file - what is holding up the discovery?

I'm seeing some scripts taking > 30 seconds to discover code coverage.

**Comment by nohwnd** [comment]
I saw that the most time is spent doint Set-Breakpoint, and even invoking the .NET api they use internally takes longer and longer time as the number of breakpoints increases. Imho this is something that would need to be fixed on powershell side.

**Comment by asears** [comment]
Some possibly related issues.
<https://github.com/PowerShell/PowerShell/issues/10530>
<https://github.com/PowerShell/PowerShell/issues/10188>
<https://github.com/PowerShell/PowerShell/issues/7269>
<https://github.com/PowerShell/PowerShell/issues/10530>

I didn't see any specific Powershell issues around Set-Breakpoint performance, sounds like something that could be repro'd and added as an issue to Powershell project?

Is this the affected class?  Could probably use some optimization if so.  Also hits the filesystem but that shouldn't increase each discover time exponentially with adding files.  Sysinternals Process Monitor / File Watcher or a .NET profile trace might help with tracking the culprit. 

Sounds like some accumulator or missing object disposal.

<https://github.com/PowerShell/PowerShell/blob/4b9b0788ed28ea6d463ce857d1ed81bd4a977a59/src/Microsoft.PowerShell.Commands.Utility/commands/utility/Set-PSBreakpoint.cs>

Would removing or disabling the breakpoints after each file discovery help with object garbage collection or performance?
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/remove-psbreakpoint?view=powershell-7
Are objects being disposed correctly?  Might be able to attach debugger to process and see which objects are growing with each call.

Could runspaces or parallel jobs help?  Some work being done recently here and additional links.
<https://github.com/PowerShell/PowerShell/issues/12240>
<https://github.com/PowerShell/PowerShell/issues/7524>
<https://github.com/PowerShell/PowerShell/blob/472943347d75db6adf669faa565941af4802a077/test/powershell/Modules/Microsoft.PowerShell.Utility/RunspaceBreakpointManagement.Tests.ps1>
<https://github.com/PowerShell/PowerShell/blob/f4382202ae4622bf26795e29a7b39b9d7cdfb3fb/test/powershell/Modules/Microsoft.PowerShell.Utility/RunspaceCmdlets.Tests.ps1>
<https://github.com/PowerShell/PowerShell/pull/10492>
<https://mcpmag.com/articles/2017/08/24/parallel-runspaces-in-powershell.aspx>
<https://devblogs.microsoft.com/scripting/beginning-use-of-powershell-runspaces-part-1/>
<https://github.com/PowerShell/PowerShell/blob/4b9b0788ed28ea6d463ce857d1ed81bd4a977a59/src/System.Management.Automation/engine/remoting/server/ServerRunspacePoolDriver.cs>

**Comment by nohwnd** [comment]
The problem is that we need to have all breakpoints in place in all the files that we might potentially hit. So there is no optimization. I can make the breakpoint self-remove when hit, but that does not help much either. I the meantime I made this PR, which does the same thing without any AST or breakpoints. So if there is any new development needed to be done on PowerShell side, it would be better to do this than optimizing breakpoints. 

https://github.com/PowerShell/PowerShell/pull/13589

**Comment by Fiander** [comment]
Just a quick question. Would it be possible on a big project to specify for witch files I want the coverage tested?
when in a big module writing a new function, or altering an existing function, locally i only need to know coverage of those files.

just like i only need unit tests of only that function to run. For me that would "fix" the local penalty for slow coverage.

**Comment by nohwnd** [comment]
Yes, you can do that. In fact you are already specifying the paths for the files to be instrumented. What the new `-CI` switch in v5 does is just trying to guess what are the files to be instrumented based on the tests that you run. But internally it also passes a list of files. 

If you look into the CodeCoverage section on PesterConfiguration you can see what is possible to be specified. 

```
PS C:\Projects\pester\bin> [PesterConfiguration]::default.CodeCoverage


Enabled        : Enable CodeCoverage. (False, default: False)
OutputFormat   : Format to use for code coverage report. Possible values: JaCoCo (JaCoCo, default: JaCoCo)
OutputPath     : Path relative to the current directory where code coverage report is saved. (coverage.xml, default:
                 coverage.xml)
OutputEncoding : Encoding of the output file. (UTF8, default: UTF8)
Path           : Directories or files to be used for codecoverage, by default the Path(s) from general settings are
                 used, unless overridden here. (System.String[], default: System.String[])
ExcludeTests   : Exclude tests from code coverage. This uses the TestFilter from general configuration. (True,
                 default: True)
```

**Comment by nohwnd** [comment]
This slowdown is caused by how the debugger is resolving breakpoints, posted a fix on powershell repo.
