### ISSUE TITLE
Pester test runner can see a Should assertion Failure but the test still passes

### ISSUE THREAD

**Issue by plastikfan** [pester/Pester#1643]
## 1. General summary of the issue

I have found a rather odd situation where an asertion failure occurs but Pester doesn't recognise the failure and the test still passes. The problem this causes is that you can't see exactly which test is causing the assertion failure, because Pester hasnt recognised it and therefore does not identify the actual test.

## 2. Describe Your Environment
 When this situation occurred, I halted my development in order to preserve the actual state of my project in this failing state so I could raise this issue. The best way for somebody else to observe this issue is for them to checkout the repo (https://github.com/plastikfan/Loopz), switch to branch 'feature/pluck-descendents'.

Once, checked out, the user needs to perform the following steps
1) install dependent module 'Elizium.Krayola' from powershell gallery
2) cd into directory 'Elizium.Loopz'
3) run the invoke-build build, just run this: 'Invoke-Build'

you should see a test case run which doesn't fail, but there are Should based assertion failures. I know what the fault is, that's not the problem. The problem is that the test did not fail.

Pester version     : 5.0.2 C:\Users\Plastikfan\Documents\PowerShell\Modules\Pester\5.0.2\Pester.psd1
PowerShell version : 7.0.3
OS version         : Microsoft Windows NT 10.0.19041.0

## 3. Expected Behavior

There is a fault with the test currently tagged 'BROKEN':

Invoke-TraverseDirectory.given: directory tree.Should: traverse [See: **Invoke-TraverseDirectory.tests.ps1**](https://github.com/plastikfan/Loopz/blob/feature/pluck-descendents/Elizium.Loopz/Tests/Public/Invoke-TraverseDirectory.tests.ps1)

```powershell
      [scriptblock]$summary = {
        param(
          [int]$_count,
          [int]$_skipped,
          [boolean]$_trigger,
          [System.Collections.Hashtable]$_passThru
        )
        $index = $_passThru['LOOPZ.FOREACH-INDEX'];
        $index | Should -Be 19;
      }

      Invoke-TraverseDirectory -Path $resolvedSourcePath `
        -SourceDirectoryBlock $feDirectoryBlock -Summary $summary;
```
The "Should -Be 19;", is the assertion that fails, without failing the test and this should be identified by Pester as is normally the case when a Should assertion fails. (The call to Invoke-TraverseDirectory results in the **$summary** scriptblock being invoked as a callback)

## 4.Current Behavior

This shows the current behaviour of the faulty but succeeding test case:

```
Invoke-ForeachFsItem: C:\Users\Plastikfan\dev\github\PoSh\Loopz\Elizium.Loopz\Output\Elizium.Loopz\Elizium.Loopz.psm1:363
Line |
 363 |  …   $directoryInfos | Invoke-ForeachFsItem -Directory -Block $adapter `
     |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Foreach Error: (Exception calling "Invoke" with "4" argument(s): "Expected 19, but got 7."), for item: 'Fields Of The Nephilim'

Invoke-ForeachFsItem: C:\Users\Plastikfan\dev\github\PoSh\Loopz\Elizium.Loopz\Output\Elizium.Loopz\Elizium.Loopz.psm1:363
Line |
 363 |  …   $directoryInfos | Invoke-ForeachFsItem -Directory -Block $adapter `
     |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Foreach Error: (Exception calling "Invoke" with "4" argument(s): "Expected 19, but got 7."), for item: 'GOTHIC'

Invoke-ForeachFsItem: C:\Users\Plastikfan\dev\github\PoSh\Loopz\Elizium.Loopz\Output\Elizium.Loopz\Elizium.Loopz.psm1:363
Line |
 363 |  …   $directoryInfos | Invoke-ForeachFsItem -Directory -Block $adapter `
     |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Foreach Error: (Exception calling "Invoke" with "4" argument(s): "Expected 19, but got 11."), for item: 'FUSE'

Invoke-ForeachFsItem: C:\Users\Plastikfan\dev\github\PoSh\Loopz\Elizium.Loopz\Output\Elizium.Loopz\Elizium.Loopz.psm1:363
Line |
 363 |  …   $directoryInfos | Invoke-ForeachFsItem -Directory -Block $adapter `
     |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Foreach Error: (Exception calling "Invoke" with "4" argument(s): "Expected 19, but got 17."), for item: 'Plastikman'

WARNING: TBD (Invoke-TraverseDirectory.tests): Apply Assert
WARNING: TBD (Invoke-TraverseDirectory.tests): Apply Assert
[+] C:\Users\Plastikfan\dev\github\PoSh\Loopz\Elizium.Loopz\Tests\Public\Invoke-TraverseDirectory.tests.ps1 228ms (135ms|89ms)
[+] C:\Users\Plastikfan\dev\github\3rd\Loopz\Elizium.Loopz\Tests\Public\Select-Directory.tests.ps1 794ms (86ms|609ms)
Tests completed in 6.57s
Tests Passed: 75, Failed: 0, Skipped: 1 NotRun: 0
Done /./Tests/Pester 00:00:07.1585111
Done /./Tests 00:00:07.1839290
Task /./Stats/RemoveStats
Done /./Stats/RemoveStats 00:00:00.0039247
Task /./Stats/WriteStats
Done /./Stats/WriteStats 00:00:00.0669441
Done /./Stats 00:00:00.0732247
Done /. 00:00:08.7095247
```
**Note: the Failed count is 0**

I can see that this is due to a problem inside 'Invoke-TraverseDirectory.tests.ps1', but I can't see which individual test is at fault.

## 6. Context

When this fault initially made itself apparent, it took some time (more than is usually the case for this scenario) to track down exactly which test was responsible for the failure, because the actuall runtime error messages occurred at a point in code that is widely excercised and not easily attributable to the failing test. If Pester had failed the test, I would have seen an error message identifiying the broken test (*Invoke-TraverseDirectory/given: directory tree/Should: traverse*)

**Comment by fflaten** [comment]
Short answer; this catch-block swallows the error/exception used by Pester to identify the failed test. You should avoid "catch all" blocks and specify your expected exception-types.
https://github.com/plastikfan/Loopz/blob/b55769db8c78d9bb3521f024406b2dc1774cad14/Elizium.Loopz/Public/Invoke-ForeachFsItem.ps1#L85-L87

Tbh, this happens after 2 levels of recursions with Invoke-ForeachFsItem using scriptblock parameters and callbacks so my head spins at this point. Fix that and Pester works as expected.

**Comment by nohwnd** [comment]
External to Pester.

**Comment by plastikfan** [comment]
Ok, so the Should is throwing an exception that Pester expects to see, but because it's being swallowed, it can't identify the test. Got it. Thanks. This was only intermediate code and wasn't in it's final state.

**Comment by nohwnd** [comment]
Yes. But just to clarify, the exception can come from anything and can have any type. If any code throws Pester will catch it and report it. You did not throw so the test was considered to be success.

**Comment by plastikfan** [comment]
I was thinking about adding a note to this section: https://github.com/pester/Pester/#collect-all-should-failures. (?)

**Comment by nohwnd** [comment]
Sure.
