### ISSUE TITLE
Output tags in the test result XML

### ISSUE THREAD

**Issue by cathalmchale** [pester/Pester#1649]
## 1. General summary of the issue

"Tags everywhere" is useful in v5 to filter test runs. But I'd like to see relevant tags enumerated in the test results xml "Tags" column, if that was possible?

## 2. Describe Your Environment

Using Azure DevOps pipeline and the new Marketplace build step. Outputting test results XML in NUnit format and uploading that. Tags column is empty for all tests.

## 3. Expected Behavior

Ideally relevant Tags would be enumerated per test line in the published results.

## 4.Current Behavior

Tags column is empty.

## 5. Possible Solution

List all relevant tags per test line item. Ok to have all tags listed here, I'd say e.g. unique list of tags from Describe, Context, It for each test line in the results XML.

## 6. Context

With the Tags column populated in the published test results , it'll be easy to filter tests that have already run when considering the published test results output.

**Comment by fflaten** [comment]
Tags are not listed in the official [mapping table](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml#result-formats-mapping) to test results. Categories in Nunit 2.5 xml schema didn't work either.

Will probably require a feature request to MS first to support NUnit categoeries as tags in DevOps test report.

**Comment by fflaten** [comment]
Closing. Can reopen and consider later if MS enables us to publish tags somehow.
