### ISSUE TITLE
version 5 of pester does not recognize explicit file path with custom name ( example .specs.ps1 or .infra.ps1) 

### ISSUE THREAD

**Issue by Nithyanathan** [pester/Pester#1651]
## 1. General summary of the issue
if the pester test cases file is saved with the custom name: Example i saved it in the form of "infra.specs.ps1" and when i run the pipeline the module does not pick up these files and throws an error no script block specified 

## 2. Describe Your Environment
I am using Azure DevOps based setup for deploying base infra in Azure and pass the pester test cases of Performing Unit tests

**Comment by nohwnd** [comment]
I tried it locally and it works for me, how exactly are you doing it? It works when I include just the path, and also when I include path and directory.

```powershell
# this is abc.Spec.ps1

Write-Host ">>>> $PSCommandPath"

Describe "a" {
    It "b" {
        1 | Should -Be 2
    }
}
```

![image](https://user-images.githubusercontent.com/5735905/90306031-51c6d780-dec9-11ea-97ca-6dbbd8ac3828.png)

**Comment by Nithyanathan** [comment]
@nohwnd Yeah seems to be working, I think my absolute path had some spaces. we are good to close this 

Thanks a lot

**Comment by Nithyanathan** [comment]
Yeah seems to be working, I think my absolute path had some spaces. we are good to close this
