### ISSUE TITLE
Mocking a "Function" with a -ParameterFilter overrides the behavior of the instances that don't succeed the filter.

### ISSUE THREAD

**Issue by EdLichtman** [pester/Pester#1653]
## 1. General summary of the issue

When I Mock a function with a parameter filter, other instances that the function is called are Mocked as well. It doesn't seem to "Filter" completely.

## 2. Describe Your Environment

Pester version     : 5.0.3 C:\Program Files\WindowsPowerShell\Modules\Pester\5.0.3\Pester.psd1
PowerShell version : 5.1.19041.1
OS version         : Microsoft Windows NT 10.0.19041.0

## 3. Expected Behavior

If I want to use Environment variables to include a variable called: $FunctionFolder, I can do that.

In Get-FunctionA.ps1 I can rely on an $FunctionFolder from an "EnvironmentVariables.ps1" file. Then I can dot-source Get-FunctionB.ps1 for later use.

Like so:

`Invoke-Expression ". '$ProjectPath\EnvironmentVariables.ps1'".`
`Invoke-Expression ". '$ProjectPath\Get-FunctionB.ps1'"`

Now, I can set $FunctionFolder = "$ProjectPath\IntegrationTestFunctionFolder", so that I can run integration tests on "Get-FunctionA.ps1" using the IntegrationTestFunctionFolder, without disrupting the actual $FunctionFolder.

I can do this by mocking Invoke-Expression as follows:
`Mock Invoke-Expression -ParameterFilter { $Command -match ". '*\EnvironmentVariables.ps1'" }`

I expect that when I Mock a function using -ParameterFilter, any instances that do not meet the "ParameterFilter" work as normal. This way I can test the integration of Get-FunctionB.ps1 inside of the Get-FunctionA.ps1.

## 4.Current Behavior

When I attempt the above, I see the following in the Pester-Output:
```
Mock: Mock filter did not pass. 
Mock: No parametrized or default behaviors were found filter. 
Mock: Invoking the original command. ****

```
Right there it's telling me that it's invoking the original command. However, it doesn't dot source the file.

You can see an example here:

[https://github.com/EdLichtman/Test-PesterBug](https://github.com/EdLichtman/Test-PesterBug)

## 5. Possible Solution

I am hoping that you might have a possible solution or workaround?

## 6. Context

The issue has affected me because I'm trying to make my [Quick-Package](https://github.com/EdLichtman/Quick-Package/) project Tested. I made the unit tests, and I figured out how to make the "Import Validation Tests" to make sure that if I refactor all the code still works. Now I'm trying to make the Integration tests, and I'm finding that I can't make integration tests without completely nuking the behavior of invoke-expression.

**Comment by nohwnd** [comment]
Thanks for the report, I was able to find the root cause thanks to your example but I don't have a solution right now. The problem is that once the original command is invoked it is invoked two levels too deep, so your file is dotsources, but all the functions it defines are then promptly thrown away when the scope ends. 

You can see it here, where print how far away I am from the `$error` variable, which equals to the number of scopes that are above the current code because `$error` is defined automatically and is not `AllScopes`.  

I invoke the code once directly and then using Invoke-Expression that is under mock but fails the filter, so the original command is invoked. They return 6 and 8, meaning the one under mock is 2 levels deeper.

```powershell
Describe "The problem" {
    It "Shouldn't have an issue dot sourcing a secondary function" {
        Write-Host (Invoke-Expression '$i=0; while (-not (get-variable -ea 0 -name error -scope ($i++))) {}; $i-1') 
        Mock Invoke-Expression { } -ParameterFilter { $false }
        Write-Host (Invoke-Expression '$i=0; while (-not (get-variable -ea 0 -name error -scope ($i++))) {}; $i-1') 
    }
}
```

I think there is a bug in your code btw, your Parameter filter uses `-match`, but I think it should use `-like`, you are now matching any amount of `'` before `\`, instead of any text in between `'` and `\`.

**Comment by EdLichtman** [comment]
@nohwnd -- First of all, Good catch on the -match vs -like, I can't believe I missed that 🤦.

Second of all, thanks so much for your quick response! I tested your theory -- you can see an updated example at [https://github.com/EdLichtman/Test-PesterBug](https://github.com/EdLichtman/Test-PesterBug). I added the "global" scope to a function that got dot sourced and I can see that it works!

So I already have a workaround for the dot-source scenario, That is to run:
`Invoke-Expression (Get-MockImportsHeader)`
using the file here: [Get-TestHeaders.ps1](https://github.com/EdLichtman/Quick-Package/blob/master/Required/Reserved/Get-TestHeaders.ps1)

As for any other scenario that I use Invoke-Expression, I don't foresee this to be a problem anymore because of how I use them!

I would be glad to close this, but first I'm a bit new to PowerShell Unit Testing and I'm wondering if you could explain from a more Advanced viewpoint, how do other users generally solve the problem of Mocking Functions and variables without them getting overwritten by a dot source within the tested function?

**Comment by EdLichtman** [comment]
So the answer to, from a more advanced viewpoint, how the mocking occurs is, it is done in Modules.

Basically, it turns out psm1 file imports functions into the Module Scope, so you don't have to dot source anything in the function itself. Then, you export the Module Members that you wish to export. So by transitioning this to a module, I was able to move away from dot-sourcing entirely except from within the .psm1 file.
