### ISSUE TITLE
[v5] Using `-Not` for `Should -Invoke` does not appear to work

### ISSUE THREAD

**Issue by glennsarti** [pester/Pester#1655]
## 1. General summary of the issue

Using the new mock assertion syntax, it appears that `-Not` has no effect. For example.

I would expect the line below to assert that the function `Invoke-OtherThing` is never called

`Should -Not -Invoke Invoke-OtherThing`

## 2. Describe Your Environment

Windows 10 : 19041
Pester : 5.0.3
PowerShell : 7.0.0

Repro Test File

``` powershell
Describe 'Repro' {
  BeforeAll {
    Function Invoke-OtherThing { 1 }
    Function Invoke-Thing([switch]$CallOtherThing) { if ($CallOtherThing) { Invoke-OtherThing } }
  }

  it 'should call thing when told to' {
    Mock Invoke-OtherThing { 'MockResult'}

    $result = Invoke-Thing -CallOtherThing
    $result | Should -Be 'MockResult'

    Should -Invoke Invoke-OtherThing
  }

  it 'should not call thing when told to' {
    Mock Invoke-OtherThing { 'MockResult'}

    $result = Invoke-Thing
    $result | Should -BeNullOrEmpty

    Should -Not -Invoke Invoke-OtherThing
  }
}
```

Repro output
``` text
C:\Source\somewhere [munge-for-syd-mel +1 ~2 -0 !]> invoke-pester -Output Detailed .\Tests\Scripts\test.ps1

Starting discovery in 1 files.
Discovering in C:\Source\somewhere\Tests\Scripts\test.ps1.
Found 2 tests. 94ms
Discovery finished in 203ms.

Running tests from 'C:\Source\somewhere\Tests\Scripts\test.ps1'
Describing Repro
  [+] should call thing when told to 497ms (451ms|46ms)
  [-] should not call thing when told to 51ms (46ms|5ms)
   Expected Invoke-OtherThing to be called at least 1 times but was called 0 times
   at Should -Not -Invoke Invoke-OtherThing, C:\Source\somewhere\Tests\Scripts\test.ps1:22
   at <ScriptBlock>, C:\Source\somewhere\Tests\Scripts\test.ps1:22
Tests completed in 1.38s
Tests Passed: 1, Failed: 1, Skipped: 0 NotRun: 0
```

## 3. Expected Behavior

Using `-Not` should set the number of expected invocations to zero

## 4.Current Behavior

Using `-Not` sets the number of expected invocations to one

**Comment by glennsarti** [comment]
Workaround.

`Should -Invoke Invoke-OtherThing -Times 0` does test correctly.

**Comment by nohwnd** [comment]
You are right, https://github.com/pester/Pester/blob/47c3c138d2bf1d87d5283365a8975a8f31b6b13c/src/functions/Pester.SessionState.Mock.ps1#L872 this needs to change the call to be -Exactly 0 times when $Negate is specified, and log it. Would you like to PR this @glennsarti ?

**Comment by glennsarti** [comment]
@nohwnd   Yeah, I'll have a go.  There's a few edge cases to this so I'd need to setup the tests correctly.

**Comment by glennsarti** [comment]
You can assign the me

**Comment by glennsarti** [comment]
Hrmm...this is going to be a little more complicated... the current code doesn't easily deal with tests like:

`Should -Invoke 5` will match 5,6,7 .... etc. invocations therefore  `Should -Not -Invoke 5` should match 0-4 invocations
`Should -Invoke 5 -Exactly` will match 5. invocations therefore  `Should -Not -Invoke 5 -Exactly` should match 0,1,2,3,4,6,7,... invocations

`Should -Not -Invoke` (with no number or exactly) is easy to change the code for.

Also, this should be applicable for `Should-InvokeVerifiable`
