### ISSUE TITLE
Add VSCode devcontainer configuration to project

### ISSUE THREAD

**Issue by fflaten** [pester/Pester#1657]
## 1. General summary of the issue

Adding a recommended, optional devcontainer-configuration to the project might help current and future contributors to get started faster using VSCode while keeping their systems clean.

See https://code.visualstudio.com/docs/remote/containers and/or https://code.visualstudio.com/docs/remote/containers-tutorial

## 3. Expected Behavior

Open this project in VSCode on a computer with docker and automatically get a suitable dev environment including the right tools, SDKs and extensions to contribute to Pester. 

## 4.Current Behavior

Users have to install .NET Core ++ locally and manually before being able to build and contribute to the project.

## 5. Possible Solution

Add a devcontainer-configuration to the project which includes PowerShell, .NET Core, VS Code Extensions (Powershell + C#) ++.

Could use the [dotnetcore ](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/dotnetcore/.devcontainer) sample devcontainer as a starting point.

## 6. Context

VSCode + [Remote - Container](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) extension + Docker allows a developer to work on a project inside a specialized development container to keep a consistent environment for all contributors. The container image can include necessary build & test tools + useful extensions for VSCode itself.

Considering the project's build process now includes both PowerShell and C# using .NET Core, it might be time introduce this as it keeps a user's system clean while also potentially improving compilation/test performance.

**Comment by fflaten** [comment]
Just realized that the dll is compiled against .Net Framework 4.5.2 so it won't be buildable in a unix-container. Guess this request should be paused until this is .NET Standard only.

**Comment by nohwnd** [comment]
There are two of the dlls, you could add option to just build the modern one in the container, because you will not need the other part in the containr, and the functionality in the dll is not different among the old and the new one.

Or possibly reference the net framework reference assemblies package and use:
```
export FrameworkPathOverride=<extracted nuget path>/microsoft.targetingpack.netframework.v4.7.2/1.0.0/lib/net472/
```
This way you might be able to build in the container for net4x as well.  But imho simply not building the netframework one is good enough.

**Comment by nohwnd** [comment]
Let's at least try this, I would love to try it out :)
