### ISSUE TITLE
PesterConfiguration values don't take affect when setting within a test file

### ISSUE THREAD

**Issue by hugh-martin** [pester/Pester#1660]
## PesterConfiguration values don't take affect when setting within a test file

I'm using latest version of Pester (5.0.3) with PowerShell 5.1 on Windows 10 1809 and I'm trying to override some of the default PesterConfiguration values.  I have a BeforeAll block as the first block in my test.  In that block, I have the following:

```
$PesterPreference = [PesterConfiguration]::Default
$PesterPreference.TestResult.Enabled = $true
$PesterPreference.Output.Verbosity = "Detailed"
$PesterPreference.Debug.WriteDebugMessages = $true
$PesterPreference.Debug.WriteDebugMessagesFrom = "Mock"
```

If I set these at the command line before running Invoke-Pester, they take affect.  However, setting them within BeforeAll does not work.  What's the best way to set these values within a test file?  Thanks.

**Comment by asears** [comment]
I think configuration object is collected at invoke-pester time in the current session.  You might need to use tagging functionality and run invoke-pester twice with different configurations and tags to override some of the default values for those specific tests.

**Comment by hugh-martin** [comment]
OK, thanks.
