### ISSUE TITLE
Show test execution start datetime

### ISSUE THREAD

**Issue by majkinetor** [pester/Pester#1667]
I want to see in the detailed report exact time when test was started. I have hundreds of tests and when some fail I want to see application logs only after the time it was started and before the time next test started.

## Example

Currently I see

```
   [+] prevents updating user with invalid Name 262ms (260ms|1ms)
   [+] prevents updating user with invalid Email 70ms (68ms|1ms)
   [+] prevents updating user Login attribute 116ms (115ms|1ms)
```

What I would like to have is test execution start time added (`get-date -format 'yyyy-MM-dd HH:mm:ss:fff'`)

```
   [+] prevents updating user with invalid Name 262ms (260ms|1ms) [2020-08-31 11:29:14.039]
   [+] prevents updating user with invalid Email 70ms (68ms|1ms) [2020-08-31 11:29:14.299]
   [+] prevents updating user Login attribute 116ms (115ms|1ms) [2020-08-31 11:29:14.367]
```

**Comment by fflaten** [comment]
Sounds like a scenario where you'd like to use `-PassThru` and retrieve it from the output-object. 
```
$p = Invoke-Pester ./demo.tests.ps1 -PassThru
$p.Tests | ft ExpandedName, ExecutedAt, @{n="DurationMS";e={ "{0:0.00}ms" -f $_.Duration.TotalMilliseconds }}

ExpandedName             ExecutedAt           DurationMS
------------             ----------           ----------
fails                    9/10/2020 7:49:41 PM 1009.70ms
passing with testcases 1 9/10/2020 7:49:42 PM 14.58ms
passing with testcases 2 9/10/2020 7:49:42 PM 8.11ms
fails                    9/10/2020 7:49:43 PM 1009.08ms
```

**Comment by nohwnd** [comment]
Agree here, that info would be hard to add to all the possible outputs in a meaningful way, this is a case where you would need your own reporter, which won't be possible until the internal plugins are made available for you to modify.

**Comment by majkinetor** [comment]
@fflaten thanks, I already make test results available as an artifact, but I didn't notice ExecutedAt field.

**Comment by majkinetor** [comment]
BTW, I was also able to show time in log with pester plugin mentioned earlier in #1611. I just added `Write-Verbose (Get-Date)` there to show date above tests.
