### ISSUE TITLE
[Freature request] TestCases naming

### ISSUE THREAD

**Issue by DarkLite1** [pester/Pester#1669]
## 1. General summary of the issue

This code works fiine with Pester `5.0.3`:
```powershell
Invoke-Pester ./test.Tests.ps1' -Output Detailed

Context 'a mandatory parameter is missing' {
        It '<name>' -Tag 'test' -TestCases @(
            @{name = 'ScriptName' },
            @{name = 'ComputerName' },
            @{name = 'MailTo' }
        ) {
            (Get-Command $sut).Parameters[$name].Attributes.Mandatory | Should -BeTrue
        }
    }
```
It generates the complete list of mandatory arguments:

![image](https://user-images.githubusercontent.com/10828570/91963336-05272d00-ed0e-11ea-9c6c-65dbc9ba76a1.png)

It would be great if we could also use the `<name>` as a variable like `$name`
```powershell
Context 'a mandatory parameter is missing' {
    It $name -Tag 'test' -TestCases @(
        @{name = 'ScriptName' },
        @{name = 'ComputerName' },
        @{name = 'MailTo' }
    ) {
        (Get-Command $sut).Parameters[$name].Attributes.Mandatory | Should -BeTrue
    }
}
```

**Comment by nohwnd** [comment]
I am not sure what you are asking me to do. Do you want to make it possible to take keys from -TestCases and be able to use them as variables in that are provided as parameters to It function?

**Comment by DarkLite1** [comment]
I just thought it would be easier to see variables highlighted when we us `It $name ` instead of `It <name> `. It makes it clearer in vs code that this is a variable name.

**Comment by nohwnd** [comment]
Yeah, the problem is that whatever you'd do, the $Name will not get value from TestCases because you don't know the value yet. You could do single quotes string, and then would expand it later after you collect the TestCases and translate them to variables. But as it is now (powershell, not Pester) the $name would simply resolve to $name variable in the current (or parent) scope and would likely be $null.

**Comment by DarkLite1** [comment]
I hear you. Closing this one.
