### ISSUE TITLE
Can't find type [PesterConfiguration] though Pester 5.0.1

### ISSUE THREAD

**Issue by blindzero** [pester/Pester#1674]
## 1. General summary of the issue
Maybe not 100% Pester as Azure Devops pipeline environment...but help still appreciated ;)

Using Pester v5 Configuration, initialized by 
```powershell
$PesterConfiguration = [PesterConfiguration]::Default
```

It is working on my local environments, but not in Azure Devops pipeline, although I am updating Pester in the pipeline image to 5.0.1 (using PSDepend). 
Tried to verify with output of .Version of ```Get-Command Invoke-Pester```: ```5.0.1```

I get the error
```powershell
At D:\a\1\s\build\tasks\psakeTask.PesterUnit.ps1:20 char:28 +     $PesterConfiguration = [PesterConfiguration]::Default +                            ~~~~~~~~~~~~~~~~~~~~~ [<<==>>] Exception: Unable to find type [PesterConfiguration].
```

## 2. Describe Your Environment

- Azure Devops Pipeline, using ```vmImage: windows-latest```
- Updating Pester through PSDepend dependencies.psd1 config to 5.0.1

```powershell
Pester version     : 5.0.1 C:\Users\VssAdministrator\Documents\WindowsPowerShell\Modules\Pester\5.0.1\Pester.psd1
PowerShell version : 5.1.17763.1007
OS version         : Microsoft Windows NT 10.0.17763.0
```

## 3. Expected Behavior

Initializing $PesterConfiguration without error

## 4.Current Behavior

error
```powershell
At D:\a\1\s\build\tasks\psakeTask.PesterUnit.ps1:20 char:28 +     $PesterConfiguration = [PesterConfiguration]::Default +                            ~~~~~~~~~~~~~~~~~~~~~ [<<==>>] Exception: Unable to find type [PesterConfiguration].
```

## 6. Context

Initializing $PesterConfiguration with default values

**Comment by asears** [comment]
Try using Powershell Core, and using 

```powershell
Import-Module Pester -Force
```

after the install.  For some reason I don't think Pester self-imports the C# dependencies as part of loading up the Powershell session, at least in Az Devops.

There needs to be more documentation around this and process with Azure Devops should be smoother.  
I had issues with this too, took a few permutations before it worked. 

There's also an extension here though I needed the flexibility of installing separately to get access to other packages like Az.Kusto and Az.Support.

https://github.com/pester/AzureDevOpsExtension

**Comment by nohwnd** [comment]
@blindzero could you make a minimal pipeline where this reproduces and publish it / share it, please?

**Comment by fflaten** [comment]
Isn't this the default everywhere? If you open PowerShell and just write `$P = [pesterconfiguration]::default` then you at least I always get the error. AFAIK module auto loading only works with the resources you've defined in the module manifest. The c# binary and it's classes is first introduced when `Add-Type -Path "$PSScriptRoot/bin/<framework>/Pester.dll"` is called during module import.

A workaround could be to export the private function `New-PesterConfiguration` and update docs. It's the same as `[PesterConfiguration]::Default`, but can be mentioned in the manifest. When a user calls it, the module should be auto-imported including the required dll.

**Comment by nohwnd** [comment]
@fflaten Ah, gotcha. I always import the module first in any of my pipelines, it seemed obvious __to me__ that the type would not be present without having Pester imported, but now that you mention module auto-loading I see how it might be not.

Yeah wrapping that type into cmdlet is long overdue and I should definitely write a proposal for it. Do you want to help me drive this?

**Comment by fflaten** [comment]
Sure. Any requirements/thoughts? Was just thinking of exporting the existing method with the addition of a parameter set for the override-dictionary. Keeping it simple enough the support the current user scenarios while supporting auto-loading. Don't want to take the spotlight from the sweet custom configuration-object 🙂

**Comment by nohwnd** [comment]
Yeah I don't know, I would like it to make sense and feel obvious in PowerShell. Will have to think about it a bit.

**Comment by fflaten** [comment]
Sure, it's important to find the balance here so we don't end up confusing the user with too many options. 👍 

There's already a very detailed and useful (non-traditional) configuration object and parameters (some deprecated though) in Invoke-Pester.

**Comment by blindzero** [comment]
Hi everybody,
I'm happy that there really seems to be an issue. Honestly, I am not a real coder, just using Pester as a very nice tool.
I tried to debug my pipeline and what I don't get:

Having one simple pipeline with one job one script task it works fine.
Having a more complex pipeline with multiple tasks it doesn't work with my build scripts:

- one task is for init and bootstrap, installing and importing all modules with PSDepend
- a separate task later (after fetching artifacts) is for testing, trying to create the PesterConfiguration object
- putting a separate Import-Module for Pester into the init task does not solve the issue

It works as soon as I move the separate Import-Module for Pester from init task directly into the task doing Pester tests.

(I am not using Pester Azure pipeline tasks as I want to use the same tool chain as locally, where all works perfectly by the way).

Sorry for those noob questions...but why is behaving that way?

**Comment by fflaten** [comment]
Pipeline tasks run in their own PowerShell process, so modules needs to be imported per task. Since `[PesterConfiguration]` isn't automatically imported, you need to use `Import-Module` in the task where you create the configuration + run Pester until this issue is fixed (new cmdlet introduced)
