### ISSUE TITLE
Pester not consistent when comparing embedded objects

### ISSUE THREAD

**Issue by demdante** [pester/Pester#1675]
## 1. General summary of the issue
Consider the below pester test:

```powershell
Describe "Start-StoppedAutomaticServices PS$PSVersion" {
    Context "When service is stopped and not disabled" {
        It "should start the service with service name" {
            $testrone = @{
                servicesuccess = @("Audiosrv")
                success = $true
            }
            $testone = ConvertTo-Json $testrone
            $retval = @{
                success = $true
                servicesuccess = @("Audiosrv")
            }
            $json = ConvertTo-Json $retval
            $testone | Should -Be $json
        }
        It "should start the service with display name" {
             $testrtwo =@{
                servicesuccess = @("gpsvc")
                success = $false
             }
             $testtwo = ConvertTo-Json $testrtwo
             $retval = @{
                success = $false
                servicesuccess = @("gpsvc")
            }
            $json = ConvertTo-Json $retval
            $testtwo | Should -Be $json
        }

    }
    Context "When service is disabled" {
        It "should return a failure" {
            $testthree = Run -servicename "upnphost"
            $failure = @{
                Name = "upnphost"
                error = 2
            }
            $hol = @{
                servicefail = @($failure)
                success = $false
            }
            $json = ConvertTo-Json $hol
            $testthree | should -Be $json
        }
    }
    Context "When service is disabled" {
        It "should return a failure" {
            $hol2 = @{
                error = 2
                Name = "upnphost"
            }
            $another = @{
                success = $false
                servicefail = @($hol2)
            }
            $testthree = ConvertTo-Json $another
            $failure = @{
                Name = "upnphost"
                error = 2
            }
            $hol = @{
                servicefail = @($failure)
                success = $false
            }
            $json = ConvertTo-Json $hol
            $testthree | should -Be $json
        }
    }
}
```

For the purpose of more clear communication and troubleshooting, I have substituted the function being tested with explicit code.  If you place the above code in a pester test file and run it with invoke-pester, you get this output:

![image](https://user-images.githubusercontent.com/64720591/92156427-7c48e800-ee18-11ea-82b1-605c7eccbe6b.png)

I find this result to be very...interesting.  You have two tests essentially: one which compares two hashtables that have been converted into json objects, and one which compares two hashtables which contain embedded hashtables that have been converted into json objects.  I find the result interesting because, as you can see from the two tests which compare the simple hashtables, I intentionally swap the location of the properties that those hashtables contain when comparing the objects:

```
$testrone = @{
                servicesuccess = @("Audiosrv")
                success = $true
            }

$retval = @{
                success = $true
                servicesuccess = @("Audiosrv")
            }
```

When pester compares the object that is created after converting these two hashtables to json objects, it concludes that they are equivalent and does not throw an error.  I did the same thing with the hashtables and embedded hashtables in the last test as well.  However, when comparing the two objects that are created when converting the hashtables into json objects, pester returns an error this time.  Based on the error that pester is outputting, it appears that pester is generating the error because it is looking at the order in which the values are declared, but **only for the embedded hashtable.**  That is the problem that I see: it would appear that pester does not do too well when handling objects embedded within other objects.

## 2. Describe Your Environment

If you would like to submit a bug report, please provide the output of a code provided below.

If you would like to write about anything else - like a feature request - feel free to remove a provided template text.
Windows 10 x64 Enterprise
Pester version:
get-module pester
ModuleType Version    Name                                ExportedCommands                                                    
---------- -------    ----                                ----------------                                                    
Script     5.0.3      pester                              {Add-ShouldOperator, AfterAll, AfterEach, Assert-MockCalled...}

PowerShell version:
Name                           Value                                                                                           
----                           -----                                                                                           
PSVersion                      5.1.18362.752                                                                                   
PSEdition                      Desktop                                                                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                         
BuildVersion                   10.0.18362.752                                                                                  
CLRVersion                     4.0.30319.42000                                                                                 
WSManStackVersion              3.0                                                                                             
PSRemotingProtocolVersion      2.3                                                                                             
SerializationVersion           1.1.0.1                                                                                         

## 3. Expected Behavior

I would expect pester to be able to properly identify and handle all objects within the json object (in this case, hashtables) within the json objects.

## 4.Current Behavior

Unless there is an error in my code (I don't think there is), it seems pester is unable to correctly identify and compare embedded objects contained within json objects

## 5. Possible Solution

Pfft.  Hell if I know.  I will take a look at the code and see if I can do something (which I have yet to do mind you), but no promises.

## 6. Context

I work for a very large financial institution which has just recently decided to dip its toe in the water and try automating some processes.  For the windows servers, we are using powershell scripts in order to accomplish this.  However, the current process that we have for approving, testing, review, and pushing to production, at the moment, is **all manual**, and I think that that is insane.  I discovered this issue in the middle of putting together a demonstration of how we can create a more streamlined process for testing code, with the overall goal being to create a powershell ci/cd pipeline that can automate a lot of the steps that we do manually, and pester is, obviously, going to be responsible for the unit testing.  However, we have a special tool in the environment that we use to actually run these scripts called "HP Operations Orchestration" (will refer to as HPOO going forward), and the way that we have it configured requires that the powershell scripts that we write always returns a json formatted string with certain required values so that hpoo can "read" the output.  So, in order for this to work, it is critical that pester be able to compare json objects like the ones I included in the example, as that is literally how every script has to be written in this environment, and I am going to have a hard time selling this pipeline idea to my manager if pester is unable to accurately compare the json return objects.

**Comment by asears** [comment]
I think avoiding the piped comparison, and getting output into something raw and comparable that doesn't introduce artifacts of Powershell is your best bet here.  JSON seems to have lots of side-effects with Powershell.

I found a couple of possibly related issues.  #1154 pipeline | eating the array, way back to #246 ordering, 

Could look at doing the test in straight Powershell then just feeding it a success or failure to Pester?

Some more interesting tidbits on nested json arrays.

https://stackoverflow.com/questions/58185002/how-to-compare-json-in-powershell

https://stackoverflow.com/questions/53583677/unexpected-convertto-json-results-answer-it-has-a-default-depth-of-2

https://4sysops.com/archives/convert-json-to-a-powershell-hash-table/#:~:text=It's%20possible%20to%20carry%20around,data%20to%20a%20hash%20table.

https://petri.com/how-to-use-powershell-7-to-work-with-json-files

Probably some workarounds or helper functions in those links.

**Comment by nohwnd** [comment]
If this is about being able to compare hashatables, I wrote this a while ago: https://github.com/nohwnd/Assert You can use Asset-Equivalent to compare quite complex objects. Here is a short talk about it: https://jakubjares.com/2018/12/18/pspowerhour-assert/

**Comment by demdante** [comment]
> 
> 
> If this is about being able to compare hashatables, I wrote this a while ago: https://github.com/nohwnd/Assert You can use Asset-Equivalent to compare quite complex objects. Here is a short talk about it: https://jakubjares.com/2018/12/18/pspowerhour-assert/


Thank you, @asears and @nohwnd , for your comments.  @nohwnd I will definitely take a look at your module and give it a shot.  I will let you all know.

**Comment by demdante** [comment]
@nohwnd Your module works.  If I convert the json string into a powershell object with convertfrom-json and then compare the objects using your assertion module, everything works great.  Thanks for your help.

**Comment by asears** [comment]
Should Assert module eventually be merged with Pester framework @nohwnd?  Perhaps with a specific alias for json comparison helpers?
