### ISSUE TITLE
"It" block generates 1 test case if "TestCases" parameter is empty array

### ISSUE THREAD

**Issue by maxim-lobanov** [pester/Pester#1682]
## 1. General summary of the issue

`It -TestCases` command doesn't work properly with empty array.

Repro case:
```
Describe "Test Suite" {
    $testCases = @()
    It "Test '<Value>'" -TestCases $testCases {
        $Value | Should -Be 0
    }
}
```

## 2. Describe Your Environment
```
Pester version     : 5.0.3 /Users//.local/share/powershell/Modules/Pester/5.0.3/Pester.psd1
PowerShell version : 7.0.0
OS version         : Unix 19.6.0.0
```

## 3. Expected Behavior

I am expecting Pester to generate 0 testcases and just skip `It`.
In my opinion, these 
```
 It "Test" -TestCases @() {
```
should work the same like this in Pester 4
```
@() | ForEach-Object {
  It "Test" {}
}
```

## 4.Current Behavior
Pester generate 1 test case, try to run it and fail because `Value` is not set:
```
Starting discovery in 1 files.
Discovery finished in 6ms.
[-] Test Suite.Test '<Value>' 9ms (7ms|2ms)
 Expected 0, but got $null.
 at $Value | Should -Be 0, /Users//Documents/Example/1.ps1:25
 at <ScriptBlock>, /Users//Documents/Example/1.ps1:25
```

**Comment by fflaten** [comment]
`It` uses a `any`-function to detect if TestCases has a value to decide between normal test or looping through testcases. `any` considers an empty array the same as a null/not defined, so TestCases is ignored and `It` still creates a single test (else-block).
https://github.com/pester/Pester/blob/9e1f92155c235897ec837157f08e4eff8ddb1d22/src/functions/It.ps1#L138-L143

Should this be changed to `if ($null -ne $TestCases) { New-ParametrizedTest ... }`? Then this would have created zero tests during the foreach-loop in `New-ParametrizedTest`? Any value in running a single test **when TestCases is set,** even though it's empty?

**Comment by fflaten** [comment]
When is the $Testcases set? As long the testcases-value are available during the first run (discovery-phase), then it still might be acceptable to use a foreach-loop in this scenario since null/blank testcases-array might occur. Correct me if I'm wrong @nohwnd. E.g.

```
Describe "Test Suite" {
    $testCases = @(@{Value=1})

    $testCases | % {
        It "Test '<Value>'" -TestCases $_ {
            $Value | Should -Be 0
        }
    }
}
```

If not, then maybe we should consider rewriting the if-test below to `if($null -ne $TestCase)`. That would cause a blank array to be sent to `New-ParameterizedTest` which would create zero tests during the foreach-loop.

https://github.com/pester/Pester/blob/9e1f92155c235897ec837157f08e4eff8ddb1d22/src/functions/It.ps1#L138-L143

Any benefit in always creating a single test (else-block) when a empty array is provided to the TestCases-parameter?

**Comment by maxim-lobanov** [comment]
@fflaten , agree, it should work.

Or even add condition `if ($PSBoundParameters.ContainsKey('TestCases'))` to make sure that
```pwsh
It "Test '<Value>'" -TestCases $null {
```
will produce zero tests too.

@nohwnd , what do you think about this issue?
If any of solutions above looks good to you, I can provide PR with fix.

**Comment by fflaten** [comment]
Maybe exclude `$null` too. We need to decide where the line would go.

At some point it's the test author's fault and a single error/failed test is warranted to help them identify the issue. An empty array might occur for dynamically created testcases, but we could expect the author to always wrap it in an array `@()` when they know it might be empty. Then the `$null`-scenario wouldn't happen. 🙂

**Comment by maxim-lobanov** [comment]
Agree, that makes sense

**Comment by nohwnd** [comment]
I agree. The testcases / ForEach condition should check if the parameter is provided and then generate one for each, in other cases it should not generate anything.
