### ISSUE TITLE
Testing for NOT $null or empty provides wrong error message

### ISSUE THREAD

**Issue by PrzemyslawKlys** [pester/Pester#1685]
## 1. General summary of the issue

Wrong message, test works

```
Describe 'Oh la la' {
    It 'Test Me' {
        $null | Should -not -BeNullOrEmpty
    }
}
```

## 2. Describe Your Environment

Operating System, Pester version, and PowerShell version:

```powershell
Pester version     : 5.0.3 C:\Users\przemyslaw.klys\Documents\WindowsPowerShell\Modules\Pester\5.0.3\Pester.psd1
PowerShell version : 5.1.19041.1
OS version         : Microsoft Windows NT 10.0.19042.0

```

## 3. Expected Behavior

Output error: Expected value to be null or empty

## 4.Current Behavior

Output error: Expected a value, but got $null or empty

## 5. Possible Solution

Just update the message

**Comment by nohwnd** [comment]
Which version of Pester are you using?

**Comment by PrzemyslawKlys** [comment]
I forgot to remove the comment... it was inside the summary.

**Comment by ianwalkeruk** [comment]
Should -Not -BeNullOrEmpty
returning: "Output error: Expected value to be null or empty" would be incorrect behaviour

The current output is logically correct

**Comment by PrzemyslawKlys** [comment]
I am not sure how you read it but:
- BeNUllOrEmpty  means Expected value to be null or empty but got something else
- -NOT -BENullOrEmpty means Expected value not to be null or empty but got something else.

**Comment by nohwnd** [comment]
@PrzemyslawKlys 

-NOT -BENullOrEmpty means Expected value not to be null or empty but got something else. 

Remember that you will get the error when the condition is not met. So you will see the message when the value is `-not -not -NullOrEmpty`, that is you will see it when the value **is** null or empty. 

@ianwalkeruk yeah, the current behavior also looks correct to me. 
```shell
PS C:\Projects\pester> 1 | should -BeNullOrEmpty    

Expected $null or empty, but got 1.
At C:\Projects\pester\bin\Pester.psm1:7154 char:13
+             throw $errorRecord
+             ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (System.Collecti...,System.Object]:Dictionary`2) [], Exception
    + FullyQualifiedErrorId : PesterAssertionFailed

PS C:\Projects\pester> $null | should -not -BeNullOrEmpty

Expected a value, but got $null or empty.
At C:\Projects\pester\bin\Pester.psm1:7154 char:13
+             throw $errorRecord
+             ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (System.Collecti...,System.Object]:Dictionary`2) [], Exception
    + FullyQualifiedErrorId : PesterAssertionFailed

```
