### ISSUE TITLE
Suggestion: The IT function could use a -Continue switch

### ISSUE THREAD

**Issue by arcanecode** [pester/Pester#1690]
## 1. General summary of the issue

Right now, if an IT test fails, it throws an error message and halts the tests. Take this example:

```powershell
Describe -Tags ('Unit', 'Acceptance') "DataFabricator Module Tests"  {

  BeforeAll {
    $module = 'DataFabricator'
    $here = Split-Path -Parent $PSCommandPath

  $functions = ( 'Get-Something',
                         'Invoke-Something',
                         'ConvertTo-Something'
                        ) 

 Context "Checking to see if all functions have a test" {
    It "$module Tests should exist" {
      foreach ($function in $functions)
      {
        "$here\$function.Tests.ps1" | Should -Exist
      }
    }
  }
}
```

Right now, when it finds the first function "Get-Something" does not have a test file for it, it throws the big red error and stops the tests. (FYI each function I write in a module is put in its own PS1 file).

Having a -Continue flag would instruct Pester to show the error, but then keep processing the rest of the tests. This way we could get a complete picture of which ones have tests, and which still need to be written. For example the Invoke-Something may have its tests, but I wouldn't know because the test errors out and stops.

## 2. Describe Your Environment

Pester version     : 5.0.4 C:\Users\arcan\OneDrive\Documents\PowerShell\Modules\Pester\5.0.4\Pester.psd1
PowerShell version : 7.0.3
OS version         : Microsoft Windows NT 10.0.19041.0

## 3. Expected Behavior (when a -Continue switch is added)

Keep executing the tests

## 4. Current Behavior

Immediately errors when a test fails.

## 5. Possible Solution

Addition of a -Continue flag as described. (Something like this may exist, but I couldn't find it in the docs.)

## 6. Context

Having this ability would give me a list of which project times still need to be completed, whether they are functions I need to author, test files I need to create, etc. 

In previous versions of Pester this was a useful tool for new module development, as I could easily see what work had been completed, and what still remained.

**Comment by nohwnd** [comment]
To do this, you can either use -ForEach in 5.1.0-beta1, or use the ability to continue on Should failure, by -ErrorAction Continue (that is there since 5.0.0). 

I would not put foreach in the It block, that's a pretty bad style. 

`Split-Path -Parent $PSCommandPath` this is just a hard way to get `$PSScriptRoot` btw.

**Comment by nohwnd** [comment]
https://github.com/pester/pester#collect-all-should-failures

**Comment by arcanecode** [comment]
I didn't realize erroraction worked like that on should, thanks. 

I saw a note somewhere that said we should use 
PS command path, but it didn't say why (that I recall). But hey if script root will work ok in Pester 5, I'm all for it. 

I agree, adding a foreach in an It sucks. Sucks so bad my fingers cramped up as I typed, sparks started flying from my keyboard, and my wife came in my office, gave me a dope slap to the back of my head and walked out of the room shaking her head in disgust. 

But I don't know of another way to do it using the current release version of 5.0.x. 

Looking forward to 5.1. Maybe then my wife will let me sleep in the house again, and not in the chicken coop out back.

**Comment by nohwnd** [comment]
Maybe you saw it here? There I mention $PSCommandPath as well as $PSSCriptRoot. What you should avoid is $MyInvocation.MyCommand.Path, that won't work.

 https://jakubjares.com/2020/04/11/pester5-importing-ps-files/

**Comment by nohwnd** [comment]
> I agree, adding a foreach in an It sucks. Sucks so bad my fingers cramped up as I typed, sparks started flying from my keyboard, and my wife came in my office, gave me a dope slap to the back of my head and walked out of the room shaking her head in disgust.

😁 😁 😁
