### ISSUE TITLE
Change the name of BUILD.md to CONTRIBUTING.md

### ISSUE THREAD

**Issue by johlju** [pester/Pester#1692]
## 1. General summary of the issue

Suggest changing the name of BUILD.md to CONTRIBUTING.md to be more discoverable for contributors. I was looking for a CONTRIBUTING.md when trying to figure out how to build the project, I figured it out before I found the BUILD.md file. *Also GitHub automatically provide links to the CONTRIBUTING.md in certain places if it exist.*

We should also add that to be able to build the .dll's there is a need to run `.\build.ps1 -Clean`.

Happy to contribute this if it is acceptable.

**Comment by nohwnd** [comment]
I support this, also running the build.ps1 becomes less annoying, I will no longer always open build.md by accident.
