### ISSUE TITLE
Is this a mock bug?

### ISSUE THREAD

**Issue by hansEricG** [pester/Pester#1696]
I discovered a (to me) strange behavior of the Mock function. It might not be a bug, but I figured if I could provide a minimal example it might be worth reporting.

```
BeforeAll {
    function a () { "some output" }
    
    function b () { a }
}

Describe "Is this a bug?" {

    It 'works for mock with empty scriptblock' {
        Mock a { }
        b | Should -Invoke a
    }

    It 'does not work if mock has a non-empty scriptblock' {
        Mock a { "mock" }
        b | Should -Invoke a
    }
}

```
Why does this work in the first It clause, but not in the second? The only difference is the mock there has a non-empty scriptclause. Or am I missing something?
 
The second test case fails with the following message:

```
[-] Is this a bug?.does not work if mock has a non-empty scriptblock 11ms (10ms|1ms)
 Expected Mock to be called at least 1 times but was called 0 times
 at b | Should -Invoke a, D:\Powershell\InvokeCountBug.Tests.ps1:16
 at <ScriptBlock>, D:\Powershell\InvokeCountBug.Tests.ps1:16
Tests completed in 185ms
Tests Passed: 1, Failed: 1, Skipped: 0 NotRun: 0
```

I'm using Pester 5.0.4

**Comment by nohwnd** [comment]
That definitely looks like a bug.

**Comment by fflaten** [comment]
I'd call this a user error and unfortunate example. `Should -Invoke` only accepts one value from pipeline `$ActualValue` and it would override the `CommandName`-parameter (`a` in the failing test). Any non-string value in the pipeline throws an error, but your mock outputs a string which coincidental is a valid command-name (`Mock`), so the error doesn't help you much.

The first sample works because it doesn't output any string or other object (would throw).

```
# This is valid
Should -Invoke "a"
"a" | Should -Invoke

# This should be avoided.
# Pipeline value "functionB" ($ActualValue) overrides "functionA" ($CommandName parameter)
"functionB" | Should -Invoke "functionA"
```

Try:
```
It 'does not work if mock has a non-empty scriptblock' {
    Mock a { "MyMockAOutput" }
    b | Should -Invoke a
}

[-] Is this a bug?.does not work if mock has a non-empty scriptblock 17ms (16ms|1ms)
CommandNotFoundException: Could not find Command MyMockAOutput

It 'does not work if mock has a non-empty scriptblock' {
    Mock a { $PSVersionTable }
    b | Should -Invoke a
}

[-] Is this a bug?.does not work if mock has a non-empty scriptblock 16ms (15ms|2ms)
 RuntimeException: Should -Invoke does not take pipeline input or ActualValue.
```

The only bug here would be the fact that it accepts a string as pipeline-input considering the error message for non-string input, but that may be for backward compatibility. The last error should probably mention the allowed CommandName-string value or get thrown very time there is pipeline input 🙂

**Comment by hansEricG** [comment]
Thank you! That makes so much sense. For some reason, I was operating under the false assumption that Should should always be piped to (probably because I've only seen such examples). But that makes no sense in this case, as you've explained.

These slightly altered tests (no pipes) produce green results - as expected.

```
    It 'works for mock with empty scriptblock' {
        Mock a { }
        b 
        Should -Invoke a
    }

    It 'does not work if mock has a non-empty scriptblock' {
        Mock a { "mock" }
        b 
        Should -Invoke a
    }
```

Sorry for taking your time.

**Comment by fflaten** [comment]
Nothing to be sorry about. Either you've discovered a broken feature or we've found a sub-optimal user experience with Should Invoke that should be looked into. Win-win 🙂

**Comment by nohwnd** [comment]
> For some reason, I was operating under the false assumption that Should should always be piped to (probably because I've only seen such examples and it created a false pattern in my brain). But that makes no sense in this case, as you've explained.

Don't worry about that, I also did not see anything wrong with those tests. And I wrote that code 😁 

@fflaten great analysis, 👍👍👍 it should not accept any input imho, to avoid this behavior. Adding this to 5.1 milestone. If you want to PR please do.
