### ISSUE TITLE
Accessing private functions in a module not working when using events

### ISSUE THREAD

**Issue by rdavidian** [pester/Pester#1699]
## 1. General summary of the issue

I'm having issues accessing a private function in the module I'm testing using Pester.  Specifically my test will fail if I try to access the private function via a public function which calls the private function in an event.  I created a simple example.

```
#Requires -Modules Pester -Version 5.0.4

Describe "Test functions with no events" {
    New-Module -Name TestModule {
        function InternalFunction { 'I am InternalFunction' }
        function PublicFunction   { InternalFunction }
        Export-ModuleMember -Function PublicFunction
    } | Import-Module -Force

    InModuleScope TestModule {
        It 'Test PublicFunction' {
            PublicFunction | Should -Be 'I am InternalFunction'
        }

        It 'Test InternalFunction' {
            InternalFunction | Should -Be 'I am InternalFunction'
        }
    }

    Remove-Module TestModule -Force
}

Describe "Test functions with events" {
    New-Module -Name TestModule {
        Register-EngineEvent -SourceIdentifier 'OnFunctionStarted' -Action { 
            InternalFunction;
        } | Out-Null

        function InternalFunction { 
            'I am InternalFunction' 
        }
        function PublicFunction   { 
            New-Event -SourceIdentifier 'OnFunctionStarted' -Sender 'Test' | Out-Null
         }
        Export-ModuleMember -Function PublicFunction
    } | Import-Module -Force

    InModuleScope TestModule {
        It "Test PublicFunction" {
            PublicFunction -Verbose | Should -Be 'I am InternalFunction'
        }

        It "Test InternalFunction" {
            InternalFunction -Verbose | Should -Be 'I am InternalFunction'
        }
    }

    Remove-Module TestModule -Force
}
```

```
-- Output
Starting discovery in 1 files.
Discovery finished in 3.88s.
**[-] Test functions with events.Test PublicFunction 1.42s (1.29s|124ms)
 Expected 'I am InternalFunction', but got $null.**
 at PublicFunction -Verbose | Should -Be 'I am InternalFunction', C:\Projects\VPM\Dev\Trunk\Database\Utility\PowerShell\VPM PowerShell Modules\FileIO_Helper\Tests.ps1:40
 at <ScriptBlock>, C:\Projects\VPM\Dev\Trunk\Database\Utility\PowerShell\VPM PowerShell Modules\FileIO_Helper\Tests.ps1:40
Tests completed in 20.69s
Tests Passed: 3, Failed: 1, Skipped: 0 NotRun: 0
```

## 2. Describe Your Environment

Pester version     : 5.0.4 C:\Program Files\WindowsPowerShell\Modules\Pester\5.0.4\Pester.psd1
PowerShell version : 5.1.18362.752
OS version         : Microsoft Windows NT 10.0.18362.0

## 3. Expected Behavior

I was expecting an indirect call to the private function to be accessible when using events

## 4.Current Behavior

An indirect call to the private function is not accessible from an event

## 5. Possible Solution

Not sure

## 6. Context

I want to be able to test modules with private functions in them.  Sometimes those private functions are called indirectly via events.  In that case, it appears that Pester can handle them correctly.

**Comment by rdavidian** [comment]
This issue isn't Pester specific.  It appears to be a restriction with calling private functions within an event's -Action scriptblock

**Comment by nohwnd** [comment]
The event will run in a job and that job does not have access to your module internals, even though you pass it a scriptblock that is bound to your modules internal session state. 

if you run `Get-Job -State Failed | Select Name, State, Error` you will see that it fails with `The term 'InternalFunction' is not recognized as the name of a cmdlet...`, because your -Action does not have access to the module internal scope. You could import the module and use this trick `-Action {  & (Get-Module TestModule) { InternalFunction } }`, but don't expect the internal state (e.g. data you share via script scoped variables) of the module to be present, it is in a different powershell session entirely.

**Comment by rdavidian** [comment]
Thanks for looking at my issue.  I did see that trick  -Action { & (Get-Module TestModule) { InternalFunction } } online but your correct about the function being in its own session.  I'm gonna just expose the function as public to get around the issue.  This is not an issue specific to Pester.
