### ISSUE TITLE
TestCases within BeforeAll don't work

### ISSUE THREAD

**Issue by DarkLite1** [pester/Pester#1705]
## 1. General summary of the issue

This works fine:
```powershell
Describe 'test' {
     $TestCases = @(
         @{
             Name  = 'banana'
             Type  = 'fruit'
             Taste = 'good'
         }
         @{
             Name  = 'kiwi'
             Type  = 'fruit'
             Taste = 'good'
         }
    )
    
    Context 'Filter' {
        It '<Name>' -TestCases $TestCases {
            $Type | Should -Be 'fruit'
        }
    }
    Context 'Property' {
        It '<Name>' -TestCases $TestCases {
            $Taste | Should -Be 'good'
        }
    }
}
```

This code does not work:
```powershell
Describe 'test' {
    BeforeAll {
        $TestCases = @(
            @{
                Name  = 'banana'
                Type  = 'fruit'
                Taste = 'good'
            }
            @{
                Name  = 'kiwi'
                Type  = 'fruit'
                Taste = 'good'
            }
        )
    }
    
    Context 'Filter' {
        It '<Name>' -TestCases $TestCases {
            $Type | Should -Be 'fruit'
        }
    }
    Context 'Property' {
        It '<Name>' -TestCases $TestCases {
            $Taste | Should -Be 'good'
        }
    }
}
```

## 2. Describe Your Environment

```powershell
Pester version     : 5.0.4 C:\Program Files\WindowsPowerShell\Modules\Pester\5.0.4\Pester.psd1
PowerShell version : 5.1.14393.3866
OS version         : Microsoft Windows NT 10.0.14393.0
```
## 3. Expected Behavior
Given that all code in the newe Pester (5) needs to be within a clause, it seemed logical to use the `BeforeAll` clause for this.

## 4.Current Behavior

The variables in `$testCases` are not expanded within the `it` clause.

**Comment by nohwnd** [comment]
BeforeAll will run after discovery. The testcases are defined during discovery, this won't work.

**Comment by DarkLite1** [comment]
That's a shame. I sometimes find myself in a situation like the code below. This is due to the same way Pester handles the discovery and execution like you explained. Is there a workaround for using the variable within the testcases? In all other places the variable is available, within the `it` test clauses but not within the `testCases`.

 BeforeAll {
    $myType = 'fruit'
}

```powershell
Describe 'test' {
    BeforeAll {
        $TestCases = @(
            @{
                Name  = 'banana'
                Type  = $myType
                Taste = 'good'
            }
            @{
                Name  = 'kiwi'
                Type  = 'fruit'
                Taste = 'good'
            }
        )
    }
    
    Context 'Filter' {
        It '<Name>' -TestCases $TestCases {
            $Type | Should -Be 'fruit'
        }
    }
    Context 'Property' {
        It '<Name>' -TestCases $TestCases {
            $Taste | Should -Be 'good'
        }
    }
}
```

**Comment by nohwnd** [comment]
You can't mix them like this, unfortunately. You would need to move the code to run before discovery into be body of the script or use `BeforeDiscovery` block that was introduced in 5.1.0-beta1

**Comment by DarkLite1** [comment]
Indeed, I believe we need to use the [BeforeDiscovery](https://github.com/pester/Pester/releases) once it becomes available in the PowerShell Gallery. Thanks for the help.

**Comment by nohwnd** [comment]
It is in gallery, 5.1.0-beta1 or 5.1.0-beta2 :)
