### ISSUE TITLE
Why is a mock not found?

### ISSUE THREAD

**Issue by DarkLite1** [pester/Pester#1710]
## 1. General summary of the issue

In the code below the mocks are defined within the `BeforeAll` clause. When asserting if all verifiable mocks have been called, this works flawlessly. See the `Get-Process` examples. However, when trying to assert if `Get-Service` was called, which is not a verifiable mock, it fails. 

Thank you for clarifying why this fails. 

```powershell
# Process.ps1
$svcHostProcesses = Get-Process -Name 'svchost'
$kiwiProcesses = Get-Process -Name 'kiwi'
$timeService = Get-Service -Name 'W32Time'
```

```powershell
# Process.Tests.ps1
#Requires -Modules Pester
#Requires -Version 5.1

BeforeAll {
    $testScript = $PSCommandPath.Replace('.Tests.ps1', '.ps1')
    
    Mock Get-Process
    Mock Get-Process -Verifiable -ParameterFilter {
        ($Name -eq "svchost") 
    } -MockWith {
        [PSCustomObject]@{Name = 'svchost' }
    }
    Mock Get-Process -Verifiable -ParameterFilter {
        ($Name -eq "kiwi") 
    } -MockWith {
        [PSCustomObject]@{Name = 'kiwi' }
    }
    Mock Get-Service -MockWith {
        [PSCustomObject]@{Name = 'W32Time' }
    }
}

Describe 'the script should' {
    BeforeAll {
        . $testScript @testParams
    }
    It 'test all process getters' {
        Should -InvokeVerifiable
    }
    It 'test service getter > FAIL' {
        Should -Invoke Get-Service -Exactly -Times 1 
    } -Tag 'test'
    It 'test service getter' {
        Mock Get-Service 

        . $testScript @testParams 

        Should -Invoke Get-Service -Exactly -Times 1
    } -Tag 'test'
}
```
![image](https://user-images.githubusercontent.com/10828570/95655369-129eb680-0b07-11eb-8544-6a5bdbb80c47.png)

## 2. Describe Your Environment

```powershell
Pester version     : 5.0.4 C:\Program Files\WindowsPowerShell\Modules\Pester\5.0.4\Pester.psd1
PowerShell version : 5.1.14393.3866
OS version         : Microsoft Windows NT 10.0.14393.0
```
## 3. Expected Behavior

Given that all mocks are defined before executing the script we would expect this mock to be available for assertion. 

## 4.Current Behavior

The test fails without redefining the mock within the `it` clause.

**Comment by fflaten** [comment]
Pester 5 counts mock usage in it's local scope (test-block) by default.
See https://github.com/pester/Pester#counting-mocks-depends-on-placement

Try using `-Scope Describe` to override it:
```
It 'test service getter > FAIL' {
    Should -Invoke Get-Service -Scope Describe -Exactly -Times 1 
} -Tag 'test'
```

**Comment by DarkLite1** [comment]
Ow yeah, you are 100% correct. Totally forgot about the `-scope` argument. Thanks for clarifying 👍
