### ISSUE TITLE
Legacy syntax shows Parameter Binding errors, but does not fail enough tests

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#1714]
I have a follow-up question, if I may. I have left my deliberate mistake to test in place (old syntax) and am now revisiting my tests and working on them more.

```
    It "should contain Write-Verbose blocks" {
      "$($_.FullName)" | Should FileContentMatch "Write-Verbose"
    }
```

I see a lot of these:
```
Should : The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of 
the parameters that take pipeline input.
At \\---------\Software\Code\Personal\TeamsFunctions\TeamsFunctions.Tests.ps1:97 char:26
+       "$($_.FullName)" | Should FileContentMatch "Write-Verbose"
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (\\conglomerator...ctionStatus.ps1:String) [Should], ParameterBindingException
    + FullyQualifiedErrorId : InputObjectNotBound,Should
```

yet:

```
Tests completed in 4.57s
Tests Passed: 291, Failed: 1, Skipped: 0 NotRun: 0
```

If it doesn't find the line valid, the test should fail, yes?

Thanks,
David

PS:
Running it with the syntax corrected, I get `Tests Passed: 280, Failed: 12, Skipped: 0 NotRun: 0` (which is expected... :))

_Originally posted by @DEberhardt in https://github.com/pester/Pester/issues/1703#issuecomment-706694491_

**Comment by nohwnd** [comment]
@DEberhardt Do you have some simple repro that I can use to see the problem and fix this issue?

**Comment by DEberhardt** [comment]
Basically the above. With new notation it works fine. Without the "-" it errors, but the test itself is marked as Passed. I have about 72 files I am testing, so I was expecting 73 to fail.

**Comment by nohwnd** [comment]
I can't repro this on the beta2, are you sure you are using it? I see this: 

```
Starting discovery in 1 files.
Discovery finished in 221ms.
[-] a.should contain Write-Verbose blocks 113ms (80ms|34ms)
 RuntimeException: Legacy Should syntax (without dashes) is not supported in Pester 5. Please refer to migration guide at: https://pester.dev/docs/migrations/v3-to-v4
 RuntimeException: Legacy Should syntax (without dashes) is not supported in Pester 5. Please refer to migration guide at: https://pester.dev/docs/migrations/v3-to-v4
 ParameterBindingException: Cannot retrieve the dynamic parameters for the cmdlet. Legacy Should syntax (without dashes) is not supported in Pester 5. Please refer to migration guide at: https://pester.dev/docs/migrations/v3-to-v4
 at <ScriptBlock>, C:\Users\jajares\Desktop\legacy.tests.ps1:3
Tests completed in 915ms
Tests Passed: 0, Failed: 1, Skipped: 0 NotRun: 0
```

**Comment by DEberhardt** [comment]
sorry for the delay, have taken a bit off to decompress - being cooped up for over six months takes its toll and my day job now requires me to work the odd Saturday as well.
Will be able to test this within the next 7 days, hopefully, we can put this to rest then :)

**Comment by nohwnd** [comment]
@DEberhardt ping on this, it's been 7 days 😁

**Comment by DEberhardt** [comment]
Thanks for the reminder. Had finally some time to devote to further testing :)
I reinstalled the most recent v5.1.0 (pre-release) - The module is not telling me which prerelease version it is, so I have removed all and reinstalled. 

```
    It "'$($_.BaseName)' should contain Write-Verbose blocks" {
      "$($_.FullName)" | Should -FileContentMatch "Write-Verbose"
    }
```
Result: `Tests Passed: 779, Failed: 0, Skipped: 0 NotRun: 0`

-------------------
Removing the Dash (i.E. Legacy syntax):

```
    It "'$($_.BaseName)' should contain Write-Verbose blocks" {
      "$($_.FullName)" | Should FileContentMatch "Write-Verbose"
    }
```

Result: `Tests Passed: 712, Failed: 67, Skipped: 0 NotRun: 0`

```
[-] TeamsFunctions Module Tests.Testing Module PUBLIC Functions.'Test-TeamsUserVoiceConfig' should contain Write-Verbose blocks 2ms (1ms|1ms)
 RuntimeException: Legacy Should syntax (without dashes) is not supported in Pester 5. Please refer to migration guide at: https://pester.dev/docs/migrations/v3-to-v4
 RuntimeException: Legacy Should syntax (without dashes) is not supported in Pester 5. Please refer to migration guide at: https://pester.dev/docs/migrations/v3-to-v4
 ParameterBindingException: Cannot retrieve the dynamic parameters for the cmdlet. Legacy Should syntax (without dashes) is not supported in Pester 5. Please refer to migration guide at: https://pester.dev/docs/migrations/v3-to-v4
 at <ScriptBlock>, TeamsFunctions.Tests.ps1:111
```

Is it deliberate that the Exception is thrown twice?

No false-positives anymore, cheers! :)

**Comment by DEberhardt** [comment]
I think this one can be closed (unless you want to keep it open to investigate the duplicated output)

**Comment by nohwnd** [comment]
I looked at that duplicated output and it's imho coming from dynamic parameter binding, which I don't know much about. The original author of this code knew a lot about it, but the code also had 3 severe bugs already. So I am okay with the message being doubled. 😁
