### ISSUE TITLE
Pester no longer seems to allow dot sourcing (at test level or in InModuleScope)

### ISSUE THREAD

**Issue by LethiferousMoose** [pester/Pester#1719]
## 1. General summary of the issue
I recently upgraded the latest version of PowerShell and Pester and now a vast majority of my Pester tests are failing. I had test scripts that contained bootstrap functions that I was dot sourcing inside of InModuleScope, now when the tests run I get CommandNotFoundExceptions.

ConfigFunctions.ps1
```powershell
function Remove-TestConfigurations {
}
```

Some.Test.ps1
```powershell
    InModuleScope AModule {
        . $PSScriptRoot/../ConfigFunctions.ps1

            AfterAll {
                Remove-TestConfigurations
            }
}
```

I've currently worked around this by moving all my bootstrapper functions to a module and updating the the PSModulePath before each run. It also does not seem that dot sourcing works at all even at the top of the test file, cause I have failures for this as well:

TestFunctions.ps1
```powershell
function PurgeTestData {
}
```

```powershell
. $PSScriptRoot/assets/TestFunctions.ps1
```

```powershell
Describe 'Some-Describe' {
    AfterEach {
        PurgeTestData
    }
}
```

This one I do not have a work around for, as these vary per module tests and are stores in an assets folder for each module unit test. This stuff has quite literally broken my entire test suite and I don't have workarounds for everything.

## 2. Describe Your Environment
Pester version     : 5.0.4 C:\Users\1020216\Documents\PowerShell\Modules\Pester\5.0.4\Pester.psd1
PowerShell version : 7.1.0-rc.1
OS version         : Microsoft Windows NT 10.0.18363.0

## 3. Expected Behavior
The functions should be detected when the test blocks execute.

## 4.Current Behavior
Functions in scripts are not found during test runs.

**Comment by LethiferousMoose** [comment]
This seems related to #1461

**Comment by fflaten** [comment]
Can you try again while placing the dot-sourcing line inside a BeforeAll-block?

Remember that all code must be place in a block in Pester v5 (see README). Code outside a block will usually only be executed during the first run which only discovers the tests to run, not later when the tests are actually executed. Haven't tried with `InModuleScope`, but I would expect the same requirements.

```
InModuleScope AModule {
    BeforeAll {
        . $PSScriptRoot/../ConfigFunctions.ps1
    }

    It "My Test" {
        #Your test depending on ConfigFunctions.ps1
    }
    
    AfterAll {
        Remove-TestConfigurations
    }
}
```

**Comment by LethiferousMoose** [comment]
Yes, I found that, that does seem to fix the issue. I will close this.
