### ISSUE TITLE
Sharing variables between BeforeAll and It blocks

### ISSUE THREAD

**Issue by LethiferousMoose** [pester/Pester#1720]
## 1. General summary of the issue
In previous versions of Pester, I was able to define variables in the BeforeAll block and those variables were then referenceable in Describe/Context/It blocks.

```powershell
Describe 'Write-Logger' {
    BeforeAll {
        [string] $testVariable = "test"
    }

   It 'SomeTest' {
        Write-Host $testVariable
   }
}
```

Whether this was intentional or not, all my tests are failing now, so I need a workaround.

## 2. Describe Your Environment
Pester version     : 5.0.4 C:\Users\1020216\Documents\PowerShell\Modules\Pester\5.0.4\Pester.psd1
PowerShell version : 7.1.0-rc.1
OS version         : Microsoft Windows NT 10.0.18363.0

## 3. Expected Behavior
Test variables should be able to be defined and references in the same test scope.

## 4.Current Behavior
All variables are now undefined.

**Comment by fflaten** [comment]
Can't reproduce. Provided sample works as intended in Win10 2004 (19041) with same PowerShell 7.1-rc1 and Pester 5.0.4. Are you sure your repro sample is similar to your failing tests?

**Comment by LethiferousMoose** [comment]
I'll need to some more digging, maybe something else is going on. I can't replicate it in a dummy test.

**Comment by LethiferousMoose** [comment]
I'll need to some more digging, maybe something else is going on. I can't replicate it in a dummy test.
