### ISSUE TITLE
Print out the filter that is being used

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#1721]
Diagnostic output does not print the actual filter that is being used, instead it prints just the evaluation. And what is being rejected and included.

**Comment by fflaten** [comment]
So basically a summary of active filters?  Something like this?

> Discovery: Starting test discovery in 2 test containers. 
> 
> Starting discovery in 2 files.
> Discovery: Discovering tests in C:\Users\Frode\Git\Pester\demo.ps1 
> Discovering in C:\Users\Frode\Git\Pester\demo.ps1.
> Found 3 tests. 16ms
> Discovery: Found 3 tests in 23 ms 
> Discovery: Discovering tests in C:\Users\Frode\Git\Pester\demo.tests.ps1 
> Discovering in C:\Users\Frode\Git\Pester\demo.tests.ps1.
> Found 8 tests. 46ms
> Discovery: Found 8 tests in 49 ms 
> Discovery: Processing discovery result objects, to set root, parents, filters etc. 
> **Discovery: Using filters: 
> Discovery: Filter 'Tag' set to ('Function'). 
> Discovery: Filter 'ExcludeTag' set to ('Ignore', 'Stuff'). 
> Discovery: Filter 'Line' set to ('C:\tests\file1.Tests.ps1:37', 'C:\tests\file12.Tests.ps1:371').** 
> Filter: ('Set-BuildRunToCI' Unit Tests) Block will be included in the run, because there were no include filters, and will let its children to determine whether or not it should run. 
> Filter: ('Set-BuildRunToCI' Unit Tests.Should mock Log-Debug) Test will be included in the run, because there were no include filters so all tests are included unless they match exclude rule. 

Could be placed before the call to `PostProcess-DiscoveredBlock` to avoid duplicate output. Filters won't change during a single `Invoke-Pester` session, right? E.g. replacing

https://github.com/pester/Pester/blob/8d555269cfcd8e3aee13d1efb10f962afc922f96/src/Pester.Runtime.psm1#L920-L922

with:
```
if ($PesterPreference.Debug.WriteDebugMessages.Value) {
    Write-PesterDebugMessage -Scope Discovery "Processing discovery result objects, to set root, parents, filters etc."

    $activeFilters = $PesterPreference.Filter.psobject.Properties | Where-Object { $_.Value.IsOriginalValue() -eq $false }
    if($null -ne $activeFilters) {
        Write-PesterDebugMessage -Scope Discovery "Using filters:"
        foreach ($filter in $activeFilters) {
            # Assuming only StringArrayOption filter-types. Might break in the future.
            Write-PesterDebugMessage -Scope Discovery "Filter '$($filter.Name)' set to ('$($filter.Value.Value -join "', '")')."
        }
    }
}
```

**Comment by nohwnd** [comment]
Yeah. :)

**Comment by fflaten** [comment]
Want me to submit a PR for it? Anything you notice immediately that should be changed? Maybe "Filter" as the debug message scope?

**Comment by nohwnd** [comment]
Yes please PR it. I was thinking about that as well. IF this is logging then yes, please make the log source Filter, but I would also print it to the screen in the Detailed output as part of Discovery. Not needed to be part of this PR.

**Comment by fflaten** [comment]
Well there's no need to duplicate it, so might as well do it now by changing it to `Write-Host` during detailed or diagnostic. Since most host-output is placed in `Get-WriteScreenPlugin`, I'd guess this belongs there too. Need some tips on step-placement.

Could use Start-step, but it feels weird to list filters early considering "found 3 tests" after is the count before filtering and the "processing discovery result .." diag-output. Might just be me 🙂.

> Discovery: Starting test discovery in 2 test containers. 
> 
> Starting discovery in 2 files.
> **Filter 'Tag' set to ('Function').
> Filter 'ExcludeTag' set to ('Ignore', 'Stuff').
> Filter 'Line' set to ('C:\tests\file1.Tests.ps1:37', 'C:\tests\file12.Tests.ps1:371').**
> Discovery: Discovering tests in C:\Users\Frode\Git\Pester\demo.ps1 
> Discovering in C:\Users\Frode\Git\Pester\demo.ps1.
> Found 3 tests. 17ms
> Discovery: Found 3 tests in 21 ms 
> **Discovery: Processing discovery result objects, to set root, parents, filters etc.** 
> Filter: ('Set-BuildRunToCI' Unit Tests) There is 'Ignore, Stuff' exclude tag filter. 

Or we could introduce a new `DiscoveryPostProcessStart`-step that's called after these lines to keep it like the post above.
https://github.com/pester/Pester/blob/8d555269cfcd8e3aee13d1efb10f962afc922f96/src/Pester.Runtime.psm1#L920-L922

Thoughts?

**Comment by nohwnd** [comment]
I think that output is okay for a start. Please do it this way.

**Comment by fflaten** [comment]
To confirm, using the Start-step?

**Comment by nohwnd** [comment]
I don't know how you did it in the output shown above :) That way.
