### ISSUE TITLE
New-Fixture generates code that isn't compatible with Pester 5?

### ISSUE THREAD

**Issue by hansEricG** [pester/Pester#1723]
I don't know if this is a problem (or already solved), but I found that New-Fixture is generating code that I believe is not compatible with the 5.x version of Pester?

```
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path) -replace '\.Tests\.', '.'
. "$here\$sut"

Describe "SomeFunction" {
    It "does something useful" {
        $true | Should Be $false
    }
}
```

Firstly, I guess the setup code should be in a BeforeAll block, and not use $MyInvocation. Secondly, the test fails since it's using legacy syntax on Should.

## 2. Describe Your Environment

Pester 5.0.3

## 3. Expected Behavior

I guess it should produce something similar to:

```
BeforeAll {
    . $PSCommandPath.Replace('.Tests.ps1', '.ps1')
}

Describe "SomeFunction" {
    It "does something useful" {
        $true | Should -Be $false
    }
}
```

**Comment by fflaten** [comment]
Simple answer: `New-Fixture` is not implemented in Pester v5 module, so the cmdlet you're running belongs to Pester 3 or 4 and the result is compatible with that syntax.
```
PS> Get-Command New-Fixture | % Module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     4.10.1     Pester                              {Add-AssertionOperator, AfterAll, AfterEach, AfterEachFeat...
```

Related question: Maybe we should implement an updated version in Pester v5? Don't see it as part of the Breaking Changes chapter in README, so most likely forgotten/delayed and not deprecated. 🙂
