### ISSUE TITLE
Access Mock Execution details outside of the module

### ISSUE THREAD

**Issue by simonsabin** [pester/Pester#1724]
Writing Asserts for MockCalled can be tricky when you aren't getting the right number of executions
1. you know what should be being called and it isn't matching because of some implicit type conversion/ToString() that isn't obvious
2. you are passing an object and not really sure what to put in the expression
3. you don't really know whats being called and its deep in some code and you'd like to know what parameters are being used

It would be great to expose the MockTable to allow for interrogation, and potentially in debug being able to validate an expression. 
One can access the MockTable by stepping into the code, but accessing it in a reliable way that matches the Assert function is hard.

Potential Solution a new function that returns the Mock Execution history

Get-MockCalled -Command -Scope -ParameterFilter -ModuleName

That outputs the MockTable in a format that matches what you would use for Assert-MockCalled

**Comment by nohwnd** [comment]
You are right, and that is why I added the Diagnostic output in v5 that shows what is being executed, with which values, and how the current mock to call was determined: https://youtu.be/mTfUO00hWSc?t=649

Further v5 also allows you to debug the mocks using breakpoints. And the Diagnostic output could (should) be extended to show the results of Should -Invoke and how it determines whether or not the assertion passes. 

The problem with your solution is that you would need to add function call and write-host to debug a mock, and then remember to remove that code once you are done debugging. You would also have to match the parameters of the mock perfectly.

I don't have much interest in adding this to v4, but you can start by implementing it outside of Pester and use this trick to reach into the Pester state to grab the mockTable variable: `& (Get-Module Pester) { $mockTable | Out-String | Write-Host }`

```powershell
Describe "a" { 
    It "b" { 
        function f () {}
        Mock f { "mock" }
        & (Get-Module Pester) { 
            $mockTable | Out-String | Write-Host 
        } 
    } 
}
```
```shell
Describing a

Name                           Value
----                           -----
||f                            {DynamicParamScriptBlock, OriginalMetadata, SessionState, Blocks…}


  [+] b 216ms
```

But personally I would much rather see this added to v5 as part of the Should -Invoke logging.

**Comment by simonsabin** [comment]
To add a bit on this for anyone looking for help. 
The debug output is very helpful in showing the evaluation of a parameter filter for a `Should -Invoke` . you can then use that to work out your parameterFilter
