### ISSUE TITLE
Gherkin...

### ISSUE THREAD

**Issue by Jaykul** [pester/Pester#173]
Would you guys like gherkin support?
I've got this working on top of pester:

http://poshcode.com/paste/445/

**Disclaimer 1:** I just started playing with the idea yesterday.

**Disclaimer 2:** It uses the official gherking parser -- which depends on a large pile of DLLs (the IKVM package)/

I have obviously not accounted for everything yet , and I'm still trying to figure out your best practices for loading/unloading modules etc, but so far it works for me ;-)

**Comment by Jaykul** [comment]
I've rebased my Gherkin tree (and moved it, just because):
https://github.com/Jaykul/Pester/tree/Syntax/Gherkin

I had to make quite a few fixes to make it work on 3.3.8 

For the record, my output functions are no longer compatible with Pester's because of your changes to have everything go through `Write-Screen` -- originally I had moved ALL Write-Host calls in all of Pester into `Functions\Output.ps1` -- in this branch, I've left the Pester code alone (so it's still calling it's own functions), and I've only used the new functions in the Gherkin side (to avoid throwing out all of someone's refactoring).  

The new Write-Screen is too limiting for me (and frankly, seems like an unnecessary abstraction).  Specifically, removing the ability to write more than one color on a line means I can't lowlight the timestamps, and I prefer a few more color options because I have at least one extra level of headline output.

I need to add a line to read my color configuration from a `psd1` configuration file (like what I'm doing with strings), and I think that's what Pester needs too (regardless of whether we re-integrate the output functions or not).

**Comment by KirkMunro** [comment]
Oh! I have a really nice solution to the Write-Screen limitation that I've
been working on...I'll see if I can polish that up and ship it, because it
would be ideal for this!

--
*Kirk Munro *
Poshoholic, Microsoft MVP
Blog <http://poshoholic.com/> | Twitter <http://twitter.com/poshoholic> |
LinkedIn <http://ca.linkedin.com/in/kirkmunro> | Facebook
<http://www.facebook.com/#%21/kirk.munro>

Need a PowerShell SME for a project at work? Contact me
<http://poshoholic.com/contact-me/>!

**Comment by dlwyatt** [comment]
Write-Screen's main responsibility is to encapsulate the -Quiet switch to control calls to Write-Host.  We can refactor out the other color logic into a separate function, which can be used by Invoke-Gherkin or Invoke-Pester as needed.

**Comment by dlwyatt** [comment]
Also, don't worry about doing too much of that in your fork.  We've already merged Gherkin (minus these output-related merge conflicts) in the LanguageDecoupling branch.  That's a bit of a misnomer now that I've sort of given up on that decoupling idea for the moment, but it's still where we're doing the work of getting this ready to ship.

**Comment by Jaykul** [comment]
Yeah, I just needed Gherkin working (on 3.3.8), so I could do some other work :grinning: 

You had also mentioned the new switches, and so I added those -- obviously `-quiet` isn't actually implemented, since I haven't reconciled Write-Screen, but I figured too much had changed in the output functions within master and LanguageDecoupling to be able to merge them back together, I guess I was assuming it was a dead end.

I could have a look at doing it the other way (merge master to LanguageDecoupling) if you think it's worth it -- but one way or another, we definitely want to have only one set of output functions (I currently have two because of Write-Screen).

**Comment by dlwyatt** [comment]
I haven't done work on LanguageDecoupling in a couple of months, so it's already due for another big merge from master.  Will do that soon, and then figure out what to do with the output code.

In a perfect world, we'd get @nohwnd 's "color scheme" functionality working with Invoke-Gherkin as well (and add your nice multi-color lines to Invoke-Pester while we're at it), but I suppose it's not a huge problem if they look different.

**Comment by Jaykul** [comment]
OK. (just for the record). 
I owe you some tests for the invoke-gherkin function.

**Comment by Xoph** [comment]
Did this ever get implemented? I would have use for this as well.

**Comment by nohwnd** [comment]
the gherking functionality should be available in the Pester/DevelopmentV4 branch, a developement branch for Pester 4. That version works pretty fine, but it's your consideration if you should use it in production environment before it's fully released.

**Comment by Xoph** [comment]
Cool! Thank you. We write our requirements in Gherkin, and we have a proprietary tool that analyzes the Pester results and traces them back to the Gherkin requirements, so having the Gherkin output would make it a step easier.

**Comment by nohwnd** [comment]
Give it a try it and see if it will work for you. I guess Jaykul is the only real user of this at the moment (or one of a few), so if you have some more questions I suggest you start a new issue and ask there, hopefully he will respond.

**Comment by Jaykul** [comment]
Do you think Pester 4 will ever be released? ;-)

**Comment by nohwnd** [comment]
Let's do it next week. :)


Jakub Jareš

.NET, Pester, PowerShell
t 00420603800578<tel:00420603800578>
e me@jakubjares.com<mailto:me@jakubjares.com>
t @nohwnd

29. 11. 2016 v 19:58, Joel Bennett <notifications@github.com<mailto:notifications@github.com>>:


Do you think Pester 4 will ever be released? ;-)

**Comment by gaelcolas** [comment]
@Jaykul @nohwnd  @dlwyatt Am I right thinking this issue can be closed as Gherkin support has been released in v4? (and thank you for that!)

**Comment by Jaykul** [comment]
I think these are "Pending" or something while v4 is in RC?
