### ISSUE TITLE
Parametric script not working with configuration object

### ISSUE THREAD

**Issue by fflaten** [pester/Pester#1737]
## 1. General summary of the issue

Parametric script introduced in #1671 doesn't work with `PesterConfiguration.Run.Container`.

## 2. Describe Your Environment

Pester version     : 5.1.0 C:\Users\Frode\Git\Pester\bin\Pester.psm1
PowerShell version : 7.0.3
OS version         : Microsoft Windows NT 10.0.19041.0

## 3. Expected Behavior

Parametric scripts should be possible to call using a `PesterConfiguration`-object.

## 4.Current Behavior

```
$sb = { Describe "Describe" { It "Some test" { } }}
$container = New-TestContainer -ScriptBlock $sb
$c = [PesterConfiguration]::Default
$c.Run.Container = @($container)
SetValueInvocationException: Exception setting "Container": "Cannot convert value "System.Object[]" to type "Pester.ContainerInfoArrayOption". Error: "Unable to cast object of type 'Pester.TestScriptBlock' to type 'Pester.ContainerInfo'.""

$c.Run.Container = $container
SetValueInvocationException: Exception setting "Container": "Cannot convert the "Pester.TestScriptBlock" value of type "Pester.TestScriptBlock" to type "Pester.ContainerInfoArrayOption"."
```

## 5. Possible Solution

`New-TestContainer` creates objects of type `TestScriptBlock` or `TestPath`. These can be passed to `Invoke-Pester -Container` which converts them to `ContainerInfo`-objects using a private `New-BlockContainerObject`-function. This all works as it should.

When using the `$c.Run.Container` option this conversion doesn't happen, so the exception occurs as there are no implicit ways to convert them.

**Comment by fflaten** [comment]
Looked into solving this in C#, but a replacement for `Find-File` gets ugly. Maybe just move this logic inside `New-TestContainer` and let it output `ContainerInfo[]` from the start? If so `src/csharp/PesterFile.cs` could probably just be removed.
https://github.com/pester/Pester/blob/d5cc670bbc9d184dfcfb1d4b26ac6eff7875d367/src/Pester.ps1#L749-L771

It would make it harder to modify the container-objects after creation, but not sure if a user would care considering they can just re-run `New-TestContainer` to generate new objects using adjusted `Data` etc.

**Comment by nohwnd** [comment]
@fflaten do you think New-PesterContainer would be a better name for this concept? I asked about this in few places, and people usually prefer New-PesterContainer over New-TestContainer. What do you think?

**Comment by fflaten** [comment]
I agree. Better public name. More consistent with `Invoke-Pester` and the future `New-PesterConfiguration`.
