### ISSUE TITLE
Add deprecation message to New-Fixture

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#1738]
I had a feeling you did, which is why this was mostly copy/paste of Pester v4 version in case we wanted it. Without mentioning the removal in README or keeping it with a warning for a while, users following old blogs and examples might auto-load Pester v3/4 without knowing it get confused when it didn't work like this time..

Thought this was a useful "get started" tool, but I got no problems with adding a deprecation warning immediately if you don't believe it's useful in the long run. Maybe refer to https://pester.dev/docs/quick-start in the warning as a quick-start replacement?

_Originally posted by @fflaten in https://github.com/pester/Pester/pull/1726#issuecomment-715928635_

**Comment by nohwnd** [comment]
Yeah linking to quick start is a good idea. No hurry on that though.

**Comment by fflaten** [comment]
@nohwnd Still want to deprecated it after the improvements made in (#1766)? Got the feel it's lifetime might have gotten extended during that discussion? 😄

**Comment by nohwnd** [comment]
Let's keep it alive.
