### ISSUE TITLE
Relative execution path changes

### ISSUE THREAD

**Issue by VaughanJ** [pester/Pester#1756]
I thought I had seen a post on this, but can't find it.

I'm getting differing behaviour when running tests in visual studio code using the pester test explorer to running invoke-pester on the terminal.

The only difference is that the relative paths are different, one of them runs a directory before.

This varying behaviour makes it very difficult to load in scripts to support the execution of the tests.

I assume this is a known issue and has a workaround, but I didn't find it.

P.s I have quite a complex directory structure as the module contains a lot of classes and scripts.

**Comment by nohwnd** [comment]
@TylerLeonhardt do you know anything about this?

**Comment by VaughanJ** [comment]
Let me get some specific examples.

**Comment by VaughanJ** [comment]
`$global:executingTestPath = Split-Path -Parent $MyInvocation.MyCommand.Path

write-host "root path:$global:executingTestPath"

BeforeAll {

    write-host "before all path:$global:executingTestPath"`

Running via invoke-pester

Starting discovery in 4 files.
root path:C:\Repos\CICD\verizonconnect.cicd\code\Test\Build
Discovery finished in 392ms.
before all path:C:\Repos\CICD\verizonconnect.cicd\code\Test\Build\Helpers

running via "run test" in Visual Studio Code

Starting discovery in 1 files.
root path:C:\Repos\CICD\verizonconnect.cicd\code\Test\Build
Discovery finished in 351ms.
before all path:C:\Repos\CICD\verizonconnect.cicd\code\Test\Build

**Comment by TylerLeonhardt** [comment]
looks like when we call Pester in the extension, the resulting PWD is set to where the tests are, not where the tests are run. I.e:

My PWD before is:

```
rootOfMyRepo
```
after I run Pester via "Run test" CodeLens it's:
```
rootOfMyRepo/tests
```

I haven't dug in yet if this is the PSES's fault but it's not our script's fault in vscode-powershell:
https://github.com/PowerShell/vscode-powershell/blob/master/InvokePesterStub.ps1

**Comment by asears** [comment]
Also seeing this relative path issue, using pwsh in VSCode terminal.  It seems to be some regression introduced as it was working previously for me.

**Comment by fflaten** [comment]
There's some inconsistent behavior in vscode-powershell. If cwd is defined but empty (`cwd: ""`) in launch config, the cwd will stay unchanged. Unfortunately there's some hardcoded values to `cwd: "${file}"` depending on which command/feature you use.

AFAIK this is the current status in the extension:

- `PowerShell: Run` command explicitly set cwd to [file's directory](https://github.com/PowerShell/vscode-powershell/blob/main/src/features/ExtensionCommands.ts#L234) which casues a change
- The play-button above to the right of the editor is also [hardcoded to file's directory](https://github.com/PowerShell/vscode-powershell/blob/d0b1f772ef56b6a917dc2af392766413df5499d3/src/features/ExtensionCommands.ts#L226-L236)
- Generated launch configs like the suggested `Launch Current File` has `cwd: "${file}"` defined by default which changes directory
- If no launch configs are defined, vscode-powershell extension autogenerates with [`cwd: ""` (don't change directory) unless temporary console is enabled in settings](https://github.com/PowerShell/vscode-powershell/blob/ea34995bbf69e038bacd3fc6b88b8e20d16c8d03/src/features/DebugSession.ts?q=generate#L214-L238)
- Run/Debug Test-codelense and Run/Debug Pester Tests-commands [`doesn't specify cwd`](https://github.com/PowerShell/vscode-powershell/blob/d0b1f772ef56b6a917dc2af392766413df5499d3/src/features/PesterTests.ts#L68-L95) and PSES leaves it unchanged unless temporary consoles are enabled.

This is unrelated to Pester and affects every switch. The Pester-specific commands actually don't change the cwd. The more general launch/debug options however favor file's directory. This should be reported as issue in the vscode-powershell repo to consider changing the hardcoded ones.

**Comment by fflaten** [comment]
@asears Not sure what you're experiecing. Is the `Invoke-Pester` command executed directly in the integrated console or from a script that you run with F5? If the latter, see comment above.

@VaughanJ 

> Running via invoke-pester
> 
> Starting discovery in 4 files. root path:C:\Repos\CICD\verizonconnect.cicd\code\Test\Build Discovery finished in 392ms. before all path:C:\Repos\CICD\verizonconnect.cicd\code\Test\Build\Helpers
> 
> running via "run test" in Visual Studio Code
> 
> Starting discovery in 1 files. root path:C:\Repos\CICD\verizonconnect.cicd\code\Test\Build Discovery finished in 351ms. before all path:C:\Repos\CICD\verizonconnect.cicd\code\Test\Build
> 
> Issue; invoke-pester the path is incorrect when executing in the beforeall

Looks like you solved this in the update/edit, but just to explain it: When you execute `Invoke-Pester` it did a discovery on all 4 files in that directory (I guess) which trigges the line that set the global value in all files. This is done before any tests are executed (in the next Run-phase), so in `BeforeAll` (Run-phase) you would always see the value set by the last file discovered. When using `Run Test` it only discovered that single file in which case it works as expected.

Tips:
- Avoid global variables
- Pester v5 doesn't work with `MyInvocation`, so use `$PSScriptRoot` as you mentioned
- No code in the root of a testfile. Set a normal variable in a `BeforeAll`-block in the root of the file to make sure it executes when the actual execution (Run-phase) of that file begins. The variable will then be available in all blocks/tests in that file.

**Comment by fflaten** [comment]
Closing this as fixed per comments above. The remaining cwd-changes in vscode is reported in https://github.com/PowerShell/vscode-powershell/issues/4082#issue-1306936632 .  Let me know if I missed something here, if so we will re-open. 🙂
