### ISSUE TITLE
Block with foreach only written to screen once - bug?

### ISSUE THREAD

**Issue by fflaten** [pester/Pester#1759]
## General summary of the issue
Using `-ForEach` with Context/Describe, the block with the foreach-parameter is only written once to screen.
Or is it only the scriptblock that's supposed to be looped, not the block itself?
Notice the Context is written with expanded name in "Current Behavior", which is why I expect to see them all.

Seen while trying to repro https://github.com/pester/Pester/issues/1564#issuecomment-718295187

## Describe your environment

Pester version     : 5.1.0-beta3 C:\Users\Frode\Git\Pester\bin\Pester.psm1
PowerShell version : 5.1.19041.546
OS version         : Microsoft Windows NT 10.0.19041.0

Also tested in PowerShell 7.0.3

## Steps to reproduce

demo.tests.ps1
```powershell
BeforeDiscovery {
    function Get-Combinations {
        1..5 | % { @{ Number = $_; Text = "Text$_" } }
    }
}

Context '<Text>' -Foreach (Get-Combinations) {
    It "works <Number>" {
        $true | Should -Be $true
    }
}
```

`Invoke-Pester .\demo.tests.ps1 -Output Detailed`

## Expected Behavior

```
Context Text1
  [+] works 1 2.31s (12ms|2.3s)
Context Text2
  [+] works 2 5ms (3ms|2ms)
Context Text3
  [+] works 3 5ms (3ms|2ms)
Context Text4
  [+] works 4 5ms (3ms|2ms)
Context Text5
  [+] works 5 5ms (3ms|2ms)
Tests completed in 2.48s
Tests Passed: 5, Failed: 0, Skipped: 0 NotRun: 0
```

## Current Behavior

```
Context Text1
  [+] works 1 2.31s (12ms|2.3s)
  [+] works 2 5ms (3ms|2ms)
  [+] works 3 5ms (3ms|2ms)
  [+] works 4 5ms (3ms|2ms)
  [+] works 5 5ms (3ms|2ms)
Tests completed in 2.48s
Tests Passed: 5, Failed: 0, Skipped: 0 NotRun: 0
```

## Possible Solution?

Looks like `$Block.FrameworkData.WrittenToScreen = $true` affects all blocks for the context during `Write-BlockToScreen`
Demo:

```
[DBG]: PS > $Block.parent.blocks | select name, shouldrun, first, last, { $_.Data.Text }, { $_.FrameworkData.WrittenToScreen } | ft

Name                ShouldRun First  Last  $_.Data.Text   $_.FrameworkData.WrittenToScreen 
----                --------- -----  ---- -------------- ----------------------------------
ROOT - <Text>            True  True False Text1                                       False
ROOT - <Text>            True False False Text2                                       False
ROOT - <Text>            True False False Text3                                       False
ROOT - <Text>            True False False Text4                                       False
ROOT - <Text>            True False  True Text5                                       False

[DBG]: PS > $Block.FrameworkData.WrittenToScreen = $true
[DBG]: PS > $Block.parent.blocks | select name, shouldrun, first, last, { $_.Data.Text }, { $_.FrameworkData.WrittenToScreen } | ft

Name                ShouldRun First  Last  $_.Data.Text   $_.FrameworkData.WrittenToScreen 
----                --------- -----  ---- -------------- ----------------------------------
ROOT - <Text>            True  True False Text1                                        True
ROOT - <Text>            True False False Text2                                        True
ROOT - <Text>            True False False Text3                                        True
ROOT - <Text>            True False False Text4                                        True
ROOT - <Text>            True False  True Text5                                        True
```

All FrameworkData is generated as new hashtables in the call to `New-ParametrizedBlock`, so wouldn't expect the same reference. Voodoo? Does powershell create one hashtable and only provide the same reference too all `New-ParametrizedBlock`-calls?

Noticed a typo at the same time:
https://github.com/pester/Pester/blob/ed24b0dfac2d00df6766f41ac8da6b7a745bd12b/src/functions/Output.ps1#L757
`$Block.FrameworkData.Parent.WrittenToScreen` should be `$Block.Parent.FrameworkData.WrittenToScreen`

**Comment by fflaten** [comment]
🤦 Of course. The FrameworkData-hashtable is passed as a value WITH the `$Foreach`-array to `New-ParametrizedBlock`.

**Comment by nohwnd** [comment]
I have a function to clone hastable, but passing just CommandUsed seems better. Working on it.

**Comment by nohwnd** [comment]
I said one thing but did another, the .Clone() works just fine for now.
