### ISSUE TITLE
Reduce analyzer for unsafe command call to src/*

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#1761]
@fflaten  please reduce the scope of the new unsafe-call rule to src only. I am getting ton of those in tests: 

![image](https://user-images.githubusercontent.com/5735905/97805982-aae91080-1c59-11eb-890a-f3ab50c7f9b9.png)

**Comment by fflaten** [comment]
Unfortunately it's not possible to specify paths (or excluded paths) in the settings-file for vscode or `PSScriptAnalyzer.psd1`  AFAIK. Hopefully it's on their todo-list for PSSA2 or a future update to vscode-powershell

I could add a (ugly) filter in the rule itself to ignore when the extents filepath is null (like it is when vscode-powershell triggers it) or if filepath exists and doesn't contain `/src/`.

Other options:
- Rename `PSScriptAnalyzer.psd1` (or disable PSSA usage in vscode settings) to stop all autorun of rules in vscode. Then we'd manually call it with `Invoke-ScriptAnalyzer -Settings "AnotherNamePSSASettings.psd1" -Path "./src" -Recurse` when needed.
- Disable this rule in the settings for now and only check that manually when required.

I'll double-check on discord

**Comment by fflaten** [comment]
Btw. I'm currently seeing duplicate PSSA-alerts for all rules in the Problems-tab. Didn't want to disable the autorun of PSSA for Pester repo yet, but if it gets too noisy then "Reload Window" in VSCode will clear it. See powershell/vscode-powershell#3252
