### ISSUE TITLE
Change the code generated by New-Fixture

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#1766]
## Summary of the feature request

The code output by New-Fixture is working but I think it could be improved to give better idea of what needs to be done.

## How should it work? (optional)

```powershell
# New-Fixture -Name Get-Cactus

# in Get-Cactus.ps1
function Get-Cactus {
    throw [NotImplementedException]"Get-Cactus is not implemented."
}

# in Get-Cactus.Tests.ps1 
BeforeAll {
    . $PSCommandPath.Replace('.Tests.ps1', '.ps1')
}

Describe "Get-Cactus" {
    It "Returns expected output" {
        Get-Cactus | Should -Be "YOUR_EXPECTED_VALUE"
    }
}
```

When the user just runs it (and similar when they would fix the `YOUR_EXPECTED_VALUE` to their expected value:
```
Starting discovery in 1 files.
Filter 'Line' set to ('c:\p\Get-Cactus.Tests.ps1:5').
Discovering in C:\p\Get-Cactus.Tests.ps1.
Found 1 tests. 6ms
Discovery finished in 16ms.

Running tests from 'C:\p\Get-Cactus.Tests.ps1'
Describing Get-Cactus
  [-] Returns expected output 6ms (3ms|2ms)
   NotImplementedException: Get-Cactus is not implemented.
   at Get-Cactus, C:\p\Get-Cactus.ps1:2
   at <ScriptBlock>, C:\p\Get-Cactus.Tests.ps1:7
Tests completed in 245ms
Tests Passed: 0, Failed: 1, Skipped: 0 NotRun: 0
```

When they delete the not implemented line, or implement it somehow:

```
PS C:\p> . 'c:\Users\jajares\.vscode\extensions\ms-vscode.powershell-2020.6.0\InvokePesterStub.ps1' -ScriptPath 'c:\p\Get-Cactus.Tests.ps1' -LineNumber 5 -MinimumVersion5 -Output 'Detailed'


Starting discovery in 1 files.
Filter 'Line' set to ('c:\p\Get-Cactus.Tests.ps1:5').
Discovering in C:\p\Get-Cactus.Tests.ps1.
Found 1 tests. 5ms
Discovery finished in 11ms.

Running tests from 'C:\p\Get-Cactus.Tests.ps1'
Describing Get-Cactus
  [-] Returns expected output 101ms (98ms|2ms)
   Expected strings to be the same, but they were different.
   Expected length: 19
   Actual length:   2
   Strings differ at index 0.
   Expected: 'YOUR_EXPECTED_VALUE'
   But was:  '🌵'
   at Get-Cactus | Should -Be "YOUR_EXPECTED_VALUE", C:\p\Get-Cactus.Tests.ps1:7
   at <ScriptBlock>, C:\p\Get-Cactus.Tests.ps1:7
Tests completed in 338ms
Tests Passed: 0, Failed: 1, Skipped: 0 NotRun: 0
```

Imho both of those should fail to indicate that there is more work to be done.

**Comment by nohwnd** [comment]
@fflaten  what do you think?

**Comment by fflaten** [comment]
I thought this was being deprecated 😄 

I do like the mini-Koan. Maybe:

```powershell
function #name# {
    throw [NotImplementedException]"#name# is not implemented."
    "Something unexpected"
}
```

**Comment by nohwnd** [comment]
@fflaten I like the single line, because it is easy to remove.

**Comment by nohwnd** [comment]
And I actually found it quite useful today :D So it might not be removed after all. But the name could improve.

**Comment by fflaten** [comment]
> @fflaten I like the single line, because it is easy to remove.

I was just updating according to your example, minus the emoji as people might be using old OS with poor editors.

```
function Get-Cactus {
    #throw [NotImplementedException]"Get-Cactus is not implemented."
}

# Would return
[-] Get-Cactus.Returns expected output 16ms (10ms|6ms)
 Expected 'YOUR_EXPECTED_VALUE', but got $null.
```
which might be more confusing for a beginner than: 

```
function Get-Cactus {
    #throw [NotImplementedException]"Get-Cactus is not implemented."
    "Something unexpected"
}

# Would return
[-] Get-Cactus.Returns expected output 17ms (12ms|5ms)
 Expected strings to be the same, but they were different.
 Expected length: 19
 Actual length:   20
 Strings differ at index 0.
 Expected: 'YOUR_EXPECTED_VALUE'
 But was:  'Something unexpected'
```

But then again, real beginners might not use Pester at all, so.. you'll decide. 😄
I agree that the generated test should fail, even if is just because the function returns `$false` by default.

**Comment by nohwnd** [comment]
> I was just updating according to your example, minus the emoji as people might be using old OS with poor editors.

Did I put emoji in the template? That output was just an example, I did not put that into the template I hope. 

> Expected 'YOUR_EXPECTED_VALUE', but got $null.

You could make the same argument by commenting out both the throw and your message. I think the user is likely to delete all the generated code from the function. So we should ensure a single thing and that is: the code we generate is easy to find. 

If we just return $false, and the user won't remove it, there will be extra $false output into the pipeline and that is hell to debug and find. That is why the code throws, to cause failure when left in place. 

The same goes for 'YOUR_EXPECTED_VALUE', it is easy to find, and when you navigate to it, it hopefully suggests that you should replace it with your expected value. If you do that, then you get error like this: 

```
[-] Get-Cactus.Returns expected output 16ms (10ms|6ms)
 Expected '🌵', but got $null.
```

Which seems understandable even for a beginner, if they know they just put the 🌵 there.
