### ISSUE TITLE
Remove extra whitespace from the templates description

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#1767]
It's very hard to see where to actually write your stuff. I would remove the extra newlines and add double newline where user should write. E.g.: 

```
BEFORE: 

## Summary of the feature request

<!-- A clear and concise description of your idea.

What problem do you want to solve?

As a user I'd like to be able to get X by doing Y. This would be very useful in situations like Z.

-->

## How should it work? (optional)

<!-- Do you already have an idea of how this experience should be. Feel free to provide a short demo of usage and expected results.

-->
```

```
AFTER: 

## Summary of the feature request
<!-- A clear and concise description of your idea.
What problem do you want to solve?
As a user I'd like to be able to get X by doing Y. This would be very useful in situations like Z. -->


## How should it work? (optional)
<!-- Do you already have an idea of how this experience should be. 
Feel free to provide a short demo of usage and expected results. -->


```

**Comment by nohwnd** [comment]
@fflaten  what do you think?

**Comment by fflaten** [comment]
Looks clean in the short templates. 👍

Removed start/end line breaks when updating templates, but left this style for readability in the larger bug report template. What do you think about this style in that one? Still readable?

**Comment by fflaten** [comment]
I've updated all issue and PR templates in https://github.com/fflaten/githubsandbox with more compact style as suggested. Better? If so, I can make a PR

**Comment by nohwnd** [comment]
Yeah please PR I have few comments: 

- double newline where reporter should type
-  in the last point of the bug template there is:

"Bug fix pull requests are always welcome. See <link> **has** detailed instructions on how to contribute. " 

The does not really fit there.
