### ISSUE TITLE
Text uses "Visual Studio" but the "Visual Studio Code" logo

### ISSUE THREAD

**Issue by TylerLeonhardt** [pester/Pester#1768]
## Location

 https://pester.dev/

## General summary of the issue

Text uses "Visual Studio" but the "Visual Studio Code" logo on the homepage
![image](https://user-images.githubusercontent.com/2644648/98751563-2f801100-2375-11eb-9347-efc0de5d2caf.png)

**Comment by nohwnd** [comment]
Fixed, thanks!
