### ISSUE TITLE
F5 in VSCode - Cannot index into a null array

### ISSUE THREAD

**Issue by PrzemyslawKlys** [pester/Pester#1771]
## General summary of the issue

I have a rather simple scenario where I've enabled Pester 5 in VSCode and I can run pester using Run tests without any problems or when I start it up from the primary file. 

But once I try to press F5 on the file

![image](https://user-images.githubusercontent.com/15063294/98930139-805e4980-24dc-11eb-9b80-a558c60f7654.png)

It errors out

```
Cannot index into a null array.
At C:\Users\przemyslaw.klys\Documents\WindowsPowerShell\Modules\Pester\5.1.0\Pester.psm1:8471 char:13
+             Invoke-Pester -Path $Path | & $SafeCommands['Out-Null']
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
```

VSCode settings:

![image](https://user-images.githubusercontent.com/15063294/98930203-979d3700-24dc-11eb-92fe-5b26327d52e2.png)

## Describe your environment

```
Pester version     : 5.1.0-rc1 C:\Users\przemyslaw.klys\Documents\WindowsPowerShell\Modules\Pester\5.1.0\Pester.psm1
PowerShell version : 5.1.19041.610
OS version         : Microsoft Windows NT 10.0.19042.0
```

## Expected Behavior

No error, runs as with pressing a button

## Current Behavior

Erorr

```
Cannot index into a null array.
At C:\Users\przemyslaw.klys\Documents\WindowsPowerShell\Modules\Pester\5.1.0\Pester.psm1:8471 char:13
+             Invoke-Pester -Path $Path | & $SafeCommands['Out-Null']
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
```

## Possible Solution?

Nope :-)

**Comment by fflaten** [comment]
Thanks 👍 SafeCommands-cleanup PR gone wrong.

We need to pass the out-null in like we do with mocks + add test for  `Invoke-Interactively` usage (`Pester.RSpec.ts.ps1`?).
https://github.com/pester/Pester/blob/96c2e2de1b99ebe7920ba9c737011b775bd8324b/src/functions/Describe.ps1#L153-L159
