### ISSUE TITLE
Cannot Mock functions with Custom Attributes

### ISSUE THREAD

**Issue by EdLichtman** [pester/Pester#1772]
## General summary of the issue
When trying to Mock a function with a custom attribute, I cannot Mock a function with a custom attribute in the parameter.

This seems to be because the Pester Scope does not contain the attributes that are loaded into the external scope.

## Describe your environment

Pester version     : 5.0.3 C:\Program Files\WindowsPowerShell\Modules\Pester\5.0.3\Pester.psm1
PowerShell version : 5.1.19041.610
OS version         : Microsoft Windows NT 10.0.19041.0

## Steps to reproduce

Create a ValidationAttribute. Create a function with a parameter that uses that attribute. Attempt to mock that function.

```powershell
using namespace System.Management.Automation;

describe 'pester' {
    BeforeAll {
        class ValidateClassAttribute : ValidateArgumentsAttribute 
        {
            [void] Validate([object]$arguments, [EngineIntrinsics]$engineIntrinsics) 
            {
               
            }
        }
        function Test-Foo {
            param([ValidateClass()]
            $test)
        }
        
    }
    it 'should be able to mock Test-Foo' {
        Mock Test-Foo
        Test-Foo
        Assert-MockCalled Test-Foo
    }

    it 'should be able to run Test-Foo' {
        Test-Foo -Test 'Foo'
    }
}
```

## Expected Behavior
I should be able to mock that function so I can verify that it was called and not perform behavior within it.

## Current Behavior

Starting discovery in 1 files.
Discovery finished in 32ms.
[-] pester.should be able to mock Test-Foo 16ms (15ms|1ms)
 RuntimeException: Cannot find the type for custom attribute 'ValidateClass'. Make sure that the assembly that contains this type is loaded.
 PSInvalidCastException: Cannot convert value "Test-Foo" to type "System.Management.Automation.CommandMetadata". Error: "Cannot find the type for custom attribute 'ValidateClass'. Make sure that the assembly 
that contains this type is loaded."
 RuntimeException: Cannot convert value "Test-Foo" to type "System.Management.Automation.CommandMetadata". Error: "Cannot find the type for custom attribute 'ValidateClass'. Make sure that the assembly that contains this type is loaded."

Tests completed in 202ms
Tests Passed: 1, Failed: 1, Skipped: 0 NotRun: 0

**Comment by EdLichtman** [comment]
By the way, just to clarify, I say it seems to not load attributes loaded into external scope, more specifically I think it's that it does not seem to load Classes in the external scope assemblies.

**Comment by rsegers** [comment]
Did you find a way to solve this or to work around the issue? I'm experiencing the same unfortunately.

**Comment by nohwnd** [comment]
Looks like doing the cast in the correct scope allows it to work.

**Comment by nohwnd** [comment]
@Jaykul  I think you also had problem with this. Or was that just something similar?
