### ISSUE TITLE
I think I'm running into this issue (I'm using Pester 5.0.4):

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#1777]
I think I'm running into this issue (I'm using Pester 5.0.4):

- I have a module that internally calls `Invoke-WebRequest`. 
- When running the tests using `Invoke-Pester`, I can mock `Invoke-WebRequest`.
- However, when I put the `Invoke-Pester` call into a script, the Mock is ignored and the real `Invoke-WebRequest` is called.

I created a repro for this behavior which can be found here
https://github.com/ap0llo/repro-pester-mocking

_Originally posted by @ap0llo in https://github.com/pester/Pester/issues/1619#issuecomment-727547382_

**Comment by nohwnd** [comment]
@ap0llo I am not sure that is the same issue, but there is some difference between interactive run in VSCode and running the test file via a script. I am not sure what it is right now, because underneath the process is pretty much the same. 

It can be fixed by setting the Mock scope correctly, to be applied in the module that calls `Invoke-WebRequest` by adding `-ModuleName "SampleModule"` to the call. This will make the mock defined in the module where it should be, instead of relying on inheriting it from the script scope.

As I said I don't fully understand why that happens yet.

**Comment by ap0llo** [comment]
Adding the module name makes it work. 

Thanks!

**Comment by fflaten** [comment]
This is weird. The function and alias is set, but are immediately lost after the scriptblock-invocation is complete - even though it is dot-sourced 👻 
https://github.com/pester/Pester/blob/f90f42614b574d96c095e5e3d4c6ae815702c561/src/functions/Mock.ps1#L1032-L1034

**Comment by nohwnd** [comment]
@fflaten I see you are going down this rabbit hole. 😁 Where are you looking for that function? Because `.` will dot-source into the session state to which the scriptblock is attached. You can set a breakpoint into the `$ScriptBlock` and check `$ExecutionContext.SessionState`, when Module is empty you are in script scope, when it is not you are in that given module. 

On 1028 the scriptblock is attached to the target session state, so if you are standing at 1038 (right after the dot-sourcing executes) you are looking into Pester session state, but you probably defined it in the script scope, or SampleModule scope. Try using `& (Get-Module SampleModule) { Get-Command '*Pester*' }`
https://github.com/pester/Pester/blob/f90f42614b574d96c095e5e3d4c6ae815702c561/src/functions/Mock.ps1#L1028-L1037

Here is an example of how it works in general: 

```powershell

Get-Module -Name "m", "n" | Remove-Module
New-Module m -ScriptBlock { 
    function Set-Function($ScriptBlock) { 
        # we dot source the script block into the session state
        # to which it is attached, so this defines the function in 
        # module n and not in the current module (m)
        . $ScriptBlock
    }
} -PassThru | Import-Module

New-Module n -ScriptBlock {
    function Get-ScriptBlockFromN {
        $scriptBlock = { 
            function Hey {
                Write-Host "Hello, from $($ExecutionContext.SessionState.Module)"
            }

            Hey
        }
        # returns scriptblock attached to module N session state
        # in Pester we build the scriptblock ourselves, and attach it 
        # to the target module, and it takes the behavior provided by
        # user as a parameter. The user behavior is probably attached to 
        # script scope (Unless they used InModuleScope to wrap the whole
        # test, then it would be attached to the module that they specified)
        $scriptBlock
    }
} -PassThru | Import-Module

$sb = Get-ScriptBlockFromN
Set-Function -ScriptBlock $sb
if (-not (Get-Command -Name Hey -ErrorAction Ignore)) {
    Write-Host "Hey is NOT defined in Script session state."
}

if (-not (& (Get-Module m) { Get-Command -Name Hey -ErrorAction Ignore })) {
    Write-Host "Hey is NOT defined in m session state."
}
else {
    Write-Host "Hey is defined in m session state."
}

if (-not (& (Get-Module n) { Get-Command -Name Hey -ErrorAction Ignore })) {
    Write-Host "Hey is NOT defined in n session state."
}
else {
    Write-Host "Hey is defined in n session state."
}
```

**Comment by nohwnd** [comment]
@fflaten  here is my talk on the internals, the module stuff are explained there as well. https://www.youtube.com/watch?v=6d0K2i7pgQs

**Comment by fflaten** [comment]
> On 1028 the scriptblock is attached to the target session state, so if you are standing at 1038 (right after the dot-sourcing executes) you are looking into Pester session state, but you probably defined it in the script scope, or SampleModule scope. Try using & (Get-Module SampleModule) { Get-Command '*Pester*' }

You're ofc right. I'm in the Pester session state at 1038. Looking inside SampleModule didn't help though at that point as it's not imported, unlike when the tests are executed using `Invoke-Pester`. In that scenario, both mock alias+function and SampleModule are available directly at 1038.

Thanks for link! Movie-time tonight, even though I'm probably still confused from the prequel, "Inception" 🐇 🍿

**Comment by nohwnd** [comment]
@fflaten don't worry I am often confused by it as well, even more than by Inception :D If you have any questions ask me, my twitter DMs are open. I will either know it, or we can learn together.

**Comment by nohwnd** [comment]
I tried it with 5.1.0 and the repro succeeded with Invoke-Pester, but failed with run-tests.ps1. In 5.2.0 the run is isolated to script always, so with that version both run-tests.ps1 and Invoke-Pester fail. 

Posting here the repro files in case OP decides to remove the repo in the future, because it seems like important edge case to keep for the future: 

```powershell
# SampleModule.Tests.ps1
BeforeAll {
    Remove-Module "SampleModule" -Force -ErrorAction SilentlyContinue
    Import-Module (Join-Path $PSScriptRoot "SampleModule.psm1")
}

Describe "Get-Response" {

    It "returns the expected data" {

        Mock Invoke-WebRequest {
            return [PSCustomObject]@{
                Content = "Hello World"
            }
        }

        $response =  Get-Response
        $response.Content | Should -Be "Hello World"
    }
}
```
```powershell 
# SampleModule.psm1
function Get-Response {

    [CmdletBinding()]
    param()

    Invoke-WebRequest "http://example.com"
}
```
```powershell
# run-tests.ps1
Invoke-Pester -Path $PSScriptRoot
```

The fix for the failure is to specify the -ModuleName when defining the mock to inject it into the scope of SampleModule. 

```powershell
Mock Invoke-WebRequest {
    return [PSCustomObject]@{
        Content = "Hello World"
    }
} -ModuleName SampleModule
```
