### ISSUE TITLE
[5.0.4] Is there a way to use Before/After with -TestCases?

### ISSUE THREAD

**Issue by JAndritsch** [pester/Pester#1778]
## Question

I have several tests that use `-TestCases`. Each `It` accesses a single parameter defined within the test cases. I'd like to be able to reduce duplication in my test setup by using `BeforeAll`, but cannot because the parameters made available to `It` via `-TestCases` are not available in `BeforeAll`. 

Below is an example of what I'm hoping to do:

```powershell
# In this example, I need to fetch a user from the database once per test.
# I'd like to be able to relocate this setup into a BeforeAll, so that the
# user is fetched only once before all of the It blocks.
Describe "Trivial example" {
    $TestCases = @(
        @{ "Username" = "SomeUser" },
        @{ "Username" = "AnotherUser"}
    )

    BeforeAll {
        # I wish I had access to $Username in here so that I could fetch
        # the user one time and then reference it in each of my tests.
        $User = Get-UserByName -Name $Username
    }

    It "User <Username> exists" -TestCases $TestCases {
        # Fetching the user would ideally be done in BeforeAll, not here
        $User = Get-UserByName -Name $Username
        $User | Should -not -benullorempty
    }

    It "User <Username> has a properly configured profile" -TestCases $TestCases {
        # Fetching the user would ideally be done in BeforeAll, not here
        $User = Get-UserByName -Name $Username
        $User.Email | Should -not -benullorempty
        $User.AnotherProperty | Should -not -benullorempty
    }

    It "User <Username> has the expected roles" -TestCases $TestCases {
        # Fetching the user would ideally be done in BeforeAll, not here
        $User = Get-UserByName -Name $Username
        $User.Roles | Should -not -benullorempty
    }
}
```

Is there another way to accomplish this?

**Environment data**

```
Pester version     : 5.0.4 C:\Users\username\Documents\PowerShell\Modules\Pester\5.0.4\Pester.psm1
PowerShell version : 7.0.3
OS version         : Microsoft Windows NT 10.0.18363.0
```

**Comment by wethreetrees** [comment]
You could get the user in the test case definition

```
Describe "Trivial example" {
    $TestCases = "SomeUser", "AnotherUser" | ForEach-Object {
        $User = Get-UserByName -Name $_
        @{ "User" = $User; "UserName" = $User.Name }
    )

    It "User <Username> exists" -TestCases $TestCases {
        $User | Should -not -benullorempty
    }

    It "User <Username> has a properly configured profile" -TestCases $TestCases {
        $User.Email | Should -not -benullorempty
        $User.AnotherProperty | Should -not -benullorempty
    }

    It "User <Username> has the expected roles" -TestCases $TestCases {
        $User.Roles | Should -not -benullorempty
    }
}
```

**Comment by nohwnd** [comment]
BeforeAll runs once before all of the tests. But you have two test cases for each test, so you would have to run Get-UserByName at least twice.  

This is available in Pester 5.1.0-rc2, 5.1 will be released today or early next week: 

What you probably want instead is using -ForEach on Describe, if you have different data that you want to use per testcase you can put them as sub-hashtables in the hashtable holding the username. See the docs I wrote recently: 
https://pester.dev/docs/usage/data-driven-tests

**Comment by nohwnd** [comment]
If you don't want to update to 5.1 just yet, you can go down to the migrating from v4 section, and do the same thing, just backwards 😀

**Comment by JAndritsch** [comment]
@wethreetrees I'll give that a shot and see how it works in my tests.
@nohwnd Sweet! `ForEach` at the `Describe` level sounds like it'll do the trick. I'll try using 5.1 once it's released.

I'm going to close this issue. Thank you both!
