### ISSUE TITLE
Missing help for functions

### ISSUE THREAD

**Issue by fflaten** [pester/Pester#1783]
## Location
BeforeEach
AfterEach
BeforeAll
AfterAll
ConvertTo-JUnitReport
ConvertTo-NUnitReport
ConvertTo-Pester4Result
Export-JUnitReport
Export-NUnitReport
New-PesterContainer

## General summary of the issue
Missing examples or help completely. Looks bad on pester.dev

Even though Before* or After* are covered in usage, they should have a simple help+example like BeforeDiscovery

**Comment by fflaten** [comment]
I know some of this is mentioned in more generic "state of documentation" issues, but though it was time for specific issues to specific problems. As some help is fixed in readme, usage docs on pester.dev lately, it's hard to keep track in those general issues.

I can write some help for these if nobody's working on it already.

**Comment by fflaten** [comment]
@nohwnd : Does the 5.2 tag mean it's up for grabs? If so, I could probably get them ready in 1-2 days to make 5.1

**Comment by nohwnd** [comment]
@fflaten wrong milestone. Moved to 5.1, waiting for you PR to be done.
