### ISSUE TITLE
"Cannot bind argument to parameter" error when passing in script paramters

### ISSUE THREAD

**Issue by alanafrankly** [pester/Pester#1784]
## General summary of the issue
When I try to run my Pester script I get the follow error: System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'clientId' because it is an empty string.

My script takes in required parameters like this:

```
param(
    [Parameter(Mandatory)]
    [string]$clientId,
    [Parameter(Mandatory)]
    [string]$clientSecret,
)
```

When I hard code default values for these parameters, everything seems to be fine. But when I try to pass in values, I get an error. This was working in version 4.8.1 but stopped working as expected when I upgraded. 

## Describe your environment
Pester version     : 5.1.0-rc2 C:\Program Files\WindowsPowerShell\Modules\Pester\5.1.0\Pester.psm1
PowerShell version : 5.1.19041.610
OS version         : Microsoft Windows NT 10.0.19042.0

## Steps to reproduce
I run my script by just passing in the path in powershell. Powershell prompts me for inputs. However, when the script runs the inputs seem to get lost because I get this error:

```
Starting discovery in 1 files.
System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'clientId' because it is an empty string.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\Pester\5.1.0\Pester.psm1: line 2903
at Invoke-File, C:\Program Files\WindowsPowerShell\Modules\Pester\5.1.0\Pester.psm1: line 2912
at Invoke-BlockContainer, C:\Program Files\WindowsPowerShell\Modules\Pester\5.1.0\Pester.psm1: line 2837
at Discover-Test, C:\Program Files\WindowsPowerShell\Modules\Pester\5.1.0\Pester.psm1: line 1411
at Invoke-Test, C:\Program Files\WindowsPowerShell\Modules\Pester\5.1.0\Pester.psm1: line 2356
at Invoke-Pester<End>, C:\Program Files\WindowsPowerShell\Modules\Pester\5.1.0\Pester.psm1: line 4754
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\Pester\5.1.0\Pester.psm1: line 8471
at Invoke-Interactively, C:\Program Files\WindowsPowerShell\Modules\Pester\5.1.0\Pester.psm1: line 8475
at Describe, C:\Program Files\WindowsPowerShell\Modules\Pester\5.1.0\Pester.psm1: line 8444
at <ScriptBlock>, [FULL-SCRIPT-PATH]: line 97
at <ScriptBlock>, <No file>: line 1
```

## Expected Behavior
I expect PowerShell to take in my parameter and run the script.

## Current Behavior
If I set a breakpoint at global variable declaration at the top of the script (after the parameter block) I can see that my parameters have values. When I continue debugging I hit this error.

**Comment by fflaten** [comment]
Parameterized tests requires use of `New-PesterContainer` in Pester v5. Have you tried it yet?
See example in the newly updated docs: https://pester.dev/docs/usage/data-driven-tests#providing-external-data-to-tests

**Comment by alanafrankly** [comment]
@fflaten , I have tried New-PesterContainer, but do I need to use that when I'm just calling the pester script directly? The powershell window asks for my inputs at run time and I can pass them in manually.

Realistically, I will want to use New-PesterContainer to automate, but Invoke-Pester with -container doesn't seem to be compatible with OutputFile/OutputFormat/Force. Or are these configured on the container too?

**Comment by fflaten** [comment]
> @fflaten , I have tried New-PesterContainer, but do I need to use that when I'm just calling the pester script directly? The powershell window asks for my inputs at run time and I can pass them in manually.

That is currently not supported. Will look into it. The prompt is used by the script, but Pester isn't invoked until the "Describe" function after, at which point it doesn't grab the current script parameters. So your parameters are lost immediately.

> Realistically, I will want to use New-PesterContainer to automate, but Invoke-Pester with -container doesn't seem to be compatible with OutputFile/OutputFormat/Force. Or are these configured on the container too?

You can combine them using [advanced interface](https://github.com/pester/Pester#advanced-interface). E.g.

```
$container = New-PesterContainer -Path ".\myFile.Tests.ps1" -Data @{ Param1 = "Value1" }
$c = [PesterConfiguration]::Default
$c.Run.Container = $container
$c.TestResult.Enabled = $true
$c.TestResult.OutputPath = "TestResults.xml"

Invoke-Pester -Configuration $c
```

**Comment by alanafrankly** [comment]
Thank you!
