### ISSUE TITLE
ConvertTo-Pester4Result output missing Version

### ISSUE THREAD

**Issue by fflaten** [pester/Pester#1786]
## General summary of the issue
The Version property returned in the Pester 4 result-object from `ConvertTo-Pester4Result` is blank.
This happens because `4.99.0` isn't a valid way to describe a version-type value. This currently fails silently and returns a null-value.

```
PS > [pscustomobject]@{Version = 4.99.0}                                          
PropertyNotFoundException: The property '0' cannot be found on this object. Verify that the property exists.
```

## Describe your environment
Pester version     : 5.1.0-rc2 /workspaces/Pester/bin/Pester.psm1
PowerShell version : 7.0.3
OS version         : Unix 4.19.128.0

## Steps to reproduce
```powershell
$c = New-PesterContainer -ScriptBlock { Describe "Demo" { It "Passes" { } } }
Invoke-Pester -Container $c -PassThru | ConvertTo-Pester4Result
```

## Expected Behavior
```
...
Version           :  4.99.0
TagFilter         : 
...
```
## Current Behavior
```
...
Version           : 
TagFilter         : 
...
```
## Possible Solution? (optional)
Replace the following
https://github.com/pester/Pester/blob/8ea7aa2ef1b9a1a9c38f80bf0952e442f0d35bad/src/Pester.ps1#L1362

with:
```powershell
Version = [version]"4.99.0"
```

Is string vs version-type locked? Pending #1503 that introduces the property in Pester v4?

**Comment by nohwnd** [comment]
I am using string because of pre-release versions which can have a suffix. Version cannot represent those versions, and the type that can is not available in all PowerShell versions that we support.

**Comment by fflaten** [comment]
> I am using string because of pre-release versions which can have a suffix.

Well, currently it's not using any type as it's not stored properly 😄

I can add a PR to make it a string later today, but then the linked WIP PR for Pester v4 should get a quick comment about this as well since it uses version-type + `$ExecutionContext.SessionState.Module.Version` to get it. Conflicting types.

**Comment by nohwnd** [comment]
> I am using string because of pre-release versions which can have a suffix.

I am using string on the normal result object. And this should be the same. 

I remember the v4 PR being broken but I did not investigate it further for a long time. Christmas time is coming with a month long vacation, and ban on travelling, so I might get to clean up here a bit. 🙂
