### ISSUE TITLE
Unable to Mock any functions defined in Module

### ISSUE THREAD

**Issue by efie45** [pester/Pester#1788]
## General summary of the issue

Unable to Mock a function defined inside of a Module.

A few approaches I've tried are shown below. I'm sure I'm just doing something completely wrong but I can't seem to figure it out. Hoping someone can help explain what I might be doing wrong. 

## Describe your environment
Pester version     : 5.1.0-rc2 /Users/<username>/.local/share/powershell/Modules/Pester/5.1.0/Pester.psm1                                        PowerShell version : 7.1.0                                                                                                                     
OS version         : Unix 10.15.6   (macOS running .NET core)

## Steps to reproduce

TestModule.psm1
```powershell
function Test-Mock {
    Write-Host 'Original function called.'
    return $false
}
```

Test.ps1
```powershell
Import-Module TestModule -Force
Test-Mock
```

Test.Tests.ps1
```powershell

Describe 'Regular Mock' {
    BeforeAll {
        . $PSCommandPath.Replace('.Tests.ps1', '.ps1')
    }
    Mock 'Test-Mock' {
        Write-Host "Mock Succeeded!"
        return $true
    }
    It "Fails" {
        Test-Mock | Should -Be $true
    }
}

Describe 'using -ModuleName' {
    BeforeAll {
        . $PSCommandPath.Replace('.Tests.ps1', '.ps1')
    }
    Mock 'Test-Mock' -ModuleName 'TestModule' {
        Write-Host "Mock Succeeded!"
    }
    It "Also Fails" {
        Test-Mock | Should -Be $true
    }
}

InModuleScope 'TestModule' {
    Describe 'using InModuleScope' {
        BeforeAll {
            . $PSCommandPath.Replace('.Tests.ps1', '.ps1')
        }
        Mock 'Test-Mock' -ModuleName 'TestModule' {
            Write-Host 'Mock Succeeded!'
        }
        It 'Also Fails' {
            Test-Mock | Should -Be $true
        }
    }
}

```

## Expected Behavior

I would like to be able to Mock the function Test-Mock in Test.Tests.ps1

## Current Behavior

Original function is always called over the Mocked command

**Comment by fflaten** [comment]
Is it a typo in your BeforeAlls? Your module is called TestModule.psm1 while you try to dot-source TestModule.ps1 in every BeforeAll.

**Comment by fflaten** [comment]
You should import the module in BeforeAll, not the script that would execute the function before your tests and mocks are ready.

Can you try:
```powershell
BeforeAll {
    . (Join-Path $PSScriptRoot "TestModule.psm1")
    #Or Import-Module TestModule if it's in modulepath
}
```

**Comment by abelal83** [comment]
Could you kindly give an example? I've tried what you suggested but mock function doesn't work.

```
# Find-Resources.psm1
function Find-SignalrService {
    param ( $ResourceGroup  )    
    return az signalr list --resource-group $ResourceGroup | ConvertFrom-Json
}

# Signalr.ps1
Import-Module .\Find-Resources.psm1
function Get-SignalrServices {
    param ( $ResourceGroups  )

    $signalrServices = New-Object System.Collections.ArrayList
    foreach ($resourceGroup in $ResourceGroups) {
        $signalrServices += Find-SignalrService -ResourceGroup $resourceGroup
    }
    return $signalrServices
}

# Signalr.Tests.ps1
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path) -replace '\.Tests\.', '.'
. "$here\$sut"

Describe "Start-FailoverSignalr" {
    BeforeAll {
        Import-Module .\Find-Resources.psm1
    }

    Context "Get-SignalrServices" {      
        
        It "ItName" {    
            Mock Find-SignalrService -MockWith {
              $t = new-object System.Collections.ArrayList
              $t.Add($signalRservices)
              return $t
            } -ModuleName Find-Resources -Verifiable
            Mock Find-SignalrService -MockWith {return $signalRservices} -Verifiable        
            $t = Get-SignalrServices -ResourceGroups x 
            $t | Should -BeOfType System.Collections.ArrayList
            Should -Invoke Find-SignalrService -Exactly 1
        }
    }
}
```

this is what I get

```
Starting discovery in 1 files.
Discovery finished in 34ms.
[-] Signalr.Get-SignalrServices.ItName 34ms (33ms|1ms)
 Expected the value to have type [System.Collections.ArrayList] or any of its subtypes, but got $null with type $null.
 at $t | Should -BeOfType System.Collections.ArrayList, C:\Users\abx\Signalr.Tests.ps1:97
 at <ScriptBlock>, C:\Users\abx\Signalr.Tests.ps1:97
Tests completed in 263ms
Tests Passed: 0, Failed: 1, Skipped: 0 NotRun: 0

**Comment by fflaten** [comment]
@abelal83 Are you using Pester v5 like OP? If so, you need to start by moving the import of your module/script inside a BeforeAll block, see. https://pester.dev/docs/usage/importing-tested-functions#migrating-from-pester-v4

A Pester v5 example of mocking inside modules is available at https://pester.dev/docs/usage/modules.

**Comment by fflaten** [comment]
👍  I'd recommend using BeforeAll for the Mock as it's not necessary to define it multiple times with the same code. BeforeAll-mocks will be available for all tests in the context

**Comment by abelal83** [comment]
Yep you are right, changed to BeforeAll and works perfectly. Thank you!
