### ISSUE TITLE
Parameterized test cases

### ISSUE THREAD

**Issue by msorens** [pester/Pester#179]
This is not a defect report, rather it is a feature request--with code provided to implement the feature.
Did not really see any other place to send this along to you...

In NUnit I am spoiled by being able to define one test case and provide multiple sets of inputs to feed to that function (using NUnit's TestCase attribute). It is such a handy thing to have that one of my colleagues implemented support for our JavaScript test cases with Jasmine and, based on that, I implemented the same thing for PowerShell test cases with Pester.

Here is an example usage, where the single test case (It) is executed 4 times because I have (a) provided 4 sets of inputs and (b) instrumented the script block to receive the parameters in each input set.

```
. "$PSScriptRoot\TestHelpers.ps1"

Describe "ContextUsingTest" {

    ContextUsing "using test" (
        (0, 1, 1),
        (1, 0, 1),
        (1, 1, 0),
        (0, 0, 0)
        ) {
        param($a, $b, $c)

        It ("Applies XOR to inputs {0} and {1}" -f $a, $b) {
            $a -xor $b | Should be $c
        }
    }
}
```

Here is the Pester output:

```
Describing ContextUsingTest
   Context using test
    [+] Applies XOR to inputs 0 and 1 0ms
    [+] Applies XOR to inputs 1 and 0 0ms
    [+] Applies XOR to inputs 1 and 1 0ms
    [+] Applies XOR to inputs 0 and 0 0ms
```

And here is the definition of ContextUsing, which is just Context with a couple lines tweaked:

```
function ContextUsing {

# Extended version of standard "Context" function.

param(
    $name,
    [object[]]$values,
    [ScriptBlock] $fixture
)
    $Pester.EnterContext($name)
    $TestDriveContent = Get-TestDriveChildItem

    $Pester.CurrentContext | Write-Context
    $values | % {
        invoke-command $fixture -ArgumentList $_
    }

    Clear-TestDrive -Exclude ($TestDriveContent).FullName
    Clear-Mocks
    $Pester.LeaveContext()
}
```

Note that ContextUsing will _not_ work with a single set of inputs, but it does not need to: a single set of inputs can use the regular Context function.

**Comment by treestryder** [comment]
Understanding that I can create my own loop. I like this feature and only wish that the -TestCases were not cast to System.Collections.IDictionary, such that it might work with other objects, particularly PsCustomObjects.

I'll admit, the problem I am currently trying to solve is a out of the ordinary, I'm testing someone else's mile long of multi-condition, nested If-Else statements. However, I can see value in TestCases being more inclusive, for needs beyond my own.

Thanks,
Nathan

EXAMPLE
```
$ function Add-Numbers($a, $b) {
    return $a + $b
}

Describe "Add-Numbers" {
    $testCases = ConvertFrom-Csv @'
a,b,expectedResult
2,3,5
-2,-2,-4
-2,2,0
'@

    It 'Correctly adds <a> and <b> to get <expectedResult>' -TestCases $testCases {
        param ([int]$a, [int]$b, [int]$expectedResult)

        $sum = Add-Numbers $a $b
        $sum | Should Be $expectedResult
    }
}
```

OUTPUT
```
Describing Add-Numbers
 [-] Error occurred in Describe block 53ms
   PSInvalidCastException: Cannot convert the "@{a=2; b=3; expectedResult=5}" value of type "System.Management.Automation.PSCustomObject" to type "System.Collections.IDictionary".
   ArgumentTransformationMetadataException: Cannot convert the "@{a=2; b=3; expectedResult=5}" value of type "System.Management.Automation.PSCustomObject" to type "System.Collections.IDictionary".
   ParameterBindingArgumentTransformationException: Cannot process argument transformation on parameter 'TestCases'. Cannot convert the "@{a=2; b=3; expectedResult=5}" value of type "System.Management.Automation.PSCustomObject" to type "System.Collections.ID
ictionary".
   at <ScriptBlock>, <No file>: line 13

```

**Comment by dlwyatt** [comment]
That feature uses splatting to send the parameters to the test case; splatting requires dictionaries.  You could write a quick function to take the objects from Import-Csv and convert them to hashtables, though:

```posh
function ConvertTo-Hashtable
{
    param (
        [Parameter(ValueFromPipeline = $true)]
        [Object[]] $InputObject
    )

    process
    {
        foreach ($object in $InputObject)
        {
            $hash = @{}

            foreach ($property in $object.PSObject.Properties)
            {
                $hash[$property.Name] = $property.Value
            }

            $hash
        }
    }
}

$testCases = ConvertFrom-Csv $yourCsvStuff | ConvertTo-Hashtable
```
