### ISSUE TITLE
Cannot install Pester 5.1.0 on a computer with PowerShell 3.0 or 4.0

### ISSUE THREAD

**Issue by cblalexv** [pester/Pester#1791]
## General summary of the issue
When I am trying to install Pester 5.1 on Windows Server 2012 (PS 3.0) or Windows Server 2012R2 (PS 4.0), I get the error message "PackageManagement\Install-Package : The specified wildcard pattern is not valid: $($p; &".

## Describe your environment
Two just created and clean AWS EC2 instances.

```
Pester version     : 5.0.4 C:\Program Files\WindowsPowerShell\Modules\Pester\Pester.psm1
PowerShell version : 3.0
OS version         : Microsoft Windows NT 6.2.9200.0
```

## Steps to reproduce

Run the following command to install the Pester module.
```
Install-Module -Name pester -Force -SkipPublisherCheck
```

## Expected Behavior
The module should be installed.

## Current Behavior
The module is not installed. I get the error message.

```
PackageManagement\Install-Package : The specified wildcard pattern is not valid: $($p; &
$SafeCommands['Remove-Variable'] -Scope Local -Name p)
At C:\windows\system32\windowspowershell\v1.0\Modules\PowerShellGet\PSModule.psm1:9711 char:34
+             $installedPackages = PackageManagement\Install-Package @PSBoundParam ...
+                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exce
   ption
    + FullyQualifiedErrorId : RuntimeException,Microsoft.PowerShell.Commands.TestModuleManifestCommand,Microsoft.Power
   Shell.PackageManagement.Cmdlets.InstallPackage
```

## Possible Solution? (optional)

Installing Pester module version 5.0.4 works fine.

**Comment by fflaten** [comment]
Thanks for the report. 🙂 

That error message isn't verify precise. I kinda see how I broke it by referencing a unavailable dictionary, but I'm having trouble seeing how this is being trigged. @nohwnd Do you see how this would affect installation? I can't see any of those `Anywhere` + `*Dependency` functions being used at all tbh. 

https://github.com/pester/Pester/blob/148d39acd7714b0dd6ca1dedbf84914106a39e51/src/Pester.Runtime.psm1#L2425-L2429

**Comment by nohwnd** [comment]
@fflaten I don't see it either, I guess trying this in a VM is the simplest way to see and fix it.  If you don't have the possibility to do that I can try it out. What would you prefer?

**Comment by nohwnd** [comment]
@fflaten installing VM, will take over this.
