### ISSUE TITLE
ConvertTo-NUnitReport produces an XML with test cases that have no description or name

### ISSUE THREAD

**Issue by gabloe** [pester/Pester#1803]
## Question

When running test cases with a tag filter the skipped tests are still reported in the resulting NUnit XML produced by ConvertTo-NUnitReport. For example:

```xml
<test-suite type="TestFixture" name="Test Context" executed="True" result="Success" success="True" time="119.9236" asserts="0" description="Test Context">
	<results>
		<test-suite type="ParameterizedTest" name="Test Suite" executed="True" result="Success" success="True" time="0" asserts="0" description="Test Suite">
			<results>
				<test-case description="" name="" time="0" asserts="0" success="False" />
				<test-case description="" name="" time="0" asserts="0" success="False" />
				<test-case description="" name="" time="0" asserts="0" success="False" />
				<test-case description="" name="" time="0" asserts="0" success="False" />
```

In this case the "Executed" field of the test-suite is set to true even though it's been skipped, and the test results all have no name, or description.

Is this expected? Having test case results with no name or description causes the nunit HTML reporting tool I am using to fail. If this is expected then I will file a bug against extent (https://github.com/extent-framework/extentreports-dotnet-cli)

**Environment data**

Pester version     : 5.0.4
PowerShell version : 5.1.19041.610
OS version         : Microsoft Windows NT 10.0.19042.0

**Comment by fflaten** [comment]
Try updating to Pester 5.1.0. 

I believe this was fixed in https://github.com/pester/Pester/issues/1662

**Comment by gabloe** [comment]
That did the trick 👍
