### ISSUE TITLE
InModuleScope: Way of setting strict mode with parameter

### ISSUE THREAD

**Issue by johlju** [pester/Pester#1808]
## Summary of the feature request
As a user I'd like to be able to set `Set-StrictMode`  using a parameter for `InModuleScope` when using Pester 5. This would be very useful in situations when we want to test that private functions aligns with a certain strict mode, but not necessarily want to enforce if during runtime in a user environment.

## How should it work?

Today this is possible by doing this:

```
It 'Should return the correct values' {
    InModuleScope -ModuleName $script:dscResourceName -ScriptBlock {
        Set-StrictMode -Version 1.0

        $mockInstanceName = 'DSCTEST'

        $getTargetResourceParameters = @{
            InstanceName = $mockInstanceName
            ProtocolName = 'TcpIp'
        }

        $getTargetResourceResult = Get-TargetResource @getTargetResourceParameters

        $getTargetResourceResult.InstanceName | Should -Be $mockInstanceName
    }
}
```

I rather see 

```
It 'Should return the correct values' {
    InModuleScope -StrictMode 1.0 -ModuleName $script:dscResourceName -ScriptBlock {
        $mockInstanceName = 'DSCTEST'

        $getTargetResourceParameters = @{
            InstanceName = $mockInstanceName
            ProtocolName = 'TcpIp'
        }

        $getTargetResourceResult = Get-TargetResource @getTargetResourceParameters

        $getTargetResourceResult.InstanceName | Should -Be $mockInstanceName
    }
}
```

**Comment by fflaten** [comment]
Not declining, but my personal view is that this feels very niche to be in a general helper-method.

**Comment by nohwnd** [comment]
Same opinion here, I don't see any upside of integrating it into inmodulescope function. It does not fit the purpose of the function very well, at least not more than integrating any other function in it (e.g. Measure-Command) and I don't want to bloat it. It also won't prevent you from forgetting to specify it, and imho is more cryptic than using the function directly. Closing this as won't fix.
