### ISSUE TITLE
InModuleScope: Cannot use [Parameter()] for the parameter inside the scriptblock

### ISSUE THREAD

**Issue by johlju** [pester/Pester#1809]
## General summary of the issue
This is similar to issue #1603, but not entirely.

When using `[Parameter()]` on the parameter declaration inside a InModuleScope it fails.

## Describe your environment
```
Pester version     : 5.1.1 C:\source\SqlServerDsc\output\RequiredModules\Pester\5.1.1\Pester.psm1
PowerShell version : 7.1.0
OS version         : Microsoft Windows NT 10.0.19042.0
```

## Steps to reproduce
```powershell
Describe 'Something' {
    Context 'When the desired protocol is Named Pipes' {
        BeforeAll {
            $mockPipeName = '\\.\pipe\$$\TESTCLU01A\MSSQL$SQL2014\sql\query'
        }

        It 'Should return the correct values' {
            $inModuleScopeParameters = @{
                MockPipeName = $mockPipeName
            }

            InModuleScope -ModuleName $script:dscResourceName -Parameters $inModuleScopeParameters -ScriptBlock {
                param
                (
                    [Parameter()]
                    [System.String]
                    $MockPipeName
                )
            }
        }
    }
}
```

## Expected Behavior
Not to fail.

## Current Behavior
It fails with the following error:
``` 
[-] Something.When the desired protocol is Named Pipes.Should return the correct values 8ms (7ms|1ms)
 ParameterBindingException: A positional parameter cannot be found that accepts argument '$null'.
```

## Possible Solution? (optional)
Removing the `[Parameter()]` solves the problem. This need to be documented if Pester will never support using `[Parameter()]`.

**Comment by johlju** [comment]
This is a non-issue if the param-block can be removed entirely as mentioned in https://github.com/pester/Pester/issues/1603#issuecomment-644908894.

**Comment by fflaten** [comment]
I'll let @nohwnd provide the official answer about supporting advanced function scriptbloks, but I've submitted a PR to fix the issue. Had a similar problem with Mock recently due to splatting a default null $ArgumentList-parameter to the scriptblock.
