### ISSUE TITLE
Parameter filter does work with a parameter named 'Arguments'

### ISSUE THREAD

**Issue by hjensen8** [pester/Pester#1819]
## General summary of the issue
Parameter filter for Mocks and Assertions (Should -Invoke) does not work when the name of the parameter is 'Arguments'

## Describe your environment
 - Pester version     : 5.1.1 C:\Users\htj\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1
 - PowerShell version : 7.1.0
 - OS version         : Microsoft Windows NT 10.0.19041.0

### Script 
```powershell
function Start-MyProcess {
    param (
        $Arguments
    )
    
    Invoke-CimMethod -ClassName Win32_Process -MethodName Create -Arguments $Arguments
}

```
### Tests
```powershell
BeforeAll {
    . $PSCommandPath.Replace('.Tests.ps1', '.ps1')
}

Describe "Start-MyProcess" {

    It "It invokes 'Invoke-CimMethod'" {

        Mock Invoke-CimMethod {}
        
        $myArgs = @{
            CommandLine               = 'notepad.exe'
            CurrentDirectory          = $null
            ProcessStartupInformation = $null
        }

        Start-MyProcess -Arguments $myArgs               

        Should -Invoke -CommandName "Invoke-CimMethod" -ParameterFilter {
            $Arguments.CommandLine -eq 'notepad.exe' 
        }
        
    }
}
```
## Expected Behavior
The assertion should detect that **Invoke-CimMethod** was called using parameters matching the parameter-filter.

## Current Behavior
The assertion does not detect that **Invoke-CimMethod** CmdLet was called, because the **$Arguments** variable is overwritten by Pester ( value of the $Arguments variable is set to an array of objects with zero elements), which prevents the parameter filter from working as intended.

**Comment by nohwnd** [comment]
We should rename our parameter to avoid the conflict, or make sure it has private scope. Thanks for posting.

**Comment by hjensen8** [comment]
You are welcome.
Thanks for a fast response.
