### ISSUE TITLE
Rendering issues in help for Invoke-Pester and New-PesterContainer due to non-breaking spaces (ascii char 160)

### ISSUE THREAD

**Issue by csandfeld** [pester/Pester#1820]
## Location

- Pester version: 5.1.1
- Function: Invoke-Pester and New-PesterContainer
- PowerShell Version 5.1.18362.1171

## General summary of the issue

The use of non-breaking space (ascii char 160) instead of regular space (ascii code 32) cause rendering issues in Windows PowerShell when viewing command help.

Example:
![image](https://user-images.githubusercontent.com/2597673/103557862-19458b80-4eb4-11eb-93ee-58c4a73b711a.png)

**Comment by csandfeld** [comment]
I can go ahead and submit a PR with non-breaking spaces replaced by spaces if you like.

**Comment by nohwnd** [comment]
Yes please do. I don't understand how that happened. Must be some autoformatting issue or something. Any ideas?

**Comment by csandfeld** [comment]
Honestly I'm not sure. My best guess is that it is introduced by copy/pasting from somewhere.
I will go ahead and submit the PR.
