### ISSUE TITLE
Populate $TestName before BeforeEach{}

### ISSUE THREAD

**Issue by JustinGrote** [pester/Pester#1824]
## Summary of the feature request
I would like to have `$TestName` available in BeforeEach, so I can meet certain requirements if needed. For instance, some tests I may not want to do the beforeEach, other times I may be running a test that needs a dependency loaded that would normally be loaded if the test was run as part of a suite rather than independently.

For example, in my Keepass extension I have a test to unlock the vault and a test for the credentials. If I run the test for credentials independent of the unlock, then I can't access the vault because it's locked. If I had testname in the beforeEach, I could do the unlock for everything but the unlock test (which is implicit)

## Workaround
In my case I can do the unlock test as a completely separate test in a completely separate context and clean it up, then always unlock as a beforeall in the next context.

**Comment by johlju** [comment]
Would it help to use `-ForEach` on the `Context`-block? Then you could access the property or string array value for each test. That way you could unlock the vault with a specific credential in the BeforeEach and then get the vault credential in the `It`-block? 🤔 See https://pester.dev/docs/usage/data-driven-tests.

**Comment by fflaten** [comment]
There have been other requests to access the object for the current test including name ++, so it might be solved in the future.

As for your current scenario though, I'd say your workaround is the solution. Context is there to group tests with ex. different requirements (unlocked vault in this case) so this is a perfect scenario. Hard-coding criterias usings test-names is ugly imo.

**Comment by JustinGrote** [comment]
@johlju I was not aware of `-Foreach` and I think this may be what I need. Thank you. I still think this is a valid request for the many use cases it can support so I will leave the case open until it is closed as fixed or wontfix :)
