### ISSUE TITLE
Pester v5 - Working with tags

### ISSUE THREAD

**Issue by Outek** [pester/Pester#1830]
## General summary of the issue
I'm using something like OVF with Pester. We are working with tags to seperate the infrastructuretests like "weekly" or "daily".

## Steps to reproduce
I have 2 Tests both with some tags
```powershell

Describe 'Get-Planet' -Tag @("Tag1", "Tag2") {

Describe 'Get-Planet' -Tag @("Tag3", "Tag4") {

```

```powershell
C:\Temp\Pester_Tags> Invoke-Pester -Output Detailed -TagFilter Tag1     


Starting discovery in 2 files.
Filter 'Tag' set to ('Tag1').
Discovering in Test1.Tests.ps1.
Found 1 tests. 12ms
Discovering in Test2.Tests.ps1.
Found 1 tests. 27ms
Discovery finished in 66ms.

Running tests from 'Test1.Tests.ps1'
Describing Get-Planet
  [+] Given no parameters, it lists all 8 planets 20ms (14ms|6ms)
Tests completed in 319ms
Tests Passed: 1, Failed: 0, Skipped: 0 NotRun: 1
```

## Expected Behavior
If i have a tag, the discovery should take account on it and should only run this test.

## Current Behavior
Discovery don't take account of tags in the tests and run the discovery over every test.

**Comment by nohwnd** [comment]
What exactly is the problem? Discovery is the part that finds tests and filters them based on the different filters. Tag is one of the filters. It reports all the found tests, not only tests that will run. Is the problem that you see found 1 tests for both files? I don't think it should say "found 0 tests", there were tests found, they just won't run. 

Maybe saying "Found 1 test matching filters, and 0 tests that will not run." is better?

**Comment by nohwnd** [comment]
@Outek  gentle ping on this.

**Comment by Outek** [comment]
My idea was, if i am working with tags, the discovery should work with tags too. My suggestion is based on something like "Operation Validation". We have a lot of tests in the folder. This looks something like this:

```powershell
Starting discovery in 34 files.
Filter 'Tag' set to ('Uptime').
Discovering in Ansible.Tests.ps1.
Found 2 tests. 104ms
Discovering in AV.Tests.ps1.
Found 16 tests. 40ms
Discovering in Burger.Tests.ps1.
Found 9 tests. 39ms
Discovering in Certificates.Tests.ps1.
Found 3 tests. 50ms
Discovering in CES.Tests.ps1.
Found 9 tests. 48ms
Discovering in Chocolatey.Tests.ps1.
Found 32 tests. 845ms
Discovering in DiskRemoved.Tests.ps1.
Found 1 tests. 33ms
Discovering in Folders.Tests.ps1.
Found 4 tests. 33ms
Discovering in HardwareIcon.Tests.ps1.
Found 1 tests. 39ms
Discovering in IIS.Tests.ps1.
Found 0 tests. 2.2s
Discovering in Java.Tests.ps1.
Found 1 tests. 31ms
Discovering in Licensing.Tests.ps1.
Found 6 tests. 40ms
Discovering in Lifecycle.Tests.ps1.
Found 3 tests. 37ms
Discovering in NetBackup.Tests.ps1.
Found 3 tests. 53ms
Discovering in Networking.Tests.ps1.
Found 24 tests. 704ms
Discovering in OsQuery.Tests.ps1.
Found 20 tests. 41ms
Discovering in PendingReboot.Tests.ps1.
Found 4 tests. 34ms
Discovering in Powershell.Tests.ps1.
Found 1 tests. 49ms
Discovering in PowershellModules.Tests.ps1.
Found 28 tests. 49ms
Discovering in Prometheus.Tests.ps1.
Found 3 tests. 1.07s
Discovering in RDP.Tests.ps1.
Found 1 tests. 39ms
Discovering in RegistryKeys.Tests.ps1.
Found 8 tests. 61ms
Discovering in RemoteAccess.Tests.ps1.
Found 20 tests. 51ms
Discovering in RuntimeManagement.Tests.ps1.
Found 8 tests. 37ms
Discovering in Schannel.Tests.ps1.
Found 34 tests. 63ms
Discovering in Security.Tests.ps1.
Found 7 tests. 162ms
Discovering in Software.Tests.ps1.
Found 55 tests. 4.87s
Discovering in Softwareupdate.Tests.ps1.
Found 2 tests. 95ms
Discovering in Uptime.Tests.ps1.
Found 1 tests. 51ms
Discovering in User.Tests.ps1.
Found 5 tests. 48ms
Discovering in WindowsEventlog.Tests.ps1.
Found 3 tests. 314ms
Discovering in Winrm.Tests.ps1.
Found 1 tests. 53ms
Discovering in WMI.Tests.ps1.
Found 2 tests. 54ms
Discovering in WSUS.Tests.ps1.
Found 13 tests. 56ms
Discovery finished in 11.83s.

Running tests from 'Uptime.Tests.ps1'
Describing Server Uptime
 Context Server Uptime
   [+] Should not be up longer than 32 days 88ms (79ms|8ms)
Tests completed in 12.08s
Tests Passed: 1, Failed: 0, Skipped: 0 NotRun: 329
```

I see that you can't just skip the discovery. It would be nice, if somehow i could only execute the discovery and the test in the tag. Maybe i should use one folder for each test, or would be your suggestion?

**Comment by fflaten** [comment]
> Maybe i should use one folder for each test, or would be your suggestion?

@Outek : This 👍 Folder-structure, filenames, predefined lists of filepaths are all good options depending on your what fits you best.

The problem about limiting discovery is: how would we know where the tags are? That's the job of discovery. It look through the files resolved from your provided paths and gather just enough evidence to know what's inside the files (containers to be specific) and make an educated decision whether to run blocks+tests or not based on the filters. Sure Pester could be smarter and skip discovery inside a Describe/Context-block that is already excluded for some reason, but this gets complex quick considering there are more filter-types than Include-/ExcludeTags (and we can't pick favorites 🙂). 

Discovery-phase is supposed to be super-quick and not involve any time-consuming logic, so my best tip would be to optimize:
- Use paths as to group the testfiles as you suggested. Then you can invoke it like `Invoke-Pester -Path '.\Software', '.\Policies', '.\Security\Weekly*.tests.ps1'` and limit discovery to files in those paths.
- Reduce time spent in discovery. I see your `Software.Tests.ps1` are running long. Maybe there's some processing not required to build testscases and blocks that you can delay until `BeforeAll/-Each` in run-phase? 

Sounds good?

**Comment by Outek** [comment]
Ok, sounds good to me, thank you 👍
