### ISSUE TITLE
Breaking change in 5.1.0 in PS v4: Should command cannot be found when a Should assertion is inside a test helper module function - Possibly caused by sccoping 

### ISSUE THREAD

**Issue by bergmeister** [pester/Pester#1831]
## General summary of the issue

I proved this started happening only when upgrading from 5.0.4 to 5.1.0 (or 5.1.1) and only in PowerShell 4 (Appveyor WMF4 image)

## Describe your environment

Appveyor - WMF4

## Steps to reproduce

Extract of the errors logs here: https://ci.appveyor.com/project/PowerShell/psscriptanalyzer/builds/37409870
```
CommandNotFoundException: The term 'Should' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
 at Test-CorrectionExtentFromContent, C:\projects\psscriptanalyzer-qdyb0\Tests\PSScriptAnalyzerTestHelper.psm1:49
 at <ScriptBlock>, C:\projects\psscriptanalyzer-qdyb0\Tests\Rules\AlignAssignmentStatement.tests.ps1:39
```

The line in the test where it fails is here: https://github.com/PowerShell/PSScriptAnalyzer/blob/master/Tests/Rules/AlignAssignmentStatement.tests.ps1#L39
Drilling down the stack trace into the function that it calls, where it actually fails at the end: https://github.com/PowerShell/PSScriptAnalyzer/blob/master/Tests/PSScriptAnalyzerTestHelper.psm1#L49

Therefore to me it seems a scoping issue whereby the `Should` function is not accessible any more if the assertion does not happen directly in the `It` block but in a helper module function that is called.

I tried to run the test suite in a VM that has PS4 but couldn't reproduce, I tried to reproduce it by coming up with a similar setup here with a dummy test in Appveyor but I couldn't repro: https://github.com/bergmeister/PesterBug1831
Any thoughts/ideas?

**Comment by fflaten** [comment]
None atm. and hard to debug without repro. 🙂 Still happening now and with latest version?
