### ISSUE TITLE
Problems with tests several layers deep

### ISSUE THREAD

**Issue by PsychoData** [pester/Pester#1836]
## Describe your environment

```
Pester version     : 5.1.1 C:\Users\username\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1
PowerShell version : 7.1.1
OS version         : Microsoft Windows NT 10.0.19042.0
```

## Steps to reproduce
I am trying to set up checking of DNS Records for Office 365 (and possibly other best practices later on). here is a snippet from code, 

```powershell
$SearchDomain = "Contoso.one"
$server = '8.8.8.8','1.1.1.1'

         Context "SPF" {
            BeforeAll {
                $params = @{
                    DnsOnly = $DnsOnly
                    Type    = 'TXT'
                    Name    = "$SearchDomain.doesntexist.com"
                }
            }
            It "SPF Record" {
                try {
                    $dnsResults = Resolve-DnsName @params -Server $server 
                } 
                Catch {
                }
                $dnsResults | Should -Not -BeNullOrEmpty

                $relevantTXTs = $dnsResults | Where-Object { $_.Strings -match 'v=spf1' } 
                $relevantTXTs                      | Should -HaveCount 1
                $relevantTXTs.Strings                | Should -HaveCount 1 
    
                ($relevantTXTs.Strings -join '' )  | Should -Match 'include:spf.protection.outlook.com'
    
                ($relevantTXTs.Strings -join '' )  | Should -Match '-all'

                ($relevantTXTs.Strings -join '' )  | Should -Match "-all$" -Because "nothing after '-all' will be evaluated"    
            }  -Tag 'Exchange', 'SPF', 'dns_TXT' 
        }
```

## Current Behavior
This works as expected, but I find it.... wrong that I would be 5+ `Should`'s deep within a "Single Test". The main difficulty is that a number of these are testing some refinement of the previous command. 

For example, in this I see it as several separate "checks"

 * Test 1 - Check that DNS Resolves successfully
 * Test 2 - Check that there is only 1 TXT Record matching as "spf"
 * Test 3 - Check that the SPF Record includes the required Include
 * Test 4 - Check that the SPF Record includes `-all`
 * Test 5 - Check that the SPF Record does not have anything after `-all`

but I can't find a way to separate them without re-running the DNS Query again for every `It {` block, which opens me to more possibilities for error, like flaky DNS not returning 100% of the time, or the confusing possibility of a DNS server that was serving multiple servers round-robin and the tests were all being conducted against different Data. 

If I try to separate the separate "Tests" out to separate `It {` blocks, then I don't have a way to persist data from the 'only 1 SPF Record' test to the rest of them. 

If I solve that by pushing it up to the `BeforeAll ` block, then I either have to crash the BeforeAll by having an `It {` fail inside it, which seems like a bad practice (and might be missed by Discovery? further confusing any results), or I need to silently swallow it and just not have Tests (and therefore results output) for "Cannot resolve $Domain" or "We should have 1 SPF record and we found 3" 

Is there some way to persist the data/results between these separate tests, or to show many results for a single test? 
I know that dependencies were something I saw mentioned, and if they were implemented I could probably use that to sole the issue, but making them Depend like 1 <= 2 <= 3,4,5 , but I was hoping there might be some existing way to handle it.

**Comment by asears** [comment]
Unclear if pester will blow away global scoped variables on test teardown, have you tried setting the scope of the variable as global?  Would nested context work? Putting the acting expensive flaky command in beforeall with a couple retries?

Couple links may help:
https://pester-docs.netlify.app/docs/commands/BeforeAll
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_scopes?view=powershell-7.1
https://gist.github.com/gwalkey/c6d889884c3bb4a835c99f65b4d39ab6

The last one has an interesting method of introducing exponential backoff that could be implemented in Pester...

One way to persist the results would be to save as files and inspect the files.  Although you'd need to do some cleanup afterwards or use testdrive, it may make it easier to see the state of the dns entry at the time of checking.

#335 may relate.

**Comment by PsychoData** [comment]
I think I found it 

Inside a Context block 
- Remove Any Existing Global Variables you want to use (Can accidentally persist across sessions when testing)
- Init Global Variables to initial Value, say `$spfRecordFound`, in the loose Context block
    - Cannot do this in BeforeAll because this scope doesn't seem to be effective while the other `It` and `Context` blocks are being Eval'd for `-Skip`
- It block for first test,  define variable in that test 
- Context with `-Skip:$($spfRecordFound)` 
    - this does NOT seem to work with multiple It blocks and -Skip on each, I am guessing it processes all of the It Blocks and evals if they need to be skipped all at once
- Repeat for level of dependancy/reliance needed 

It's still somewhat of a minefield, because ideally your test is Negative during Discovery, so that it will get into all Context blocks and their Children, but Positive once the first test has run

I would say that ideally we could define some sort of TestID and set "Relies on Test ID X" but I know that will be very difficult

**Comment by nohwnd** [comment]
Looks like you want this: https://github.com/pester/Pester#collect-all-should-failures

**Comment by fflaten** [comment]
@PsychoData Did you try the suggestion above?

> If I solve that by pushing it up to the BeforeAll block, then I either have to crash the BeforeAll by having an It { fail inside it, which seems like a bad practice (and might be missed by Discovery? further confusing any results), or I need to silently swallow it and just not have Tests (and therefore results output) for "Cannot resolve $Domain" or "We should have 1 SPF record and we found 3"

Not sure why you would need a `It`-block inside `BeforeAll`. You can use `Should` inside `BeforeAll` or any other ways of validating and throwing if the dependencies (dns-request) isn't how it should be. If `BeforeAll` fails, then the tests will also fail since their dependency failed. Alternatively you can ignore/catch the error in `BeforeAll` and use `Set-ItResult` to skip.

Ex.

```powershell
Describe 'd1' {
    Context 'SPF Fail' -Tag 'Exchange', 'SPF', 'dns_TXT' {
        BeforeAll {
            $SearchDomain = "Contoso.one"
            $server = '8.8.8.8','1.1.1.1'
            $params = @{
                DnsOnly = $DnsOnly
                Type    = 'TXT'
                Name    = "$SearchDomain.doesntexist.com"
            }
            $dnsResults = Resolve-DnsName @params -Server $server
            $dnsResults | Should -Not -BeNullOrEmpty
            $relevantTXTs = $dnsResults | Where-Object { $_.Strings -match 'v=spf1' }
        }

        It 'Should only get one SPF-record' {
            $relevantTXTs | Should -HaveCount 1
        }

        It "SPF Record has expected values" {
            $relevantTXTs.Strings | Should -HaveCount 1
            ($relevantTXTs.Strings -join '' ) | Should -Match 'include:spf.protection.outlook.com'
            ($relevantTXTs.Strings -join '' ) | Should -Match '-all'
            ($relevantTXTs.Strings -join '' ) | Should -Match "-all$" -Because "nothing after '-all' will be evaluated"
        }
    }

    Context 'SPF Skip Edition' -Tag 'Exchange', 'SPF', 'dns_TXT' {
        BeforeAll {
            $SearchDomain = "Contoso.one"
            $server = '8.8.8.8','1.1.1.1'
            $params = @{
                DnsOnly = $DnsOnly
                Type    = 'TXT'
                Name    = "$SearchDomain.doesntexist.com"
            }
            $dnsResults = Resolve-DnsName @params -Server $server -ErrorAction SilentlyContinue
            $relevantTXTs = $dnsResults | Where-Object { $_.Strings -match 'v=spf1' }
        }

        It 'Should only get one SPF-record' {
            if ($null -eq $relevantTXTs) { Set-ItResult -Skipped -Because "we couldn't retrieve the SPF DNS-record for domain $SearchDomain" }
            $relevantTXTs | Should -HaveCount 1
        }

        It "SPF Record has expected values" {
            if ($null -eq $relevantTXTs) { Set-ItResult -Skipped -Because "we couldn't retrieve the SPF DNS-record for domain $SearchDomain" }
            $relevantTXTs.Strings | Should -HaveCount 1
            ($relevantTXTs.Strings -join '' ) | Should -Match 'include:spf.protection.outlook.com'
            ($relevantTXTs.Strings -join '' ) | Should -Match '-all'
            ($relevantTXTs.Strings -join '' ) | Should -Match "-all$" -Because "nothing after '-all' will be evaluated"
        }
    }

    It 'Another test' {
        1 | Should -Be 1
    }
}
```
