### ISSUE TITLE
Script running in pester test pulls in wrong module's function

### ISSUE THREAD

**Issue by efie45** [pester/Pester#1849]
## General summary of the issue

Pester tests are pulling in functions from modules which aren't imported in the tests being executed.

I have a large repository which holds a bunch of other projects. I have some modules that include functions with the same name. They have different implementations depending on the project. 

The problem is that when I run the tests individually they work as there are no function naming conflicts, but when I run the tests altogether in my pipeline, the functions with the same name will run from the wrong module. 

The modules are being imported with a using statement at the top of my project test files.

## Describe your environment

Pester version     :  /.local/share/powershell/Modules/Pester/5.1.1/Pester.psm1                                                                                                 PowerShell version : 7.1.0                                                                        
OS version         : Unix 11.0.0

**Comment by nohwnd** [comment]
I thing those usings are causing the problems. The file runs as a whole in during Discovery phase, and then later it runs during run, so I guess it is possible that if a module with function that has the same name is imported later than the first one it will pick up the later function, and not the earlier function.

**Comment by efie45** [comment]
Interesting. I'm not sure how to avoid this as my modules contain classes and as far as I am aware that is the only way to import classes from modules in PowerShell. I suppose I could search for the command and remove any existing versions with Remove-Module after every script but that seems messy. Any other ideas?

**Comment by asears** [comment]
I had a similar situation and solved it by iterating through the folders, setting Pester configuration values for paths, and running Invoke-Pester on each folder.  Not ideal but solved scope and path traversal issues for me. 

A few resources I saw during my review of this functionality.

## Prefixing the module on import

```powershell
import-module mymodule -Prefix myPrefix
```

## Qualifying the function calls
https://www.sapien.com/blog/2015/10/23/using-module-qualified-cmdlet-names/

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_command_precedence?view=powershell-5.1

## Function drive.

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_function_provider?view=powershell-7.1
Microsoft.PowerShell.Management\Get-Process

**Comment by fflaten** [comment]
@efie45 Try `Import-Module` at the start of your testfile to overwrite the conflicting functionw. Ex.

```powershell
using module .\b.psm1

BeforeAll {
    Import-Module "$PSScriptRoot\b.psm1" -Force
}

Describe 'Testing module b' {
    It 'Testing abc' {
        abc | Should -Be 'invoked in module b'
    }
}
```

As @nohwnd explains, your `using module .\module123.psm1` at the top of your testfile are executed during the discovery-phase. They are also not executed in run-phase because the statement is placed outside any `BeforeAll/BeforeEach/It` blocks. This means that the last module imported during discovery "wins" the function name. Since it's not allowed to move the using-statement anywhere, like inside a `BeforeAll`-block, a workaround would be to use `Import-Module` to steal back the functions. Your classes are already imported by the using-statements.
