### ISSUE TITLE
ParameterBindingException when using Add-ShouldOperator

### ISSUE THREAD

**Issue by tbergstedt** [pester/Pester#1853]
## General summary of the issue
I'm having trouble using `Add-ShouldOperator` in Pester v5. I used to have a number of `Add-AssertionOperator` for Pester v4 that worked, but converting these to using the new command makes them fail with `ParameterBindingException`

## Describe your environment
Pester version : 5.1.1 C:\Users\tober\Documents\PowerShell\Modules\pester\5.1.1\Pester.psm1
PowerShell version : 7.1.2
OS version : Microsoft Windows NT 10.0.18363.0

## Steps to reproduce
I'm using the following (somewhat simplified) syntax:
```powershell
BeforeDiscovery {
    #Import common policy functions
    Import-Module $PSScriptRoot\CommonPolicyFunctions\CommonPolicyFunctions.psd1

    # Add imported assertions to Pester
    Add-ShouldOperator -Name 'UseFileEncoding' -Test $Function:UseFileEncoding

    $changedItems = ...
}

Describe "File" {

    Context "File Encoding" {
        It "'<_>' Should use correct file encoding" -ForEach $changedItems {

            $encoding = Get-FileEncoding $_
            $encoding.Encoding | Should -Not -UseFileEncoding -Encoding @("UTF-16") -item $_
        }    
    }
}
```

My UseFileEncoding.ps1:
```powershell
Function UseFileEncoding {
    <#
    .SYNOPSIS
    Tests whether an item uses any of given file encodings
    #>
    [CmdletBinding()]
    Param(
        $ActualValue,

        [string[]]$Encoding,

        $item,

        [switch]$Negate
    )

    foreach ($e in $Encoding) {
        [bool]$Pass = $ActualValue -match $e
    }
    If ( $Negate ) { $Pass = -not($Pass) }

    If ( -not($Pass) ) {
        If ( $Negate ) {
            $FailureMessage = 'Expected {{{0}}} to not use file encoding(s) {{{1}}}, but it appears to use {{{2}}}' -f $item,"$Encoding",$ActualValue
        }
        Else {
            $FailureMessage = 'Expected {{{0}}} to use file encoding(s) {{{1}}}, but it appears to use {{{2}}}' -f $item,"$Encoding",$ActualValue
        }
    }

    $ObjProperties = @{
        Succeeded      = $Pass
        FailureMessage = $FailureMessage
    }
    return New-Object PSObject -Property $ObjProperties
}
```
## Expected Behavior
Each item in `$changedItems` to be validated using the custom `UseFileEncoding` operator.

## Current Behavior
Each test fails with exception `ParameterBindingException: A parameter cannot be found that matches parameter name 'CallerSessionState'.`

## Possible Solution? (optional)
Might this have to do with the fact that my custom operator uses more input parameters than the standard `$ActualValue` and `$Negate`? Unfortunatley, this is the very reason I create such custom operators, so that I can produce error information more meaningful to the end user.

**Comment by tbergstedt** [comment]
And sorry for bombing you with bug reports now! That's mostly because I am trying to convert some scripts using Pester to produce test results in a not-so-standard way.

**Comment by fflaten** [comment]
As seen below, custom assertions will always receive ActualValue, Negate and CallerSessionState-values. 
https://github.com/pester/Pester/blob/5234884fff3202fb4c1b9f04bfd8c7e227095e87/src/functions/assertions/Should.ps1#L276

By adding `[CmdletBinding()]` in your custom assertion, you turn it into an advanced function which require very strict parameter binding as arguments are not allowed by default (normally caught by $args). You have three options:
1. Add a `$CallerSessionState`-parameter to your custom assertion param-block
2. Remove `[CmdletBinding()]` as you're not using any advanced functions-features like common parameters
3. Add a param `[Parameter(ValueFromRemainingArguments)]$Arguments` to behave like `$args` in normal functions.

Personally would prefer 1 or 2.

@nohwnd Maybe we should update the documentation to include `$CallerSessionState` as mandatory input for custom assertions? Just in case someone uses cmdletbinding or parameter-block in their assertion, e.g. to enabled `-Verbose` support.

**Comment by tbergstedt** [comment]
Thanks. The solution that worked for me was the first one, adding a `$CallerSessionState` to my custom assertion. In addition, I had to call the assertion with an added `-CallerSessionState (New-Object psobject)`. I tried using `-CallerSessionState @PSBoundParameters` first, but I guess that's a non-existing object at this stage of execution.

The second suggestion gave a bool conversion exception. I use a switch parameter as input to my test script, and as stated in #1851, I currently have to use `New-PesterContainer` followed by `Invoke-Pester` to call it. And apparently, this doesn't go well when passing bool values through a hash table.

Never tried the third option.

**Comment by fflaten** [comment]
You don't have to modify your test. The internals of Pester provide the value for it. 

As long as you adjusted the param-block of your custom assertion, you can use the same `$encoding.Encoding | Should -Not -UseFileEncoding -Encoding @("UTF-16") -item $_` in your test code

**Comment by fflaten** [comment]
Related pester/docs#95

**Comment by davecader** [comment]
You really need to document this feature properly. I can no longer get any of my custom assertions to work, which is extremely frustrating.

**Comment by fflaten** [comment]
Working on it 👍  Just collecting all related issues first to make sure I cover it all. See my comment above for the solution.
