### ISSUE TITLE
Upgrade csharp projects and dependencies, utilize language options

### ISSUE THREAD

**Issue by asears** [pester/Pester#1861]
## Summary of the feature request 

Pester should use later versions of .net framework and upgrade csharp dependencies.  Pester should check for null values in code at compile-time.

## How should it work? (optional) 

```xml
    <LangVersion>8.0</LangVersion>
    <Nullable>enable</Nullable>
    <TargetFrameworks>netstandard2.1;net48</TargetFrameworks>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
```

See https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types for nullable type checks.  Nullable check is safe to implement.

Upgrade tests could be done as part of devops test matrix and implemented on a branch.

```shell
# Pester
dotnet add package System.Management.Automation

# Pester.Tests
dotnet add package xunit
dotnet add package Microsoft.NET.Test.Sdk
dotnet add package xunit.runner.visualstudio
dotnet add package coverlet.collector
```

Wondering if changing target framework would break any downstream consumers or devs?
Is there any need for additional test coverage of the C# code?

**Comment by nohwnd** [comment]
I am using that version of .NET Framework on purpose to be compatible with PowerShell 3 which is net452.
