### ISSUE TITLE
Should -HaveParameter <parameter name> -HasArgumentCompleter does not cover all scenarios

### ISSUE THREAD

**Issue by dtewinkel** [pester/Pester#1890]
## General summary of the issue

The assertion `Should -HaveParameter <parameter name> -HasArgumentCompleter` does not work for argument completers that are registered with `Register-ArgumentCompleter`.

## Describe your environment

Pester version     : 5.1.1 C:\Users\User\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1
PowerShell version : 7.1.3
OS version         : Microsoft Windows NT 10.0.19042.0

## Steps to reproduce

```powershell
Describe "Reproduce" {
	BeforeAll	{
		function Reproduce()
		{
			param(
				[Parameter()]
#				[ArgumentCompleter({param($Command, $Parameter, $WordToComplete, $CommandAst, $FakeBoundParams)})]
				[String] $Foo
			)
		}

		Register-ArgumentCompleter -CommandName Reproduce -ParameterName Foo -ScriptBlock {
			param($Command, $Parameter, $WordToComplete, $CommandAst, $FakeBoundParams)
		}

	}

	It "should pass" {
		Get-Command Reproduce | Should -HaveParameter Foo -HasArgumentCompleter
	}
}
```

## Expected Behavior
The test should Pass. The Argument has an argument completer.

## Current Behavior
The test fails with error:
```
[-] Reproduce.should pass 16ms (14ms|2ms)
 Expected command Reproduce to have a parameter Foo, has ArgumentCompletion, but has no ArgumentCompletion.
 at Get-Command Reproduce | Should -HaveParameter Foo -HasArgumentCompleter, Reproduce.Tests.ps1:19
 at <ScriptBlock>, Reproduce.Tests.ps1:19
```

Test will succeed with using the (commented out) `ArgumentCompleter` attribute.

**Comment by nohwnd** [comment]
@lipkau I think you were adding this? Any ideas?

**Comment by dtewinkel** [comment]
I guess this gist on github may help in solving this issue: [Get-ArgumentCompleter.ps1](https://gist.github.com/indented-automation/26c637fb530c4b168e62c72582534f5b).
It provides a way to find the registered argument completers.

**Comment by nohwnd** [comment]
@dtewinkel @indented-automation @lipkau  Is anyone of you interested in making a PR for this? 🙂

**Comment by dtewinkel** [comment]
Thank you @indented-automation. I am looking forward to the next release.

**Comment by nohwnd** [comment]
@dtewinkel there will be at least 2 pre releases till then. Please help us test it. I will try to make one this morning.

**Comment by dtewinkel** [comment]
@nohwnd, Sure, no problem. I'll try to have a look at it and test it in my project a.s.a.p.

**Comment by dtewinkel** [comment]
@nohwnd, @indented-automation, to me it is working as expected now :-). Both for succeeding the test if the argument completer is present and for failing the test if the argument completer is missing.
