### ISSUE TITLE
The new mock logging for conflicting vars reports that variable is redefined when two mocks are used

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#1912]

**Comment by nohwnd** [comment]
It reports conflict when we run in function from the current scope. Because everything in in the same scope.

**Comment by fflaten** [comment]
Do you remember how to repro this by any chance?

**Comment by nohwnd** [comment]
Yeah, I think it was just having two mocks for the same command with a filter. Then the second mock filter would report all vars as duplicated.
