### ISSUE TITLE
Invoke-Pester fails due to missing HelperFunctions since Pester 5.2.0-beta1

### ISSUE THREAD

**Issue by fawohlsc** [pester/Pester#1921]
## General summary of the issue
Invoke-Pester fails due to missing HelperFunctions since Pester *5.2.0-beta1*:

![image](https://user-images.githubusercontent.com/41372128/116202796-4657cb80-a73b-11eb-9e10-19bc562bb9c2.png)

## Describe your environment

Pester version     : 5.2.0-beta1 C:\Users\*username*\Documents\PowerShell\Modules\Pester\5.2.0\Pester.psm1
PowerShell version : 7.1.3
OS version         : Microsoft Windows NT 10.0.19042.0

## Steps to reproduce

Code shared privately with @nohwnd.

Taken from stack trace:
![image](https://user-images.githubusercontent.com/41372128/116204943-8ae46680-a73d-11eb-8f94-ae3a27de5785.png)

## Expected Behavior
Invoke-Pester to execute tests like it did in *5.2.0-alpha3*.

## Current Behavior
Invoke-Pester fails with error message shared above.

## Possible Solution? (optional)
Currently not upgrading from *5.2.0-alpha3* as a workaround.

**Comment by nohwnd** [comment]
This seems to happen when running Pester from a module that has .psd1 dependency on other module that imports HelperFunctions via moduleToProcess dependency in their .psd1. 

The module is some half-loaded state where we see it in Get-Module but can't invoke in it.

No exported commands seen there: 
```
Binary     7.0.0.0               CimCmdlets                          {Get-CimAssociatedInstance, Get-CimClass, Get-CimInstance, Get-CimSession…}
Script     0.0                   HelperFunctions                     
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemProperty…}
```

Needs a try catch around the clean up logic. And hopefully a test.

**Comment by nohwnd** [comment]
https://github.com/PowerShell/PowerShell/blob/658837323599ab1c7a81fe66fcd43f7420e4[…]stem.Management.Automation/engine/runtime/Operations/MiscOps.cs This is the source of the error. I guess I can check if the returned object has session state (if that is public on the module type) or just handle that type of exception.
