### ISSUE TITLE
Configuration to stop running tests after first failure.

### ISSUE THREAD

**Issue by rifftual** [pester/Pester#1927]
## Summary of the feature request
Implement a configuration option that, when enabled, stops processing further tests if one fails. This would be similar to `--bail`` in [Mocha](https://mochajs.org/)

**Comment by fflaten** [comment]
Related #360

**Comment by fflaten** [comment]
Closing as fixed in #2023.

See the new option `Run.SkipRemainingOnFailure` option which will be available soon in Pester 5.3.
