### ISSUE TITLE
NotImplementedException

### ISSUE THREAD

**Issue by Dh3va** [pester/Pester#1931]
## General summary of the issue
When I invoke pester, he doesn't see the script on which I want the tests to run. Even when performing a basic test it doesn't see the script.ps1 and gives me this error: NotImplementedException. If I manually add the script.ps1 .(".\script.ps1") inside of the script.Tests.ps1 it works, and of course it works if the functions and tests are in the same file .Tests.ps1.

Update: From VisualStudio it works correctly, but not from iTerm2 when on pwsh.

## Describe your environment

I use a MacBook Pro with Big Sur, I installed PowerShell via Brew, added the Pester module via PowerShell.
PS /Users/ale/Documents/Pester> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Darwin 20.4.0 Darwin Kernel Version 20.4.0: Fri…
Platform                       Unix

Pester version 5.

## Steps to reproduce

Install Powershell via Brew 

```bash
brew install --cask powershell
```
From powershell

```powershell
Install-Module -Name Pester
```

Create a folder in ./Documents/Pester with two files in it: scripts.ps1 and script.Tests.ps1 with the following content:

script.ps1:
```powershell
function Install-Pester {
    param()
    Write-Output "Working!"
}
```
script.Test.ps1:
```powershell
describe 'Install-Pester' {
    it 'outputs a string' {
        Install-Pester | Should -Be 'Working!'
    }
}
```
```powershell
Invoke-Pester
```
The output is:
```powershell
PS /Users/ale/Documents/Pester> Invoke-Pester

Starting discovery in 1 files.
Discovery finished in 12ms.
[-] Install-Pester.outputs a string 22ms (20ms|2ms)
 CommandNotFoundException: The term 'Install-Pester' is not recognized as a name of a cmdlet, function, script file, or executable program.
 Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
 at <ScriptBlock>, /Users/ale/Documents/Pester/script.Tests.ps1:3
Tests completed in 83ms
Tests Passed: 0, Failed: 1, Skipped: 0 NotRun: 0
```

## Expected Behavior

It should pass the test.

## Current Behavior

It fails.

## Possible Solution? (optional)

Add the location of the script manually:

Modify the script.Tests.ps1:

```powershell
.(".\script.ps1")

describe 'Install-Pester' {
    it 'outputs a string' {
        Install-Pester | Should -Be 'Working!'
    }
}
```

```powershell
PS /Users/ale/Documents/Pester> Invoke-Pester                                                                                                                                                                     

Starting discovery in 1 files.
Discovery finished in 5ms.
[+] /Users/ale/Documents/Pester/script.Tests.ps1 61ms (16ms|41ms)
Tests completed in 77ms
Tests Passed: 1, Failed: 0, Skipped: 0 NotRun: 0
PS /Users/ale/Documents/Pester> 
```

**Comment by fflaten** [comment]
You need to load you script/module into the session. See https://pester.dev/docs/usage/importing-tested-functions#importing-the-tested-functions . Try:

script.Test.ps1:
```powershell
BeforeAll { 
    . $PSScriptRoot/script.ps1
    # Since this is not a module by design, be aware that any code in the file outside of a function-block will be executed!
}

Describe 'Install-Pester' {
    It 'outputs a string' {
        Install-Pester | Should -Be 'Working!'
    }
}
```

**Comment by Dh3va** [comment]
Thank you very much, now it's clear, I would still like to understand why it worked on VisualStudio, but anyway thank you again.
