### ISSUE TITLE
Configuration option Output.Verbosity of 'None' not fully respected when using RunOptions.Skip = $true

### ISSUE THREAD

**Issue by vexx32** [pester/Pester#1933]
## General summary of the issue

When using `RunOptions.Skip` to run discovery only in combination with `Output.Verbosity` being set to `'None'`, the message `The test run was skipped` is still printed.

## Describe your environment
```
Pester version     : 5.2.0 /Users/joelfrancis/.local/share/powershell/Modules/Pester/5.2.0/Pester.psm1
PowerShell version : 7.0.3
OS version         : Unix 20.4.0.0 
```

## Steps to reproduce

Run the following in a folder with some tests. I was using koan files doing some updates for PSKoans but any test file(s) should work the same.

```powershell
$configuration = New-PesterConfiguration
$configuration.Output.Verbosity = 'None'
$configuration.Run.SkipRun = $true
$configuration.Run.PassThru = $true

Invoke-Pester -Configuration $configuration
```

## Expected Behavior

The test result object is output, with no other console output.

## Current Behavior

The message `The test run was skipped.` is printed before the result object is output.

## Possible Solution? (optional)

I'm guessing that whatever is used to print that message is somehow nonstandard or not checking the configuration for whether it should print the message or not; setting the verbosity to None disables all other Pester output, I'm guessing this is just an oversight here.

Temporary workaround is to redirect stream 6 to $null:

```powershell
Invoke-Pester -Configuration $configuration 6> $null
```

**Comment by nohwnd** [comment]
Fixed by #1942
