### ISSUE TITLE
Mocking a certain cmdlet works in v5.1.1 but in v5.2.1

### ISSUE THREAD

**Issue by ErikMogensen** [pester/Pester#1945]
## General summary of the issue
Using Pester v5.1.1 I am able to mock a call to Get-AzApiManagement but not when using v5.2.0 and v5.2.1.

## Describe your environment

Pester version     : 5.1.1 C:\Program Files\PowerShell\Modules\pester\5.1.1\Pester.psm1
PowerShell version : 7.1.3
OS version         : Microsoft Windows NT 10.0.19042.0

and 

Pester version     : 5.2.1 C:\Program Files\PowerShell\Modules\pester\5.2.1\Pester.psm1
PowerShell version : 7.1.3
OS version         : Microsoft Windows NT 10.0.19042.0

## Steps to reproduce

Install the PowerShell Az module. Instructions are available at https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-5.9.0. 

Both Pester version 5.1.1 and version 5.2.1 should be installed.

Create a file with the following content:
```powershell
import-module Az.ApiManagement

function Test-Mock {
    Get-AzApiManagement -ResourceGroupName "NotExisting" -Name "Neither"
}   
```

Save it in an empty directory. Call it PesterRepro.psm1

Create another file and put the following content in it:
```powershell
$pesterVersion = (Get-module -Name Pester).Version.ToString()
Write-Host "Using Pester version $pesterVersion"

Import-Module "$PSScriptRoot\PesterRepro.psm1" 

Describe "Works in 5.1.1 but not in 5.2.1" {

    Context " when mocking a call Get-AzApiManagement" {
        BeforeAll {
            Mock -CommandName Get-AzApiManagement  -MockWith {
                Write-Host "Mocked call to Get-AzApiManagement"
                return  $null
            }
        }

        It " should mock" {
            Write-Host "Going to call Get-AzApiManagement"
            Test-Mock
        }
    }
}
```
Save it as PesterRepro.Test.ps1 in the same directory.  

For the working scenario start a new PowerShell session and enter:
```powershell
    cd <directory where the files are>
    import-module pester -RequiredVersion 5.1.1
    invoke-pester
```

For the scenario that does not work start a new PowerShell session and enter:
```powershell
    cd <directory where the files are>
    import-module pester -RequiredVersion 5.2.1
    invoke-pester
```

It does not work with Pester 5.2.0 either.

## Expected Behavior

I expected the Pester versions 5.2.0 and 5.2.1 to mock the call to Get-AzApiManagement just like Pester version 5.1.1 does.

## Current Behavior

When using Pester version 5.2.0 or 5.2.1 the call to Get-AzApiManagement is not mocked.

**Comment by nohwnd** [comment]
You need to specify -ModuleName on the Mock. 

```powershell
 Mock -CommandName Get-AzApiManagement  -MockWith {
    Write-Host "Mocked call to Get-AzApiManagement"
    return  $null
} -ModuleName PesterRepro
```

This worked previously because mocks from a module that does not define the mocked function would leak from the module scope.

**Comment by ErikMogensen** [comment]
You are absolutely right. Thanks for the super-quick reply and for making a great tool!

**Comment by hangar18rip** [comment]
Hi. Do you plan a doc refresh with this point soon?
