### ISSUE TITLE
Using ANSI escape codes for output

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#1953]
Using ANSI escape codes would probably also fix output not being colored in CI, which is very unfortunate:

<details>
<summary>Travis CI</summary>

![image](https://user-images.githubusercontent.com/10532611/58371056-3e1f0200-7f0e-11e9-9d68-44ee04a82b53.png)

https://travis-ci.org/felixfbecker/PSKubectl/jobs/500233965

</details>
<details>
<summary>VSTS</summary>

![image](https://user-images.githubusercontent.com/10532611/58371067-5727b300-7f0e-11e9-99e4-474fd6b89fa7.png)

https://felixfbecker.visualstudio.com/PowerGit/_build/results?buildId=179

</details>

_Originally posted by @felixfbecker in https://github.com/pester/Pester/issues/1265#issuecomment-495924708_

**Comment by nohwnd** [comment]
For perf reasons and because of the redirect issue above make sure we use one write host per line (or less).

**Comment by fflaten** [comment]
Should I look into this?

Thinking that we would extend OutoutConfiguration with a new option. If not set explicit, auto-detect.

Would also limit ANSI-output to the same ConsoleColor-values for now as all VT-terminals doesn't support full RGB. 

Could maybe introduce a private `Write-PesterHost` helper function to avoid if ansi/else-blocks in the code. That is unless the syntax gets too complex. Would need array-parameter for a new class to support multiple vs single write-host calls.

**Comment by nohwnd** [comment]
if you are interested in this and see some upside then sure why not. Sure add a function to encapsulate the logic, but probably figure it out at the module load/invoke-pester and then reuse the result? Most, if not all, of the output should be contained the Output.ps1

**Comment by asears** [comment]
Other than ANSI, color can be controlled via Azure Devops-specific commands.  There are not as many color options available as in Output.ps1 themes though.

https://developercommunity.visualstudio.com/t/write-host-foreground-color-with-powershell-task-i/440605

Travis CI has this unbuffer workaround for colorizing output.
https://github.com/travis-ci/travis-ci/issues/7967#issuecomment-424521694

Kieran Marron posted this example of colorizing the Write-Information output.
https://blog.kieranties.com/2018/03/26/write-information-with-colours

Getting rid of direct calls to Write-Host by first wrapping it with a new Write-PesterHost or Write-HostOutput or Write-TermOutput call would probably be beneficial to Pester framework flexibility with various CI/CD outputs.

**Comment by beatcracker** [comment]
I'm using my own drop-in replacement for `Write-Host` to colorize output in CI (Azure DevOps):

- [Write-Host with ANSI colors](https://beatcracker.wordpress.com/2020/09/12/write-host-with-ansi-colors/) (source: [Write-Host.ps1](https://github.com/beatcracker/Powershell-Misc/blob/master/Write-Host.ps1))

I just dot-source it before running anything else and didn't have any issues yet. Unfortunately it doesn't work with Pester because of the `SafeCommands`. You might try to embed it, since it would provide an easy way to produce color output. Or at least allow for `Write-Host` it to be overridden, so we can fix it ourselves.

**Comment by briantist** [comment]
@beatcracker 's suggestions seem great to me, I would love to be able to get colorized output in GitHub Actions and I think that would do the trick.

**Comment by fflaten** [comment]
That's the idea. The plan is similar, but tried to also merge multiple messages to a single `write-host` call so we can fix broken redirection of Information-stream.

Btw Pester 5.3 highlights errors in GitHub Actions. So at least they're red atm. 🙂

**Comment by briantist** [comment]
> That's the idea. The plan is similar, but tried to also merge multiple messages to a single `write-host` call so we can fix broken redirection of Information-stream.
> 
> Btw Pester 5.3 highlights errors in GitHub Actions. So at least they're red atm. 🙂

Nice, is there a PR or some WIP I can follow?

**Comment by fflaten** [comment]
Not yet. Profiled some PoCs when this issue was created, but haven't had time after. Not sure if the stream redirection is worth the perf cost, tried to find the cheapest way.

**Comment by briantist** [comment]
> Not yet. Profiled some PoCs when this issue was created, but haven't had time after. Not sure if the stream redirection is worth the perf cost, tried to find the cheapest way.

Thanks! A short term change that could be helpful is beatcracker's suggestion of allowing overrides of `Write-Host` at least. That might not work for every scenario, and that might cause issues with mocking, but it would be something.

**Comment by fflaten** [comment]
There's nothing stopping you from overwriting it already. It is unsupported but as long as you use a parameter-compatible replacement it should work fine. The internal `SafeCommands`-system is mostly there to avoid unintentional hijacks and only used by internal code. Demo:

```powershell
function global:mywritehost {
    [CmdletBinding()]
    Param(
        [Parameter(ValueFromPipeline=$true)]
        [Alias('Message')]
        [System.Object[]]$Object,
        [System.Object]$Separator,
        [System.ConsoleColor]$ForegroundColor,
        [System.ConsoleColor]$BackgroundColor,
        [switch]$NoNewline
    )

    Microsoft.PowerShell.Utility\Write-Host -Object "AWESOME - $Object" @PSBoundParameters
}

Import-Module Pester

# Overwrite internal Write-Host reference to point at custom function. Will work until re-import of module
& (Get-Module Pester) { $SafeCommands['Write-Host'] = Get-Command -Type Function -Name mywritehost }

# Test it
Invoke-Pester -Path xyz.tests.ps1 -Output Detailed
```

There won't be any official way of doing this, especially considering the direct use of `Write-Host` will be replaced when this feature isse is fixed. You could use `-Output None -Passthru` and create your own output based on the returned result-object.

**Comment by nohwnd** [comment]
```powershell
function mywritehost {
    [CmdletBinding()]
    Param(
        [Parameter(ValueFromPipeline=$true)]
        [Alias('Message')]
        [System.Object[]]$Object,
        [System.Object]$Separator,
        [System.ConsoleColor]$ForegroundColor,
        [System.ConsoleColor]$BackgroundColor,
        [switch]$NoNewline
    )

    Microsoft.PowerShell.Utility\Write-Host -Object "AWESOME - $Object" @PSBoundParameters
}

Import-Module Pester

& (Get-Module Pester) { param ($c) $SafeCommands['Write-Host'] = $c } (Get-Command mywritehost)
```

Commenting just because I am stickler for scoping. That function does not have to be global, you can pass the command info in, and assign it. 🙂
