### ISSUE TITLE
Pester says "Test run has failed" and then reports "Failed: 0"

### ISSUE THREAD

**Issue by duncanworthy** [pester/Pester#1956]
## General summary of the issue
Pester appears to report all tests as having succeeded, but then also reports "Test run has failed".

## Describe your environment
Windows Server 2019 VM in Azure

Pester version     : 5.2.1 C:\Program Files\WindowsPowerShell\Modules\Pester\5.2.1\Pester.psm1
PowerShell version : 5.1.17763.1852
OS version         : Microsoft Windows NT 10.0.17763.0

## Steps to reproduce
While using packer to build a VM image, based on a subset of the scripts in repo https://github.com/actions/virtual-environments, the file https://github.com/actions/virtual-environments/blob/main/images/win/scripts/Tests/Git.Tests.ps1 is executed during https://github.com/actions/virtual-environments/blob/main/images/win/scripts/Installers/Install-Git.ps1

```powershell
Invoke-PesterTests -TestFile "Git" -TestName "Git"
```

## Expected Behavior
When all tests complete successfully, no error should be reported.

## Current Behavior
Pester says "Test run has failed" but then reports that all tests succeeded.

```
    vhd: Starting discovery in 1 files.
    vhd: Filter 'FullName' set to ('Git').
    vhd: Discovering in C:\image\Tests\Git.Tests.ps1.
    vhd: Found 10 tests. 517ms
    vhd: Discovery finished in 1.09s.
    vhd: Running tests.
    vhd:
    vhd: Running tests from 'C:\image\Tests\Git.Tests.ps1'
    vhd: Describing Git
    vhd:   [+] bash is installed 704ms (472ms|232ms)
    vhd:   [+] awk is installed 24ms (23ms|1ms)
    vhd:   [+] git is installed 28ms (27ms|1ms)
    vhd:   [+] git-lfs is installed 69ms (68ms|1ms)
    vhd:   [+] bash is located in 'C:\\Program\ Files\\Git' 46ms (45ms|1ms)
    vhd:   [+] awk is located in 'C:\\Program\ Files\\Git' 6ms (4ms|1ms)
    vhd:   [+] git is located in 'C:\\Program\ Files\\Git' 3ms (2ms|1ms)
    vhd:   [+] git-lfs is located in 'C:\\Program\ Files\\Git' 4ms (3ms|1ms)
    vhd:   [+] Git core.symlinks=true option is enabled 228ms (227ms|1ms)
    vhd:   [+] GCM_INTERACTIVE environment variable should be equal Never 3ms (2ms|1ms)
    vhd: Tests completed in 4.42s
==> vhd: Test run has failed
    vhd: Tests Passed: 10, Failed: 0, Skipped: 0 NotRun: 0
```

Because of the "Test run has failed" message, packer aborts the VM image build.

**Comment by duncanworthy** [comment]
On further investigation it looks like the "Test run has failed" message is coming from the scripts that call Pester and then verify the result, so there must be some dubious logic there in that repo regarding what has run/failed/passed.

Will close this issue once a further test run confirms my suspicions.

**Comment by nohwnd** [comment]
I can't find any mention of that string in our repo (or organization), I tried searching for each word, but I can't find where it is coming from. 

Looks like it's not a Pester issue, but instead Test.Helpers.psm1 issue of this: https://github.com/search?l=PowerShell&q=%22Test+run+has+failed%22&type=Code

Not sure which one is the original one, or which one you are using but this looks like the relevant code: 

https://github.com/jamesrcounts/terraform-packer/blob/42f3fead093dbf612fec1523cced6a61b949abc3/tmp/virtual-environments-ubuntu18-20210219.1/images/linux/scripts/helpers/Tests.Helpers.psm1#L39-L42

**Comment by nohwnd** [comment]
I must have missed your second comment where you point out that it's not coming from Pester. Could have saved 5 minutes trying all to find it in our repo :D

**Comment by duncanworthy** [comment]
Sorry about that!
Yes, I had just done the same and tracked it down to the line you mentioned.

For the benefit of anyone else looking at Pester logs in the context of packer, the lines that are marked with a prefix of `==>` come from the Powershell scripts that packer is running, not the standard output from the tools that those scripts call out to.

**Comment by nohwnd** [comment]
I wonder what the error is, because that condition looked correct.

**Comment by duncanworthy** [comment]
Yeah, I'm still looking at it.
I'm trying to build a smaller image to use in an Azure Scale Set for Self Hosted Build VMs with a subset of their tools because we don't need half of the tools that come by default but need to add some of our own.
Possibly somewhere in the scripts it has a result like "Succeeded: 0, Failed: 0" that the condition check isn't expecting. I'm sure I'll figure it out.
