### ISSUE TITLE
Allow specifying the OutputXml path from pester.bat

### ISSUE THREAD

**Issue by daryl-mcmillan** [pester/Pester#196]
When calling pester.bat it always creates a report file in the working directory.  Because pester.bat always provides the OutputXml parameter to Invoke-Pester, the arguments that are passed through can't be used to override this location.

https://github.com/pester/Pester/blob/master/bin/pester.bat#L12

I can work around this by running pester.bat from the report location and specifying the Path to the tests, but being able to specify OutputXml would be pretty nice.

**Comment by dlwyatt** [comment]
BTW, as of a few days ago, we're no longer using pester.bat in our CI job.  (There's still a reference to it in build.psake.ps1, but our current CI job is only using the package step; the Test step has been replaced with PowerShell runners executing Invoke-Pester -PassThru.)

At this point, we could just get rid of the old .bat files and any dependencies on them, or keep them around as examples, whatever.

**Comment by vors** [comment]
:+1:
