### ISSUE TITLE
v5.0 renamed, master renamed

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#1963]
Following the suite of other repositories, and because the code in v4 is no longer focus of this repo.

-  `v5.0` is renamed to `main`
- `master` is renamed to `rel/4.x.x`
- `V3Maintenance` is renamed to `rel/3.x.x`

All PRs were re-based. And I will make PRs to docs and here to fix references v5.0 if there are any. 

@ArmaanMcleod @fflaten @asears @bravo-kernel  and other active contributors, GitHub will suggest how to rename the branch in your fork but it does not work for me, instead I've been using this to move / rename the branch:

```
git branch -m v5.0 main
git push -u origin main
```

If you have other active branches you might want to merge main into them, or rebase them on main before posting further PRs.

**Comment by bravo-kernel** [comment]
I can still see the site so... good job :)

**Comment by nohwnd** [comment]
I did not rename it in the docs-repo yet.

**Comment by bravo-kernel** [comment]
Oops, I feel silly now 🤦

**Comment by nohwnd** [comment]
Np. Will do that later.
