### ISSUE TITLE
Remove listing of files

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#1967]
https://github.com/pester/Pester/blob/3d11941bf5c08ca41486195dbfa7f7e4e5a02eef/src/functions/Output.ps1#L4

@ArmaanMcleod I think we should remove that output, it duplicates what is shown in the detailed view in discovery, and unlike the version it does not seem useful, because it is much easier to look at the discovery listing, instead of trying to decipher that list of files.

I think in the previous versions we printed the unresolved paths which made this more succinct, but it still was not very useful info, becaus most of the time it was just `running all tests in '.'.`

![image](https://user-images.githubusercontent.com/5735905/120447128-8dfcf300-c38a-11eb-8aee-97941ea6e5bc.png)

It also does not handle correctly when there are just scriptblocks executed, in that case it shows `Executing all tests in '' and 1 scriptblock`.

**Comment by fflaten** [comment]
Sounds good. There's already an issue/discussion about the discovery itself being too noisy for some users, so this additional message listing 500+ testfiles might get unpopular 🙂

**Comment by ArmaanMcleod** [comment]
Hi @nohwnd and @fflaten, fully agree on this. I've submitted a PR which removes the start message completely with that `"Executing all tests in..."` line.

**Comment by nohwnd** [comment]
Fixed in #1968
