### ISSUE TITLE
Upgraded from 5.1.1 to 5.2.2. Mocks for module referenced by relative path not working

### ISSUE THREAD

**Issue by forktrucka** [pester/Pester#1981]
## General summary of the issue
Have just updated to 5.2.2 from 5.1. 

## Describe your environment

Pester version     : 5.2.2 C:\Program Files\WindowsPowerShell\Modules\Pester\5.2.2\Pester.psm1
PowerShell version : 5.1.18362.1593
OS version         : Microsoft Windows NT 10.0.18363.0

## Steps to reproduce
An cut-down version from the original code base. Works fine in 5.1.1. Doesn't work in 5.2.2.

```powershell
Describe "Find-GitChangedFile" {
    BeforeAll{
        Import-Module "$PSScriptRoot\..\Git.psm1" -Force
        Import-Module "$PSScriptRoot\..\..\Util\Util.psm1" -Force
    }
    Context "Execution" {
        BeforeEach {
           
            $global:expected = @(
                "a",
                "b",
                "c"
            )          
          
            # Module function signature
            # function Invoke-ExternalCommand{
            #     param(
            #         [string]
            #         [Parameter(Mandatory = $true, Position = 0)]
            #         $command,
            #         [string[]]
            #         [Parameter(Position = 1, ValueFromRemainingArguments)]
            #         $commandArguments
            #     )          
            # }

            Mock -CommandName Invoke-ExternalCommand -MockWith {
                $passedArgs = [string]::Join(" ", $commandArguments)
                Write-Host "Mocking $Command $passedArgs"
                return $global:expected
            } -Verifiable 
          
        }
        It("returns a list of files") {

            $result = Find-GitChangedFilesByExtension -sourceReference "source" -destinationReference "destination" -extension ".ext"

            Should -Invoke Invoke-ExternalCommand

            $result | Should -Be $global:expected
        }
    }
}
```

The `Find-GitChangedFilesByExtension` cmdlet should call `Invoke-ExternalCommand`.

Reading through #1845 I understand that 5.2.2 is more strict, so did try adding `-ModuleName Util` to the mock as well as a `InModuleScope  -ModuleName Util`. Also tried forward slashes and backslashes. But no luck. 

Modules loaded:

![image](https://user-images.githubusercontent.com/17393932/121458190-0bfd7180-c9fd-11eb-9ea8-911ad74c459a.png)

## Expected Behavior
I expect the mock to be called, which will write out the command e.g. `Mocking git --no-pager diff source destination --name-only --diff-filter=dr -- *.ext` and return the expected value.

## Current Behavior
The actual implementation is called rather than the mock.

**Comment by fflaten** [comment]
Thanks for the report. `-ModuleName ...` is used to specify where the mock will be called from, not where it exists. In this case it will be called from `Find-GitChangedFilesByExtension` which I'm guessing belongs in Git.psm1

You also need to specify this to `Should -Invoke`. Try adding `-ModuleName Git` to both the Mock and Should commands. 

InModuleScope is not necessary here.

**Comment by forktrucka** [comment]
yep, that looks like that was it, thank you kind sir
