### ISSUE TITLE
invoke-pester fails 'unable to find type [pester.containerinfo]

### ISSUE THREAD

**Issue by Schutzhund3** [pester/Pester#1987]
## Issue
I copied my 5.2.2 folder to a disconnected server (C:\Program Files\WindowsPowerShell\Modules\Pester) folder.  I also unblocked all files in that folder and compared the ACL of the folder to the 3.4.0 folder with no differences.  

![pestererror](https://user-images.githubusercontent.com/31139481/121724677-352e0880-cab6-11eb-9996-6f7e09a93f30.png)

**Environment data**
Pester version 5.2.2
PowerShell version 5.1
OS version Windows Server 2016

**Comment by nohwnd** [comment]
Try `[PesterConfiguration]` does that give the same error? If yes the dll is not imported. Add-Type -Path (Path to the Pester dll in the net451 folder if you are one powershell 5). 

If not then there is something wrong with our types. But there are not other issues reporting this, and there are imho at least few thousands of downloads of that verison.

**Comment by Schutzhund3** [comment]
![add-type](https://user-images.githubusercontent.com/31139481/121730496-c18ff980-cabd-11eb-9ba0-a1f0ffe52257.png)

I haven't used the [PesterConfiguration] mentioned before, if someone could provide an example?

**Comment by fflaten** [comment]
He meant to execute exactly `[PesterConfiguration]`, it would have displayed some information about the type/class which is part of the assembly. The fact that `Add-Type` fails like that is equally good verification that dll is not loaded. 🙂 

Are you really sure that dll is unblocked? Also try reopening PowerShell after unblocking the dll.
