### ISSUE TITLE
Feature Request: Filter.ExcludeLine Option

### ISSUE THREAD

**Issue by JustinGrote** [pester/Pester#1992]
## Summary of the feature request
The VSCode Proposed Test API has a feature to "hide" tests from running. Currently to translate this to Pester I would have to enumerate all the tests in the blocks and then selectively exclude them. It would be nice if pester would do this for me with an ExcludeLine parameter. Excludes would take precedence over includes.

###  Example (paths abbreviated for clarity):

Line 5 - Describe Block Begin
Line 6 - It Test 1
Line 7 - Context Block Begin
Line 9 - It Test 2
Line 11 - It Test 3

```
Path.Line = '7'
Path.ExcludeLine = '9'
```
Result: Test 3 is run

```
Path.Line = '5,7,9'
Path.ExcludeLine = '9'
```
Result: Test 1 and 3 are run

```
path.line = '5'
path.excludeline = '7'
```
Result: Test 1 is run

**Comment by nohwnd** [comment]
Yeah that should be quite simple. Would you like to PR it? It is mostly about adding the option to `New-FilterObject` and implementing it in the `Test-ShouldRun` filter function. There is already some code for exclusions I think, so there should not be much thinking needed how to handle this.

https://github.com/pester/Pester/blob/main/src/Pester.Runtime.ps1#L2283

https://github.com/pester/Pester/blob/main/src/Pester.Runtime.ps1#L1705-L1724

**Comment by ArmaanMcleod** [comment]
@nohwnd and @JustinGrote I can probably help make a PR for this if it's not already taken 🙂

**Comment by nohwnd** [comment]
@ArmaanMcleod  it is all yours.

**Comment by JustinGrote** [comment]
@ArmaanMcleod if you take a stab at it I'll be happy to review.

**Comment by JustinGrote** [comment]
@ArmaanMcleod great work! I'll be incorporating this into the pester test adapter soon.

**Comment by nohwnd** [comment]
@JustinGrote would another pre-relelase make it easier for you, or are you good with just importing it from source?

**Comment by JustinGrote** [comment]
@nohwnd source is fine for now.
