### ISSUE TITLE
Implement an option to disable TestRegistry

### ISSUE THREAD

**Issue by StephenFerrero** [pester/Pester#2004]
## Summary of the feature request
We are working to run Pester inside Azure Functions, a blocker we have run into is that access to the Windows registry is restricted. When running Pester we receive the following error:

`System.Exception: Was not able to create a Pester Registry key for TestRegistry System.Security.SecurityException: Requested registry access is not allowed.`

This seems related to the TestRegistry feature, which we are not using. Similar to issue #1345

It would be helpful to have the option to disable TestRegistry on Pester runs. We have experimented with this successfully by just removing the following line:
https://github.com/pester/Pester/blob/989dac0620fd1312b4fa24ad111c9a48614f53ae/src/Main.ps1#L940

**Comment by nohwnd** [comment]
Agree with that, we should also be able to disable TestDrive.

**Comment by fflaten** [comment]
What would the configuration be? 

If the plugin-system is made public it would likely require it's own Plugins-configuration section both to add new custom plugins, but also disable built-in to avoid conflict. Should this issue result in two bool options (for now) in a new section maybe?

**Comment by nohwnd** [comment]
Not sure. I don't want to complicate our options for first class plugins with the fact that they are in fact plugins. And I am okay if we later link some options to a more general section in the options. 

It would also be nice to disable TestDrive and enable it for just some files (and same for testregistry). But that is very complicated, and the testdrive overhead is very small already.

**Comment by nohwnd** [comment]
I think we should follow the suite of CodeCoverage (also a plugin), and just make a TestDrive and TestRegistry sections with Enabled = $true, and Path = <the default root path>, options.

**Comment by nohwnd** [comment]
> enable it for just some files but that is very complicated

We could have .TestDrive.Enabled = $true, .TestDrive.Containers = "All | WithRequires". And `#Requires -Pester -TestDrive` in the file. But that is just a possibility that might be added in the future once we think it through. It could be also done via a function to avoid coming up with a custom #requires syntax.

**Comment by nohwnd** [comment]
I did not add the Path. It was not an ask, and we have different path for mac and windows so I would have to add a new concept to the config for that, or have some workaround.
