### ISSUE TITLE
ExpandedPath is incorrect if a period is used in the test name

### ISSUE THREAD

**Issue by JustinGrote** [pester/Pester#2005]
![image](https://user-images.githubusercontent.com/15258962/122473172-555a3d80-cf76-11eb-936e-2b69e3497c35.png)

## Fix
The test name should be validated and throw an error if it includes a period. Alternatively a different delimiter could be used for ExpandedPath like | or some obscure unicode character, but that would probably be more breaking.

## Workaround

Generate your own unique path using Test.Path -join `<customDelimiter>`

**Comment by nohwnd** [comment]
Can you add more details please? I don't see from your example how the path is incorrect? It looks like all the paths are the name of parents joined by `.`. Or am I overlooking something? 

Why should we throw if the name contains a `.`? Expanded path is not meant to be parsed to tokens. That is why there is Path as string[] on the objects, so we get the literal strings that user provided.

**Comment by JustinGrote** [comment]
Yes, that's what I'm doing, just thought I could save some trouble. As long as expandedpath isn't meant to be parsed I suppose this can be a `wontfix`
