### ISSUE TITLE
Script scope variables not defined for tests

### ISSUE THREAD

**Issue by rjmholt** [pester/Pester#2028]
## General summary of the issue

PSScriptAnalyzer [migrated to Pester 5 about a year ago](https://github.com/PowerShell/PSScriptAnalyzer/pull/1444), but recently we've seen [some new test failures in CI](https://github.com/PowerShell/PSScriptAnalyzer/issues/1695).

I wasn't able to reproduce the issue in my local clone, and my suspicion is that my local Pester version (5.1-rc1) doesn't have the issue.

In CI we seem to be using 5.0.2.

I'm working on the fix in https://github.com/PowerShell/PSScriptAnalyzer/pull/1697.

Essentially:

- Initially the issue was [hashtable keys defined with script-scoped variables were null](https://dev.azure.com/powershell/psscriptanalyzer/_build/results?buildId=82028&view=logs&j=c492b3f2-3f7f-545b-9740-4a941d8a8097&t=c5aebf1d-d8d8-5429-6ff5-668d8560bdd2). I fixed this by moving those variables to normal scope under a top-level `BeforeAll` block
- This fixed the issue on most platforms, but I'm now seeing [test case input as null in PowerShell 4](https://ci.appveyor.com/project/PowerShell/psscriptanalyzer/builds/39993854)

It looks like we're using Pester 5.0.2 in PS 4 and I'm wondering what the right solution is here and why it might be behaving differently across different platforms.

**Comment by rjmholt** [comment]
So I've fixed the original issue, but had to duplicate code because some variables were needed in both the discovery and test phases.

Now I'm hitting a strange problem where our Pester tests call a module which calls `Should` and we get something like this:

```console
[-] UseConsistentIndentation.When a multi-line command is given.Should indent properly after line continuation (backtick) character 231ms (225ms|6ms)
 CommandNotFoundException: The term 'Should' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
 at Test-CorrectionExtentFromContent, C:\projects\psscriptanalyzer\Tests\PSScriptAnalyzerTestHelper.psm1:49
 at <ScriptBlock>, C:\projects\psscriptanalyzer\Tests\Rules\UseConsistentIndentation.tests.ps1:286
```

**Comment by rjmholt** [comment]
I managed to find a workaround for this: https://github.com/PowerShell/PSScriptAnalyzer/pull/1697/commits/1f8f79362398a7df0aaae001594a513f985d792f.

**Comment by fflaten** [comment]
> This only happens in PowerShell 4; the tests all pass and run correctly in PS 5.1 and 7 on all platforms.

Thanks. Probably same as #1831. Can you reproduce consistently? Possible to run this in a different CI or server with PSv4? Both issues point to Appveyor WMF4 image it seems.

**Comment by rjmholt** [comment]
Sounds like this is indeed #1831. I don't have easy access to another instance unfortunately.
