### ISSUE TITLE
Feature Request - Exclude paths from code coverage discovery and results

### ISSUE THREAD

**Issue by asears** [pester/Pester#2032]
## Summary of the feature request

Currently there does not appear to be a way to exclude a script from the discovered powershell scripts surfaced in code coverage analysis results.

An example would be a script in the folder is picked up for code coverage, however it is a Pester test harness script or other Powershell script not under test and not requiring coverage.

## How should it work? (optional)

This would introduce a new property to the project CodeCoverageConfiguration.ExcludePaths. It would be used to exclude paths from Code Coverage results.  A PR #2031 has been submitted for the csharp code changes, some assistance would be appreciated on the Powershell implementation of this property and verification of PR / couple backwards compatibility tests failing.

**Comment by beau-witter** [comment]
This is something I would be interested in as well. In this project: https://github.com/vexx32/PSKoans There is a folder "PSKoans\Koans" that is not to be considered as part of code coverage, as that is meant for the user to interact with. There are many other files that do need tests and should be part of code coverage, so a way to specify that path to not be considered would be ideal.

**Comment by fflaten** [comment]
As a workaround you could use `Get-ChildItem -File ...`, filter and provide the array of paths to `CodeCoverage.Paths`

**Comment by LethiferousMoose** [comment]
@fflaten that's more or less what I ended up doing, worked fairly well.

**Comment by nohwnd** [comment]
sorry for the spam, just testing my notification filter. @nohwnd
