### ISSUE TITLE
Sometimes the it clauses in a 'tests.ps1' script fail

### ISSUE THREAD

**Issue by DarkLite1** [pester/Pester#2056]
## General summary of the issue
When running the same test script repetitive it might fail at times but not always. 

## Describe your environment
> Pester version     : 5.3.0 C:\Program Files\WindowsPowerShell\Modules\Pester\5.3.0\Pester.psm1
PowerShell version : 5.1.14393.4530
OS version         : Microsoft Windows NT 10.0.14393.0

## Steps to reproduce

1. Clone repo: https://github.com/DarkLite1/copy-or-move-latest-file.git
2. Run the test script in a loop
```powershell
1..20 | ForEach-Object {   
    Invoke-Pester 'C:\Copy or move latest file.Tests.ps1' -Output Detailed
}
```
Notice that sometimes the it clauses fail and sometimes they all pass. 

## Expected Behavior
Consistent, always pass the tests or always fail the tests.

## Current Behavior
Sometimes failing tests and sometimes not.

## Extra info
Code ran in the latest vscode with the latest PowerShell extension (v2021.8.0)
> Version: 1.59.0 (system setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.14393

**Comment by nohwnd** [comment]
What is the error?

**Comment by DarkLite1** [comment]
Sorry for being a bit unclear. I tried to simplify the example as much as possible to the following code:
```powershell
# test.ps1
BeforeAll {
    $testScript = {
        Param (
            [Parameter(Mandatory)]
            [String]$SourcePath,
            [Parameter(Mandatory)]
            [String]$DestinationPath
        )

        $getParams = @{
            LiteralPath = $SourcePath
            File        = $true
            Force       = $true
            ErrorAction = 'Stop'
        }
        $fileToMove = Get-ChildItem @getParams | 
        Sort-Object LastWriteTime | Select-Object -Last 1

        $copyParams = @{
            Path        = $fileToMove.FullName
            Destination = Join-Path $DestinationPath $fileToMove.Name
            Force       = $true
            ErrorAction = 'Stop'
        }
        Copy-Item @copyParams
    }
    
    $testParams = @{
        SourcePath      = (New-Item 'TestDrive:/A' -ItemType Directory).FullName 
        DestinationPath = (New-Item 'TestDrive:/B' -ItemType Directory).FullName 
    }
}
Describe 'copy only the latest file found in the source folder' {
    BeforeAll {
        @(
            '1.txt', '2.txt', '3.txt', 
            '1.csv', '2.csv', 
            '1.xlsx'
        ) | ForEach-Object {
            New-Item (Join-Path $testParams.SourcePath $_) -ItemType File
        }
    }
    BeforeEach {
        Get-ChildItem $testParams.DestinationPath | Remove-Item
    }
    It 'to the destination folder' {
        . $testScript @testParams
        $actual = Get-ChildItem $testParams.DestinationPath
        $actual | Should -HaveCount 1
        $actual.Name | Should -Be '1.xlsx'
    }
}
```

Execute this script file multiple times and notice successes and failures being mixed:
```powershell
1..30 | ForEach-Object {
    Invoke-Pester 'T:\Test\Brecht\PowerShell\Testie5.ps1' -Output Detailed
}
```
Output:
![image](https://user-images.githubusercontent.com/10828570/130027080-73527346-9c77-4882-a1a9-74d2304aa580.png)

**Comment by nohwnd** [comment]
Most likely ordering by last write time in this: 

```powershell
$fileToMove = Get-ChildItem -LiteralPath $SourcePath -File | 
        Sort-Object LastWriteTime | Select-Object -Last 1
        
```

**Comment by DarkLite1** [comment]
Don't think that's the issue. The file `1.xlsx` is always the last file created and as such also the one with the last `LastWriteTime`. I'm under the impression that for some reason not all files are created when the `It` clause runs.

**Comment by nohwnd** [comment]
Might be, but I think it's rather the last write time, because there is no guarantee that will update immediately, should be easy to see when you output all the sorted files. We should be able to see if there are all, and if they are correctly sorted.

```powershell
$files = Get-ChildItem -LiteralPath $SourcePath -File | 
        Sort-Object LastWriteTime
        
Write-Host ($files.FullName -join "`n")
$fileToMove =  $files | Select-Object -Last 1

```

**Comment by DarkLite1** [comment]
Strange but you are correct. They are all created but sometimes the last tow have the same LastWriteTime and CreationTime to the millisecond. However, one would expect the order in which they are created in the loop to be respected but that's not the case. 

We could simply add `Start-Sleep` to the loop to make sure the times are different but that seems a bit overkill. Hmmm.... thinking about this.

![image](https://user-images.githubusercontent.com/10828570/130189096-67927cdb-f203-4b3f-b395-b7927a28ab46.png)

**Comment by nohwnd** [comment]
> However, one would expect the order in which they are created in the loop to be respected but that's not the case.

Not sure why you'd expect that, but if you need more predictable results, add name as the second property to sort by. That way it will be a deterministic tiebreaker in case there are to items with the same milliseconds.
