### ISSUE TITLE
TestItem during a dry-run should stringify as [NOTRUN] Testname instead of [ERR] TestName

### ISSUE THREAD

**Issue by JustinGrote** [pester/Pester#2057]
## General summary of the issue
Maybe set skipped to true? That may not communicate that it was a dry run and was not skipped as part of the pester logic.
![image](https://user-images.githubusercontent.com/15258962/129974502-aa9d1682-5bc9-4a79-a780-70ec351a7cf9.png)

**Comment by nohwnd** [comment]
Can't repro this on 5.2.0 nor 5.3.0. Can you post a repro?

```powershell
$r = invoke-pester -configuration @{ 
    run = @{ 
        container = (
            new-pestercontainer -scriptblock {
                describe "a" {
                    it "b" {

                    }
                }
            });
        skiprun   = $true
        passthru  = $true
    }
}

$r.Tests[0].ToString()
```

```
Tests Passed: 0, Failed: 0, Skipped: 0 NotRun: 1
[ ] b
```

**Comment by JustinGrote** [comment]
@nohwnd my bad, this is happening in my shim prior to it being formatted on the output, closing.
