### ISSUE TITLE
Make TestDrive available during Discovery

### ISSUE THREAD

**Issue by tbergstedt** [pester/Pester#2058]
## Summary of the feature request
Maybe this is a bit of an edge case, but I'm having a bit of a struggle setting up Pester to 'test itself', i.e. test scripts that contain Pester code. I'm using Pester notation to verify that our source code abides to certain standards and rules we have internally.

I think a lot of my problems boil down to the **TestDrive** functionality not being available until **Run** phase.

The script to test uses data-driven functionality, and as I've gathered it, this means that a lot of setup needs to be placed inside the `BeforeDiscovery` block:
```powershell
BeforeDiscovery {
   $itemsToCheck = ... # Some functionality to determine what to test dynamically
}
Describe 'Test items' {
   It "'<_>' should be OK" -ForEach $itemsToCheck {
      ...
   }
}
```

The script to verify the above code looks something like this (simplified):
```powershell
BeforeAll {
   # Set up test data to verify on
  $projectFileContents = @'
<?xml version="1.0" encoding="utf-8"?>
<Project>
   <!-- some test data -->
</Project>
'@

   $projectFile | Set-Content "$TestDrive\project.xml"   
}

Describe 'Verify Test Items' {

   It 'Should Verify execution of Test Items' {
      $pesterContainer = New-PesterContainer -Path 'TestItems.ps1' -Data @{File="$TestDrive\project.xml"}

       $result =  Invoke-Pester -Container  $PesterContainer -PassThru
   }
}
```

Now since the original script has to do a lot of setup inside `BeforeDiscovery`, it doesn't work to use **TestDrive** in the test script, since that isn't available until after, correct? At least, I have not been able to use it this way.

I ended up creating my own `$MyTestDrive`, which I then have to make sure gets removed within the `AfterAll` block, so it is possible to work around. But having the testdrive available from the beginning would simplify things. Is this possible?

**Comment by nohwnd** [comment]
Could you post an example of what you are actually trying to do, please? Your example code not mention TestDrive at all.

**Comment by tbergstedt** [comment]
Of course added to original text now, sorry about that.

**Comment by fflaten** [comment]
It looks like the biggest issue here is the attempt to use Pester inside Pester considering that's not supported in the same process. You could do it with a PSJob in the outer script as jobs run in a new process (no state conflict).

The outer testfile will generate some data in BeforeAll and pass it to the inner script using absolute paths (as `$TestDrive` will be different inside the job).

Inner.Tests.ps1
```powershell
param($File)

BeforeDiscovery {
   $itemsToCheck = ([xml](Get-Content $File)).Project.Node
}
Describe 'Test items' {
   It "'<_.name>' should be OK" -ForEach $itemsToCheck {
      1 | Should -Be 1
   }
}
```

Outer.Tests.ps1
```powershell
BeforeAll {
    # Set up test data to verify on
    $projectFileContents = @'
<?xml version="1.0" encoding="utf-8"?>
<Project>
    <!-- some test data -->
    <Node name="a" />
    <Node name="b" />
    <Node name="c" />
</Project>
'@
    $projectFileContents | Set-Content "$TestDrive\project.xml"
}

Describe 'Verify Test Items' {

    It 'Should Verify execution of Test Items' {
        $modulePath = (Get-Module Pester).Path
        $result = Start-Job {
            Import-Module $using:modulePath
            $pesterContainer = New-PesterContainer -Path 'demoIssue2058Inner.Tests.ps1' -Data @{ File = "$using:TestDrive\project.xml" }
            Invoke-Pester -Container  $PesterContainer -PassThru -Output Detailed # You might want to use -Output None to avoid mixing the output
        } | Receive-Job -Wait

        $result.TotalCount | Should -Be 3
        $result.FailedCount | Should -Be 0
    }
}
```

**Comment by tbergstedt** [comment]
Works much better now with verification done within its own scope - thanks! The only thing I had to change was how to retrieve the Pester module path. Since I require a certain version of Pester (using a `#requires` statement), I had to make sure the module is imported using the module manifest, instead of just the script file:
```powershell
    $pesterModulePath = (Get-Module Pester).Path -replace '\.psm1','.psd1'
```
