### ISSUE TITLE
Mock of Cmdlet from external module (e.g. Az module) does only work if the module is actually present

### ISSUE THREAD

**Issue by J0F3** [pester/Pester#2065]
## General summary of the issue
I am not sure if this is really an issue or if it is the desired behavior however I found it a bit strange and could not find anything in the documentation so I thought I give it a shot here.  

I want to test at script module (.psm1 file) which uses some command from the Az (Azure PowerShell) Module which I have mocked in the test. So I assumed the teste would be run independently from the Az module. But I discovered that the test actually only run if the Az module is installed. Otherwise they fail with  "Could not find Command" even the command should be actually mocked.

## Describe your environment

Pester version     : 5.3.0 /home/jfeller/.local/share/powershell/Modules/Pester/5.3.0/Pester.psm1
PowerShell version : 7.1.4
OS version         : Unix 5.10.16.3

## Steps to reproduce

Script Module with a Function which uses some commands form the Az module internally (pesterTest.psm1)
```powershell
function Test-Mock {
    Get-AzAccessToken
}   
```

Testing the module and the `Test-Mock` function while mocking the Get-AzAccessToken function:
```powershell
BeforeAll {
    Import-Module "$PSScriptRoot\mockTest.psm1"
}

Describe "Mocking external cmdlets" {

    Context " when mocking a call Get-AzApiManagement" {


        It " should mock" {
            function Get-AzAccessToken {}
            Mock -CommandName Get-AzAccessToken -MockWith {
                Write-Host "Mocked call to Get-AzAccessToken"
                return $null
            } -ModuleName pesterTest
        
            Write-Host "Going to call Get-AzAccessToken"
            Test-Mock
        }
    }
}
```

## Expected Behavior

I would expect that the test works independently if the Az Module is installed or not.
(I assumed defining `Get-AzAccessToken`  as an empty function in the test should make it possible to mock the command even if the Az module ist not present/loaded/installed).

## Current Behavior

It does not work. The test fails with `Could not find Command Get-AzAccessToken` and does not use the mock.
![image](https://user-images.githubusercontent.com/12759579/130497675-f7a91255-833c-442a-9557-1a4c2baae254.png)

## Possible Solution? (optional)

After experimenting around a bit I found out that the following works (Defining a new module and add the empty `Get-AzAccessToken` function to it.):

```powershell
BeforeAll {
    Import-Module "$PSScriptRoot\mockTest.psm1"
}

Describe "Mocking external cmdlets" {

    Context " when mocking a call Get-AzApiManagement" {


        It " should mock" {
            New-Module -ScriptBlock {function Get-AzAccessToken {}}
            Mock -CommandName Get-AzAccessToken -MockWith {
                Write-Host "Mocked call to Get-AzAccessToken"
                return $null
            } -ModuleName mockTest
        
            Write-Host "Going to call Get-AzAccessToken"
            Test-Mock
        }
    }
}
```
![image](https://user-images.githubusercontent.com/12759579/130498270-1ea56e12-c57e-40b7-8758-b0b3f6996d31.png)

While this seems to work multiple questions keeps with me:

-  Why does that work at all? 😊
-  Is this the correct why to solve the described problem? 
-  Is it intended at all that the pester tests can work without any external module (the Az module in my case) or should such external modules be installed anyway. Even if all the command exported by the external module get mocked away in the tests?
For me it seems to be a bit strange that I need to install some extra modules only to run the unit test of my script module because I had assume that mocking does make my test independent form external dependencies....

Any inputs or explanations are much welcome! 😊

Thx a lot!

**Comment by fflaten** [comment]
Yes, this is by design. When you mock you create a copy of a function (same parameters etc) but with your own controlled logic/response. If the original function isn't available, Pester wouldn't know what to impersonate.

Creating a dummy-function prior to mocking it is an alternative if you can't import the module. The downside is that your fake function might get out of sync with the real Az function's parameters which would give false positives in your test (tests pass while real life usage fails).

**Comment by J0F3** [comment]
Thank you @fflaten for the explanations. This makes sense.

What irritated me was that only creating the dummy-function was not enough. I must also define a dummy-module with `New-Module` in which I created the dummy-function. (see my possible solution above). That was the main reason why I decided to ask here. 
I have used the method with the dummy-function in the past already but I had never needed the `New-Module` part.

**Comment by fflaten** [comment]
`Mock` looks for the original (fake) function inside the specified mockTest-module, but can't find it. Functions created in the script-scope, where the tests execute, can't be seen inside other modules. Imported modules however are globally available for everyone.

You could also do this:

```powershell
It " should mock" {
            InModuleScope mockTest { function script:Get-AzAccessToken {} }
            Mock -CommandName Get-AzAccessToken -MockWith {
                Write-Host "Mocked call to Get-AzAccessToken"
                return $null
            } -ModuleName mockTest
        
            Write-Host "Going to call Get-AzAccessToken"
            Test-Mock
        }
```

**Comment by J0F3** [comment]
Ah now I got it. Thanks @fflaten for answer my stupid questions! 😄 

So, I am going to close this now as everything works as desired. 👍
