### ISSUE TITLE
Clean up Mocking framework code

### ISSUE THREAD

**Issue by dlwyatt** [pester/Pester#208]
Mock.ps1 is becoming a bit of a mess.  There are potentially three different modules / session states in play on any given mock now:
1. Where the mocked function was originally defined (only applies to mocks of functions and other PowerShell code.)  This is where the code from the original function's DynamicParam block must execute, so it can continue to resolve things like script-scope variables.
2. Where the call to the function is coming from.  This is where the mocking bootstrap function gets injected.  At the moment, the bootstrap function script block must be bound to this same scope, because it relies on $ExecutionContext.SessionState.Module in order to pass on the correct information to Invoke-Mock.
3. Where the test code is currently running.  This could be out in the main powershell session, or in a module (depending on whether InModuleScope is currently in effect.)  The -MockWith and -ParameterFilter blocks should be executed in this scope, so they can resolve variables defined in the test scripts.  (There is currently an issue where the -MockWith block is being executed in scope #2 if the -ModuleName parameter is used when calling Mock.  There's a separate issue open to fix this in v4, as it's technically a breaking change.)

The mocking code has grown organically quite a bit since the first work on v3.0 was started, and it's getting difficult to follow these concepts.  These notes will help keep everything straight later on when we try to express it more cleanly in the code.

**Comment by it-praktyk** [comment]
@dlwyatt, I expect that can be closed now. Am I right?

**Comment by dlwyatt** [comment]
It's not done, but we probably don't need to leave an issue open either.  I've put it on my own to-do list.
