### ISSUE TITLE
Error after successful Pester run in teardown

### ISSUE THREAD

**Issue by efie45** [pester/Pester#2083]
## Question
I'm getting the following error after a 'successful' run of my pester tests. I can trace everything through the last AfterAll  and I am getting the expected results inside my scripts. However, after the final AfterAll closing bracket if I "step-into" with the debugger I am dropped into Pester.psm1 and end up walking through the teardown until I get this error:

```
  Modules/Pester/5.3.0/Pester.psm1:1208:17
Line | 1208 
     |                  $Test.ErrorRecord.AddRange($result.ErrorRecord)
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "AddRange" with "1" argument(s): "Value cannot be null.
     | (Parameter 'collection')"
```
If I break on line 1208 inside the Pester teardown I see these two lines of code, which is where the error occurs:

```powershell
                $Test.StandardOutput = $result.StandardOutput
                $Test.ErrorRecord.AddRange($result.ErrorRecord)
```

The variable ```$Test``` shows that the test passed and there are no errors:

```
> $Test
Result            : 
ErrorRecord       : {}
StandardOutput    : 
Duration          : 00:00:00
ItemType          : Test
Id                : 
...
Tag               : 
Focus             : False
Skip              : False
Block             : [ ] Block
First             : True
Last              : True
Include           : False
Exclude           : False
Explicit          : True
ShouldRun         : True
StartLine         : 44
Executed          : True
ExecutedAt        : 9/16/2021 11:12:54 AM
Passed            : True
Skipped           : False
UserDuration      : 00:00:00
FrameworkDuration : 00:00:00
PluginData        : {Mock}
FrameworkData     : {Runtime}
```

And the ```$result``` variable shows that the run was also successful:

```
> $result

True
True

Success ErrorRecord StandardOutput
------- ----------- --------------
   True {}     
```

Can someone please help me figure out what's going on here? I'm at my absolute wits end and have been trying to figure this out for a couple of days now. 

**Environment data**
Pester version     : 5.3.0 /Users/USER/.local/share/powershell/Modules/Pester/5.3.0/Pester.psm1PowerShell version : 7.1.3                                                                         OS version         : Unix 11.0.0

**Comment by nohwnd** [comment]
$result is supposed to be just a single object:

```
Success ErrorRecord StandardOutput
------- ----------- --------------
   True {}     
```

But from your output it looks like it is an array of 3 items, boolean true, boolean true, the actual result object.

If you do $result[0] do you see true? If you do $result[2] do you see the object? 

This looks like some stray output is ending up in the $result object, sadly those are the worst bugs to debug. Can you post a repro? If not maybe I can craft a collection that will report, stop ad debugger, as soon as boolean enters it, and create a branch for you so you can collect the info.

One last question, does the run fail? How exactly that looks like? I am just making sure that even in this weird scenario we output some kind of error.

**Comment by efie45** [comment]
Interestingly enough, the run appears to succeed even though the test shows as failed with a [-] indicator. 

```
[-] Describe My Test
  ArgumentNullException: Value cannot be null. (Parameter 'collection')
  MethodInvocationException: Exception calling "AddRange" with "1" argument(s): "Value cannot be null. (Parameter 'collection')"
  
Tests completed in 130.95s
Tests Passed: 1, Failed: 0, Skipped: 0 NotRun: 0
```

It was failing like this even if I didn't have any Should assertions after running my script. 

It turns out that something in my script was returning True back to standard output that I wasn't catching. 

Is this how it is supposed to work though? If a script has standard output that isn't assigned to anything when the script is run is the test supposed to throw an error?

**Comment by fflaten** [comment]
> Is this how it is supposed to work though? If a script has standard output that isn't assigned to anything when the script is run is the test supposed to throw an error?

No, output is captured and stored in the StandardOutput-property for the test in Pester's result-object.

**Comment by nohwnd** [comment]
Yeah I would really like to see that code that is erroring out like this. Looks like Pester is not capturing all the output that the user can output, which interferes with the error counting, and that is a serious bug.

**Comment by efie45** [comment]
I will try to create an example project that I can share to recreate and will post here in the next couple of days.

**Comment by efie45** [comment]
FYI I have been limited on time on this due to some new priorities at work. So far I've been unable to recreate aside from the original code but I'm still looking into it.

**Comment by fflaten** [comment]
@efie45 closing as we're unable to repro. Will reopen if you can provide a sample as discussed. 🙂
