### ISSUE TITLE
Test fails when no breakpoint is set, test passes with a breakpoint set

### ISSUE THREAD

**Issue by DarkLite1** [pester/Pester#2092]
## General summary of the issue
This is a bit of strange bug but it is consistent. When we run `Invoke-Pester` from the command line in  a new PowerShell terminal the test fails. However, when we place a breakpoint within vscode and run the test then with `F5` or `Invoke-Pester` the test passes.

## Describe your environment
```
Pester version     : 5.3.1 C:\Program Files\WindowsPowerShell\Modules\Pester\5.3.1\Pester.psm1
PowerShell version : 5.1.14393.4583
OS version         : Microsoft Windows NT 10.0.14393.0
```

VS Code:
```
Version: 1.61.0 (system setup)
Commit: ee8c7def80afc00dd6e593ef12f37756d8f504ea
Date: 2021-10-07T18:13:09.652Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.14393
```
## Steps to reproduce
1. Clone the module and its test file from [GitHub](https://github.com/DarkLite1/pester-test-module)
2. In VS Code right click the folder with the script files an choose `Open in Integrated Terminal`
3. Run `Invoke-Pester` and see the test fail:
![image](https://user-images.githubusercontent.com/10828570/137141420-be8c2a6a-a148-471c-ae52-092493345dab.png)
4. Place a breakpoint in the file `Toolbox.PermissionMatrix.Tests.ps1` within the `It` clause and press `F5` to start the tests
5. Notice the test is now successful:
![image](https://user-images.githubusercontent.com/10828570/137141713-e3833bea-3ec7-459c-a206-c7be640d4ea5.png)

Side issue: the prompt is not correct and says `PS>` as visible in the screenshot. Hitting enter after the incorrect prompt does bring us back to the correct one:
![image](https://user-images.githubusercontent.com/10828570/137141889-7e168717-aac9-44da-a1d1-448608eba8d2.png)

## Expected Behavior
We expect the test to always pass or always fail, with or without breakpoints set.

## Current Behavior
The test fails when not using a breakpoint for the editor to stop. When there is a breakpoint set, and VS Code stops at the breakpoint, the test is always successful.

**Comment by nohwnd** [comment]
> When there is a breakpoint set, and VS Code stops at the breakpoint, the test is always successful. 

Just to understand. Always meaning when the value is correct and breakpoint is hit. Or even when the value is incorrect?

**Comment by DarkLite1** [comment]
@nohwnd just tested that for you. When a breakpoint is set the test is only successful when the value is correct. So this works as designed.

**Comment by fflaten** [comment]
You forgot to pass `$moduleName` to the run-phase in the image above. So the mocks are created with `-ModuleName $null`. 

Try updating the Describe line to `Describe 'Get-ADUserPrinci....' -ForEach @{ moduleName = $moduleName }`

**Comment by DarkLite1** [comment]
OMG that fixed it! Thank you @fflaten , I couldn't have figured this out myself.

Question for the team (@nohwnd): should the behavior between running with `F5` in VS Code or simply running `Invoke-Pester` not be consistent? This would avoid troubleshooting issues like this.

**Comment by fflaten** [comment]
You could enable the "Create Temporary Integrated Console" setting in the powershell extension, but come to think of it we might still get the problem.

When using F5 or interactive execution (run file directly in console), everything before the first Describe will be added to the session. I'd recommend using the code lens links (Run/Debug tests) or using `Invoke-Pester`. That way you should always be same iirc.

**Comment by nohwnd** [comment]
> Behavior of F5 in vscode is part of the Powershell-extension, it's not Pester-specific.

True. Maybe we should look into making this Pester aware as well, based on the filename pattern, which is *.Tests.ps1 in most cases. We could probably add an extra scope, or better run it via Invoke-Pester. But we should open a discussion in the extension repo with a list of issues we are having, and a proposal of a fix. Anyone wants to do that?

**Comment by fflaten** [comment]
> But we should open a discussion in the extension repo with a list of issues we are having, and a proposal of a fix. Anyone wants to do that?

We should make a issue/epic/milestone here first to track them. 🙂 Because this particular issue might be more a general problem with interactive execution. Especially when dot-sourcing `*.tests.ps1` files like VSCode does here because the variables will corrupt the session (variables will be session-wide and inherited to Discover and Run). 

> It's outside of Pester's control. Using F5 in vscode runs the script directly. Code in BeforeDiscovery (or in the root of the script) will then be invoked in the session scope and become variables at the level/scope which everything else will inherit

I didn't really see the forest for the trees here. We **can** control `BeforeDiscovery` and we should,  by adding the check for interactive execution (currently in `Describe` + `Context`) to this block also. It won't fix root-level code, but we already discourage that in docs.
