### ISSUE TITLE
Strange Behaviour When Mocking Import-CSV

### ISSUE THREAD

**Issue by jsmythsci** [pester/Pester#2099]
## General summary of the issue
I have a script that we use for a DNS CI process. The script reads records from a version-controlled CSV file and compares the expected records against the live records in our DNS provider's system and then makes the necessary changes.

I am trying to Mock `Import-CSV` but I am getting strange results when the mocked version is called from within the script I want to test.

## Describe your environment
Pester version     : 5.3.1 C:\Program Files\WindowsPowerShell\Modules\Pester\5.3.1\Pester.psm1
PowerShell version : 5.1.18362.1474
OS version         : Microsoft Windows NT 10.0.18363.0

## Steps to reproduce
I don't know how to reproduce it without completely recreating my test environment, but let's start with this, the full `Context` block:

```powershell
    Context 'Update job completes as ERROR' {
        BeforeAll {
            Mock Get-LiveDnsRecord {
                @(
                    [PSCustomObject]@{
                        id = 'A_91763'
                        name = 'foo'
                        ttl	= 300
                        type = 'A'
                        data = 127.0.178.54
                        comment = 'Something pithy!'
                    }
                )
            }

            Mock Import-Csv {
                @(
                    [PSCustomObject]@{
                        name = 'foo'
                        ttl	= 9001
                        type = 'A'
                        data = 127.0.178.54
                        comment = 'Something else...'
                    }
                )
            }

            Mock Set-LiveDnsRecord {
                Process {
                    [PSCustomObject]@{
                        status = 'ERROR'
                        error = @{
                            details = 'You can''t do that, friend!'
                            code = 500
                            message = 'Bad Request'
                        }
                    }
                }
            }
        }

        It 'Throws an exception' {
            # This works. If I purposely fail the assertion the It stops after this line.
            (Import-CSV 'Somefile.csv').name | Should -BeExactly 'foo' -Because 'If the mock isn''t working...'
            $shouldParams = @{
                Because = 'API job failures should fail the Pipeline'
            }
            # -Not is here because I am trying to validate the script's current behaviour with this test
            { & $scriptPath @{ 'DomainName' = 'foo.com' } } | Should -Not -Throw @shouldParams
        }
    }
```

## Expected Behavior
Given my environment, the above test should pass.

## Current Behavior
The above test throws an exception because it is reaching a section of code that should not be reachable given the test scenario. The first `Should` confirms that the `Mock` seems to be working as intended but when I debug and look at what `Import-CSV` returns inside the script under test, I find an object that looks like this:

```none
name    : foo.System.Collections.Hashtable
ttl     : 9001
type    : A
data    :
comment : Something else...
```
The values for `ttl`, `type` and `comment` are correct, but `name` and `data` are incorrect. The result is that, instead of seeing a single record that needs to be updated, the script figures this is a new record and throws an exception because a DNS record cannot be created with a $null data value.

When I invoke `Import-CSV` from the debug sessions, I get this:

```none
[DBG]: PS C:\Users\jasons\Source\git\SciPS\Tests> Import-CSV .

Mock: Mock for Import-Csv was invoked from block Process, resolving call history and behaviors. 
Mock: Getting all defined mock behaviors in this and parent scopes for command Import-Csv. 
Mock: We are in a test. Finding all behaviors in this test. 
Mock: Found no behaviors for 'Import-Csv' in this test. 
Mock: Finding all behaviors in this block and parent blocks.
Mock: Found behaviors for 'Import-Csv' in 'Update job completes as ERROR'. 
Mock: Filtering behaviors for command Import-Csv, for target module $null (Showing all behaviors for 
this command, actual filtered list is further in the log, look for 'Filtered parametrized behaviors:' 
and 'Filtered default behaviors:'): 
Mock: Behavior is a default behavior from script scope, saving it:
     Target module: $null
     Body: { @(
                    [PSCustomObject]@{
                        name = 'foo'
                        ttl     = 9001
                        type = 'A'
                        data = 127.0.178.54
                        comment = 'Something else...'
                    }
                ) }
     Filter: $null
     Default: $true
     Verifiable: $false
Mock: We are in a test. Returning mock table from test scope. 
Mock: Filtered parametrized behaviors:
$null
Mock: Filtered default behavior:
     Target module: $null
     Body: { @(
                    [PSCustomObject]@{
                        name = 'foo'
                        ttl     = 9001
                        type = 'A'
                        data = 127.0.178.54
                        comment = 'Something else...'
                    }
                ) }
     Filter: $null
     Default: $true
     Verifiable: $false
Mock: Finding behavior to use, one that passes filter or a default: 
Mock: { 
                @(
                    [PSCustomObject]@{
                        name = 'foo'
                        ttl     = 9001
                        type = 'A'
                        data = 127.0.178.54
                        comment = 'Something else...'
                    }
                )
             } is a default behavior and will be used for the mock call.
Mock: Executing mock behavior for mock Import-Csv.


name    : foo
ttl     : 9001
type    : A
data    :
comment : Something else...

Mock: Behavior for Import-Csv was executed.
```

**Comment by jsmythsci** [comment]
As I was typing this up I had the idea of modifying the `Mock` to explicitly wrap all values as strings and that worked.

I will leave this open, though, because I am not sure whether or not this should be considered a bug.

**Comment by fflaten** [comment]
That corrupt object looks weird. Are you sure you looked at the object immediately after the mock created it? Not before e.g. any custom code could modify it in the same pipeline etc.?

`Import-CSV` always returns string properties, so any mock not doing might break your remaining code. I don't think this was Pester-related as the code worked fine when the mock returned a properly mocked object as you mentioned.

**Comment by jsmythsci** [comment]
Thank you for the feedback @fflaten.

There are only 2 references to the variable that holds the source records: variable assignment from `Import-CSV` and then a foreach loop that iterates over the resulting array:

```powershell

[PSCustomObject[]]$sourceRecords = Import-Csv (Join-Path -Path $csvPath -ChildPath "$DomainName.csv") -ErrorAction Stop

<#
Some stuff that doesn't touch $sourceRecords here...
#>

foreach ($sr in $sourceRecords) {
    # loop stuff here
    # no modification to $sourceRecords inside the loop
}
```

I have been checking `$sourceRecords` after the `foreach` loop, but I will check again immediately after variable assignment.

Meantime, for what it's worth, what the script is doing after the loop demonstrates that the value is corrupted inside the `foreach` loop. (I.E., instead of finding 1 record to update it is finding 1 record to remove and 1 to add.)
