### ISSUE TITLE
Dot Sourcing in test fixture not practical for all scripts

### ISSUE THREAD

**Issue by aarismendi** [pester/Pester#21]
See SO question about this issue here: http://stackoverflow.com/questions/10540632/is-it-possible-to-include-functions-only-without-executing-the-script

A script such as the following is not we'll suited to be dot sourced in a test fixture because it has mandatory parameters and code not inside of functions that should not be executed but does get executed.

``` powershell
[cmdletbinding()]
param ( 
    [Parameter(Mandatory=$true)]
        [string] $MyInput
)

function Show-Input {
    param ([string] $Incoming)
    Write-Output $Incoming
}

function Save-TheWorld {
    #ToDo
}

Write-Host (Show-Input $MyInput)
```

**Comment by Nova1089** [comment]
In case it helps anybody, you can add this little incantation to BeforeAll to import functions from a script without executing it.

```
function Get-Functions($filePath)
{
    $script = Get-Command $filePath
    return $script.ScriptBlock.AST.FindAll({ $args[0] -is [Management.Automation.Language.FunctionDefinitionAst] }, $false)
}

Get-Functions ScriptPath.ps1 | Invoke-Expression
```
