### ISSUE TITLE
Casting hashtable to PesterConfiguration fails to convert ['Run']['Path'] when its an ArrayList

### ISSUE THREAD

**Issue by splatteredbits** [pester/Pester#2100]
## General summary of the issue
When casting a hashtable to a `PesterConfiguration` object, `Collections.ArrayList` objects aren't converted. Properties retain their default value.

## Describe your environment
```
Pester version     : 5.3.1 C:\********\PSModules\Pester\5.3.1\Pester.psm1
PowerShell version : 7.1.5
OS version         : Microsoft Windows NT 10.0.19043.0
```

## Steps to reproduce
This code:
```
$paths = [Collections.ArrayList]::New();
[void]$paths.Add('one')
[void]$paths.Add('two')
[void]$paths.add('three')
([PesterConfiguration]@{ Run = @{ Path = $paths } }).Run.Path
```
outputs 

```

Default Description                                                                                 Value
------- -----------                                                                                 -----
{.}     Directories to be searched for tests, paths directly to test files, or combination of both. {.}
```

As you can see, the value is `{.}`. I expected the value to be `{one, two, three}`.

Now, normally, this wouldn't be a problem. Just case `$paths` to a `[String[]]` when assigning it to the `Paths` property. Unfortunately, this doesn't work if you're running Pester in a background job. PowerShell converts *all* arrays passed to a background job to a `Collections.ArrayList` object:

```
$array = @('one','two','three')
Start-Job { ($using:array).GetType() } | Receive-Job -Wait -AutoRemoveJob
```
returns
```

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     ArrayList                                System.Object
```

## Expected Behavior
I would expect that when converting a hashtable to a `PesterConfiguration` object, Pester handles when an object is an array list or maybe any other type of enumerable.

## Current Behavior
Values that are `Collections.ArrayList` are treated as not set.

## Possible Solution? (optional)

```
if( $value -is [IEnumerable] )
{
   $convertedValue = $value | Write-Output
}
```

**Comment by fflaten** [comment]
Thanks. This isn't specific to configuration casted from dictionaries. StringArray configuration-options like `Run.Path` only support conversion/casting from values or arrays of `string` or `PathInfo` atm. Attempting to use `ArrayList`, `List` etc would've thrown if you'd tried it directly on a `PesterConfiguration`-object. Ex.

```powershell
> $l = [System.Collections.Generic.List[string]]::new(); $l.Add("a"); $l.Add("b")
> $a = [System.Collections.ArrayList]::new(); [void]$a.Add("c"); [void]$a.Add("d")
> $c = New-PesterConfiguration

> $c.run.Path = $a
SetValueInvocationException: Exception setting "Path": "Cannot convert the "System.Collections.ArrayList" value of type "System.Collections.ArrayList" to type "Pester.StringArrayOption"."

> $c.run.Path = $l
SetValueInvocationException: Exception setting "Path": "Cannot convert the "System.Collections.Generic.List`1[System.String]" value of type "System.Collections.Generic.List`1[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]" to type "Pester.StringArrayOption"."
```

> Now, normally, this wouldn't be a problem. Just case `$paths` to a `[String[]]` when assigning it to the `Paths` property. Unfortunately, this doesn't work if you're running Pester in a background job. PowerShell converts _all_ arrays passed to a background job to a `Collections.ArrayList` object:

Yeah that conversion is weird, especially considering serialization using `Export/Import-CliXml` doesn't reproduce it.
I don't understand why you say the explicit casting to string-array can't be used as a workaround. `Start-Job { ($using:array).ToArray() } | Receive-Job -Wait -AutoRemoveJob` should work. Or you could create and pass the whole `PesterConfiguration`-object to the job using Pester 5.3+.
