### ISSUE TITLE
Windows Defender marks Pester as malicious

### ISSUE THREAD

**Issue by adricl** [pester/Pester#2104]
## General summary of the issue
So when I import Pester Windows Defender is picking it up as a virus "[Trojan:PowerShell/Fleisnam.A](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aPowerShell%2fFleisnam.A&threatid=2147742186)"

```
PS D:\Runbooks> Import-Module Pester -Passthru
At C:\Program Files\WindowsPowerShell\Modules\Pester\5.3.1\Pester.psm1:1 char:1
+ # file src\functions\Pester.SafeCommands.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
This script contains malicious content and has been blocked by your antivirus software.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ScriptContainedMaliciousContent

Import-Module : The module to process 'Pester.psm1', listed in field 'ModuleToProcess/RootModule' of module manifest
'C:\Program Files\WindowsPowerShell\Modules\Pester\5.3.1\Pester.psd1' was not processed because no valid module was
found in any module directory.
At line:1 char:1
+ Import-Module Pester -Passthru
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (Pester:String) [Import-Module], PSInvalidOperationException
    + FullyQualifiedErrorId : Modules_ModuleFileNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
```

## Describe your environment

Pester version     :
PowerShell version : 5.1.19041.1237
OS version         : Microsoft Windows NT 10.0.19043.0

## Steps to reproduce

```powershell
    Import-Module Pester -Passthru
```

## Expected Behavior
Not be picked up as a virus

## Current Behavior
Pickup as a virus
![image](https://user-images.githubusercontent.com/3646505/141233794-e6f7f190-3300-4aaf-b0b5-fcd430b57118.png)

## Possible Solution? (optional)
I am not sure why Safe Command is being picked up as a virus.

**Comment by nyanhp** [comment]
It is not only the PassThru switch, it also happens when importing it normally. It seems to have originated from updated Defender AV signatures that go haywire. My signatures are version 1.353794.0 from Nov 11th.

**Comment by alagoutte** [comment]
get the same issue...

**Comment by rafabu** [comment]
confirming, that 1.353.794.0 detects and blocks Pester as being infected with `Trojan:PowerShell/Fleisnam.A`

**Comment by potatoqualitee** [comment]
I am as well for versions 5.3.1, 5.3.0, 5.2.2, 4.10.0 and 3.4.6 but not 3.4.0 (which was built-in and signed by Microsoft)

**Comment by davidwallis3101** [comment]
I'm also seeing this issue, 5.3.1 here - or it was until it got quarantined

**Comment by nohwnd** [comment]
It has been reported to the responsible team and they are working on it.

**Comment by maoyalu** [comment]
Same issue.

Security Intelligence Version:
1.353.810.0 (latest at the moment)

**Comment by mike-loux-planview** [comment]
Yak Shaving for Fun and Profit.™

**Comment by Marc013** [comment]
> Same issue.
> 
> Security Intelligence Version: 1.353.810.0 (latest at the moment)

The same for me :-(

_Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.353.818.0)_

**Comment by belibug** [comment]
Oh boy, this got picked by Enterprise Defender, broke code testing. 
Windows 11, PowerShell 7.2, Pester 5.3.1

**Comment by mverbaas** [comment]
Yes, we're experiencing the same.

**Comment by TheWelshFifer** [comment]
We are seeing the same.  Raise a ticket with unified support.

**Comment by ronhowe** [comment]
> It has been reported to the responsible team and they are working on it.

Any sense if this is a real issue or a false positive?

I'd like to know how likely my day is going to be ruined tomorrow. :)

**Comment by SteveGilham** [comment]
> Any sense if this is a real issue or a false positive?

Embrace the healing power of 'and' -- it's correctly spotting that Pester is an engine for taking external text (the test you write) and interpreting it as PowerShell code which is the "this program ... executes commands" part; it just happens that this is its entirely benign intent, and the scrutiny should be placed on the inputs instead.  This is a truly wicked problem to resolve.

**Comment by TheWelshFifer** [comment]
Microsoft support confirmed that they have re-created the issue.  Awaiting feedback.

**Comment by ninmonkey** [comment]
### What triggered it

- I was in the Pwsh Integrated Debug Terminal [**PSIC**]
- I ran this silly script (in the term, not the editor)
- `Should` had been unused at that point, so I tried to import
- The import showed the virus error


```ps1
& {

        Get-Culture 'en-gb' -ea stop
        Get-Item -ea stop 'sdfsd'
        $false | Should -be $true -because 'Should never reach here'
    }
```

### environment

| . | Version                          |
| -------- | ---------------------------------------- |
| code-insiders | 1.62.0-insider | 
| Commit   | 284e0db6c4cac1e557a43cd6691babdaafc2e1a9 |
| Date     | 2021-10-12T05:45 14.621Z                 |
| Electron | 13.5.1                                   |
| Chrome   | 91.0.4472.164                            |
| Node.js  | 14.16.0                                  |
| V8       | 9.1.269.39-electron.0                    |
| OS       | Windows_NT x64 10.0.19043                |


### Addons

| Name                                           | Version   |
| ---------------------------------------------- | --------- |
| GitHub.vscode-pull-request-github              | 0.32.0    |
| justin-grote.powershell-extension-pack         | 0.0.5     |
| ms-vscode.live-server                          | 0.2.9     |
| ms-vscode.powershell                           | 2021.10.2 |
| ms-vscode.powershell-preview                   | 2021.8.3  |
| ms-vscode.test-adapter-converter               | 0.1.4     |
| PowerQuery.vscode-powerquery                   | 0.1.23    |
| pspester.pester-test                           | 2021.10.2 |
| redhat.vscode-xml                              | 0.18.1    |
| redhat.vscode-yaml                             | 1.2.0     |
| TylerLeonhardt.vscode-inline-values-powershell | 0.0.5     |
| TylerLeonhardt.vscode-pester-test-adapter      | 0.0.23    |
| vscode-icons-team.vscode-icons                 | 11.7.0    |



![image](https://user-images.githubusercontent.com/3892031/141372226-fe1cb5dd-8e3e-4881-b398-99f38b9953ad.png)

**Comment by mkht** [comment]
Security Intelligence Version: **1.353.849.0** may have fixed the issue.
Pester can now load properly in my environment.

**Comment by maoyalu** [comment]
Confirmed that it is fixed in Intelligence version 1.353.849.0

**Comment by ronhowe** [comment]
![image](https://user-images.githubusercontent.com/5210043/141390175-0da3fa4b-da8e-4bad-8282-9a3c88eeb595.png)

![image](https://user-images.githubusercontent.com/5210043/141390187-bc54beee-df2f-407e-859e-57481f11e103.png)

Looks good to me.

Thanks!

**Comment by adricl** [comment]
Can confirm it works with the new update for Windows Defender. Shall I close the ticket.

**Comment by nohwnd** [comment]
While I was asleep 1.353.853.0 was released which fixes the issue. For completeness here is additional info on trigerring an update: https://www.microsoft.com/en-us/wdsi/defenderupdates

**Comment by nohwnd** [comment]
@adricl I think ypu can close it.
