### ISSUE TITLE
Getting MethodException: Cannot find an overload for ".ctor"  with PSScriptAnalyzer exclusion line

### ISSUE THREAD

**Issue by asears** [pester/Pester#2106]
## General summary of the issue

This is a low priority issue and goes back awhile but something I thought might help others.

When I call out from a Pester test script to a script under test, the test throws an error on the call to the SUT script.

```powershell
##[error]    [-] It should return no errors 94ms (31ms|63ms)
##[error]     MethodException: Cannot find an overload for ".ctor" and the argument count: "1"
```
Removing invalid the Diagnostics.CodeAnalysis.SuppressMessageAttribute line fixes the issue.

Fixing the signature of the attribute fixes the issue.

See https://github.com/psake/psake/issues/164

## Describe your environment
Using latest Pester version in a Windows-2019 Azure Devops CI pipeline.

## Steps to reproduce

this doesn't work
```powershell
    <# my synopsis header #>
[Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSAvoidUsingCmdletAliases")]
param()
# my code
```
this works
```powershell
    <# my synopsis header #>
[Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSAvoidUsingCmdletAliases", "")]
param()
# my code
```

Oddly enough, it appears to cache the first successful signature hit.  If I have 2 scripts with this issue, and fix the first tested script, the second script passes with the invalid signature SuppressMessageAttribute.

Plus this script passes Invoke-ScriptAnalyzer and ignores the warning so I guess there may be a bug (or a fix) in the validation of that library's signature to raise this or suppress this issue.

## Possible Solution? (optional)

The message is really cryptic and a better description or troubleshooting message could help.

Some issue with the C# AST parser error handling perhaps.  A better error out of the parser would probably help, identifying the line of interest rather than just the called script, or a suggestion to increase verbosity to troubleshoot further.

See https://github.com/psake/psake/issues/164

**Comment by fflaten** [comment]
Thanks for the tip.

As mentioned in the related issue there's only one valid constructor for that attribute and it requires to string parameters. https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.suppressmessageattribute?view=net-6.0

Yes the error is unclear, but it is what's being thrown and it's caused by a user error and not by Pester. So it doesn't feel right to modify the error message for edge cases like this. Well at least that's my two cents.
