### ISSUE TITLE
Run.Passthru $true doesn't populate the variable with the results psobject

### ISSUE THREAD

**Issue by ChrisGibson1982** [pester/Pester#2112]
## General summary of the issue
If I run the invoke-pester command as the value of a variable ($result = invoke...) , the variable is not populated with the command output object.  However, I can see the object when the command is run.  I have tried tweaking the output verbosity, but this makes no difference.

## Describe your environment

Pester version     : 5.3.1 C:\program files\powershell\7\Modules\Pester\5.3.1\Pester.psm1
PowerShell version : 7.2.0
OS version         : Microsoft Windows NT 10.0.19043.0

## Steps to reproduce
```powershell

$configuration = [PesterConfiguration]@{
    Run    = @{
        Path          = './powershell'
        TestExtension = '.tests.ps1'
        Exit          = $true
        PassThru      = $true
    }
    Should = @{
        ErrorAction = 'SilentlyContinue'
    }

    Output = @{
        Verbosity = 'Normal'
    }

}

$result = Invoke-Pester -Configuration $configuration

```

## Expected Behavior
The results ps object would be accessibale via the variable name, e.g. $result.failedcount etc

## Current Behavior
The variable is empty

**Comment by nohwnd** [comment]
This is happening because you set the exit to $True, and I assume run it in VSCode? VSCode is not exiting the process on exit. So you will end up with the result in pipeline, but it won't be associated with the $result variable, because PowerShell will never reach that point.

**Comment by jaccus** [comment]
Would you care to elaborate on what is wrong in the provided sample code? I seem to be running into the same / similar issue (no, not using VSCode, invoking straight from the terminal).

**Comment by nohwnd** [comment]
There is nothing wrong with the original example. It just can be a bit confusing what is happening when exit is set to true in the configuration. That means that once tests finish, Pester will call `exit`. Exit keyword is context sensitive and can exit the current process, but also just the current script. 

We also write the result into the pipeline when PassThru is specified, before exiting. So if Pester exits the output is reported but the $result = in your script is never reached. You will get output but no assignment.

Save this into s.ps1: 
```powershell
function f () {
    "Hello!"
    exit 1
}

$result = f
```

Then run `.\s.ps1`. You will get "Hello!" on your screen, for the same exact reason :)

**Comment by ChrisGibson1982** [comment]
Sorry missed this update.  Changing to $false solved the problem.  Thanks :)
