### ISSUE TITLE
Azure pipeline uses outdated images

### ISSUE THREAD

**Issue by fflaten** [pester/Pester#2117]
The current Azure Pipeline uses deprecated and removed images in hosted agents

- **vs2017-win2016** (used in "PS_5_1_Windows_Server2016" and "PS7_Windows_Server2016" test-steps)
  - Deprecated
  - _With the upcoming end of mainstream support on Windows 2016 in January 2022, we are deprecating vs2017-win2016 images starting November 15. Retirement is planned for March 2022._
- **ubuntu-16.04**  (used in "PS7_Ubuntu_16_04" test-step)
  - Was removed September 2021
- **macOS-10.14**  (used in "PS7_macOS_10_14_Mojave" test-step)
  - Was removed December 2021
  - _Azure Pipelines is removing macOS 10.14 Mojave images (macOS-1014) from our hosted pools on December 10th_

Should maybe update build image to "windows-2022" to use .NET 6.0 SDK at the same time.

**Comment by nohwnd** [comment]
Did that in #2141

**Comment by fflaten** [comment]
Still using vs2017-win2016

**Comment by nohwnd** [comment]
For backwards compatibility 😁 Let me remove that when I have something to build.
