### ISSUE TITLE
user@contoso.onmicrosoft.com

### ISSUE THREAD

**Issue by Neo-wise** [pester/Pester#2118]
https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-the-new-certification-for-microsoft-teams-voice/ba-p/3035405

**Comment by Jhammond1983-SU** [comment]
https://github.com/pester/Pester/issues/2118#issue-1083745031

**Comment by Jhammond1983-SU** [comment]
@Jhammond1983-SU
