### ISSUE TITLE
Should generate coverage report files 

### ISSUE THREAD

**Issue by Jaykul** [pester/Pester#212]
It would be really great if we could export code coverage reports to a reusable format to show progress, and document state.

There are several known formats already (e.g. gcov, lcov, even a json format) -- which are used by projects like codecov.io to generate pretty web-based code-coverage reports, can we pick one of those?

See here, for docs and examples: https://codecov.io/docs

**Comment by DarqueWarrior** [comment]
Has there been anymore thought on this? I would really like to publish my code coverage results as part of my CI. What would it take to generate a JaCoCo or Cobertura?

**Comment by dlwyatt** [comment]
I'll have to look into those formats and see what they support.  It's not difficult to take the information we have in memory and dump it out to a file, but Pester's code coverage analysis looks at PowerShell _commands_, regardless of whether they're one to a line, one command spanning multiple lines, or multiple commands on a single line.  Where it gets awkward is translating that to a format that expects a report on what _lines_ were hit.

**Comment by stevepeak** [comment]
@DarqueWarrior Can you upload a Jacoco report to me. I'm curious if if contains complexity data because Codecov will support Jacoco Complexity next month.

> Both Jacoco and Cobertura are acceptable upload formats to Codecov.

**Comment by DarqueWarrior** [comment]
@stevepeak Here you go. These are from a very simply Java project created with [yo vsts](https://github.com/DarqueWarrior/generator-vsts).
[CoberturaCodeCoverageReport.zip](https://github.com/pester/Pester/files/615111/CoberturaCodeCoverageReport.zip)
[JaCoCoCodeCoverageReport.zip](https://github.com/pester/Pester/files/615112/JaCoCoCodeCoverageReport.zip)

**Comment by dlwyatt** [comment]
Both of those formats have assumptions from Java (things like "Packages" and "Classes" must exist, etc), but we could probably still just fudge that and put Pester's useful information in there.

**Comment by stevepeak** [comment]
@DarqueWarrior very nice 👍 both those formats work.

**Comment by DarqueWarrior** [comment]
I have used them for C# which does not have Packages but still was useful.

**Comment by TravisEz13** [comment]
The DSC resource has a Module we use to generate reports for `codecov.io` here
https://github.com/PowerShell/DscResource.Tests/tree/dev/DscResource.CodeCoverage

**Comment by RangerDjanger** [comment]
Has anyone been able to generate code coverage results to publishing into TFS/VSTS?

**Comment by it-praktyk** [comment]
The pull request #782 introduced support for JaCoCo XML code coverage reports - thank you @scriptkiddie123.

Maybe this can be reused for other formats too?

**Comment by jonkeda** [comment]
Just created a version of the JaCoCo xml in pull request #920 and create a JaCoCo reader available at 
https://marketplace.visualstudio.com/itemsitemName=Jonkers.JaCoCoreaderfortheJavaCodeCoveragefile.

**Comment by scriptkiddie123** [comment]
@RangerDjanger yes, version 6 of PesterRunner has support for Pester 4, and got a new field to specify where you want the code coverage report: https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-PesterRunner-Task.

**Comment by jonkeda** [comment]
@scriptkiddie123 Would you be able to test pull request #920 with the PesterRunner? I guess you should be able to see details in VSTS. I haven't been able to try it yet.

**Comment by scriptkiddie123** [comment]
@it-praktyk The code created to do the JaCoCo report is the bare minimum. Mostly because TFS/VSTS only has the 4 bar charts for total files/functions/lines/instuctions, so for my purpose I did not need anything else.

The Get-JaCoCoReportXml function consists of 3 basic parts:
1: Take the code coverage report object, and count the number for hit/missed lines/functions/files, these values are not directly in the report.
2: Defined the JaCoCo xml document.
3: Set the calculated values in the XML.

So to change it to also support Corbetura, you would only need to
1: Move the counting step into the Get-CoverageReport
2: Copy paste the rest of the Get-JaCoCoReportXml to a Get-CobeturaReportXML.
3: Understand the Cobertura format. I can see that it has required fields for branch-rate and complexity, which I don't think Pester provides. Maybe they can be set to null/0, but it would depend on the consumers.
4: Modify the get-coberturaReportXml so it outputs the Cobertura xml.
5: Make a switch in the following code in pester.psm1, that can switch between Cobertura, JaCoCo and other formats:
```Powershell
if (& $script:SafeCommands['Get-Variable'] -Name CodeCoverageOutputFile -ValueOnly -ErrorAction $script:IgnoreErrorPreference) { 
      $jaCoCoReport = Get-JaCoCoReportXml -PesterState $pester -CoverageReport $coverageReport 
      $jaCoCoReport | & $SafeCommands['Out-File'] $CodeCoverageOutputFile -Encoding utf8 
} 
```

**Comment by felixfbecker** [comment]
I also found https://github.com/JanJoris/coveralls

It seems like there are a lot of custom scripts. Could one of these get integrated into core so there is some kind of output? It doesn't have to be perfect, it doesn't matter if initially it doesn't report partial hits on lines, but even hit/not hit per line is valuable.

**Comment by felixfbecker** [comment]
I got it to working in the meantime using the script by DscResource:

- [appveyor.yml](https://github.com/aaronpowell/ps-nvmw/blob/9784e5ada938a7485a6786371ac76b3ed78d37fb/appveyor.yml)
- [.travis.yml](https://github.com/aaronpowell/ps-nvmw/blob/9784e5ada938a7485a6786371ac76b3ed78d37fb/.travis.yml)
- [CodeCov report](https://codecov.io/gh/aaronpowell/ps-nvmw/src/master/nvm.psm1)

As this seems to work fine, could we just integrate that script with a parameter `-CodeCoverageOutputFileFormat json`?

**Comment by it-praktyk** [comment]
I'll try to read about [coveralls](https://github.com/JanJoris/coveralls) and test it on weekend.
Personally, I'm not sure if we would like to add an external dependency to Pester.

CC: @JanJoris

**Comment by felixfbecker** [comment]
I'm not saying we should add an external dependency, my understanding is that the JSON format is a commonly used format and I would copy and integrate the DscResources script code and remove any mention of codecov.

**Comment by it-praktyk** [comment]
I think that with that kind of contribution we will not have an issue :-) 

Of course
- the source projects maintainers need to be aware of that. Maybe we should give them even priority to contribute? 
- a source code license needs to be appropriate to a code reuse under Apache license.

@SteveL-MSFT, who can verify formal aspects of reuse the code from the [PowerShell\DscResource.Tests](https://github.com/PowerShell/DscResource.Tests) repository?

**Comment by felixfbecker** [comment]
It's MIT. You could also just look at the way they do as an example of how it could be done in Pester.

**Comment by jonkeda** [comment]
In #920 the line details are added for JaCoCo. Looking at the  PowerShell\DscResource.Tests it shouldn't be hard to add this. 

I don't know how what the proces is for contributing to Pester. Is it ok if I create the code over the weekend? Or is there another way?

**Comment by it-praktyk** [comment]
@jonkeda, please read [Contributing to Pester](https://github.com/pester/Pester/wiki/Contributing-to-Pester).

I hope to find time to update it soon. Update will contain e.g. what needs to be fulfilled due to PowerShell Core compatibility.

**Comment by JanJoris** [comment]
> Personally, I'm not sure if we would like to add an external dependency to Pester.

Just stumbling in here to see what it's all about. I don't mind if anyone uses my code to add this functionality, I would even be glad to help out as I did a lot of the lifting by trial and error. The only issue today is that, I kid you not, no longer have a proper Windows dev environment due to switching jobs. But I'd gladly create one, because I love Pester :-)

**Comment by SteveL-MSFT** [comment]
@it-praktyk as noted, it's MIT licensed, so just attribution is required (adding to ThirdPartyNotices.txt is typically what happens)

**Comment by nohwnd** [comment]
@JanJoris You are right on time then. Pester runs cross-platform since this morning. You can either install powershell directly to your linux/mac, or run it in Docker. Either interactively in `microsoft/powershell`, or use this [pre-canned](https://hub.docker.com/r/nohwnd/pester-build/) image that I use.

**Comment by JanJoris** [comment]
@nohwnd cool, let me try that!

**Comment by felixfbecker** [comment]
I did some slight modifications to the DSC CodeCov script to make it work cross-platform: https://github.com/aaronpowell/ps-nvm/blob/bf4ca1953b250c11887a36464de566794947afb1/.scripts/CodeCovIo.psm1
(the original is linked at the top if you want to diff it)

**Comment by nohwnd** [comment]
@JanJoris Still willing to contribute this? :)

**Comment by stevepeak** [comment]
(*Codecov Team Member*) I'll be happy to help verify uploads and json structure when it's time. Just ping me. 👍

**Comment by VertigoRay** [comment]
@felixfbecker Thanks for sharing your process. I set it up, but it gave me 0% for the Composite Resource I'm working on. Mind looking at the repo and letting me know if anything stands out to you?

https://github.com/VertigoRay/OneDriveDsc

**Comment by felixfbecker** [comment]
@VertigoRay according to this you don't use the script I posted?

https://github.com/VertigoRay/OneDriveDsc/blob/aaea7a67debeaac3c98fe773abe6751ef0ddcdf1/REQUIREMENTS.psd1#L19:64

**Comment by VertigoRay** [comment]
@felixfbecker You said it was minor changes for linux/mac compatibility, so I didn't switch to that. I took that one from your first post:
https://github.com/aaronpowell/ps-nvm/blob/9784e5ada938a7485a6786371ac76b3ed78d37fb/appveyor.yml#L15

I'll switch to the one your have posted just above and see if it works.

**Comment by VertigoRay** [comment]
@felixfbecker Same issue with newer script. I don't want to clutter this issue, but I want to be sure that whatever solution is implemented properly tracks coverage of DSC Composite Resources.

**Comment by it-praktyk** [comment]
This issue was referenced in the blog post [Adding a code coverage badge to a PowerShell project](http://wragg.io/add-a-code-coverage-badge-to-your-powershell-deployment-pipeline/) by @markwragg

**Comment by it-praktyk** [comment]
I updated the pull request #920. Now the proposed feature (detailed code coverage) is updated to be compatible with PowerShell Core 6.x too.

Before merge tests are needed. Can you help?

**Comment by felixfbecker** [comment]
I published the script I mentioned above in a module: https://www.powershellgallery.com/packages/PSCodeCovIo/1.0.1

It exports the `$res.CodeCoverage` data to a JSON file that can be uploaded to CodeCov with the standard bash uploader.

**Comment by Mobrockers** [comment]
We would like to include our pester code coverage results in our sonarqube projects. SonarQube uses their generic test data format for uploading test data. The format is XML and they provide an xsd to validate against. Information can be found here: https://docs.sonarqube.org/display/SONAR/Generic+Test+Data
We would very much like this format to be available as output.

**Comment by nohwnd** [comment]
#920 was merged, Pester outputs JaCoCo, other formats are possible to be added if the PSCodeCovlo above is not enough.
