### ISSUE TITLE
Debug.WriteDebugMessages Can Cause Dictionary Key Errors

### ISSUE THREAD

**Issue by LethiferousMoose** [pester/Pester#2123]
## General summary of the issue
Using parameter filters when debug messages are turned on can lead to errors in Pester with duplicate keys for variables being added to the dictionary

## Describe your environment

```
Pester version     : 5.3.1 C:\Users\biggi\Documents\PowerShell\Modules\Pester\5.3.1\Pester.psm1
PowerShell version : 7.2.1
OS version         : Microsoft Windows NT 10.0.19043.0
```

## Steps to reproduce

Create a test module (TestModule.psm1) with the following and install it where PowerShell can find it:
```powershell
function Function-To-Mock {
    param (
        [System.Collections.Generic.List[PSCustomObject]] $ValueToCheck
    )

    Write-Host 'Stuff happened'
}

function Function-One {
    param (
        [System.Collections.Generic.List[PSCustomObject]] $ValueToPassIn
    )

    Function-To-Mock -ValueToCheck $ValueToPassIn
}
```

Create a Pester test (TestVariables.Tests.ps1) with the following:
```powershell
Import-Module TestModule -Force

InModuleScope TestModule {
    Describe 'Duplicate key issue' {
        It 'Using parameter filter to check map entries' {
            [System.Collections.Generic.List[PSCustomObject]] $res = @()
            $res.Add([PSCustomObject]@{'ValueOne' = 'Some value'; 'ValueTwo' = 'It does something'})
            $res.Add([PSCustomObject]@{'ValueOne' = 'Some other value'; 'ValueTwo' = 'It also does something'})

            Mock Function-To-Mock

            Function-One -ValueToPassIn $res

            Assert-MockCalled Function-To-Mock -Scope It -Exactly 1 -ParameterFilter {
                for ($i = 0; $i -lt $ValueToCheck.Count; $i++) {
                    if ($ValueToCheck[$i].ValueOne -ne $res[$i].ValueOne -or $ValueToCheck[$i].ValueTwo -ne $res[$i].ValueTwo) {
                        return $false
                    }
                }

                return $true
             }
        }
    }
}
```

Setup the `PesterConfiguration` with Debug messages enabled and call `Invoke-Pester`:
```powershell
    $Configuration = [PesterConfiguration]::Default

    $Configuration.Run.Path = "<Path To Test>"
    $Configuration.CodeCoverage.Path = "<Path to Module>"

    $Configuration.CodeCoverage.Enabled = $true

    $Configuration.Debug.WriteDebugMessages = $true
    $Configuration.Debug.WriteDebugMessagesFrom = "CodeCoverage"

    Invoke-Pester -Configuration $Configuration
```

## Expected Behavior

No errors happen and the test behaves the same and when debug messages are disabled.

## Current Behavior

An argument exception occurs:
```
ArgumentException: Item has already been added. Key in dictionary: 'res'  Key being added: 'res'
MethodInvocationException: Exception calling "Add" with "2" argument(s): "Item has already been added. Key in dictionary: 'res'  Key being added: 'res'"
```

## Possible Solution? (optional)

In Pester.psm1, this is where the error occurs, maybe this could be changed to an update using `$preExistingFilterVariables.[$v.VariablePath.UserPath]`, rather than an `Add()` call or just do not add it if already present.

```powershell
    # Check for variables in ParameterFilter that already exists in session. Risk of conflict
    if ($PesterPreference.Debug.WriteDebugMessages.Value) {
        $preExistingFilterVariables = @{}
        foreach ($v in $filter.Ast.FindAll( { $args[0] -is [System.Management.Automation.Language.VariableExpressionAst] }, $true)) {
            if ($existingVar = $SessionState.PSVariable.Get($v.VariablePath.UserPath)) {
                $preExistingFilterVariables.Add($v.VariablePath.UserPath, $existingVar.Value)
            }
        }
```

**Comment by fflaten** [comment]
Thanks for the report!

I never tested multiple references to the same variable in the filter. Rookie mistake 🤦 

Should definitely ignore if already defined in dictionary. Will be fixed in next release. 👍

**Comment by LethiferousMoose** [comment]
It was mostly just chance I came across it. I have some old pester tests that broke when I updated to the new Pester configuration. I'm still not 100% sure which setup makes the variable duplicate, it took some playing around to figure out exactly how to reproduce it with a sample test.

**Comment by fflaten** [comment]
This should repro (can't test atm). 👍 

`Assert-MockCalled Function-To-Mock -Scope It -Exactly 1 -ParameterFilter { $ValueToCheck -we $ValueToCheck }`

**Comment by LethiferousMoose** [comment]
Oh thanks, I must have missed the new syntax when I upgraded to v5 and just got things to run. I'll look over the docs again and get everything switched to the new syntax, it's definitely much more readable! I see you can also mock native commands now, so I guess I can remove my wrappers.
