### ISSUE TITLE
Inconsistency with Should -Be @()

### ISSUE THREAD

**Issue by LethiferousMoose** [pester/Pester#2124]
## General summary of the issue
The `Should -Be` operation does not work if the list is returned from a function with a leading comma to avoid type coercion into `$null` or a single object.

## Describe your environment

Pester version     : 5.3.1 C:\Users\biggi\Documents\PowerShell\Modules\Pester\5.3.1\Pester.psm1
PowerShell version : 7.2.1
OS version         : Microsoft Windows NT 10.0.19043.0

## Steps to reproduce

Create a PowerShell script that looks like the following.
TestList.ps1:
```powershell
function TestList {
    [System.Collections.Generic.List[object]] $list = @()

    $list.Add('a')
    $list.Add('b')

    # Use leading comma to avoid nulls and single item types
    return , $list
}
```

Create a Pester test like the following.
TestList.Tests.ps1:

```powershell
BeforeAll {
    . /path/to/scripts/TestList.ps1
}

Describe 'Test non-null list' {
    It 'Fails' {
        TestList | Should -Be @('a', 'b')
    }

    It 'Succeeds' {
        [System.Collections.Generic.List[object]] $list  = TestList

        $list.Count | Should -Be 2
        $list[0] | Should -Be 'a'
        $list[1] | Should -Be 'b'
    }
}
```

## Expected Behavior

Both tests should pass.

## Current Behavior

Only one the test manually checking elements passes.

**Comment by fflaten** [comment]
Same as #1154.

You can try the [Assert](https://github.com/nohwnd/assert) module from PSGallery to solve this. Remember to import it before running your tests or in `BeforeAll`.
```powershell
It 'Fail no more' {
    Assert-Equivalent -Actual (TestList) -Expected @('a', 'b')
}
```

**Comment by LethiferousMoose** [comment]
Looks like the same issue, I will close mine.
