### ISSUE TITLE
Expanding data with ForEach, BeforeAll and BeforeDiscovery 

### ISSUE THREAD

**Issue by PingPongSet** [pester/Pester#2125]
The code in the section "Expanding data to generate Describe and Context blocks" below is not working.
https://pester.dev/docs/usage/test-file-structure#expanding-data-to-generate-describe-and-context-blocks
```

BeforeAll {
   $files1 = @(
    "test1","test2"
   )
}
Context "BeforeAll function <_>" -ForEach $files1 {
    It 'dummy' {
        "1" | Should -Be "1"
    }
}
```

However, below is working when `BeforeDiscovery` is used. 
```

BeforeDiscovery {
    $files2 = @(
        "test1","test2"
       )
}

Context "BeforeDiscovery function <_>" -ForEach $files2 {
    It 'dummy' {
        "1" | Should -Be "1"
    }
}
```

**Can anyone explain why one block is working, and the other is not working?**

## Location

https://pester.dev/docs/usage/test-file-structure#expanding-data-to-generate-describe-and-context-blocks

- Pester version: 5.3.1
- Function:

**Comment by fflaten** [comment]
Thanks for pointing this out. There's a typo in the docs example as it should've been BeforeDiscovery.

That's because `-Foreach ..` is evaluated in the Discovery-phase while `BeforeAll` is executed in Run-phase later.
