### ISSUE TITLE
`Should` throws exception for legacy syntax when parameters are broken across lines

### ISSUE THREAD

**Issue by snow-jlove** [pester/Pester#2138]
## General summary of the issue

When `Should` parameters (with dashes!) are split across lines, a runtime exception gets thrown, stating "RuntimeException: Legacy Should syntax (without dashes) is not supported in Pester 5. Please refer to migration guide at: https://pester.dev/docs/migrations/v3-to-v4".

## Describe your environment

```
Pester version     : 5.3.1 C:\Users\jlove\Documents\WindowsPowerShell\Modules\Pester\5.3.1\Pester.psm1
PowerShell version : 5.1.19041.1320
OS version         : Microsoft Windows NT 10.0.19044.0
```

## Steps to reproduce

```powershell
Describe ShouldLegacySyntax {
    It "does not complain about syntax" {
        1 + 1 | Should -Be 2
    }

    It "complains about syntax" {
        1 + 1 | Should `
            -Be 2
    }
}
```

## Expected Behavior

Both of the above tests should be treated equally and pass.

## Current Behavior

The second above test fails with the syntax exception.

**Comment by snow-jlove** [comment]
I ran into this issue when I tried splitting a long command across lines. Consider this line - when indented, it overran my editor's vertical ruler (120 chars):

```powershell
        Should -CommandName Install-Module -Exactly -Invoke -ModuleName $ModuleName -ParameterFilter $ParameterFilter1 -Times 2

# gets formatted to...

        Should `
            -CommandName Install-Module `
            -Exactly `
            -Invoke `
            -ModuleName $ModuleName `
            -ParameterFilter $ParameterFilter1 `
            -Times 2
```

**Comment by nohwnd** [comment]
Yikes, that rule is nothing but trouble. :/

**Comment by fflaten** [comment]
Not parameters in general, just the operator (Invoke\Be\...). I'd recommend using the operator as your first parameter for readability and as a bonus that would let you keep it on the first line and avoid this issue. Try:

```powershell
Should -Invoke `
    -CommandName Install-Module `
    -Exactly `
    -ModuleName $ModuleName `
    -ParameterFilter $ParameterFilter1 `
    -Times 2
```

**Comment by nohwnd** [comment]
Upvote on what Frode said, that makes it way easier to understand what that `Should` does and avoids the issue as well.

**Comment by ElvenSpellmaker** [comment]
@nohwnd That seems like a bad workaround, it's much cleaner to only have a single parameter per line and either all on newlines or none.

A proper fix would be great, I don't this issue is 'solved', until the next version that removes them (and the messages) entirely lands.

**Comment by nohwnd** [comment]
Ok let's just remove the warning.

**Comment by ElvenSpellmaker** [comment]
@nohwnd Thanks for the fix 🙂

**Comment by nohwnd** [comment]
That was all @fflaten  :)
