### ISSUE TITLE
CodeCoverage not reporting percentage properly when filtering

### ISSUE THREAD

**Issue by Nibushi** [pester/Pester#2144]
## General summary of the issue
When providing either the Filter.Tag or Filter.ExcludeTag options I can see the right number of functions are being executed but this is not reflected in the percentage covered report.

For example, if I have a file with 3 tests and I tag one of the describe blocks with "RunTest", then create the following Pester Configuration 

```powershell
$pesterArgs = New-PesterConfiguration
$pesterArgs.Run.Path =  ".\Do-Stuff-All.Tests.ps1"
$pesterArgs.Filter.Tag = "RunTest"
$pesterArgs.CodeCoverage.Enabled = $true
$pesterArgs.CodeCoverage.Path = ".\Do-Stuff.ps1"
$pesterArgs.Output.Verbosity = "Detailed"

Invoke-Pester -Configuration $pesterArgs
```

I would expect the code covered to show 100%, as I only ran one test. Similar to how this used to work in Pester 4 when providing a hashtable with a Function property you could specify which tests to run.

Running the above will show the tagged Test ran as expected but that the code covered is:
Covered 33.33% / 75%. 3 analyzed Commands in 1 File.

It will then list the 2 missed commands.

## Describe your environment
Pester version     : 5.3.1
PowerShell version : 7.2.1
OS version         : Microsoft Windows NT 10.0.22000.0

## Expected Behavior
I would expect the code covered percentage to match the filtered number of functions/tests called. The documentation seems to suggest that this is what should happen:
https://pester-docs.netlify.app/docs/commands/New-PesterConfiguration 
ExcludeTests: Exclude tests from code coverage. This uses the TestFilter from general configuration.

Or am I misunderstanding how Code coverage works now? [Probably :-) ]

**Comment by nohwnd** [comment]
Exclude tests will exclude .Tests.ps1 files from the code coverage, so they don't skew your results. Including .Tests.ps1 in your overall coverage is rarely useful. Probably only when you want to figure out tests that exist but don't run for some reason, like misplaced return in the tests file.

If you run 1 test on a file that has 3 functions, and that test only runs 1 function than it seems correct that your file has 33% coverage. Coverage cannot know how your functions are connected together, and so it cannot know that running 1 test is fully covering that 1 function, and should not cover the other 2. 

Do you have a more concrete example? :)
