### ISSUE TITLE
Consistent capitalisation: Foreach => ForEach

### ISSUE THREAD

**Issue by fsackur** [pester/Pester#2150]
## Summary of the feature request
- Given that some users have a strong preference for "canonical" formatting
- and given that `ForEach-Object` capitalises the `Each`
- then `Describe`, `It` and `Context` should tab-complete `-Foreach` to `-ForEach`

I would be happy to PR. This seems like a safe change AFAICS.

Oddly enough, Pester v5.3.1 on PS v7.2.1 does capitalise as `ForEach` for `Describe` and `It`; `Context` is an outlier.

**Comment by fflaten** [comment]
This is already fixed in #2111. Will be part of the next release. 🙂
