### ISSUE TITLE
How to use "Should -HaveParameter ... -Alias" when function has multiple aliases?

### ISSUE THREAD

**Issue by RobAshton-IM** [pester/Pester#2152]
## Location

- Pester version: 5.3.1
- Function: Should

## General summary of the issue

The documentation for Pester's "Should" command does not make it 100% clear what to do if I am trying to prove all of the possible variant Aliases for a function-under-test have been defined where more than one should exist.

Given a function definition like this:
``` PowerShell
function Get-FakeOutput {
    [CmdletBinding()]
    [OutputType([string])]
    param(
        # Input_A
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [Alias('In_A', 'A')]
        $Input_A
    )

    begin {}

    process {
        return ("FakeOutput for Input_A: {0}" -f $($Input_A))
    }

    end {}
}
```

The documentation for `Should -HaveParameter` indicates that the `-Alias` parameter expects a `System.Object` but that's it. There are no examples of usage here to guide the user either.

One would hope that you would be able to supply the `-Alias` parameter with an array containing all of the alias variants for the function, like so:

``` PowerShell
Describe "Get-FakeOutput Tests" {
    Context "" {
        It "Has a mandatory parameter called 'Input_A' of type 'System.String' with aliases ('In_a', 'A')" {
            $getFakeOutputCommand = Get-Command -Module "MyModule" -Verb "Get" -Noun "FakeOutput"
            $getFakeOutputCommand | Should -HaveParameter 'Input_A' -Type 'System.String' -Mandatory -Alias $('In_A', 'A')
        }
    }
}
```

However, this results in the error `Expected command Get-FakeOutput to have a parameter Input_A, which is mandatory, of type [System.String] and to have an alias 'In_A A', but it didn't have an alias 'In_A A'.`

The only way I've successfully tested all alias variants on a function parameter was to repeat the Should for each variant like so:

``` PowerShell
Describe "Get-FakeOutput Tests" {
    Context "" {
        It "Has a mandatory parameter called 'Input_A' of type 'System.String' with aliases ('In_a', 'A')" {
            $getFakeOutputCommand = Get-Command -Module "MyModule" -Verb "Get" -Noun "FakeOutput"
            $getFakeOutputCommand | Should -HaveParameter 'Input_A' -Type 'System.String' -Mandatory -Alias 'In_A'
            $getFakeOutputCommand | Should -HaveParameter 'Input_A' -Type 'System.String' -Mandatory -Alias 'A'
        }
    }
}
```

More clear documentation would help others in this situation.

**Comment by fflaten** [comment]
I don't see why -Alias shouldn't be a string-array parameter. String will auto-convert so no breaking change. 🙂 

Tagging as feature for now.

**Comment by fflaten** [comment]
Implementer will find all relevant code [here](https://github.com/pester/Pester/blob/main/src/functions/assertions/HaveParameter.ps1). Parameter type needs to be changed + add a loop to test each alias. ErrorMessage should specify which aliases was missing (or preset when -Not/Negate is specified). [Tests](https://github.com/pester/Pester/blob/main/tst/functions/assertions/HaveParameter.Tests.ps1) for this assertion should be extended to test a function with parameter w/mulitple aliases with and without success.
