### ISSUE TITLE
Add default parameter set to New-MockObject for backward compatibility.

### ISSUE THREAD

**Issue by phoerr** [pester/Pester#2158]
## General summary of the issue

Parameter sets were added to `New-MockObject` in [this commit](https://github.com/pester/Pester/commit/5282c930bf679331505a66295317c096fa8309c6) for `5.3.0`, but no default parameter set was specified. This breaks tests that worked for previous versions if they did not explicitly include the `-Type` parameter because they assumed the `[type]` input. 

Could we add the `DefaultParameterSetName` property to `New-MockObject` for backward compatibility?

## Describe your environment

```text
Pester version     : 5.3.1 C:\Program Files\PowerShell\Modules\Pester\5.3.1\Pester.psm1
PowerShell version : 7.2.2
OS version         : Microsoft Windows NT 10.0.19043.0
```

## Steps to reproduce

Run this Pester test:

```powershell
Describe 'New-MockObject ParameterSet tests' {
    BeforeAll {
        $ExpiredCert = New-MockObject System.Security.Cryptography.X509Certificates.X509Certificate2 |
            Add-Member -Force -MemberType NoteProperty -Name NotAfter -Value (Get-Date).AddDays(-1) -PassThru

        Mock -CommandName 'Get-PfxCertificate' -ParameterFilter { $FilePath -eq 'Expired Cert Path' } -MockWith { $ExpiredCert }
    }

    It 'Certificate is expired' {
        $PfxCertificate = Get-PfxCertificate -FilePath 'Expired Cert Path'
        (Get-Date) | Should -BeGreaterThan $PfxCertificate.NotAfter
    }
}
```

## Expected Behavior

The above test passes. This last worked with Pester version `5.2.2`, but no longer works starting with version `5.3.0`.

## Current Behavior

The above test fails with the error:

```text
[-] Describe Mock ParameterSet tests failed
 ParameterBindingException: Parameter set cannot be resolved using the specified named parameters.
 One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
 at <ScriptBlock>, C:\SourceCode\Pester\New-MockObject-DefaultParameterSet.Tests.ps1:3
```

## Possible Solution? (optional)

While the immediate answer is to simply update the test to add the `-Type` parameter like this:

```powershell
New-MockObject -Type System.Security.Cryptography.X509Certificates.X509Certificate2
```

We could allow for backward compatibility with minimal code and maintenance complexity by adding the `DefaultParameterSetName` property. We could add the following line before the `param` block in `New-MockObject`:

```powershell
[CmdletBinding(DefaultParameterSetName = 'Type')]
```

**Comment by nohwnd** [comment]
Yes, PR please?

**Comment by phoerr** [comment]
Definitely! I've submitted PR https://github.com/pester/Pester/pull/2160, which includes a new test for `New-MockObject`.

**Comment by nohwnd** [comment]
Thanks merged.
