### ISSUE TITLE
Invoke-Pester with -OutputFile Fails in Nano Server Images

### ISSUE THREAD

**Issue by irishismyname** [pester/Pester#2181]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?

`Invoke-Pester` with `-OutputFile TestResult.xml` fails on Windows Nano Server images with:
```
Microsoft.Management.Infrastructure.CimException: FAILED
```
While `Get-CimInstance` is a "safe command" in Nano Server, running [`Get-CimInstance Win32_OperatingSystem`](
https://github.com/pester/Pester/blob/f7ee1bacfd575c3b4ced4fff2ebedf2e208a04ab/src/functions/TestResults.ps1#L938) returns:
```
Get-CimInstance: FAILED
```

I guess they (Microsoft) are aware of this? https://github.com/PowerShell/PowerShell/issues/11009

### Expected Behavior

`Invoke-Pester -OutputFile TestResult.xml` should not fail when [`Get-RunTimeEnvironment()`](https://github.com/pester/Pester/blob/f7ee1bacfd575c3b4ced4fff2ebedf2e208a04ab/src/functions/TestResults.ps1#L933) can't get the OS info.

### Steps To Reproduce

I created a kind of silly reproduction at https://github.com/irishismyname/PesterTester where you can clone and run `./Start-DockerContainer.ps1` on a Windows 20H2+ machine.

Summary:
1. `docker run -it mcr.microsoft.com/powershell:nanoserver-20h2`
2. `Install-Module Pester -Force -Scope AllUsers -SkipPublisherCheck; Import-Module Pester -PassThru;`
3. Load/paste/mount a .Tests.ps1 file into the container
4. Run a test with `Invoke-Pester -OutputFile TestResult.xml`

### Describe your environment

```
Pester version     : 5.3.3 C:\program files\powershell\Modules\Pester\5.3.3\Pester.psm1
PowerShell version : 7.2.4
OS version         : Microsoft Windows NT 10.0.19042.0
```

### Possible Solution?

It seems that [`Get-RunTimeEnvironment`](https://github.com/pester/Pester/blob/f7ee1bacfd575c3b4ced4fff2ebedf2e208a04ab/src/functions/TestResults.ps1#L933) should failover to something like what's in the [Linux/MacOS condition](https://github.com/pester/Pester/blob/f7ee1bacfd575c3b4ced4fff2ebedf2e208a04ab/src/functions/TestResults.ps1#L944) or maybe a try/catch block should be added.

**Comment by nohwnd** [comment]
https://github.com/pester/Pester/blob/8634da048e67d84b07b15af339a13f748d13129d/src/functions/Pester.SafeCommands.ps1#L85-L99 

This is where we report a warning when cim / wim cmdlets are not available. Is there a **fast** way to determine that we are on nano server to add as additional condition, and in that case not populate the safe commands entry? This will then fall back to writing the warning, and all places that try to grab OS info will skip over it because the command entry is empty.


You can also locally disable module autoloading to see the same happen, because cim cmdlets won't be imported. `$PSModuleAutoLoadingPreference = 'None'` on top of your profile.

**Comment by irishismyname** [comment]
I'm struggling to find a more concise way, but according to this [*out of date documentation I found*](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/hh846315(v=vs.85)):
```
try {
  (Get-ItemPropertyValue 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Server\ServerLevels' -Name NanoServer) -eq 1
}
catch { $false }
```

**Comment by nohwnd** [comment]
Sounds like an okay solution, it will be queried once on module import, so it should be fast enough. Will you PR this? :)
