### ISSUE TITLE
TestDrive not available in scriptblock

### ISSUE THREAD

**Issue by DarkLite1** [pester/Pester#2188]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?
We're trying to create a file when a job is called. However, it seems that the Pester TestDrive is not available within a scriptblock of `Start-Job`. The thrown job error is:

`Cannot find drive. A drive with the name 'TestDrive' does not exist.`

### Expected Behavior

The file would simply be created in the Pester TestDrive

### Steps To Reproduce

```powershell
Describe 'should be' {
    BeforeAll {
        $realCmdLet = @{
            StartJob = Get-Command Start-Job
        }
        Mock Start-Job {
            & $realCmdLet.StartJob -Scriptblock { 
                New-Item 'TestDrive:\test.txt' -ItemType File -
            }
        }
    }
    It 'green' {
        $job = Start-Job -ScriptBlock { 1 }
        $job | Wait-Job
        'TestDrive:\test,txt' | Should -Exist
    }
}
```

### Describe your environment

Pester version     : 5.3.3 C:\Program Files\WindowsPowerShell\Modules\Pester\5.3.3\Pester.psm1
PowerShell version : 5.1.14393.5066
OS version         : Microsoft Windows NT 10.0.14393.0

**Comment by fflaten** [comment]
Jobs run in a different process, so no state is shared. You haven't even imported Pester in it. Just pass the `$TestDrive` variable to it.

```powershell
Mock Start-Job {
            & $realCmdLet.StartJob -Scriptblock { 
                New-Item "$using:TestDrive\test.txt" -ItemType File -
            }
        }
```

You could also map the PSDrive yourself, but why bother.

**Comment by DarkLite1** [comment]
Feeling stupid here.... Didn't know the `TestDrive` was a variable. Thank you for the help, this really fixed the issue for us:

```powershell
Describe 'should be' {
    BeforeAll {
        $realCmdLet = @{
            StartJob = Get-Command Start-Job
        }
        Mock Start-Job {
            & $realCmdLet.StartJob -Scriptblock { 
                New-Item "$using:TestDrive\test.txt" -ItemType File
            }
        }
    }
    It 'green' {
        $job = Start-Job -ScriptBlock { 1 }
        $job | Wait-Job
        'TestDrive:\test.txt' | Should -Exist
    }
}
```
