### ISSUE TITLE
File CreationTime not updated when new file in TestDrive is created with the same name

### ISSUE THREAD

**Issue by DarkLite1** [pester/Pester#2194]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?

The property `CreationTime` of a file is not updated in the `TestDrive`, even when the file is first removed.

### Expected Behavior

A new `Creationtime`

### Steps To Reproduce

```powershell
BeforeAll {
    Mock Invoke-Sqlcmd {
        $testFile = 'TestDrive:\backup.bak'
        Remove-Item $testFile -EA Ignore
        New-Item $testFile -ItemType File
    }
}
Describe 'should be' {
    It 'green' {
        $startTime = Get-Date

        $params = @{
            ServerInstance = 'a'
            Query          = 'b'
        }
        Invoke-Sqlcmd @params

        $params = @{
            Path        = 'TestDrive:\'
            Recurse     = $true
            File        = $true
            Filter      = '*.bak'
        }
        $mostRecentFile = Get-ChildItem @params | 
        Where-Object { $_.CreationTime -ge $startTime } |
        Sort-Object CreationTime | 
        Select-Object -Last 1 -ExpandProperty FullName

        $mostRecentFile | Should -Exist
    }
    It 'green' {
        $startTime = Get-Date

        $params = @{
            ServerInstance = 'a'
            Query          = 'b'
        }
        Invoke-Sqlcmd @params

        $params = @{
            Path        = 'TestDrive:\'
            Recurse     = $true
            File        = $true
            Filter      = '*.bak'
        }
        $mostRecentFile = Get-ChildItem @params | 
        Where-Object { $_.CreationTime -ge $startTime } |
        Sort-Object CreationTime | 
        Select-Object -Last 1 -ExpandProperty FullName

        $mostRecentFile | Should -Exist
    }
}
```

### Describe your environment

Pester version     : 5.3.3 C:\Program Files\WindowsPowerShell\Modules\Pester\5.3.3\Pester.psm1
PowerShell version : 5.1.14393.5066
OS version         : Microsoft Windows NT 10.0.14393.0

### Possible Solution?

Tried by adding `Start-Sleep -Seconds 1` but even then the `CreationTime` stays the same.

**Comment by fflaten** [comment]
The feature is officially called filesystem tunneling. See https://devblogs.microsoft.com/oldnewthing/20050715-14/?p=34923

**Comment by DarkLite1** [comment]
That makes it clear. Thanks for helping out once again. Been scratching my head about this...
