### ISSUE TITLE
Need help sanity checking generated commands

### ISSUE THREAD

**Issue by bravo-kernel** [pester/Pester#2195]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [open documentation issues](https://github.com/pester/Pester/issues?q=is%3Aissue+label%3ADocumentation+is%3Aopen)

### Where did you see it?

Other

### Function name

After-All

### What is the issue?

I am seeing an indentation problem when regenerating the Pester 5.3.3 command reference pages.

An example:

- see this raw and untouched [AfterAll.PlatyPS.md](https://gist.githubusercontent.com/bravo-kernel/86f27dc5be9276a44202dd095cf484ad/raw/2090bd92dba7175355efc4d0e8fe1088b504e355/After-All.PlatyPS.md)
- generated by PlatyPS by parsing this Get-Help line in [SetupTeardown.ps1](https://github.com/pester/Pester/blob/main/src/functions/SetupTeardown.ps1#L235) 

You will see that `It "File Contains 100 lines"` is not indented in the `.md` file even thought the indentation is correct in the source file.

## Reproduce locally

1. Run `generate-command-reference.ps1` in the pester-docs repo
2. Check git diffs in the `docs/commands` folder
3. You will see that there are more files with the indentation issue (e.g. Add-ShouldOperator and AfterEach)

## Versions

I have tried all possible combinations going back to old versions of Pester, PlatyPS and Alt3.Docusaurus.Powershell. E.g.

```powershell
.\generate-command-reference.ps1 -PesterVersion 5.2.1 -PlatyPSVersion 0.12.0 -DocusaurusVersion 1.0.12
```

Unfortunately:

- I could not find any combination that produces the correct indentation
- I could thus not pinpoint the cause to a specific version of any of the modules

Leading me to think this might have always been an issue, perhaps in the Pester code, manually corrected before.

## Raw files

FYI the raw PlatyPS files can be found in `%TEMP%\Alt3.Docusaurus.PowerShell\Pester` after running the generate script.

Suggestions welcomed!

**Comment by bravo-kernel** [comment]
Sorry, seems I created this ticket in the wrong repo, Can be moved to pester/docs otherwise keep it here.

**Comment by fflaten** [comment]
You can see the manual fixes we did last time here https://github.com/pester/docs/commit/462716872b21b59c45a0d1ad7bee441cbd796aab

**Comment by bravo-kernel** [comment]
Ah yes, now I remember. Thanks for that one, helps clear the fog :-D 

I will still investigate a little more. Starting with a new test case [here](https://github.com/alt3/Docusaurus.PowerShell/tree/main/Tests/Integration).

**Comment by fflaten** [comment]
👍 Played around with it last time where I added the missing code fences etc. but gave up on the last random indentation-issues. Had to save some for next time, hoping it would be fixed by platyPS2 😅

**Comment by bravo-kernel** [comment]
Yeah, it is pretty weird indeed but now that I have a test case... I can see what is causing the issue:

> PlatyPS cannot handle the white lines in-between which makes sense because it only expecting standard ([one-line and PS7-mulitline](https://docusaurus-powershell.netlify.app/docs/faq/multi-line-examples)) code fencing. 

- **The good news:** removing lines https://github.com/pester/Pester/blob/main/src/functions/SetupTeardown.ps1#L234, 238 en 242 solves the problem but will make it less readable
- **The bad news:** I don't think PlatyPS 2.0 will solve this issue

However, because we are post-processing the markdown anyway we might be able to regex-catch these errors and fix them ourselves [by adding a new function here](https://github.com/alt3/Docusaurus.PowerShell/tree/main/Source/Private) .

**Comment by bravo-kernel** [comment]
If there is a Powershell genius that can come up with a function to correct the indentation for the three test cases below it would be awesome, taken from the docusaurus enriched `.mdx`.

https://gist.github.com/bravo-kernel/e5fc2e4178754b3ffabcc43fa690d77f

**Comment by fflaten** [comment]
Tried `Invoke-Formatter` from PSScriptAnalyzer?

Probably better than my old ISE-profile script (which probably breaks multiline-strings ++). 😁

**Comment by bravo-kernel** [comment]
No I did not but I do have a fix (I think). Will close this ticket once done.

**Comment by bravo-kernel** [comment]
Fixed in release https://github.com/alt3/Docusaurus.PowerShell/releases/tag/1.0.30. Thanks for the reviews!

Indentation correction magic is happening here: https://github.com/alt3/Docusaurus.PowerShell/blob/main/Source/Private/IndentLineWithOpeningBracket.ps1
