### ISSUE TITLE
Mocking ShouldProcess stopped working in Pester 5.3.3?

### ISSUE THREAD

**Issue by hansEricG** [pester/Pester#2206]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?

I have created a utility module to help me test the PowerShell Should Process. It worked perfectly in Pester 5.1.1 but now that I've upgraded to 5.3.3, it doesn't seem to mock the Invoke-TDDShouldProcess function I've created anymore. I've made the most minor test case I could think of which produces the problem and my findings are these:

1. The provided test case works as expected in 5.1.1, but in 5.3.3 the Should Process is not mocked and I'm prompted for a manual answer. So the issue was introduced sometime between 5.1.1 and 5.3.3.

2. The issue seems to be related to the fact that the helper function (Invoke-TDDShouldProcess in my case) resides in a module. When I tried to extract the relevant files into the test project it works as expected.

Here are the relevant files needed to reproduce the issue. It consists of two files (Remove-Something.ps1 and Remove-Something.Tests.ps1) and a module (TDDSeams.zip)

[PesterMockIssue.zip](https://github.com/pester/Pester/files/9045499/PesterMockIssue.zip)

### Expected Behavior

When invoking Pester for the tests Remove-Somthing.Tests.ps1, I'm not prompted by any "Are you sure you want to perform this action?" confirmation requests.

### Steps To Reproduce

1. Unzip the files in the provided zip package to a temporary folder
2. Unzip the TDDSeams.zip file and copy its content to one of the powershell modules folders
3. Start powershell and go to the temporary folder in which you unzipped the files (step 1)
4. Run the command "Import-Module -Name Pester -RequiredVersion 5.3.3"
5. Run the command "Invoke-Pester".
6. You should see an example of the issue, an "Are you sure [...]" prompt.

![image](https://user-images.githubusercontent.com/2334493/177308111-4a82f17b-8922-4f4f-803b-b4ec56d876ec.png)

7. Cancel the execution with Ctrl-C.
8. Run the command "Remove-Module Pester"
9. Run the command "Import-Module -Name Pester -RequiredVersion 5.1.1"
10. Run the command "Invoke-Pester"
11. You are not prompted, and all tests are passed (as expected)

![image](https://user-images.githubusercontent.com/2334493/177308902-72a724d2-566e-46f5-905c-9d05ce9345c4.png)
 

### Describe your environment

Pester version     : 5.3.3 C:\Users\rc4091\OneDrive - Sandvik\HomeShare\Documents\PowerShell\Modules\Pester\5.3.3\Pester.psm1
PowerShell version : 7.2.3
OS version         : Microsoft Windows NT 10.0.19044.0

**Comment by fflaten** [comment]
This most likely broke with 5.2.0 when the rules regarding mocks and modules became stricter and more predictable.

The reason is trying to mock a function called by code (`Invoke-TDDShouldProcessCode`) inside the module. Since you didn't specify `-ModuleName TDDSeams` when creating the mock, you only made it visible in the script scope where only your test-code and `Remove-Something` can see it.

This is similar to mocking an internal private function inside a module, so you can see [in the docs](https://pester.dev/docs/usage/modules)

Try specifying `-ModuleName TDDSeams` in `Mock` and `Should -Invoke` since you're both calling and counting internal use of the function.

```powershell
It 'Should invoke SupportProcess' {
    Mock Invoke-TDDShouldProcess -ModuleName TDDSeams { $true }
    Remove-Something 
    Should -Invoke Invoke-TDDShouldProcess -ModuleName TDDSeams -Times 1 -Exactly
}
```

**Comment by hansEricG** [comment]
Of course, it makes perfect sense. And now it works perfectly again, with the ModuleName specified. Thank you so much, you guys are amazing.
