### ISSUE TITLE
Variables in BeforeDiscovery are lost when run with InModuleScope

### ISSUE THREAD

**Issue by fflaten** [pester/Pester#2222]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?

Variables created inside `BeforeDiscovery` are not available for ex. `-TestCases` when the whole block (ex `Describe`) is wrapped in `InModuleScope`.

Notice three tests missing in `InModuleScope - BeforeDiscovery`-block
```
Pester v5.3.3

Starting discovery in 1 files.
Discovery found 15 tests in 44ms.
Running tests.
Describing InModuleScope - loose variable
  [+] t1 from discovery 6ms (3ms|2ms)
  [+] t2 from discovery 4ms (2ms|2ms)
  [+] t3 from discovery 4ms (2ms|2ms)
  [+] t1 hardcoded 4ms (2ms|2ms)
  [+] t2 hardcoded 4ms (2ms|2ms)
  [+] t3 hardcoded 4ms (2ms|2ms)

Describing InModuleScope - BeforeDiscovery
  [+] t1 hardcoded 7ms (4ms|4ms)
  [+] t2 hardcoded 5ms (3ms|2ms)
  [+] t3 hardcoded 21ms (19ms|2ms)

Describing Normal
  [+] t1 from discovery 8ms (4ms|4ms)
  [+] t2 from discovery 5ms (2ms|3ms)
  [+] t3 from discovery 5ms (3ms|2ms)
  [+] t1 hardcoded 5ms (3ms|2ms)
  [+] t2 hardcoded 4ms (2ms|2ms)
  [+] t3 hardcoded 4ms (2ms|2ms)
Tests completed in 220ms
Tests Passed: 15, Failed: 0, Skipped: 0 NotRun: 0
```

Using `InModuleScope` around `Describe/Context` [IS discouraged in docs](https://pester.dev/docs/migrations/v4-to-v5#avoid-putting-in-inmodulescope-around-your-describe-and-it-blocks) due to poor performance etc. This issue might be a limitation, but then at least it will be documented here.

### Expected Behavior

All six tests found in all `Describe`-blocks.

### Steps To Reproduce

```powershell
$c = New-PesterConfiguration
$c.Run.ScriptBlock = {
    InModuleScope Pester {
        Describe 'InModuleScope - loose variable' {
            $numbers = 1..3
            It 't<_> from discovery' -TestCases $numbers {
                $_ | Should -BeLessOrEqual 3
            }

            It 't<_> hardcoded' -TestCases @(1..3) {
                $_ | Should -BeLessOrEqual 3
            }
        }

        Describe 'InModuleScope - BeforeDiscovery' {
            BeforeDiscovery {
                $numbers = 1..3
            }
            It 't<_> from discovery' -TestCases $numbers {
                $_ | Should -BeLessOrEqual 3
            }

            It 't<_> hardcoded' -TestCases @(1..3) {
                $_ | Should -BeLessOrEqual 3
            }
        }
    }

    BeforeDiscovery {
        $numbers = 1..3
    }
    Describe 'Normal' {
        It 't<_> from discovery' -TestCases $numbers {
            $_ | Should -BeLessOrEqual 3
        }

        It 't<_> hardcoded' -TestCases @(1..3) {
            $_ | Should -BeLessOrEqual 3
        }
    }
}
$c.Output.Verbosity = 'Detailed'
Invoke-Pester -Configuration $c
```

### Describe your environment

Pester version     : 5.3.3 /workspaces/Pester/bin/Pester.psm1                                                           
PowerShell version : 7.2.3
OS version         : Unix 5.10.102.1

**Comment by fflaten** [comment]
Never mind - closing as user error. 😅
Caused by being in same module state as `BeforeDiscovery`. Not relevant for other modules.

**Comment by nohwnd** [comment]
Uuuf. That would have been a terrible bug to fix. 😁
