### ISSUE TITLE
Evaluate parameter in a parameter set

### ISSUE THREAD

**Issue by johlju** [pester/Pester#2227]
### Checklist

- [X] Feature request has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### Summary of the feature request

As a user I would like to validate that a specific parameter set exist and that it contain the expect parameters.

### How should it work?

If `HaveParameter` would learn `CommandParameterSetInfo` we could use that to pass to `Should`.

```powershell
It 'Should have have correct parameters in parameters sets' {
    $parmetersSet = (Get-Command -Name 'New-SqlDscAudit').ParameterSets | Where-Object Name -EQ 'Set1'
    $parameterSet | Should -HaveParameter 'MyParameter'
    $parameterSet | Should -HaveParameter 'Set1Parameter'

    $parmetersSet = (Get-Command -Name 'New-SqlDscAudit').ParameterSets | Where-Object Name -EQ 'Set2'
    $parameterSet | Should -HaveParameter 'MyParameter'
    $parameterSet | Should -HaveParameter 'Set2Parameter'
}
```

Another option is to add `HaveParameterSet` with an optional parameter `WithParameter`.

```powershell
It 'Should have have correct parameters in parameters sets' {
    $commandInfo = Get-Command -Name 'Get-Something')

    $commandInfo | Should -HaveParameterSet 'MySetName1'
    $commandInfo | Should -HaveParameterSet 'MySetName2' -WithParameter 'MyParameter'
    $commandInfo | Should -HaveParameterSet 'MySetName3' -WithParameter @('MyParameter1', 'MyParameter2')
}
```

**Comment by fflaten** [comment]
Parameter set support is lacking in general. Noticed it the other day looking at `-Mandatory`. It will pass if the parameter is mandatory in any set, but there's no way to specify which.

Would a `-InParameterSet 'SetName123'` parameter be more intuitive maybe? Ex
```
(Get-Command abc123) | Should -HaveParameter 'MyParameter' -InParameterSet 'Set1' -Mandatory -DefaultValue '123'
```

You second suggestion would be hard to combine with Mandatory, DefaultValue, Type ++

**Comment by johlju** [comment]
`InParameterSet` would work too, didn't think of looking at it from that angle. 

Then this should work too and is also intuitive:

```
(Get-Command abc123) | Should -Not -HaveParameter 'MyParameter' -InParameterSet 'Set1'
```

**Comment by jeffpatton1971** [comment]
When can something like this be expected to be available? In the interim @fflaten do you have thoughts on testing for a parameter that is mandatory in one set and not mandatory in another?

**Comment by jeffpatton1971** [comment]
I like this code below for testing if a parameter is in the correct set! nice

> ```powershell
> It 'Should have have correct parameters in parameters sets' {
>     $parmetersSet = (Get-Command -Name 'New-SqlDscAudit').ParameterSets | Where-Object Name -EQ 'Set1'
>     $parameterSet | Should -HaveParameter 'MyParameter'
>     $parameterSet | Should -HaveParameter 'Set1Parameter'
> 
>     $parmetersSet = (Get-Command -Name 'New-SqlDscAudit').ParameterSets | Where-Object Name -EQ 'Set2'
>     $parameterSet | Should -HaveParameter 'MyParameter'
>     $parameterSet | Should -HaveParameter 'Set2Parameter'
> }
> ```

**Comment by jeffpatton1971** [comment]
@johlju  I took your code and tweaked it a little

```powershell
   It "ParameterSet should contain, DocumentId, HideId" {
    (Get-Command -Name 'Get-MongoDBDocument').Parameters['DocumentId'].ParameterSets.DocumentId | Should -Be $true
    (Get-Command -Name 'Get-MongoDBDocument').Parameters['HideId'].ParameterSets.DocumentId | Should -Be $true
   }
```

This works as expected, which got me thinking about how to test for mandatory in a given set

**Comment by jeffpatton1971** [comment]
It's a little cludgy but until @fflaten gets the inparameterset available

first parameterset

```powershell
   It "DocumentId should be Mandatory" {
    (Get-Command -Name 'Get-MongoDBDocument').Parameters['DocumentId'].ParameterSets.DocumentId.IsMandatory | Should -Be $true
   }
```

second parameterset

```powershell
   It "DocumentId should not be Mandatory" {
    (Get-Command -Name 'Get-MongoDBDocument').Parameters['DocumentId'].ParameterSets.CollectionNameId.IsMandatory | Should -Not -Be $true
   }
```

You will need to specify the ParmaeterName and ParmeterSetName; and it looks rather awkward but does in fact work as expected, which helps me a lot.

**Comment by fflaten** [comment]
> When can something like this be expected to be available?

Unclear as I'm busy at work the next month. Was hoping on some input by @nohwnd before committing to it. Feel free to submit a PR if you'd like to look into it. See https://pester.dev/docs/contributing/pull-requests . Source is [here](https://github.com/pester/Pester/blob/main/src/functions/assertions/HaveParameter.ps1) with tests in a matching file under /tst

> In the interim @fflaten do you have thoughts on testing for a parameter that is mandatory in one set and not mandatory in another?

Not really. I'd probably go commandinfo -> ParameterSets (filter by name) -> Parameters (filter by name) -> IsMandatory, but just personal preference.

**Comment by jeffpatton1971** [comment]
I get the work-life stuff, but I'm pretty swamped at work as well; if I get some time next week, I'll see if I can do a PR.

**Comment by fflaten** [comment]
Found some time and gave it a shot in linked PR. Can't promise a release date as its pending review.
