### ISSUE TITLE
-TestCases doesn't do the job in a test driven scenario

### ISSUE THREAD

**Issue by DeLeneMirouze** [pester/Pester#2242]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?

I have a test file that sound like this:

```
[CmdletBinding()]
param(
    [Array]$resources,
	[string]$resourceGroupName
)

Describe 'Testing webapps deployment' {
    BeforeAll {
        $parameters = @()

        $parameters += foreach ($resourceToDeploy in $resources) {
  
            
            @{
                webappNameName   = $resourceToDeploy.name 
            }
        }
    }

    It "Webapps <resourceName> exists" -TestCases $parameters {
        param($webappNameName)

        $instance = Get-AzResource -ResourceGroupName $resourceGroupName -Name $webappNameName -ErrorAction SilentlyContinue
        $instance.name | Should -Be $webappNameName
    }
}
```

$parameters is an array of names. I expect the It test iterate on every value.

But in fact it doesn't. When I enter into the test, parameter $webappNameName receive $null

When I rename $parameters to say $ffo, the test script is not even launched.

Don't know what I am missing.

Thank you

### Expected Behavior

How to make my test working

### Describe your environment

Pester => 5.3.2                

PowerShell => 

PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19042

**Comment by fflaten** [comment]
`-TestCases/ForEach` is evaluated during Discovery-phase. Variables created in Run-phase, e.g. in `BeforeAll { }` won't be available. You'll have to use `BeforeDiscovery { }`, see https://pester.dev/docs/usage/data-driven-tests#beforediscovery

**Comment by DeLeneMirouze** [comment]
I found the solution. Just replace BeforeAll by BeforeDiscovery
