### ISSUE TITLE
External array from Pester container treated as empty if used in ForEach

### ISSUE THREAD

**Issue by timwebster9** [pester/Pester#2246]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?

I have 2 issues here - one is more a question and the other potentially a bug (maybe).

I have some tests that use external data from a HashTable in an external configuration file.  One of the entries is an array, and one is a string like so:

config/$PlatformEnv.ps1 (the filename is determined at runtime by another variable):
```
@{
  customerEnv = 'dev'
   allowedEnvs = @('dev','sbx')
}
```

Pester setup/run:

```
$testData = Get-HashtableFromFile -Path "config/$PlatformEnv.ps1"

# Pester config
$pesterConfiguration = @{
 blah blah
}

# Configure and execute
$config = New-PesterConfiguration -Hashtable $pesterConfiguration
$container = New-PesterContainer -Path 'tests/*'-Data $testData
$config.Run.Container = $container
Invoke-Pester -Configuration $config
```

I want to use the array value (`allowedEnvs`) to dynamically generate test cases using `ForEach`.  However, it doesn't discover any tests:

```
# doesn't work - no tests discovered
It "Invalid environment name <_> should be allowed" -ForEach $allowedEnvs  {
   #some test code  
}

Pester v5.3.3
Starting discovery in 25 files.
Discovery found 65 tests in 3.62s.
Filter 'Tag' set to ('naming-rg-env-allowed').
Filter 'ExcludeTag' set to ('none').
Filters selected 0 tests to run.
Running tests.
Tests completed in 3.57s
Tests Passed: 0, Failed: 0, Skipped: 0 NotRun: 65
```

However, it works if I include this variable in a `param` block:

```
param (
    [Parameter(Mandatory)]
    [array] $allowedEnvs,
)

...

# works
It "Invalid environment name <_> should be allowed" -ForEach $allowedEnvs  {
   #some test code  
}

Pester v5.3.3
Starting discovery in 25 files.
Discovery found 67 tests in 2.65s.
Filter 'Tag' set to ('naming-rg-env-allowed').
Filter 'ExcludeTag' set to ('none').
Filters selected 2 tests to run.
Running tests.
Running tests from '/agent/_work/1/s/tests/General/Resource-Group-Naming-Env.Tests.ps1'
Describing Test Resource Group naming policy - ENV
Context Resource group ENV names should be allowed
Deleting resource group dev-policytest-uks-rg...
[+] Resource group with invalid environment name dev should be allowed 1.11s (1.08s|33ms)
Deleting resource group sbx-policytest-uks-rg...
[+] Resource group with invalid environment name sbx should be allowed 724ms (723ms|2ms)
Tests completed in 4.71s
Tests Passed: 2, Failed: 0, Skipped: 0 NotRun: 65
```

Now, of course the [documentation](https://pester.dev/docs/usage/data-driven-tests#providing-external-data-to-tests) says to use a `param`, but the thing is these variables from the external config work fine without having to declare them in a `param` block. 

```
It "print vars"  {
   Write-Host $customerEnv
    Write-Host $allowedEnvs
}

dev
dev sbx

```
 If you add one to the `param` block, you then need to add all of them or else you get an error like so:

```
##[error] System.Management.Automation.ParameterBindingException: A parameter cannot be found that matches parameter name 'customerEnv'.
```

My issue with having to add these to a `param` block is that there could be potentially many variables and I don't want to have to add them all to the `param` block, so I was happy I didn't actually have to declare them - until now.  This is kind of a side-issue though, and I could probably get around this by putting them all into an Object and just passing that in?

So - my questions/issues are:

1. Should the array variable work in the `ForEach` without needing to make it a parameter?  The variable seems to not be empty - why doesn't it work?
2. How/why is it possible to use the external data without declaring them all as parameters, and why do you need to declare all of them the minute you add a `param` block?  Maybe the docs could make this clearer?

Apologies - I'm not able to provide better code samples or output - I can't log into Github from the system where the tests are running.

### Expected Behavior

Array variables declared in external data should be able to be used in `ForEach` without making them a parameter.  At the very least they seem to behave differently that string variables at the moment.

### Steps To Reproduce

see above

### Describe your environment

Pester v5.3.3 running on Ubuntu Linux.

**Comment by fflaten** [comment]
> I want to use the array value (`allowedEnvs`) to dynamically generate test cases using `ForEach`. However, it doesn't discover any tests:

`-ForEach/TestCases` is processed during Discovery. Discovery is essentially your script executed with splatted `-Data`. A hashtable splatted in a script without parameters defined won't create any parameter-variables -> `$allowedEnvs -eq $null` -> no tests found.

```powershell
$testData = @{
    customerEnv = 'dev'
    allowedEnvs = @('dev','sbx')
}

$script = {
    param($customerEnv)
    "customerEnv is: '$customerEnv'"
    "allowedEnvs is: '$($allowedEnvs -join ', ')'"
    "args is: '$($args -join ', ')'"
    "PSBoundParameters is: '$($PSBoundParameters | out-string)'"
}

& $script @testData

# output
& $script @testData
customerEnv is: 'dev'
allowedEnvs is: ''
args is: '-allowedEnvs:, System.Object[]'
PSBoundParameters is: '
Key         Value
---         -----
customerEnv dev

'
```

**Solution:** Define param-block in script for parameters you want to access during discovery, as described in docs.

> Now, of course the [documentation](https://pester.dev/docs/usage/data-driven-tests#providing-external-data-to-tests) says to use a param, but the thing is these variables from the external config work fine without having to declare them in a param block.

Code inside `It { # here }` is executed in Run-phase (also code inside `<Before/After><All/Each> { # here }`). When moving into Run-phase, Pester has special sauce to make any Data set using `-ForEach/TestCases` or passed to the script/container, available as variables to make the transition from Discovery -> Run more seamless. That's how you're able to access the current testcase/foreach-value using `$_`. 

*If `$_` is a hashtable each key will also be added as a named variable* 

> If you add one to the param block, you then need to add all of them or else you get an error like...

Caused by the Parameter-attribute. `[CmdletBinding()]` or `[Parameter()]` turns your script into an advanced function/script which doesn't allow arguments by default. Skip the attribute and it works as seen above.

-----------------

> 1. Should the array variable work in the ForEach without needing to make it a parameter? The variable seems to not be empty - why doesn't it work?

Should not work. It was empty when `-ForEach` was evaluated (Discovery-phase). You can see this using `BeforeDiscovery { Write-Host $customerEnv; Write-Host $allowedEnvs }` which also runs in Discovery.

> 2. How/why is it possible to use the external data without declaring them all as parameters, and why do you need to declare all of them the minute you add a param block? Maybe the docs could make this clearer?

See answers above.
