### ISSUE TITLE
TestDrive:\ provided to New-Item creates folder in current working directory

### ISSUE THREAD

**Issue by jcoryatjr** [pester/Pester#2258]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?

When invoking the New-Item cmdlet  with a path of TestDrive:\ -Force during a test, a new folder in the current working directory with the name of the guid of the TestDrive: provider is created.

### Expected Behavior

Do nothing.

### Steps To Reproduce

```powershell
New-Item -Path TestDrive:\ -ItemType Directory -Force
```

### Describe your environment

Pester version     : 5.3.3 C:\Program Files\WindowsPowerShell\Modules\Pester\5.3.3\Pester.psm1
PowerShell version : 7.3.0
OS version         : Microsoft Windows NT 10.0.19044.0

**Comment by fflaten** [comment]
Thanks for the report.

This is a bug with `New-Item -Force` when directly referencing a PSDrive, though I'm not sure why you'd want to force create an existing PSDrive-root tbh. Closing this since it's not unrelated to Pester. Please create an issue in the [PowerShell repo](https://github.com/powershell/powershell)

Standalone repro
```ps1
Set-Location $home
New-Item $home\NewItemDemo\Drive -ItemType Directory -Force
New-PSDrive -Name Demo -PSProvider FileSystem -Root $home\NewItemDemo\Drive

# Only occurs when using -Force. Without -Force it says the path exists
New-Item -Path Demo:\ -ItemType Directory -Force

# Verify Demo is created in $home (current directory)
Get-Item Drive
```

**Comment by jcoryatjr** [comment]
I use it as a shortcut instead of testing for existence before creating it.

In the unit test I was passing the root of the `TestDrive:\`

```powershell
function MyFunction {
    param (
        [Parameter( Mandatory )]
        [ValidateScript( Test-Path -Path $_ -IsValid )]
        [string]
        $OutputFilePath
    )
    # Do something meaningful

    # Ensure path exists
    New-Item -Path ( Split-Path -Path $OutputFilePath -Leaf ) -Force -ErrorAction SilentlyContinue
    # Write out the results
    $result | Set-Content -Path $OutputFilePath -Force
}
```
