### ISSUE TITLE
Pester not giving the same output as plain Powershell.

### ISSUE THREAD

**Issue by ntaheij** [pester/Pester#2266]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?

Pester filters out unexpected parts of JSON File. Currently Failing on specific part of Pester Script.

In Powershell CLI
```powershell
$json.parameters.policy.value.properties
```
Returns
```
displayName : Deny VNet Peering
policyType  : Custom
mode        : All
description : This policy denies the creation of vNet Peerings under the assigned scope.
metadata    : @{category=Network}
parameters  : @{effect=}
policyRule  : @{if=; then=}
```

Yet in Pester Script
```powershell
It "Properties must contain 'metadata' element" {
    'metadata' | Should -BeIn $json.parameters.policy.value.properties
}
```
Returns
```
@{displayName=Add a Tag Creation Date on Resource Creation; policyType=Custom; mode=All; description=Adds a Tag Creation Date with value of utcNow() on Resource Creation when it doesnt exist; parameters=; policyRule=}
```

### Expected Behavior

Pester doesn't fail action

### Steps To Reproduce

[Used JSON object](https://github.com/pester/Pester/files/10022884/denyVnetPeering.md)

### Describe your environment

Pester version     : 5.3.3 C:\Program Files\WindowsPowerShell\Modules\Pester\5.3.3\Pester.psm1
PowerShell version : 7.2.7
OS version         : Microsoft Windows NT 10.0.22621.0

**Comment by fflaten** [comment]
> **Returns**
> `@{displayName=Add a Tag Creation Date on Resource Creation; policyType=Custom; mode=All; description=Adds a Tag Creation Date with value of utcNow() on Resource Creation when it doesnt exist; parameters=; policyRule=}`
>
> **Expected Behavior**
> Pester doesn't fail action

Repro returns a detailed error when I attempt it.
![image](https://user-images.githubusercontent.com/3436158/202236546-0b745188-7333-4a54-8d63-b7d30206e653.png)

Your PowerShell CLI sample is not equal to the Pester-script.
`'metadata' | Should -BeIn $json.parameters.policy.value.properties` in Pester equals
`'metadata' -in $json.parameters.policy.value.properties` in pure PowerShell.

 `-BeIn` and `-in` is used to check for a value in a collection. You can't use it to check for a property like you're trying to. For that try:
- `'metadata' | Should -BeIn $json.parameters.policy.value.properties.psobject.properties.name`
- or if you're not in strict mode:  `$json.parameters.policy.value.properties.metadata | Should -Not -BeNullOrEmpty`

**Comment by ntaheij** [comment]
Hi there, sorry for the inconvenience. Total oversight on my end.

**Comment by fflaten** [comment]
No worries - glad it worked out 🙂
