### ISSUE TITLE
-BeOfType returns Could not find type when the Type is an Interface

### ISSUE THREAD

**Issue by jeffpatton1971** [pester/Pester#2269]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?

I'm working on a Mongo PowerShell module, written in C# I'm using the MongoDB.Driver 2.18 (latest afaik). What I am seeing is when I test for say getting a list of collections the cmdlet returns an array of objects, if I place that in my test, it fails and lets me know the specific type it wants, when I change to that type, it tells me that type is not loaded. I believe this is because that type is an Interface.

### Expected Behavior

I'm assuming that -BeOfType is basically running GetType() on the output, so if my BaseType is System.Array the test should pass. The cmdlet returns an Interface [MongoDB.Driver.IMongoCollection](https://mongodb.github.io/mongo-csharp-driver/2.8/apidocs/html/T_MongoDB_Driver_IMongoCollection_1.htm)

```powershell
(Get-MongoDBCollection).GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Object[]                                 System.Array
```

The test

```powershell
  Context "Without a CollectionName" {
   It "Should Return System.Array" {
    Get-MongoDBCollection | Should -BeOfType System.Array
   }
  }
```

The result

```powershell
  Context Without a CollectionName
    [-] Should Return System.Array 57ms (55ms|3ms)
     Expected the value to have type [array] or any of its subtypes, but got MongoDB.Driver.MongoCollectionImpl`1[MongoDB.Bson.BsonDocument] with type [MongoDB.Driver.MongoCollectionImpl`1[[MongoDB.Bson.BsonDocument, MongoDB.Bson, Version=2.18.0.0, Culture=neutral, PublicKeyToken=null]], MongoDB.Driver, Version=2.18.0.0, Culture=neutral, PublicKeyToken=null].
     at Get-MongoDBCollection | Should -BeOfType System.Array, D:\CODE\Organizations\PoshMongo\PoshMongo\Tests\Get-MongoDBCollection.Tests.ps1:31
     at <ScriptBlock>, D:\CODE\Organizations\PoshMongo\PoshMongo\Tests\Get-MongoDBCollection.Tests.ps1:31
```

Changing the test to line up with this output

```powershell
  Context "Without a CollectionName" {
   It "Should Return MongoDB.Driver.MongoCollectionImpl`1[MongoDB.Bson.BsonDocument]" {
    Get-MongoDBCollection | Should -BeOfType MongoDB.Driver.MongoCollectionImpl`1[MongoDB.Bson.BsonDocument]
   }
  }
```

The result

```powershell
  Context With a CollectionName
    [-] Should Return MongoDB.Driver.IMongoCollection 11ms (7ms|4ms)
     ArgumentException: Could not find type []. Make sure that the assembly that contains that type is loaded.
```

### Steps To Reproduce

You could grab my code and build it yourself, there are instructions the tests are in a [feature branch](https://github.com/PoshMongo/PoshMongo/tree/5-document-cmdlets-should-be-more-flexible) I'm currently working on. You will want to follow the [build.md](https://github.com/PoshMongo/PoshMongo/blob/5-document-cmdlets-should-be-more-flexible/Build.md) instructions in order to build it. You'll need to have access to mongo someplace.

From the root of the project you should be able to run to what's going on

```powershell
Invoke-Pester -Output Detailed -Tag Collection
```

### Describe your environment

Pester version     : 5.3.3 D:\Documents\PowerShell\Modules\Pester\5.3.3\Pester.psm1
PowerShell version : 7.2.7
OS version         : Microsoft Windows NT 10.0.19044.0

**Comment by fflaten** [comment]
> The result
> 
> ```powershell
>   Context Without a CollectionName
>     [-] Should Return System.Array 57ms (55ms|3ms)
>      Expected the value to have type [array] or any of its subtypes, but got MongoDB.Driver.MongoCollectionImpl`1[MongoDB.Bson.BsonDocument] with type [MongoDB.Driver.MongoCollectionImpl`1[[MongoDB.Bson.BsonDocument, MongoDB.Bson, Version=2.18.0.0, Culture=neutral, PublicKeyToken=null]], MongoDB.Driver, Version=2.18.0.0, Culture=neutral, PublicKeyToken=null].
>      at Get-MongoDBCollection | Should -BeOfType System.Array, D:\CODE\Organizations\PoshMongo\PoshMongo\Tests\Get-MongoDBCollection.Tests.ps1:31
>      at <ScriptBlock>, D:\CODE\Organizations\PoshMongo\PoshMongo\Tests\Get-MongoDBCollection.Tests.ps1:31
> ```

The pipeline will unwrap the array in the first example. Nothing we can do about it unfortunately.
Try: `Should -BeOfType System.Array -ActualValue (Get-MongoDBCollection)`

> The result
> 
> ```powershell
>   Context With a CollectionName
>     [-] Should Return MongoDB.Driver.IMongoCollection 11ms (7ms|4ms)
>      ArgumentException: Could not find type []. Make sure that the assembly that contains that type is loaded.
> ```

`Could not find type [].` basically means it couldn't resolve the requested type. This should've shown the expected value - will fix.

Could you try specifying the type as a literal string because of the backtick (escape char):
```Get-MongoDBCollection | Should -BeOfType 'MongoDB.Driver.MongoCollectionImpl`1[MongoDB.Bson.BsonDocument]'```

**Comment by jeffpatton1971** [comment]
I actually spent most of the morning trying to get it to work as I would have expected. I actually tried that with doublequotes, singlequotes, no quotes, I tried A LOT of different variatiosn on a theme. I did _not_ try your suggestion of -ActualValue.

Basically I looked up the BeOfType code, and it looks like we're just doing an -as [Type] so I started playing around with [System.Type]::GetType and nothing really worked. I think it's how the implementation is setup where it needs a <T> in order to actually have a type to return? Maybe? I don't have the same issue with IMongoClient

```powershell
# JeffreyPatton@FSTNQL1 | 10:45:01 | 11-23-2022 | [10.05GB] D:\CODE\Organizations\PoshMongo\PoshMongo $  [5-document-cmdlets-should-be-more-flexible ↑3 +0 ~2 -0 !]
'MongoDB.Driver.IMongoClient' -as [Type]

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    IMongoClient

# JeffreyPatton@FSTNQL1 | 10:45:07 | 11-23-2022 | [10.05GB] D:\CODE\Organizations\PoshMongo\PoshMongo $  [5-document-cmdlets-should-be-more-flexible ↑3 +0 ~2 -0 !]
'MongoDB.Driver.IMongoCollection' -as [Type]
```

I will update with your suggestions in a few

**Comment by jeffpatton1971** [comment]
Ok here is your first suggestion

```powershell
  Context "Without a CollectionName" {
   It "Should Return MongoDB.Driver.MongoCollectionImpl`1[MongoDB.Bson.BsonDocument]" {
    Get-MongoDBCollection | Should -BeOfType System.Array -ActualValue (Get-MongoDBCollection)
   }
  }
```

This was very angry with me

```powershell
  Context Without a CollectionName
Should: D:\CODE\Organizations\PoshMongo\PoshMongo\Tests\Get-MongoDBCollection.Tests.ps1:27
Line |
  27 |  … ollection | Should -BeOfType System.Array -ActualValue (Get-MongoDBCo …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take
     | pipeline input.

Should: D:\CODE\Organizations\PoshMongo\PoshMongo\Tests\Get-MongoDBCollection.Tests.ps1:27
Line |
  27 |  … ollection | Should -BeOfType System.Array -ActualValue (Get-MongoDBCo …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take
     | pipeline input.

    [-] Should Return MongoDB.Driver.MongoCollectionImpl1[MongoDB.Bson.BsonDocument] 1.79s (1.79s|5ms)
     Expected the value to have type [array] or any of its subtypes, but got $null with type $null.
     at Get-MongoDBCollection | Should -BeOfType System.Array -ActualValue (Get-MongoDBCollection), D:\CODE\Organizations\PoshMongo\PoshMongo\Tests\Get-MongoDBCollection.Tests.ps1:27
     at <ScriptBlock>, D:\CODE\Organizations\PoshMongo\PoshMongo\Tests\Get-MongoDBCollection.Tests.ps1:27
```

And just to quell any fears

```powershell
# JeffreyPatton@FSTNQL1 | 10:52:14 | 11-23-2022 | [10.05GB] D:\CODE\Organizations\PoshMongo\PoshMongo $  [5-document-cmdlets-should-be-more-flexible ↑3 +0 ~2 -0 !]
 New-MongoDBDatabase -DatabaseName 'MyDB' | Out-Null
# JeffreyPatton@FSTNQL1 | 10:52:29 | 11-23-2022 | [10.05GB] D:\CODE\Organizations\PoshMongo\PoshMongo $  [5-document-cmdlets-should-be-more-flexible ↑3 +0 ~2 -0 !]
 New-MongoDBCollection -CollectionName 'myCollection1' | Out-Null
# JeffreyPatton@FSTNQL1 | 10:52:31 | 11-23-2022 | [10.05GB] D:\CODE\Organizations\PoshMongo\PoshMongo $  [5-document-cmdlets-should-be-more-flexible ↑3 +0 ~2 -0 !]
 New-MongoDBCollection -CollectionName 'myCollection2' | Out-Null
# JeffreyPatton@FSTNQL1 | 10:52:32 | 11-23-2022 | [10.05GB] D:\CODE\Organizations\PoshMongo\PoshMongo $  [5-document-cmdlets-should-be-more-flexible ↑3 +0 ~2 -0 !]
Get-MongoDBCollection

CollectionNamespace : MyDB.myCollection1
Database            : MongoDB.Driver.MongoDatabaseImpl
DocumentSerializer  : MongoDB.Bson.Serialization.Serializers.BsonDocumentSerializer
Indexes             : MongoDB.Driver.MongoCollectionImpl`1+MongoIndexManager[MongoDB.Bson.BsonDocument]
Settings            : AssignIdOnInsert=True;GuidRepresentation=CSharpLegacy;ReadConcern={ };ReadEncoding=null;ReadPreference={ Mode : Primary };WriteConcern={ };WriteEncoding=null

CollectionNamespace : MyDB.myCollection2
Database            : MongoDB.Driver.MongoDatabaseImpl
DocumentSerializer  : MongoDB.Bson.Serialization.Serializers.BsonDocumentSerializer
Indexes             : MongoDB.Driver.MongoCollectionImpl`1+MongoIndexManager[MongoDB.Bson.BsonDocument]
Settings            : AssignIdOnInsert=True;GuidRepresentation=CSharpLegacy;ReadConcern={ };ReadEncoding=null;ReadPreference={ Mode : Primary };WriteConcern={ };WriteEncoding=null


# JeffreyPatton@FSTNQL1 | 10:52:38 | 11-23-2022 | [10.05GB] D:\CODE\Organizations\PoshMongo\PoshMongo $  [5-document-cmdlets-should-be-more-flexible ↑3 +0 ~2 -0 !]
```

**Comment by jeffpatton1971** [comment]
Second suggestion

```powershell
  Context "Without a CollectionName" {
   It "Should Return MongoDB.Driver.MongoCollectionImpl`1[MongoDB.Bson.BsonDocument]" {
    Get-MongoDBCollection | Should -BeOfType 'MongoDB.Driver.MongoCollectionImpl`1[MongoDB.Bson.BsonDocument]'
   }
  }
```

and the result

```powershell
  Context Without a CollectionName
    [-] Should Return MongoDB.Driver.MongoCollectionImpl1[MongoDB.Bson.BsonDocument] 57ms (52ms|5ms)
     ArgumentException: Could not find type []. Make sure that the assembly that contains that type is loaded.
```

**Comment by jeffpatton1971** [comment]
In the interim, so I can move forward with my work I've just done a simple string check

```powershell
  Context "Without a CollectionName" {
   It "Should Return MongoDB.Driver.MongoCollectionImpl`1[MongoDB.Bson.BsonDocument]" {
    (Get-MongoDBCollection).GetType().FullName | Should -Be 'System.Object[]'
   }
  }
```

please let me know if there is anything else you need.

**Comment by fflaten** [comment]
> Ok here is your first suggestion
> 
> ```powershell
>   Context "Without a CollectionName" {
>    It "Should Return MongoDB.Driver.MongoCollectionImpl`1[MongoDB.Bson.BsonDocument]" {
>     Get-MongoDBCollection | Should -BeOfType System.Array -ActualValue (Get-MongoDBCollection)
>    }
>   }
> ```

Nope, skip the pipeline completely to avoid PowerShell unwrapping your collection. Just like you have to use `Get-Member -InputObject (Get-MongoDBCollection)` to check the collection/array itself. Ex:

```ps1
It "Should Return MongoDB.Driver.MongoCollectionImpl`1[MongoDB.Bson.BsonDocument]" {
    Should -BeOfType System.Array -ActualValue (Get-MongoDBCollection)
}
```

**Comment by jeffpatton1971** [comment]
Wouldn't that test always return true? I mean I could potentially replace that with say Get-Service and it ought to work right?

**Comment by jeffpatton1971** [comment]
at any rate corrected suggestion1 ;)

```powershell

**Comment by fflaten** [comment]
> Wouldn't that test always return true? I mean I could potentially replace that with say Get-Service and it ought to work right?

Yes, I simply corrected your first example in the issue to show how to test a collection-type. 🙂
I'd personally skip it since it was a basic object-array this time and not a specialized collection or strongly typed array that makes sense.

As for the second attempt, you should stick with string-matching. `MongoCollectionImpl` is an [internal class](https://github.com/mongodb/mongo-csharp-driver/blob/b9b80f1969db5c92f45953e192d0d9f581fe0a3f/src/MongoDB.Driver/MongoCollectionImpl.cs#L34), so Pester will not be able to resolve the type. 

Try something like: `((Get-MongoDBCollection)[0].GetType().ToString() | Should -Be 'Whatever ToString returns'`

**Comment by jeffpatton1971** [comment]
Yea, that's basically what I'm doing, after digging in this morning and even re-writing some portions using the legacy driver, realized just doing a simple match on that was at least as good as a regular test. Hopefully not causing too much work for you, but thanks for diggin in with me.

**Comment by fflaten** [comment]
No problem. Ended up fixing a broken error message, so worth it (related PR) 😃
Closing this now as it wasn't interface-specific and there's nothing more we can do here IMO.
