### ISSUE TITLE
For information : updating PsModuleCache Action

### ISSUE THREAD

**Issue by LaurentDardenne** [pester/Pester#2280]
### Checklist

- [X] Feature request has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### Summary of the feature request

The [latest version](https://github.com/potatoqualitee/psmodulecache/blob/main/README.md#pnppowershell) of Action PsmoduleCache can answer [this remark](https://github.com/pester/Pester/blob/main/.github/workflows/code-analysis.yml#L26).

**Comment by fflaten** [comment]
Thanks for the tip - and your massive contributions to PSModuleCache 👏 
Will look into this soon. We have to upgrade anyways due to the output-deprecation also.
