### ISSUE TITLE
Add possibility for supplying two or more Pester result objects when using ConvertTo-NUnitReport / Export-NUnitReport

### ISSUE THREAD

**Issue by erikgraa** [pester/Pester#2281]
### Checklist

- [X] Feature request has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### Summary of the feature request

The parameter _Result_ in the cmdlets `ConvertTo-NUnitReport` and `Export-NUnitReport` only take a single object.

If possible it would be great to be able to concatenate/merge multiple result objects from a Pester-run into the same NUnitReport.

### How should it work?

```
$p = @()
$p += Invoke-Pester -Path tests1.ps1 -Passthru
$p += Invoke-Pester -Path tests2.ps1 -Passthru
$p | ConvertTo-NUnitReport -Path TestResults.xml

$p = @()
$p += Invoke-Pester -Path tests1.ps1 -Passthru
$p += Invoke-Pester -Path tests2.ps1 -Passthru
$p | Export-NUnitReport -Path TestResults.xml
```

**Comment by fflaten** [comment]
Thanks for the feedback :)
This feels like something a third-party module or console app should solve. If this is common practice, I guess there's multiple solutions out there already supporting NUnit 2.5 schema.

**Comment by erikgraa** [comment]
Hi :)

It does seem like it is available in e.g.  Azure DevOps' `PublishTestResults@2` task using the `mergeTestResults` parameter (although I haven't gotten around to trying it).
