### ISSUE TITLE
Allow for multi-line parameters in Should function

### ISSUE THREAD

**Issue by TofuBug** [pester/Pester#2282]
### Checklist

- [X] Feature request has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### Summary of the feature request

I would like to see the ability to use the ` to provide the Should function its parameters in individual lines.

```
Should `
     -Contain `
     -ExpectedValue (
         [WpfHandlerVisitor].
             GUID
     )
```

Right now this throws an error from the dynamicparam block in the Should function

```
if ($myLine -match '^\s{0,}should\s{1,}(?<Operator>[^\-\@\s]+)')
```

I'd like to see the Tilde ( ` ) added to the "NOT" list of characters

```
if ($myLine -match '^\s{0,}should\s{1,}(?<Operator>[^\-\@\s`]+)')
```

**Comment by fflaten** [comment]
Hi. Thanks for the feedback!

This is a covered by #2138 which has a planned action so I'll close this. 

As a workaround for now, keep the operator on the same line. The rest can be on different lines. See comment in related issue.

**Comment by TofuBug** [comment]
> Hi. Thanks for the feedback!
> 
> This is a covered by #2138 which has a planned action to remove that legacy syntax check, so I'll close this.
> 
> As a workaround for now, keep the operator on the same line. The rest can be on different lines. See comment in related issue.

Guess I just wasn't searching the issues broadly enough to find that. I appreciate the information, and the advice.

**Comment by fflaten** [comment]
No worries - it was hidden in a bug report :)
