### ISSUE TITLE
Lazy loading doesn't work with Pester

### ISSUE THREAD

**Issue by SHIERZHA** [pester/Pester#2289]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [x] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?

Lazy object is not working when it's invoked in Pester. $testLazy["key"] is not loaded when getting accessed.

```
Describe 'LazyLoad' {
    It 'Should build cluster with vCenter' {
        $testLazy = [System.Collections.Generic.Dictionary[string,object]]::new()
        $testLazy["key"] = [Lazy[object]]::new([System.Func[object]] {"value"}.GetNewClosure())
        $testLazy["key"] -eq "value" | Should -BeTrue
    }
}
```

Same script following running in PowerShell session (without Pester) works fine and  $testLazy["key"] is loaded
```
$testLazy = [System.Collections.Generic.Dictionary[string,object]]::new()
$testLazy["key"] = [Lazy[object]]::new([System.Func[object]] {"value"}.GetNewClosure())
$testLazy["key"]
```

### Expected Behavior

$testLazy["key"] should be loaded when invoked

### Steps To Reproduce

 Code in "What is the issue part"

### Describe your environment

PowerShell 7.3.0
Pester 5.3.3

**Comment by nohwnd** [comment]
It works, you return Lazy<object> which is not equal to "value".  `$testLazy["key"] -eq "value"` is `$false`.  You need to get the value using `.Value`.

```powershell
Describe 'LazyLoad' {
    It 'Should build cluster with vCenter' {
        $testLazy = [System.Collections.Generic.Dictionary[string,object]]::new()
        $testLazy["key"] = [Lazy[object]]::new([System.Func[object]] {"value"}.GetNewClosure())
        $testLazy["key"].Value -eq "value" | Should -BeTrue
    }
}
```
