### ISSUE TITLE
Changes in exit code handling from Pester 5.1.0 through 5.4.0

### ISSUE THREAD

**Issue by erikgraa** [pester/Pester#2292]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?

After updating from Pester `5.0.4 `to the latest `5.4.0` version CIs were suddenly failing with exit code 1.

I did some troubleshooting by attempting the next version after 5.0.4, and found this behavior was changed from `5.1.0` onwards.

I use Azure DevOps and the gist of the Pester testing is first a `PowerShell` task with Invoke-Pester, whereupon the results are published with the `PublishTestResults` task.

In Pester `5.0.4`, both tasks succeed even though some tests fail, so long as the `PublishTestResults` task does not have `failTaskOnFailedTests: true`

![image](https://user-images.githubusercontent.com/20067955/216630653-d07561aa-34e2-4730-a52a-016596ca90d3.png)

From Pester `5.1.0` onwards, to accomplish the same, one needs to add `ignoreLASTEXITCODE: true` to the `PowerShell` task, if not:
![image](https://user-images.githubusercontent.com/20067955/216630288-1e6787e7-2cc8-47ce-825c-e644a874aa46.png)

**NOTE**: This seems to be related to #1797.

**BTW**: I really enjoy the new CI Output!

### Expected Behavior

I'm unsure about the expected behavior.

The release notes for `5.1.0`  sparsely discusses this change and it would be nice to have a discussion into what is the current best practice in order to run tests in Azure DevOps when one structures the Publish Task whether to fail the pipeline when the Pester task has failed tests.

Is `ignoreLASTEXITCODE: true` the best way forward?

### Steps To Reproduce

Using Pester `5.0.4`, this will not stop the pipeline:

```powershell
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: Invoke-Pester -Path .\
    ignoreLASTEXITCODE: false # boolean. Ignore $LASTEXITCODE. Default: false.
```

Using Pester `5.1.0` through `5.4.0`, this will stop the pipeline:

```powershell
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: Invoke-Pester -Path .\
    ignoreLASTEXITCODE: false # boolean. Ignore $LASTEXITCODE. Default: false.
```

Using Pester `5.1.0` through `5.4.0`, this will not stop the pipeline:

```powershell
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: Invoke-Pester -Path .\
    ignoreLASTEXITCODE: true # boolean. Ignore $LASTEXITCODE. Default: false.
```

**Comment by johlju** [comment]
The default should be that it should not fail on tests failing unless `Exit` or `Throw` is set to `$true`. Are they false in your case?

```powershell
# shows default value as false.
PS> $a = New-PesterConfiguration
PS> $a.Run.Throw.Value          
False
PS> $a.Run.Exit.Value           
False
```

 It does not fail in the pipeline here when tests fail (see line 7715): https://dev.azure.com/dsccommunity/SqlServerDsc/_build/results?buildId=7415&view=logs&j=8af7cf9c-43a1-584d-6f5c-57bad8880974&t=a93ba588-7f3e-5259-6924-3f054a327451&l=7715

**Comment by fflaten** [comment]
Pester 5.1.0 and later will always set the exit code equal to the number of failed tests (inspired by nUnit i assume). This is done to be consistent as we previously had an issue where a code executed prior to OR during your Pester-tests would set the exit code and then CI would fail even though all your tests passed. Any remaining code your script/step will still run though.

Setting `Run.Exit = $true` will also run `exit`, effectively killing the PowerShell-process -> ignore the remaining parts of your script.

In Azure DevOps you could set `ignoreLASTEXITCODE`, or you could make your publishing-steps run even on failure using `condition: succeededOrFailed()`. That's how Pester's own pipeline works.

https://github.com/pester/Pester/blob/d81fdbc46318d6c3486c241fa82d9749df5c2031/azure-pipelines.yml#L170-L175

**Comment by erikgraa** [comment]
Thanks for the clarification, will adjust my scripts to this new behavior!
