### ISSUE TITLE
Idea: Add suggestions for how to fix / remedy an issue when a test fails

### ISSUE THREAD

**Issue by erikgraa** [pester/Pester#2293]
### Checklist

- [X] Feature request has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### Summary of the feature request

I think I have seen a similar feature request before, perhaps it was in the form of a pull request for version 4. Anyway, I was unable to find it.

It would be nice to be able to add suggestions to an `It` test for how to fix whatever is causing a failed test, e.g. when you are doing infrastructure testing.

I suppose one could also add such in the `It` text itself, or `throw` a useful suggestion.

### How should it work?

```powershell
It 'JSON file should adhere to schema' `-Suggestion 'Check that you used the latest version of [..] available at [..]'` { }
```

```powershell
Running tests from 'C:\Example.Tests.ps1'
Describing [..]
  [-] JSON file should adhere to schema
   Exception: The JSON is not compatible with schema [..]
   at <ScriptBlock>, C:\Example.Tests.ps1:7
   SUGGESTION: Check that you used the latest version of [..] available at [..]
Tests Passed: 0, Failed: 1, Skipped: 0 NotRun: 0
```

**Comment by fflaten** [comment]
Thanks for the feedback and an interesting idea! I like the simplicity and clean look of this.

One thing to keep in mind is that users may often have multiple `Should`-assertions inside a single test and the exception is thrown by the first assertion that fails (unless you use `Should.ErrorAction = 'Continue'`). This means that a test may require multiple suggestions based on which part of the test that fails.

So while not as pretty as the suggestion above, you could use `Should ... -Because 'reason'` to provide some suggestions. Example:

```ps1
$config = New-PesterConfiguration
$config.Run.ScriptBlock = {
    Describe 'demo' {
        It 'Prereqs check' {
            1 | Should -Be 2 -Because 'two is better than one'
            Get-Command -Name notepad.exe -ErrorAction SilentlyContinue | Should -Not -BeNullOrEmpty -Because 'notepad should be installed'
        }
    }
}
# Using this to let both assertions in a single test run and fail
$config.Should.ErrorAction = 'Continue'

Invoke-Pester -Configuration $config

# output
Starting discovery in 1 files.
Discovery found 1 tests in 48ms.
Running tests.
[-] demo.Prereqs check 26ms (24ms|2ms)
 [0] Expected 2, because two is better than one, but got 1.
 at 1 | Should -Be 2 -Because 'two is better than one', :5
 at <ScriptBlock>, <No file>:5
 [1] Expected a value, because notepad should be installed, but got $null or empty.
 at Get-Command -Name notepad.exe -ErrorAction SilentlyContinue | Should -Not -BeNullOrEmpty -Because 'notepad should be installed', :6
 at <ScriptBlock>, <No file>:6
Tests completed in 105ms
Tests Passed: 0, Failed: 1, Skipped: 0 NotRun: 0

**Comment by erikgraa** [comment]
I was not aware of the `-Because` parameter, sounds like a perfect fit for my use case. Thanks!
