### ISSUE TITLE
Script block streams suppressed

### ISSUE THREAD

**Issue by DarkLite1** [pester/Pester#2297]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?

Executing the code below should display all streams. However, we notice that the streams in the script block are not visible. Under some circumstances the `verbose` stream is displayed and the `warning` stream is not. But this I can't seem to duplicate.

Thank you for having a look. 

### Expected Behavior

Displaying all streams in all circumstances.

### Steps To Reproduce

```powershell
$scriptBlock = {
    Write-Verbose 'ScriptBlock verbose message'
    Write-Warning 'ScriptBlock warning message'
}

Describe 'stream' {
    It 'verbose is displayed' {
        Write-Verbose 'Verbose message'
    }
    It 'warning is displayed' {
        Write-Warning 'Warning message'
    }
    It 'in script block is displayed' {
        $scriptBlock # not displayed, bug?
    }
}
```

### Describe your environment

Pester version     : 5.4.0 C:\Program Files\WindowsPowerShell\Modules\Pester\5.4.0\Pester.psm1
PowerShell version : 5.1.14393.5582
OS version         : Microsoft Windows NT 10.0.14393.0

**Comment by DarkLite1** [comment]
Thank you @fflaten for getting back to me. Just tried your suggestion and still no luck:
```powershell
$scriptBlock = {
    $VerbosePreference = 'continue'
    $WarningPreference = 'continue'
    Write-Verbose 'ScriptBlock verbose message'
    Write-Warning 'ScriptBlock warning message'
}

Describe 'stream' {
    It 'verbose is displayed' {
        Write-Verbose 'Verbose message'
    }
    It 'warning is displayed' {
        Write-Warning 'Warning message'
    }
    It 'in script block is displayed' {
        $scriptBlock # not displayed, bug?
    }
}
```

**Comment by fflaten** [comment]
Oh, you're actually not invoking the scriptblock at all 😁 

Try:
```ps1
It 'in script block is displayed' {
        & $scriptBlock # not displayed, bug?
    }
```

**Comment by DarkLite1** [comment]
Stupid me! Been looking at code too long...

When testing this:
```powershell
$scriptBlock = {
    # $VerbosePreference = 'continue'
    # $WarningPreference = 'continue'
    Write-Verbose 'ScriptBlock verbose message'
    Write-Warning 'ScriptBlock warning message'
}

Describe 'stream' {
    It 'verbose is displayed' {
        Write-Verbose 'Verbose message'
    }
    It 'warning is displayed' {
        Write-Warning 'Warning message'
    }
    It 'in script block is displayed' {
        & $scriptBlock # not displayed, bug?
    }
}
```
We see this error popping up:
![image](https://user-images.githubusercontent.com/10828570/218109002-33f82035-f155-4808-8e9c-8a98c047281b.png)

Even when starting clean. Am I still missing something here?

**Comment by fflaten** [comment]
I'm a bit tired apparently 🥱 

The scriptblock has to be defined inside `It/BeforeAll/BeforeEach`. It's only accessible during Discovery when defined in the root.

**Comment by DarkLite1** [comment]
Thanks @fflaten :)
