### ISSUE TITLE
Using Run.Exit and Run.PassThru causes unexpected output to stdout

### ISSUE THREAD

**Issue by codaamok** [pester/Pester#2300]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?

While using the Run.PassThru and Run.Exit configuration options, a Pester object is unexpectedly dropped to the output stream if an exception is raised. The object is not in the output stream if an exception is not raised.

See screenshot below:

![image](https://user-images.githubusercontent.com/6683266/218275669-67dce22e-22b2-4f3d-9887-91aef6f72d30.png)

- `test.ps1` contains some blocks with a single test. `throw` is used in `BeforeAll` but it can be used in any block to reproduce the issue
- The test script file is called from `testrun.ps1` and the output should be assigned to `$r` within the scope of the script file
- `$r` isn't dropped to the output stream, however we can see a Pester output object in the console which called `testun.ps1`

In order to reproduce, both PassThru and Exit must be true.

## test.ps1

```powershell
Describe 'Some test' {

    BeforeAll {
        Write-Host 'hello world from beforeall'
        throw 'some error'
    }

    AfterAll { 
        Write-Host 'hello world from afterall'
    }

    it 'should be true' {
        throw 'some error'
        Write-Host 'within a test'
        $true | Should -Be $true
    }
}
```

## testrun.ps1
```powershell
$Container = New-PesterContainer -Path 'C:\path\to\test.ps1'

$Configuration = New-PesterConfiguration -Hashtable @{
    Run = @{
        PassThru = $true
        Exit = $true
        Container = $Container
        SkipRemainingOnFailure = 'Container'
    }
    Output = @{
        Verbosity = 'None'
    }
    TestResult = @{
        Enabled = $false
        TestSuitName = 'abc'
    }
}

$r = Invoke-Pester -Configuration $Configuration
```

### Expected Behavior

I expected to not see any output in the given code example.

### Steps To Reproduce

1) Create `test.ps1` with the above code
2) Create `testrun.ps1` with the above code and update line 1 for path to `test.ps1`
3) Call `testrun.ps1`

### Describe your environment

```
Pester version     : 5.3.1 C:\Users\adamp\OneDrive - Adam Cook\Documents\PowerShell\Modules\Pester\5.3.1\Pester.psm1
PowerShell version : 7.3.2
OS version         : Microsoft Windows NT 10.0.22621.0
```

### Possible Solution?

@fflaten suggests is [discord](https://discord.com/channels/180528040881815552/447476910499299358/1073885781854261278) to:

> We should likely ignore passthru when run.exit is set and there is a failed test. It's returned as text so it wouldn't provide anything more than the normal colored output

**Comment by fflaten** [comment]
Fixing this is a minor breaking change.

If you run `Invoke-Pester ...` directly in the terminal, the result would be printed since the process is killed before the result is assigned the variable. However, when you use `Invoke-Pester` inside a script like `testrun.ps1`, then Pester will only exit the script and not kill the process. That's when it gets messy:

- If you call `testrun.ps1` which includes `$r = Invoke-Pester` to catch the result (like your sample), then a failed run would not be assigned and unexpectedly returned to the screen.
- If you do `$r = ./testrun.ps1` instead then you'd be able to catch both success and failure atm.
