### ISSUE TITLE
Tests fails when passing a scriptblock to `InModuleScope` that mocks inherit of a class, when `UseBreakpoints` is set to`$false`

### ISSUE THREAD

**Issue by johlju** [pester/Pester#2309]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?

This issue is just meant to track for other users how to solve it if encountered. This issue can be closed as it is will be solved by #2306.

When mocking a class that inherits from a class that is being tested one way is to have `using module` inside a here-string. The string is converted to a scriptblock that is then called by `InModuleScope`. But if `UseBreakpoints` is set to`$false` this fails with an exception.

Example:

```powershell
BeforeAll {
    $inModuleScopeScriptBlock = @'
using module DscResource.Base

class MyMockResource : ResourceBase
{
    [DscProperty(Key)]
    [System.String]
    $MyResourceKeyProperty1

    [System.Collections.Hashtable[]] Compare()
    {
        return $null
    }
}

$script:mockResourceBaseInstance = [MyMockResource]::new()
'@

    InModuleScope -ScriptBlock ([Scriptblock]::Create($inModuleScopeScriptBlock))
}
```
When run it throws the following error.
```
[-] Context ResourceBase\Test().When the system is in the desired state failed
   ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than or equal to the size of the collection. (Parameter 'index')
   at <ScriptBlock>, <No file>:19
```

### Expected Behavior

To pass without the need to add a default empty constructor.

### Steps To Reproduce

See possible solution.

### Describe your environment

n/a

### Possible Solution?

Add a default empty constructor to the mocked class in your test.

```powershell
BeforeAll {
    $inModuleScopeScriptBlock = @'
using module DscResource.Base

class MyMockResource : ResourceBase
{
    [DscProperty(Key)]
    [System.String]
    $MyResourceKeyProperty1

    MyMockResource () {}

    [System.Collections.Hashtable[]] Compare()
    {
        return $null
    }
}

$script:mockResourceBaseInstance = [MyMockResource]::new()
'@

    InModuleScope -ScriptBlock ([Scriptblock]::Create($inModuleScopeScriptBlock))
}
```

**Comment by fflaten** [comment]
Thanks for sharing. Closing as requested as bug is tracked in #2306
