### ISSUE TITLE
Another Performance report between v4 and v5 :-)

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [pester/Pester#2335]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?

So following on from [the discussion here](https://github.com/pester/Pester/discussions/2331) Jakub identified that Get-Command was slow and updated with [a3d207078f8309833a8d3116efa2d2bc09b99a3e](https://github.com/pester/Pester/commit/a3d207078f8309833a8d3116efa2d2bc09b99a3e) for 5.4.1

This is beautiful and has reduced the time, however, as is often the case I have uncovered another place where v4 is faster than v5.

https://github.com/pester/Pester/blob/4e3b5cd62b6d8a6a805861d16d032c09d4220f80/src/Main.ps1#L166-L171 

As before I am using Profiler and dbachecks in a container to test this. On the left Pester 5.4.1, on the right Pester 5.4.1 with those lines commented out

![image](https://user-images.githubusercontent.com/6729780/230151840-8aa0d2db-59b0-4927-9a68-9e4a4ca48804.png)

For completeness - top duration from Profiler with Pester v4.10.1 

![image](https://user-images.githubusercontent.com/6729780/230152290-e7969b25-2dd9-4205-9bd6-17ddefb11168.png)

and with Pester v5.4.1
![image](https://user-images.githubusercontent.com/6729780/230152434-47e1ef5a-9760-4382-aac3-76e38999dfd0.png)

### Expected Behavior

v5 to be faster than v4 (because thats what I keep telling people :-) )

### Steps To Reproduce

Follow the instructions 
[![image](https://user-images.githubusercontent.com/6729780/230152708-d6a0db6a-872f-4cb6-ae46-b69ca446883a.png)](https://github.com/dataplat/dbachecks/blob/main/developing/Howto.md)

Run the comparison as per  [the discussion here](https://github.com/pester/Pester/discussions/2331)

**Comment by fflaten** [comment]
Thanks for report. This is new code and should only affect module import IIRC. I forgot to benchmark import when I wrote it, so will look into it.

Is your container very resource-limited by any chance? 😅

**Comment by SQLDBAWithABeard** [comment]
I dont think I am that limited :-)
![image](https://user-images.githubusercontent.com/6729780/230191227-af4c4c27-83e1-4743-98bc-cad0c97d0b09.png)

annoyingly becuase dbachecks was written for Pester v3 and updated for v4 it needs to support both v4 and v5 which is requiring a complete re-write and also means that my code (at the moment) is removing and importing the stated version of Pester

**Comment by SQLDBAWithABeard** [comment]
Can confirm that if I validate the Pester version and only import if needed the code doesn't run. Hat tip to @fflaten 

https://github.com/dataplat/dbachecks/commit/e2fd913b69d46277225843449e9cd2517e84cad6

I wonder if it makes a case for a headless Pester module which safes CPU cycles not doing unnecessary things ???

Thoughts??

**Comment by fflaten** [comment]
I don't think there's much unnecessary to remove. Most things that can make it slower can be disabled, ex. output. 

This help-related part might be the only exception as it only affects docs, primarily the website. So worst case we could consider hiding it behind a module parameter, but will Troy to improve perf first.

**Comment by fflaten** [comment]
This is weird. It's only slow in the release build.
```
Dev build (psm1 dot sources ps1-files): 0.15sec
Release build (inline/merged to single psm1): ~3sec
```

**Comment by nohwnd** [comment]
My modest guess is that in the merged mode the whole definition (whole psm1 with multiple thousand lines) is reparsed multiple times, I am will try to prove that theory with Profiler, PerfView and VS ( I need more content for PSConfEU 😁 ).

**Comment by nohwnd** [comment]
Yup. 
![image](https://user-images.githubusercontent.com/5735905/230345276-3a608e61-1bb8-4b04-be87-210533f866e7.png)

![image](https://user-images.githubusercontent.com/5735905/230345606-fa471e39-18ef-49c5-bea5-f5d9d011b714.png)

**Comment by fflaten** [comment]
Please do! I assume something similar myself as help isn't loaded in commandmetadata. Likely not as bad if we used MAML help.

**Comment by fflaten** [comment]
Great find! Cache miss every time? Is the provided token-cache per command maybe? Because they all share the same `rootAst` so ideally it'd be shared to only get one 150ms hit. Anyways, won't be fixed in PS-versions for now.

Parameter help for dynamic parameters aren't visible with `Get-Help`, only in parameter-attribute. So only relevant for command ref-docs. I'll either use a module parameter (ugly) or provide the synopsis as a parameter to `Add-ShouldOperator` (duplicate source) - both messy.

Another minor reason to move external help, or even generate MAML from comment-help as a first step if they can co-exist.
