### ISSUE TITLE
Not reloading PowerShell class before new test run

### ISSUE THREAD

**Issue by zombiemaker** [pester/Pester#2349]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?

Pester or PowerShell is not loading newer version of PowerShell class being tested in the same PowerShell session.  A new PowerShell session has to be created in order to get the test results using updated version of the PowerShell class being tested.

### Expected Behavior

Pester should reload the (updated) PowerShell class definition in the same PowerShell session and get correct test results using the new PowerShell class definition.

Using example in Steps to Reproduce section 

- Session A Run #2 should get the opposite result from Session A Run #1 and the same result as Session B Run #1

### Steps To Reproduce

PROCEDURE TO REPRODUCE BUG

- Create ps1 file (e.g., MyPsClass.ps1) containing PowerShell class definition
- Create ps1 file (e.g., MyPsClass.Unit.Tests.ps1) container Pester tests for the MyPsClass
- Start PowerShell session A
- Run Pester test (Session A Run #1) using Invoke-Pester command
- Get whatever result (pass or fail) from the test
- Change the MyPsClass.ps1 file to make the test result change from pass -> fail or fail -> pass
- Re-run Pester test (Session A Run #2) using Invoke-Pester command
- Get the SAME result from Session A Run #1
- Start PowerShell session B
- Run Pester test (Session B Run #1) using Invoke-Pester command
- Get the opposite (and correct) result from Session A Run #1
- Go back to Session A
- Re-run Pester test (Session A Run #3) using Invoke-Pester command
- Still get same result as Session A Run #1 even though Session B gets different result

### Describe your environment

Pester version     : 5.4.1 /home/username/.local/share/powershell/Modules/Pester/5.4.1/Pester.psm1                   
PowerShell version : 7.3.4
OS version         : Unix 5.15.90.

### Possible Solution?

Spawn a new PowerShell session for each run of Pester tests?

**Comment by zombiemaker** [comment]
The issue with PowerShell seems has been [a known issue](https://stackoverflow.com/questions/40881824/reloading-a-modified-class-in-powershell) for awhile.  The issue when running Pester tests seems to be resolved using the solution described in the link:

pwsh -Command { Invoke-Pester [pester-test-file] }

Can the Invoke-Pester command be written to do this form of function call?

**Comment by fflaten** [comment]
Unfortunately classes in PowerShell are far from perfect, and like testing binary modules it's recommended to use fresh sessions.

It would not make sense to provide an option for that in `Invoke-Pester` in my opinion. We'd have to serialize and pass through both the config/parameters and the results etc. It's already simple for the user to do it manually like your suggestion above. Issues like this will help users find your workaround. 🙂 

**Tip:** In VSCode you have the option to make debug/launch-command run in a temporary console typically to address this common issue. Ex.

```
// .vscode/launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Run Pester Tests",
            "type": "PowerShell",
            "request": "launch",
            "script": "Invoke-Pester -Path \"${workspaceFolder}/tests\" -Output Detailed",
            "args": [],
            "createTemporaryIntegratedConsole": true,
        }
    ]
}
```

You could also set `"powershell.debugging.createTemporaryIntegratedConsole": true` in your `settings.json` to have it as a default for all PowerShell debugging.

**Comment by zombiemaker** [comment]
Thanks for work around!  Did not know about the createTemporaryIntegratedConsole option.
