### ISSUE TITLE
BeforeEach and AfterEach problems with nested blocks

### ISSUE THREAD

**Issue by dlwyatt** [pester/Pester#236]
Currently, this code won't work properly:

``` posh
Describe 'Something' {
    InModuleScope someModule {
        BeforeEach { Do-Something } # This will NOT be executed before each It block.
    }
}
```

This is because the code that parses the Describe block is naïve about how it treats nested braces.  It looks for a BeforeEach command as a direct child of the Describe block.  Even though there's logically no reason why the InModuleScope command here should be a problem, it will cause that BeforeEach block to be ignored.  (Likewise if you used something like try/catch with the BeforeEach inside of it.)

This is mainly because we still need to support PowerShell v2, where the AST isn't available to make it easier to make smarter decisions.

However, we should see about making this code behave better in a future release.  The only time we don't want to parse and process the BeforeEach / AfterEach blocks inside a nested block is if they are inside a nested test group (Context, in this case.)  All other nested blocks should be fine.

**Comment by havcaaren** [comment]
Are there any updates in this matter since '14?

**Comment by dlwyatt** [comment]
Not yet, but it's something that should be easy to address for PowerShell v3+.  (We already have a branch in the code that uses the AST for parsing; the old code I referred to when I created this issue is only used if you're running Pester in PowerShell v2.  This was to enable breakpoints in the BeforeEach / etc blocks, something that I couldn't figure out how to do with the older code.)

If you needed to execute a particular Tests file in v2, then this wouldn't be any help at all, but I suspect that we'll be seeing more and more modules that require a newer version anyway.  (Certainly anything DSC-related, and maybe other modules as well.  Once support for Windows Server 2008 R2 ends, there won't be any supported operating system left that can even have PSv2.)

**Comment by havcaaren** [comment]
> Not yet, but it's something that should be easy to address for PowerShell v3+. (We already have a branch in the code that uses the AST for parsing;
That's what I'm interested in. I'm using PowerShell 5. Could you, please, specify where I can find the new code? Is this the one in DevelopmentV4 branch?

**Comment by dlwyatt** [comment]
It's already in the release.  By "branch" I wasn't referring to source control, but to code execution.  :)  https://github.com/pester/Pester/blob/master/Functions/SetupTeardown.ps1#L138

However, it still doesn't currently support nested blocks.  I just said that it would be much easier to fix in the `Add-SetupAndTeardownV3` function than in the `Add-SetupAndTeardownV2` code.

**Comment by havcaaren** [comment]
Oh, now it's clear. Thanks :)

**Comment by it-praktyk** [comment]
I assume that the issue can be closed now. Feel free to reopen if you need more assistance.
