### ISSUE TITLE
Mock Azure cli command

### ISSUE THREAD

**Issue by ktran1005** [pester/Pester#2360]
### Checklist

- [X] Feature request has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### Summary of the feature request

Hi everyone, I am reaching out to ask if anyone knows a way to mock Azure CLI. I am currently having a ps script that has something like this:
```powershell
$azResources = (az resource list --resource-group ...) | ConvertFrom-Json
if ($LASTEXITCODE -ne 0) { throw "az resource list returned a $LASTEXITCODE exit code." }
```

This is how my mock looks like:
`Mock az { JSON format here }`

I want to mock the az command in pester but receiving this error: **RuntimeException: az resource list returned a 1 exit code.** I have reviewed other issues from the past about mocking azure cli but all of them are wrapped in a PS function. I wonder that if we are able to mock azure cli if it is not wrapped in a PS function, Thanks!

**Comment by fflaten** [comment]
Hi. Are you sure it the mock didn't work? Did you verify the contents of `$azResources`? And the value of `$LASTEXITCODE` before?

`$LASTEXITCODE` is only set by applications, so the value 1 could be from a previous command before this code. If the mock works as expected, it wouldn't change that variable to 0.

**Comment by ktran1005** [comment]
Hi @fflaten, I know the return value from the az command will be under JSON format so my actual mock looks like this:
`Mock az {

            '[
                {
                "id": "something...",
                "name": "something..."
                }
            ]'
        } -ParameterFilter {"$args" -match 'resource list'}`
then I passed arguments for the script that I want to test:
`& "$PSScriptRoot\myscript.ps1" $arg1 $arg2...`
`Should -Invoke az `
The **$LASTEXITCODE** happens after executing the line `$azResources = (az resource list --resource-group ...) | ConvertFrom-Json` from the ps script

**Comment by fflaten** [comment]
> Update: I checked the content of `$azResources`. It matches with the value I set in my mock.

Then `$LASTEXITCODE` is changed by something else in the script if it changes during the test. Pester only modifies it at the end of `Invoke-Pester` to number of failed tests.

Isolated repro:
```powershell
Describe 'd' {
    It 'i' {
        & whoami # to reset lastexitcode
        $LASTEXITCODE | Should -Be 0 -Because 'should not be non-zero before we start'

        $scriptContent = @'
$azResources = (az resource list --resource-group $args[0]) | ConvertFrom-Json
if ($LASTEXITCODE -ne 0) { throw "az resource list returned a $LASTEXITCODE exit code." }
$azResources
'@
        Set-Content -Path 'TestDrive:/myscript.ps1' -Value $scriptContent

        Mock -CommandName az -ParameterFilter { "$args" -match 'resource list' } -MockWith {
            '[ { "id": "something...", "name": "something..." } ]'
        }

        $res = & 'TestDrive:/myscript.ps1' 'hello'
        $res.id | Should -Be 'something...'
        $LASTEXITCODE | Should -Be 0
    }
}

# Tests pass
```

So ready to close? 🙂

**Comment by ktran1005** [comment]
Hi @fflaten. Thanks for your suggestion. I followed your code above and run from my side. Everything works fine. However, when I tried to do something like this:
In **myscript.ps1**:
`
write-host $LASTEXITCODE # gives me blank here leading to if statement
$azResources = (az resource list --resource-group $args[0]) | ConvertFrom-Json`
`if ($LASTEXITCODE -ne 0) { throw "az resource list returned a $LASTEXITCODE exit code." }`

In **myscript.Tests.ps1**
Describe 'a' {
  `It 'testing' {
       Mock -CommandName az -ParameterFilter { "$args" -match 'resource list' } -MockWith {
               '[ { "id": "something...", "name": "something..." } ]'
       }
       $res = & './myscript' 'hello'
  }
}`
