### ISSUE TITLE
pester.dev site does not load properly

### ISSUE THREAD

**Issue by wethreetrees** [pester/Pester#2369]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?

The [pester.dev](https://pester.dev/) site is not loading properly. Appears to be a Docusaurus configuration issue.

![image](https://github.com/pester/Pester/assets/3781142/93d0aa6d-5bbd-4060-81b1-f5b89102b674)

### Expected Behavior

The site works properly

### Steps To Reproduce

navigate to [pester.dev](https://pester.dev/)

### Describe your environment

Chrome Version 114.0.5735.134 (Official Build) (64-bit)

**Comment by fflaten** [comment]
Hi. I'm not able to reproduce this. Can you reproduce on another device using https://pester.dev ?

**Comment by wethreetrees** [comment]
Looks like this is related to some settings in my companies VPN. Sorry for the false alarm!
