### ISSUE TITLE
Errors from tests not displaying variables

### ISSUE THREAD

**Issue by Leshmoe** [pester/Pester#2376]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?

---------------
If it passes it shows correctly in the report:
Edgewood - WWW.Checking Main WWW at https://www.edgewood.edu.Website Test https://www.edgewood.edu - Passed
If it fails it shows incorrectly:
Edgewood - WWW.Checking <WebName> at <WebURL>.Website Test <WebURL> - Failed

### Expected Behavior

What I would expect the output to be would be 
Edgewood - WWW.Checking Main WWW at https://www.edgewood.edu.Website Test https://www.edgewood.edu - Failed

### Steps To Reproduce

```powerhsell
$pesterArgs = [PesterConfiguration]::Default
$pesterArgs.Run.Path = ".\Tests\*"
$pesterArgs.Run.PassThru = $true
$pesterArgs.Output.Verbosity = "Detailed"
$pesterArgs.Should.ErrorAction = "Continue"
$pesterArgs.TestResult.Enabled = $true
$pesterArgs.TestResult.OutputPath = '.\Results\Testresult.xml'
$pesterArgs.CodeCoverage.Enabled = $true
$pesterArgs.CodeCoverage.RecursePaths = $true
$pesterArgs.CodeCoverage.OutputFormat = 'NUnit2.5'
$pesterArgs.CodeCoverage.OutputPath = ".\Results\coverage.xml"

$Results = invoke-pester -Configuration $pesterArgs
```

```powershell
BeforeDiscovery {
    $EC_WWW_URIs = @(
        @{"Main WWW" = "https://www.edgewood.edu"}
}

Describe "Edgewood - WWW" -ForEach $EC_WWW_URIs {
    BeforeAll {
        $WebURI = $($_)
        # $URI
        $WebName = $WebURI.Keys
        $WebURL = $WebURI.Values
        $StatusCode = (Invoke-WebRequest  $($WebURL)).StatusCode 
        #Write-Host("(Invoke-WebRequest -Uri $URL -Method Get -UseDefaultCredentials).StatusCode")
         }
    
       Context "Checking <WebName> at <WebURL>" {
            It "Website Test <WebURL>"  { 
                $StatusCode | Should -Match "200"
            }  
        } 
}
```

### Describe your environment

Pester version     : 5.4.1 C:\Program Files\WindowsPowerShell\Modules\Pester\5.4.1\Pester.psm1
PowerShell version : 5.1.20348.1366
OS version         : Microsoft Windows NT 10.0.20348.0

**Comment by fflaten** [comment]
Hi. Thanks for the issue. The repro doesn't fail and there's no error, but I assume you mean when `Invoke-WebRequest` fails, something I can reproduce with a URL.

In that case this is expected behavior. The failure occurs inside a setup-block (`BeforeAll/-Each`) which stops further processing of the block, incl. updating test names of child blocks since we can't be sure that the variables have correct values. 5.4.1 improved this a bit by updating as far as possible (parent block) when there's a failure or skip as explained in [this comment](https://github.com/pester/Pester/issues/2220#issuecomment-1192369856).

**If you only use the StatusCode inside that test** I'd move the `Invoke-WebRequest` call inside the test. The names are update before the code inside `It` is executed, so then the variables will be expanded in the report.

```powershell
# filename: demoIssue2376.tests.ps1
BeforeDiscovery {
    # Tip: Providing hashtables to `-ForEach` will automatically create variable by the key-name
    $EC_WWW_URIs = @(
        @{ WebName = 'Main WWW'; WebURL = 'https://www.edgewood.edu' }
        @{ WebName = 'Fail WWW'; WebURL = 'https://www.edgewood.edusssss' }
    )
}

Describe 'Edgewood - <WebName>' -ForEach $EC_WWW_URIs {
    # $WebName and $WebURL exists at this point and can even be used in Describe name (just like a variable set in BeforeAll here)
    It 'Website Test <WebURL>' {
        $StatusCode = (Invoke-WebRequest $($WebURL)).StatusCode
        $StatusCode | Should -Match '200'
    }
}
```

```powershell
> $p = invoke-pester -path /workspaces/Pester/Samples/demoIssue2376.tests.ps1 -Output None -PassThru
> $p.tests | fl ExpandedPath, Result

ExpandedPath : Edgewood - Main WWW.Website Test https://www.edgewood.edu
Result       : Passed

ExpandedPath : Edgewood - Fail WWW.Website Test https://www.edgewood.edusssss
Result       : Failed
```
