### ISSUE TITLE
Pester throws an exception when run inside runspace

### ISSUE THREAD

**Issue by kborowinski** [pester/Pester#2383]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?

*(This issue was moved from [here](https://github.com/pester/Pester/issues/1270#issuecomment-1648018135))*

**Environment:**
1. PowerShell 7.3.6 on up-to-date Windows 10 22H2 x64
2. Pester 5.5.0
3. ThreadJob 2.0.3 and Microsoft.PowerShell.ThreadJob 2.1.0

**Explanation:**
I use *Pester* for advanced infrastructure testing. Due to the long execution time of some tests I need to run them in parallel using `Start-ThreadJob` cmdlet from *ThreadJob* module. The tests are independent of each other. Sporadically, during initialization, Pester throws an exception:
**Cannot index into a null array**.

![pester_threadjob_error_0](https://github.com/pester/Pester/assets/16168755/60a4a829-cf1c-4eba-be47-f65f1843b26d)

The line *13998* in *Pester.psm1* module where exceptions happens:

![image](https://github.com/pester/Pester/assets/16168755/482195ac-467d-4475-9597-c7a1d85009cd)

### Expected Behavior

Pester should not throw when running in an runspace.

### Steps To Reproduce

1. Start new session:
`pwsh -nop`

2. Run following scriptblock:
```powershell
$cpuCount = [Environment]::ProcessorCount

$splatStartThreadJob = @{
    ThrottleLimit = $cpuCount
    StreamingHost = $Host
    ErrorAction = 'Stop'
    InitializationScript = {Import-Module Pester -Force -ErrorAction Stop}
}

$threadJobs = 1..($cpuCount * 2) | ForEach-Object {
    Start-ThreadJob -Name $_ -ScriptBlock {
        $pc = New-PesterConfiguration
        $pc.Run.Container = New-PesterContainer -ScriptBlock {Describe 'd' { It 'i' { 1 | Should -Be 1 }}}
        $pc.Output.Verbosity = 'None'
        $pc.Run.PassThru = $true
        $pc.Run.SkipRemainingOnFailure ='Block'
        [PSCustomObject]@{
            Test    = $Using:_
            Result  = Invoke-Pester -Configuration $pc
        }
    } @splatStartThreadJob
}

Wait-Job -Job $threadJobs | Receive-Job
```
3. If there was no error on first try, then start new PowerShell session, do not use existing session

**Output:**
![image](https://github.com/pester/Pester/assets/16168755/c03a5b32-8301-4fe9-9b13-90dde86d3461)

### Describe your environment

Pester version     : 5.5.0 C:\Program Files\WindowsPowerShell\Modules\Pester\5.5.0\Pester.psm1
PowerShell version : 7.3.6
OS version         : Microsoft Windows NT 10.0.19045.0

### Possible Solution?

Do not use the `-StreamingHost` parameter in `Start-ThreadJob` when calling `Invoke-Pester`

**OR:**

Replace line *13998* in *Pester.psm1* with the following:
```powershell
 elseif ($null -ne $host.UI -and ($hostProperties = $host.UI.psobject.Properties) -and ($supportsVT = $hostProperties['SupportsVirtualTerminal']) -and $supportsVT.Value) {
```

**Comment by kborowinski** [comment]
BTW, just for fun, repro code refactored to use `ForEach-Object -Parallel` works:
```powershell
$cpuCount = [Environment]::ProcessorCount
$results = 1..($cpuCount * 2) | ForEach-Object -Parallel {
    Import-Module Pester -Force -ErrorAction Stop
    $pc = New-PesterConfiguration
    $pc.Run.Container = New-PesterContainer -ScriptBlock {Describe 'd' { It 'i' { 1 | Should -Be 1 }}}
    $pc.Output.Verbosity = 'None'
    $pc.Run.PassThru = $true
    $pc.Run.SkipRemainingOnFailure ='Block'
    [PSCustomObject]@{
        Test    = $_
        Result  = Invoke-Pester -Configuration $pc
    }
} -ThrottleLimit $cpuCount
$results
```

**Output:**
![image](https://github.com/pester/Pester/assets/16168755/d8b543f1-95ba-4b43-b941-95da08a04e00)

The issue is - this is for PowerShell 7+ only. I need parallelization on PowerShell 5.1. Also, it looks like the `$Host.UI.psobject.Properties` behavior is *ThreadJob* bug or limitation?

**Comment by fflaten** [comment]
Did you check if UI is null? `psobject.properties` might work silently because of member enumeration.

Not in front of a computer today so can't test myself

**Comment by kborowinski** [comment]
It does work without `StreamingHost` 👀:

![image](https://github.com/pester/Pester/assets/16168755/f1136890-ce46-4ab4-9463-a359a035e9ad)

`$Host.UI` is not null but `$Host.UI.psobject.Properties` are:

![image](https://github.com/pester/Pester/assets/16168755/5dc8aa2e-7493-4cb7-a751-ecdc4333daae)

![image](https://github.com/pester/Pester/assets/16168755/ac1b9a86-d33d-4df0-a69a-2c54da4bc542)

**Comment by kborowinski** [comment]
This is very strange:
1. I've changed the *Pester.psm1* module to wait for debugger when `$Host.UI.posobject.Properties` are `$null` (and store the value in the `$p` variable):

![pester](https://github.com/pester/Pester/assets/16168755/fd323f75-a213-4fda-b067-475599eb5ecf)

2. Then I've attached to the process and entered the runspace for debugging:

![runspace](https://github.com/pester/Pester/assets/16168755/c31f98a6-dfa0-4ae9-b9c8-1ba932d17114)

And as you can see on in the left windows the `$p` variable is really `$null` but by the time the debugger was attached to the runspace the `$Host.UI.psobject.Properties` has all the values and is not null anymore 👀👀👀

**Comment by kborowinski** [comment]
OK, got it! Finally! The `$Host.UI` is kind of **lazy loaded**!

I have modified the *Pester.psm1* once more with simple loop that waits until the `$Host.UI.psobject.Properties` are available:

![image](https://github.com/pester/Pester/assets/16168755/169d250a-c57e-423f-ab69-9c225c8b18dd)

And it works now - this is the output of the repro script now:

![lazy](https://github.com/pester/Pester/assets/16168755/0d6f4eba-0eec-4172-83fa-9ff20719d0ac)

Really strange behavior. I would love if @SeeminglyScience could have a look at it for some thorough explanation.

**Comment by kborowinski** [comment]
@fflaten I was able to chat with @SeeminglyScience yesterday on Discord, and for him it looks like race condition bug *(I hope he doesn't mind me posting the conversation screenshot here)*: 

![image](https://github.com/pester/Pester/assets/16168755/2e8d1918-98f9-471b-8254-a86b522beb65)

I will investigate some more if that's *PowerShell* or *ThreadJob* module bug or something else. In the meantime, I'll not use `StreamingHost` in my parallel testing module since, in that case, I do not need it anyways.

**Comment by kborowinski** [comment]
This is yet simplest repro case:
```powershell
1..1e2 | % {Start-ThreadJob {1 | Should -BeExactly 1; $supportsVT = $Host.UI.psobject.Properties['SupportsVirtualTerminal'].Value} -StreamingHost $Host -InitializationScript {Import-Module Pester -Force}} | Wait-Job | Receive-Job | Remove-Job -Force
```
Output:
![image](https://github.com/pester/Pester/assets/16168755/3a828b31-918f-46ac-9e92-27e5db5cba11)

**Comment by fflaten** [comment]
Thanks for the thorough troubleshooting! I was able to reproduce a couple of times then suddenly not, so wasn't able to see if we could make the repro simpler. I doubt module import and calling `Should` is relevant, so was hoping to reproduce with sleep or something else.

Either way I support the suggested fix with a few conditions:
- Bug report is created in repo for ThreadJob or PowerShell
- Issue is referenced in comment above the fix

Reason being that checking `psobject.properties` and not just `$host.UI` is unexpected and would likely be removed in a future cleanup/refactor PR + hopefully they're able to fix the root cause which might help others as well 🙂

**Comment by kborowinski** [comment]
I was able to reproduce the issue without  `InitializarionScript` but I still needed to call `Should`. Otherwise I was unable to reproduce the issue.

I also think that checking `psobject.Properties` is not the right solution, and the exception could happen on `$Host.UI` for someone else therefore I would refrain from implementing my workaround. Maybe instead I could suggest, as a temporary workaround, to not use `StreamingHost` when calling `Pester` from `Start-ThreadJob`.

I will create an issue in the `ThreadJob` module repo though.

**Comment by kilasuit** [comment]
@kborowinski - In your original testing when using Start-ThreadJob I see that you are using the older of the two ThreadJob modules. In my testing in 7.3.6 & 5.1 on `Microsoft Windows 10.0.25905 - aka Win 11 23H2 via the Insiders Dev ring` with the newer `Microsoft.PowerShell.ThreadJob module v2.1.0` I did not get it throwing that error, using this to test `1..500 | % {Start-ThreadJob {1 | Should -BeExactly 1; $supportsVT = $Host.UI.psobject.Properties['SupportsVirtualTerminal'].Value} } | Wait-Job | Receive-Job `

So this may be fixed for you using that module, can you please test it out for me?

>Additional background info
ThreadJob (v2.0.3) as is what is currently included in 7.3.6 however in future (somepoint soon as I have a PR for this) Microsoft.PowerShell.ThreadJob (v2.1.0 - and is the successor to ThreadJob going forward - joys of module renames eh!!) will also be included. I also noted that you mention that you need this to work on PowerShell 5.1 as well as in 7.x.x - does testing with Microsoft.PowerShell.ThreadJob (v2.1.0) on both repro for you too?
FYI Paul Higin has recently retired so may not answer the question you posted to him above & also thanks for rasing this [issue in the PowerShell Org ThreadJob Repo](https://github.com/PowerShell/ThreadJob/issues/31) too. 

```

**Comment by kborowinski** [comment]
Where can I get the 2.1.0 version, so I could test it on Windows 10 and PowerShell 5.1 and 7.3.6? On PowerShell Gallery there is only 2.0.3. The same on GitHub repo.

**Comment by kborowinski** [comment]
@kilasuit [Unfortunately the same issue occurs](https://github.com/PowerShell/ThreadJob/issues/31#issuecomment-1653514960) in `Microsoft.PowerShell.ThreadJob` *v2.1.0*

**Comment by fflaten** [comment]
> 2. PR with a full `$Host.UI` check:
> 
> ```powershell
>  elseif ($null -ne $host.UI -and ($hostProperties = $host.UI.psobject.Properties) -and ($supportsVT = $hostProperties['SupportsVirtualTerminal']) -and $supportsVT.Value) {
> ```
> 
> What do you think @fflaten?

I'm fine with this workaround incl. a comment with link to this issue since I doubt we'll be able to cover this with a test consistently.

Thanks for really troubleshooting this and sorry for the delayed response 🙂 . Would you still like to provide a PR?

**Comment by kborowinski** [comment]
No problem, I will provide a PR.
