### ISSUE TITLE
Issues calling a Mock when a Mandatory attribute is included on a parameter

### ISSUE THREAD

**Issue by daverayment** [pester/Pester#2387]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?

I am mocking `Test-Path` for my Pester tests so I can test against a predictable file system.

I initially wrote the mock like this:

        # Test a path against a mock host filesystem instead of the host itself.
        Mock -CommandName 'Test-Path' -MockWith {
            param(
                [Parameter(Mandatory = $true)]
                [string]$Path
            )

            # Code which eventually returns $true or $false
            # ...
        }
        
However, I received some unexpected results when running my tests.

When testing a case which returns `$true`:

```
    It "Tests the top-level folder. Relative path." {
        Test-Path 'SomeHostFolder' | Should -Be $true
    }
```

It resulted in the following error:

```
PSInvalidCastException: Cannot convert value to type System.String.
   ArgumentTransformationMetadataException: Cannot convert value to type System.String.
   ParameterBindingArgumentTransformationException: Cannot process argument transformation on parameter 'Path'. Cannot convert value to type System.String.
```

Wrapping the `Test-Path` expression in curly braces corrected this for that case:

```
    It "Tests the top-level folder. Relative path." {
        { Test-Path 'SomeHostFolder' } | Should -Be $true
    }
```

However, a test which generated a `$false` response from the mock would now result in this output:

`Expected $false, but got { Test-Path 'Invalid' }.`

Removing the `[Parameter(Mandatory = $true]` attribute fixed all issues. My tests involving the mock now work with or without the wrapping curly braces, i.e. both of these work only if the mandatory attribute is removed:

```
    It "Tests an invalid top-level path." {
        Test-Path 'Invalid' | Should -Be $false
    }

    It "Tests the top-level folder. Relative path." {
        Test-Path 'SomeHostFolder' | Should -Be $true
    }
```

Please note: I initially thought this may have been an issue with just `Test-Path`, but I have tested with other commands and seen the same issues.

### Expected Behavior

When the `Mandatory` attribute is included on a parameter for a mocked command, I would expect either:

- Pester emulates the PowerShell in-built mandatory check for the parameter. I understand that prompting the user for input may not be reasonably practical, so reporting an error is acceptable if the parameter is missing; or
- Pester reports the presence of the `Mandatory` attribute as an error because it is unsupported. The error explains that the attribute should be removed. Pester does not run the test which is using the mock, but continues to the next test.

### Steps To Reproduce

```
Describe "False-returning tests." {
    BeforeAll {
        Mock -CommandName 'Test-Path' -MockWith {
            param(
                [Parameter(Mandatory = $true)]
                [string]$Path
            )

            return $false
        }
    }

    #  Throws "PSInvalidCastException: Cannot convert value to type System.String."
    It "Calls the mock with a Path." {
        Test-Path "SomePath" | Should -Be $false
    }

    #  Outputs "Expected $false, but got { Test-Path "SomePath" }."
    It "Calls the mock with a Path. Wrapped expression." {
        { Test-Path "SomePath" } | Should -Be $false
    }
}

Describe "True tests" {
    BeforeAll {
        Mock -CommandName 'Test-Path' -MockWith {
            param(
                [Parameter(Mandatory = $true)]
                [string]$Path
            )

            return $true
        }
    }

    # Throws "PSInvalidCastException: Cannot convert value to type System.String."
    It "Calls the mock with a Path." {
        Test-Path "SomePath" | Should -Be $true
    }

    # Passes.
    It "Calls the mock with a Path. Wrapped expression." {
        { Test-Path "SomePath" } | Should -Be $true
    }
}
```

### Describe your environment

Pester version     : 5.5.0 C:\Users\daver\Documents\PowerShell\Modules\Pester\5.5.0\Pester.psm1
PowerShell version : 7.3.6
OS version         : Microsoft Windows NT 10.0.22621.0

**Comment by fflaten** [comment]
Hi. Thanks for the detailed report with repros!

This isn't an Pester-issue, but PowerShell behavior when using a cmdlet/advanced function which you enable by using `[CmdletBinding()]` or `[Parameter()]`.

**The simple solution is to remove your param-block.**
The param-block is not necessary as mocks are generated with all the original parameters **and parameter-types**.

When calling a mock, you actually invoke a Pester-generated wrapper which accepts the same `[string[]]$Path` parameter as `Test-Path`. After some internal logic, the parameter is passed to the scriptblock you provide, which tries to convert it to `[string]`.

I'm not familiar enough with the PowerShell codebase as to why it allows the conversion for simple functions, but as shown below it's how PowerShell work for advanced functions/cmdlets which have more strict parameter validations.

```powershell
# Using [string[]] as input as that's what the Pester will pass to
# your mock's scriptblock unless you use `Mock -RemoveParameterType 'Path' ...` 
$myValue = [string[]]('SomePath')

function test {
    param(
        [Parameter()]
        [string]$Path
    )

    if ($Path -eq 'SomePath') {
        return $true
    } else {
        return $false
    }
}

test -Path $myValue

# output
test: C:\Users\Frode\Desktop\Demo\demo.ps1:16:12
Line |
  16 |  test -Path $myValue
     |             ~~~~~~~~
     | Cannot process argument transformation on parameter 'Path'. Cannot convert value to type System.String.
```

> Wrapping the `Test-Path` expression in curly braces corrected this for that case:
> 
> ```
>     It "Tests the top-level folder. Relative path." {
>         { Test-Path 'SomeHostFolder' } | Should -Be $true
>     }
> ```
> 
> However, a test which generated a `$false` response from the mock would now result in this output:
> 
> `Expected $false, but got { Test-Path 'Invalid' }.`

The first sample is a false positive and intended behavior. `Should -Be` uses the `-eq` operator like `$ExpectedValue -eq $ActualValue`. The provided scriptblock isn't executed but passed as-is as the `-ActualValue` parameter in `Should`. Because it's used on the right side of the operator, it will be cast to the type of your expected value, `$true` (bool), on the left side. A scriptblock is not null, which usually becomes `$true` when cast to `[bool]`.

```powershell
> $true -eq { 'hello' }
True
```

**Comment by daverayment** [comment]
Thanks so much for your detailed response, @fflaten! This is my first time using PowerShell and Pester, so I hope you'll forgive my lack of knowledge.

Thanks also for the explanation of the string[] -> string coercion and the scriptblock evaluation to $true. I'm sure that will be useful on future projects...if I ever get this one finished :)

**Comment by fflaten** [comment]
You're very welcome. I'm sure this issue will be useful for others in the future as well, so time well spent. 

Good luck with your project 🙂
