### ISSUE TITLE
I’m not a developer I run a nonprofit and a Pester Power Shell is running

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#2403]
I’m not a developer I run a nonprofit and a Pester Power Shell is running
on my laptop. How did that happen?

_Originally posted by @billgothacked in https://github.com/pester/Pester/issues/2400#issuecomment-1807221041_

**Comment by nohwnd** [comment]
did you get hacked?

**Comment by fflaten** [comment]
Closing. Question was likely spam, based on other random and unrelated comments from the same user.
