### ISSUE TITLE
Remove -Pending from Set-ItResult

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#2436]
### Checklist

- [X] Feature request has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### Summary of the feature request

Remove -Pending from Set-ItResult as mentioned in the deprecation message that was added here. https://github.com/pester/Pester/pull/2405

Pending state is unuseful and we won't re-implement it.

**Comment by fflaten** [comment]
There's also:
- `It .. -Pending` switch translating to Skip
- OwnPendingCount + PendingCount in Pester.Block
- Support in NUnit2.5 + NUnit3 for pending (translated to inconclusive)
- 
Remove only `Set-ItResult` for now? Or rip it all out?

**Comment by nohwnd** [comment]
I would remove it all, it was not working in 5.x.x, so to me it is "deprecated".
