### ISSUE TITLE
Pester shoud understand arrays

### ISSUE THREAD

**Issue by vors** [pester/Pester#246]
This test fails on a4244c3c3825f4a108be5283a98bb6eb7a3e3508 (v4 branch)

``` powershell
Describe "Pester shoud understand arrays" {
    It "two arrays are different" {
        @(1) | Should not be @(1,2)
    }
}
```

**Comment by francoislg** [comment]
I hit the same wall with arrays today and I think it's a wonderful idea to support it.

I've come up with a simple solution that works quite well for my context (thought probably not elegant enough) to compare two arrays regardless of their order.

function Assert-ArrayEquals {
	param($array, $expected)
	for($i = 0; $i -lt $expected.length; $i++){
		$expected -contains $array[$i] | Should Be $true
	}
}

The only problem is that it isn't quite verbose enough.

Hope that helps others

**Comment by it-praktyk** [comment]
Please check @stuartleeks projects
- [PesterMatchArray](https://github.com/stuartleeks/PesterMatchArray)
- [PesterMatchHashtable]https://github.com/stuartleeks/PesterMatchHashtable

More Pester's related links on my blog -> https://blog.it-praktyk.pl/2016/05/29/Pester-related-links/

**Comment by DarkLite1** [comment]
Stumbled upon this too and tried to use the suggested solution with `PesterMatchArray`, but it doesn't test the content [deeply enough](https://github.com/stuartleeks/PesterMatchArray/issues/5) . So in the end I reverted to [this post](https://dscottraynsford.wordpress.com/2015/08/23/comparing-objects-using-json-in-powershell-for-pester-tests/) and used the following test:

```
$Result = @(
    [PSCustomObject]@{
        'First Name' = 'Chuck'
        'Address'    = 'California'
    }
    [PSCustomObject]@{
        'First Name' = 'Jean-Claude'
        'Address'    = 'Brussels'
    }
)

$ExpectedResult = @"
[
    {
        "First Name":  "Chuck",
        "Address":  "California"
    },
    {
        "First Name":  "Jean-Claude",
        "Address":  "Brussels"
    }
]
"@

[String]::Compare(($Result | ConvertTo-Json),$ExpectedResult) | Should Be 0
```

**Comment by nohwnd** [comment]
Maybe this could help you: https://github.com/nohwnd/Assert#comparing-whole-objects

**Comment by DarkLite1** [comment]
Perfect! Even better! Thank you very much for the helpful module. Love it already!

**Comment by it-praktyk** [comment]
I assume that the issue can be closed soon (7 days). Feel free to send any additional information that can be helpful to answer your question/issue.

**Comment by PatrickGrub** [comment]
Would be nice if Pester itself provides such a functionality without installing other modules. 

I would love that!

Thanks,
Patrick

**Comment by jrobiii** [comment]
Not a solution, but a workaround.  The way that I'm working around this issue is by gathering the results into a variable and then doing multiple Should(s).  Like so:
`    
    It 'GetCsvKvp returns correct KVP array from a CsvString with correctly formatted CSV and valid KVP (key value pair)' {
        $KvpArray = GetCsvKvp -CsvString 'this=that,those=them'
        $KvpArray | Should -HaveCount 2
        ($KvpArray | where {$_.Name -eq 'this'} ).Value | Should -Be 'that'
        ($KvpArray | where {$_.Name -eq 'those'} ).Value | Should -Be 'them'
    }
`
Works great for small scenarios.  Hope this helps someone.

Jim Roberts

**Comment by DannyArr** [comment]
I just hit this as well. I tried the below, worked for me. I created a little helper function to re-order the array if the contents matched.

```
function Convert-ArrayOrderToSource {
    param (
        [parameter(mandatory=$true)]
        [array]$SourceArray,

        [parameter(mandatory=$true)]
        [array]$DifferenceArray
    )

    if(!(Compare-Object -ReferenceObject $a -DifferenceObject $b)) {
        $result = $SourceArray
    }
    else {
        $result = $DifferenceArray
    }
    return $result
}
```

Then in my pester test I convert the array. If it doesn't match it just spits out the original array and will fail the test.

`$propertiesInOrder | Should -Be $expectedProperties`
