### ISSUE TITLE
Does Pester support to view the code coverage report in browser?

### ISSUE THREAD

**Issue by pcgeng** [pester/Pester#2485]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [open documentation issues](https://github.com/pester/Pester/issues?q=is%3Aissue+label%3ADocumentation+is%3Aopen)

### Where did you see it?

Pester (latest)

### Function name

Invoke-Pester -Configuration New-PesterConfiguration

### What is the issue?

How to view the code coverage report in browser?

**Comment by fflaten** [comment]
There's no built-in HTML report but the JaCoCo xml can be read by CI-systems and tools like https://reportgenerator.io to create HTML.
