### ISSUE TITLE
Remove or update included about_ help files

### ISSUE THREAD

**Issue by fflaten** [pester/Pester#2491]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [open documentation issues](https://github.com/pester/Pester/issues?q=is%3Aissue+label%3ADocumentation+is%3Aopen)

### Where did you see it?

Pester (latest)

### Function name

about_*

### What is the issue?

Pester includes offline help in about_* format which has not been updated for Pester v5. Before releasing v6 there's a choice to be made:

- Update?
- Remove and solely depend on https://pester.dev and command help? Maybe keep about_Pester as a simple introduction and reference to the website?

Related files found here https://github.com/pester/Pester/tree/main/src/en-US:
about_BeforeEach_AfterEach
about_Mocking
about_Pester 
about_Should
about_TestDrive

**Comment by nohwnd** [comment]
delete? no-one is using those apparently. Or I don't recall a single issue that says the files are updated.

**Comment by fflaten** [comment]
I agree. Keep a simple intro and links in about_Pester?
