### ISSUE TITLE
Update SECURITY.md and SUPPORT.md?

### ISSUE THREAD

**Issue by fflaten** [pester/Pester#2494]
@nohwnd Just noticed the Pester supported versions information in [SECURITY.md](https://github.com/pester/Pester/blob/main/SECURITY.md) has not been updated for many years.

_Originally posted by @xtqqczze in https://github.com/pester/Pester/issues/2324#issuecomment-2150578380_

Update SECURITY.md. Should the support matrix also move to SUPPORT.md?

**Comment by nohwnd** [comment]
sure. PRed.
