### ISSUE TITLE
Use versioned links in v5 help?

### ISSUE THREAD

**Issue by fflaten** [pester/Pester#2503]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [open documentation issues](https://github.com/pester/Pester/issues?q=is%3Aissue+label%3ADocumentation+is%3Aopen)

### Where did you see it?

Pester (latest)

### Function name

All

### What is the issue?

⚠️ Pending PR pester/docs#316

Should we do a patch release for v5 to update https://pester.dev/docs/* links to https://pester.dev/docs/v5/* ? Once Pester v6 stable version is released, https://pester.dev/docs/* URIs will likely point to v6-docs which will cause dead links and wrong content for v5-users.

If done, should we consider a v4 patch release as a quality of life fix as well?

**Comment by nohwnd** [comment]
v5 yes
v4 probably no, because it would change the certificate for very little benefit, and we said we will patch only critical issues.

**Comment by fflaten** [comment]
Good point. Forgot that v4 is signed
