### ISSUE TITLE
don't return values from assertions except for throw

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#2508]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?

leave chaining of assertions for later

### Expected Behavior

no value out from 1 | Should-BeTruthy

**Comment by fflaten** [comment]
Did you find a problem?

**Comment by nohwnd** [comment]
I just don't think it is that practical. It was originally done to chain the assertions but it makes it harder to debug, and you can chain them via soft-assertions. So I am removing that functionality for now.

**Comment by fflaten** [comment]
👍 Should we close #1906 as won't fix then?
