### ISSUE TITLE
Deduplicate files provided using Run.Path and -Path?

### ISSUE THREAD

**Issue by fflaten** [pester/Pester#2530]
> > Using "/tests", "/tests/.github" should be enough. You only need to specify the hidden folder, the rest will be found using recursion unless you want to include only a subset of folders under tests.
>
> I tried this initially but the `.github` tests ran twice on windows which is also not ideal.

_Originally posted by @tbutler-qontigo in https://github.com/pester/Pester/issues/2515#issuecomment-2202080286_

Should Pester deduplicate file paths provided using `-Path` / `Run.Path`? I don't see a reason why you'd want to run the same file multiple times without parameters.

Calling a file multiple times with different parameters (`-Data`) requires use of `-Container` / `Run.Container` which is unaffected by the suggested change to `-Path`.

**Comment by nohwnd** [comment]
Yes please, I thought we are already doing that.

**Comment by nohwnd** [comment]
Please implement in 6.0.0 and backport.

**Comment by tbutler-qontigo** [comment]
> Please implement in 6.0.0 and backport.

@fflaten @nohwnd There hasn't been a release of 5.x since July 2024 - are there still plans to backport this into 5?
Thanks

**Comment by fflaten** [comment]
Yes. It's already backported in the repo, just pending a future release with a few other fixes and features.
