### ISSUE TITLE
Should -Throw doesn't perform substring matching

### ISSUE THREAD

**Issue by jackmtpt** [pester/Pester#2557]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?

The documentation (https://pester.dev/docs/v4/usage/assertions#throw) says that the following code should work:

`{throw "foo bar baz"} | Should -Throw "bar" # Test will pass`

It does not; the assertion fails.

### Expected Behavior

The test should pass, instead, the following error is generated:

```
InvalidResult: Expected an exception with message like 'foo' to be thrown, but the message was 'foo bar baz'. from line:1 char:2     + {throw "foo bar baz"} |
Should -Throw "foo" # Test will pass     +  ~~~~~~~~~~~~~~~~~~~
```

### Steps To Reproduce

```powershell
{throw "foo bar baz"} | Should -Throw "bar"
```

### Describe your environment

Pester 5.6.1, Win11, pwsh 7.4.4

**Comment by johlju** [comment]
No need to delete, it is good knowledge for others that hit the same issue. I think it could also been kept open so it could be tracked to get the documentation updated. 🙂

**Comment by jackmtpt** [comment]
https://pester.dev/docs/assertions/#throw the docs were updated, I just can't google good 😆

**Comment by fflaten** [comment]
> I just can't google good 😆 

Or... ideally v5 docs should rank higher. If anyone knows a SEO trick, let us know :)
