### ISSUE TITLE
Is it safe to delete older version of Pester module? 

### ISSUE THREAD

**Issue by Hot12345** [pester/Pester#2570]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?

Hi, 

Im using Powershell 5.1 
Have the following modules versions installed of Pester;

- Script     5.6.1      Pester                                                  
- Script     5.5.0      Pester                                                 
- Script     3.4.0      Pester 

Which version is module is safe to delete? Or is It that the version 3.4.0 must be installed? 

### Expected Behavior

Hi, 

Im using Powershell 5.1 
Have the following modules versions installed of Pester;

- Script     5.6.1      Pester                                                  
- Script     5.5.0      Pester                                                 
- Script     3.4.0      Pester 

Which version is module is safe to delete? Or is It that the version 3.4.0 must be installed? 

### Steps To Reproduce

Hi, 

Im using Powershell 5.1 
Have the following modules versions installed of Pester;

- Script     5.6.1      Pester                                                  
- Script     5.5.0      Pester                                                 
- Script     3.4.0      Pester 

Which version is module is safe to delete? Or is It that the version 3.4.0 must be installed?

**Comment by Hot12345** [comment]
Name                           Value                                                                                                                  
----                           -----                                                                                                                  
PSVersion                      5.1.22621.4249                                                                                                         
PSEdition                      Desktop                                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                
BuildVersion                   10.0.22621.4249                                                                                                        
CLRVersion                     4.0.30319.42000                                                                                                        
WSManStackVersion              3.0                                                                                                                    
PSRemotingProtocolVersion      2.3                                                                                                                    
SerializationVersion           1.1.0.1

**Comment by fflaten** [comment]
Unless you run scripts specifying the version in a `#requires ...` statement or specify a version during `Import-Module`, PowerShell will default to the latest. In that case you can delete the older versions.

Be aware that 3.4.0 was included in Windows so you need to modify some permissions to delete it, see the note [here](https://pester.dev/docs/introduction/installation#windows)

**Comment by Hot12345** [comment]
> Unless you run scripts specifying the version in a `#requires ...` statement or specify a version during `Import-Module`, PowerShell will use the newest version installed. In that case you can delete the older versions.
> 
> Be aware that 3.4.0 was included in Windows so you need to modify some permissions to delete it, see the note [here](https://pester.dev/docs/introduction/installation#windows)

Thanks for your reply.
So It doesn't harm or miss some cmdlets if I delete the module version 3.4.0? All the cmdlets are passed over to the newer module 5.x.x?

**Comment by fflaten** [comment]
Functionality, yes. Some commands have changed due to a completely new architecture in newer versions. v3 has been unsupported for years.

**Comment by nohwnd** [comment]
https://gist.github.com/nohwnd/5c07fe62c861ee563f69c9ee1f7c9688 here is a script for that if you are still having the version that came with Windows, and is locked by TrustedInstaller.
