### ISSUE TITLE
Invoke-Pester with $config.Run.Path does not work the same as with -Path

### ISSUE THREAD

**Issue by alx9r** [pester/Pester#2575]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?

`Invoke-Pester` with `PesterConfiguration` `$c ` where $c.Run.Path set to path $p does not produce the same result as `Invoke-Pester -Path $p`.   

Rather, providing $c.Run.Path results in `RuntimeException` with message "No test files were found and no scriptblocks were provided."

### Expected Behavior

`Invoke-Pester` with `PesterConfiguration` `$c ` where $c.Run.Path set to path $p should produce the same result as `Invoke-Pester -Path $p`.   

#### `repro.ps1`

```PowerShell
param(
    [ValidateSet('Invoke-Pester -Path $p','$c.Run.Path=$p')]
    [string[]]
    $ParameterSet = @('Invoke-Pester -Path $p','$c.Run.Path=$p')
)
$path = '.\repro.Tests.ps1'
{
Describe 'something' {
    It 'does' { 1 | Should -be 1 }
}
} |
    Set-Content $path

[PesterConfiguration]$configuration = New-PesterConfiguration
$configuration.Run.Path = $path

foreach ($p in $ParameterSet) {
    '',''
    "ParameterSet = $p" | % {$l = $_.Length; $_}
    '='*$l
    switch ($p) {
        'Invoke-Pester -Path $p'      {Invoke-Pester $path         }
        '$c.Run.Path=$p' {Invoke-Pester $configuration}
    }
}
```

### Describe your environment

Pester version     : 5.6.1 C:\Users\User1\Documents\WindowsPowerShell\Modules\Pester\5.6.1\Pester.psm1
PowerShell version : 5.1.22621.4249
OS version         : Microsoft Windows NT 10.0.22631.0

**Comment by fflaten** [comment]
How about `Invoke-Pester -Configuration $configuration`?

Unable to test atm but I assume the configuration object is implicitly converted to a string value like "PesterConfiguration" for `-Path` because it's the first property in the default parameter set.

**Comment by alx9r** [comment]
@fflaten That indeed cured the problem.  Thank you.  I should have read the syntax for that parameter set more carefully.
