### ISSUE TITLE
Snippets directory not included in NuGet package

### ISSUE THREAD

**Issue by todd-bowles-onthehouse** [pester/Pester#264]
The missing snippets directory causes a failure when Importing the module in Powershell ISE.

I've created a pull request to fix the issue with the missing snippets directory (just testing the path), but maybe the snippets directory should actually be there?

Pull Request for fix:
https://github.com/pester/Pester/pull/263

**Comment by dlwyatt** [comment]
Yep, it should.  Good catch!  Will get that sorted out.

**Comment by dlwyatt** [comment]
This should be all set as of the v3.3.5 release.  I've just verified that the downloads from NuGet.org, Chocolatey and PowerShellGet all contain the Snippets folder and its contents.
