### ISSUE TITLE
InModuleScope failing

### ISSUE THREAD

**Issue by msorens** [pester/Pester#275]
I attempted to write a new Pester test file using an InModuleScope but Pester throws this error:

    Cannot process argument transformation on parameter 'SessionState'.
    Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Management.Automation.SessionState".
    at InModuleScope, C:\Users\msorens\Documents\WindowsPowerShell\Modules\pester\Functions\InModuleScope.ps1: line 87

This occurs irrespective of what is in the test, i.e. even this empty script block triggers it:

    Import-Module -force '\path\to\my_module.psd1'
    InModuleScope my_module {
    }

Thus, I assume there is something in my module itself precipitating this error, but not sure where to start looking. Note that the module is a combination of both compiled cmdlets and scripted cmdlets.

P.S. This occurred with 3.0.2 so I just upgraded to 3.3.5 and it is still occurring.

**Comment by dlwyatt** [comment]
Hmm... I suspect that you have two copies of the same module loaded (or two modules with the same name, which amounts to the same problem), which is throwing off Pester.  Here's the code:

```posh
    try
    {
        $module = Get-Module -Name $ModuleName -All -ErrorAction Stop
    }
    catch
    {
        throw "No module named '$ModuleName' is currently loaded."
    }

    $originalState = $Pester.SessionState
    $originalScriptBlockScope = Get-ScriptBlockScope -ScriptBlock $ScriptBlock

    try
    {
        $Pester.SessionState = $module.SessionState

        Set-ScriptBlockScope -ScriptBlock $ScriptBlock -SessionState $module.SessionState

        & $ScriptBlock
    }
    finally
    {
        $Pester.SessionState = $originalState
        Set-ScriptBlockScope -ScriptBlock $ScriptBlock -SessionStateInternal $originalScriptBlockScope
    }
```

I would expect to see the error you're describe if $module is an array, because Get-Module returned more than one result.  There's really nothing we can do to improve that situation, but at least we can throw a more helpful error message.

On a side note, I avoid this problem in my own test scripts by removing the module first, then importing, so I don't wind up with multiple copies:

```posh
Remove-Module ModuleName -ErrorAction Ignore
Import-Module $PSScriptRoot\ModuleName.psm1
```

**Comment by msorens** [comment]
Thanks for your feedback! That helped me isolate the issue further and I believe it is a real issue due to the fact, as I mentioned above, that my module has both scripted and compiled cmdlets. In this situation, Get-Module rightly returns two modules, one with ModuleType `Binary` and one with ModuleType `Script`. I patched my copy of InModuleScope.ps1 to simply take the first one, as it does not seem to matter which of the two I use.

**Comment by dlwyatt** [comment]
Is your module available for download?  I'll play around with it and see what I can find.

**Comment by msorens** [comment]
Unfortunately, no, Dave, it is proprietary code :-(.

**Comment by dlwyatt** [comment]
Well, I need something to work with if you want this fixed.  If nothing else, the module manifest would be fine.  I can make up whatever dll and psm1 files I need to get the same effect.

**Comment by msorens** [comment]
Sent you the module manifest separately, Dave, as I did not see a way to attach a file here.

**Comment by dlwyatt** [comment]
OK, the main problem is probably that your DLL and PSM1 files have the same name.  It would be better if they were different; since one is a nested module, it doesn't make a difference to the end user either way.

I'll see about reproducing the problem, and get a feel for how it behaves.

**Comment by dlwyatt** [comment]
Okay, here's what I've determined so far:

- Pester's Mock and InModuleScope functionality seems pretty worthless for any module type other than Script anyway.  If you bind InModuleScope (or Mock) to the binary module, they don't really work.  For Manifest modules, it's even worse; the SessionState property for those is null, and Pester winds up throwing a different error.
- So, a simple solution might be to limit the results of that Get-Module call to those with a ModuleType of Script.
- If you really want to get weird, it's still possible to break this by having two different PSM1 files with the same name (one of which is in a subfolder).  Then you have multiple Script modules of the same name, and Pester goes back to complaining.

I don't think we need to worry about that third bullet point, so we might be okay with just limiting the module resolution to Script modules.

**Comment by msorens** [comment]
I agree, Dave; limiting to Script modules should be quite satisfactory.
Thanks for looking into it!
