### ISSUE TITLE
Output customizations or Changes

### ISSUE THREAD

**Issue by ghostsquad** [pester/Pester#280]
It would be cool to be able to hook up some sort of formatting syntax object to Pester to allow custom output (WHILE tests are running). I know that this is possible after the fact `$results = Invoke-Pester -PassThru`, but it would be nice to have the output display a bit easier to read, or customizable to the user's preference.

Current

```
Describing TheSUT
   Context TheSUT - Sunny Day
    [+] Given foo, produces bar 55ms
Describing TheSUT2
   Context TheSUT2 - Blah Blah
    [+] Given bar, produces foo and blarg 100ms
    [-] Given bar2, throws 30ms

```

Proposed

```
Describing TheSUT
   Context TheSUT - Sunny Day
    [+] Given foo, produces bar                 Success    55ms
Describing TheSUT2
   Context TheSUT2 - Blah Blah
    [+] Given bar, produces foo and blarg       Success    100ms
    [-] Given bar2, throws                      Failed     30ms
```

In order to get the output to lineup properly, you would need to get all the test names ahead of time, and pad based on the longest name, or truncate to a specific length.

**Comment by nohwnd** [comment]
I don't see much difference. :)

**Comment by ghostsquad** [comment]
Because things are in columns, it makes it easier to read. I can scan the column to see long running tests, failures etc. This also makes it easier for the colorblind to notice failures.

**Comment by it-praktyk** [comment]
I assume that your feature request was refused so the issue can be closed now. If you still think that something needs to be discussed please feel free to reopen it.
