### ISSUE TITLE
PowerShell 'break' statement is problematic in Pester

### ISSUE THREAD

**Issue by msorens** [pester/Pester#289]
Pester does not seem to properly control execution when a non-loop-confined break statement is executed. Consider the following sample code. 

    function go
    {
    	Get-ChildItem "before"
        $count = 0
        while ($true) {
            if ($count++ -ge 3) { break }
    	}
        # if ($count++ -ge 3) { break }
    	Get-ChildItem "after"
    }
    
    Describe 'Break-Non-Module-Test' {
    	Context 'context' {
    		It 'test1' {
                    Mock Get-ChildItem
                    go
                   Assert-MockCalled Get-ChildItem
            }
    		It 'test2' {
                    Mock Get-ChildItem
                    Assert-MockCalled Get-ChildItem
            }
        }
    }
    
As written, there is a break statement confined to a loop, so Pester performs as expected, completing both tests:

    Describing Break-Non-Module-Test
       Context context
        [+] test1 169ms
        [+] test2 32ms
    Tests completed in 201ms
    Passed: 2 Failed: 0 Skipped: 0 Pending: 0

However, if you uncomment the one commented line--containing a break statement that is *not* confined to a loop--that break should terminate the function or script completely. It does, but all too well. It terminates some part (but not all!) of the Pester process as well. Here is the output, showing Pester did not actually complete any of the tests:

    Describing Break-Non-Module-Test
       Context context
    Tests completed in 0ms
    Passed: 0 Failed: 0 Skipped: 0 Pending: 0

So it terminates all tests in that file, but the master test runner itself is still with us, giving the test summary. 
(I actually observed a slightly different manifestation of the same issue in my production code, but when I tried to produce an isolated failure case, it manifested as that described above. I am hoping that if you can address the issue presented, then it might fix my production code issue as well.)

**Comment by dlwyatt** [comment]
The PowerShell break statement is a problem in general, for the reasons you described.  Dynamically-scoped break / continue is just a nightmare.

There _might_ be something we can do about it in some cases, though.  If we put the calls to the test scripts / blocks into a do {} until ($true) loop, then any misbehaving (unlabelled) break or continue statement in the test script would just break out of that loop instead of the entire Pester run.  (Labelled break / continue statements would continue to blow everything up; nothing we can do about that.)

**Comment by nohwnd** [comment]
That's a great idea Dave! My first reaction was to use Finally (not even sure if it would work) but this is so much better.

**Comment by msorens** [comment]
Yes, very good idea, Dave. Thank you!
