### ISSUE TITLE
CodeCoverage all the things

### ISSUE THREAD

**Issue by ghostsquad** [pester/Pester#293]
How do I get code coverage for all my tests?

Can I provide a PSM1 file as a parameter here? What is this parameter actually doing?

Example from Help:
```
C:\PS>Invoke-Pester -CodeCoverage 'ScriptUnderTest.ps1'


Runs all *.Tests.ps1 scripts in the current directory, and generates a coverage report for all commands in the "ScriptUnderTest.ps1"
file.
```

**Comment by dlwyatt** [comment]
There's a fair amount of detail in the help blurb for that parameter, as well as in the wiki:  https://github.com/pester/Pester/wiki/Code-Coverage .

You can pass the path to a ps1, psm1 or psd1 file to that parameter, or you can give it hashtables with more specific information.  (It works a lot like Select-Object's -Property parameter, actually.)

As for what it does, it uses the AST to parse the files you've specified (which makes this the only part of Pester that doesn't work at all in PowerShell 2.0), sets a bunch of breakpoints on the commands in those files, and then checks the breakpoints after execution to see which ones were not triggered.  The information is displayed in the console at the end of the test run (if you're not using the -Quiet switch), and will also be added as an extra property on the -PassThru object, if you're using that parameter.

Here's an example of what the output looks like when I use the feature on one of my modules:

```
Tests completed in 12.04s
Passed: 63 Failed: 0 Skipped: 0 Pending: 0

Code coverage report:
Covered 89.95 % of 806 analyzed commands in 1 file.

Missed commands:

File         Function                              Line Command
----         --------                              ---- -------
Commands.ps1                                          3 $IgnoreError = 'SilentlyContinue'
Commands.ps1 Protect-Data                            81 throw "InputObject must be one of the following types: $($script:ValidTypes -join ', ')"
Commands.ps1 Protect-Data                            81 $script:ValidTypes -join ', '
Commands.ps1 Protect-Data                            86 throw 'SecureString argument contained no data.'                                                                                                                                      
```

**Comment by ghostsquad** [comment]
How does it work with PSObject ScriptMethods and ScriptProperties and that sort of thing?

**Comment by dlwyatt** [comment]
Works fine for those as well.  Anything that would trigger a breakpoint in the debugger should also be analyzed for coverage.

Using [scriptblock]::Create() and or Invoke-Expression can unfortunately screw with that, though, since they result in code that's not associated with the file and its breakpoints.

**Comment by ghostsquad** [comment]
thanks! this helps.
