### ISSUE TITLE
Cannot Mock Get-ADGroup

### ISSUE THREAD

**Issue by ephracis** [pester/Pester#294]
The following code fails for me:

    Describe "Mock" {
      It "Should mock Get-ADGroup" {
        Mock Get-ADGroup
        Get-ADGroup "Test"
      }
    }

It fails with the error:
> Cannot retrieve the dynamic parameters for the cmdlet.

I am running Pester 3.3.5 on PowerShell 3.0 on Windows 7.

**Comment by dlwyatt** [comment]
Hmm, it worked for me when I ran that code on my system, but that's PowerShell 5.0 on Windows 8.1.  I'll see if I can reproduce it on a system similar to yours when I have time.

**Comment by ephracis** [comment]
Thanks for the quick response. I can't give you the full error message since it's in a darknet but it seems to try to convert a Dictionary of ADPropertyValueCollection to a KeyValuePair of ADPropertyValueCollection.

**Comment by dlwyatt** [comment]
Well, the good news is that I was able to reproduce it, and blindly stumble over a fix.  I can even tell you more or less why I didn't see the problem on my Windows 8.1 system:  the AD module changed quite a bit in that version of the RSAT tools, and the object returned by the AD cmdlets' GetDynamicParameters() methods no longer implements any interfaces (including IEnumerable, which was part of the problem.)

Beyond that, I'm scratching my head.  I'm not sure why this exception came up, even with the goofy old AD module code.  Seems like it should have worked, but oh well, we can work around it.
