### ISSUE TITLE
Pester Wiki page says version is 3.0, but actual version is 3.3.?

### ISSUE THREAD

**Issue by lboening** [pester/Pester#299]
First, I see the Pester wiki page says the version is 3.0. Isn't the version different? Second, is the version number "embedded" somewhere in the code? I wouldn't necessarily know where to find it in the PSM1.

**Comment by nohwnd** [comment]
@lboening The version is in the Pester.psd1 file and changelog.md. The 3.0 version mentioned on the wiki is there likely since the last major update, because 3.0 was in beta for quite some time. Would changing it to 3.x make more sense to you?
