### ISSUE TITLE
Problem with BeforeAll and AfterAll when supplying scriptblock

### ISSUE THREAD

**Issue by JonSutton** [pester/Pester#300]
BeforeAll and AfterAll do not work with script blocks (BeforeEach + AfterEach do not have this issue)

I tried this:
```powershell
    $beforeAllScriptBlock = [ScriptBlock]::Create("$PSScriptRoot\Tests\TestSetup.ps1")
    BeforeAll { &$beforeAllScriptBlock }
```
but this failed with the message:
>Invoke-Blocks : The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo object.
At...

What I really wanted to be able to do was this:

```powershell
Describe "foo" {
    Context "bar" {
        BeforeAll {
            &"$PSScriptRoot\Tests\TestSetup.ps1"
        }
        It "Tests Something" {
            ........
        }
    }
}
```
the above fails to insert $PSScriptRoot (it's coming out blank in the error message)

I've tried a the `[ScriptBlock]::Create` approach for BeforeEach and it works just fine.

I've added to the set of tests here that pass on Before/AfterEach and fail for Before/AfterAll: JonSutton@6edfa373fa3cae0940aee4c747e86add87734dea

Thanks!

**Comment by dlwyatt** [comment]
Will investigate.

**Comment by nohwnd** [comment]
In the Invoke-TestGroupSetupBlocks the scriptblock is moved to different scope. The content of the scriptblock is correctly passed (for example: &$scriptBlock), but the variable containing the script is not passed. Hence you get the same error as if you'd do &$null.

**Comment by nohwnd** [comment]
Got it: The BeforeAll is running BEFORE the Describe. So at that point the $scriptBlock is not defined. You need to put the assignment before the Describe. 

```
Describe 'error' {   
    BeforeAll {
        &$a
     }
    It 'empty' {
        0 | should Be 0
    }
}

$a = [scriptBlock]::Create("Write-Host 'a'")
Describe 'no error' {

    BeforeAll {
        &$a
     }
    It 'empty' {
        0 | should Be 0
    }
}
```

Output:
```
Describing error
[113,5: Write-Error] The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo object.
 [+] empty 680ms
Describing no error
a
 [+] empty 97m
```

**Comment by dlwyatt** [comment]
Makes sense.  Also, $PSScriptRoot is probably not working because Pester is creating an unbound script block in memory (no longer tied to the Tests.ps1 file).  You can fix that by assigning another variable the value of $PSScriptRoot in your tests.ps1 file, then refer to that in BeforeAll / etc.  (This is similar to how you avoid having other automatic variables such as $_ "hijacked" by later code.)

**Comment by JonSutton** [comment]
Thanks for the great + speedy replies, realising that the BeforeAll was running before the contents of the describe was the key. Also thanks for the tip about copying the value of $PSScriptRoot so it would be available when I wanted it!

After your wise words I'm pretty sure that this issue should be closed, so i'll do that.
