### ISSUE TITLE
Some sort of global BeforeAll/AfterAll that runs only before/after all fixtures are run

### ISSUE THREAD

**Issue by theficus** [pester/Pester#302]
Today in my tests I try to reuse some resources between several different Describe { } groups. To do this I have to do something like this:

``` powershell
try
{
    Describe "MyTest2" { BeforeAll { CreateOrReuseExpensiveWidget } ... }
    Describe "MyTest2" { BeforeAll { CreateOrReuseExpensiveWidget } ... }    
}
finally
{
    CleanupExpensiveWidget
}
```

This works fine but has some problems -- notably that it completely skews the logged run time for tests. Also I have to duplicate this code per-Fixture.

What would be really great is to have a concept of a global BeforeAll/AfterAll that can do setup/teardown of resources that are to be shared across all tests. 

I realize there's plenty of ways to work around this by caching objects and putting things in shared scripts, or by wrapping Invoke-Pester in its own try/finally block, but I'm hoping for a more elegant solution that is built in to Pester.

**Comment by dlwyatt** [comment]
Would it work this way?

```posh
try
{
    CreateOrReuseExpensiveWidget
    Describe "MyTest2" { ... }
    Describe "MyTest2" { ... }    
}
finally
{
    CleanupExpensiveWidget
}
```

That's essentially all BeforeAll and AfterAll do, anyway.  We can't really do much outside of a Describe with the way the module is currently written; we'd have to promote the "Test script" scope to be a first-class citizen (allowing all Pester commands to be used outside of a Describe), which would have the side effect of killing the ability to just run a test script without using Invoke-Pester.

**Comment by theficus** [comment]
Yes, this does work and it's what I'm doing today. The problem comes when I have multiple fixtures where I want to share cleanup logic that only runs once.

The simplest way I can think of to work around this is to do something like this, which is pretty hacky:
```powershell
try
{
    Invoke-Pester ...
}
finally
{
    CleanupExpensiveWidget
}
```

I mean, this works and all but it'd be great if there was some way to instruct Pester that there's some code that should run once among all fixtures.

One possible idea is to have Invoke-Pester have parameters to define a startup/teardown script that only runs once per set of fixtures. This could set a variable that scripts could use to know they perform the startup/teardown on their own if run standalone.

**Comment by dlwyatt** [comment]
It's awkward to accomplish this while still retaining our current ability to just run a Tests.ps1 script (such as by pressing F5 in the ISE).  If we got rid of that ability, then we could easily promote the whole Tests.ps1 script to be a first-class citizen in the Pester state (allowing It blocks to be used without a Describe, BeforeAll/AfterAll scoped to the whole script, etc.)

**Comment by andschwa** [comment]
Can't this be closed? These are [documented](https://github.com/pester/Pester/blob/7a55e0ffa8bc1517f97d3a144c1f77f3d9b450f8/en-US/about_BeforeEach_AfterEach.help.txt#L24) and [tested](https://github.com/pester/Pester/blob/36687b41d7533ac9fefef459d5115f5b9c86e02f/Functions/SetupTeardown.Tests.ps1#L107).

**Comment by dlwyatt** [comment]
Not exactly.  BeforeAll / AfterAll only work inside a Describe (or Context) block; you can't place them outside of your Describes to have global cleanup at the end of the entire script.

**Comment by andschwa** [comment]
Ah. Well to add to that, it'd be great to run `In` outside of a `Describe` block too.

**Comment by redoz** [comment]
Would be nice to be able to define these on a global level too, either by using something like "Before.ps1" and "After.ps1" or a "Setup.ps1" that is invoked first of all which can then register global Before/After script blocks.

**Comment by cdhunt** [comment]
Here is the hacky way I've implemented a solution. I have one Module.Tests.ps1 that dot-sources a bunch of *.T.ps1 files that contain the actual describe blocks. I'm sure there's a better way, but it's eluding me at the moment.

```powershell
$global:Root = Split-Path -Path $PSScriptRoot -Parent
$global:Here = Join-Path -Path $root -ChildPath 'Source'
$global:ModuleName = Split-Path -Path $Root -Leaf
$global:TestsFolder = $PSScriptRoot

Import-Module "$here\$ModuleName.psd1"

foreach ($testFile in (Get-ChildItem -Path "$TestsFolder\*.T.ps1"))
{

    . "$testFile"

}

Remove-Module -Name $ModuleName
Remove-Variable -Name Root -Scope Global
Remove-Variable -Name Here -Scope Global
Remove-Variable -Name ModuleName -Scope Global
Remove-Variable -Name TestsFolder -Scope Global
```

**Comment by felixfbecker** [comment]
I would really like to be able to add something like a `.BeforeAll.ps1` file that runs before _all_ tests.

**Comment by nohwnd** [comment]
@felixfbecker can't that be solved by just running the setup before invoking Pester?

**Comment by nohwnd** [comment]
Not sure what would be the best approach here, it seems connected to Parallel switch (because one time setup for every file is probably needed there), and also to the BeforeEach -Describe, BeforeEach -Context story.

**Comment by fflaten** [comment]
Closing as top-level `BeforeAll` and `AfterAll` is supported in 5.1.0 and later. Demo:

```ps1
BeforeAll {
    Write-Host 'Hello world!' -ForegroundColor Yellow
}

Describe 'd' {
    Context 'c' {
        It 'i' {
            Write-Host 'Yay!' -ForegroundColor Yellow
        }
}

AfterAll {
    Write-Host 'Goodbye world!' -ForegroundColor Yellow
}

# output
Starting discovery in 1 files.
Discovery found 1 tests in 48ms.
Running tests.
Hello world!
Yay!
Goodbye world!
[+] /workspaces/Pester/Samples/RootSetup.tests.ps1 82ms (4ms|32ms)
Tests completed in 83ms
Tests Passed: 1, Failed: 0, Skipped: 0 NotRun: 0
```
