### ISSUE TITLE
Introducing Mock causes Error: Cannot retrieve the dynamic parameters for the cmdlet.

### ISSUE THREAD

**Issue by alx9r** [pester/Pester#305]
I ran into the following error try to Mock a function whose non-test implementation has two parameter sets:

```
Cannot retrieve the dynamic parameters for the cmdlet. Parameter set cannot be resolved using the specified named parameters.
```

## Repro
Here is the reproduction.  Test `f1 (1)` results in the error.  `f1 (2)` works fine.
### module.psm1

```Powershell
function f1
{
    [CmdletBinding()]
    param()
    process
    {
        New-Object PSObject -Property @{
            p1 = 'p1'
            notaparam = 'notaparam'
        } | f2
    }
}
function f2
{
    [CmdletBinding()]
    param
    (
        [parameter(ParameterSetName                = 'ps1',
                   ValueFromPipelineByPropertyName = $true)]
        [string]
        $p1,      

        [parameter(ParameterSetName                = 'ps2',
                   ValueFromPipelineByPropertyName = $true)]
        [string]
        $p2
    )
    process
    {
        return $true
    }    
}
```

### Module.Tests.ps1

```Powershell
Import-Module Module

InModuleScope Module{
Describe 'f1 (1)' {
    Mock -Verifiable f2
    It 'fails with mock.' { f1 }
}
Describe 'f1 (2)' {
    It 'succeeds without mock.' { f1  }
}
}
```

## Should f1 (1) work?
It seems like `f1 (1)` should be a valid test.  I suppose Pester is unable to sort out the parameter bindings for the mock.  If there's a good reason that `f1 (1)` is invalid, I'd like to understand why so I can work around it.

**Comment by dlwyatt** [comment]
Hmm... You should probably be defining a DefaultParameterSetName in your CmdletBinding attribute for that function.  However, I think I can clean this up a bit within Pester as well.  There's no need to bother with a DynamicParam block for the mock if the original function didn't have one anyway.

**Comment by alx9r** [comment]
Thanks @dlwyatt.  Your recommendation about DefaultParameterSetName is duly noted.  I just updated to 3.3.7, and this problem seems to be resolved.

**Comment by abhinitmodi** [comment]
Hey,
I am trying to use an azure-commandlet which uses dynamic parameters. The commandlet is new-azureresourcegroupdeployment. I am mocking it in the following way
Mock New-AzureResourceGroupDeployment { throw "No appropriate mock called for New-AzureResourceGroupDeployment" }
    Mock New-AzureResourceGroupDeployment -MockWith { return $validResourceGroupDeployment } -ParameterFilter{$Name -eq $validResourceGroupName -and $ResourceGroupName -eq $validResourceGroupName -and $TemplateFile -eq $validTemplatePath}
    
But when I run my tests, I get the same exception: Cannot retrieve dynamic parameters. Am I missing something. Could you please point me to an example where you have mocked a commandlet which has dynamic parameters. I am using the 3.3.6 version.

Thanks

**Comment by abhinitmodi** [comment]
I tried upgrading to 3.3.8, but no luck

**Comment by alx9r** [comment]
@abhinitmodi AFAIK, this issue didn't address using dynamic parameters.  The repro certainly wasn't using dynamic parameters.  You should probably open a new issue with code others can run that reproduces the problem you are seeing.

**Comment by abhinitmodi** [comment]
Yeah done that, Thanks. Issue posted here
https://github.com/pester/Pester/issues/339
