### ISSUE TITLE
Mocks are not hit if the mocked command is invoked with a qualified name

### ISSUE THREAD

**Issue by eliah-hecht-zocdoc** [pester/Pester#308]
If I mock a function and then my production code calls that function with a qualified name (like `SomeModule\SomeFunction`), the actual function is invoked, not the mock. Here's a test case to demonstrate:

``` posh
# production functions
function GetContentWithQualifiedName {
    $content = Microsoft.Powershell.Management\Get-Content somefile.txt

    return $content
}

function GetContentWithUnqualifiedName {
    $content = Get-Content somefile.txt

    return $content
}

# tests
Describe "GetContentWithQualifiedName" {
    It "returns the mocked content" {
        # neither call to Mock is effective
        Mock Get-Content {return "foo"}
        Mock Microsoft.Powershell.Management\Get-Content {return "foo"}

        $result = GetContentWithQualifiedName

        $result | Should Match "foo" # Fails
    }
}

Describe "GetContentWithUnqualifiedName" {
    It "returns the mocked content" {
        Mock Get-Content {return "foo"}

        $result = GetContentWithUnqualifiedNAme

        $result | Should Match "foo" # Passes
    }
}
```

**Comment by dlwyatt** [comment]
Yep.  Unfortunately, I don't think there's anything we can do about that while still maintaining PowerShell 2.0 compatibility.  I believe PowerShell 3.0 added some hooks that we can use to improve on this in the future, though.

**Comment by eliah-hecht-zocdoc** [comment]
I was afraid this might be the case. I'll add a note about this to the Mock wiki page, so people don't have to spend time trying to debug this issue in the future.

**Comment by nohwnd** [comment]
This works because we are adding alias with the unqualified and fully qualified name.
