### ISSUE TITLE
Invoke-Pester runs no tests when an array of TestNames is provided

### ISSUE THREAD

**Issue by alx9r** [pester/Pester#309]
`Invoke-Pester` has a parameter named `TestNames` with the following description:
```
-TestName <String[]>
    Informs Invoke-Pester to only run Describe blocks that match this name.
    
    Required?                    false
    Position?                    2
    Default value                
    Accept pipeline input?       false
    Accept wildcard characters?  false
```

The help text doesn't really imply that multiple test names can be provided.  However, the parameter type is an array of strings which suggests that multiple test name ought to be handled correctly.  

Whether or not multiple test names should be allowed, the current behavior is rather surprising: Providing an array of names to `TestNames` result in no tests running.

### mytests.Tests.ps1
```Powershell
Describe 'test 1' {
    It 'passes' { $true | Should be $true }
}
Describe 'test 2' {
    It 'passes' { $true | Should be $true }
}
```
### Invocation 1 (as expected)
Running `Invoke-Pester -TestName 'test1'` yields
```
Describing test 1
 [+] passes 52ms
Tests completed in 52ms
Passed: 1 Failed: 0 Skipped: 0 Pending: 0
```

### Invocation 2 (no tests run)
Running `Invoke-Pester -TestName 'test1','test2'` yields 
```
Tests completed in 0ms
Passed: 0 Failed: 0 Skipped: 0 Pending: 0
```

**Comment by dlwyatt** [comment]
Thanks.  Should be fixed by PR #310 .  I need to see if I can add some tests to cover this condition, but this may be one of the awkward bits that's hard to test from within Pester itself.

**Comment by nohwnd** [comment]
@dlwyatt I think that should not be hard to test. There are some tests that run Pester in Pester already. So you can just do the same and invoke pester from test path and assert on the pester result object. I can have a look when I get home if you want.

**Comment by alx9r** [comment]
@dlwyatt I just tested PR #310.  It seems to have fixed this issue.  Thanks!
