### ISSUE TITLE
Add -Message param to Should assertion

### ISSUE THREAD

**Issue by ephracis** [pester/Pester#312]
It would be nice to be able to add a message when doing Should, so I can add extra information to the assertion.

In my case I have a recursive method which checks the structure of an XML document. I have the following assertion:

```
$actual.ChildNodes.Count | Should Be $expected.ChildNodes.Count
```

When this fails, I have no way of knowing where in the document there are too many or too few elements. I would like to do this:

```
$actual.ChildNodes.Count | Should Be $expected.ChildNodes.Count -Message "In element $(Get-NodePath $actual)"
```

**Comment by nohwnd** [comment]
@ephracis That's a nice idea, and I think somebody actually mentioned it before. The only problem is the syntax. If we add the `-Message` parameter we'll also have to add Input, Arguments and Message parameters. Similarly to this: 
```powershell
function Should
{
    param (
        
        [Parameter(Position=0, ValueFromRemainingArguments=$true)] 
        $ArgumentList, 
        [Parameter(ValueFromPipeline=$true)]
        $InputObject,
        [string] $FailureMessage 
    )
    Process {
        "Input: $InputObject"
        "Arguments: $ArgumentList"
        "FailureMessage: $FailureMessage"
    }
}

10 | Should Not Be 5 -FailureMessage 234
```
This will result in a really weird IntelliSense experience, maybe a better paramater names are needed? 
```powershell 
        [Parameter(Position=0, ValueFromRemainingArguments=$true)] 
        $Assertion 
        [Parameter(ValueFromPipeline=$true)]
        $Expected,
        [string] $FailureMessage 
```

---

The more I think about it, the more I am inclined to change the direction of the whole project to better fit with the rest of the PowerShell language, and change the syntax to something like this: 
```powershell
Test-Block -Name "Validating XML" -ScriptBlock {
   Test-Case -ScriptBlock {
       $expected = $expected.ChildNodes.Count
       $actual = $actual.ChildNodes.Count   

       Assert-Equal -Actual $actual -Expected $expected -FailureMessage  "In element $(Get-NodePath $actual)"
   }
}

#or using parameter names only where appropriate 
Test-Block "Validating XML" {
   Test-Case {
       $expected = $expected.ChildNodes.Count
       $actual = $actual.ChildNodes.Count   

       Assert-Equal $actual $expected -FailureMessage  "In element $(Get-NodePath $actual)"
   }
}
```
In my point of view it would make Pester a lot easier to discover and grasp. But on the other hand there are people using the current syntax.. In the end the community will probably have to decide :)

**Comment by skullkiller** [comment]
It would be nice to have this functionality.
Maybe we could have the following and this would solve the issue:
1. Add a message parameter for both Success and Failure to the It cmd
2.  Add a new cmd `Add-BlockMessage -ResultType <Failure, Success, All, Imediatte> -Message <string>/<scriptblock??> -SkipConsole`. This would allow to add messages to the output (including only to the NUnit ouptut with the `-SkipConsole`. Immediate would write the message imediatly, while the other type would just write the message at the end of the tests, depending on the result chosen. This would be useful to add messages to Describe/contexts level and in the Before/after blocks.

Not sure if it's possible to add multiple `<message>` elements in the NUnit XML schema, but it would be nice to have that in some way. For the Describe/context and Before/After message a new test could be created in the Nunit XML if necessary to be able to maintain the schema.

**Comment by dlwyatt** [comment]
I'm not sure why we would need to modify the `It` command or add new ones.  A parameter on `Should` seems like the right place to put in custom assertion failure messages.
