### ISSUE TITLE
Pester should expose what test is currently running, today it doesn't.

### ISSUE THREAD

**Issue by theficus** [pester/Pester#321]
Pester doesn't tell you what test is currently running. This means that when you're watching the output results all you know is what previously ran and what its result was, but there's no visibility into the test that's currently running.

I have some tests that take 30+ seconds to run and it would be nice to know what's currently executing.

Some ideas for how to solve this:
* Use Write-Progress to show what's currently running (I like this one)
* Use Write-Verbose to log an additional line like ```[*] MyTestName starting ...```. The nice thing about this approach is you can suppress it by disabling verbose logging.
* Use Write-Output to log an additional line

**Comment by dlwyatt** [comment]
We could add some Write-Progress calls, though they'd go from 0% to Completed all at once.  No way for us to predict how long a particular test is going to take, but at least you'd have an indication of what's running.

**Comment by theficus** [comment]
Yeah I think that would be fine though. A nice indicator as to what it is running.

--
Sent from my phone. Expect brevity and typos.

On Apr 24, 2015, at 8:35 PM, Dave Wyatt <notifications@github.com<mailto:notifications@github.com>> wrote:


We could add some Write-Progress calls, though they'd go from 0% to Completed all at once. No way for us to predict how long a particular test is going to take, but at least you'd have an indication of what's running.

-

**Comment by nohwnd** [comment]
In console rewriting the current line of output is pretty easy, and it actually looks nice. 
```powershell
Write-Host "[*] test running..." -ForegroundColor Yellow -NoNewline
Start-Sleep -Seconds 1
Write-Host "`r[+] test succeeded " -ForegroundColor Green
```
Problem is that it does not work in ISE. 

Writing out progress, suggested by Dave, works in both console and ISE (and likely other hosts), and looks quite good in my opinion: 
```powershell 
1..10 | foreach {
    $r = (Get-Random -Minimum 10 -Maximum 1000)
    Write-Progress -Activity testing -PercentComplete 0 -CurrentOperation $_
    Start-Sleep -Milliseconds $r
    Write-Progress -Activity testing -PercentComplete 100 -CurrentOperation $_
    
    if ($r % 2)
    {
        Write-Host "[+] Test completed" -ForegroundColor Green
    }
    else 
    {
        Write-Host "[+] Test failed" -ForegroundColor Red        
    }
    Start-Sleep -Milliseconds 10 #sleep for few milliseconds to see the progress go to 100 %
}
```
One thing that need to be solved is that the output is hidden behind the progress bar.. Also I need to stop for 10 ms after every test to see the progress go to 100, otherwise it just stays 0 all the time.
