### ISSUE TITLE
Could the "Powershell 2 Limitation" problem be overcome with a "PesterCompatibility" switch?

### ISSUE THREAD

**Issue by alx9r** [pester/Pester#331]
[There is a slowly-growing list of issues tagged with "Powershell 2 Limitation"](https://github.com/pester/Pester/labels/PowerShell%202%20Limitation).  Changing the default behavior of Pester will break tests.  I get that, and I'm not proposing to change Pester's default behavior.  What I'm suggesting is some sort of switch that tells Pester it's OK to change its behavior to solve some of the most harmful problems currently baked into Pester on account of Powershell 2.

Here's a truth-table of the logic I propose: 

| Powershell Version | Switch Position | Behavior |
| --- | --- | --- |
| 2 | `V2` (default) | unchanged |
| 2 | `$null` | unchanged |
| >2 | `V2` (default) | unchanged |
| >2 | `$null` | changed to resolve problems |

I suppose the switch should be on a Module-by-Module basis.  Perhaps a variable defined in the `.Tests.ps1` file would work:
#### Module.Tests.ps1

``` PowerShell
Import-Module module

$PesterCompatibility = $null

Describe {
...
}
```

That would be fairly idiomatic.  Powershell uses, for example, `$PSModuleAutoLoadingPreference = $null` to change a behavior that has sweeping impact.

**Comment by nohwnd** [comment]
I am afraid that would cause a lot of trouble both for you and us. To avoid different behavior between PowerShell versions we aim to keep the code same across all versions. If we did not do that the codebase would become full of duplicated code and fixing an issue would be a nightmare.

A better option would be to put the current version on hold and only fix it without adding new features. But I am not sure how many people would hate us for doing that.

**Comment by theficus** [comment]
I'm asking only because I don't know any differently -- but is preserving PowerShell 2.0 compatibility a critical need at this point?

Windows Server 2003 is going EOL in July, and XP is already EOL. WMF 3.0 has been out for over 2 years and is supported on Vista/Server 2008 and newer operating systems, and WMF 4.0 is baked into Windows 8/Server 2012.

I really like Pester and hate to see it being hamstrung by this need to preserve PS 2.0 compatibility and I question if it's really necessary anymore.

**Comment by dlwyatt** [comment]
My thought on that is as long as people are writing and testing modules that are intended to be compatible with PowerShell 2.0, it's valuable to have Pester support running tests on that version.

However, that doesn't mean we can't say at some point, Pester version x.x.x is the last one to support PowerShell 2.0, so you need to use that version of Pester if this is important for your module.
