### ISSUE TITLE
Suggestion: Provide PowerShell operator syntax (Obsolete Should?)

### ISSUE THREAD

**Issue by Jaykul** [pester/Pester#334]
I think it would be awesome if we could provide a new syntax word which would map roughly to the syntax of Where-Object such that all of the PowerShell operators would work for assertions.

The logical thing would probably be to keep "Should" for the sake of pluggable assertions (but perhaps mark as obsolete the assertions which map to operators and would thus overlap), but perhaps we could find a way to make the new command work for both, and just mark "Should" as entirely obsolete (that is, obviously, leaving it in for now, but warning people to migrate to a new more PowerShell-specific syntax).

As a suggestion, we could use the keyword "must" with an alias "mustbe" ... so we could write things like:

``` posh
12 | Must -Eq 12
"This","And","That" | Must -contain "And"
14 | MustBe -gt 10
```

**Comment by dlwyatt** [comment]
@ghostsquad had a good suggestion for this in #279 .  By using dynamic parameter sets, we can support both the new and old syntax in calls to `Should`, and we can also add aliases (where `-Be` could also be `-Eq`, if that's your preference.)

**Comment by Jaykul** [comment]
Yeah, I had one from PSAINT which I was migrating over (haven't made it throw exceptions yet):
https://github.com/Jaykul/Pester/blob/Assertive/Functions/Assertions/Must.ps1

**Comment by it-praktyk** [comment]
The related issue #397 (?)

**Comment by nohwnd** [comment]
At least we have a new form of Assertions for Pester 6 :D

**Comment by it-praktyk** [comment]
So maybe should we change the label from 'Feature to ' 'Futurology'?

**Comment by nohwnd** [comment]
The operator syntax is already there provided by the aliases. Better assertions with better collection support are planned.
