### ISSUE TITLE
Variable scopes are counter-intuitive

### ISSUE THREAD

**Issue by vors** [pester/Pester#336]
It's probably a known issue, but I found this very counter-intuiteve:

```powershell
Describe 'pester scopes' {

  $failed = $true

  It 'assign failed' {
    1 | Should be 1 
    $failed = $false
    Write-Host "[inside it] failed = $failed"
  }
    
  Write-Host "[outside of it] failed = $failed"

}
```

Output

```
Describing pester scopes
[inside it] failed = False
 [+] assign failed 38ms
[outside of it] failed = True
```

**Expected**:
[outside of it] failed = False

**Comment by dlwyatt** [comment]
That's just how PowerShell works; variable assignments are locally scoped, and reads are dynamic.  I get around this by setting up a hashtable in the parent scope, and adding keys to it in the child scope:

```posh
Describe 'pester scopes' {

  $hash = @{ failed = $true }

  It 'assign failed' {
    1 | Should be 1 
    $hash.failed = $false
    Write-Host "[inside it] failed = $($hash.failed)"
  }

  Write-Host "[outside of it] failed = $($hash.failed)"

}
```

**Comment by theficus** [comment]
You can also use $Global: or $Script: to force certain variables to be usable outside of your scope. 

More about scopes: https://technet.microsoft.com/en-us/library/hh847849.aspx
