### ISSUE TITLE
Can I rely on a Mock in a Context overriding a Mock in a Describe?

### ISSUE THREAD

**Issue by alx9r** [pester/Pester#340]
Further to @nohwnd's [convincing me that I should probably be putting mocks close to where they are used](https://github.com/pester/Pester/issues/330#issuecomment-97457983), I find myself wanting to define "default" default behavior of mocks in the `Describe` block and more specific behavior of the same mocks in `Context` blocks.  My main motivation is to ensure that there are no side-effects if I accidentally miss one of the mocks in a `Context`.  

The following demonstrates the behavior I'm looking for:

#### module.psm1

```Powershell
function f1{}
```

#### module.Tests.psm1

```Powershell
Import-Module module

InModuleScope module{
    Describe 'test' {
        # default mock that ensures no side effects
        Mock f1 { 'default' }
       # ... whole bunch of other Contexts ...
        Context 'some specific test case' {
            Mock f1 { 'specific' }
            It 'returns specific' {
                f1 | Should be 'specific'
            }
        }
       # ... whole bunch more Contexts ...
        Context 'uses default mock' {
            It 'returns default' {
                f1 | Should be 'default'
            }
        }
    }
}
```

#### Can I rely on this behavior?

The above very simple case works, but I am left wondering whether I can rely on this behavior.  In other words, are the answers to the following questions true?

1. Will a mock defined in a `Context` always override a mock of the same name defined in its parent `Describe`?
2. If a mock of a certain name is defined in both a parent `Describe` and a sibling `Context`, will the mock used always be the one in the parent `Describe` block?

**Comment by nohwnd** [comment]
Yes, you can rely on it. I would not trust it to protect me from deleting my entire Active Directory, I would make sure to set non-existing search root for that or something... But generally this should protect you pretty well. I use it quite often to stop my computer from restarting, deleting files and so on. 

1), 2) I think your code snippet answers your questions. Yes and yes. I can't think of a scenario where the complexity of Context/Describe should change the behavior of the mocking.

**Comment by dlwyatt** [comment]
There's one potential exception to this rule.  Mocks defined with parameter filters are evaluated before those without a filter.  So in that case (a mock with a filter defined in Describe, a filterless mock defined in Context) you might wind up executing the Describe-scoped mock, if the parameters match its filter.

**Comment by alx9r** [comment]
Yikes.  That's sure to cause confusion one day.

**Comment by dlwyatt** [comment]
Agreed, but it's the way it has always worked (and is documented as such). I don't see a compelling reason to change it and potentially break people's scripts at this point.

**Comment by alx9r** [comment]
On second thought, I don't think that behavior is much of a hazard.  Anyone using mocks with parameter filters needs to be familiar with their evaluation order to use them effectively anyway.
