### ISSUE TITLE
Can I access test parameters from within an InModuleScope block?

### ISSUE THREAD

**Issue by replicaJunction** [pester/Pester#342]
If I include a param() block at the beginning of my test file, can I access the parameter values from within an InModuleScope block?  In testing, they appear to be null.

Here's an example of the code I'm currently using.  There are two Write-Host calls in here; the first returns the actual value of the parameter passed to the script, and the second returns null.

    param(
	    [Parameter(Mandatory = $true)]
	    [bool] $ShowMockData
	)

	$here = Split-Path -Parent $MyInvocation.MyCommand.Path
	$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path).Replace(".Tests.", ".")
	. "$here\$sut"

	Write-Host "ShowMockData: [$ShowMockData]"
	# ShowMockData: [True]

	InModuleScope MyModule {
	    Write-Host "ShowMockData: [$ShowMockData]"
	    # ShowMockData: []

	    # ...

	    Mock Get-Thing {
	    	if ($ShowMockData)
	    	{
	    		Write-Host "       Mocked Get-Thing" -ForegroundColor Blue
	    		Write-Host "         [Arg1] $Arg" -ForegroundColor Blue
	    	}
	    }
	}

I run the code using this line:

    Invoke-Pester -Script @{Path='.\Get-Something.Tests.ps1'; Parameters=@{ShowMockData=$true}}

It's worth noting that when I remove the Parameters hashtable from Invoke-Pester, I do get prompted for the ShowMockData parameter, so the mandatory attribute is working correctly.

I'm currently running on WMF5.0 April preview on 8.1x64, but I have also tested on PS v4 on Win7 with the same results.

Am I doing something incorrectly here, or is this a limitation of Pester and/or PS?

**Comment by dlwyatt** [comment]
That's tricky... you might need to resort to setting some global variables to make that work.  The problem is that the code inside the module (and by extension, in your InModuleScope block) can't resolve variables outside the module, except in the global scope.

**Comment by replicaJunction** [comment]
Ah, that makes sense. I'll fiddle with global variables and put together a workaround.  Thank you very much!
