### ISSUE TITLE
Special characters do not work with Should Exist

### ISSUE THREAD

**Issue by adityapatwardhan** [pester/Pester#343]
The first It works but the second does not. There is a need of ExistExactly.

```powershell
Describe "Testing Exists" {
    It "works with test-path" {
        $file = New-Item -Path "TestDrive:\[test].txt" -ItemType File         
        Test-Path -LiteralPath $file | Should Be $true
    }

    It "should work with Exists" {
        $file = New-Item -Path "TestDrive:\[test].txt" -ItemType File 
        $file | Should Exist        
    }
}
```

**Comment by nohwnd** [comment]
This is a bug rather than a feature. Creating ExistExactly is IMHO not warranted here because there is no such thing as a partially existing file.

**Comment by nohwnd** [comment]
@adityapatwardhan We agreed not to add this corner case to the assertion as it would muddy it for everyone. Instead there are two workarounds described in the wiki: [Should Exist](https://github.com/pester/Pester/wiki/Should#exist). Hope that works for you.
