### ISSUE TITLE
Pester silently fails with $ErrorActionPreference = Continue

### ISSUE THREAD

**Issue by vors** [pester/Pester#344]
I just found a minor obscure problem.

```powershell
Describe 'foo' {
    $ErrorActionPreference = Continue # here is a mistake, it should be string 'Continue'
    It 'bar' {
        1 | Should be 1
    }
}
```

Output
```
Describing foo
```

Test doesn't run.

**Comment by dlwyatt** [comment]
It used to be even worse.  :)  At least now Pester handles the errant continue keyword and continues running the rest of the tests; used to be, that would abort everything.

**Comment by dlwyatt** [comment]
There's really nothing we can do about that, since PowerShell's break / continue keywords are dynamically scoped.  Instead of producing an error, it just starts walking up the stack looking for something to continue.

**Comment by vors** [comment]
hehe.
