### ISSUE TITLE
-Skip parameter on It doesn't have help

### ISSUE THREAD

**Issue by JamesWTruher** [pester/Pester#350]
it might seem obvious, but perhaps it should have some help

**Comment by nohwnd** [comment]
Thanks. There is also `-Pending` that is likely not documented as well (including automatic Pending status of and empty `It`) and also the `-Strict` parameter on `Invoke-Pester` that fails any Pending or Skipped test.

Will add the documentation soon.

**Comment by nohwnd** [comment]
Updated the Wiki and also the It inline help.
