### ISSUE TITLE
Feature sugestion: named properties on tests like NUnit PropertyAttribute

### ISSUE THREAD

**Issue by JaegerJens** [pester/Pester#356]
custom properties can be used for
- tracking bugs
- test cases
- change request

like http://www.nunit.org/index.php?p=property&r=2.6.4

**Comment by dlwyatt** [comment]
Do you have an example of what an NUnit XML file looks like when these properties are used?

**Comment by it-praktyk** [comment]
Based on the lack of answer I assume that issue can be closed soon (7 days). Please update about requested data or the issue will be closed.
