### ISSUE TITLE
Module scoped mocks throw an error on second context if Get-Content has been mocked

### ISSUE THREAD

**Issue by JonSutton** [pester/Pester#361]
Hi,

We're running 3.3.9 from the chocolatey feed.

Apologies, for the complex example but this is (almost) the shortest way I've been able to reproduce this:

Given a module (TestModule.psm1)  :

```PowerShell
function ModuleFunction 
{
    return getMyValue
}

function getMyValue
{
    return get-content 'C:\foo.txt'
}

Export-ModuleMember -Function ModuleFunction
```

and a test script (Test.Tests.ps1) :

```PowerShell
Describe 'My Tests' {

BeforeAll { 
            Import-Module .\TestModule.psm1
          }
AfterAll {
            Remove-Module TestModule
         }

    Context MyContext {

    Mock getMyValue -ModuleName 'TestModule' { return 'mocked' }
    Mock Get-Content {} -ModuleName 'TestModule'
    
    it 'returns mocked' {
        Assert-VerifiableMocks
        ModuleFunction | Should Be 'mocked'
    }

    }

    Context MyContext2 {

    
    Mock getMyValue -ModuleName 'TestModule' { return 'mocked2' }
    Mock get-Content {} -ModuleName 'TestModule'
    
    it 'returns mocked2' {
        Assert-VerifiableMocks
        ModuleFunction | Should Be 'mocked2'
    }

    }
    
}
```

On running invoke-pester the second context block will output a set of 2 exceptions:

```PowerShell
Describing My Tests
   Context MyContext
    [+] returns mocked 83ms
   Context MyContext2
Get-Content : Cannot find path 'Function:\script:getMyValue' because it does not exist.
At C:\Users\Anon\Documents\WindowsPowerShell\Modules\pester\Functions\Mock.ps1:833 char:9
+         & $mock.OriginalCommand @ArgumentList @BoundParameters
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Function:\script:getMyValue:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
 
Get-Content : Cannot find path 'Function:\script:Get-Content' because it does not exist.
At C:\Users\Anon\Documents\WindowsPowerShell\Modules\pester\Functions\Mock.ps1:833 char:9
+         & $mock.OriginalCommand @ArgumentList @BoundParameters
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Function:\script:Get-Content:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
 
    [+] returns mocked2 78ms
Tests completed in 162ms
Passed: 2 Failed: 0 Skipped: 0 Pending: 0
```

Inverting the order of the context blocks will produce the same result. This problem didn't occur in Pester 3.3.8

The problem seems tied to the mocking of Get-Content as we don't have this problem elsewhere, and if you remove the get-content bits from my example then the problem will go away.

Hope the above makes sense !

#### Additional Query:
While I'm here, an extra query, I'll gladly raise a separate issue for this if you like, just ask!

If we run in `$ErrorActionPreference = 'Stop'` we get an : 
```
[-] Error occurred in Context block 70ms
      Cannot find path 'Function:\script:getMyValue' because it does not exist.
      At C:\Users\Anon\Documents\WindowsPowerShell\Modules\pester\Functions\Mock.ps1:833 char:9
```

I'd not have expected to need to set $ErrorActionPreference to 'Stop' to get the "Error occurred in Context block", without setting this to Stop the tests indicate that they pass. This could be by design, but it's not how i'd have expected it to work.

**Comment by dlwyatt** [comment]
Well that's obscure.  :)  You actually found two bugs at once with this one.  Fix coming shortly.

As for the ErrorActionPreference thing, that's because this particular error from Get-Content is not a terminating error, but it's probably a good idea for us to tack -ErrorAction Stop on to that particular call to the cmdlet anyway, which will fix that as well.

**Comment by JonSutton** [comment]
That's great, many thanks!
