### ISSUE TITLE
Should `It [-Skip]` also have an alias [-ignore] assigned to the property?

### ISSUE THREAD

**Issue by ChaseFlorell** [pester/Pester#363]
Just working my way through pester, and I've got a test that I want to ignore. In nUnit and xUnit, it's possible to have an [ignore] attribute.

I noticed that in pester it's called `-skip`, and I'm wondering if we should add an alias `-ignore`?

    [CmdletBinding(DefaultParameterSetName = 'Normal')]
    param(
        [Parameter(Mandatory = $true, Position = 0)]
        [string]$name,

        [Parameter(Position = 1)]
        [ScriptBlock] $test = {},

        [System.Collections.IDictionary[]] $TestCases,

        [Parameter(ParameterSetName = 'Pending')]
        [Switch] $Pending,

        [Parameter(ParameterSetName = 'Skip')]
        [alias('Ignore')]
        [Switch] $Skip
    )

**Comment by ChaseFlorell** [comment]
Along this same line, when the xml output is generated, nunit will use `result="Ignored"` whereby pester uses `result="Skipped"`. When  this happens, our build runner (TeamCity) reports the `-skipped` tests as "Success" instead of "Ignored".

I think the output also needs to be changed to match nunit, if the nunit style output is to be used for the xml results.

**Comment by ChaseFlorell** [comment]
@dlwyatt any chance of having a discussion around this? I'd be happy to fork and implement, but I'd like to discuss it first.

Is there a specific reason for using `skip` instead of `ignore`?
I can definitely implement it as an alias so that it doesn't break existing functionality, however changing the nunit xml would obviously change things, I'm pretty sure (not 100% mind you) that nunit doesn't support the `skip` verb in xml reports.

**Comment by nohwnd** [comment]
@ChaseFlorell Looks like a good idea. Changing the xml output should not be a problem if it was broken till now. Do they show the correct format of the output somewhere in the documentation? Are you sure it's  not fixing the problems "just" for TC?

**Comment by ChaseFlorell** [comment]
Hey @nohwnd, I can't say with 100% certainty that it's not just a TeamCity fix, however, when I look at the results of an nunit run, I've got results that look like this.



    <test-results name="C:\Dev\ECIM\build-artifacts\output\TransCanada.ECIM.Test.dll" total="977" errors="0" failures="0" not-run="1" inconclusive="0" ignored="1" skipped="0" invalid="0" date="2015-06-12" time="09:07:22">
      <environment nunit-version="2.6.3.13283" clr-version="2.0.50727.5485" os-version="Microsoft Windows NT 6.1.7601 Service Pack 1" platform="Win32NT" cwd="C:\Dev\ECIM" machine-name="W-43439" user="chase_florell" user-domain="TCPL" />
      <culture-info current-culture="en-US" current-uiculture="en-US" />
      <test-suite type="Assembly" name="C:\Dev\ECIM\build-artifacts\output\TransCanada.ECIM.Test.dll" executed="True" result="Success" success="True" time="19.028" asserts="0">
                    <results>
                      <test-case name="TransCanada.ECIM.Test.BulkDataLoadEntryPoint.DoBulkDataInsert" executed="False" result="Ignored">
                        <reason>
                          <message><![CDATA[]]></message>
                        </reason>
                      </test-case>
                    </results>

Notice how they have `ignored="1"` and also `skipped="0"`. TeamCity treats them differently. [Here is a discussion on the matter](https://groups.google.com/forum/#!topic/nunit-discuss/GH5Zp_WWOdw).

> In the sort of unit testing NUnit is designed for, Ignoring a test is considered a "bad thing." For that reason, it is highlighted in the Gui with a Yellow bar. **Skipping is not available to the user directly**, but is a state that can be reached if some requirement for the test is not met.

**Comment by ChaseFlorell** [comment]
So if 'Skipping is not available to the user directly', then it makes sense to leverage `ignore`, at least in the nunit report. Like I said, the flag can be an alias as to not break existing functionality.
