### ISSUE TITLE
Mocking a function in a module throws 'The term 'Invoke-Mock' is not recognized as the name of a cmdlet'

### ISSUE THREAD

**Issue by ChaseFlorell** [pester/Pester#364]
I've got a function inside my module suite called `Invoke-ExternalCommand`.

In a test that I'm writing for a separate tool that uses that calls that function, but when I mock it, I get an exception.

>  'The term 'Invoke-Mock' is not recognized as the name of a cmdlet'

    $ErrorActionPreference = 'Stop'
    $here = Split-Path $script:MyInvocation.MyCommand.Path
    
    Describe 'ClickOnce' { 
        Context 'Sign Package'{
            # setup
            $manifestPath = 'foo'
            $pfxPath = 'C:\bar'
            $pfxPassword = 'baz'
            Mock Invoke-ExternalCommand {} -moduleName poshBAR
                
            # execute
            $execute = {Invoke-SignAppliationManifest $manifestPath $pfxPath $pfxPassword}
    
            # assert
            It 'Will not throw' {
               $execute | should not throw
            }
            
            It 'Will call Mock of poshBAR\Invoke-ExternalCommand' {
                Assert-MockCalled Invoke-ExternalCommand -moduleName poshBAR
            }
        }
    }

**Comment by dlwyatt** [comment]
That's odd.  Invoke-Mock is one of the functions exported by Pester.  What version are you running?  Can I see the module that you're testing?

**Comment by ChaseFlorell** [comment]
The entire repo is located [here](https://github.com/transcanada/poshbar)

The module I'm mocking is [Invoke-ExternalCommand](https://github.com/transcanada/poshBAR/blob/master/src/poshBAR/Invoke-ExternalCommand.ps1#L31)

The build step can be found [here](https://github.com/transcanada/poshBAR/blob/master/build/build.ps1#L66)

And I'm running [v-3.3.9](https://github.com/transcanada/poshBAR/tree/master/packages/Pester.3.3.9)

**Comment by dlwyatt** [comment]
OK, will take a look next week.  I'll be travelling and visiting people for this weekend; not sure if I'll have a chance to test before then.

**Comment by ChaseFlorell** [comment]
I've began writing another function, and I'm getting the same result.

If I add `-module myModule` to the mock, it throws the above error. If I do not add that property, then the mock doesn't get called, and the concrete implementation does.

$ErrorActionPreference = 'Stop'
    $here = Split-Path $script:MyInvocation.MyCommand.Path
    
    Describe 'Invoke-PowershellScriptSigning' { 
        Context 'Should execute against pfx path' {
            # setup
            Mock Set-AuthenticodeSignature {exit 0} 
            Mock Get-PfxCertificate {} #-module poshBAR
            
            $scripts = @("$env:TEMP\script.ps1")
            $pfxPath = "$env:TEMP\cert.pfx"
            $password = 'foo'
            
            Set-Content $pfxPath -value 'foo'
            $scripts | % {Set-Content $_ -value 'bar' }
            
            $pfxPathInfo = (Resolve-Path $pfxPath)
            
            # execute
            $execute = {Invoke-PowershellScriptSigning $scripts $pfxPathInfo $password}
    
            # assert
            It 'Will not throw' {
               $execute | should not throw
            }
        }
    }

**Comment by dlwyatt** [comment]
Looks like this is a scoping problem with PSake.  Adding the `-Global` switch to both of the calls to `Import-Module` in your build.ps1 script fixes the problem.  (For whatever reason, the Pester module wasn't being seen from inside poshBAR with the way the modules were originally imported.)

**Comment by ChaseFlorell** [comment]
That did it @dlwyatt, thanks
