### ISSUE TITLE
Pester for Non-Terminating Error

### ISSUE THREAD

**Issue by dotps1** [pester/Pester#366]
I reviewed the Should Wiki Page, and i apologize if i missed how to use this, but i was working with some error handling, and i want to Pester for non terminating errors as well as Exceptions.  Basically, i have some tests in a function that are in the Process block, and i still want the End block to process, so in this case i want to use Write-Error rather then Throw, so, in my pester assertion, i want to make sure the Catch block is being hit, and the Write-Error is being executed, and im not sure how to do that.
```PowerShell
It 'Error should be raised' {
     My-FunctionThatWritesErrorForInvalidPath -Path '.\InvalidPath' | Should #Here is where im lost, maybe Should Error would be nice.
}
```
I hope that makes sense and im sorry if im just using Write-Error incorrectly, and i could use the 'Should Throw' assertion.

thanks for any help.

**Comment by ChaseFlorell** [comment]
My-FunctionThatWritesErrorForInvalidPath -Path '.\InvalidPath' | Should Throw

**Comment by dlwyatt** [comment]
`Should Throw` only works for terminating errors, so you can do one of two things.  You can either use `-ErrorAction Stop` to force your non-terminating errors to become terminating (though this would prevent your End block from running), or you can use something like `-ErrorVariable` and then do assertions against that.  Something along these lines:

```posh
It 'Error should be raised' {
     My-FunctionThatWritesErrorForInvalidPath -Path '.\InvalidPath' -ErrorVariable err
     $err.Count | Should Not Be 0
     $err[0].Exception.Message | Should Be "Path '.\InvalidPath' is not valid" # or something like that
}
```

**Comment by dotps1** [comment]
thanks Dave, that works fine for me!  keep up the good work!  feel free to close this thread if you wish.

**Comment by ChaseFlorell** [comment]
Ah, sorry, I didn't read the question all the way through. I personally always throw and then run cleanup code in `finally`. I see you're using a different (and valid) approach.

**Comment by theficus** [comment]
I work around this with two helper methods:

* Method 1: Expect script to fail (in other words, throw a terminating exception):

```powershell
Function InvokeShouldFail
{
    Param([Parameter(Mandatory)][string]$script)
    Write-Host Invoking command and expecting failure: $script
    $didFail = $false
    try
    {
        iex $script
        Write-Warning Did not fail: $script
    }
    catch
    {
        Write-Host "Script failed as expected: $_"
        $didFail = $true
    }

    $didFail | Should Be $true
}
```

* Method 2: Expect an error (in other words, it should fail, but not in a terminating way). You could always extend this to look for specific error text as well if you want to assert not only that it errors, but it errors with a specific string but I haven't had a need for this yet.

```powershell
Function InvokeShouldError {
    Param([Parameter(Mandatory)][string]$script)
    Write-Host Invoking command and expecting error: $script
    $didError = ""
    iex $script -ErrorVariable didError

    Write-Host Error result: $didError
    $didError | Should Not BeNullOrEmpty
}
```

**Comment by Midacts** [comment]
I ran into this as well.
Thanks for the help.

**Comment by fgimian** [comment]
> `Should Throw` only works for terminating errors, so you can do one of two things. You can either use `-ErrorAction Stop` to force your non-terminating errors to become terminating (though this would prevent your End block from running), or you can use something like `-ErrorVariable` and then do assertions against that. Something along these lines:
> 
> ```powershell
> It 'Error should be raised' {
>      My-FunctionThatWritesErrorForInvalidPath -Path '.\InvalidPath' -ErrorVariable err
>      $err.Count | Should Not Be 0
>      $err[0].Exception.Message | Should Be "Path '.\InvalidPath' is not valid" # or something like that
> }
> 
> # or
> 
> It 'Error should be raised' {
>      $scriptBlock = { My-FunctionThatWritesErrorForInvalidPath -Path '.\InvalidPath' -ErrorAction Stop }
>      $scriptBlock | Should Throw "Path '.\InvalidPath' is not valid" # or something like that
> }
> ```

Thanks so much for these tips, very helpful.

Just one little note.  The first solution will still display the error on the screen which may be rather distracting while running Pester.  You may simply add `-ErrorAction SilentlyContinue` to avoid this happening.

Cheers
Fotis

**Comment by deadlydog** [comment]
I believe this is probably a pretty common scenario, so I updated [the `Should` documentation](https://github.com/pester/Pester/wiki/Should#throw) to include a blurb about it in the `Throw` example, with a link back to this issue 🙂

**Comment by RobJohnson459** [comment]
I know I'm new and this may be obvious to those who have used this a lot before, but doesn't the `stop` keyword in the code blocks above need to be in quotes?

In any case, I ran into a situation where I wanted to test that a warning was printing, so I had to make use of the piping operator to test:

```
Describe 'Get-RelativePath' {
    Context 'Filesystem Paths' {
        It 'Should return a warning when given incorrect paths' {
            $temporaryFile - $PSScriptRoot + '\notARealFile.txt'
            New-Item -Path $temporaryFile -ItemType 'file' -Force
            Get-RelativePath -Path 'C:\invalid\path'  3> $temporaryFile
            $temporaryFile | Should -not -BeNullOrEmpty
            $temporaryFile | Should Be ( 'your Error Message here' )
        }
    }
```

All this does is pipe all the errors to a file named 'notARealFile.txt' that you can then check yourself.

**Comment by fflaten** [comment]
> doesn't the `stop` keyword in the code blocks above need to be in quotes?

No. `-ErrorAction` is of type enum (a pre-defined list of values) and not a string. Even if it was a string parameter, values without whitespace are usually okay (fixed automatically by powershell).  

> All this does is pipe all the errors to a file named 'notARealFile.txt' that you can then check yourself. 

You are actually saving warnings (stream 3), not errors. So this is unrelated to this issue. You can avoid the file all together by just redirecting to a variable `Get-RelativePath -Path 'C:\invalid\path' 3> $myWarnings` or if this command a "advanced function" (ex uses `[CmdLetBinding()]`), then you can use `Get-RelativePath -Path 'C:\invalid\path' -WarningVariable mywarnings`.

**Comment by RobJohnson459** [comment]
Thanks for the `-ErrorAction` clarification. And piping to a variable would be a better idea for my use case, thanks.
