### ISSUE TITLE
Fresh Clone, build fails, is there anything I need to do to get started?

### ISSUE THREAD

**Issue by ChaseFlorell** [pester/Pester#367]
I just did a fresh fork/clone and ran `build.bat`. I want to make sure I'm not missing anything before I get started, as the build failed on 2 version tests.

![](http://i.imgur.com/bLxAn9O.png)

**Comment by dlwyatt** [comment]
The version tests are there to prevent our automated jobs in TeamCity from publishing the module to Chocolatey / NuGet / PowerShellGet unless we've set up the changelog, module manifest, and git tag all to the same version number.

You can ignore those, or run it with `-ExcludeTag VersionChecks`

**Comment by ChaseFlorell** [comment]
ah, sweet, thanks for that.

**Comment by dlwyatt** [comment]
BTW, I don't think you can pass the ExcludeTag parameter to the psake build script without some modifications, but you can pass it to either pester.bat or Invoke-Pester.
