### ISSUE TITLE
New-Fixture creates code that can cause a StackOverflowException because it uses case sensitive matching

### ISSUE THREAD

**Issue by theficus** [pester/Pester#369]
I noticed something interesting with the code created by New-Fixture. It adds a line like this:

``` powershell
$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path).Replace(".Tests.", ".")
```

This creates a problem when you use Invoke-Pester, if you type the test name using ".tests" instead of ".Tests" (note the case) it ends up continually re-running $sut as it doesn't replace ".tests" as it would if it was typed as ".Tests". This eventually causes the script to fail with a SOE.

The $sut code created by New-Fixture should replace the $sut code with a method that does a replace in a case-insensitive manner (unfortunately string.Replace doesn't have an overload that supports StringComparison so Regex.Replace may be the best option here).

**Comment by dlwyatt** [comment]
LOL, oops.  :)  I'll probably fix it like this:

```posh
$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path) -replace '\.Tests\.ps1$', '.ps1'
```

**Comment by it-praktyk** [comment]
It looks trivial but still is not implemented. Can I grab it?

**Comment by nohwnd** [comment]
@it-praktyk sure. It would be nice if you figured a way to test this so we don't run in the same bug again.

**Comment by nohwnd** [comment]
Probably to just use `-replace` which is still case-insensitive.

**Comment by it-praktyk** [comment]
I need to check impact for Linux and Mac OS support too.
