### ISSUE TITLE
Should throw should allow specification of Exception type and partial message matching

### ISSUE THREAD

**Issue by pcgeek86** [pester/Pester#372]
The `should throw` statement should allow me to specify the type of Exception that I am expecting to be thrown, and also offer the option of performing regular expression matching against the Exception message.

The need for this stems from the fact that a `ScriptBlock` may thrown different types of exceptions, and I need the ability to determine which exception was thrown, based on the Exception type, or a part of the Exception's `Message` property.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by dlwyatt** [comment]
This is probably a duplicate of #279 .  It's something that's coming in v4, with some new syntax options for the Should command.

**Comment by pcgeek86** [comment]
Dave,

You're right, it is a duplicate. Thanks for pointing that out. I'll go ahead and close it.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
