### ISSUE TITLE
Invoke-Pester needs a -Path parameter

### ISSUE THREAD

**Issue by pcgeek86** [pester/Pester#374]
The `Invoke-Pester` command should have a `-Path` parameter, that allows the user to perform a one-time invocation against a particular filesystem path. It appears that the `-Script` parameter achieves a similar objective, but the name is not quite as familiar with your average PowerShell user.

I would propose the following:

1. Rename the `-Script` parameter to `-Path`
2. Add a parameter alias named `Script` to the `-Path` parameter

A less preferred option would be:

1. Add a parameter alias named `Path` to the existing `-Script` parameter

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by dlwyatt** [comment]
-Path is an alias for -Script. I chose that name because -Script allows you to do more than just pass in a path as a string. (It can also take hashtables, similar to constructed properties in Select-Object.)

**Comment by pcgeek86** [comment]
I should have validated that before I submitted this. Didn't realize it already existed as an alias, sorry about that.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
