### ISSUE TITLE
v3.3.5 :: It "Should be $null" fails when exception is thrown

### ISSUE THREAD

**Issue by pcgeek86** [pester/Pester#375]
### Issue

The `it` block and `should be $null` Pester statement fails to pass when a PowerShell function throws an exception, even if the Output stream is `$null`.

```
		It -Name 'Should return null when the -WhatIf parameter is used' -Test {
            ### The following line throws an exception (terminating error)
			$Output = Get-SomeObject -Param1 Value1 -WhatIf;
			$Output | Should Be $null;
		}
```

### Expected Results

The `it` block and `should be $null` statement should be configurable to ignore exceptions.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by pcgeek86** [comment]
ps. I worked around this by wrapping the call to `Get-SomeObject` in a `try..catch` block.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by dlwyatt** [comment]
I don't think there's a way for Pester to do this itself reliably.  Terminating errors are always going to screw with your code if you don't explicitly handle them.
