### ISSUE TITLE
How to mock system cmdlets when a module is imported as Global?

### ISSUE THREAD

**Issue by ChaseFlorell** [pester/Pester#379]
With my tests, I'm required to import the modules as Global (per #364).

Now doing this causes all mocks to be assumed under my module if I do not provide a `-moduleName` parameter to my mock.

I'm trying to test a method of mine that calls `Add-Content`, but when I mock it, I can't seem to get it working.

    $ErrorActionPreference = 'Stop'
    
    Describe 'Add-HostsFileEntry' { 
       Mock Add-Content  -scope Describe -moduleName 'Microsoft.PowerShell.Management' 
       
        Context 'Handle a valid tool.'{
            # Setup
            
            # Execute
            $execute = { Add-HostsFileEntry 'my-temp-hostname.com' }
            
            # Assert
            It 'Will call Add-Content' {
                Assert-MockCalled Add-Content -scope Describe -moduleName 'Microsoft.PowerShell.Management' 
            }
        }
    }

> Describing Add-HostsFileEntry
>  [-] Error occurred in Describe block 296ms
>    Module 'Microsoft.PowerShell.Management' is not a Script module.  Detected modules of the following types: 'Manifest'
>    At C:\Dev\poshBAR\Packages\Pester.3.3.9\tools\Functions\InModuleScope.ps1:128 char:9

**Comment by dlwyatt** [comment]
The name you pass to `-ModuleName` should be the module that contains the _calls_ to Add-Content, not the module that defines the Add-Content command itself.  (In this case, it's likely to be whatever module has the `Add-HostsFileEntry` command).

**Comment by ChaseFlorell** [comment]
Ok, that makes sense, however, when I do that the Mock isn't called, but the actual implementation.

This is my implementation

function Add-HostsFileEntry
    {
        [CmdletBinding()]
    	param(
            [parameter(Mandatory=$true,position=0)] [string] [alias('hn')]$hostName,
            [parameter(Mandatory=$false,position=1)] [ValidatePattern('\d{1,3}(\.\d{1,3}){3}')] [string] [alias('ip')] $ipAddress = "127.0.0.1",
            [parameter(Mandatory=$false,position=2)][switch] $includeLoopbackFix
    	)
        $ErrorActionPreference = "Stop"
        Write-Host ($msgs.msg_add_host_entry -f $hostName) -NoNewLine
    
    	$HostsLocation = "$env:windir\System32\drivers\etc\hosts"
    	$NewHostEntry = "`t$ipAddress`t$hostName"
    
    	if((gc $HostsLocation) -contains $NewHostEntry)
    	{
            Write-Host "`tExists" -f Cyan
    	}
    	else
    	{
    		Add-Content -Path $HostsLocation -Value $NewHostEntry
            Write-Host "`tDone"
    	}
    
    	# Validate entry
        Write-Host ($msgs.msg_validate_host_entry -f $hostName) -NoNewLine
    	if((gc $HostsLocation) -contains $NewHostEntry)
    	{
            Write-Host "`tPassed" -f Green
    	}
    	else
    	{
            Write-Host "`tFailed" -f Red
    	}
    
        if($includeLoopbackFix.IsPresent){
            Add-LoopbackFix $hostName
        }
    }

And when I run the test above and actually execute the `$execute` block, my host file get's updated 

Again, I have a hunch that it's because I'm forced to bring my module in Globally, but I'm not sure.

**Comment by ChaseFlorell** [comment]
NM, I get it now.
I still have to add the name of *MY* module. It's all become so much clearer.
