### ISSUE TITLE
Why does Invoke-Pester contain a do { .. } while ($true) loop?

### ISSUE THREAD

**Issue by Remco-74** [pester/Pester#381]
In the middle of Invoke-Pester (the main test loop) uses a *do { .. } while ($true)* loop. It seems to do nothing, and removing it leaves everything working as before.

What is the reasoning behind using the *do .. wile* loop, and can it be removed?

**Comment by dlwyatt** [comment]
That's there to handle cases where the user's test script has a `break` or `continue` statement in the wrong place.  Previously, those were causing the entire test suite to abort, but now Pester's code will continue running where it left off.
