### ISSUE TITLE
Make the -CodeCoverage parameter easier to use

### ISSUE THREAD

**Issue by Remco-74** [pester/Pester#383]
I really like the code coverage feature of Pester. I do think it can be even better by making -CodeCoverage a switch parameter instead.

Right now using codecoverage requires that you specifiy the files to measure coverage for. I suspect most users just use -CodeCoverage *.ps1, or even -CodeCoverage * and ignore the warning about non-powershell files.

Why not just use -CodeCoverage as a switch parameter, and let Pester figure out the right thing to do?

**Comment by dlwyatt** [comment]
Too many ways for us to get it wrong, I think.  Some people place their source code and test files in the same folder, others place them into different subfolders (src and test, that sort of thing).  By requiring the user to specify which files they want to analyze, Pester doesn't have to figure any of that out.

And as you say, the simplest use cases of `-CodeCoverage *.ps1` and `-CodeCoverage *` really don't add much in the way of extra typing anyway.
