### ISSUE TITLE
Mock -Verifiable does not reset the invocation counter within the same Context

### ISSUE THREAD

**Issue by dfch** [pester/Pester#385]
When using `Mock FunctionToBeMocked -Verifiable -With {}` and `Assert-MockCalled FunctionToBeMocked -Exactly 1` the counter is not reset in the same `Context` across separate tests. 

Even when you redefine the mocked function and use it in separate `It` test cases the counter is still not reset. Only when you create a second `Context` the counter of `Mock-Assert` will be reset.

My question: is this an intended behaviour? I find it strange that I can redefine the mocked function within a test case but have no means to reset the counter (or to _read_ the current counter). This would imply I have to create one context per test case if I want to verify the number of times my mocked function has been called.

See [MockTimesExactly.Tests.ps1](https://gist.github.com/dfch/5b1b64afd0be13f4c4e5#file-mocktimesexactly-tests-ps1) for an example.

This is the test output:

	Describing Test-MockTimesExactly.ps1
	   Context Test-MockVerifyOccurence1
		[+] MockFunction-ShouldSucceedOnFirstTest 115ms
	   Context Test-MockVerifyOccurence2
		[+] MockFunction-ShouldSucceedOnFirstTest 148ms
		[-] MockFunction-ShouldSucceedButFailsOnSecondTest 52ms
		  Expected FunctionToBeMocked to be called 1 times exactly but was called 2 times
		  at line: 67 in
		  67:                       Assert-MockCalled FunctionToBeMocked -Exactly 1;

**Comment by dlwyatt** [comment]
You can make your tests work by adding `-Scope It` to the calls to `Assert-MockCalled`.

Incidentally, you don't need to use the `-Verifiable` switch on your mocks or the `Assert-VerifiableMocks` command at all, if you don't want to.  That's the old way of doing things, and is only still here for backward compatibility.  `Assert-MockCalled` gives you much finer control over those assertions, and is the only thing I use in my own tests.

**Comment by dfch** [comment]
Hi @dlwyatt , thanks for your quick answer and clarification! Sorry that I did not read the [wiki](https://github.com/pester/Pester/wiki/Assert-MockCalled) thoroughly. I was somehow expecting this in the `Mock` command.
Thanks again! Regards, Ronald
