### ISSUE TITLE
Module '' is not a Script module.  Detected modules of the following types: 'Manifest'

### ISSUE THREAD

**Issue by alextc** [pester/Pester#387]
Hi,
I am getting this error message:
Module '' is not a Script module.  Detected modules of the following types: 'Manifest'
when attempting to use Mock -ModuleName when the module is a nested module.

Here is my test:

Import-Module LocalAdminPasswordReset

Describe "Assert-LocalAdminPasswordAgeHasNotExceededResetThreshold.psm1" {
	Context "When Threshold reached" {
		Mock -ModuleName LocalAdminPasswordReset Get-LocalAdminPasswordAgeInHours { 100 }

		It 	"Should return false when password age is greater than the threshold" {
			# Default threshold is 24 hours
			Assert-LocalAdminPasswordAgeHasNotExceededResetThreshold | Should be $false
		}	
	}
}

LocalAdminPasswordReset module (which is on PSModulePath) is a nested module. The psd1 file for the module contains multiple nested modules:
GetLocalAdminPasswordAgeInHours.psm1 where the LocalAdminPasswordAgeInHours CmdLet is 
defined.

AssertLocalAdminPasswordAgeHasNotExceededResetThreshold.psm1 where the Assert-LocalAdminPasswordAgeHasNotExceededResetThreshold is defined.

Is this a supported scenario? 
Are there workarounds to make this scenario work?

Thanks
Alex.

**Comment by dlwyatt** [comment]
If I remember correctly, it should work if you specify the name of the nested module in your calls to Mock and/or Assert-MockCalled.
