### ISSUE TITLE
Mock of Get-WmiObject Does Not Return Expected Value

### ISSUE THREAD

**Issue by bgshacklett** [pester/Pester#390]
This is related to the last issue I opened, but I felt it was different enough to have its own space. I'm mocking Get-WmiObject with `return @('10.0.0.1','10.0.0.2')`, but it seems that the mocked command isn't returning anything, as Compare-Object throws 'Cannot bind argument to parameter 'DifferenceObject' because it is null.'

I feel that I'm probably missing something silly, but I've spent hours on this with no forward progress, so I figured it was time to ask for help.

```
$ModuleName = 'testCase'
$ParentDirectory = Split-Path -Parent $MyInvocation.MyCommand.Path

$ManifestPath = "$ParentDirectory\$ModuleName.psd1"

Import-Module -Force $ManifestPath

Describe 'Test-Issue' `
{
    It 'Gets an array from the mocked object' `
    {
        Mock Get-WmiObject -ModuleName $ModuleName -Verifiable -MockWith `
        {
            return @('10.0.0.1','10.0.0.2')
        }

        $expected = @('10.0.0.1','10.0.0.2')
        $actual = Test-Issue

        Assert-MockCalled -ModuleName $ModuleName -CommandName Get-WmiObject

        Compare-Object $expected $actual | Should Be $null
    }
}

Remove-Module -Force $ModuleName
```

Output: 
```
Describing Test-Issue
 [-] Gets an array from the mocked object 271ms
   Cannot bind argument to parameter 'DifferenceObject' because it is null.
   at line: 20 in C:\Program Files\WindowsPowerShell\Modules\GoDnsServerManagement\testCase.Tests.ps1
```

Test-Issue Cmdlet:
```
function Test-Issue
{
    #TODO: Implement
    [CmdletBinding()]
    param()

    $queryArgs =
    @{
        NameSpace = 'root\MicrosoftDns'
        Class = 'MicrosoftDns_Server'
        Property = 'Forwarders'
    }

    return (Get-WmiObject @queryArgs).Forwarders
}
```

**Comment by dlwyatt** [comment]
That's a problem with your test logic, not with Pester.  Your Test-Issue command is calling Get-WmiObject, then returning the Forwarders property on the object(s) that Get-WmiObject returned.  Try it like this:

```posh
        Mock Get-WmiObject -ModuleName $ModuleName {
            return New-Object psobject -Property @{
                Forwarders = @('10.0.0.1', '10.0.0.2')
            }
        }
```

Incidentally, you don't need to use the -Verifiiable switch on Mock unless you also intend to use the older `Assert-VerifiableMocks` command.  `Assert-MockCalled` works fine without it, and offers a lot more flexibility besides.

**Comment by bgshacklett** [comment]
Awesome, that was it! I knew it was going to be something silly on my side. Thank you very much.
