### ISSUE TITLE
Idea: Should have the ability to retry when certain failures occur

### ISSUE THREAD

**Issue by theficus** [pester/Pester#391]
Sometimes when I run tests, I am performing operations that may randomly fail due to network connectivity. There's no good way to define "retry if" type behavior without modifying every single test or script to handle this inline.

It would be really nice if there was a way to define certain "retry" behaviors for tests -- such as retry n times if e exception occurs and the like. This would save me a bunch of time re-running the same tests over and over again because I ran into an intermittent infrastructure issue. 

One idea is something like this:

``` powershell
Describe ... -RetryCount 2 {
    OnThrow  {
        if($Error[0].Exception -eq ...) {
            return $true # retry if RetryCount is not exhausted
         }
         return $false # fail
    }
}
```

**Comment by dlwyatt** [comment]
I think it would probably be better to implement this as its own command (possibly in a separate module), rather than adding a new parameter to Describe and new parsing behavior to read the OnThrow block, particularly since this could be used outside of Pester as well.  Something like what Microsoft did with the [Remotely](https://github.com/PowerShell/Remotely) command.

**Comment by theficus** [comment]
Yes, implementing a new command would certainly work but a criteria I mentioned was not having to change every single unit test to take advantage of such a behavior. Leveraging this type of flow natively within Describe would make the impact of using it much more manageable. 

Another way to put it is I have a few hundred Describe { } blocks, but I have tens of thousands of It { } blocks. I'd much prefer to not have to change every single individual unit test to leverage retry logic versus changing a much more manageable set of Describe { } blocks.

**Comment by it-praktyk** [comment]
@theficus, based on @dlwyatt's answer I assume that it can be closed. Please reopen if needed.
