### ISSUE TITLE
Test ConfirmImpact Setting

### ISSUE THREAD

**Issue by ahaid** [pester/Pester#392]
There should be a way to test the confirm impact setting of a cmdlet. I want to know that I was challenged if I should have been.

**Comment by dlwyatt** [comment]
That is possible already, but I don't think it needs to be part of Pester itself.  Something like this should be fine:

```posh
Describe 'ConfirmImpact sample' {
    $command = Get-Command Enable-PSRemoting
    $metadata = [System.Management.Automation.CommandMetadata]$command
    
    It 'Has a ConfirmImpact of High' {
        $metadata.ConfirmImpact | Should Be 'High'
    }
}
```

**Comment by it-praktyk** [comment]
I assume that the issue can be closed now. Feel free to reopen if you need more assistance.
