### ISSUE TITLE
If an exception is thrown in BeforeEach, AfterEach is still run

### ISSUE THREAD

**Issue by theficus** [pester/Pester#393]
If an exception is thrown in BeforeEach, AfterEach is still run. This doesn't seem right to me as if BeforeEach fails there's no guarantee AfterEach will be in a good state to run.

Repro script:

``` powershell
Describe -Name "Repro" {
    BeforeEach {
        Write-Host BeforeEach
        throw "I failed"
    }

    AfterEach {
        Write-Host AfterEach
    }

    It "Does something" {
        Write-Host It test
    }
}
```

Output:

```
Describing Repro
BeforeEach
AfterEach
 [-] Does something 49ms
   I failed
   at line: 9 in E:\build\sms\psh\sms\PowerShell\UnitTest\Tests\Common\CMPSCmdlet.Tests.ps1
```

**Comment by dlwyatt** [comment]
I think that's a good thing, actually.  AfterEach blocks are essentially `finally` blocks, which should always run.  Your code can check for state before it does anything, if needed.

**Comment by theficus** [comment]
I sort of agree, but to the best of my recollection this is not how MSTest works so this inconsistency threw me for a loop. In MSTest if TestInitialize fails, TestCleanup is not called.

**Comment by nohwnd** [comment]
The MSTest behavior is actually filed as a [bug on MSConnect](https://connect.microsoft.com/VisualStudio/feedback/details/694337/testcleanup-method-does-not-run-when-it-should). All other frameworks that I've come by guarantee to run the cleanup part of the test to make it simpler for you to write the test, and to make the test runs consistent (details of one test must not leak to another test).

**Comment by it-praktyk** [comment]
I assume that the issue can be closed now. Feel free to reopen if you need more assistance.
