### ISSUE TITLE
If BeforeEach fails, the error message should clearly indicate that the failure occurred here

### ISSUE THREAD

**Issue by theficus** [pester/Pester#394]
This is just a minor feature request. I've found that when a test fails in BeforeEach this isn't clearly indicated in the logging. I mean sure I can just find the line in the script where the failure occurred but at a glance it would be nice to know that the test itself didn't fail but it was one of the pre-actions that failed instead.

**Comment by it-praktyk** [comment]
Sorry for a delay in a reaction. Can verify if the current version of Pester (4.0.6-RC) fulfills your request?

Thank you.

**Comment by nohwnd** [comment]
Looked at this and it would be quite easy to implement if we provide parameter to `Invoke-Blocks` catch and throw exception from there that will include both the information about where we failed, and with which error we failed. 

The only downside I can see is that we won't be throwing the original type of exception but a single type of exception with the original exception attached as InnerException. If people already have try catch block with a concrete filter in place we would be breaking their code.

**Comment by nohwnd** [comment]
We are filtering the messages in Output.ps1 to reduce the amount of clutter that you see when assertion fails, this is applied to the Describe failures as well so when there is internal failure the output is shortened and throws away useful info. Ideally we would distinguish between assertion failure, user-code failure and framework failure.

**Comment by nohwnd** [comment]
The error reporting improved signigicantly in v5, you see all errors if there are errors in the body and as well in the test or block or container teardown.
