### ISSUE TITLE
It (and Describe and Context) should support a WorkItem parameter

### ISSUE THREAD

**Issue by dfch** [pester/Pester#396]
When writing unit tests in Pester there currently is no means to associate a test case (`It`) with an actual work item. Though it certainly is possible to reference an issue in a commit message, you later cannot easily derive from the test code the actual issue this test case was addressing.

If we included a parameter that could reference an issue we could act upon test failures (and additionally take action upon that in an automated way) by evaluating the test output. 

The functionality should be similar or equal to what MSTest provides with the [WorkItem](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.testtools.unittesting.workitemattribute) annotation:

``` csharp
[WorkItem(42)]
```

The test case in Pester could be written like this:

``` powershell
It -WorkItem 42 { 2 + 3 | Should Be 5 }
```

This could be implemented as a parameter to the `It` Cmdlet (but might be useful also to the `Describe` and `Context` Cmdlets if a group of tests references a single work unit or issue).
In addition the `WorkItem` should be included in the test ouput as well (next to the test case, context or describe block) so during an automated build we can act upon that by parsing the output.

[Motivation for this suggestion: The idea behind this is that for every feature we at d-fens create several issues (as acceptance criteria defined by the behaviour derived from our BDD) before writing any code and having our tests reference these issues. As soon as the tests succeed we know that the feature works and is implemented being ready for the next quality gate. As some of our code relies on PowerShell scripts we would like to be able to apply that approach from C# and MSTest to PowerShell and Pester as well.]

What do you think of this suggestion? Regards, Ronald

**Comment by nohwnd** [comment]
@dfch that is an interesting idea. But I am afraid this would only work with TFS and so it seems to be too narrow scoped to be part of the framework. Also when I was looking up the details of the attribute usage, [this SO](http://stackoverflow.com/questions/7366495/use-for-workitemattribute) thread says that the attribute should not be used anymore in TFS 2010. And that it's not needed in VS 2013. Not sure how the bug to test linking works, but it might be something for you to look at.

**Comment by dfch** [comment]
@nohwnd thanks for your response. Regarding the `WorkItem`attribute: I am not referring to the TFS workitem, but to the [`Assert.WorkItem`](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.testtools.unittesting.workitemattribute.aspx) property (which is supported - including VS2015). In fact I just took this attribute and its name as an example on how this could be implemented.

On the 'server side' (which is TeamCity/GitHub in our case) we simply parse the code via the WebHook feature and look for this attribute (via Reflection). We could also use any other attribute or parameter, but a predefined attribute/parameter would be beneficial.

The SO discussion you are referring to mainly talks about TFS integration. I rather look for a universal approach that will work independent of a particular build environment (so 'CodeLens' would not be an approach either as not all PoSH developers work in VS (Enterprise|Professional)).

Of course I could just include my 'workitem' as a convention to the test name `It "#1-TheAnswerShouldBe42"`, but this rather seems error prone to me (and the 'refelection' approach to parse the PoSH code is quite stable and error-free).

So I am actually just asking for an additional parameter like this (and maybe some output during test execution):

	function It {
	PARAM
	(
		[ValidateScript( {$_ -is [int] -Or $_ -is [Array]} )]
		[Parameter(Mandatory = $false)]
		$WorkItem
	)

	# do something ...

	}

**Comment by dlwyatt** [comment]
Is there anything different about WorkItem than just -Tag?  (-Tag is currently only on the Describe command, but we could add this functionality to Context and It as well at some point.)

**Comment by dfch** [comment]
`tag` could be sufficient if it was available on `It` and `Context` as well. This would limit to assign a test to only a single workitem, but I would think this to be sufficient (the `workitem` annotation from `MSTest` allows for multiple entries, but this is should be no real limitation).

**Comment by it-praktyk** [comment]
`tag` is available on `Context` in Pester v4 - the final version will be released soon.

`tag` - or any other method to run a single test - is a subject of discussion in the issue #721 so I close the current issue now. If do you feel that issue still should be opened please feel free to reopen it but please put some justification for this, please. Thank you.
