### ISSUE TITLE
Automocking?

### ISSUE THREAD

**Issue by nobodyguy** [pester/Pester#398]
Hi, is there any way how to automock functions?
I have function that I want to test. And this function is calling another functions from our library. But we don't want to load the whole library because of unit tests. So I want to automock these functions (they should be dummy/stubs/whatever), because Pester gives me errors that these functions don't exist.
I think we tried also PSMock and it's OK in that mocking framework.

**Comment by nohwnd** [comment]
There is not. But you can simply define `function Name-OfTheFunctionFromTheLibrary {}` before your mock and then mock it. It's a bit unwieldy but it's still better than making a typo in a mock name ( like Remvo-Item ) and not being notified about the problem. Maybe `-Force` on the mock should permit creating mock without any backing function. I remember having discussion on the topic of mocking non-existing function with @dlwyatt, but I don't remember the conclusion.

**Comment by dlwyatt** [comment]
Right now, the main reason Pester needs to see the original command is so the mock can copy that command's parameters (including dynamic).  However, you can define a function with the same name and the same parameter sets, then mock that (for tracking purposes).

It may be possible for us to put this functionality directly into the Mock command at some point, but for now, it's two steps.

**Comment by nobodyguy** [comment]
Thank you for your quick responses, guys!
I tried to use PSMock together with Pester and it worked great, but I had to clean mocks manually.
Anyways, I've created Mock-All($path) function, that goes through content of file from $path parameter, finds callings of external functions and creates stubs for them... But I don't have to explain how ugly is it.

Defining these functions manually is a bit uncomfortable, -Force param for Mock function looks great. So it depends how much is it aganist ideology of Pester and how hard it would be to implement it.

**Comment by nohwnd** [comment]
As @dlwyatt mentioned the Mock needs the original function to know what is it's signature (What params it has.). That way you can use the ParameterFilter parameter to filter mock call history and as a result you can for example check if a Mock of Get-Computer was called only once with -ComputerName localhost. 

In theory there is a way around that if you want the ParameterFilter to work. We could probably do a bit of magic to make the mock work like this: 
```powershell
# make the mock define the function without any parameters
Mock Some-Function -Force 

# this function is not defined
Some-Function -ComputerName localhost -Value 120 

# check if the call with that parameter was done, but do not guarantee 
# that the filter paremeter actually exists on the function
Assert-MockCalled -ParameterFilter { $Value -eq 120 } -Exactly 1 
```
But as I said the Mock would not be able to fail if the filter parameter was not present on the function , so it would make the Mock even more complex that it is now. Plus there would have to be quite a lot of changes in the Mock code to handle this kind of scenario I suppose.

**Comment by nobodyguy** [comment]
I agree it could be a lot of work, but I don't think it's magic. I use unittest library for testing my Python scripts and you can create completely stupid Mock without knowing anything about API and call it with anything you want and still ask the mock about called params and their values. Or you can create Mock with option called autospec and it creates mock with the same parameters (=it knows about API).
What do you think? Maybe what about separation of this behaviour to another script, if it makes sense?

**Comment by dlwyatt** [comment]
It's very tricky to do that in PowerShell, when you take pipeline input into account (particularly ValueFromPipelineByPropertyName).  When you create an empty function and call it with "parameters", what you wind up with are the $args array (where you have to do the parsing yourself, figure out which parameters have arguments and which are switches, etc), and the $psitem / $_ variables for pipeline input.

Frankly, it's a giant pain in the butt to do things that way, and much nicer to define a mock with parameter metadata (which makes the PowerShell engine do all of that parameter binding work for you.)

**Comment by nobodyguy** [comment]
Ok, thanks for the info. I guess I have to solve it all by myself or try another way.

**Comment by nohwnd** [comment]
Hello, @nobodyguy  I am having [a discussion](http://blogs.msdn.com/b/brian_farnhill/archive/2015/09/10/how-to-unit-test-powershell-scripts-that-call-cmdlets-from-the-sharepoint-snap-in.aspx) with @BrianFarnhill about mocking SharePoint cmdlets without actually having them. I introduced a function that generates a stub for a module, that might work for your case. Could you test it, and share some feedback please? Would you like to see something like that to be part of the framework? 

```powershell 
function Get-ModuleStub ($ModuleName)
{
   (Get-Command -Module $ModuleName)  |  ForEach-Object -Process {
       $signature = $null
       $command = $_
       $metadata = New-Object -TypeName System.Management.Automation.CommandMetaData -ArgumentList $command
       $definition = [System.Management.Automation.ProxyCommand]::Create($metadata)  
       foreach ($line in $definition -split "`n")
       {
           if ($line.Trim() -eq 'begin')
           {
               break
           }
           $signature += $line
       }
       "function $($command.Name) { `n  $signature `n } `n"
   }
}

Get-ModuleStub SharePoint | Out-File PortableSharepoint.psm1
```

**Comment by dlwyatt** [comment]
That's a cool idea.  Dynamic parameters on cmdlets would still be a problem, but everything else could be handled with similar code to what the Mock command already does.

**Comment by nohwnd** [comment]
@dlwyatt IMHO we don't need to change anything in Pester to make this work. You just need to deploy those module stubs to your testing environment, and create Mocks in your test code as usual.

But in the future it would be nice to be able to run whole test suite against stubs of multiple versions of the real module, as mentioned in comments to the original article. But I am afraid there are very few users who would actually use that. For that we would need to change the Invoke-Pester I think.

**Comment by BrianFarnhill** [comment]
I agree @nohwnd - while it would be super awesome from my point of view to just say "run these tests with these stubs, and then these ones from a different version", I feel I'm way out there in edge case territory and probably not in the mainstream here. I do plan on taking your script sample for a spin to see if I can generate multiple versions of the stubs for different versions of SharePoint though and see about how I can inject that in to the tests I have, so we'll see how that goes as a starting point.

**Comment by nohwnd** [comment]
@BrianFarnhill Check the `Script` parameter on `Invoke-Pester`. I think Dave introduced this based on a request for parametrised runs of the test suite. If I recall correctly you can use it to run the test suite multiple times with different parameters and still get a single nUnit xml in the end to pass to your test result visualiser. 
So I might have been wrong, maybe we don't need to change anything in the module to facilitate your use case.

**Comment by BrianFarnhill** [comment]
@nohwnd Sure, I'll kick the tyres on it and will let you know how it goes. Thanks for the direction

**Comment by BrianFarnhill** [comment]
@nohwnd Well 20k lines of stub later, looks like I have something that might be viable here. Had to modify the Get-Command statement a little from your sample (The SharePoint cmdlets ship in a snap-in, not a module so I can't use module name to pull them out) but it looks like I have some stubs that are ready to throw back in to the scripts here. Give me a few days to finalise some changes I'm in the middle of to my DSC resources but then I'll take this out for a spin. Appreciate the assist on this one!

**Comment by BrianFarnhill** [comment]
@nohwnd Just looking at how we integrate this in to our process a little - I might need to look at scripting the load of the stub module within my tests. Reason being that I can't see a way to have an impact over the Invoke-Pester statement when I'm executing my tests from within Visual Studio. Not really a show stopper I guess but it's been nice having the tools all in one place as I'm scripting.

**Comment by nobodyguy** [comment]
Hi, I'm on vacation right now, so I'll play with that as soon as I return back home. It looks really awesome and I ended up with something similar (but uglier). Does it also work for cmdlets written in C#?

**Comment by nohwnd** [comment]
@nobodyguy It does work for cmdlets. One thing that @BrianFarnhill discovered though, is that some of the parameters have non-standard types. So currently we are looking in ways to overcome this.

**Comment by BrianFarnhill** [comment]
@nohwnd @nobodyguy - So the non-standard types are proving challenging to handle. I have an approach where I can scan for the types based on the abstract syntax tree of the stub module that we generate and I can load them all in, but the issue comes from where functionality if provided through them that I depend upon, such as converting values. For example:

    Get-SPServiceApplicationPool -Identity "My application pool name"

Identity is of the type "Microsoft.SharePoint.PowerShell.SPIisWebServiceApplicationPoolPipeBind" which will quite happily take in a string, or a GUID, or a couple of other object types (I think, there are other "PipeBind" data types in SharePoint that do similar things) and the cmdlet will just figure out what it needs to do based on the actual type applied. Now this is fine where I run on a machine that has the type on there for it to be able to do the conversion, but I hit the problem where I see this error:

Cannot process argument transformation on parameter 'ApplicationPool'. Cannot convert the "Test App Pool" value of type "System.String" to type "Microsoft.SharePoint.PowerShell.SPIisWebServiceApplicationPoolPipeBind".
at line: 34 in xSharePoint.Util.psm1

I can't think of a way to fake what I need to here, which might mean I need to look at dumbing down the object types in the stubs to bring them all back to basic types - in the case of SharePoint though there are around 200+ data types I need to deal with if I wanna handle everything. My script won't make calls to everything so I won't need them all (I should be able to parse my scripts maybe and then extract only the types I need and mess around with them) but I feel like I'm getting in to a much less elegant solution the further I'm pushing this. 

Definitely open to suggestions here though guys

**Comment by nohwnd** [comment]
I don't think we should automock, it would bring a lot of issues and generating stubs is quite easy (and it's better than mocking against parameterless functions).  What we should do is add the ability to relax the types that are emitted on the mock, becasue often (in unit tests) they are not needed and only bring problems.

**Comment by nohwnd** [comment]
Relaxing the parameter type of mock is covered by #601 stubbing methods can be done externally, as well as generating a function without any signature, closing this because I won't be adding automocking and the other concerns are hopefully covered in the other issues. Thanks for the discussion and sharing your experience.
