### ISSUE TITLE
Mocking .net types as parameters

### ISSUE THREAD

**Issue by CopterHat** [pester/Pester#400]
Currently Pester doesn't have support for mocking .net types that lack a purely abstract base class, interface, parameterless constructor, etc. Is there a recommended coding pattern for dealing with this problem in general or a plan for supporting this scenario? It would be nice if it were possible to have a fine-grained type for a parameter of a function without giving up the ability to test it.

**Comment by nohwnd** [comment]
Hello Christopher, 
could you provide an example of the issue you are facing, please?

Would you like to mock a call to a static method/property on a type? 
```powershell
[int]::MaxValue
```
In that case your only choice is to wrap that call in a PowerShell function and mock that instead:
```powershell
function Get-IntMaxValue 
{
    [int]::MaxValue
}
```

Would you like to mock a type in a function signature on a parameter that is marked as Mandatory?
```powershell
function Get-ReversedString
{
    [Parameter(Mandatory=$true)]
    param ([String]$Value)

    [Array]::Reverse(($temp=$value.ToCharArray()))
    -join $temp
}
```
That is not possible I am afraid, as you said unless the type used in the signature is an abstract class or an interface we can't substitute that type with our own implementation of the abstraction, that is we can't mock it. 
In theory this is a good thing, if we can't exchange types just willy-nilly, we can assure that the data passed will be of a given type and hence will have all the properties, methods and other features that we expect. On the other hand this makes it a bit difficult for us to test. But this is not PowerShell or Pester fault, this would be exactly the same in C#. It's not the matter of the tools, it's simply going against the rules of the language. 

But if you post an example maybe we can figure something out.

(As a side note, there is a framework called Moles that can do that, by doing some really clever (but awful) magic, but that should not be your daily routine.)

**Comment by CopterHat** [comment]
I think you've got it. If I have a mandatory parameter of some concrete type that comes out of some service or other and there's no other way to create such types then there's no way to mock it with Pester.

For normal code this is a good thing, but for being able to unit test it adds a big roadblock, you basically have to do integration testing, skip testing, or figure out some complicated way of passing parameters.

**Comment by it-praktyk** [comment]
I assume that the issue can be closed now. Feel free to reopen if you need more assistance.
