### ISSUE TITLE
Feature Request: TestDrive for Registry

### ISSUE THREAD

**Issue by robbiepc30** [pester/Pester#402]
One thing that I have been doing frequently in my scripts is writing to the registry. I've been using mocking to unit test anything that I write to the registry and it has worked well, but after using TestDrive in some of my scripts for writing and deleting files I keep wishing that I could do the same thing with the registry.

I was wondering if anyone else would be interested in seeing a feature like TestDrive for the Registry, and if its possible, could we see that as an added feature some time in the future.

**Comment by megamorf** [comment]
I think one could implement that with transactions since they don't directly write to the registry until you commit the changes with `Complete-Transaction`

http://blogs.technet.com/b/heyscriptingguy/archive/2015/04/23/using-transactions-with-powershell-registry-provider.aspx

**Comment by nohwnd** [comment]
That should be quite easy to implement, the test drive is just folder in Temp that has uniquely generated name. This folder is then mapped to the TestDrive PS Provider. You can do the same with registry. 

The only thing that would be a bit clumsy is that the Pester is not very modular at its core, so you need to setup and tear down the registry folder for each describe.

**Comment by JacodeWeerd** [comment]
I am starting to use Pester on PowerShell modules that do a lot of writing and reading to the registry. A testdrive for the registry would be great and would simplify the tests.
Thank you in advance!

**Comment by bwright86** [comment]
I am in the same boat with you all, doing some registry work and starting to use Pester for testing it. It would be nice to spin up a new test drive pointed to a hive file object in the $env:Temp path as well, something like TempReg: or HKTR:. 

Might just look at what it takes to spin up a registry hive in the Describe block, and tear it down afterwards.

**Comment by sam-bryant** [comment]
I also came across the need for this functionality.  +1

**Comment by fschumann1211** [comment]
I second the request. Also for an ActiveDirectory test drive +1

**Comment by nohwnd** [comment]
@fschumann1211 AD test drive is not going to happen, we would have to take dependency on the AD cmdlets, and install a real domain per-test :)) The registry test drive I'd like to implement, but unfortunately I have so little free time :/

**Comment by andikrueger** [comment]
I'm also looking for a way to test registry reads and writes. I could start to implement something similar to TestDrive, but see an issue with cross platform compatibility. Linux doesn't have something comparable. See: https://github.com/pester/Pester/blob/517f40c90f013e3d042d8845c68444c4c8728eb2/Functions/Environment.ps1#L32-L42
I pushed my current changes to this [branch](https://github.com/andikrueger/Pester/tree/issue-402) and am looking forward to your (@nohwnd) feedback about the OS compatibility.

**Comment by nohwnd** [comment]
@andikrueger looks good, I quickly read through it and don't see any obvious problems. Please make a PR from that branch. :) I'd like to test the clean-up a bit more, and see what is the impact on performance.
