### ISSUE TITLE
Support for PowerShell Workflows

### ISSUE THREAD

**Issue by cstewart87** [pester/Pester#404]
Has any testing been done in regard to Pester support for PS Workflows?  I made a little bit of progress with a very simple workflow by just validating the output, however I'm unable to mock any commands within the workflows.

**Comment by dlwyatt** [comment]
I don't know if that's even possible.  PowerShell workflows are compiled down into .NET workflows, are generally executed in separate processes (or on separate computers) from where they're invoked.  There may not be any opportunity for Pester to inject itself into those processes and mock commands.

**Comment by avishnyakov** [comment]
Hm.. +1 here.

The following one would be nice to pass, surely:

```
describe "Can_Run_Workflow" {

    It "Checks R365 environemtn creation" {

		function DoRequest($s) {

		}

		workflow myTest {
			param($servers)

			foreach -parallel ($server in $servers) {
			
				DoRequest $server
			}

		}
		
		myTest @('11', '22')
	}
}
```

Output:
```
Result Message:	
it Checks R365 environemtn creation
Windows PowerShell Workflow is not supported in a Windows PowerShell x86-based console. Open a Windows PowerShell x64-based console, and then try again.
```

**Comment by it-praktyk** [comment]
I assume - based on @dlwyatt's answer - that initial request was refused so I'm closing the issue now.
