### ISSUE TITLE
Is there a way to mock .ps1 files that start with [CmdletBinding()]?

### ISSUE THREAD

**Issue by alx9r** [pester/Pester#406]
The vast majority of functions I test are inside modules.  I have a project, however, where I am contemplating the use of `.ps1` files with a particular signature as a way to delegate some functionality to the user of some modules.  That is working nicely, however, I haven't figured out how to mock the `.ps1` files.  Below is a (non)working example of what I'm trying to do.

Running the test results in the following error:

>Could not find Command .\Multiply-NumberByFive.ps1

Is there a way to mock a dot-sourced script file that takes advanced function parameters?

### `module.Tests.ps1`
**Edit: I fixed this script after @nohwnd some errors.  The same error mentioned above remains.**

```Powershell
Import-Module module -Force

InModuleScope module {
    Describe Invoke-DotSourcedScript {
        Mock .\Multiply-NumberByFive.ps1 -Verifiable {20}
        It 'calls the mock.' {
            $r = Invoke-DotSourcedScript
            $r | Should be 20

            Assert-MockCalled .\Multiply-NumberByFive.ps1 -Times 1 {
                $number -eq 4
            }
        }
    }
}
```

### `module.psm1`

```Powershell
function Invoke-DotSourcedScript
{
    [CmdletBinding()]
    param()
    process
    {
        4 | . '.\Multiply-NumberByFive.ps1'
    }
}
```

### `Multiply-NumberByFive.ps1`

```Powershell
[CmdletBinding()]
param
(
    [parameter(ValueFromPipeline = $true)]
    $number
)
process
{
    5*$number
}
```

**Comment by nohwnd** [comment]
There are two mistakes in your code: 
- you are calling `Invoke-SomeFunction` from the test, but define `Invoke-DotSourcedScript` in the module. 
- you are calling `\Multiply-NumberByFiveFunction.ps1` but define `Multiply-NumberByFive.ps1`, missing the Function at the end of the name.

Another not an easy to guess problem is that the resolved name of the script is `Multiply-NumberByFiveFunction.ps1`, without `.\`. It's similar for all "aliased" calls. 

But in the end the `.` or even `&` invocation does not add one to the mock call history. You would be better off defining an `Invoke-Script` function with `-Name` parameter and call/mock that instead.

**Comment by alx9r** [comment]
Oh that's embarassing.  I should know better than to edit example code without running running it.  I have fixed (in the OP) the two mistakes you pointed out and re-ran the example code which produces the same error.

>But in the end the . or even & invocation does not add one to the mock call history. 

Thank you very much for pointing this out.  Indeed I haven't found a way have the mock called by the SUT at all.  I does seem that Pester accepts a mock for the .ps1 if you use the full path the .ps1:

````Powershell
Import-Module module -Force

InModuleScope module {
    Describe Invoke-DotSourcedScript {
        Mock "$PSScriptRoot\Multiply-NumberByFive.ps1" -Verifiable {21}
        It 'calls the mock.' {
            $r = Invoke-DotSourcedScript
            $r | Should be 21

            Assert-MockCalled "Multiply-NumberByFive.ps1" -Times 1 
        }
    }
}
````
However, if you run that test `$r` is `20` not `21` which indicates the SUT invokes the real .ps1.

I have followed your advice and used an `Invoke-Script` function instead.

Thanks for your help,

Alex

**Comment by nohwnd** [comment]
You are welcome. 

When debugging such issues it's I usually set breakpoint somewhere in the script, then step through the code till I get somewhere in the Pester code. When in Pester code you are in Pester scope, so you can inspect the $Pester variable that holds internal state and mock history. There are different ways of seeing the internal Pester state, but this is by far the easiest.
