### ISSUE TITLE
Would you like to include API documentation to your build?

### ISSUE THREAD

**Issue by ChaseFlorell** [pester/Pester#407]
I've got a build process that I've written to generate API documentation (like [MS TechNet](https://technet.microsoft.com/en-us/) docs) during my build.

I've run pester through the generator, and [here's the output](https://transcanada.github.io/Pester/).

I'm just wondering if you'd like to include it in your build in order to help people discover the API. If you're interested, I'd be happy to submit a PR.

**Comment by vors** [comment]
Looks slick!
Sorry for hijacking the thread, but do you generate it from Get-Help output?
I'm totally down to use it for my projects.

**Comment by ChaseFlorell** [comment]
yes, I fully generate it from the help documentation.

```
<#
.SYNOPSIS
Provides logical grouping of It blocks within a single Describe block. Any Mocks defined
inside a Context are removed at the end of the Context scope, as are any files or folders
added to the TestDrive during the Context block's execution. Any BeforeEach or AfterEach
blocks defined inside a Context also only apply to tests within that Context .
.PARAMETER Name
The name of the Context. This is a phrase describing a set of tests within a describe.
.PARAMETER Fixture
Script that is executed. This may include setup specific to the context and one or more It
blocks that validate the expected outcomes.
.EXAMPLE
function Add-Numbers($a, $b) {
    return $a + $b
}
Describe "Add-Numbers" {
    Context "when root does not exist" {
         It "..." { ... }
    }
    Context "when root does exist" {
        It "..." { ... }
        It "..." { ... }
        It "..." { ... }
    }
}
.LINK
Describe
It
BeforeEach
AfterEach
about_Should
about_Mocking
about_TestDrive
#>
```

**Comment by vors** [comment]
I didn't find a project in your github profile that does it. What do you use?

**Comment by ChaseFlorell** [comment]
It's hand rolled, and exists currently in my poshBAR project. I'm thinking of  moving it into it's own repo now that it's nearly full featured. Doesn't currently support `about_` stuff yet though.

**Comment by nohwnd** [comment]
Looks great! Will check it out more closely in the evening!

**Comment by dlwyatt** [comment]
We'd need to tweak it a bit for Pester; the Should command and the Before/After Each/All don't really expose much via the help system, which also makes the resulting API pages a bit lacking.  I'd love to use something automatically generated like this instead of the manually-edited wiki, though, so we don't have them getting out of sync.

**Comment by ChaseFlorell** [comment]
just to re-iterate, I've posted the code in a repo

If there are changes that need to be made to accommodate some of the advanced comments in Pester, I'd be happy to a) implement them, or b) accept a PR.

https://github.com/ChaseFlorell/psDoc

**Comment by nohwnd** [comment]
Checked it again on a computer, instead on a phone. I like it overall, but I am not big fan of the animations, the spacing between examples seems a bit off and the side menu is too wide.  But I guess all that can be easily changed in CSS right? :)

**Comment by vors** [comment]
CSS and there is also a [template](https://github.com/ChaseFlorell/psDoc/blob/master/src/out-html-template.ps1) file that describes the whole content. I think currently there is no separate CSS file actually. @ChaseFlorell correct me if I'm wrong

**Comment by ChaseFlorell** [comment]
It's using [bootstrap](http://getbootstrap.com/2.3.2/), and jQuery, and a couple of other things. There is *some* embedded CSS at the top, and the animations are embedded at the bottom (javascript). I intentionally didn't include local resources in this project as it just adds extra files that need to be moved around. Right now is simply generates a single index.htm file and links to a few well known CDN's.

**Comment by nohwnd** [comment]
Thanks for the explanation.

**Comment by it-praktyk** [comment]
It looks great.

Improvement in process of generating help and wiki is planned for Pester v4.1.

Are you still interested in participating in that work?

**Comment by ChaseFlorell** [comment]
Yeah I'd be interested. Also, now that Github allows for your pages to be generated directly out of a `/docs` folder on the master branch, it would be super easy to drop the output there.

**Comment by nohwnd** [comment]
@ChaseFlorell thanks for the info (again :))) about GitHub, I am putting this in 4.1 milestone

**Comment by nohwnd** [comment]
I never got back to this, if anyone wants to pick it up they are free to do so, but I likely won't implement it myself.

**Comment by fflaten** [comment]
Ready to close? Both Pester v4 and v5 command reference are available at https://pester.dev
