### ISSUE TITLE
Cannot debug BeforeAll/AfterAll/BeforeEach/AfterEach methods.

### ISSUE THREAD

**Issue by amitsara** [pester/Pester#409]
I am trying to debug setup method by putting breakpoints inside BeforeAll. 
Breakpoints are never hit, I am using PowerShell ISE for debugging my test.

**Comment by nohwnd** [comment]
@amitsara Works for me. What editor OS and version of PowerShell are you using?
![capture](https://cloud.githubusercontent.com/assets/5735905/10448418/0a84bde6-718d-11e5-8127-ea101e2e425f.png)

**Comment by dlwyatt** [comment]
Also, which version of Pester?  This was fixed in v3.3.9 (but only for PowerShell v3+, unfortunately.)

**Comment by nohwnd** [comment]
I am on `3.3.11` so that would explain why it works for me.

**Comment by amitsara** [comment]
Thanks, It works with latest version :)
