### ISSUE TITLE
Some way to detemine if script is running under Pester

### ISSUE THREAD

**Issue by matt-richardson** [pester/Pester#411]
It would be useful to be able to determine if a script is running under Pester.

I'll acknowledge that this isn't perfect, as it means your script will be different under test conditions, so you're testing something different to live, but in some circumstances, this is necessary.

It could be a global variable, or an environment variable, or???

**Comment by nohwnd** [comment]
What would be an example of such cirmustances? Are you trying to keep your functions and code that executes them in a single `.ps1` file, and prevent Pester from running the whole script when testing it? 

I wrote [an article](http://jakubjares.com/blog/2015/01/10/test-powershell-scripts-end-to-end-with-pester/) that talks about (not) running your code under Pester.

**Comment by matt-richardson** [comment]
Was chatting to @dlwyatt about this just as you replied :)

The use case is a a single script with functions and code that executes - a script that is used in TeamCity that needs to be self contained. 

I've ended up using your `$MyInvocation.InvocationName -ne '.'` method, however it needs a comment to explain what its there for, and also it doesn't work under PowerGui (i'm told).

A simple helper function that wraps this bit of code might make it a bit clearer.

**Comment by nohwnd** [comment]
Tehnically speaking it does work under PowerGui, the problem is that PowerGui dot-sources all the scripts, so the 'test' mode and actual script run are indistinguishable for that `if`. 

In the end the Pester Test files are just code, so you can set your own global variable in your test files and use your helper function to check presence/value of your variable.

**Comment by it-praktyk** [comment]
I assume that the issue can be closed now. Feel free to reopen if you need more assistance.

**Comment by sassdawe** [comment]
How can one reopen an issue?

My use case would be to include the information of the execution environment when the script generates it's own logs. Without any extra parameter.
`if ( $isPester ) { Write-Log "this is a test" }`

I hope this makes sense.

**Comment by nohwnd** [comment]
@sassdawe you can reopen it if you are the author of that issue. Please start a new issue and link to this one :)

**Comment by sassdawe** [comment]
I figured it out!

```PowerShell
BeforeAll {
    $isPester = $true
}
```
