### ISSUE TITLE
Assert-MockCalled ignored when break is used in process{}

### ISSUE THREAD

**Issue by alx9r** [pester/Pester#412]
I just noticed that Pester does not seem to assert that a mock is called when `break` or `continue` is invoked in the `process{}` block in the SUT.  The result is rather surprising since `Assert-MockCalled` succeeds despite that there is no reference whatsoever to the mocked function.  Here is the repro:

## module.psm1

````PowerShell
function Invoke-ProcessWithBreak
{
    [CmdletBinding()]
    param
    (
        [Parameter(ValueFromPipeline=$true)]
        $Item
    )
    process
    {
        if ($Item -eq 'breakItem')
        {
            break
        }
        if ($Item -eq 'continueItem')
        {
            continue
        }
    }
}
````

## module.Test.ps1

````PowerShell
Import-Module module -Force

InModuleScope module {
    Describe Invoke-ProcessWithBreak {
        Mock Write-Error -Verifiable

        # this test fails, which is correct
        Context 'normal' {
            It 'invokes Write-Error.' {
                'normalItem' | Invoke-ProcessWithBreak
                Assert-MockCalled Write-Error -Times 1 { $false }
            }
        }

        # this test succeeds, but should fail
        Context 'break' {
            It 'invokes Write-Error.' {
                'breakItem' | Invoke-ProcessWithBreak
                Assert-MockCalled Write-Error -Times 1 { $false }
            }
        }

        # this test succeeds, but should fail
        Context 'continue' {
            It 'invokes Write-Error.' {
                'continueItem' | Invoke-ProcessWithBreak
                Assert-MockCalled Write-Error -Times 1 { $false }                
            }
        }
    }
}
````

**Comment by dlwyatt** [comment]
The problem isn't that Assert-MockCalled is "succeeding", it's that Assert-MockCalled never gets executed in the first place.  The SUT is malformed; break and continue should not be used in process blocks.

It used to be that those malformed break and continue statements would abort the entire test suite, but fairly recently, we wrapped all calls to test code in a `do { } until ($true)` loop, so it only exits out from the current `It` (or `Context`, etc) block.

**Comment by alx9r** [comment]
Thanks for the clear explanation.

>The SUT is malformed; break and continue should not be used in process blocks.

Duly noted.  Do you mean that `break` and `continue` should not be used in the _outermost scope_ of a `process{}` block?  Or do you mean that `break` and `continue` should not be used at all inside `process{}`?

This came up during a SUT refactor where a section containing `break` that was once inside a `foreach` was moved into the outermost scope of the `process{}` block.  I find this sort of refactoring to be commonplace when doing TDD.  Obviously the `break` that was now no longer inside the `foreach` was left in place by mistake.  The surprise was that a bunch of tests that should never have passed, unexpectedly started passing.

In this _particular_ case it was obvious to _me_ that something had gone awry.  I can imagine refactoring scenarios, though, where I and others would not have noticed that a stray `break` is causing tests to falsely succeed.  

Is there some other way to surface that `break` inside a SUT prevented the rest of the `It{}` block from executing?

Thanks for all your help,

Alex

**Comment by dlwyatt** [comment]
`break` and `continue` should only be used inside a loop (foreach, while, or do), or a switch statement.  If you use them outside of one of those, unfortunately, PowerShell will start walking up the stack until it finds one to break out of (and will abort all executing scripts / pipelines if it can't find any.)

**Comment by alx9r** [comment]
Yikes.  In that case, I should probably rely on static analysis to detect stray `break` statements rather than expecting Pester to do so.
