### ISSUE TITLE
build.bat throws quotation errors

### ISSUE THREAD

**Issue by prikkeldraad** [pester/Pester#413]
When I run Build.bat in a directory containing spaces I get the following error:
dir : Cannot find path 'P:\Mijn' because it does not exist.
At line:1 char:22
+ $psakeDir = ([array](dir P:\Mijn Documenten\test\trunk\pester\Vendo ...
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (P:\Mijn:String) [Get-ChildItem], ItemNotFound
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

I rewrote part of the script to fix this:
```
@echo off

if '%1'=='/?' goto help
if '%1'=='-help' goto help
if '%1'=='help' goto help
if '%1'=='-h' goto help

"%~dp0vendor\tools\NuGet.exe" install "%~dp0vendor\packages.config" -o "%~dp0vendor\packages"
@SET cmd=$psakeDir = ([array](dir """%~dp0vendor\packages\psake.*"""))[-1]; ".$psakeDir\tools\psake.ps1" build.psake.ps1 %* -ScriptPath "$psakeDir\tools" ; if ($psake.build_success -eq $false) { exit 1 } else { exit 0 }
powershell -NoProfile -ExecutionPolicy Bypass -Command ^ "%cmd%"
goto :eof

:help
@SET cmd=$psakeDir = ([array](dir """%~dp0vendor\packages\psake.*"""))[-1]; ".$psakeDir\tools\psake.ps1 build.psake.ps1" -docs -ScriptPath "$psakeDir\tools"
powershell -NoProfile -ExecutionPolicy Bypass -Command ^ "%cmd%"
```

Hope it helps

**Comment by nohwnd** [comment]
@prikkeldraad  Great, thanks for the help! Could you possibly create a PullRequest for your changes? In case you need any help with that, please let me know.
