### ISSUE TITLE
Assert-VerifiableMocks not working?

### ISSUE THREAD

**Issue by pfaffle** [pester/Pester#416]
I have a function which checks for the existence of a path, and mocking it works fine except for when I try to assert that the mock itself was called.

```powershell
Function Get-Arch {
    if (Test-Path -Path "$env:systemroot\syswow64") {
        return 'x64'
    }
    return 'i386'
}

Describe 'Get-Arch' {
    It 'returns x64 on a 64-bit system' {
        Mock 'Test-Path' { $true } -ParameterFilter { $Path -eq "$env:systemroot\syswow64" } -Verifiable
        Assert-VerifiableMocks
        Get-Arch | Should Be 'x64'
    }
    It 'returns i386 on a 32-bit system' {
        Mock 'Test-Path' { $false } -ParameterFilter { $Path -eq "$env:systemroot\syswow64" } -Verifiable
        Assert-VerifiableMocks
        Get-Arch | Should Be 'i386'
    }
}
```

If I simply remove the `Assert-VerifiableMocks` calls, the tests pass, so obviously the mock is working. It seems like such a simple example. Am I doing something wrong here?

**Comment by dlwyatt** [comment]
You're calling `Assert-VerifiableMocks` before calling your `Get-Arch` function.  Just reverse the order, and call `Assert-VerifiableMocks` as the last step in each `It` block, and you should be fine.

**Comment by pfaffle** [comment]
Well now don't I feel dumb? :)

Thanks, it works fine.
