### ISSUE TITLE
Mock inside a Mock? Mocking within scriptblock of Invoke-Command calls.

### ISSUE THREAD

**Issue by goomyman** [pester/Pester#418]
Is there a way to unit test an invoke-command call that needs to mock within the script block or a best practice for this?

I have code that does invoke command calls which I wish to unit test.   The best way I have come up with would be to Mock the invoke-command call itself and then call the same script block within the Mock.   This works except when I want to mock within that script block.  

Is there a way to do this without putting conditional statements in my code to bypass invoke command calls just for testing

I am looking for a way to invoke mocks within a scriptblock invoke command in a mock or some other method to do this without altering the original code. 

Hope this makes sense and that I am asking an appropriate question in an appropriate location.

Thank you!

**Comment by nohwnd** [comment]
@goomyman Could you provide an example, please? 
To me it seems like you need to decide what you are testing. You should be asking only one of those questions in your test: "Was the Invoke-Command called?" or "Is MyInnerAction invoked correctly?" or  "Is the result of MyInnerAction propagated correctly?" but not all of them at the same time. Here is some code to show the "patterns":

```powershell
function MyInnerAction {
    #delete all files on disk
    #and return 1
}

function MyCommand
{
    Invoke-Command { MyInnerAction }
}

Describe "Invoke testing" {
    Context "Scope for the Invoke-Command Mock" {
        It "Was the Invoke-Command called?" {
            # -- Arrange
            Mock Invoke-Command { }
            
            # -- Act
            MyCommand
        
            # -- Assert
            Assert-MockCalled -CommandName Invoke-Command -Scope It
        }
    }

    It "Is MyInnerAction invoked correctly?" {
         # -- Arrange
        Mock MyInnerAction { }
            
        # -- Act
        MyCommand
        
        # -- Assert
        Assert-MockCalled -CommandName MyInnerAction -Scope It
    }

    It "Is result of MyInnerAction propagated correctly?" {
        # -- Arrange
        $expected = 1
        Mock MyInnerAction { $expected }
            
        # -- Act
        $actual = MyCommand
        
        # -- Assert
        $actual | should be $expected
    }
}
```

**Comment by goomyman** [comment]
Thank you very much for the reply and I understand the comment around how to design code to be testable which is always desired. 

The use case I am describing involves a lot of remote powershell commands where all the business logic is done remotely.   Now I could break this up or test the business logic separately in local unit testable functions and use that local function as a scriptblock in an invoke command call but I find its hard to get developers to write unit tests if they have to change their coding habits ( which is not a bad thing ).  Large chunks of business logic within remote calls is very common to see.

Here is a fake example so don't read to much into it but imagine I have to first log into a host machine to perform some actions such as starting a VM and then validating that the VM is ready to accept requests.  Ignore the fact that Get-VM and Start-VM support remote calls for this scenario where I wouldn't need to run remotely.  Testing that Invoke-Command was called is not an interesting test if the logic falls within the remote command. 

Start-VMExample
{
  params($hostServer, $vmName)

  Invoke-Command -ComputerName $hostServer {        

       $vm = Get-VM | ? Name -EQ $Using:vmName

       Start-VM $vm

       # Business logic here to loop and wait for VM to be able to receive requests
  }
}

Because the entire script I wish to test is within a remote call as its currently written it makes it hard to test.  

I don't have a good answer for unit testing this scenario or any remote call scenarios other than separating out your code into testable functions but this is not powershell's strong suit.  

What I did try was Mocking Invoke-Command and then calling invoke on the script block to complete the test but that does not allow mocking more calls such as Get-VM and Start-VM etc within the script block.  Of course validation is also a problem. 

I don't have an answer but unit testing where the business logic calls within remote calls is an interesting use case.

**Comment by nohwnd** [comment]
@goomyman One thing that should be possible is to split the remote scripblocks in separate `.ps1` files, and then use the `FilePath` param of the `Invoke-Command` to run those scripts. 

To test those scripts you could use one of the approaches described [here](http://jakubjares.com/blog/2015/01/10/test-powershell-scripts-end-to-end-with-pester/). 

This of course assumes that you have the needed cmdlets available on your local system, or that you deploy the tests to the remote system.

**Comment by scorpionlion** [comment]
Hi, there I have a similar example where I want to Mock a function which is called by Invoke-Command.

`   
     
    function Common-Write-Log-Console
    {
	    param (
		    [Parameter(Mandatory=$true)]
		    [string] $logText
		    )

		    $textToOutput = [String]::Format("{0}:{1}", [System.DateTime]::Now.ToString(), $logText)
		    Write-Output ($textToOutput)
    }


    function Common-Write-Log-WithInvoke
    {
	    param (
		    [Parameter(Mandatory=$true)]
		    [string] $logText

		    )
	
	    foreach($logger in $loggers.Values)
	    {
		    Invoke-Command $logger -ArgumentList $logText,$verbosityLevel,$logType
	    }

    }




    function Common-Write-Log-WithoutInvoke
    {
	    param (
		    [Parameter(Mandatory=$true)]
		    [string] $logText, 
		    [string] $verbosityLevel = "Normal",
		    [string] $logType = "Info"
		    )
	
	    Common-Write-Log-Console $logText

    }


    # Add Loggers for dynamic calling
    $loggers = @{}
    $loggers.Add("Console_Logger", ${function:Common-Write-Log-Console})


    # pester tests
    Describe "Common-Write-Log" {
	    It "Test 1. Calls all log sources when log sources are called directly - **this test passes**" {
		
		
		    # Arrange
		    $expectedLogText  = "test message" 
		    Mock Common-Write-Log-Console -Verifiable -ParameterFilter { $logText -eq  $expectedLogText}
		
		    # Act
		    Common-Write-Log-WithoutInvoke "test message"
			
		    # Assert
		    Assert-VerifiableMocks
	    }

        It "Test 2. Calls all log sources when log sources are called through Invoke-Command - **this test fails**" {
		
		
		    # Arrange
		    $expectedLogText  = "test message" 
		    Mock Common-Write-Log-Console -Verifiable -ParameterFilter { $logText -eq  $expectedLogText}
		
		    # Act
		    Common-Write-Log-WithInvoke "test message"
			
		    # Assert
		    Assert-VerifiableMocks # This statement fails as actual function "Common-Write-Log-Console" is called instead of the mocked one
	    }
    }
`


The above is the code of the problem . Test 2. always fails. I have worked around by creating a fake logger function, instead of using mock and setting some global variables to verify/assert in my test that dynamic loading and calling of intended function works. It would be nice to get the Mock working in such scenario , rather then writing those dumb fakes!

**Comment by dlwyatt** [comment]
In your case, scorpion, you don't need to use Invoke-Command at all.  You can use the call operator on script blocks, which will also solve your mocking problem by keeping everything in the same PowerShell session:

```posh
# instead of this:

Invoke-Command $logger -ArgumentList $logText,$verbosityLevel,$logType

# do this:

& $logger $logText $verbosityLevel $logType
```

Similar to the other issue where people are asking about Start-Job (and likely the same thing for workflows), as far as I know, there's really nothing that Pester can do to mock commands when you launch code in another PowerShell session, or on another computer.

**Comment by scorpionlion** [comment]
Hi Dave,
Thanks for replying. Pleased to see your response. I am working with Graham Smith who met you in Seattle last year in an event. 

The solution you suggested shows the same behavior. One thing I noticed that $logger variable contains the definition (and body) of actual function, so the Mock is kind of being ignored or overridden.  

PS: Please excuse my little knowledge of power-shell.

**Comment by scorpionlion** [comment]
[its all working now thanks to alx9r] (http://stackoverflow.com/questions/35626695/pester-mock-does-not-work-for-invoke-command-using-script-block)

**Comment by dlwyatt** [comment]
Great!  :)

**Comment by johnemau** [comment]
@goomyman, @nohwnd I found a workaround using `InvokeWithContext` on the `$ScriptBlock` parameter
```powershell
Describe "Mock Invoke-Command" {
    It "Should be mocked" {
        Mock Invoke-Command {
            Return $ScriptBlock.InvokeWithContext(@{
                "Test-Path" = { Return $True }
            }, @())
        }

        $Result = Invoke-Command -ScriptBlock { Return Test-Path "Z:\this\path\does\not\exists" }

        $Result | Should -Be $True
    }
}
```
