### ISSUE TITLE
Invoke-Pester -Script parameter does not work as described in documentation but instead expects a Path key

### ISSUE THREAD

**Issue by dfch** [pester/Pester#423]
The wiki describes the [Script](https://github.com/pester/Pester/wiki/Invoke-Pester#script) parameter with an example as follows:

``` powershell
Invoke-Pester -Script @{'Parameters' = @{'ComputerName' = $ComputerName }}
```

However when executing this (and it does not matter wether `$ComputerName` is actually set or not) we will receive the following error:

``` powershell
When passing hashtables to the -Path parameter, the Path key is mandatory, and must contain a single string.
At C:\Program Files\WindowsPowerShell\Modules\Pester\Pester.psm1:264 char:21
+                     throw 'When passing hashtables to the -Path parameter, the P ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (When passing ha... single string.:String) [], RuntimeException
    + FullyQualifiedErrorId : When passing hashtables to the -Path parameter, the Path key is mandatory, and must contain a single string.
```

Pester version tested with is `3.3.11`.

Instead we have to provide a `Path` key to the hashtable as described in *Example 3* of ``help Invoke-Pester -Examples`:

``` powershell
Invoke-Pester -Script @{'Path' = './'; 'Parameters' = @{'ComputerName' = $ComputerName }}
```

It is not clear why one would have to be forced to supply a `Path` key for test execution just to supply arguments into the tests.

Please either correct the wiki page or even better remove the `Path` key as a required input for the hashtable when using the `Script` parameter.

**Comment by vors** [comment]
For the historical context: this capability rises from https://github.com/pester/Pester/issues/271
Since it aimed to address an uncommon scenario (examples in the issue), I think it's fine to require Path parameter.

**Comment by dfch** [comment]
thanks for the quick response (still the documentation is misleading; maybe we can link from the wiki to the issue?) - Ronald

**Comment by vors** [comment]
Is not wiki open for edit to everybody? :) I think that was the case at some point, not sure how it's now.

**Comment by dfch** [comment]
sorry, did not know I could/should edit it - but it is done now. You can review [my changes](https://github.com/pester/Pester/wiki/Invoke-Pester#script) and correct them if you like. 
thanks for the hint ...

**Comment by vors** [comment]
:+1: 
@pester/pestercollaborators do you want to keep this issue open to track `Path` could be mandatory proposal?
