### ISSUE TITLE
New-Fixture: case-insensitive evaluation of sut filename

### ISSUE THREAD

**Issue by bschwede** [pester/Pester#428]
I don't no why it happend to me, may be I changed spelling of the ".Tests." filename infix manually or I didn't used the New-Fixture cmdlet to create the testfile in this case.

Due to the case-sensitive replacement the testfile included itself in a loop until the shell ran out of memory. It took me some time to understand it - silly me :-)

Perhaps the marked line could be changed in the New-Fixture code template from
```
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path).Replace(".Tests.", ".")   # <====
. "$here\$sut"
```
to
```
$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path) -replace '\.Tests\.', '.' 
```
in order to make it more robust.

**Comment by nohwnd** [comment]
Good idea. Created a PR for that.

**Comment by bschwede** [comment]
Thanks.

This passage is also quoted in the following help files: 
* **en-US\about_Mocking.help.txt:** 46:  $sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path).Replace(".Tests.", ".")
* **en-US\about_Pester.help.txt:** 37:    $sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path).Replace(".Tests.", ".")
* **en-US\about_Pester.help.txt:** 74:    $sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path).Replace(".Tests.", ".")
* **README.md:** 37:$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path).Replace(".Tests.", ".")

Maybe this could also be updated.

**Comment by nohwnd** [comment]
Definitely. You should be able to edit the wiki directly if you want to do it yourself. Do you? Otherwise I can do it :)

**Comment by bschwede** [comment]
I think I found all occurences in the wiki.
