### ISSUE TITLE
pester@3.3.12 ~ `mock` regression?

### ISSUE THREAD

**Issue by rivy** [pester/Pester#436]
There seems to be a regression in the `mock` function for pester@3.3.12.

In a previously running / passing test, `mock get-command` is now causing a call depth exception. For all known prior versions of 3.x, the test passes. And, pester@3.3.11 definitely completes without error.

The test code is:

```powershell
describe "ensure_command_in_path" {
    mock get-command { $false }
}
```

The output is:

```
Describing ensure_command_in_path
 [-] Error occurred in Describe block 5.54s
   ScriptCallDepthException: The script failed due to call depth overflow.
   RuntimeException: The script failed due to call depth overflow.
   CmdletInvocationException: The script failed due to call depth overflow.
   ParameterBindingException: Cannot retrieve the dynamic parameters for the cmdlet. The script failed due to call depth overflow.
   at <ScriptBlock><Begin>, <No file>: line 76
   at <ScriptBlock><Begin>, <No file>: line 76
   at <ScriptBlock><Begin>, <No file>: line 76
   ... <1400+ lines elided> ...
   at <ScriptBlock><Begin>, <No file>: line 76
   at <ScriptBlock><Begin>, <No file>: line 76
   at <ScriptBlock><Begin>, <No file>: line 76
   at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\Pester\3.3.12\Functions\Mock.ps1: line 333
   at Invoke-InMockScope, C:\Program Files\WindowsPowerShell\Modules\Pester\3.3.12\Functions\Mock.ps1: line 1049
   at Mock, C:\Program Files\WindowsPowerShell\Modules\Pester\3.3.12\Functions\Mock.ps1: line 337
   at <ScriptBlock>, C:\Users\Roy\Projects\scoop\repo\test\Scoop-Core.Tests.ps1: line 153
```

Please let me know if I can help track down the issue any further.

**Comment by dlwyatt** [comment]
Heh, well that didn't take long.  Pester's using Get-Command to fetch other commands that it can invoke safely, without triggering a mock.  But Get-Command itself is a bit of a weak link in the chain, apparently.  I can use some methods in $ExecutionContext instead, I think; will get a fix out shortly.

**Comment by dlwyatt** [comment]
Man... damned if I do, damned if I don't on this one.  The previous versions of Pester would have had the same problem if you mocked Get-Variable and then called it; now it's Get-Command that's a problem.  A while back, I was using $ExecutionContext in that spot, and someone reported a bug where they had a goofy function that defined a parameter named ExecutionContext (which is bad; that's an automatic variable), so I tried avoiding using that as well.

I need _one_ of these things to be reliable at that point in the mocking code.  I suspect that I'm going to have to break the other guy's tests, and just say "don't overwrite the $ExecutionContext variable", but I'll see if I can get it going some other way.

**Comment by dlwyatt** [comment]
K, sorted it out.  3.3.13 should be publishing in a few minutes, once the build server finishes tests.

**Comment by rivy** [comment]
:+1:

Thanks.
