### ISSUE TITLE
Error Line 540 of Coverage.ps1

### ISSUE THREAD

**Issue by lboening** [pester/Pester#438]
I got this error running  a code coverage report:

The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo object.
At C:\Users\Luke\Documents\WindowsPowerShell\Modules\Pester\Functions\Coverage.ps1:540 char:65
+ ... nds['Format-Table'] -AutoSize | & $SafeCommands['Out-String'] | Write ...
+                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : BadExpression

I tracked it down as described to line 540

 if ($CoverageReport.MissedCommands.Count -gt 0)
    {
        Write-Screen ''
        Write-Screen 'Missed commands:'
        $report | & $SafeCommands['Format-Table'] -AutoSize | & $SafeCommands['Out-String'] | Write-Screen
    }

**Comment by dlwyatt** [comment]
Crap.  Will fix shortly.  I seem to have left Out-String out of the SafeCommands table.  Will look into adding tests to detect this condition as well.
