### ISSUE TITLE
Should BeGreaterThan not described in Wiki

### ISSUE THREAD

**Issue by lboening** [pester/Pester#446]
I see the "Should BeGreaterThan" comparison is not described in the wiki article for "Should".

Given the wiki article (Should)[https://github.com/pester/Pester/wiki/Should],
as a person reading the article for the command  "Should", I see a an explanation of the "Should BeGreaterThan" comparison, so as to perform a comparison of an integer value.

**Comment by lboening** [comment]
I could adjust the verbiage of the wiki article, if you like.

**Comment by nohwnd** [comment]
That would be great.

**Comment by lboening** [comment]
I see Should BeLessThan is not available either.

**Comment by lboening** [comment]
What should it be called? I see this [http://chaijs.com/api/bdd/] and find a should called "above". 
1. Should BeGreaterThan compares two integer values?
2. Should BeGreaterThan compares two string values?

Not sure what is being compared.

**Comment by nohwnd** [comment]
`-gt` is used internally, so it will act the same way as that PowerShell operator. 

```
-gt
      Description: Greater-than.
      Example:

          PS C:\> 8 -gt 6
          True

          PS C:\> 7, 8, 9 -gt 8
          9
```

**Comment by lboening** [comment]
I found the about_should file and will use that language.

**Comment by lboening** [comment]
I am still thinking about this. The wiki needs more work. There are other omissions in the wiki text. 

Is there a chance the source documentation exist in some form other than "free-text" ? 

For example, if the "source" information were contained in semi-structured format, then one could pipe this into a Markdown creation script. 

Another way of course is to use the Get-Help command to read the contents from each function, then send that into a markdown formatted file, which could be merged into the main wiki.

**Comment by nohwnd** [comment]
Jakub Jareš

PowerShell & Pester
t 00420603800578<tel:00420603800578>
e me@jakubjares.com<mailto:me@jakubjares.com>
t @nohwnd

10. 3. 2016 v 3:01, Luke Boening <notifications@github.com<mailto:notifications@github.com>>:


I am still thinking about this. The wiki needs more work. There are other omissions in the wiki text.

Is there a chance the source documentation exist in some form other than "free-text" ?

For example, if the "source" information were contained in semi-structured format, then one could pipe this into a Markdown creation script.

Another way of course is to use the Get-Help command to read the contents from each function, then send that into a markdown formatted file, which could be merged into the main wiki.

**Comment by lboening** [comment]
See issue #555. I agree. The output might be the same.
Module help will equal  wiki article with same content.
