### ISSUE TITLE
ValidationMetadataException on Get-ADUser

### ISSUE THREAD

**Issue by EsOsO** [pester/Pester#448]
Hi, I can't understand why this test always fails:
``` powershell
Describe 'Test identity parameter' {
    $User = New-Object Microsoft.ActiveDirectory.Management.ADUser
    $User.GivenName = 'John'
    $User.Surname = 'Doe'
    $User.objectSid = 'S-1-2-5-1231-231123-312331'
    $User.distinguishedName = 'CN=Doe John,CN=Users,DC=contoso,DC=com'

    Mock Get-ADUser {}

    It 'should work' {
        Get-ADUser -Identity $User
    }  
}
```
with the following error:
``` terminal
Describing Test identity parameter
 [-] should work 134ms
   ValidationMetadataException: The Identity property on the argument is null or empty.
   ParameterBindingValidationException: Cannot validate argument on parameter 'Identity'. The Identity property on the argument is null or empty.
   at <ScriptBlock>, D:\Tools\dev\Identity.Tests.ps1: line 11
```

I've mocked `Get-ADUser` in other tests but always with the `-Filter` parameter. I cannot get  `-Identity` to work, any help is appreciated.

**Comment by nohwnd** [comment]
The first thing you can do is check if the user is null before `It` and inside `It` by adding ` write-host ($null -eq $user)` before and inside`It`.
```powershell
Describe 'Test identity parameter' {
    $User = New-Object Microsoft.ActiveDirectory.Management.ADUser
    $User.GivenName = 'John'
    $User.Surname = 'Doe'
    $User.objectSid = 'S-1-2-5-1231-231123-312331'
    $User.distinguishedName = 'CN=Doe John,CN=Users,DC=contoso,DC=com'

    Mock Get-ADUser {}
    write-host ($null -eq $user)
    It 'should work' {
        write-host ($null -eq $user)
        Get-ADUser -Identity $User
    }  
}

**Comment by EsOsO** [comment]
`$User` is not null:

```powershell
Describing Test identity parameter
False
False
 [-] should work 159ms
   ValidationMetadataException: The Identity property on the argument is null or empty.
   ParameterBindingValidationException: Cannot validate argument on parameter 'Identity'. The Identity property on the argument is null or empty.
   at <ScriptBlock>, D:\Tools\dev\Identity.Tests.ps1: line 12
Tests completed in 159ms
Passed: 0 Failed: 1 Skipped: 0 Pending: 0 Inconclusive: 0
```

**Comment by dlwyatt** [comment]
I'll look into it.  On a completely unrelated note, I want to beat whoever wrote the ActiveDirectory module with a stick.  Nothing but problems with that thing.  :)

**Comment by nohwnd** [comment]
Looking at `ADUser` in dotPeek I see that it inherits from `ADEntity` which defines an internal property called Identity. This property is not set when you use the default constructor. You need to use a constructor that takes `string identity` which is used to set the property. 

![image](https://cloud.githubusercontent.com/assets/5735905/12037613/c9547e8c-ae50-11e5-80f1-bac902647e04.png)

**Comment by nohwnd** [comment]
And here is the fixed code:
```powershell
Describe 'Test identity parameter' {
    $User = New-Object Microsoft.ActiveDirectory.Management.ADUser "identity" #<---
    $User.GivenName = 'John'
    $User.Surname = 'Doe'
    $User.objectSid = 'S-1-2-5-1231-231123-312331'
    $User.distinguishedName = 'CN=Doe John,CN=Users,DC=contoso,DC=com'

    Mock Get-ADUser {}
    It 'should work' {
        Get-ADUser -Identity $User
    }  
}
```

Now that we got that out of the way. Was that just an example, or you have a real test that uses that? I am asking because the test seems backwards.

**Comment by nohwnd** [comment]
@dlwyatt :+1: You are absolutely right!

**Comment by dlwyatt** [comment]
@nohwnd already nailed it, so I will now slowly back away from the AD module, and hide under my bed.

**Comment by EsOsO** [comment]
@nohwnd Work's like a charm. It was just an example to show the issue.

Thank you guys!!
