### ISSUE TITLE
Installation using `cinst pester` fails

### ISSUE THREAD

**Issue by jozefizso** [pester/Pester#449]
Recently, we run into an issue with the `cinst pester` command which just hangs after displaying the license notice. This issue appears locally or in AppVeyor environment.

This is the output from `cinst pester`. Choco just hangs and never install the pester.

```
cinst pester
Installing the following packages:
pester
By installing you accept licenses for the packages.
```
e.g. https://ci.appveyor.com/project/jozefizso/psake-contrib/build/1.0.0-build-17

Workaround is to explicitly specify the version of the pester. Current latest release is 3.3.14. Both of these commands will install the pester successfully:

```
cinst pester -version 3.3.14
cinst pester -version 3.3.13
```

**Comment by jozefizso** [comment]
Full chocolatey log: https://gist.github.com/jozefizso/e710c230bebb320ca32a#file-chocolatey-log

**Comment by dlwyatt** [comment]
I'm aware of the problem, but I'm not sure what I can do about it other than alert the Chocolatey folks, which has already been done.  It's not a problem with the Pester module itself, just something goofy with the Chocolatey client and/or feed for the Pester package.

**Comment by dlwyatt** [comment]
Ah, Rob has already identified the client bug:  https://github.com/chocolatey/chocolatey.org/issues/302

**Comment by jozefizso** [comment]
I see. I tried it to reproduce with other packages and this bug appear only when installing Pester so I though the issue is with the Pester package only. Thanks for reply.
