### ISSUE TITLE
Extra initial blank line output necessary?

### ISSUE THREAD

**Issue by rivy** [pester/Pester#450]
Are the initial blank lines of output needed (see [Pester.psm1#L261](https://github.com/pester/Pester/blob/5dc122d481750cacc2e6c8e09491fbbf61faeb2e/Pester.psm1#L261))? They are a bit odd/distracting to my eyes when reading the test output.

I reviewed the commit where the line was added (a8af2e2d3e2 [`Adding some Write-Progress output to It`](a8af2e2d3e2)), but it's not obvious to me why it was added.

If there is some need, would it be reasonable to add an option to enable/disable it?

If optional is acceptable, I'd be happy to submit a PR if you give me some guidance as to how you'd like it to function.

**Comment by iainbrighton** [comment]
From memory; it was implemented so that the progress bar didn't obscure the first test output.

Now, whether there's an option to disable it, I don't know. I'll do some digging! I'd like to disable the progress bar too!

**Comment by dlwyatt** [comment]
Disabling progress output is easy enough:

```posh
$ProgressPreference = 'SilentlyContinue'
```

The blank lines are just there.  I don't think it's worth adding extra switches just to disable that, though I suppose we could add a check for the value of `$ProgressPreference` and only output those lines if the output of `Write-Progress` is actually going to be visible.

**Comment by rivy** [comment]
That would be quite acceptable to me. I'd also like it if the extra output lines were omitted when output is redirected, although I'm at a loss at how to detect that redirection within a PowerShell script (neither `$host.UI` nor `[System.Console]` seem to be up to the task).

Unfortunately, an additional complication is that `$ProgressPreference = 'SilentlyContinue'` is only effective if you use the `Invoke-Pester` command from the shell command line. When using `pester` (which I do most of the time as I'm back and forth between CMD and PowerShell), the default "Continue" is re-enabled when the `pester.BAT` command starts the new PowerShell to invoke the command.

This is, admittedly, a cosmetic issue. But I'm reading the output text quite frequently, and it's visually jarring.

Thanks for at least thinking about it.

**Comment by rivy** [comment]
I've found a method to test for output redirection that covers execution from CMD or PowerShell. So, the current line would be changed to:

```powershell
$output_isRedirected = [Console]::IsOutputRedirected -or ( $MyInvocation.PipelinePosition -lt $MyInvocation.PipelineLength )

if (($ProgressPreference -ne 'SilentlyContinue') -and (-not $output_isRedirected)) { Write-Screen "`r`n`r`n`r`n`r`n" }
```

@dlwyatt, if you think it's a reasonable change, I can create a pull request.

**Comment by dlwyatt** [comment]
Seems reasonable, though I'm not sure why the pipeline position matters.  (Write-Host output doesn't travel down the pipeline anyway.)  It might also need a little tweaking to make it friendly to non-console hosts (ISE, possibly third-party hosts).

Anyhow, make the PR, and I'll go from there :)

**Comment by rivy** [comment]
I believe I was doing all my initial rough testing via CMD. In that case, the pipeline position *was* indicative of output redirection because PowerShell redirects everything to STDOUT + STDERR.

I neglected to consider pure execution from the PowerShell command line, so, I'll need to look at this a bit more...

**Comment by g8tguy** [comment]
Is it implemented yet? I just hate myself every time I see these empty lines! Please, consider adding some switch to disable them!

**Comment by nohwnd** [comment]
No not yet. At the moment we are focusing on getting the version 4 out the door.

**Comment by rivy** [comment]
Closing ~ fixed in the current release (v4+).
