### ISSUE TITLE
Unable to mock SqlCommand Object

### ISSUE THREAD

**Issue by ankitguptaa** [pester/Pester#451]
Function definition:

function New-SqlCommand
{
    return New-Object ("System.Data.SQLClient.SQLCommand")
}

Implementation:
$deleteCmd = New-SqlCommand
$deleteCmd.Connection = $Connection
$deleteCmd.Transaction = $Transaction

How can I mock this New-SqlCommand Object?

I was trying something on these line:
$NewSqlCommand = @"
        public class MockSqlCommand
        {
            public System.Data.SqlClient.SqlConnection Connection { get; set; }
            public System.Data.SqlClient.SqlTransaction Transaction { get; set; }
            public void ExecuteNonQuery() {}
        }
"@
        Add-Type -TypeDefinition $NewSqlCommand -ReferencedAssemblies System.Data -Language CSharp -Debug
        $NewSqlCommand = New-SqlCommand MockSqlCommand 

but this approach didn't worked for me.

**Comment by nohwnd** [comment]
You can't mock the object. But you can create similar object to it that has properties and methods named the same as the original object does.

It would be easier to give you more concrete answer if you posted the actual test case where you'd like to use it.

**Comment by ankitguptaa** [comment]
Hi Nohwnd,

Thanks for your reply. here below is my real sceenario for which I am trying to write test case.
$Connection = New-Object System.Data.SQLClient.SQLConnection
$Connection.ConnectionString = "server=dummyServer;database=DummyDatabase;trusted_connection=true;MultipleActiveResultSets=True;"
            $Connection.Open()
            $deleteCmd = New-Object System.Data.SQLClient.SQLCommand
            $deleteCmd.Connection = $Connection
            
            $Transaction= $Connection.BeginTransaction("Delete-Data");
            $deleteCmd.Transaction=$Transaction
            $deleteCmd.CommandText = "DELETE * From Employee Where EmployeeId=@EmployeeId"
            $deleteCmd.CommandType = [System.Data.CommandType]::Text
            $EmployeeId = 123
            $deleteCmd.Parameters.Add("@EmployeeId", $EmployeeId) | Out-Null 
            $deleteCmd.ExecuteNonQuery()            
            $Transaction.Commit()

here I wanted to mock the $deleteCmd in my test case, so that I can stop ExecuteNonQuery() from being executed.

**Comment by dlwyatt** [comment]
It's very difficult to achieve that kind of mocking from PowerShell / Pester.  Can _sometimes_ be done, but a much easier approach is to just wrap the .NET code in a small PowerShell function.  Then you can just mock the function, and you're done.

**Comment by ankitguptaa** [comment]
yes, I have got a bad way to do it:
function Command-ExecuteNonQuery
{
       Param(
      [Parameter(Mandatory = $true, valueFromPipeline=$false)]
      [System.Data.SQLClient.SQLCommand]$SqlCommand
      )

      return $SqlCommand.ExecuteNonQuery()
}

still thought there should be some other better way to do it :) 

thanks
