### ISSUE TITLE
Customize suite name in NUnit XML output

### ISSUE THREAD

**Issue by splatteredbits** [pester/Pester#453]
We have a repository with 6 different test suites. To speed up our builds, we run them in parallel (the longest suite takes about 16 minutes). When our build results show in our build server (CruiseControl.NET!), all the test suites show as "Pester". This requires extra sleuthing/work to figure out what test suite the tests are a part of.

Add an -OutputSuiteName parameter to Invoke-Pester that allows me to customize the name of the suite.

This is what Pester currently generates:

    <?xml version="1.0" encoding="utf-8" standalone="no"?>
    <test-results xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="nunit_schema_2.5.xsd" name="Pester" total="0" errors="0" failures="0" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2016-01-15" time="16:21:03">
      <test-suite type="Powershell" name="Pester" executed="True" result="Success" success="True" time="0" asserts="0">
        <results />
      </test-suite>
    </test-results>

This is what it should generate with -OutputSuiteName 'MSBuild':

    <?xml version="1.0" encoding="utf-8" standalone="no"?>
    <test-results xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="nunit_schema_2.5.xsd" name="Pester" total="0" errors="0" failures="0" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2016-01-15" time="16:21:03">
      <test-suite type="Powershell" name="MSBuild" executed="True" result="Success" success="True" time="0" asserts="0">
        <results />
      </test-suite>
    </test-results>

**Comment by dlwyatt** [comment]
I have plans to change this stuff around in v4 anyway.  The "Pester" suite never made much sense to me.  What I'd like to see is a suite with the name (or full path) of each Tests.ps1 file instead.  Would that cover your needs as well?

**Comment by splatteredbits** [comment]
Yes. I'd prefer just the file name, but even a full path would be fine.

To workaround this, after a test run finishes, I crack open the Pester XML file and do this:

    $pesterXml = [xml](Get-Content -Raw -Path $pesterXmlPath)
    if( $pesterXml -and ($pesterXml | Get-Member -Name 'test-results') )
    {
        $pesterXml.'test-results'.SetAttribute( 'name', $StageName )
        if(  ($pesterXml.'test-results' | Get-Member -Name 'test-suite') )
        {
            $pesterXml.'test-results'.'test-suite'.SetAttribute( 'name', $StageName )
        }
        $pesterXml.Save( $pesterXmlPath )
    }

**Comment by dlwyatt** [comment]
Will be fixed in v4

**Comment by dlwyatt** [comment]
Well, crap.  Looks like the NUnit 2.5 schema _requires_ us to have a single `test-suite` element at the just under the root `test-results` node.  So I'll just add in the customized suite name option you had originally asked for, instead.

**Comment by dlwyatt** [comment]
Just pushed this to the dev branch.  Syntax will look like this:

```posh
$option = New-PesterOption -TestSuiteName 'Whatever you want'
Invoke-Pester -PesterOption $option

# Or, shorthand:

Invoke-Pester -PesterOption @{ TestSuiteName = 'Whatever you want' }
```
