### ISSUE TITLE
Create Should BeLike assertion

### ISSUE THREAD

**Issue by splatteredbits** [pester/Pester#454]
In our [current, homegrown test framework](http://get-blade.org/), we have an assertion that checks strings using wildcards. I'd like a similar assertion in Pester:

    'FubarSnafu' | Should BeLike 'Fubar*'
    'fubarsnafu' | Should BeLikeExactly '*Snafu'

**Comment by splatteredbits** [comment]
Added in [pull request 456](https://github.com/pester/Pester/pull/456).

**Comment by megamorf** [comment]
Why not use [Should Match](https://github.com/pester/Pester/wiki/Should#match)?

**Comment by nohwnd** [comment]
@splatteredbits Thanks for your suggestions and PR, but as @megamorf said you can use the Match assertion to do the same thing. The difference is, that match uses regular expressions where "contains" matching is done by default, so you need to turn your logic upside down and specify where the string should end:
```powershell
'fubarSnafu' | should match 'arsn' #same as like *arsn*
'FubarSnafu' | Should Match '^Fubar' #same as like Fubar*
'fubarsnafu' | Should Match 'Snafu$' #same as like *Snafu
'fubarsnafu' | Should be 'bar' #same as like bar
```
And in the same way you can use `[Regex]::Escape()` to escape strings.

I understand that the syntax needs a bit of getting used to, but at this point I don't see much value in adding another string matching assertion. I still would be happy to hear your view of the problem.

**Comment by dlwyatt** [comment]
I don't see the harm in adding an operator around `-like`.  After all, PowerShell has both; why not `Should`?  :)

**Comment by splatteredbits** [comment]
I (obviously) agree with @dlwyatt. PowerShell has both regex and wildcard operators because sometimes you want a wildcard and sometimes you want a regex.
