### ISSUE TITLE
Create function for quickly creating a directory tree in the test drive

### ISSUE THREAD

**Issue by splatteredbits** [pester/Pester#455]
In our [current, homegrown test framework](http://get-blade.org/), we have a function, [New-TempDirectoryTree](https://bitbucket.org/splatteredbits/blade/src/tip/Blade/Functions/New-TempDirectoryTree.ps1?at=default&fileviewer=file-view-default), that can quickly create a directory tree using a simple DSL.

I'd like to create a New-TestDriveDirectoryTree function (is there a better name?) function that mimics this behavior.

Someone would call it like this:

```
New-TestDriveDirectoryTree @'
+ RootDir
  * ChildFile.txt
  + ChildDir
    * GrandchildFile.txt
    * GrandchildFile2.txt
* RootFile.txt
'@
```

Anything prefixed with a + creates a directory of that name. Anything prefixed with a \* creates a file of that name. Items that should be within a parent directory are indented two spaces from the position of its parent.

**Comment by nohwnd** [comment]
I like the idea but the syntax is nowhere near to what people are used to in PowerShell, and so I am afraid no one would use it, simply because it's extremely simple to just write a script that will create the structure for you, without looking up details of your syntax. We already have one such neglected function (new-fixture), and I am afraid yours would be next. 

But you can always publish it on nuGet and import it whenever you need it without tying it to Pester. 

Another thing is that it relies on spaces (as far as I can tell) which makes it awkward to work with, when you have auto-formatting tools, and the here-string terminator needs to be the first character on the line which is why I tend to avoid here-strings whenever I can.
I would suggest that you change the syntax to use hastables (and hashtables in hashtables) but the resulting syntax is quite awkward (still a more powershell-ish solution).

**Comment by dlwyatt** [comment]
> But you can always publish it on nuGet and import it whenever you need it without tying it to Pester. 

That's sort of where I'd go with this one.  Microsoft did the same thing with the [Remotely](https://github.com/powershell/remotely) command after we discussed it and decided that so few people would need that functionality (possibly only Microsoft themselves).  That way we keep the core API of the Pester module fairly neat and easy to learn.

However, I do think we should put a page up here (either in the readme, wiki, or both) linking to useful functions / modules that can be used with Pester.  That way they're still fairly discoverable, and people will know when modules to install to get the functionality they've seen in other test scripts.

**Comment by splatteredbits** [comment]
@nohwnd  I disagree that it isn't PowerShell-like: see `ConvertFrom-StringData` for an example of giant here strings being parsed and converted to objects.

You also don't need to use a here string. A regular string will work,too:

    New-TestDriveDirectoryTree "
    + RootDir
      * ChildFile.txt
      + ChildDir
        * GrandchildFile.txt
        * GrandchildFile2.txt
    * RootFile.txt"

I disagree that the alternative is extremely simple. The above would get converted to raw PowerShell as:

    New-Item -Path 'TestDrive:\RootDir' -itemType 'Directory'
    New-Item -Path 'TestDrive:\RootDir\ChildFile.txt' -itemType 'File'
    New-Item -Path 'TestDrive:\RootDir\ChildDir' -itemType 'Directory'
    New-Item -Path 'TestDrive:\RootDir\ChildDir\GrandchildFile.txt' -itemtype 'File'
    New-Item -Path 'TestDrive:\RootDir\ChildDir\GrandchildFile2.txt' -ItemType 'File'
    New-Item -Path 'TestDrive:\RootDir\RootFile.txt' -ItemType 'File'

Although it works, I like the DSL syntax better. I think it is a good DSL, because it is a format people are familiar with: when you want to communicate a directory structure to people through e-mail, on the web, etc, that's how people usually do it.

If Pester supported plug-ins, then I wouldn't mind having it in a contrib package of some kind. Each of our PowerShell modules has a dedicated version of Pester that gets checked into its repository. That way, we don't have to install Pester as a global module. Each of our PowerShell modules can use its own version, which makes it easier to upgrade and use newer versions of Pester on an as-needed basis. Are there any plans to support plug-ins in Pester?

**Comment by SigitasG** [comment]
I wrote myself 'Touch' function that can do the following:
```
'D:\' | Touch 'TestData' {
    Touch 'Results.txt'
    Touch 'Samples' {
        Touch 'SampleUsers.csv' -Content {'John;Doe'}
        Touch 'SampleComputers.txt' -Content {"localhost`r`n127.0.0.1"}
        Touch 'EmptyFolder' {}
    }
}
```
Not sure if it is should be part of pester though. I use it for projects skeletons primarily. However there were cases when I used this script to deploy some test data for pester tests. So may be not so bad idea after all?

**Comment by it-praktyk** [comment]
@splatteredbits, I assume that the final request should be: "Add support for plugins to Pester". Am I right?

If yes please create the new issue with justification e.g. usage cases, etc.

For now, I'm closing the current issue as 'Feature - refused'. 

Please reopen if you would like something more/new to your initial request. Thank you.
