### ISSUE TITLE
Output from BeforeAll/AfterAll returned to pipeline

### ISSUE THREAD

**Issue by splatteredbits** [pester/Pester#460]
If code in `BeforeAll` and/or `AfterAll` writes any objects to the pipeline (i.e. returns any objects), they are returned to the user's pipeline. For example:

    
    Describe 'Invoke-Pester' {
        BeforeAll {
            'BeforeAll'
        }

        BeforeEach {
           'BeforeEach' 
        }

        AfterAll {
            'AfterAll'
        }

        AfterEach {
            'AfterEach'
        }

        It 'should not return It block output' {
            'It'
        }
    }

returns this output when invoked:

    Describing Invoke-Pester
    BeforeAll
     [+] should not return any output 60ms
    AfterAll

I expect the output to be:

    Describing Invoke-Pester
     [+] should not return any output 60ms

This causes a problem when using the `Invoke-Pester` command's `-PassThru` switch. Instead of just getting an object representing the results, you first get any/all objects returned by all fixtures' `BeforeAll` and `AfterAll` blocks. So, in my build pipeline scripts, I can't run

    $result = Invoke-Pester -Script $pathToTest -PassThru

I have to run

    $result = Invoke-Pester -Script $pathToTest -PassThru |
                    Where-Object { $_ -is [Management.Automation.PSCustomObject] } |
                    Where-Object { $_ | Get-Member -Name 'PassedCount' } |
                    Where-Object { $_ | Get-Member -Name 'FailedCount' }

**Comment by dlwyatt** [comment]
Oops!  Will fix, thanks for the report.  :)
