### ISSUE TITLE
Mocking fails with DSC composite resource.

### ISSUE THREAD

**Issue by skyguy94** [pester/Pester#469]
This worked in 3.3.5. Fails in 3.3.14 and I think earlier (some older versions were hanging rather than just failing).

I'm trying to build a DSC module that has composite resources and I'm using pester to test those resource implementations. My module is called SCHANNEL and its structure is something like this:
```
<path>\SCHANNEL\SCHANNEL.psm1
<path>\SCHANNEL\DSCResources\Cipher\Cipher.ps1
<path>\SCHANNEL\DSCResources\CipherOrder\CipherOder.ps1
....
```
In mocking/testing the cipher resource, I'm executing the tests from the SCHANNEL folder which is the root of my git repo. My test looks like this:
```
Import-Module -Name "$PSScriptRoot\..\DSCResources\Cipher"
InModuleScope Cipher {
    Describe 'Cipher is a DSC Resource' {
...

        Context "Given a set of configured ciphers" {
            Mock _GetCipher -MockWith {
                if ($Cipher -contains 'AES 256/256') {
                    0xffffffff
                } else {
                    0x0
                }
            }

            It 'Should have Get-TargetResource return $false for a disabled cipher.' {
                (Get-TargetResource -Cipher 'NULL').Enabled |  Should Be $false
            }
...
```
This passes fine on 3.3.5. On 3.3.14, I get an error 
```
  Context Given a set of unconfigured ciphers
   [-] Should have Set-TargetResource enable a resource 55ms
     RuntimeException: Module 'Cipher' is not a Script module.  Detected modules of the following types: ''
     at Get-ScriptModule, C:\Program Files\WindowsPowerShell\Modules\Pester\3.3.14\Functions\InModuleScope.ps1: line 12

     at Validate-Command, C:\Program Files\WindowsPowerShell\Modules\Pester\3.3.14\Functions\Mock.ps1: line 758
     at <ScriptBlock>, D:\Projects\dsc-resources\SCHANNEL\Tests\Cipher.tests.ps1: line 58
   [-] Should have Set-TargetResource disable a resource 48ms
     RuntimeException: Module 'Cipher' is not a Script module.  Detected modules of the following types: ''
     at Get-ScriptModule, C:\Program Files\WindowsPowerShell\Modules\Pester\3.3.14\Functions\InModuleScope.ps1: line 12

     at Validate-Command, C:\Program Files\WindowsPowerShell\Modules\Pester\3.3.14\Functions\Mock.ps1: line 758
     at <ScriptBlock>, D:\Projects\dsc-resources\SCHANNEL\Tests\Cipher.tests.ps1: line 63
```
I'm not certain if the composite resource is involved in the issue, or if I'm even structuring how I test with it properly, so I'm open to any feeback which will resolve the issue. Right now my workaround is to force my CI to load the 3.3.5 version.

**Comment by dlwyatt** [comment]
Please run these commands, and let me know what you receive:

```posh
# set $path to your module location first, naturally

Import-Module $path\SCHANNEL\DSCResources\Cipher
Get-Module Cipher -All
```

It does look like I was assuming that Get-Module would throw an exception if the module wasn't loaded, for some reason, but that's not the case.  It should just be checking for lack of output.  However, that hasn't changed since v3.3.5.  There was a change made to fix this bug where multiple modules (of different types) were loaded: #275 ; this was released with 3.3.6.

**Comment by dlwyatt** [comment]
Incidentally, did you mean to type `.ps1` extensions in your post?  `Cipher.ps1`, etc?  If you're treating this as a module, it should be `.psm1` (and if it's a composite resource, it should be `.schema.psm1` since that's what DSC needs it to be named to find it.)

**Comment by skyguy94** [comment]
I'm not certain I'm using the correct terminology, or that I have this structured the right way. Its not a composite resource in the sense of not needing a "nodes" element for a DSC script, but a grouping of resources that make up a module rather than one resource per module.

I tried those commands and it can't find the module. I need to figure out if I'm structuring these resources properly.

**Comment by skyguy94** [comment]
@dlwyatt I took a look at your stackexchange example and sync'd my files to match that structure and everything works properly now. While I don't know why it worked in earlier versions of pester, it was definitely my problem, but I needed a sounding board to help me sort it out. Thank you for that.
