### ISSUE TITLE
Show full stack trace when test fails

### ISSUE THREAD

**Issue by splatteredbits** [pester/Pester#481]
When a test fails, show the full stack trace. I have various helper functions in my test fixtures, which sometimes get used multiple times in a test. Without a full stack trace, I don't know which usage of the helper failed.  For example

```
describe 'fixture' {
    function Assert-Something
    {
        $a | Should Be $expected
    }

    It 'should pass' {
        Assert-Something
        Do-Stuff
        Do-MoreStuff
        Do-YetEvenMoreStuff
        Assert-Something
    }
}
```

If the assertion in `Assert-Something` fails, I have no idea, without a stack trace, if it failed the first time it got called or the second time. With tests that only fail on build servers, it is even more critical in investigating why a test failed.

**Comment by nohwnd** [comment]
Running this 
```powershell 
```
