### ISSUE TITLE
Tests with Start-Job / Get-Job / Receive-Job seem to fail

### ISSUE THREAD

**Issue by avishnyakov** [pester/Pester#483]
Hey guys, we have the following tests which seem to fail and we aren't sure why:

```
describe "Can_Do_Stuff" {

    It "Checks stuff" {

                // ensure array of the Hyper-V VMs
                 $servers = @('tmp')
        Ensure-Servers $servers 15

        # should exist
        $server = Find-Server $vmName
        ($server -eq $null) | Should Be $false

        Remove-Server-Fully $vmName

        # should NOT exist
        $server = Find-Server $vmName
        ($server -eq $null) | Should Be $true
    }
}
```

Ensure-Servers if a function that uses Start-Job -filePath call:

```
function Ensure-Servers($servers, $refreshTime) {

$runner = "$here/../common/EnsureServer.Job.ps1"

    foreach($server in $servers)
    {
        Start-Job -FilePath $runner  `
                  -Name "VM provision [$($server.Name)]" `
                  -ArgumentList @($here, $server) `
                  | out-null

    }

    $jobs = Get-Job -State "Running" 
    While ($jobs)
    {
          Write-Host "Refreshing status in [$refreshTime] sec..."

          foreach($job in $jobs) {
            "`t$($job.Name) - $($job.State)"
             $res = Receive-Job $job 

             if($res -ne $null) {
                Write-Host "`t`t $res" -ForegroundColor Gray
             }
          }

          Start-Sleep $refreshTime
          $jobs = Get-Job -State "Running" 
    }

    Remove-Job *

}

```

Test gives kind random output sometimes running for 60 sec, or sometimes skipping the job if they did not exist at all finishing the run in 3-4 sec.

What might be wrong with that flow? 
Does Pester see the jobs or shroud they be handled in special way?

VS2015, the latest PS tools / Pester.

**Comment by avishnyakov** [comment]
Feels like test runner has a 60 sec timeout per test or something.
Tests seem to fail exactly 60-65 sec each time. 

Could that be a case?

**Comment by dlwyatt** [comment]
Nope, Pester doesn't have any timeouts.  If your code has an infinite loop, you'll hang the tests as well.

**Comment by dlwyatt** [comment]
What happens if you run the tests in powershell.exe or the ISE, instead of VS?  Could be something going on in the extension, perhaps.

**Comment by avishnyakov** [comment]
Hmm.. let me run test without VS, that's a nice idea.

**Comment by it-praktyk** [comment]
I assume that the issue can be closed now. Feel free to reopen if you need more assistance.
