### ISSUE TITLE
CodeCoverage requires full path

### ISSUE THREAD

**Issue by juneb** [pester/Pester#487]
If the value of Invoke-Pester -CodeCoverage is a filename without a path name, Invoke-Pester assumes the path is the local directory instead of the directory that Invoke-Pester is testing, which is far more likely.  

I was wondering why you decided to do it this way.

For example, if the command is:

PS C:\test> Invoke-Pester -Script $home\Documents\WindowsPowerShell\TestModules\TestModule -CodeCoverage TestModule.psm1

Invoke-Pester looks for TestModule.psm1 in C:\test, not in $home\Documents\WindowsPowerShell\TestModules\TestModule.

**Comment by dlwyatt** [comment]
You're giving me credit for having thought about that at all.  :)  Right now, the Coverage code just resolves relative paths the same way as any other PowerShell command.

I like the way it looks in your example, but I'm not sure how it should behave if the caller happens to pass multiple paths to the -Script parameter.

**Comment by juneb** [comment]
Oh, users! If they pass multiple paths, it uses the first one. Or, in that case, you could require a full path. My point is that the local directory is not a likely location for the file.

**Comment by fflaten** [comment]
For me, this would only add complexity to the code while being more confusing then helpful for multiple reasons:

- CodeCoverage doesn't search subfolders (unless you write ex. `*\*.ps1`), so your example would only search in the first folder. Combine that with using mulitple Script-paths as @dlwyatt mentioned and the confusion is complete.
- A lot of modules split tests and code in src and tests folders at the root, so personally I specify the folders in each parameter to keep control.
- Last, but not least.. Isn't using current working directory of the process (powershell.exe in this case) as root for relative paths the default in every other cmdlet and appliaction in general? A new user would not expect this custom behaviour.

You can easily work around it by using
```
cd $home\Documents\WindowsPowerShell\TestModules\TestModule
Invoke-Pester -Script "." -CodeCoverage "TestModule.psm1"
```

or
```
Push-Location $home\Documents\WindowsPowerShell\TestModules\TestModule
Invoke-Pester -Script "." -CodeCoverage "TestModule.psm1"
Pop-Location
```

**Comment by nohwnd** [comment]
@fflaten good point. Removing this from help wanted, I think it's better to keep as is, but will revisit in future.

**Comment by nohwnd** [comment]
Keeping as is.
