### ISSUE TITLE
Exit statement causes test to also exit

### ISSUE THREAD

**Issue by mrboring** [pester/Pester#489]
Hi

I have a script that contains a function with an `exit `statement in it. If an exception occurs I don't want the script to continue. The following is psuedo code for it:

```
function SampleFunction
{
	try {
		Do something
	}
	catch {
		CustomLoggingFunction error
		exit
	}
}

...
```

I've written a test that checks that when something goes wrong the CustomLoggingFunction is called once:

```
It -name 'SomeTestName' -test {
	
	Mock -CommandName 'CustomLoggingFunction' -MockWith { return $true }

	SampleFunction

	Assert-MockCalled -CommandName 'CustomLoggingFunction' -Exactly 1
}
```

However, (I think) the `exit `statement in the function causes the test to not complete. The results look like:

```
Describing SomeTestFixture
Tests completed in 0ms
Passed: 0 Failed: 0 Skipped: 0 Pending: 0 Inconclusive: 0
```

If I comment out the `exit` statement the results are reported correctly, but the script continues to run after a terminating exception:

```
Describing SomeTestFixture
 [+] SomeTestName 275ms
Tests completed in 275ms
Passed: 1 Failed: 0 Skipped: 0 Pending: 0 Inconclusive: 0
```

How do I deal with `exit `statments when using Pester?

**Comment by dlwyatt** [comment]
As far as I know, you don't.  Functions shouldn't be using `exit`, and if they are, they probably can't be unit tested.  This would be a better design:

```posh
function SampleFunction
{
    try {
        Do something
    }
    catch {
        CustomLoggingFunction error
        throw
    }
}
```

Unless the exception is caught by its caller, using the `throw` statement will abort the script just as well as `exit`, and it will also make the script more able to be unit tested.

Another option would be to wrap the `exit` statement in a function, and you can then `Mock` the function to do nothing (and use `Assert-MockCalled` to find out if the script would have exited.)

**Comment by mrboring** [comment]
@dlwyatt

I changed to rethrowing the exception (as per your suggestion) and updated the test to:

`{ SampleFunction } | Should Throw`

I'm now getting the desired results.

Thanks very much for hte quick response.

**Comment by dlwyatt** [comment]
No problem!  :)
