### ISSUE TITLE
How to get CodeCoverage for a whole directory tree?

### ISSUE THREAD

**Issue by agross** [pester/Pester#490]
I want to get coverage for a directory tree like this one:

```
lib
└─ my-module
   ├─ foo.ps1
   ├─ foo.Tests.ps1
   └─ bar
      ├─ baz.Tests.ps1
      └─ baz.ps1
```

```posh
Invoke-Pester -Path 'lib' -CodeCoverage '.\lib'
#=> no coverage output

Invoke-Pester -Path 'lib' -CodeCoverage '.\lib\*\*.ps1'
#=> only for foo

Invoke-Pester -Path 'lib' -CodeCoverage '.\lib\**\*.ps1'
#=> only for foo.ps1

Invoke-Pester -Path 'lib' -CodeCoverage '.\lib\my-module\*\*.ps1'
#=> only for bar\baz.ps1
```

**Comment by dlwyatt** [comment]
Pester just uses Resolve-Path, so it follows the same rules for patterns.  (No `**` support, etc.)

Personally, I just do it in two steps:

```posh
$files = Get-ChildItem .\lib -File -Recurse -Include *.ps1
Invoke-Pester -Path lib -CodeCoverage $files
```

**Comment by agross** [comment]
Thanks!

**Comment by juneb** [comment]
Be sure to include this information in the help for the CodeCoverage parameter, which says: 
"If strings are used, they must be paths (wildcards allowed)..." and add it to the examples.

From the data presented here, it looks likes "(No  **  support, etc.)" is not quite right, nor is "(wildcards allowed)".

**Comment by dlwyatt** [comment]
It does support wild cards, but only those you would normally encounter in PowerShell. The double asterisk ** has special meaning in other software.

**Comment by juneb** [comment]
Ah, got it. I would still add the example.
