### ISSUE TITLE
Doc deprecated parameters (and related issues)

### ISSUE THREAD

**Issue by juneb** [pester/Pester#492]
When you deprecate a parameter, please mention it in the help for the parameter. Let users know before they use it.

When a parameter requires a particular value type, let the user know. For example, help for OutputXml says it requires a "path," but it actually requires the path to a file with a .xml file name extension. If you give it a path, you get an access denied error.

I can't figure out the effect of the IncludeVsCodeMarker pester option. Can you please show the change in output in an example?

In Invoke-Pester Example 3:
PS C:>Invoke-Pester -Script @{ Path = './tests/Utils*'; Parameters = @{ NamedParameter = 'Passed By Name' }; Arguments = @('Passed by position') }

Please show the test that this would call and how it would use the parameters and arguments. Otherwise, it's hard to use the example as a model for any command.

Thanks!

**Comment by gerane** [comment]
I am guessing the IncludeVsCodeMarker is for the results output and Code being able to flag Fails/passes/scripts/linenumbers without needing a crazy amount regex in the runner.json. I know 3.4.0 added changes for that, but I am not sure if those are specific to that or not.

**Comment by it-praktyk** [comment]
The issue partially resolved - please look at #654.

**Comment by it-praktyk** [comment]
@juneb , @nohwnd - I think that the issue can be closed now. Could you check? Thank you.

**Comment by juneb** [comment]
Sure. I'll check.

**Comment by juneb** [comment]
Looks good. I'll close as "Resolved: Fixed".
