### ISSUE TITLE
How to run a selected Context or It block

### ISSUE THREAD

**Issue by juneb** [pester/Pester#493]
To run a Describe block, I can use the TestName or Tag parameters of Invoke-Pester. But neither of these work on a Context or It block. Is there a higher-resolution test query, like the hashtable of CodeCoverage? I thought the Script parameter would work, but that seems only to supply parameter values to a test script.

**Comment by dlwyatt** [comment]
At the moment, there's no way to do that.  It's something I've considered, and may be on the table for v4, but it's a bit tricky with how Pester works, in combination with support for PowerShell v2.

**Comment by kilasuit** [comment]
I would suggest as an hacks way about it to place any specific Context or It blocks within a separate Describe block and that would allow to run at that level.

It's additional code to write but if the usecase is there then that would be the way I would use to mitigate this issue.

**Comment by samr33** [comment]
Not sure if this was the use case for the requested feature, but I added the following to the first line of the Context function so I could set conditional breakpoints on the function I'm testing:
$global:PesterContext = $name
Made it a lot easier to bug hunt!

**Comment by it-praktyk** [comment]
Due to that in v4 Describe and Context have tags and is not possible to filter by It (a discussion e.g. #721) I propose to close the current issue.

**Comment by splatteredbits** [comment]
I've submitted a PR for this functionality: https://github.com/pester/Pester/pull/1374
