### ISSUE TITLE
-Tag does not limit tests

### ISSUE THREAD

**Issue by juneb** [pester/Pester#499]
When I use -Tag <string> in a path where some tests have the <string> Tag, it works as expected, But, when I use -Tag in a path where none of the test have the <string> Tag, it still runs the tests. 

Using Pester 3.4.0
```
PS C:\ps-test> dir *.Tests.* -Recurse | sls 'integration'
PS C:\ps-test> dir *.Tests.* -Recurse | sls '-Tag'

Pester\ProfileTests\Set-Profile.Tests.ps1:106:Describe -Tags 'foo' -Name "Enable-Profile" {
Pester\ProfileTests\Set-Profile.Tests.ps1:142:Describe "Get-Profile -Tag PROD" {

PS C:\ps-test> Invoke-Pester -Tag 'Integration'

 [-] Error occurred in test script 'C:\ps-test\Pester\HelloMocking\HelloMocking.Tests.ps1' 1.55s
   CommandNotFoundException: The term 'region' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
   at <ScriptBlock>, C:\ps-test\Pester\HelloMocking\HelloMocking.Tests.ps1: line 6
   at <ScriptBlock>, C:\Users\JuneBlender\Documents\WindowsPowerShell\Modules\Pester\3.4.0\Pester.ps
m1: line 279
   at Invoke-Pester, C:\Users\JuneBlender\Documents\WindowsPowerShell\Modules\Pester\3.4.0\Pester.ps
m1: line 292
   at <ScriptBlock>, <No file>: line 1
```

**Comment by dlwyatt** [comment]
What's in the `HelloMocking.Tests.ps1` file?

**Comment by juneb** [comment]
There's an intentionally failing test (it's one of my learning projects), but it doesn't have any tags and doesn't include the word 'Integration.'

I didn't paste the entire screen, but this command ran every test in every subdirectory of my ps-test directory, even though those tests did not have an 'Integration' tag.

**Comment by dlwyatt** [comment]
I can't reproduce that.  Do you have other calls to Invoke-Pester coming from inside your tests, by chance?  I remember talking about that on Twitter recently.

**Comment by juneb** [comment]
I have scripts in that directory that call Invoke-Pester, but there are no calls to Invoke-Pester in my *.Tests.* files.

**Comment by juneb** [comment]
I think you can close this. I can't repro outside of the test directory that has numerous test subdirectories with lots of invalid (just learning) examples.
