### ISSUE TITLE
Should BeLike isn't finding text in output.

### ISSUE THREAD

**Issue by juneb** [pester/Pester#501]
If this test passes:
    `Get-Widget  3>&1 | Select-String "This is a warning" | Should Not BeNullOrEmpty`
Shouldn't this test pass, too? It fails.
    `Get-Widget  3>&1 | Should BeLike "*This is a warning*"`

The output of the first command includes the "This is a warning" string, among other strings. Might be an array thing.

**Comment by dlwyatt** [comment]
Yep, very likely to do with it being an array.  Try this to confirm:

```posh
[string](Get-Widget 3>&1) | Should BeLike "*This is a warning*"
```

**Comment by juneb** [comment]
Yup. Confirmed.
