### ISSUE TITLE
Unable to mock Out-GridView

### ISSUE THREAD

**Issue by bushe** [pester/Pester#517]
In a attempt to mock out-gridview -Passthru or -OutputMode Single I am just returning a single object but the mock is return the entire object that is passed. Test code below:

Function/Code

``` powershell
function Test-OutGridView {
    $Service = Get-Service | Out-GridView -PassThru

    Write-Verbose "Count: $($Service.count)" -Verbose

    return $Service
}
```

Pester Test

``` powershell
Describe "Pester bug with Out-GridView" {
    Context "Fake out gridview with 1 object" {
        Mock Out-GridView { return (Get-Service WinRM)}
        It "should have a count of 1" {
            $Count = Test-OutGridView
            $Count.count | Should be 1
        }
    }
    Context "Fake out gridview with null or 0 object" {
        Mock Out-GridView { return $null}
        It "should have a count of 0 or BeNullorEmpty" {
            $Count = Test-OutGridView
            $Count.count | Should be 0
            $Count | Should BeNullorEmpty
        }
    }
}
```

And the output from running the test

``` powershell
Describing Pester bug with Out-GridView
   Context Fake out gridview with 1 object
VERBOSE: Count: 165
    [-] should have a count of 1 1.09s
      Expected: {1}
      But was:  {165}
      14:             $Count.count | Should be 1
      at <ScriptBlock>, P:\Scripts\PesterBugTest\TestOutGridView.Tests.ps1: line 14
   Context Fake out gridview with null or 0 object
VERBOSE: Count: 165
    [-] should have a count of 0 or BeNullorEmpty 620ms
      Expected: {0}
      But was:  {165}
      21:             $Count.count | Should be 0
      at <ScriptBlock>, P:\Scripts\PesterBugTest\TestOutGridView.Tests.ps1: line 21
```

As you can see in both tests the return is returning all of the 165 services running on the server.

**Comment by dlwyatt** [comment]
Actually, you're returning 165 copies of the WinRM service, if I'm reading this code correctly.  You've piped the objects from `Get-Service` to your mocked `Out-GridView`.  For each input object, it returns the value of `Get-Service WinRM`.  (The body of a mock is essentially a `process` block.)

This is an interesting problem... possibly a design flaw in the way mocking was implemented.  (You can't specify begin / process / end blocks for a mock at the moment.)

Anyhow, you can fix this temporarily by placing some logic inside your mock that makes it only return a value once:

```posh
        $hash = @{}
        Mock Out-GridView { if (-not $hash.ContainsKey['Service']) { $hash['Service'] = Get-Service WinRM; return $hash['Service'] }}
```

I use a hashtable here to get around PowerShell's dynamic scoping rules for variable assignments; you could also just do something similar with a `$script:` scoped variable, if that's your preference.

**Comment by bushe** [comment]
Thanks, this makes way more sense on why this is happening. Could -FromBlock from Invoke-Mock be exposed to the Mock command so you code specify to only run in the End block if mock something in the pipeline?

**Comment by dlwyatt** [comment]
Not sure.  Changing the mocking code is pretty tricky.  For example, parameter filters only really work well in the process block when pipeline input is involved, so figuring out which mock to call during the begin / end blocks could be difficult.  (Might be why Mock was implemented this way in the first place; dunno, that was before my time.)

**Comment by it-praktyk** [comment]
I assume that the issue can be closed now. Feel free to reopen if you need more assistance.
