### ISSUE TITLE
Invoke-Pester seems to run tests in subdirectories first 

### ISSUE THREAD

**Issue by kilasuit** [pester/Pester#522]
I am working with a similar file structure to the below in Windows 10 build 14328 (so PSv5.1)

```
\Module
\Module.psm1
\Module.tests.ps1
     \Public
          \Get
             \Get-function.ps1
             \Get-function.tests.ps1
     \Private
```

I am finding that Invoke-Pester when run in the Module Folder will run the Get-Function.tests.ps1 first causing the tests to fail as I'm requiring the module to be loaded (which I am doing in module.tests.ps1) so that I can call the function into a variable like the below

``` powershell
$function = Get-Gommand -Name Get-Function -Module Module
```

I then have my tests in that functions tests.ps1 file.

I've noticed the behaviour is similar when I run - it returns the current directory last

``` powershell
Get-ChildItem *tests.ps1 -Recurse 
```

though by doing this

```
Get-ChildItem *tests.ps1 -Recurse | Sort-Object Directory
```

I get the module.tests.ps1 showing up first

I know I could always add into the module.tests.ps1 to invoke all the subtests however this doesn't seem fitting with what I would expect the results to be from Invoke-Pester

I will boot up a v3 & v4 machine and see if the issue is the same on those as well

**Comment by dlwyatt** [comment]
That's just how `Get-ChildItem -Recurse` behaves (which is exactly what Pester uses to find the tests files, if you give it a directory.)

**Comment by it-praktyk** [comment]
It's not a bug it's a feature! ;-)
