### ISSUE TITLE
Mock: Not working when attempting to Mock Get-View (from PowerCLI)

### ISSUE THREAD

**Issue by tparker00** [pester/Pester#528]
This is similar to #63. When mocking Get-View i receive the following error:
`PSInvalidCastException: Cannot convert the "VirtualMachine" value of type "System.String" to type "System.Type".
   ArgumentTransformationMetadataException: Cannot convert the "VirtualMachine" value of type "System.String" to type "System.Type".
   ParameterBindingArgumentTransformationException: Cannot process argument transformation on parameter 'ViewType'. Cannot convert the "VirtualMachine" value of type "System.String" to type "System.Type".`

I'm using powerCLI 6.0. Below is the base test and script to reproduce the issue.

```
function test {
    param (
        $myVM
    )
    Get-View -viewtype VirtualMachine -Property Name -Filter @{"name" = $myVM}
}
```

```
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path) -replace '\.Tests\.', '.'
. "$here\$sut"
Describe "test" {
    Mock Get-View {
        Return @{name="Test";config="Test"}
    }
    It "does something useful" {
        test MyVM
    }
}
```

**Comment by dlwyatt** [comment]
Looks like this might be a bug in PowerShell's ProxyCommand class.  The PowerCLI commands have some custom attributes for validation / transformation, and while they're present in the command's metadata, they're missing when the ProxyCommand class generates code:

```posh
$cmd = Get-Command Get-View
$metadata = [System.Management.Automation.CommandMetadata]$cmd

# Showing the custom attributes:

$metadata.Parameters['ViewType'].Attributes[1].GetType().FullName
$metadata.Parameters['ViewType'].Attributes[2].GetType().FullName

# Here's what ProxyCommand spits out for that parameter, notice the missing attributes:

[System.Management.Automation.ProxyCommand]::GetParamBlock($metadata)

<#
    [Parameter(ParameterSetName='GetEntity', Mandatory=$true)]
    [ValidateNotNullOrEmpty()]
    [type]
    ${ViewType}
#>

Since Pester uses the ProxyCommand class to generate mock code, it's missing the attributes that allow you to pass in a value like "VirtualMachine" and have it translate automatically to `[VMware.Vim.VirtualMachine]`
```

**Comment by tparker00** [comment]
Ok...well that stinks. I did manage to come up with a workaround for this instance. Figured I'd put it here in case anyone else comes across something similar. It's a bit of a hack but "works" good enough.

```
function Detect-Pester {
    return $false
}
function test {
    param (
        $myVM
    )
    if ($(Detect-Pester)) {
        Get-View -id $myVm
    }
    else {
        Get-View -viewtype [Vmware.Vim.VirtualMachine] -Property Name -Filter @{"name" = $myVM}
    }
}
```

```
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path) -replace '\.Tests\.', '.'
. "$here\$sut"

Describe "test" {
    Mock Get-View {
        Return @{name="Test";config="Test"}
    }
    Mock Detect-Pester {
        Return $true
    }
    It "does something useful" {
        test MyVM
    }
}
```

If there's a better workaround I'm all ears. Since this looks like it's a Powershell issue I'm not sure if there's anything else to be done here.

**Comment by dlwyatt** [comment]
I'll keep thinking about this. No promises, but maybe I can find a way to get it working at some point. :)

In the short term, I'd probably just wrap the calls to Get-View in your own function. Then you can mock that function instead of Get-View.

**Comment by it-praktyk** [comment]
I think that was explained under #803 recently.

I propose to close the current issue also. @tparker00, what do you think about?
