### ISSUE TITLE
Split-Path Fails in Scripts being tested

### ISSUE THREAD

**Issue by GitAMBS** [pester/Pester#531]

**Comment by dlwyatt** [comment]
Can you provide a repro?  This is a pretty vague report.

**Comment by GitAMBS** [comment]
it is sry bout that. 

was working on the repro and found that it was actually in the tests the error occured. 
Using Split-Path -Path $MyInvocation.MyCommand.Definition to load ressources from the testfile threw Split-Path : Illegal characters in path
Cause: C:\ do not have a parent. Invoke-FacePalm -force :facepunch: 

working as supposed to now, when loading resource(s) via the functions/module that I want to test.
