### ISSUE TITLE
Consideration for additional OutputFormats?

### ISSUE THREAD

**Issue by RamblingCookieMonster** [pester/Pester#533]
Hi!

In recent years, we've seen a wealth of *audit technology XYZ with PowerShell* scripts.  In the past few months or so, we've seen some of these start to leverage Pester as a means to assert things in scenarios ranging from monitoring, to infrastructure testing, to service validation.

Given that many of these scenarios would greatly benefit from further context around tests, it might be worth considering an extended output format, beyond traditional output offered by Pester.

If that makes sense, take a look at [Chef Inspec](https://www.chef.io/inspec/), which offers [something along these lines](https://github.com/chef/inspec/pull/671).  I haven't had time to dive in too deeply, but I would imagine a free form hash table of sorts (similar to PrivateData in a module manifest) might be helpful, to avoid being locked into a particular schema.

Apologies if some of my phrasing is off, this isn't my area of expertise : )

Cheers!

**Comment by dlwyatt** [comment]
I suspect that this sort of thing would belong in a module that happens to be a wrapper around Pester, similar to the operation validation framework that Microsoft did:  https://github.com/PowerShell/Operation-Validation-Framework

In general, I'd be fine with adding other output formats.  In this case it's the API bloat that I don't think should be added to Pester itself (adding commands or parameters for title / description / impact / etc.)

**Comment by RamblingCookieMonster** [comment]
Hadn't considered the bloat, good call, thanks for the note!
