### ISSUE TITLE
Mock a function inside of a remote scriptblock

### ISSUE THREAD

**Issue by adbertram** [pester/Pester#535]
I have a function that's called inside of another function I'd like to test.  This function contains an Invoke-Command reference with various function calls inside of the remote scriptblock. Is it possible to mock the function calls inside of the remote scriptblock?  Here's an example.
```powershell
function MyFunction {
     Invoke-Command -ComputerName X -ScriptBlock { Mock-ThisPlease }
}

describe MyFunction {
    it 'mocks something' {
        mock 'Mock-ThisPlease' {

        }
    }
}
```

**Comment by nohwnd** [comment]
Where do you defining the `Mock-ThisPlease` function? If you define it outside of the script block it won't be available on the remote computer. If you define it inside the script block, mock has no way of replacing it. The only way would be to pass the function definition as a parameter, but even for that the mocking would have to be self-contained. (or parse the code and replace the definitions).

**Comment by dlwyatt** [comment]
Either way, Pester doesn't exist in the remote session, and you can't use its Mock commands for anything inside it.  You'd have to mock Invoke-Command itself in your local session.

**Comment by adbertram** [comment]
That's what I was afraid of. Just checking. :/
