### ISSUE TITLE
running pester with  PowerShell Tools for Visual Studio

### ISSUE THREAD

**Issue by rs38** [pester/Pester#538]
Is there any support for it or examples (Powershell Soluton) to get it running?
Can you provide some links where I could get this question asked any better?
Is integration into VSCode any different?

thx!!

**Comment by andydtoma** [comment]
Take a look on that: https://writeabout.net/2016/01/01/visual-studio-github-powershell-pester/

**Comment by it-praktyk** [comment]
I assume that the issue can be closed now. Feel free to reopen if you need more assistance.
