### ISSUE TITLE
Help to Mock the following command Get-Disk

### ISSUE THREAD

**Issue by sathish1000** [pester/Pester#539]
Hi,

   I have function x with the following command in it..

function disk{
	$Test=get-disk | Where-Object BusType -Ne USB 
}

 How to mock this command "get-disk | Where-Object BusType -Ne USB"

**Comment by nohwnd** [comment]
What are you trying to test?

**Comment by sathish1000** [comment]
Hi,

       I am trying to test commands that are piped together. 
       What I am trying to test is whether 'get-disk' is getting called or not [through a mock] but I don't want to call the actual 'get-disk' function.

**Comment by nohwnd** [comment]
You just specify the mock in your current scope, either Context, Describe or It.
Mock Get-Disk {}
