### ISSUE TITLE
Question: How are you using your DevelopmentV4 and master branches?

### ISSUE THREAD

**Issue by juneb** [pester/Pester#542]
When I submitted my help rewrite, I submitted it to the master branch. Should I have submitted it to DevelopmentV4, or will these be merged? I'm working on a parameter description for you and I want to make sure it's in the branch that gets released with your 4.0.

Just a suggestions: You might want to put collaboration instructions on the ReadMe or wiki. Thanks!

**Comment by dlwyatt** [comment]
The best answer is probably, we're doing it completely wrong. :P  But stuff in master will get merged again soon.

**Comment by juneb** [comment]
There's Developmentv4, DevelopmentV4, and master. To which branch should I send my PR?

**Comment by dlwyatt** [comment]
Master is fine

**Comment by juneb** [comment]
Thanks. So, when I test my examples against current code, I should test against the code in master?

**Comment by dlwyatt** [comment]
Yep, unless you're doing something specifically for v4 (Gherkin, etc)
