### ISSUE TITLE
To mock a executable that is not present on the system

### ISSUE THREAD

**Issue by sathish1000** [pester/Pester#544]
I am trying to Mock a executable that is not present in system. Say try.exe
[I tried mocking a exe that was already present on the system. I was able to Mock it.]

Can you help me with how to Mock it?

**Comment by dlwyatt** [comment]
Personally, I never directly mock external commands.  The functionality is a bit inconsistent.  I wrap the calls to the external command in a PowerShell function, and then mock that function instead.  This would also solve your problem of being able to run the tests on a system that didn't have the command available.

**Comment by it-praktyk** [comment]
I assume that the issue can be closed now. Feel free to reopen if you need more assistance.
