### ISSUE TITLE
Mocking does not follow expected order

### ISSUE THREAD

**Issue by adbertram** [pester/Pester#547]
I've got a module with two functions that looks like this:

MyModule.psm1
   |_ Get-Function1
   |_ Get-Function2

Get-Function2 has a parameter on it called Param1 and Get-Function1 has a param called Whatever. Get-Function1 calls Get-Function2.

I also have a Pester test file called MyModule.Unit.Tests.ps1 inside of the same folder as MyModule.psm1.

Inside of the tests file looks like this:

```
#region import modules
$ThisModule = "$($MyInvocation.MyCommand.Path -replace '\.Unit\.Tests\.ps1$', '').psm1"
$ThisModuleName = (($ThisModule | Split-Path -Leaf) -replace '\.psm1')
$RequiredModules = $ThisModule
Remove-Module -Name $ThisModuleName -Force -ErrorAction Ignore
Import-Module -Name $RequiredModules -Force -ErrorAction Stop
#endregion

InModuleScope MyModule {

    describe Get-Function1 {

        it 'does something' {
            mock Get-Function2 {
                return $null
            }
        }

        it 'does something else' {
            mock Get-Function2 {
                return $null
            } -ParameterFilter { $Param1 -eq 'something' }
            
            ## This should match the mock with the parameter filter but does not
            $null = Get-Function1 -Whatever 'test'

            Assert-MockCalled 'Get-Function2'
        }
    }
}
```

When I run the test as-is, 'does something new' succeeds when it shouldn't. That's because $Param1 will not equal 'something'. However, when I comment out the mock inside of 'does something', it then fails as expected.

I would expect the mock with the parameter filter to apply since it's in the same It block but it appears like the mock inside of 'does something' that has no parameter filter is overriding the other. 

Is this intended behavior? If so, how can I use each mock without putting them inside of their own describe block? It would be nice if mocks were scoped to It blocks.

**Comment by adbertram** [comment]
I just moved the 'does something' block below the 'does something else' It block and now it's working as expected. It appears that the first mock was superseding the second one.

**Comment by nohwnd** [comment]
Tht's weird, I will try to have a look tmorrow.


Jakub Jareš

PowerShell & Pester
t 00420603800578<tel:00420603800578>
e me@jakubjares.com<mailto:me@jakubjares.com>
t @nohwnd

31. 5. 2016 v 21:54, Adam Bertram <notifications@github.com<mailto:notifications@github.com>>:


I just moved the 'does something' block below the 'does something else' It block and now it's working as expected. It appears that the first mock was superseding the second one.

**Comment by dlwyatt** [comment]
Right now, mocks are scoped to Describe and Context blocks only.  We did briefly scope them to It blocks during the v3 betas, but got some push back and reverted the change.  Don't really remember why.

Technically, both mocks are still active in the second block.  The one without the parameter filter gets executed (unless you actually match a parameter filter.)

For what you're doing, I'd rather use the `-ParameterFilter` on `Assert-MockCalled`, rather than `Mock`:

```posh
#region import modules
$ThisModule = "$($MyInvocation.MyCommand.Path -replace '\.Unit\.Tests\.ps1$', '').psm1"
$ThisModuleName = (($ThisModule | Split-Path -Leaf) -replace '\.psm1')
$RequiredModules = $ThisModule
Remove-Module -Name $ThisModuleName -Force -ErrorAction Ignore
Import-Module -Name $RequiredModules -Force -ErrorAction Stop
#endregion

InModuleScope MyModule {

    describe Get-Function1 {

        mock Get-Function2

        it 'does something' {
            
        }

        it 'does something else' {
            $null = Get-Function1 -Whatever 'test'

            Assert-MockCalled 'Get-Function2' -ParameterFilter { $Param1 -eq 'something' } -Scope It
        }
    }
}

```

I also added `-Scope It` to the call to `Assert-MockCalled`.  (The scope defaults to the parent scope of the It block, again to avoid a breaking change from how mocking was originally written.)

Perhaps v4 is a good time to change this behavior to something more intuitive.  We've got enough breaking changes coming anyway that this one shouldn't matter much.
