### ISSUE TITLE
Parameters do not show up when passing to tests

### ISSUE THREAD

**Issue by adbertram** [pester/Pester#549]
I'm using 3.4.0 and have a test that I'd like to pass a couple parameters to. My test looks like this:

describe {
    it 'does somthing' {
        $EnvironmentId ## This does not exist
    }
}

I'm passing $EnvironmentId to the test file like this:

Invoke-Pester -Script { 'Path' = 'C:\Tests.ps1'; Parameters = @{'EnvironmentId = 'B'}}

It looks like $EnvironmentId exists but it's null. Am I doing this right?

**Comment by dlwyatt** [comment]
Does your Tests.ps1 script have a param block?

**Comment by adbertram** [comment]
No, it does not.

**Comment by adbertram** [comment]
That'd do it. :) Thanks!

**Comment by it-praktyk** [comment]
I assume that the issue can be closed now. Feel free to reopen if you need more assistance.
