### ISSUE TITLE
Multiple Script modules named 'XXXX' are currently loaded

### ISSUE THREAD

**Issue by adbertram** [pester/Pester#551]
I'm using 3.4.0 with PS v5.0.10586.117. The first part of my test file looks like this:

```
#region import modules
$ThisModule = "$($MyInvocation.MyCommand.Path -replace '\.Integration\.Tests\.ps1$', '').psm1"
$ThisModuleName = (($ThisModule | Split-Path -Leaf) -replace '\.psm1')
$RequiredModules = $ThisModule, 'GHI.Library.ComputerDefinition'
Remove-Module -Name $ThisModuleName -Force -ErrorAction Ignore
Import-Module -Name $RequiredModules -Force -ErrorAction Stop
#endregion
```

You can see that I try to remove any loaded modules with Remove-Module but it doesn't seem to help.

![image](https://cloud.githubusercontent.com/assets/4306938/15792225/78c38cac-29a1-11e6-8289-98cdd819665c.png)

**Comment by dlwyatt** [comment]
What happens if you run Get-Module with the -All switch?

**Comment by adbertram** [comment]
Ah, that found them. Thanks!
