### ISSUE TITLE
V4:  Sort out console colors

### ISSUE THREAD

**Issue by dlwyatt** [pester/Pester#553]
Big merge conflict here, still not resolved.  After we branched off to start working on v4, @nohwnd added color profiles to v3 which change the console output based on your PowerShell host (powershell.exe, ISE, and PowerGUI if I remember right).

In the Gherkin code, @Jaykul added code to adjust output text and colors based on whether we're running Pester or Gherkin files.

Right now, the Gherkin code is what's active here, and a lot of code from V3 is commented out at the end of Functions\Output.ps1 .

**Comment by Jaykul** [comment]
Do you need help figuring out what's what?

**Comment by dlwyatt** [comment]
I think it's mostly about deciding what to keep between the v3 and Gherkin palettes, at this point

**Comment by dlwyatt** [comment]
Would rather have the two be consistent, though, particularly if we're going to merge Invoke-Gherkin and Invoke-Pester into a single command

**Comment by it-praktyk** [comment]
Is it resolved?

**Comment by nohwnd** [comment]
Yes, my approach was removed, and instead Jaykul's approach was used. Some pieces of making the error output better were removed, but that is fixed as well.
