### ISSUE TITLE
Nice to have:  Documentation updates / automation

### ISSUE THREAD

**Issue by dlwyatt** [pester/Pester#555]
Right now the comment-based help and Wiki are managed separately, and we wind up with documentation missing in one place or the other all the time.

What I'd like to see is our documention managed in markdown files in the Pester repo.  Those can be used directly on the wiki, and many of them can be converted to MAML by the PlatyPS module for distribution with the Pester module (replacing the comment-based help).  Our release steps on TeamCity can be responsible for updating the wiki when we release new versions.

**Comment by alexandear** [comment]
I can resolve this issue.

**Comment by pcgeek86** [comment]
Can we also address that there's no built-in help for `Should`?

![image](https://cloud.githubusercontent.com/assets/466713/19123911/a42603b6-8ae5-11e6-8c9c-5bbb631aadaf.png)

**Comment by dlwyatt** [comment]
There's `about_Should`.  The command itself doesn't really use PowerShell's parameter system, so there's not really a good way to jam the help there.

**Comment by pcgeek86** [comment]
@dlwyatt it doesn't need to use the parameter system -- a simple pointer in `.DESCRIPTION` and `.SYNOPSIS` over to `about_Should` should be sufficient.

**Comment by nohwnd** [comment]
@pcgeek86 Like that #618?

**Comment by pcgeek86** [comment]
@nohwnd Thanks!

**Comment by it-praktyk** [comment]
I just prepared the pull request #686 with basic help for Should.

**Comment by it-praktyk** [comment]
I propose to continue discussion in #720.
