### ISSUE TITLE
Describe -Tag <object>

### ISSUE THREAD

**Issue by juneb** [pester/Pester#556]
Can we please make the type of the Tag parameter of Describe an explicit string array? 

The Tag parameter of Describe takes an array of strings, just like the Tag parameter of Invoke-Pester, but because the Tag parameter of Describe doesn't have a defined type, it shows up in the syntax as object. This is especially confusing in Pester where <object> parameters like Script take two different objects, like a string and a hash table. 

I can make this change and submit a PR, but I wanted to check with you to make sure it doesn't have some downstream effect, or be set as object for a reason.

**Comment by dlwyatt** [comment]
Oops!  PR please! :)

**Comment by juneb** [comment]
Fixed by #558
