### ISSUE TITLE
Invoke-Pester -Tag, -ExcludeTag fail when tag includes spaces

### ISSUE THREAD

**Issue by juneb** [pester/Pester#557]
When the value of the Tags parameter of Describe includes spaces, e.g. 'unit test', the Tag and ExcludeTag parameters of Invoke-Pester do not include or exclude the test properly, because Invoke-Pester splits tags on whitespace (/s), not on strings.

We should either fix the split or explain in the help that tags can't include spaces.

**Comment by dlwyatt** [comment]
Hmm... I suspect that `-split` is a leftover from when the Tag parameter only took a single string.  Didn't notice that when we changed it to `[string[]]`.  Can't think of any reason we'd do a split when we already accept an array.

**Comment by nohwnd** [comment]
This was fixed by #1047
