### ISSUE TITLE
Interaction of TestName and Tag

### ISSUE THREAD

**Issue by juneb** [pester/Pester#559]
When you use TestName and Tag in the same Invoke-Pester command, it ANDs the requirements and runs only tests that have the specified TestName and the specified tag. That's fine, but I wanted to make sure it's the intended behavior. Users might expect OR behavior, because multiple Tag values are OR'd.

**Comment by nohwnd** [comment]
Won't fix this for v4, but in v5 the filters have OR relationship, with excludes taking the precedence. :) This should be good enough for most cases, for others I might add a scriptblock predicate where the caller can do whatever they way.
