### ISSUE TITLE
Include code coverage in output XML

### ISSUE THREAD

**Issue by juneb** [pester/Pester#565]
Similar to #212 , but Joel focused on specific output format. I'm wondering why the code coverage results aren't included in the XML output.

**Comment by dlwyatt** [comment]
The XML output is using NUnit's schema.  As far as I know, NUnit has no concept of code coverage, nor a place to put it in the XML file.

**Comment by juneb** [comment]
Understand. Best to stick with industry standard. I'll close the issue. Thanks for the quick reply.
