### ISSUE TITLE
Mock Fails when mocked function is dot sourced in tested script

### ISSUE THREAD

**Issue by jaredgeinosky** [pester/Pester#567]
I'm trying to test a script that has a function dot sourced within it. When I try to mock that function, the regular version is called instead of the mocked one. Here is an example that shows the problem:
I'm trying to test a script that has a function dot sourced within it. When I try to mock that function, the regular version is called instead of the mocked one. Here is an example that shows the problem:
Invoke-Bar.ps1
function Invoke-Bar {
    . .\Invoke-Foo.ps1
    Invoke-Foo
}

Invoke-Foo.ps1
`Function Invoke-Foo{
    'Cantelope'
}

Invoke-Bar.tests.ps1
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path) -replace '\.Tests\.', '.'
. "$here\$sut"

Describe "Invoke-Bar" {
    It "Returns Cantelope" {
        Invoke-Bar | should be 'Cantelope'
    }
    context "When the function is mocked"{
        It "Returns Banana"{
            Mock Invoke-Foo { 'Banana' }
            Invoke-Bar | Should be 'Banana'
        }
    }
}

**Comment by dlwyatt** [comment]
This is a problem:

```posh
function Invoke-Bar {
    . .\Invoke-Foo.ps1
    Invoke-Foo
}
```

Every time you run `Invoke-Bar`, you're re-importing the `Invoke-Foo` function definition.  This overwrites Pester's mock of the function.  A cleaner approach would be to dot-source Invoke-Foo.ps1 once when you run Invoke-Bar.ps1 (whether it's dot-sourced or not is irrelevant), rather than inside the call to Invoke-Bar.

**Comment by dlwyatt** [comment]
For example, have Invoke-Bar.ps1 look like this:

```posh
. .\Invoke-Foo.ps1

function Invoke-Bar {
    Invoke-Foo
}
```

Moving that line of code makes all the difference.
