### ISSUE TITLE
Tweak Auto-Generated Fixtures

### ISSUE THREAD

**Issue by tribou** [pester/Pester#57]
It would be helpful if the auto-generated fixtures produces something more like:

``` powershell
It "does something useful" {
  $expectedValue = $true
  $returnedValue = $false
  $returnedValue | Should Be $expectedValue
}
```

This is similar to Matt Wrock's tutorial here: http://www.mattwrock.com/post/2012/11/15/Unit-Testing-Powershell-and-Hello-Pester.aspx

**Comment by it-praktyk** [comment]
The related issue #783

**Comment by it-praktyk** [comment]
Is it currently the oldest one issue still opened for Pester. Can we do something with that? In my opinion, we can close it now. Any concerns?

**Comment by nohwnd** [comment]
@it-praktyk a while ago I tweeted a [poll about this](https://twitter.com/PSPester/status/845024534436741121) and `New-Fixture` is not that popular only 6 % of 72 people use it, and 63 % marked it as never used it. So yeah let's close this, because updating it would be contraproductive.
