### ISSUE TITLE
Mock Wait-Debugger doesn't work

### ISSUE THREAD

**Issue by Remco-74** [pester/Pester#570]
Suppose i have the following CmdLet:

    function Test-Debugger {
        [CmdletBinding()]
        param ( )

        Begin {
            if ($MyInvocation.BoundParameters.ContainsKey('Debug')) {
                Wait-Debugger
            }
        }

        Process {
            # ...
        }
    }

and the following test:

    Describe 'Test-Debugger' {

        It 'implements -Debug' {
            Mock Wait-Debugger
            Test-Debugger -Debug
            Assert-MockCalled Wait-Debugger
        }
    }

Then Pester does not mock Wait-Debugger, but the debugger is activated.

**Comment by nohwnd** [comment]
@Remco-74 Your code works for me on PowerShell v5. What version of powershel and Pester are you using?

**Comment by Remco-74** [comment]
@nohwnd I tried reproducing this this on my work machine (Win2008 R2, WMF 5.0, Pester 3.4.0), and there it works as expected. I will try to re-test tonight on my private machine (Win10, PowerShell 5, Pester 3.4.0) where the defect originally occurred) to validate.

**Comment by Remco-74** [comment]
The scenario is a bit more complex, the code to be tested resides in a module. Given 'GetSome.psm1'

```
function Get-Something {
    [OutputType([object])]
    [CmdletBinding(ConfirmImpact='None')]
    param (
        # The Name of the thing to Get.
        [Parameter(Mandatory, ValueFromPipeline)]
        [string] $Name
    )

    Begin {
        if ($MyInvocation.BoundParameters.ContainsKey('Debug')) {
            Wait-Debugger
        }
    }

    Process {
        # get things ..
    }
}

Export-ModuleMember -Function Get-Something
```

And 'GetSome.Tests.ps1':

```
$here = Split-Path -Parent $MyInvocation.MyCommand.Path

Describe 'Get-Something' {

    BeforeAll {
        Import-Module "$here\GetSome.psm1" -Force
    }
    AfterAll {
        # Remove-Module
    }
    
    It 'implements -Debug correctly' {
        # arrange
        Mock Wait-Debugger

        # act
        Get-Something -Name 'x' -Debug

        # assert
        Assert-MockCalled Wait-Debugger
    }
}    
```

And Calling 

PS> Invoke-Pester -Script GetSome.Tests.ps1

Will result in the debugger being started.

**Comment by Remco-74** [comment]
Alright, my bad. 

I found out i need to use -Module for the Mock 

```
    It 'implements -Debug correctly' {
        # arrange
        Mock -Module 'GetSome' -CommandName 'Wait-Debugger' -MockWith { }

        # act
        Get-Something -Name 'x' -Debug

        # assert
        Assert-MockCalled -Module 'GetSome' -CommandName 'Wait-Debugger' -Times 1
    }
```

Never mind, and thanks for looking into this.
