### ISSUE TITLE
Request for Sanity Check:  New NUnit XML output

### ISSUE THREAD

**Issue by dlwyatt** [pester/Pester#571]
I'm working on #554 , and have just made a bunch of changes to TestResults.ps1.  New XML files should have test-suite elements for both the test scripts themselves, and for any Contexts (or nested Describes, whatever).

A sample export of Pester's own tests on my machine is here:  https://gist.github.com/dlwyatt/2e53a821271b36833f54eaa57b920e33

Anyone who uses this format a lot, please have a look and let me know if anything seems off.  I'm not sure if I'm handling the counts for each test-suite properly; is it supposed to only reflect test-case elements that are direct children of the suite, or total up including child test-suite elements as well?  (Right now it's doing the latter.)

**Comment by dlwyatt** [comment]
Also:  Is there any reason to continue prepending test-case names with the full path of test-suites that led to them?  That was a request in v3, but may have just been a stop-gap until we had the full hierarchy, don't recall for sure.  (Will dig through the old issues / PRs to try to find it.)

**Comment by dlwyatt** [comment]
Looks like that was part of the original request for parameterized test cases, which is when we introduced the new NUnit XML format.  Based on what I see here:  https://github.com/x97mdr/pickles/blob/master/src/Pickles/Pickles.Test/results-example-nunit.xml

- Each script file should have a test-results node, instead of a test-suite node as we currently have.  (The "Pester" test-results node should just go away.)
- Looks like it's correct to have each test-suite have the total time (including all child test-suites).
- test-case nodes should have the dotted name format, but not test-suite nodes.  (eg:  test-suite1.test-suite2.test-suite3.test-caseName).

Will update the code with these changes, and then update the gist.

**Comment by nohwnd** [comment]
I also remember using [this viewer](https://sourceforge.net/projects/nunittrviewer/) when doing some changes to the nUnit output to make sure it's still valid. There is schema validation now if I am not mistaken, but it still might be easier way to review the structure.

**Comment by vors** [comment]
For some reason AppVeyor doesn't like new format.
https://ci.appveyor.com/project/vors/test-new-pester-nunit-with-appveyor

The test tab is empty.

Could be a problem with my setup.

**Comment by TravisEz13** [comment]
@vors I found this workaround
https://github.com/appveyor/ci/issues/1271

**Comment by nohwnd** [comment]
Been using the current NUnitXml output with AppVeyor without any problems, I think this can be safely closed.
