### ISSUE TITLE
Change a mocks return value based on number of times called

### ISSUE THREAD

**Issue by nhudacin** [pester/Pester#574]
Wondering how other people have dealt with this...

I would like to be able to change the return value on the mocked function during the first (or second, etc) call to the mock. Are there any properties available to me to help determine, if even just rudimentary, if the mock has been executed already inside the mocked block? I.E. Could I create the mocked function to up a counter each time it is called and return a different value based on that counter? 

Here's one example of what I'm trying to do... 

``` posh
function Get-ProjProps {
    param(
        [String]$ProjectCode
    )
    return @{
        ID = 1
        ProjectCode = $ProjectCode
        Connection = 'ConnectionString'
    }
}

function foo {

    # calling an internal function to get some properties
    $ProjectProps = Get-ProjProps 'ProjectCode'

    # in the next block of code, I'll move the project, thus
    # chaning the connection string
    $TargetInstance = 'Bar'
    Write-Output 'faking some actual work'

    # towards the end, I validate the work updated everything
    # correctly and consistently by getting the projProps again
    $newProjectProps = Get-ProjProps 'ProjectCode'

    if ($newProjectProps.Connection -ne $TargetInstance) {
        Throw "Some inconsistencies were detected.. rolling back"
    }
}

```

Notice the validation at the end.. I'm calling the same procedure `Get-ProjProps` but I expect a different return value so that my procedure doesn't throw. 

Maybe there's an internal indicator available to me to help with my logic paths inside my mock.. Ideally something like this would work... 

``` posh
describe 'foo' {
    mock Get-ProjProps {        

        if (-not $executionNumber) { # maybe $ExecutionNumber will persist during the test?
            # this would be ok for the first call to Get-ProjProps
            return @{
                ID = 1
                ProjectCode = $ProjectCode
                Connection = 'ConnectionString'
            }

            # set the $executionNumber to force the different path on the next call
            $executionNumber = 1
        }
        else {
            # all subsequent calls return this value
            return @{
                ID = 1
                ProjectCode = $ProjectCode
                Connection = 'Bar'
            }
        }
    }

    it 'does not throw' {
        {foo} | Should Not Throw
    }
}
```

**Comment by nohwnd** [comment]
**This is not the way to go**, but technically you can do this:
```powershell 
describe "d" {
    it "i" {
        $script:mockCounter = 0; 
        function Get-Something  {}
        Mock Get-Something { 
            if ($script:mockCounter -eq 0) { "a" } else {   "b"  }
            $script:mockCounter++
        }

        Write-Host (Get-Something)
        Write-Host (Get-Something)
    }
}
```
Such a test, would test your mock and not your code. Because all the storing/updating of the object the first mock produced is thrown away and another unrelated object is returned from the mock on second call. 

So if you decide to go the stateful mock way, then rather than counting mock calls use the variable as a store and mock both Get  and Set.

Now  let me say that **stateful mocks are bad**. You are supporting a complex implementation with a complex mock, and when the implementation gets even more complex your mocks will have to get more complex as well. Which is the opposite of what you are trying to achieve: Specifying a lot of *simple* examples to define complex behavior.

 A better way to approach this is to move the actual functionality to your cmdlets (`Set-ProjProps` and `Get-ProjProps`) and in your `foo` method you just orchestrate the calls and verify that `Set-ProjProps` (which you omitted from your example but I assume it does the actual work)  is called with correct parameters. You can test that via `Assert-MockCalled`.

**Comment by nhudacin** [comment]
Interesting...

So in this example, there is no "Set-ProjProps" method. I'm trying to test the orchestration of moving a database from one server to another.  There are several steps involved -->  killing db connections, setting it to read only, backing it up, copying it over, restoring it, running some validation checks, and sending our service notification of the new location.

The "Get-ProjProps" is just a stub method for this example. But really it's the query to our main service asking it where a project is located (as well as several other key attributes). I use this method to get the source connection string, then I run the above workflow, then for validation, I query the main service again to make sure it's reporting as I expect ($TargetInstance). 

I'm not testing Get-ProjProps, I'm really testing the stuff in the middle as well as (and probably most importantly) my error handling in the `foo` method (another stub just for this example).

Because I don't want the unit tests to actually query the service or move anything, I can't un mock `Get-ProjProps`. But I DO expect the return values to change during the `foo` procedure. 

With that in mind, is there still a way to avoid stateful mocks?  

TIA!

**Comment by Xoph** [comment]
What about a while-loop scenario?

I'm trying to test out a loop where we keep trying to get input from the user and continue in the loop until a condition is satisfied. I am mocking the actual call that reads the input within the loop, but I want to ensure the loop condition is correct, so I need to return different user inputs.

**Comment by nohwnd** [comment]
@nhudacin Wrote an example and forgot to post it: 
```powershell
function Get-Project ($name) {}
function Lock-Project ($project) {}
function Move-Project ($project) {}

function Assert-ProjectLocked ($Project) 
{
    if (-not $Project.Locked)
    {
        throw [InvalidOperationException]"Project is not locked"
    }
}
function Assert-MovedProject () {}

function Migrate-Project ($Name, $To) 
{ 
    $project = Get-Project $Name
    
    Lock-Project  $project
    Assert-ProjectLocked $project

    Move-Project -To $To $project

    $validationProject =  Get-Project $project.Name
    Assert-MovedProject $validationProject $To
}

function New-ProjectMock ($Name, [switch]$Locked)  
{ 
    [pscustomObject]@{
        Name = $Name 
        Locked = $Locked
    }
}

Describe "Migrate-Project" {
    #avoid calling real dependencies
    Mock Get-Project {} 
    Mock Lock-Project {}
    Mock Move-Project {}
    Context "Mocking scope" {
        It "Moves locked project" {
            Mock Get-Project { New-ProjectMock  }
            Mock Lock-Project { $Project.Locked = $True}

            Migrate-Project -Name dummy;

            Assert-MockCalled Move-Project -ParameterFilter { $Project.Locked }
        }
    }
    Context "Mocking scope" {
        It "Throws when moving unlocked project" {
            Mock Get-Project { New-ProjectMock }

            { Migrate-Project -Name dummy } | should Throw "not locked"
         
        }
    }
}
```

**Comment by nohwnd** [comment]
@Xoph I would limit the number of possible attempts to avoid getting into an infinite loop, because I don't want them to run on my Azure CI server indefinitely crunching away money. (Plus I want to get an email that says that the build failed without having to check.) And when you do that it's as simple as testing the correct and invalid input. 
```powershell
function Get-WellFormedInput ([int]$MaxAttempts = 1000) {     
    while ($true) {
        $data = (Read-Host)
        if ($data -match "^\d+$") 
        {
            return $data 
        }
        
        if (++$attempts -ge $MaxAttempts)
        {
            throw [InvalidOperationException]"User failed to provide well formed input before reaching the maximum number of attempts ($MaxAttempts)."
        }
    
    }
    $data
}

Describe "Get-WellFormedInput" {
    it "Fails after reaching maximum number of attempts" {
        mock Read-Host { "m" }
        { Get-WellFormedInput -MaxAttempts 10 }  | should throw
    }

    it "Accepts correct input" {
        $expected = 10
        mock Read-Host { $expected }
        $actual = Get-WellFormedInput -MaxAttempts 10  
        
        $actual| should Be $expected
    }

    Context "mocking scope" {
        it "Reads input only once when correct input is provided on first try" {
            $expected = 10
            mock Read-Host { $expected }
            $actual = Get-WellFormedInput -MaxAttempts 10  

            Assert-MockCalled Read-Host -Exactly 1
        }
    }

    Context "mocking scope" {
        it "Reads input maximum number of times" {
            $expected = 7
            mock Read-Host { "wrong input" }
            
            { Get-WellFormedInput -MaxAttempts $expected } | should throw
            Assert-MockCalled Read-Host -Exactly $expected
        }
    }
} 
```

**Comment by Xoph** [comment]
Awesome. Thank you for your response @nohwnd. I'm glad to see I was basically on the right track, although I do like the idea of limiting the number of attempts.

As a feature, would you consider a parameter to the Mock command, allowing a user to specify the maximum number of calls for these kind of loop-mocks?

**Comment by nohwnd** [comment]
Interesting idea, but it would be useful only for catching infinite loops, and only if we set the limit (1000 calls maybe?) as a default and let the users to override it. Pr did you have different use case in mind?

**Comment by Xoph** [comment]
Ya it should definitely be overrideable. For our unit tests, we are mocking all calls for anything that reads from the host, so I'm specifying explicitly what should be returned each time it is called. But I guess there would be value if someone is integration testing and allowing the user to interact with the test. Maybe it should just be something implemented by someone if/when they need it.

**Comment by it-praktyk** [comment]
I assume that the issue can be closed now. Feel free to reopen if you need more assistance.

**Comment by ghidalgo3** [comment]
@nohwnd you are too opinionated on stateful mocks. There is existing code out there written by people that don't have the time or expertise to design it to be easily testable. Say you inherit a large script and you're told to write unit tests for it because it keeps breaking: should Pester not support this use case?

**Comment by nohwnd** [comment]
@ghidalgo3 probably, but I am trying to avoid features that are targeted only on a single use case. Especially when they can be easily implemented when needed by the consumer of the framework.

**Comment by nohwnd** [comment]
This is admittedly opionionated, and has been shown how to overcome this limitation. If we add parameters to mock parameter filters then you can push your desired state in the mock easily and don't need any special support for this. Same thing could be done with reference object I think.
