### ISSUE TITLE
Question - How would I "Mock & Call Original"

### ISSUE THREAD

**Issue by nhudacin** [pester/Pester#578]
I'm finding more and more that I would like to simply Mock something just to be able to verify it was called with the parameters I expect. 

For things like `Get-ChildItem` or `Test-Path`, there are times I would prefer the original implementation to occur but just want to verify the parameters are what I expect. [RSpec](https://relishapp.com/rspec/rspec-mocks/docs/configuring-responses/calling-the-original-implementation) has this concept if you're not familiar with what I'm looking for.

Here's a quick example of what I'm looking to do. I want to figure out which of my `Get-ChildItem` functions were called. My first take is to mock `Get-ChildItem` and then call the original `Get-ChildItem` with the input path. This results in a depth overflow error: 

```posh
function NewFeature {
    
    if ($SomeEnvVar -and (Test-Path $SomeEnvVar)) {
        Get-ChildItem $SomeEnvVar | Where-Object { $_.Name -eq 'IDK' }
    }
    else {
        Get-ChildItem C: | Where-Object {$_.Name -eq 'WHOCARES' }
    }       

}

Describe 'Mock and call original' {
    
    Mock Get-ChildItem { return Get-ChildItem -Path $Path }
    
    It 'Mocks and calls the original' {
        NewFeature | Should Be $null
        Assert-MockCalled Get-ChildItem -ParameterFilter {$Path -eq 'C:'} -Exactly 1
    }
} 
```

Now I know the above doesn't really make sense to mock and call the original. I could just mock `Get-ChildItem` and assert it was call with a parameter filter. It was just a quick example of what I was looking to do. 

Anyone else doing this?? TIA

**Comment by dlwyatt** [comment]
Something along these lines should work:

```posh
    $getChildItemCmdlet = Get-Command Get-ChildItem -CommandType Cmdlet
    Mock Get-ChildItem { return & $getChildItemCmdlet -Path $Path }
```

**Comment by nhudacin** [comment]
That worked PERFECTLY!

Thank you so much!

**Comment by nohwnd** [comment]
If someone stumbles upon this a simpler (and safer) way is to put the variable directly into the Mock body: 

```powershell
Mock Get-ChildItem { 
    $getChildItemCmdlet = Get-Command Get-ChildItem -CommandType Cmdlet
    return & $getChildItemCmdlet -Path $Path 
}
```
Also make sure you specify the `-CommandType` correctly. Otherwise it will return the alias that Mock defined and will get into infinite loop.

**Comment by Xoph** [comment]
@nohwnd I tried your approach, as I understand what you're saying with it being simpler and safer, however, I actually get the infinite loop issue with your approach, but not with @dlwyatt 's.

The function I am mocking is a function from one of our modules, so I used -CommandType Function. It actually works in the first Context block in my Describe block, but then in the next Content block, I get the inifinite loop issue. However, I found that if I do the Get-Command inside the Describe block but outside of any Context block, then I can use @dlwyatt 's code to mock it in each Context block.

Example that has infinite loop issue:
```
Describe "Describe" {
    Context "Context1 PASSES" {
        Mock My-Function { 
            $myFunction = Get-Command My-Function -CommandType Function
            return & $myFunction
        }
    }

    Context "Context2 FAILS" {
        Mock My-Function { 
            $myFunction = Get-Command My-Function -CommandType Function
            return & $myFunction
        }
    }
}
```

Example that passes:
```
Describe "Describe" {
    $myFunction = Get-Command My-Function -CommandType Function

    Context "Context1" {
        Mock Get-ChildItem { 
            return & $myFunction
        }
    }

    Context "Context2" {
        Mock My-Function { 
            return & $myFunction
        }
    }
}
```

**Comment by Xoph** [comment]
I realized today that this could also be a scoping issue on my end since we're stuck on an earlier version of Pester.

**Comment by nohwnd** [comment]
Don't know what you do wrong, it works for me, when the function is in module and even if it is not in module:  

```powershell
New-Module a -ScriptBlock {
    function My-Function () { 
        Write-Host "Hello"
    }  
} | Import-Module

Describe "Describe" {
    Context "Context1 PASSES" {
        Mock My-Function { 
            $myFunction = Get-Command My-Function -CommandType Function
            return & $myFunction
        }

        My-Function
    }

    Context "Context2 FAILS" {
        Mock My-Function { 
            $myFunction = Get-Command My-Function -CommandType Function
            return & $myFunction
        }

        My-Function
    }
}
```

This is latest Pester 4, which version are you using? This probably would not work on very old Pester where aliases are not used for Mocking, but instead of that functions are used.

**Comment by jazzdelightsme** [comment]
I think this technique is important and useful enough, and difficult enough to figure out on your own, that it warrants being described in the documentation for `Mock`.
