### ISSUE TITLE
Tweak results line to be more readable

### ISSUE THREAD

**Issue by rkeithhill** [pester/Pester#581]
Whenever I glance at this:

```
Passed: 11 Failed: 0 Skipped: 0 Pending: 0 Inconclusive: 0
```

I see `11 Failed`  instead of `Passed: 11`.  It might be more readable as:

```
Passed: 11, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0
```

Or maybe

```
Passed: 11  Failed: 0  Skipped: 0  Pending: 0  Inconclusive: 0
```

**Comment by kilasuit** [comment]
As an extended suggestion I'd personally perfer it to be separate lines like so
```
Passed: 11  
Failed: 0  
Skipped: 0  
Pending: 0  
Inconclusive: 0
```
I just that its easier to read like that than on 1 line.

**Comment by dlwyatt** [comment]
In v4, I believe they're all different colors anyway, so the alignment doesn't matter as much.  Have to double check

**Comment by rkeithhill** [comment]
@dlwyatt That'll work for the PowerShell.exe and ISE hosts.  It will be interesting to see if that works in VSCode.

**Comment by it-praktyk** [comment]
I assume that the issue can be closed now. Feel free to reopen if you need more assistance.
