### ISSUE TITLE
Naming conflict in Mock.ps1 - Set-DynamicParameterVariables

### ISSUE THREAD

**Issue by mbreakey3** [pester/Pester#582]
The parameter $Metadata in Set-DynamicParameterVariables (Mock.ps1: line 1202) is causing a type-conflict for mocked functions that also have a parameter called 'Metadata'  (WebAdministration's [Set-WebConfiguration](https://technet.microsoft.com/en-us/library/hh867871(v=wps.630).aspx) particularly). 

When this line:

$SessionState.PSVariable.Set($variableName, $keyValuePair.Value) (line 1219)

is called, it won't allow the mocked $Metadata to be set because it thinks it should be of type [System.Management.Automation.CommandMetadata].

One solution is to change the names of the parameters in this function to be more unique so that conflicts such as this don't arise.

Repro:

function Sample { 
param(
    [string]
    ${Metadata}
)
 } 

function Wrapper {
    Sample -Metadata 'test'
}

Describe 'Bug in mock' {
    Mock -CommandName Sample -MockWith {}
    Wrapper
}

**Comment by TravisEz13** [comment]
To clarify...
# Repro

function Sample { 
param(
[string]
${Metadata}
)
}

function Wrapper {
Sample -Metadata 'test'
}

Describe 'Bug in mock' {
Mock -CommandName Sample -MockWith {}
Wrapper
}

# Expected
 should be able to mock sample without error

# actual
Cannot mock sample due to error

**Comment by kilasuit** [comment]
@mbreakey3 / @TravisEz13 I know I'm being picky but could you add the code formatting to these to make it easier to read - Cheers

**Comment by dlwyatt** [comment]
Ah, good catch.  I thought I had given all of the variables that get injected into caller's scope weird names, but missed the ones in that block.

It's not the parameters in Set-DynamicParameterVariables that are the problem, it's the `$scriptBlock` set up in the `ExecuteBlock` function.  Will fix tonight.
