### ISSUE TITLE
Consider allowing nested Described blocks

### ISSUE THREAD

**Issue by narrieta** [pester/Pester#587]
This would allow, for example, sharing initialization across multiple Describe blocks:

    Describe 'MyModule' {
        BeforeAll { ... }
        AfterAll { ... }
        Describe 'MyFirstCmdlet' { ... }
        Describe 'MySecondCmdlet' { ... }
    }

Thanks!

**Comment by dlwyatt** [comment]
This is already happening in v4.  Still have some things to tie up before that's ready for release, but we're getting close.

**Comment by narrieta** [comment]
Thanks!
