### ISSUE TITLE
Mock command within child import-module script

### ISSUE THREAD

**Issue by davidwallis3101** [pester/Pester#593]
I have a psm1 file containing a few functions one of these is lets say CreateSomething()

Function CreateSomething {
  ## other logic
  DoSomething($WithSomething)
}

I want to put some tests around the above function, but mock the DoSomething Function..  however this is imported with  import-module $moduleName -force -ErrorAction stop within the script as people may not have the module installed but it is typically located in the same path.. 

how do I mock the DoSomething?? Do I need to change the import and edit the manifest? - does the module need to be installed for pester to see it??

**Comment by dlwyatt** [comment]
Ideally, you should have all of the dependent modules installed in order to run your tests.  (After all, your module would just error out if the other module wasn't there, right?)  But if not, you could just define a global `DoSomething` function in your code, then mock that.

**Comment by davidwallis3101** [comment]
createSomething calls code to check that the required dependency is imported - so that stops the errors from occurring.

**Comment by dlwyatt** [comment]
That's awkward.  Personally, I would move that code to check for the dependency so that it happens when your module is imported, not when the createSomething function is called.  Otherwise you won't be able to mock the dependency functions ahead of time.

**Comment by davidwallis3101** [comment]
Ok, let me hack about and the script and see what happens :) - I'm just trying it as a nested module in the manifest.

**Comment by davidwallis3101** [comment]
Right that fixed the issue by getting rid of that code and doing a nested module via the manifest.. I now have that command mocked. I now also have a test verifying the manifest thanks to some googling.

Thanks :)
