### ISSUE TITLE
VSCode..

### ISSUE THREAD

**Issue by davidwallis3101** [pester/Pester#594]
I am using vscode and some task runners to kick of the test..

I am using https://github.com/IBM-Bluemix/vscode-log-output-colorizer to colourize the output.. 

Dont suppose you have any plans to add support in for Pester?

Also Is there anyway I can change the formatting of:

Passed: 18 Failed: 0 Skipped: 0 Pending: 0 Inconclusive: 0

to be:

Passed: 18 `n Failed: 0`n Skipped: 0 `n Pending: 0`n Inconclusive: 0

or

Passed: 18, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0

Its just I read it as "18 Failed"

**Comment by davidwallis3101** [comment]
its stripped the back tick (IE powershell escape char, so I mean't to show a new line char)

**Comment by dlwyatt** [comment]
Other than modifying the code, there's not currently any way to control that part of the output.  (I suppose you could technically wrap Invoke-Pester in your own function, use the `-Quiet` switch, then build console output however you like based on the `-PassThru` object, but that's a lot of work.)

I haven't been using VSCode, so not sure what its current state is with regards to PowerShell colors.  Pester already does a lot of colorization itself via Write-Host.

**Comment by eugeneniemand** [comment]
@davidwallis3101 try the integrated console and not the debug output window. The terminal does support colour. Not sure how to get tasks to run in the integrated terminal instead of debug window.

**Comment by it-praktyk** [comment]
Is it related: https://powershell.org/forums/topic/vscode-snippets-for-pester/ ?

Can you update the current issue based on the newest version of Pester v4?

Can you change the issue title to something more descriptive?

**Comment by nohwnd** [comment]
@it-praktyk I am using Pester in VSCode regularly, and since this was reported they started using the standard terminal for output, which shows colors. Closing.
