### ISSUE TITLE
Recommendation for NUnitXml to HTML Converter

### ISSUE THREAD

**Issue by ChrisLynchHPE** [pester/Pester#596]
Not sure where else to ask this question.  But I'm curious what tool folks are using to convert the NUnitXml report to an HTML readable version.  I found [NUnit-HTML-Report-Generator](https://github.com/JatechUK/NUnit-HTML-Report-Generator) and it seems to do a decent job (although it currently can't handle the . character correctly when trying to parse the `Description` property of the NUnitXml file).  I found [NUnit Orange – NUnit HTML Report](https://www.nuget.org/packages/NUnitOrange), but it appears that the developer has some problems maintaining a virus free dev environment.

**Comment by iainbrighton** [comment]
Have you looked at Format-Pester? https://github.com/equelin/Format-Pester

**Comment by ChrisLynchHPE** [comment]
@iainbrighton I have not.  Thanks!

**Comment by ChrisLynchHPE** [comment]
@iainbrighton I think I may have found a bug in Format-Pester, which I did log on the [Format-Pester Issue Tracker](https://github.com/equelin/Format-Pester/issues/14).  I see you have helped with that project, any ideas?

**Comment by ChrisLynchHPE** [comment]
Format-Pester is really awesome.  Thanks for the suggestion.  Closing this discussion.
