### ISSUE TITLE
Problems Mocking Set-AzureRmVirtualNetwork

### ISSUE THREAD

**Issue by dacarab** [pester/Pester#600]
Not sure if I am missing something here or if this is related to #491 

I'm getting prompted to provide a PSVirtualNetwork object when running the below:
```
Remove-Module Pester -ErrorAction:SilentlyContinue
Remove-Module Azure* -ErrorAction:SilentlyContinue

Import-Module AzureRm.Profile -RequiredVersion 2.0.1
Import-Module AzureRm.Network -RequiredVersion 2.0.1
Import-Module Pester -RequiredVersion 3.4.3

Describe "Testing AzureRm Mocks" {
    Mock Get-AzureRmVirtualNetwork {
        Return "Get-VNet Mock"
    }

    Mock Set-AzureRmVirtualNetwork {
        Return "Set-VNet Mock"
    }

    It "Should Mock Get-AzureRmVirtualNetwork" {
        Get-AzureRmVirtualNetwork | Should Be "Get-VNet Mock"
        Assert-MockCalled -Times 1 -CommandName Get-AzureRmVirtualNetwork
    }

    It "Should Mock Set-AzureRmVirtualNetwork" {
        Set-AzureRmVirtualNetwork | Should Be "Set-VNet Mock"
        Assert-MockCalled -Times 1 -CommandName Set-AzureRmVirtualNetwork
    }
}
```
The output is 
```
Describing Testing AzureRm Mocks
 [+] Should Mock Get-AzureRmVirtualNetwork 66ms
cmdlet Set-AzureRmVirtualNetwork at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
VirtualNetwork: 
```
It sits there prompting for input for the VirtualNetwork parameter.

**Comment by dlwyatt** [comment]
Not related to the other issue, but one of the biggest pain points in Pester at the moment.  Right now, when you mock a command, the mock inherits the parameter metadata of the original command:  parameter sets, names, attributes, types, everything.  When you mock one command that's used as the input to another, you typically wind up outputting an object of a different type than what the original command would have done, maybe just a pscustomobject or a hashtable.  Then when you try to pass that on to a different mocked command, you get this error.  Happens in lots of places.

I'm still trying to think of a good way to solve this problem.  Might take a page out of the PowerShell team's book and start up a "Pester RFC" repo where we can open discussion on this sort of thing, get some community input before deciding on a course of action.

**Comment by dacarab** [comment]
OK cool - thanks for the feedback, much appreciated.

In my tests, I've been trying to save a PSVirtualNetwork object as an xml string in the test script, then use **[System.Management.Automation.PSSerializer]::Deserialize()** to turn it into the correct object type. 

But that results in a type with a ***Deserialized*** prefix, so when I try and pass that test object into a cmdlet like **Add-AzureRmVirtualNetworkSubnetConfig**, I get a **PSInvalidCastException**.

Are there any good strategies for handling this type of issue? Or is it a case that different cmdlets / types require different approaches?

**Comment by dlwyatt** [comment]
Depends on the types involved.  If you're lucky, the type will have a sane, public constructor that you can just use in your mock of Get-AzureRmVirtualNetwork.  By "sane", I mean the object won't try to do things on the network just by creating an instance of it.  (But considering that they have _cmdlets_ behaving that way in the issue you referenced, I wouldn't get my hopes up too much on that one.)

**Comment by dacarab** [comment]
Ok, thanks for the feedback
