### ISSUE TITLE
Input requested:  Mocking commands with annoying, strongly-typed parameters

### ISSUE THREAD

**Issue by dlwyatt** [pester/Pester#601]
This has long been the most annoying type of test to write in Pester, and I want to do something about it.  Haven't been able to think of a perfect solution, but there are a couple of options available, and I'd like to get some feedback from the community.  First, an example of the problem:
## Looks great.  Doesn't work.

``` posh
# Somewhere in your code to be tested:

$adapter = Get-NetAdapter
# Do something
$adapter | Set-NetAdapter
```

If you look at the parameter metadata for Set-NetAdapter (or run Trace-Command), you'll see that we're binding the InputObject parameter via the pipeline in this scenario, which needs to be a [ciminstance[]] object with a particular PSTypeName.  Now let's mock these commands in a test somewhere:

``` posh
Mock Get-NetAdapter { [pscustomobject]@{ Name = 'Mocked' } }
Mock Set-NetAdapter

# Do stuff

Assert-MockCalled Set-NetAdapter -ParameterFilter { $InputObject.Name -eq 'Mocked' }
```

Reasonable looking code.  Mock the Get command to return a dummy object and eliminate one external dependency, and mock the Set command in conjunction with Assert-MockCalled to take care of the other.  Except it doesn't work, with an error something like this:

```
Set-NetAdapter : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:6
+ $adapter | Set-NetAdapter
+      ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (@{Name=Mocked}:PSObject) [Set-NetAdapter], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Set-NetAdapter
```

The exact error may vary a bit, but they all boil down to the fact that the simple custom object we returned from our mock of Get-NetAdapter can't be passed to the InputObject parameter of the mock, because Set-NetAdapter's expecting a different object type (even when mocked; it gets the parameter metadata from the original command.)

The way things stand today, you have two main options for getting around this situation:
- Have your mocked Get- command return an object compatible with what the other cmdlets later on will expect.  In the case of a [ciminstance] with a particular PSTypeName, that's not too painful; we can make that happen.  But sometimes you might be dealing with types that don't have public constructors, or have constructors that do things you don't want them to do as soon as the object is created.
- Write a function with similar, but not quite exactly the same metadata as the Set-NetAdapter command, then mock that instead.  In this case, you'd probably change InputObject's type to [object[]] and get rid of the PSTypeName requirement.  Works, but can sometimes be tricky due to scopes and function lookup order, and requires a fair bit of code.
### Option 1: Automatically make all parameters [object] or [object[]], get rid of validation attributes on the mock.

On the plus side, you'd completely avoid the types of errors discussed in this post, but may introduce other errors.  For example, you might bind to a different parameter set than what would have happened in the original command, or your test may succeed when a call to the live command will fail.  If you're using parameter filters and Pester needs to call the original command due to not matching any filter, it may be possible for the command to error for similar reasons.  (Not certain of this one.)
### Option 2: User-controlled version of Option 1

Instead of making _all_ parameters "safe" for mocking, only change the ones the test author specifies when they call the Mock command.  Something like `Mock Set-NetAdapter -SafeParameter InputObject` .  This way you only use the feature when you need it, and otherwise won't get the weird binding / false positive problems mentioned above.

Possible downside to this:  mock parameter metadata is set one time for the mock, regardless of how many times you use the Mock command for that target.  (Technically,this happens once per Describe block, or in the upcoming v4, once per test script; mocks get cleaned up after the top level test container goes away.)  Even if we update Pester's code to make sure that the most recent Mock's options are "live", there can still only be one version defined at a time.
### Option 3:  Your Idea Here.  :smile:

If you have a better idea on how to make mocking these commands less painful, please share!

**Comment by MattHodge** [comment]
This is more of a work around, but what I do something like:

```powershell
# serialize the adapter object to XML
Get-Adapter | Export-Clixml -Path 'C:\tmp\adatperxml.xml'
```

Then inside my test, I would copy the contents of `C:\tmp\adatperxml.xml` and put it as a Here-String eg:

```powershell
$getAdapterMockObject = @"
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04">
  <Obj RefId="0">
    <TN RefId="0">
      <T>Microsoft.Management.Infrastructure.CimInstance#ROOT/StandardCimv2/MSFT_NetAdapter</T>
      ... #etc etc
      <S N="ifDesc">Hyper-V Virtual Ethernet Adapter</S>
      <S N="ifName">ethernet_32771</S>
      <S N="DriverVersion">10.0.14393.0</S>
      <S N="LinkLayerAddress">00-15-5D-02-0F-00</S>
    </MS>
  </Obj>
</Objs>
"@

# Deserialize it back into an object
$myobj = [System.Management.Automation.PSSerializer]::Deserialize($getAdapterMockObject)

# Mock the cmdlet with the object
Mock Get-NetAdapter { return $myobj }
```

**Comment by vors** [comment]
I like user controlled version, but I would suggest to change the default to strictly typed by default. Then parameter would be UnsafeParameter.

**Comment by MathieuBuisson** [comment]
I prefer the user-controlled version.

Pester users have come to expect that mocks have the same parameters and parameter behaviours as the original command.
For that reason, anything that makes the mock diverge from the original command's behaviour should be explicitly set by the user. That way, anyone who reads, reviews or maintains the code can see it easily, and can assume this was a deliberate choice and this was done for a specific reason.

Also, I like the fact that this is specified on a per parameter basis, because I think this should be done granularly and **sparingly**.
Why "sparingly", because whenever possible (and it is possible most of the time), it is still better to pass a object compatible with what the original parameter expects.

**Comment by dlwyatt** [comment]
@vors :  That behavior is the plan.  Parameter name is kind of irrelevant; don't have one that really clicks yet.  Thought of `-JustFreakingBindMyParameterAlready`, but it's kind of long.

**Comment by 4c74356b41** [comment]
User controlled version seems ok. I'm not exactly the biggest expert in this stuff.

**Comment by vors** [comment]
@dlwyatt ah I see. Good.

**Comment by nohwnd** [comment]
@dlwyatt As other said. Keeping it work with strong types, and being able to override when needed sounds like the best option.

**Comment by nohwnd** [comment]
Will mark this as Help wanted:
- Implementer should go for Option 2. 
- The `-SafeParameter` name could be improved, please propose one. `-UntypeParameter`? 
- I think the parameter should take `-like` wildcards so '*' is possible for making all parameters untyped.
- I think there will be similar functionality `-SkipParameter` (`-UndefineParameter`?) that will allow you to skip parameters that otherwise cause errors like `$PSEdition`. It would be nice if the names complimented each other.

**Comment by renehernandez** [comment]
@nohwnd As part of this issue, are the following two items required?:
- Change parameter type to `object` or `object[]`
- Remove validation attributes?

Do you have any new idea for the name of the new Parameter to add to the Mock function? If the two requirements above are correct, then `UntypeParameter` is missing part of the objective. What about `RelaxParameter`?

**Comment by nohwnd** [comment]
@renehernandez  Yeah I think it should do those two things. I am not sure if they should be tied together though. How about `-RemoveParameterType` and `-RemoveParameterValidation` that would do each of the actions? 

I am also not sure if the type should be explictly provided as `[object]`/`[object[]]` or simply omitted from the parameter definition. Personally I would remove it, let the implementer do what he/she wants. (or even better it would be commented out `# [VirtualMachine[]] - skipped by Pester Mock` not sure how difficult that is, but it would be useful for debugging imho).

**Comment by renehernandez** [comment]
@nohwnd  How are these changes going to apply to nested `Mock` statements? The following example may illustrate better my question:

```
function Test-ParameterRemoval {
    param(
        [Parameter()]
        [ValidateNotNull()]
        [WeirdParameterType]
        $Foo,
        [Parameter()]
        [ValidateNotNull()]
        [WeirdParameterType]
        $Bar
    )

    Write-Output $Foo
}

Describe 'Test-ParameterRemoval' {
    BeforeAll {
         Mock Test-ParameterRemoval {} -RemoveParameterType 'Foo' -RemoveParameterValidation 'Bar'
    }

    Context 'First context' {
        BeforeAll {
            Mock Test-ParameterRemoval {} -RemoveParameterType 'Bar' -RemoveParameterValidation 'Foo' -ParameterFilter {$Bar -eq #something}
        }
    }

    Context 'Second context' {
        BeforeAll {
            Mock Test-ParameterRemoval {} -ParameterFilter {$Foo -eq #something}
        }
    }
}
```

Is each Mock instance override the changes?

**Comment by nohwnd** [comment]
@renehernandez to keep it simple, they won't. The Mock bootstrap function is defined just once for the first mock, and so are the parameters to that function. Which means that the change to Bar would not apply, nor would the last mock have strongly typed `Foo`.

To make the rules apply we would need to aggregate the rules and apply de-apply them based on the scope. It's not a rocket science, but it's not exactly simple either. 😁 So let's start from the simpler solution where the first mock defines what happens and once that works go from there. k?:)

**Comment by renehernandez** [comment]
Yup, that was where I was coming from, because currently we cache the `Metadata` object associated with the Mock; therefore this type of changes applies to all nested `Context`/`Describe`.  I think I have what I need to start working :)

**Comment by sheppyh** [comment]
Hi, what if the function that you are testing (and therefore cannot mock) has strongly typed parameters? Anyway to relax this? Or do I need to make a deserialized object as suggested in the XML example?

**Comment by nohwnd** [comment]
@sheppyh then you have to make the parameters abstract or interfaces, or subclass them if they are not sealed. Or use reflection to modify the contents of the class. Could you start a new thread with an example of what you are struggling with? If you are author of the class that is used as the strong typed parameter. You should make sure that you can get the class in the state that is needed for the test. Or make sure the class can only get into states that are valid for your usage.
