### ISSUE TITLE
Mocking Get-Package and Install-Package

### ISSUE THREAD

**Issue by RamblingCookieMonster** [pester/Pester#604]
Hi all!

Will start poking around, but having a tough time mocking Get-Package and Install-Package.

```powershell
Describe "PackageManagement" {
    Context "Testing with Pester" {
        It 'Should let me Mock it' {
            Mock Get-Package { 'not null' }
            Get-Package -Name 7zip -ProviderName Chocolatey | Should Not BeNullOrEmpty
        }
    }
}
```

Expected outcome: Test passes...

Actual outcome:

```
Describing PackageManagement
   Context Testing with Pester
    [-] Should let me Mock it 168ms
      ParameterBindingException: A parameter cannot be found that matches parameter name 'ProviderName'.
      at <ScriptBlock>, C:\Users\wframe\Desktop\dupe.ps1: line 5
Tests completed in 168ms
Passed: 0 Failed: 1 Skipped: 0 Pending: 0 Inconclusive: 0
```

Server 2012 R2, PSVersionTable:
```
Name                           Value                                                                                                     
----                           -----                                                                                                     
PSVersion                      5.0.10586.117                                                                                             
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                   
BuildVersion                   10.0.10586.117                                                                                            
CLRVersion                     4.0.30319.42000                                                                                           
WSManStackVersion              3.0                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                       
SerializationVersion           1.1.0.1     
```

Same deal with the `Source` parameter for Install-Package.

Am I missing anything obvious?

Cheers!

**Comment by dlwyatt** [comment]
It's a dynamic parameter.  Pester is supposed to work with those, but occasionally someone finds a cmdlet that is broken.  I'll see what I can do.

**Comment by dlwyatt** [comment]
In Windows 10 (PS v5.1), I get a different error:  `Get-Package : Parameter set cannot be resolved using the specified named parameters.`  This isn't limited to Pester, though; same thing happens if I just create a proxy function for `Get-Package` and try to call it the same way.  Since Pester's mocks are essentially just proxy functions, we might be screwed on this one.

You could work around it by writing a dummy Get-Package function in your tests, instead of (or in addition to) mocking.

**Comment by RamblingCookieMonster** [comment]
Hi Dave!

Makes sense to me, that will work - thanks!

**Comment by rismoney** [comment]
So if I call Install-Module, Get-PackageSource, Unregister-PackageSource, and Register-PackageSource in a function, what is the proper way to mock those, and not have the system call out.  I can't see to get this working using any method.

**Comment by nohwnd** [comment]
Have you tried doing this on the latest version of Pester? If it still does not work, please create a new issue.
