### ISSUE TITLE
Question: Always have a Describe block run during tests

### ISSUE THREAD

**Issue by ChrisLynchHPE** [pester/Pester#606]
I have defined multiple Describe blocks within my main test script, each with their own `-Tag` defined.  Is there any way to have a Describe block always run, every time, even when you use `Invoke-Pester -Tag $TagName`?

I ask because `BeforeAll` and `AfterAll` are only available within a `Describe` or `Context` block.  I want to have completion tests run that test for removal of module resources when it is unloaded for regression testing purposes.

**Comment by dlwyatt** [comment]
There's no way to do that at the moment, but you could use try/finally to accomplish the same thing.  (`AfterAll` is just a wrapper around try/finally anyway).:

```posh
try
{
     # "BeforeAll" code here

    Describe 'Something' { }

    Describe 'Something Else' { }
}
finally
{
    # "AfterAll" code here
}
```

**Comment by ChrisLynchHPE** [comment]
I'll check to see if that works.  Are there plans to add this functionality?

**Comment by dlwyatt** [comment]
In v4, I plan to have the tests script be a first-class scope as far as Pester is concerned, so Describe blocks would become optional (and you could put BeforeAll / AfterAll at the script scope, etc, though I think there is still some work to be done before those would function properly.)

**Comment by it-praktyk** [comment]
@dlwyatt, can you confirm that it was implemented and the issue can be closed now?

@nohwnd, can you add this to the changelog? - based on @dlwyatt's answer

**Comment by ChrisLynchHPE** [comment]
This issue can be closed.  I just put all of the pre-validation code into `BeforeAll` calls within each `Describe` block.
