### ISSUE TITLE
Array comparison fails if arrays begin with zero

### ISSUE THREAD

**Issue by art-bel** [pester/Pester#609]
If I compare two exactly same arrays beginning with 0 the test fails. Output dump is attached.

Output dump:
WARNING: Left comparand:  00 11 22 33 44 55 66 77 88 99 AA BB CC DD EE FF
WARNING: Right comparand: 00 11 22 33 44 55 66 77 88 99 AA BB CC DD EE FF
    [-] Different input 8.28s
      Expected: {0 17 34 51 68 85 102 119 136 153 170 187 204 221 238 255}
      But was:  {0}
      63:                     ($Config.Value["Secret"] | ConvertTo-ByteArray) | Should Be ($parsed["secret"] | ConvertTo-ByteArray)
      at Test-Key<Process>, C:\Arthur\Tests\New-Token.tests.ps1: line 63
      at <ScriptBlock>, C:\Arthur\Tests\New-Token.tests.ps1: line 346

**Comment by dlwyatt** [comment]
At the moment, `Should Be` doesn't really compare arrays.  This is something that's coming in v4.

**Comment by dlwyatt** [comment]
If you really want to twist your brain, add another zero to that array and watch it succeed.  ;)  (Has to do with how PowerShell's comparison operators work with arrays, and how it casts different things to boolean).
