### ISSUE TITLE
Test duration

### ISSUE THREAD

**Issue by davidwallis3101** [pester/Pester#611]
Don't know how feasible it would be, but I have some long running steps in a test that for example:

`it "check long running job doesn't time out" { {do-longrunningJob} |should not throw}`

it would be nice if it were possible to also say for the same step.. :

`it "check long running job" { {do-longrunningJob}  | should complete [under]/[within] (New-TimeSpan -Seconds 120)}`

Or is it already possible as I can't find an example

Thanks

**Comment by nohwnd** [comment]
No this is not currently built-in, but it's very easy to do, and combine with other assertions.
```powershell
function Get-ADUser(){ "user" }
Describe a {
    it "check long running job" {
        $me   = $null
        $time = Measure-Command { $me = Get-ADUser }
        $time | should BeLessThan (New-TimeSpan -Seconds 1)
        $me   | should be "user"
     }
 }
```

**Comment by davidwallis3101** [comment]
Nice :+1:  Thanks
