### ISSUE TITLE
Launching tests in parallel

### ISSUE THREAD

**Issue by davidwallis3101** [pester/Pester#613]
Is anyone launching tests in parallel or got any tips?

I am using pester to do some integration testing of my automated server build process, and the pester test kicks off a build and waits for it to complete so this takes a little while..

I have a number of env's and OS combo's that I need to test, so to run these sequentially will take a while..

I have split the tests out into smaller test files on a per env basis so I can attempt to launch them in parallel,  has anyone created a script using workflows or invoke-parallel to launch their tests in parallel?

(I plan to take the Nunit output and use this within TFS)

Thanks

**Comment by dlwyatt** [comment]
I generally rely on my CI server to take care of that.  In TeamCity, I'd set up multiple build configurations, each to run a different sub-set of the tests, and define the configuration dependencies in such a way that TC will automatically run the configs as soon as an agent is available.

**Comment by davidwallis3101** [comment]
Ok, I have got something working nicely:

it might be a bit crude but works in tfs Vnext build servers.. 

I run the following script (Write-host will be swapped back to verbose!):

```
[CmdletBinding()]
param()

Write-verbose "Importing required modules"
Import-Module "C:\Program Files\WindowsPowerShell\Modules\Pester\pester"

Write-host "Powershell Version:"
$PSVersionTable |fl

# Create the artifacts folder if not present
if (!(Test-Path -Path "./artifacts" )){ $null = New-Item -ItemType directory -Path "./artifacts"}

# Dot source the invoke-parallel script
. ".\AutomatedBuilds\Invoke-Parallel\Invoke-Parallel\Invoke-Parallel.ps1"

#Get the test Files and invoke in parallel
$Tests = Get-ChildItem ".\IntegrationTests\Tests" -Filter "*.tests.ps*"

$Tests | Invoke-Parallel -ScriptBlock {
	Write-Host "Invoking Pester for: $_.Name"
	Import-Module .\OrchestratorServiceModule\OrchestratorServiceModule.psd1 -errorAction Stop
	Import-Module .\Servers\Servers.psd1 -errorAction Stop
    
    Invoke-Pester `
        -Script $_.FullName `
        -EnableExit `
        -OutputFile "./artifacts/Test-$($_.Name)_Pester.XML" `
        -OutputFormat NUnitXml
 }

```

I then have a step to publish the Nunit results and have clicked the merge results option.

Thanks

**Comment by it-praktyk** [comment]
The related issue #663.

**Comment by it-praktyk** [comment]
I assume that the issue can be closed now. Feel free to reopen if you need more assistance.

**Comment by lawrencegripper** [comment]
If anyone lands here looking for similar I put together a blog post building on the above script: https://blog.gripdev.xyz/2020/11/12/running-pester-tests-in-parallel/
