### ISSUE TITLE
Typo at project's description in word "PowerShell"

### ISSUE THREAD

**Issue by alexandear** [pester/Pester#614]
Pester's description at GitHub should be:
**PowerShell** BDD style testing framework

Typo also present at [TeamCity](https://build.powershell.org/project.html?projectId=Pester&tab=projectOverview&guest=1)
![image](https://cloud.githubusercontent.com/assets/3228886/18934696/e16c6fa0-85e3-11e6-8a4f-ffc55ce1bfa1.png)

**Comment by nohwnd** [comment]
Fixed it in the description. @dlwyatt Would you please fix it in the TC?

**Comment by dlwyatt** [comment]
Done.

**Comment by nohwnd** [comment]
@dlwyatt Thank you.
