### ISSUE TITLE
Write-Verbose - Odd Behaviour when testing output combined with Write-Output

### ISSUE THREAD

**Issue by Bidthedog** [pester/Pester#621]
Hi there. Thankfully I've managed to replicate this in a relatively small example.

When I mix Write-Output and Write-Verbose, with Write-Verbose mocked, I get unexpected test failures. Module and tests are in the same folder:

**my.module.psm1**

```
function Test-One {
    Write-Output "testing output"
}

function Test-Two {
    Write-Verbose "testing verbose"

    Write-Output "testing output"
}
```

**my.module.tests.ps1**

```
Import-Module Pester

Import-Module "$PSScriptRoot\my.module.psm1" -Force

Describe "Assertion Failure Example" {
    Context "Write-Output" {
        # Arrange

        # Act
        $output = Test-One

        # Assert
        It "Does not return null" {
            $output | Should Not Be $null
        }

        It "Returns expected string" {
            $output | Should Be "testing output"
        }
    }

    Context "Write-Output and Write-Verbose" {
        # Arrange
        Mock Write-Verbose { return $null } -ModuleName "my.module"

        # Act
        $output = Test-Two

        # Assert
        It "Does not return null" {
            $output | Should Not Be $null
        }

        It "Returns expected string" {
            $output | Should Be "testing output"
        }
    }

    Context "Write-Output and Write-Verbose with string return" {
        # Arrange
        Mock Write-Verbose { return "" } -ModuleName "my.module"

        # Act
        $output = Test-Two

        # Assert
        It "Does not return null" {
            $output | Should Not Be $null
        }

        It "Returns expected string" {
            $output | Should Be "testing output"
        }
    }
}
```

Test output is as follows:

> Describing Assertion Failure Example
>    Context Write-Output
>     [+] Does not return null 102ms
>     [+] Returns expected string 15ms
>    Context Write-Output and Write-Verbose
>     [-] Does not return null 282ms
>       Expected: value was {}, but should not have been the same
>       31:             $output | Should Not Be $null
>       at <ScriptBlock>, D:\pester\my.module.tests.ps1: line 31
>     [-] Returns expected string 31ms
>       Expected: {testing output}
>       But was:  {}
>       35:             $output | Should Be "testing output"
>       at <ScriptBlock>, D:\pester\my.module.tests.ps1: line 35
>    Context Write-Output and Write-Verbose with string return
>     [+] Does not return null 155ms
>     [-] Returns expected string 28ms
>       Expected string length 14 but was 0. Strings differ at index 0.
>       Expected: {testing output}
>       But was:  {}
>       -----------^
>       52:             $output | Should Be "testing output"
>       at <ScriptBlock>, D:\pester\my.module.tests.ps1: line 52

Fiddling around with it, it seems to pass again if I return "" from the Write-Verbose mock. However, testing for the value (see second test in second describe) doesn't return true as I would expect

I've been using $null for all mock outputs up until now - though I've only been mocking my own functions, not the built in functions.

**Comment by dlwyatt** [comment]
In PowerShell, `return $null` is not the same as doing nothing.  You're actually writing a `$null` value to the pipeline, which winds up being tested by the `Should` command.  Just do this instead:

`Mock Write-Verbose`

Or, if you prefer to be explicit:

`Mock Write-Verbose { }`

**Comment by Bidthedog** [comment]
D'oh, that's pretty obvious now you've said it. Strangely I'd just tried to do exactly that and was about to post my results!
