### ISSUE TITLE
Testing against multiple PS versions

### ISSUE THREAD

**Issue by davidwallis3101** [pester/Pester#622]
What approach are people using for testing their code against multiple powershell versions? 

Launch powershell with a specific -version flag and then invoke tests or have a script to determine available versions and launch tests??

**Comment by nohwnd** [comment]
The `-Version` flag is not a good way to test compatibility with a given PowerShell version. To test your product properly, you need to have multiple installations of Windows and then use something to run the tests on them. You can either use a custom script, or a whole continuos integration solution such as TeamCity. That is how Pester is tested, and if your project is public then you can use build.powershell.org as well. Here is example how Pester is built on that server. https://build.powershell.org/project.html?projectId=Pester&tab=projectOverview&guest=1
