### ISSUE TITLE
Should beOfType doesn't seem to work for classes

### ISSUE THREAD

**Issue by alx9r** [pester/Pester#623]
Running 

````PowerShell
Describe describe {
    class a {}
    $a = [a]::new()
    It 'fails' {
        $a | Should beOfType 'a'
    }
    It 'succeeds' {
        $a -is [a] | Should be $true
    }
    It 'succeeds' {
        1.0 | Should beOfType 'double'
    }
}
````

yields
![image](https://cloud.githubusercontent.com/assets/11237922/19582199/5ea71b1e-96ce-11e6-9ea2-16b514112c17.png)

I expected all three `It{}` blocks to pass.  It seems like `$a -is [a] | Should be $true` ought to be equivalent to `$a | Should beOfType 'a'` but they differ when `[a]` is a PowerShell class.

**Comment by dlwyatt** [comment]
Might not be anything we can do about that.  The PowerShell team deliberately isolated class definitions into the scope of the script or module that defined them; Pester can't resolve the `[a]` type, but the test script can.

**Comment by alx9r** [comment]
Yep.  I see what's happening now.  I don't think this is worth pursuing because passing the type to `Should` works fine:

````PowerShell
Describe describe {
    class a {}
    $a = [a]::new()
    It 'succeeds' {
        $a | Should beOfType ([a])
    }
}
````
