### ISSUE TITLE
ItemNotFoundException in Exit-MockScope

### ISSUE THREAD

**Issue by splatteredbits** [pester/Pester#627]
PowerShell 5/Windows 7 & PowerShell 4/Windows 2012 R2

Pester 3.3.14 and 3.4.3 (stack trace below is from 3.4.3):

I'm getting an ItemNotFound exception. I have no idea what the root cause is.

> [-] Error occurred in test script '.\Tests\Initialize-WhsHgRepository.Tests.ps1' 95ms
>    ItemNotFoundException: Cannot find path 'Function:\PesterIsMocking_Update-HgRepository' because it does not exist.
>    MethodInvocationException: Exception calling "Remove" with "4" argument(s): "Cannot find path 'Function:\PesterIsMocking_Update-HgRepository' because it does not exist."
>    at <ScriptBlock>, F:\Build\WhsInitCrew\Arc\Pester\Functions\Mock.ps1: line 715
>    at Invoke-InMockScope, F:\Build\WhsInitCrew\Arc\Pester\Functions\Mock.ps1: line 1096
>    at Exit-MockScope, F:\Build\WhsInitCrew\Arc\Pester\Functions\Mock.ps1: line 742

I have two tests scripts. Test script #2 is failing. The failure started when I added four mocks to test script #1 for a total of 26 mocks. In my efforts to reproduce, if I removed any one call to `Mock` from script #1, the error went away. Each script, when run separately, pass. It is only when I run them together that I get this error.

**Comment by dlwyatt** [comment]
I'd like to see a repro of this before merging the PR.  There's a bug somewhere in Pester that would even allow you to reach that state, and adding the `if` statement around it is just sweeping the original problem under the rug.

**Comment by splatteredbits** [comment]
Here is the code to reproduce the problem. Unzip, import Pester, move into the `Pester-627` directory, and run:

```
Invoke-Pester .\Tests\Initialize-Computer.Tests.ps1, .\Tests\Initialize-WhsHgRepository.Tests.ps1
```

[Pester-627.zip](https://github.com/pester/Pester/files/551461/Pester-627.zip)
