### ISSUE TITLE
weird "Should Not Be Null"

### ISSUE THREAD

**Issue by rs38** [pester/Pester#630]
```
Describe "Docker is installed" {
 $service = Get-Service | Where-Object {($_.Name -eq "Docker") -or ($_.Name -eq "com.Docker.Service")}
    It "A Docker service is installed - 'Docker' or 'com.Docker.Service' " {
        write-warning " is not null: $($service -ne $null)"
        # $service | Should Not BeNullorEmpty
        $service | Should Not Be Null
}
```
returns:
```
Describing Docker is installed
WARNING:  is not null: False
 [+] A Docker service is installed - 'Docker' or 'com.Docker.Service'  23ms

```
Did I get it wrong?
if `Null` in an unknown perster keyword, it should complain somehow.
This leads to a lot of false positives.
(BeNullorEmpty behaves as expected)

**Comment by dlwyatt** [comment]
In this case, "Null" is a string.  You want the automatic variable `$null` here.

**Comment by rs38** [comment]
...which also does not work as expected there

**Comment by rs38** [comment]
@dlwyatt  
obviously no error, but I´m still not quite happy with mixing strings and keywords, which will very probably opens many pitfalls.
