### ISSUE TITLE
First test execution time includes time spent on BeforeAll operations

### ISSUE THREAD

**Issue by ymarushchenko** [pester/Pester#632]
Hello!

I have a test with 'BeforeAll' block and one 'It' block that runs repeatedly within a ForEach-Object loop with different test data.
'BeforeAll' block contains WebDriver initialization operations (I use Selenium to test something on web pages) and it takes about 30-40 seconds.
Each test that is executed within 'It' block is very fast and takes up to 100 milliseconds.

But in Pester report I see that 'BeforeAll' block execution time is added to first test, thus showing wrong numbers, e.g.:

```
Describing Schedule
   Context Broadcasts
    [+] RADIO network broadcasting on October 29, 2016 between 1:00 PM and 6:00 PM during tournament 1 is present on page 32.08s
    [+] RADIO network broadcasting on October 29, 2016 between 2:30 PM and 5:30 PM during tournament 1 is present on page 94ms
    [+] TV network broadcasting on October 29, 2016 between 8:30 PM and 10:30 PM during tournament 1 is present on page 11ms
    [+] TV network broadcasting on October 29, 2016 between 9:30 AM and 2:30 PM during tournament 2 is present on page 8ms
    [+] TV network broadcasting on October 29, 2016 between 11:00 PM and 4:00 AM during tournament 2 is present on page 11ms

```

The first test shows 32.08s, whereas the other four tests show real numbers.

Is it a bug?

**Comment by megamorf** [comment]
Yeah, I've run into this issue as well when I have to enumerate a lot of registry keys in BeforeAll the first test will usually show something like 20 seconds whereas the rest just take a few milliseconds.

@ymarushchenko I'd actually be interested in seeing that Pester Selenium integration because I've wanted to look into that for while now.

**Comment by dlwyatt** [comment]
Ironically, this was the fix to another bug report, that the times logged for the tests were not anywhere close to the actual time taken (because the `It` blocks are generally a very low percentage of the total test time, overall.)

**Comment by ymarushchenko** [comment]
@megamorf Using Selenium WebDriver with PowerShell is pretty straightforward after adding WebDriver DLLs with Add-Type cmdlet.
How can I contact directly here to explain the details? It would be an off-topic in this thread.

**Comment by megamorf** [comment]
@ymarushchenko Github doesn't have PMs but I've invited you to gitter: https://gitter.im/PS-Selenium/Lobby (sign in with your github account).

**Comment by fireflycons** [comment]
Late comer to the party here, but it seems that the time reported for the first test in any context includes all the time required to set up the describe, context, anything else that is initialised prior to the first 'It'

**Comment by nohwnd** [comment]
In v5 the time spent running user code and the time spent running framework code is counted separately, in the output object you find Duration (time in user code in this and child blocks), FrameworkDuration (time in framework code in this and child blocks), DiscoveryDuration (time spent discovering this block), and it would also be possible to calculate time spent running just this block but not the children, but that is not a very useful metric so I am not adding it right now.
