### ISSUE TITLE
Test Counts in Console output do not Match TeamCity's Count

### ISSUE THREAD

**Issue by alx9r** [pester/Pester#633]
I've noticed that the test count in the Pester console output does not match the test count seen in the TeamCity UI.  For example, [this Pester build log counts 446 tests](https://build.powershell.org/viewLog.html?buildId=6041&buildTypeId=Pester_TestPesterOnPowerShellV5&tab=buildLog#_focus=28&state=28)

![image](https://cloud.githubusercontent.com/assets/11237922/20123529/d5a3b980-a5c3-11e6-8bad-b0602dbaa3fd.png)

[while the overview tab for the same build counts 338 tests](https://build.powershell.org/viewLog.html?buildId=6041&buildTypeId=Pester_TestPesterOnPowerShellV5&tab=buildResultsDiv):

![image](https://cloud.githubusercontent.com/assets/11237922/20123516/bd07d67c-a5c3-11e6-9eb6-8f2f64f989f3.png)

I see a similar discrepancy on my ToolFoundations project. For that project the corresponding test counts on AppVeyor do match.  

What is the source of the discrepancy on TeamCity?

**Comment by dlwyatt** [comment]
If I remember correctly, TeamCity lumps together any tests with duplicate names.

**Comment by alx9r** [comment]
Yes.  That is it.  There is a view option called "tests without grouping by name" which, once selected, shows the correct count.

Thanks @dlwyatt.

**Comment by AlexanderKol** [comment]
Please tell me where this setting is?

**Comment by alx9r** [comment]
@AlexanderKol It's a setting on the TeamCity CI server:
![image](https://cloud.githubusercontent.com/assets/11237922/25092819/33d91a10-2344-11e7-9cb0-3bce55689544.png)

**Comment by AlexanderKol** [comment]
@alx9r Thank you so much

**Comment by alx9r** [comment]
You're welcome.

**Comment by RickRauch** [comment]
Is there any way to make "tests without grouping by name" the default for reporting results on the Overview screen?

**Comment by it-praktyk** [comment]
Did you try https://github.com/equelin/format-pester ? The Format-Pester is available in Powershell Gallery too.

The currently released version support passed/failed tests but in my devel branche you can find some new features e.g. support for skipped, pending, inconclusive tests.
