### ISSUE TITLE
Create pester contribution guide

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#636]
The process of proposing a new feature to Pester and implementing it through PR needs to be better described to avoid handing out partial information in every PR that proposes a new feature. @adbertram already summed up some of the process in this wiki article https://github.com/pester/Pester/wiki/Contributing-to-Pester and I plan to continue expanding on that. Just from the top of my head I'd say we need: Reporting a bug, Proposing a new feature, Implementing a bug fix, implementing new feature, publishing functions from Pester, making sure tests pass, and then describe how the code is tested on TC and that some of the tag tests may fail. Anything else?

**Comment by it-praktyk** [comment]
Maybe creating a template for issue - like described [here](https://github.com/blog/2111-issue-and-pull-request-templates) is a good idea?

A proposed template content
- information about what data is necessary to report bug
- link to [Contributing to Pester](https://github.com/pester/Pester/wiki/Contributing-to-Pester)

**Comment by nohwnd** [comment]
The pull request template would be also nice, the contribution guide seems comprehensive enough as is.

**Comment by it-praktyk** [comment]
The pull request template is currently on place - https://raw.githubusercontent.com/pester/Pester/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by nohwnd** [comment]
Ok, closing :)
