### ISSUE TITLE
Enable the ability to change properties on objects from New-MockObject

### ISSUE THREAD

**Issue by adbertram** [pester/Pester#640]
I'm not sure if this is possible but it would be nice to be able to set property values on mocked objects returned from New-MockObject. As-is, since New-MockObject returns an actual object back, it enables all property attributes like ReadOnly. It would be nice to be able to override this behavior and set your own property values.

**Comment by dlwyatt** [comment]
It can be done with Reflection, I think.

```posh
$foo = New-MockObject 'Foo'
$foo.GetType().GetField('Bar', 'Instance,NonPublic').SetValue($foo, 'New Value')
```

**Comment by nohwnd** [comment]
I already did some prototyping on this, but I don't have the code on me. It's not always easy to set the value, but in the easiest cases it's as simple as the code that Dave posted. The `Type` type has `GetProperties()` and `GetFields()` methods (and their more specialized versions) which you can use to query the type metadata.

This would be the simple cases that we can accomodate easily with a familiar syntax: 
```powershell 
New-MockObject -Type "MyApp.User" -Data @{ Name = "Jakub"; }
```
```csharp
public class TheSimplestCase
{
	//this is a settable property
        //we simply set it through the property info
	public string Name { get; set; }
}

public class WithReadonlyAutoProperty
{
	//this property is readonly (check be .CanWrite on the PropertyInfo object)
        //we can find the the automatic backing field "<{Name}>k__BackingField" and set that
	public string Name 	{get; private set;}
}

public class WithReadonlyPropertyBackedByAField
{
	//this is a field, fields are always settable	
        //notice it's missing the {get;set;} that's what distinguishes it from a property
	private string _name;

	//in this case we need to find the field that backs the property and 
        //set it. we can do that based on convention, and user can also specify the name
        //directly
	public string Name
	{
		get { return _name; }
		private set { _name = value; }
	}
}
```

**Comment by nohwnd** [comment]
There is a whole set that I forgot to mention, and that is objects that do some other stuff in the property, or delegate the property to another object. Such as the `System.Process`, setting just the name there is a nightmare, you need to pass checks, have the correct state and so on. And since we are not using any of the object constructors we don't have any of the objects to delegate to and lot of other problems. We need to go knees deep in the assemblies, so these need to be implemented via custom code.

**Comment by nohwnd** [comment]
@adbertram I can write the code if you have some objects I can work with, and properties to fill, should be no problem.

**Comment by adbertram** [comment]
@nohwnd The object I was wanting to do this on was System.IO.FileInfo. It would be a good idea to define some examples of which types would work with Dave's method and which do not.

I'm no .NET developer but is there not a way to "convert" all of the properties to simple read/write strings. I realize I'm probably way oversimplifying this. :)

**Comment by dlwyatt** [comment]
For fields, this method should always work.  For properties, it's anybody's guess (depends on how the class is written.)  There's not really a way to make a one-size-fits-all solution there.

**Comment by nohwnd** [comment]
Tried to do it on the FileInfo, I succeeded to populate the Name and the Path, but to populate Length and Exists, which are also very interesting properties, I would need to do so much more than just finding the field and settings it. There are internal objects that would need to be mocked etc. So I suggests to continue on this, but only settings a minimal set of usecases that are suported: 

- Populate are writable public properties of a given name
- Populate all (internal and public) fields of a given name
- strip underscore from the field name and populate it (to match the standard backing field convention)
- (also be able to specify field that starts with underscore)
- look for autoimplementing fields for a property

- Write errors, but continue to next member

and that's it. There is not much more that we can provide to work reasonably well without the user reading the source code and figuring what needs to be done for himself/herself. Here is a quick prototype of a function that does most of the stuff, I will clean it up and implement the rest if you think it's worth it.
```powershell
function New-MockObject {
    param (
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [type]$Type,
        [hashtable]$Data = @{}
    )

    $obj = [System.Runtime.Serialization.Formatterservices]::GetUninitializedObject($Type)
    if ($Data.Count -eq 0) {
      return $obj
    }
    
    $properties = $Type.GetProperties()
    $fields = $Type.GetFields(([Reflection.BindingFlags]::Instance -bor [Reflection.BindingFlags]::NonPublic))
    
    foreach ($field in $fields | where {$Data.Keys -contains ($_.Name.TrimStart("_"))})
    {
      try {
        $field.SetValue($obj, [Convert]::ChangeType(($Data[$field.Name.TrimStart("_")]), $field.FieldType))
      }
      catch {
        Write-Error -ErrorRecord $_
      }
    }
    
    
    foreach($property in $properties | where {$Data.Keys -contains $_.Name})
    {
      if ($property.CanWrite)
      {
        try {
            $property.SetValue($obj, [Convert]::ChangeType($Data[$property.Name], $property.PropertyType))
        }
        catch {
          Write-Error -ErrorRecord $_
        }
      }
      else {
        $field = $fields  | where {  $_.Name -eq ("_" + $property.Name)}
        
      }
    }
    
    $obj
}


$foo.GetType().GetProperties() | select name, canwrite
"===="
$foo.GetType().GetFields([Reflection.BindingFlags]::Instance -bor [Reflection.BindingFlags]::NonPublic -bor [Reflection.BindingFlags]::Public) | select name

$foo = New-MockObject -Type ([IO.FileInfo]) -Data @{  
  dataInitialised = 1
  Length = 100
  FullPath = "C:\temp\file1.txt" #field in base class -> maybe support "PropName:FieldName = value" for overriding
  Name = "file1.txt"  # readonly property backed by _name
  IsReadonly = $false  # writable property but fails with nullref
  LastWriteTime = (Get-Date).AddDays(-10) #fails with cannot find file
}

$foo | fl
```

**Comment by adbertram** [comment]
I'd say implement this as long as it doesn't throw an exception. Ie, try to
mock the object, attempt to build it in a way so properties are writable
and, if all the properties aren't writable, then just return the original
object.

**Comment by nohwnd** [comment]
That's not something you can do. You cannot change the property from readonly to writable, all you can do is populating the field that backs the property with some value. Technically speaking properies by themselves do not hold any value,because a property called Name is just a syntactic sugar for a get_Name and set_Name *methods*, that methods get and set a value to a field. So all you can really do is set the fields. That is the easy part. The hard part is tricking the getter and setter code to actually get through all the guarding code that assures the object is in a correct state.

**Comment by adbertram** [comment]
I figured it would be something like that. This is probably not really
doable.

**Comment by nohwnd** [comment]
I think you misunderstood me. I was saying that changing the shape of a type (changing it's properties from read only to writeable) is not possible. I was no saying that populating the fields/properties of an object, is impossible. I still think it's worth it to implement this, even with the described set of capabilities.

**Comment by adbertram** [comment]
I see.

**Comment by nohwnd** [comment]
I originally re-opened this so I can track the conversation better, but there was nothing more to discuss. I am closing it again.
