### ISSUE TITLE
Feature Request: get just the failures

### ISSUE THREAD

**Issue by SteveL-MSFT** [pester/Pester#645]
Two options:

1) Get-PesterFailures cmdlet similar to https://github.com/PowerShell/PowerShell/pull/2600 to parse the log
2) Invoke-Pester -ShowFailuresOnly (passing tests can be shown in progress bar)

When there is a large number of tests and I'm working on a PR, I really just want to see which ones failed so I can investigate those failures.

**Comment by iSazonov** [comment]
As far as I understand this code already tested and it was great to do a quick transfer into Pester.
PSPester guys please help.

**Comment by nohwnd** [comment]
@SteveL-MSFT Do I understand correctly that you want an option that will print only the red messages (and i guess describe context info) *to the screen*, but will keep the output object that you get through `-PassThrough` unchanged? 

In that case I would implement it as a more general parameter `-Show` that would take [flags](http://stackoverflow.com/questions/8447/what-does-the-flags-enum-attribute-mean-in-c) from this set `Passed, Failed, Pending, Skipped, Describe, Context, Summary, Default = All, Fails = Failed, Describe, Context, Summary`, that would enable you to specify -Show "Fails" to get what you requested, while enabling others to select what they want to see, and it should also be quite simple to implement.

**Comment by nohwnd** [comment]
#568

**Comment by nohwnd** [comment]
@iSazonov The code in the linked PR is operating at the end of the pipeline where you already have the xml output. See [my comment under the PR](https://github.com/PowerShell/PowerShell/pull/2600#issuecomment-261486201) that explains why I don't think this is the best approach to tackle this request.

**Comment by iSazonov** [comment]
@nohwnd Thanks for the quick response and excellent advice!
Would be perfect to implement your proposal in Perter!

**Comment by nohwnd** [comment]
@iSazonov @SteveL-MSFT @juneb Could you please give the output filtering a quick test before I merge it?

**Comment by iSazonov** [comment]
I am out of office but if I understand you correctly you can download XMLs from [here](https://ci.appveyor.com/project/PowerShell/powershell/build/artifacts).

**Comment by nohwnd** [comment]
@iSazonov @SteveL-MSFT @juneb released in 3.4.5

**Comment by iSazonov** [comment]
@nohwnd Many thanks!
