### ISSUE TITLE
What, exactly, does Pester ship with?

### ISSUE THREAD

**Issue by alx9r** [pester/Pester#649]
I'm trying to figure out what, exactly, Pester ships with.  I've read that [pester is included in Windows 10](https://blogs.technet.microsoft.com/heyscriptingguy/2015/12/14/what-is-pester-and-why-should-i-care/) but that was just a vague statement made in passing.  I've also [seen it implied that Pester is included in WMF](https://msdn.microsoft.com/en-us/powershell/wmf/5.1/scenarios-features), but it's not clear to me which WMF versions that applies to.  This all leaves me with the following questions:

* Which OS distributions include Pester?
* Which WMF distributions include Pester?

Thanks for your help,

Alex

**Comment by dlwyatt** [comment]
It definitely ships with Windows 10.  I believe that the standalone WMF packages also started including it with either 5.0 or 5.1, but would have to double check that.  (And since I run Windows 10, I rarely have to use those packages.)

**Comment by alx9r** [comment]
Thanks @dlwyatt.  FWIW, it doesn't seem to be present on fresh Windows 8.1 computers with WMF 5.0 installed.
