### ISSUE TITLE
Session corruption related to import-module, mock, and classes.

### ISSUE THREAD

**Issue by mpbarano** [pester/Pester#650]
Pester version     : 3.4.3 C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.3\Pester.psm1
PowerShell version : 5.1.14393.206
OS version         : Microsoft Windows NT 10.0.14393.0

I have found a strange interaction related to import-module, mock, and classes. I am trying to test a module with a class. I want to mock a C# dependency. I am extracting that dependency as a function. This method works, but after the script runs the first time and I reimport the module into the same session, the mock call doesn't work. To get it to work again, I need to change the byte size of the module and import the file again. Force import does not help. Changing the file time doesn't matter. File size does. I haven't tried to see if same file size but different content works. 

Here is a clean module and test that demonstrates an initial successful import, a re-import with a failure, and a re-re-import with success. It is necessary that that import statements occur in separate describe blocks. import-module or updating the file in the same describe block won't trigger or repair the error. The context blocks do not impact the behavior.

There are 2 files. Put them in the same directory and run Invoke-Pester or Invoke-Pester .\Nothing.Tests.ps1.

Nothing.psm1:

```
class NothingClass {
    [string] RunACmdlet() {
        return Get-SomeString
    }
}

function Get-SomeString() {
    throw New-Object Exception "You may not have a string unless you know how to mock me."
}

function Get-Nothing() {
    return [NothingClass]::new()
}

Export-ModuleMember -Function Get-Nothing
```

Nothing.Tests.ps1
```
Function Update-NothingFile {
    Write-Host "File size was $((ls .\Nothing.psm1).Length)."
    Add-Content .\Nothing.psm1 "`n"
    Write-Host "File size is $((ls .\Nothing.psm1).Length)."
}

Describe "First import of module with a fresh byte size." {
    Context "First import." {         
         Update-NothingFile
         import-module -Force .\Nothing.psm1
         Mock -ModuleName Nothing Get-SomeString { return "You may have a string." }

         $nothing = Get-Nothing
         it "should not throw an exception because everything is clean" {
            {$nothing.RunACmdlet()}| should not throw
         }
    }

    Context "Second call without an import" {
         
         Mock -ModuleName Nothing Get-SomeString { return "You may have a string." }

         $nothing = Get-Nothing
         it "should not throw an exception because everything is still clean" {
            {$nothing.RunACmdlet()}| should not throw
         }
    }
}
Describe "Reimport but don't update the byte size of the module." {
    Context "Second import. 3rd Test." {

         import-module -Force .\Nothing.psm1

         Mock -ModuleName Nothing Get-SomeString { return "You may have a string." }

         $nothing = Get-Nothing
         it "should throw an exception because we have corrupted the session somehow" {
            {$nothing.RunACmdlet()}| should throw "You may not have a string unless you know how to mock me."
         }

    }
}
Describe "Updating the file will clean this up." {
    Context "Third import. Fourth Test." {
         Update-NothingFile
         import-module -Force .\Nothing.psm1
         Mock -ModuleName Nothing Get-SomeString { return "You may have a string." }
         
         $nothing = Get-Nothing
         it "should not throw an exception because it is cleaned up again." {
            {$nothing.RunACmdlet()}| should not throw
         }

    }

}
```

**Comment by dlwyatt** [comment]
That was my observation as well, when I started looking into testing classes with Pester.  The problem is that the class is still caching a reference to the originally imported module, even though you've run Import-Module again with -Force.  My recommendation is to run these sorts of tests using Start-Job, so you get a clean runspace every time.

**Comment by mpbarano** [comment]
Thanks. I had thought of running a separate powershell for tests. Running each describe block in Start-Job does work and it is a pretty clean way to run the tests with only minor additional code. How certain are you that the problem is that the class is caching a reference? How do you know? 

An additional odd detail that is leading me in a different direction: if I run the tests without force on the subsequent import, nothing breaks. I seem to need to call import of a module with the class, mock a function in the class, import -force the module again to replicate the error. It seems more likely that Pester is caching a reference to the wrong function. Maybe if I were to force import Pester or something similar I could fix the problem? I am going to see if I can come up with a way to get Pester to drop any state it is holding.

**Comment by dlwyatt** [comment]
When you run `Import-Module` without `-Force` on a module that's already loaded, nothing happens.

Pester doesn't cache anything.  :)  When I was investigating this, I dug through the PowerShell engine with ILSpy (this was back before the source code was available on GitHub), and wrote a bunch of demo code to send the report on to Microsoft.

Here's the simplest way to reproduce it:

```
# TestModule.psm1:

class MyClass
{
    [object] GetSessionState() {
        return (Get-Variable ExecutionContext -ValueOnly).SessionState
    }
}

function Get-SessionState {
    return $ExecutionContext.SessionState
}

# test.ps1, in the same directory:

using module .\TestModule.psm1

param ([switch] $PerformModuleImport)

if ($PerformModuleImport) { Import-Module $PSScriptRoot\TestModule.psm1 -Force }

$loadedModuleState = Get-SessionState
$object = [MyClass]::new()
$classSessionState = $object.GetSessionState()

Write-Host "States equal?  $($loadedModuleState -eq $classSessionState)"
```

In a clean PowerShell session, run test.ps1 as many times as you like without using the -PerformModuleImport switch, and the session states reported by the PowerShell function and the class will be the same.  (This is when mocking works from Pester.)

Run it once with the switch, and that session is forever broken.  When you call methods on the class, the class is still keeping a reference to the original module / session state from when it was first added, which is not the same as what's active in the rest of the module (and as what you get when you call Get-Module).

**Comment by mpbarano** [comment]
Thanks for this test code. It proves your case and I haven't been able to find anyway to get the class to reload or release its internal context. It seems that in many contexts it makes sense to run powershell inside of Start-Job to get clean start up and tear down.

I +1 both your comments. I will close the thread.
