### ISSUE TITLE
Mock should return a mock object that can be reused with Assert-Mock called

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#653]
I'd find it really useful if a call to Mock returned an object that enabled me to refer back to the mock. That prevents errors in typing the command name, as well as the filter. All the unused mock results would be output to $null, so the change is not breaking.

Usage: 
```powershell
# -- Arrange
#default mock here for "protection", I don't care about reusing this one
mock Test-Connection 

$dummy = "dummyComputer"
$m = mock Test-Connection -ParameterFilter { $ComputerName -eq $dummy } 

# -- Act
# ... test code here

# -- Assert
# this will reuse the name of the command and the filter
$m | Assert-MockCalled -Exactly 1 -Scope It

# same thing with the current syntax
Assert-MockCalled Test-Connection -ParameterFilter { $ComputerName -eq $dummy }  -Exactly 1 Scope It
```

**Comment by nohwnd** [comment]
I tried to implement this, and it's simple, but the CommandName parameter has position 0, and so the value `20` will become the `$CommandName` when I do `$m | mock -Exactly 20`, which is a form some people use. The problem is that `-Exactly` is a switch with no position, and the 20 actually binds to `-Times` which has parameter position 1. So the `-Exactly 20` is an illusion, but it's the way people (including me) are using the function.

I don't want to introduce a breaking change this would need to move to v4, and I will have to think about how should I set up the parameters to keep the impact minimal. 

Unless you have some clever way of overcoming this parameter binding problem @dlwyatt ? :)  

related commits: a15aafefdfc4b30918bc6a4886135d55810dce6b 6d041e95b7785b591851449dc3f92ac8e0205bbb

**Comment by dlwyatt** [comment]
Instead of binding by property name, you could add a new parameter set that takes pipeline input (by value).  That parameter set wouldn't have CommandName, ModuleName or ParameterFilter options.

**Comment by Jaykul** [comment]
I think we still want to be able to override the parameter filter, so that we can still write tests like this:

```powershell
Mock Invoke-Thing { }

It "Calls Invoke-Thing with the right parameters" {
    # ...
    Assert-MockCalled Invoke-Thing -Times 1 -Exactly -ParameterFilter { $Name -eq "ExpectedName" }
    Assert-MockCalled Invoke-Thing -Times 0 -Exactly -ParameterFilter { $Name -ne "ExpectedName" }
}
```

**Comment by nohwnd** [comment]
You could still do that. Outputting the mock settings was meant to be an addition, not a replacement for the current syntax.

**Comment by nohwnd** [comment]
This does not seem practical anymore. Most Mocking I do I do by defining a single mock, and asserting on it with filter, so the amount of duplicated info is minimal. Closing.
