### ISSUE TITLE
Should Throw: ability to indicate expected type of exception

### ISSUE THREAD

**Issue by cheretbe** [pester/Pester#659]
It would be nice to have the ability to indicate not only an expected message, but also an exception type in **Should Throw**.
Like this, for example:
``` powershell
{ throw [System.IO.FileNotFoundException] "file not found" } | Should Throw [System.IO.FileNotFoundException]
```
The same error might be represented by different messages on systems with different localizations and using exception type could come in quite handy.

**Comment by nohwnd** [comment]
please see #279

**Comment by cheretbe** [comment]
Ah! Ok, thanks.
