### ISSUE TITLE
Suggestions needed Please !!!

### ISSUE THREAD

**Issue by nagaraj1993** [pester/Pester#660]
Hi Team,

I am currently a novice in this Pester. And I have a requirement to write unit tests for Powershell scripts using Pester. I am able to do it fine with psm1 files. But I also have ps1 files that does not have any functions with it and has param() which directly invokes another ps1 script. I am not able to pass or set the paramaters to the file(first ps1 script) that it invokes the another script with different parameters. I used Set-variable and quite a few stuffs but does not work. It says "not recognised as a cmdlet . . ."

**Comment by davidwallis3101** [comment]
can you post an example of the script and how you are calling it, showing what the issue is that you are having??

When you start to use pester this demonstrates a perfect example of why you should break tasks down into functions. :)
