### ISSUE TITLE
using tags causes warnings in TFS publish test results

### ISSUE THREAD

**Issue by davidwallis3101** [pester/Pester#663]
I invoke a load of pester scripts in parallel as part of a CI build in visual studio, using TFS variables I am able to then pass the pester tags through to control which tests do or don't run.

If a test has applicable tags then it runs and publishes fine.

If there are no applicable tabs, the test launches but runs nothing and the output causes TFS to throw warnings such as:

`2016-12-19T17:35:46.4900856Z ##[warning]Invalid results file. Please make sure the Test Result Format field in the task matches the result format of the file: C:\agent\_work\2\s\artifacts\Test-xxxxxxxxxx.tests_Pester.XML`

Looking at the resuilts file, there is just no results - just `<results />` which tfs obviously doesnt like..

My first thought was to have a test that runs regardless of tags to put one result in, but I cant do a test without a describe block - which would then not work with the tags.. 

Short of deleting files that just contain <results /> prior to publishing has anyone any suggestions?

The code I am using to invoke the tests is:

```
<#
.SYNOPSIS
    Used for Invoking pester tests in parallel

.DESCRIPTION
    Used for Invoking pester tests in parallel

.EXAMPLE
    Example: <script.ps1>

.NOTES
    <snipped>

.LINK
    <snipped>
#>

[CmdletBinding()]
param()

Write-host "Powershell Version: $($PSVersionTable.PSVersion), CLR Version: $($PSVersionTable.CLRVersion)"

# Create the artifacts folder if not present
if (!(Test-Path -Path "./artifacts" )){ $null = New-Item -ItemType directory -Path "./artifacts"}

# Dot source the invoke-parallel script
. ".\AutomatedBuilds\Invoke-Parallel\Invoke-Parallel\Invoke-Parallel.ps1"

#Get the test Files
$Tests = Get-ChildItem ".\IntegrationTests\Tests" -Filter "*.tests.ps*"

#invoke in parallel
$Tests | Invoke-Parallel -ScriptBlock {

    Import-Module "C:\Program Files\WindowsPowerShell\Modules\Pester\pester" -ErrorAction Stop

    [string[]]$Tags = $ENV:PESTER_TAGS.Split(",")

    Write-Host ("Invoking Test File: {0}" -f $_.FullName)
    Invoke-Pester `
        -Script $_.FullName `
        -EnableExit `
        -OutputFile "./artifacts/Test-$($_.BaseName)_Pester.XML" `
        -OutputFormat NUnitXml `
        -Tag $Tags `
        -ExcludeTag $ENV:PESTER_EXCLUDETAGS
 }
```

**Comment by nohwnd** [comment]
@davidwallis3101 any idea how we could solve this? If there are no matching tests to run, there won't be anything reasonable in the file. Is TFS collecting the .XML files automatically? Maybe you could filter the files before it takes it and delete the empty ones?

**Comment by davidwallis3101** [comment]
I got around it by having a step in the build that runs the following:

```powershell
# Remove Tests with no results
(Get-ChildItem $ENV:BUILD_SOURCESDIRECTORY\Artifacts\*Pester.XML | Select-String -Pattern "<results />" | Select-Object -ExpandProperty path -Unique) | ForEach-Object{Remove-Item -Force -LiteralPath $_}

```

I'm not sure if its an issue other people are seeing? I guess VS Online should exhibit the same behaviour.

to reproduce, create multiple test files and tag one file with say

```powershell
Describe "something" -Tag "runme" {
    Context "blah" {
        it "something" { $true | should be $true }
    }
}
```

and the other with 

```powershell
Describe "something" -Tag "DontRunMe" {
    Context "blah" {
        it "something" { $true | should be $true }
    }
```

Then invoke all tests with the tag runme

**Comment by davidwallis3101** [comment]
To add the test results in my usage are ending in Pester.XML so alter for your environment if you are having the same issue.

All i am basically doing is looking for the files with the <results /> attribute in them that it complains about and then removing them - use at your own risk :)

**Comment by nohwnd** [comment]
This can be worked around, and since then we are adding more xml tags above the test-suite I think. Closing this because OP needs no fix .
