### ISSUE TITLE
Update pester version on Powershell Gallery to 3.4.4

### ISSUE THREAD

**Issue by dimapasko** [pester/Pester#664]
Hi.

Current Pester version is 3.4.4 (according to https://github.com/pester/Pester/blob/master/Pester.psd1)

On Powershell Gallery latest published version is 3.4.3
https://www.powershellgallery.com/packages/Pester/

Could this version be updated?

**Comment by nohwnd** [comment]
@dlwyatt something went wrong somewhere with publishing. You know all about that, could you have a look please?

**Comment by dlwyatt** [comment]
There's no 3.4.4 tag; that's needed for triggering a release from our build server.  (In addition to having v 3.4.4 in the changelog and module manifest.)

**Comment by nohwnd** [comment]
Ah, that would explain it. I remember tagging the version, so I must have forgotten to push the tags. Sorry, will fix that. And thanks. And happy new year!


Jakub Jareš

.NET, Pester, PowerShell
t 00420603800578<tel:00420603800578>
e me@jakubjares.com<mailto:me@jakubjares.com>
t @nohwnd

30. 12. 2016 v 18:46, Dave Wyatt <notifications@github.com<mailto:notifications@github.com>>:


There's no 3.4.4 tag; that's needed for triggering a release from our build server. (In addition to having v 3.4.4 in the changelog and module manifest.)

**Comment by toddbrownmcis** [comment]
Any progress on this issue yet?

**Comment by nohwnd** [comment]
I tagged the version but it does not release it when you tag it afterwards. I will need to release 3.4.5, maybe I can do that today.


Jakub Jareš

.NET, Pester, PowerShell
t 00420603800578<tel:00420603800578>
e me@jakubjares.com<mailto:me@jakubjares.com>
t @nohwnd

6. 1. 2017 v 16:38, Todd Brown <notifications@github.com<mailto:notifications@github.com>>:


Any progress on this issue yet?

**Comment by nohwnd** [comment]
@dimapasko 3.4.5 is released

**Comment by nohwnd** [comment]
cc @toddbrownmcis
