### ISSUE TITLE
Not all parameters available after mocking New-ADGroup on Win7

### ISSUE THREAD

**Issue by danielboth** [pester/Pester#671]
Mocking New-ADGroup on Windows 7 (and possibly W2008R2) does not mock all parameters available on the New-ADGroup cmdlet. Code to test:

```PowerShell
$Parameters = (Get-Command New-ADGroup).Parameters.GetEnumerator() | ForEach-Object {
    @{'Parameter'=$_.Key}
}

Describe 'Mock New-ADGroup' {
    Mock New-ADGroup

    $mockedParameters = (Get-Command New-ADGroup).Parameters.GetEnumerator() | ForEach-Object Key
    
    It 'Parameter <parameter> is present' {
        Param (
            [string]$Parameter
        )

        $mockedParameters -contains $Parameter | should be $true
        
    } -TestCases $Parameters
} 
```

The following list of parameters is not available on Win7 (tested with PowerShell 5.0 RTM):
[-] Parameter GroupScope is present 9ms
[-] Parameter GroupCategory is present 15ms
[-] Parameter HomePage is present 17ms
[-] Parameter ManagedBy is present 19ms
[-] Parameter SamAccountName is present 16ms
[-] Parameter Name is present 20ms
[-] Parameter Description is present 14ms
[-] Parameter DisplayName is present 15ms

Tested on W2012R2 with PowerShell 5.0 as well, there it works fine, so seems to only affect older ActiveDirectory module.

**Comment by it-praktyk** [comment]
@danielboth, sorry for a lack of the previous reaction. Can you confirm that issue still exists in the newest version of Pester?

**Comment by it-praktyk** [comment]
Due to lack of additional information, the issue is closed now. Please feel free to open when you feel that your question or request was not handled correctly.
