### ISSUE TITLE
Add #requires -Version functionality

### ISSUE THREAD

**Issue by adbertram** [pester/Pester#675]
If I'm building tests with functions only available in a certain version of Pester, it'd be nice to be able to specify a required version or later option in my tests to ensure it fails before tests begin.

**Comment by dlwyatt** [comment]
This gets awkward in PowerShell v5, where multiple versions of a module can exist side-by-side on the system.  If you use `#requires -Module` with a different version of Pester than what's imported, PowerShell actually imports the second copy of Pester, at which point things just get silly.

We could add something like an `Assert-PesterVersion` command, but that would just fail if you have a version older than what's on the system.  (Or it would automatically load the more recent version, if you have side-by-side versions, leading to the weird situation again.)  Alternatively, just do something like this:

```posh
if ((Get-Module Pester).Version -lt [version]'3.4.5') { throw "Pester 3.4.5 or later is required." }
```

**Comment by it-praktyk** [comment]
I assume that the issue can be closed now. Feel free to reopen if you think your request has not been properly treated.
