### ISSUE TITLE
ScriptBlock feature in Pester

### ISSUE THREAD

**Issue by irwins** [pester/Pester#679]
Hi,

I was looking for a way to save pester results by invoking a scriptblock instead of a *.tests.ps1 file.

The test is defined in the the Scriptblock
```PowerShell
$sb = {
  Describe "Get-Hello" {
    It "does something useful" {
      $true | Should Be $false
    }
  }
}

$result = Invoke-Pester -ScriptBlock $sb -PassThru
```

This would make for easier access to Pester test without having to save it first to a *.tests.ps1 file which is currently the only way to run and save the results.

It makes your scripting effort in terms of discovery and delivery more straightforward.

**Comment by adbertram** [comment]
You don't have to save it to a *.Tests.ps1 file. You can invoke a Describe block just like you can a function.

**Comment by nohwnd** [comment]
```powershell
describe "abd" { it "abc" { "yrp" | should be "abc"}}
```
```
Describing abd
 [-] abc 258ms
   String lengths are both 3. Strings differ at index 0.
   Expected: {abc}
   But was:  {yrp}
   -----------^
   1: describe "abd" { it "abc" { "yrp" | should be "abc"}}
   at <ScriptBlock>, <No file>: line 1
```
Hehe, right, never thought about it this way.

**Comment by dlwyatt** [comment]
I don't remember if that still works in v4.  We had talked about giving up the ability to run code outside of Invoke-Pester, due to its limited usefulness and challenges in some of the v4 changes

**Comment by nohwnd** [comment]
Won't give you the test result object, which was one of the things Irwin mentioned when we discussed it on twitter.  I am not sure how usable this whole feature would be, but I asked on twitter.

**Comment by irwins** [comment]
I wanted to save the test results from within a class method by creating a scriptblock with the test.
& $sb works fine, I just won't be able to save it...

```PowerShell
    $this.ValidationResults = [PSCustomObject]@{
      ValidationDate = $(Get-Date)
      Results = Invoke-Pester -ScriptBlock $sb -Tag $tag -PassThru
    }
```

Rg./Irwin

**Comment by nohwnd** [comment]
This was recently merge in #972 and #1159. You can provide `-Script` parameter to `Invoke-Pester` to run without files. I will probably rename the parameter before release to something less confusing, because now it looks like `-Script` is what you provide the test files. Probably `-ScriptBlock` or `-Text` or something like that. See release notes of the next release. :)
