### ISSUE TITLE
Importing of Pester v4 from PowerShell Gallery

### ISSUE THREAD

**Issue by adbertram** [pester/Pester#693]
I also have 3.4.4 but unloaded it before attempting to import v4.

PS> rmo Pester
PS > ipmo Pester -RequiredVersion 4.0.0 -Force
```
Add-Type : Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path 'C:\Program Files\WindowsPowerShell\Modules\Pester\4.0.0\lib\Gherkin.dll' because it does not exist."
At C:\Program Files\WindowsPowerShell\Modules\Pester\4.0.0\Functions\Gherkin.ps1:3 char:16
+ Add-Type -Path "${Script:PesterRoot}\lib\Gherkin.dll"
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Add-Type], ParameterBindingException
    + FullyQualifiedErrorId : ParameterBindingFailed,Microsoft.PowerShell.Commands.AddTypeCommand

Add-Type : Cannot add type. The type name 'Pester.ClosingBraceFinder' already exists.
At C:\Program Files\WindowsPowerShell\Modules\Pester\4.0.0\Functions\SetupTeardown.ps1:272 char:1
+ & $SafeCommands['Add-Type'] -TypeDefinition @'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Pester.ClosingBraceFinder:String) [Add-Type], Exception
    + FullyQualifiedErrorId : TYPE_ALREADY_EXISTS,Microsoft.PowerShell.Commands.AddTypeCommand
```

**Comment by nohwnd** [comment]
Yes that is an issue with 4.0.0, I forgot that the packaging script for gallery is not using nuspec (and in 4.0.0 lib is not included in it either), it is fixed from the beginning in the 4.0.2 as mentioned in the RC announcement. So 4.0.2 is the version to use.

**Comment by adbertram** [comment]
OK, you definitely want to remove 4.0.0 from the Gallery, if possible. It
was second nature to do Install-Module Pester -RequiredVersion 4.0.0.

**Comment by nohwnd** [comment]
There are ~400 downloads of 4.0.2 and 60 of 4.0.0, and no-one reported it, so it does not seem to be a problem. Ypu cannot import 4.0.0 if ypu don't have it. Unless you were one of the 60 who got one of the broken versions. Anyway it's gone from the gallery.
