### ISSUE TITLE
4RC: Invoke-Pester -Show Describe, Failed produces output for every file name

### ISSUE THREAD

**Issue by Jaykul** [pester/Pester#705]
On our tests, if I run `Invoke-Pester -Show Describe, Failed -TestName $threeTests` I get hundreds of lines of "Executing script ..." (with full paths, that frequently wrap onto multiple lines) mixed into my output. I really wish I didn't get an "Executing Script" line at all when I'm running with a TestName filter, and the file in question doesn't contain any tests to be run.

Any chance we can just add "Script" to the enum, and change `Write-Describe` to validate the input is a valid enum, so that the first line of the Process block of Write-Describe could be:

```posh
        if(-not ( $pester.Show | Has-Flag $CommandUsed)) { return }
```

That way, you could -Show Script if you want to, and I could ... not ;-)

What I'm trying not to ask: I'm really in love with just doing `-Show Failed` but I would love if every failure (retroactively) printed the test name (and file?) if it hadn't been printed already ;-)

**Comment by nohwnd** [comment]
Yes, the list of options can be changed and this sounds reasonable. But is `Script` the best name? How about `Path`? Something else? They both seem quite non-descriptive.

As for what you are trying not to ask: That is how I originally wanted it to work as well, but it would need to keep track of what was already written to the screen, and I did not want to add that much logic around something which should be straightforward.

**Comment by Jaykul** [comment]
Yeah, `ExecutingScript` or something like that would be better -- I was going with "Script" just because it makes the fix to `Write-Describe` easier (the caller is already passing "Script"). To be honest, we'd probably have to review all the calls to `Write-Describe` anyway, so there's no harm changing it to the default English message...

**Comment by fflaten** [comment]
Pester v4 is no longer actively maintained and in Pester v5, the output has changed. Normal view will only output path of files with tests actually executed, however it won't output name of Describe-blocks. That requires `Detailed`-view which also enables more detailed discovery-logs that kinda still outputs all filepaths as they're processed and filtered during Discovery (related #1552).

Ready to close or did we just move the "issue" to Discovery-output in v5? 😄

**Comment by nohwnd** [comment]
I am going to close this. You now only get the file when tests are actually executed in the file. And with the changes discusses in the related issue, we will further reduce the output of the discovery to avoid listing all the files so a bigger testbases won't see a ton of output for the discovery.
