### ISSUE TITLE
[Pester 4.02] Empty hashtable no longer passes ShouldBeNullOrEmpty test

### ISSUE THREAD

**Issue by BrianFarnhill** [pester/Pester#709]
In previous versions of Pester the following test would pass fine, but in 4.02 we are seeing this fail

    Describe "test" {
        Context "test" {
            It "Should be empty" {
                @{} | Should -BeNullOrEmpty
            }   
        }
    }

This isn't a show stopping thing for me right now, we can adjust our tests - but I wanted to call it out in case it wasn't deliberate.

**Comment by nohwnd** [comment]
IMHO this should fall under the "Empty", will have a look.
