### ISSUE TITLE
[Pester 4.02] Bug in output where multiple Paths are passed in to -Scripts at Invoke-Pester

### ISSUE THREAD

**Issue by BrianFarnhill** [pester/Pester#710]
If you call Invoke-Pester with an array of hashtables passed to the -Scripts parameter like this:

    @(
        @{
            'Path' = "C:\path1"
            'Parameters' = @{ "Param" = "value 1" }
        },
        @{
            'Path' = "C:\path1"
            'Parameters' = @{ "Param" = "value 2" }
        },
        @{
            'Path' = "C:\path2"
            'Parameters' = @{ "Param" = "value" }
        }
    )

The output that you see at the start of the test run looks like this below:

> Executing all tests in System.Collections.Hashtable', 'System.Collections.Hashtable', 'System.Collections.Hashtable

The tests all still execute as they should, it's just that first line out output that is looking at the objects and not the Path property in each. 

To that end, could we do something with the output here to include the parameters as well? In the case of what I'm doing I'm actually running the tests in a single directory multiple times, but shifting the parameters on each (to point to a different stub module each time). So something more meaningful here would be useful.

**Comment by nohwnd** [comment]
Thanks. 

The same issue is already reported in #699.

Yes the output can be made better. Please report it as a new issue so I can add it to 4.1 milestone.
