### ISSUE TITLE
[Pester 4.0.2] Import-LocalizedData not in $script:SafeCommands 

### ISSUE THREAD

**Issue by it-praktyk** [pester/Pester#712]
I'm not sure if is it issue but the command Import-LocalizedData are not added to $script:SafeCommands and is invoked directly.

I see in a code that all (?) ordinary commands are called by 
```powershell
$script:SafeCommands['Get-WmiObject']
```
except Import-LocalizedData what is used in
- [Pester.psm1](https://github.com/pester/Pester/blob/master/Pester.psm1#L691)
- [Functions\Gherkin.ps1](https://github.com/pester/Pester/blob/master/Functions/Gherkin.ps1#L168)

Mentioned lines are also part of the pull request #711 

2017-03-31 - the links updated due to move V4 to the master branch and changed numbers of affected lines due to a code change.

**Comment by it-praktyk** [comment]
Thank you @nohwnd.

**Comment by nohwnd** [comment]
@it-praktyk no need to close this manually before the PR is merged. :)

**Comment by it-praktyk** [comment]
I didn't realize that it wasn't merged yet. Next time I'll try don't do things in my nap time ;-)
