### ISSUE TITLE
[Pester 4.0.2] The Turkey Test failed by the Be assertion

### ISSUE THREAD

**Issue by it-praktyk** [pester/Pester#713]
Under testing solution for the issue #708 I used method described by @mikefrobbins (thx Mike!) in the article [Using Pester to Test PowerShell Code with Other Cultures](http://mikefrobbins.com/2015/10/22/using-pester-to-test-powershell-code-with-other-cultures/).

The one test provided below failed for the tr-TR culture.

```powershell
PS > Use-Culture -ScriptBlock { invoke-pester } -Culture tr-TR
    [-] Compares arrays with correct case-insensitive behavior 31ms
      Expected: {1 2 3 4 I AM A STRİNG}
      But was:  {1 2 3 4 I am a string}
      at line: 34 in C:\Users\<SOME DIRECTORY>\Pester\Functions\Assertions\Be.Tests.ps1
      34:             $array | Should Be $arrayWithCaps
```

Could you look on this?

**Comment by nohwnd** [comment]
@it-praktyk Is this problem limited to Pester 4.0.2? 

I understand that this is nice theoretical problem, but the `-eq` is handling it the same way as Pester (the other way aroung actually), and there is not much we can do about it. We can replace the `-eq` with `.ToUpper()` and `-ceq`, but that will surely has it's own set of edge cases that will get highlighted sooner or later.

**Comment by it-praktyk** [comment]
The issue was introduced by the pull request https://github.com/pester/Pester/pull/252 to the DevelopmentV4 branch.

I'm not sure what is a real impact of that issue. Maybe that should be mentioned in the release notes document at least?

**Comment by nohwnd** [comment]
@it-praktyk I tried this, and I am not sure how to progress. `Be` should work the same way as `-eq` including some of it's glitches. If you need different behavior there should imho be [special string assertion](https://github.com/nohwnd/Assert/blob/master/src/String/Assert-StringEqual.ps1) that adresses it explicitly via some parameter, `Be` is already overloaded enough.

Do you know how the PR introduces the new behavior, I don't see it? It seems to still use `-eq` and `-ceq` as before, only in a different place in the code.

**Comment by it-praktyk** [comment]
I didn't analyze it very deeply before I've opened the issue. I agree that it's very specific case and maybe doesn't be handled even.

I just marked it as 'Known limitation' and 'Documentation' so I'll try mention about it in the wiki.
