### ISSUE TITLE
[Pester 4.0.2] Gherkin scenario counts are broken

### ISSUE THREAD

**Issue by Jaykul** [pester/Pester#714]
The changes to how Describe and Context are handled in Pester 4 broke the output for Gherkin by flipping the values of "Context" and "Describe" in the `$Pester.TestResult` ...

I need to investigate further -- just wanted to log this here so we can be sure to fix it before release.

Any thoughts about how to include tests that fail so that I can test the result of failing tests ... without ... failing tests? (Wow, that's confusing).

**Comment by Jaykul** [comment]
Just an update: I'm still working on this -- I updated Gherkin with the new options on Invoke-Pester, but the exact nature of how the Context and Describe are wrong eluded me today.

I did spend a little time playing with scoping in Gherkin to see if I can figure out how to make mocks and indeed, variables persist through the scopes that they should -- will need to work on that a little more.

**Comment by nohwnd** [comment]
I was just wondering how to tell that you are done with this, so just let me know when you feel like it's ready. Just a head up, as highlighted in #697 the mocks are currently working only for the first describe if the function is defined inside of describe, it's a bug, so don't get tripped by it.

**Comment by Jaykul** [comment]
As discussed in #721, I've changed Gherkin to run each "Scenario" as a "Describe" (aka Context), which I think work around that mocking problem and makes variable scoping work roughly the way I wanted it to.

The work for this is done now. All the tests pass on my box, so I'll wait for the build on the PR ;-)

I clearly need to add some additional tests, because I found a couple of things by running the gherkin tests on the [dev branch of Configuration](https://github.com/PoshCode/Configuration/tree/dev).  I had to fix a few tests, because of the scoping changes, but I feel _really good_ about that, because they were mostly sloppy scoping problems.

**Comment by Jaykul** [comment]
Ok, this is **fixed** @nohwnd, even works on PS2 now...

**Comment by ronaldborman** [comment]
Should this work in 4.0.3-rc? Because Scenarios Passed is 0 in a simple single scenario, although all steps passed. I'll try to investigate further if it should work.

**Comment by Jaykul** [comment]
Just saw this note -- I've been ignoring email. 😉 I'll look into it.

**Comment by nohwnd** [comment]
@Jaykul could you have a look pls?

**Comment by dlwyatt** [comment]
```The changes to how Describe and Context are handled in Pester 4 broke the output for Gherkin by flipping the values of "Context" and "Describe" in the $Pester.TestResult ...```

Wait, what?  Did they used to be backwards?  Looks correct now:

```
ErrorRecord            :
ParameterizedSuiteName :
Describe               : PesterContain
Parameters             : {}
Passed                 : True
Show                   : All
FailureMessage         :
Time                   : 00:00:00.1634025
Name                   : returns true if the file contains the specified content
Result                 : Passed
Context                : when testing file contents
StackTrace             :


    Describe "PesterContain" {
        Context "when testing file contents" {
            Setup -File "test.txt" "this is line 1`nrush is awesome`nAnd this is Unicode: ☺"
            It "returns true if the file contains the specified content" {

```

**Comment by Jaykul** [comment]
I'm pretty sure this is fixed. There's a test in [Gherkin.Tests.ps1](https://github.com/pester/Pester/blob/master/Functions/Gherkin.Tests.ps1#L57) to ensure it stays that way.  Need repro otherwise @ronaldborman
