### ISSUE TITLE
Move help to PlatyPS and generate pages of wiki based on it too

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#720]
https://github.com/PowerShell/platyPS

**Comment by it-praktyk** [comment]
The related issue #648 

The current state of help - after merging currently opened pull requests.

![pesterv4-help-20170131_-_2017-01-31_18 25 34](https://cloud.githubusercontent.com/assets/4910261/22476521/074f7f94-e7e3-11e6-9de5-7077f44b00ba.png)

**Comment by Jaykul** [comment]
So ... if we think we want to do this, I think we should ...

## Just Do It!

```posh
New-MarkdownHelp -Module Pester -OutputFolder Docs -WithModulePage
```

And then ask people to start helping us fix them.

**Comment by vors** [comment]
Would be great to see pester help in platyPS. Let me know if you find anything blocking transition.

**Comment by Jaykul** [comment]
Next step, clearly -- get people to help write help ;-)

**Comment by it-praktyk** [comment]
The related issue #555

**Comment by it-praktyk** [comment]
The related issue: [Would you like to include API documentation to your build?]( https://github.com/pester/Pester/issues/407).

**Comment by it-praktyk** [comment]
The related series of blog posts [Automated Documentation in a CI/CD Pipeline for PowerShell Modules with PlatyPS, psake, AppVeyor, GitHub and ReadTheDocs](https://get-powershellblog.blogspot.com/2017/03/write-faq-n-manual-part1.html) by @markekraus

**Comment by nohwnd** [comment]
Anyone interested in implementing this or should we keep it as is and close it?

**Comment by it-praktyk** [comment]
I'll try to do that.

The related issue
https://github.com/PowerShell/platyPS/issues/371

Wojciech Sciesinski

________________________________

**Comment by nohwnd** [comment]
halbarad (discord) APP [1:04 PM]
@PrzemyslawKlys @nohwnd, this is how I add it in:

```powershell
#.ExternalHelp VMConfig-help.xml
Function Start-VmcLab {
```

There's another way using an attribute on the function but I always forget what it is.
This is how I generate that xml from the md files.

```powershell
New-ExternalHelp -Path $(Build.SourcesDirectory)\Docs -OutputPath ` 
    $(Build.SourcesDirectory)\Output\en
```

**Comment by PrzemyslawKlys** [comment]
I actually generate Docs folder for all my projects:

```
$null = New-MarkdownHelp -Module $ProjectName -WithModulePage -OutputFolder $DocumentationPath 

# and then update it
$null = Update-MarkdownHelpModule $DocumentationPath -RefreshModulePage -ModulePagePath $ReadMePath 
```

I've not played with XML yet as I don't really know how to host XML online for a module and how to pinpoint it to the module. 

@nohwnd  what you mentioned on twitter would be cool because right now it seems PlatyPS can take markdown help written inside a function (but not everything at least to my testing) and move it to docs folder, but having it work another way around would be great too.

**Comment by nohwnd** [comment]
The problem I am trying to solve is how to keep the documentation up to date, trackable and easy to update. These days I am working on Pester v5 and I am removing and renaming a lot of stuff. Migrating from v4 to v5  will take some until we can safely retire v4, so having two versions of wiki is definitely needed. And the other thing is that scrolling past inline help is extremely annoying, especially since there are many functions in one file it's not very easy to see in which function I currently am. 

On the other hand I like that the wiki is easy to edit.

@it-praktyk how far are you with this?:)

**Comment by Splaxi** [comment]
Would it be enough to have the format of the documentation based on the CBH and from that generate either External-Help and Wiki pages?

**Comment by PrzemyslawKlys** [comment]
There are already markings `.Example` marking is start, next `.EXAMPLE` is another marking

**Comment by it-praktyk** [comment]
> @it-praktyk how far are you with this?:)

Not so far, I just generated files using PlatyPS - you can find the branch https://github.com/it-praktyk/Pester/tree/PlatyPS_Help.

**Comment by it-praktyk** [comment]
How do I see a process of migration to a markdown-based help?

1. Create the branch PlatyPS_help in the repository Pester/Pester - to make work visible

2. Update CI pipeline to trigger Update-MarkdownHelpModule (please be aware of the issue PowerShell/platyPS#371 - as long as the step 5 will not be completed it's not the case but later ...

3. Verify/clean the content of markdown files.

4. Generate XML MAML-formated help files based at markdown and include them in the release

5. Remove a command-based help from the *.ps1 files

**Comment by fourpastmidnight** [comment]
I was totally going to attempt this myself. I didn't want two sources of truth for help in my own modules, and so early on, I decided to not use comment-based help in my functions, but instead write the markdown documents and use platyPS to generate the help file for my module. I was hoping to do the same for Pester--but my time is limited and I see that there are already ppl working on/interested in making this happen! I'd be happy to lend any help and support for this effort.

**Comment by Splaxi** [comment]
@fourpastmidnight If you could share what you have already, it would make it easier for us to skip in making it happen.

**Comment by nohwnd** [comment]
So here is a https://github.com/pester/Pester/tree/move-help-to-platyps if more people want to work on this. The help should be in Markdown, and the comment based help would be generated from it. I would start with moving the help into it's own files, and then we can start talking about possibly making the wiki and the help using the same sources, or integrating in some way. Any takers?

**Comment by it-praktyk** [comment]
I'll make an initial work just now :-)

**Comment by it-praktyk** [comment]
Done, PR #1226.

**Comment by nohwnd** [comment]
@it-praktyk k merged, only scrolled through the changes, and the first file looked broken, some extra type escaping there and incorrect code regions, but I will review properly when this is ready to merge to master.

**Comment by it-praktyk** [comment]
I work now to clean 'RELATED LINKS' sections and doubled empty lines.

**Comment by it-praktyk** [comment]
Please be aware of the issue with ```Update-MarkdownHelp``` - https://github.com/PowerShell/platyPS/issues/433.

**Comment by it-praktyk** [comment]
@nohwnd,
I'm thinking about reverting your change  regarding the structure of MD files - I'm thinking about undoing your change regarding the structure of MD files. 

Some (all?) of changes will be reverted under the next update made by using Update-MarkdownHelp - please read the thread https://github.com/PowerShell/platyPS/issues/345.

**Comment by nohwnd** [comment]
@it-praktyk I am probably getting this wrong, but I thought that new-markdown help generates the markdown files from the existing files **once**. And then we use something different to convert the existing markdown files back to the powershell help.  So formatting the markdown properly should not be a problem, because we will be using the markdown as the source of the help for the cmdlets, and not the other way around, in other words the markdown will never be regenerated again.

**Comment by it-praktyk** [comment]
IMHO, Update-MarkdownHelp workflow is like below.
1. read the existing markdown help file
2. parse markdown to PSObject
3. get information about parameters from the code
4. merge 2 + 3
5. write the file 

@vors, Am I right?

The related issue: https://github.com/PowerShell/platyPS/issues/393

**Comment by PrzemyslawKlys** [comment]
You need to continue using Update-MarkdownHelp if you want to have all the benefits of it. Otherwise everytime you will change order, add parameters you will have to update docs manually. It's best to keep to the specs that platyPS proposes.

**Comment by nohwnd** [comment]
Okay gotcha, I confused New-MarkdownHelp with Update-MarkdownHelp

**Comment by PrzemyslawKlys** [comment]
We can always help and bring new features to PlatyPS 👍 I'm sure @vors  will be happy!

**Comment by fourpastmidnight** [comment]
@nohwnd so yes, that implies you can generate the help once and then use the markdown as the primary source from which to generate help for the middle on build. When I get into the office in about one hour, I'll quick dig up the psake task I'm using to do just that.

**Comment by PrzemyslawKlys** [comment]
Here is generated content by New / Update 

https://github.com/EvotecIT/PSEventViewer/blob/master/Docs/Get-EventsInformation.md

As you can see there are several examples. It actually converted the content from https://github.com/EvotecIT/PSEventViewer/blob/master/Public/Get-EventsInformation.ps1 including comments under examples. Seems good enough right?

**Comment by fourpastmidnight** [comment]
@PrzemyslawKlys Hmm, I recalled having difficulty with that--but glad to see it seems to be working. Though, the example you linked to didn't have code + text. I think it's that interplay between code/non-code text that _may_ trip up platyPS? I don't really remember.

Here's my psake task for generating help, which probably already looks very much like what you're already doing:

```powershell
Task GenerateModuleHelp {
    [string[]]$helpDocs = @(Get-ChildItem $DocsDirectory -File -Filter "*.md" -Recurse | Select-Object -ExpandProperty FullName)

    New-ExternalHelp -Path $helpDocs -OutputPath "${ENV:BHPSModulePath}\en-US"
}
```

I'm also using the [BuildHelpers](https://github.com/RamblingCookieMonster/BuildHelpers) module which simplifies things for me--that's all those `$ENV:BH*` variables.

So, I first ran whatever cmdlet to run to convert my existing comment-based help to Markdown, tweaked the markdown, and now I only use `New-ExternalHelp`. Otherwise, I maintain the markdown manually at this point. I haven't used this long enough to have any regrets--maybe someone else has? Anyway, guess I'm not really contributing much, as you guys already have this--and by the way, good job to all who have taken point on this.

**Comment by PrzemyslawKlys** [comment]
I believe it takes everything under .Example as code you can see that in my example

**Comment by PrzemyslawKlys** [comment]
And actually, if you modify the output .md file as I did now it doesn't change it back. https://github.com/EvotecIT/PSEventViewer/blob/master/Docs/Get-EventsInformation.md 

So I would say as long as you conform to some rules you should be fine.

**Comment by nohwnd** [comment]
As you say. Help in markdown only.

**Comment by it-praktyk** [comment]
I need help to find why some tests fail in the branch `move-help-to-platyps`

```
  Assertion operators                                                                                                                                                                                                                           
    [-] Allows an operator with an identical name and test to be re-registered 39ms                                                                                                                                                             
      Expected no exception to be thrown, but an exception "Assertion operator name 'SameNameAndScript' has been added multiple times." was thrown from C:\Users\<FOLDER_PATH>\Pester\Pester.psm1:484 char:13     
          +             throw "Assertion operator name '$string' has been added m ...                                                                                                                                                           
          +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.                                                                                                                                                              
      352:             } } | Should -Not -Throw                                                                                                                                                                                                 
      at <ScriptBlock>, C:\Users\<FOLDER_PATH>\Pester\Pester.Tests.ps1: line 350                                                                                                                                  
    [-] Allows an operator with an identical name, test, and alias to be re-registered 30ms                                                                                                                                                     
      Expected no exception to be thrown, but an exception "Assertion operator name 'SameNameAndScriptAndAlias' has been added multiple times." was thrown from C:\Users\<FOLDER_PATH>\Pester\Pester.psm1:484 char
:13                                                                                                                                                                                                                                             
          +             throw "Assertion operator name '$string' has been added m ...                                                                                                                                                           
          +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.                                                                                                                                                              
      362:             } -Alias SameAlias } | Should -Not -Throw                                                                                                                                                                                
      at <ScriptBlock>, C:\Users\<FOLDER_PATH>\Pester\Pester.Tests.ps1: line 360                                                                                                                                  
    [+] Allows an operator to be registered with multiple aliases 23ms                                                                                                                                                                          
    [+] Does not allow an operator with a different test to be registered using an existing name 20ms                                                                                                                                           
    [+] Does not allow an operator with a different test to be registered using an existing alias 45ms                                                                                                                                          

```

I've reverted, locally, the commit e8f5722ad289d3895762ab00025ca3f016433d89 but it still fails.

I propose to exclude the tag `Help` under Invoke-Pester.

**Comment by it-praktyk** [comment]
It's a part of the standard Pester tests. Under changing help (and the code reformatting, in some cases).

I broke something during my actions :-/

**Comment by nohwnd** [comment]
Keep it failing I can have a look on it later. :)

**Comment by nohwnd** [comment]
We created https://pester.dev in the meantime.
