### ISSUE TITLE
Set-TestInconclusive - unexpected/inconsistent behaviour

### ISSUE THREAD

**Issue by it-praktyk** [pester/Pester#722]
I'm preparing the next update for help and I play with the Test-Inconclusive function.

I prepared a tests like below

```powershell

Describe "Function1" {
    It "Test what always pass" {
        
        $true | Should Be $true
        
        Set-TestInconclusive -Message "I'm inconclusive because I can"
    }
    
    It "Test what always fail" {
        
        $true | Should be $false
        
        Set-TestInconclusive -Message "I'm inconclusive because I can"
        
        
        
    }
    
    It "Test what is inconclusive" {
        
        Set-TestInconclusive -Message "I'm inconclusive because I can"
        
    }
}

```

The function Function1.ps1 is empty (initialized by the New-Fixture).

Returned results are

```
PS >invoke-pester

Executing all tests in <SOME FOLDER>\inconclusive\

Executing script C:\Users\<SOME FOLDER>\inconclusive\Function1.Tests.ps1

  Describing Function1
    [?] Test what always pass 110ms
      I'm inconclusive because I can
      at line: 10 in C:\Users\<SOME FOLDER>\inconclusive\Function1.Tests.ps1
      10:         Set-TestInconclusive -Message "I'm inconclusive because I can"
    [-] Test what always fail 38ms
      Expected: {False}
      But was:  {True}
      at line: 15 in C:\Users\<SOME FOLDER>\inconclusive\Function1.Tests.ps1
      15:         $true | Should be $false
    [?] Test what is inconclusive 96ms
      I'm inconclusive because I can
      at line: 25 in C:\Users\<SOME FOLDER>\inconclusive\Function1.Tests.ps1
      25:         Set-TestInconclusive -Message "I'm inconclusive because I can"Tests completed in 245ms
Tests Passed: 0, Failed: 1, Skipped: 0, Pending: 0, Inconclusive: 2
PS >
```

In my opinion the Set-TestInconclusive behaviour should be the same for tests 1 and 2. Am I right?

Confirmed with

Pester version     : 3.4.6 C:\Program Files\WindowsPowerShell\Modules\pester\3.4.6\Pester.psm1
PowerShell version : 5.1.14393.693
OS version         : Microsoft Windows NT 10.0.14393.0

Pester version     : 4.0.2 C:\Users\<SOME FOLDER>\Pester\Pester.psm1
PowerShell version : 5.1.14393.693
OS version         : Microsoft Windows NT 10.0.14393.0

**Comment by dlwyatt** [comment]
Set-TestInconclusive should be the first line of a test, if you want to use it.  `It` blocks are terminated by exceptions, which can be thrown by any command (including `Should` and `Set-TestInconclusive`.)  Whichever one throws the error first wins.

**Comment by it-praktyk** [comment]
Thank you for your explanation. It's logical - now I see, yesterday was too dark ;-)

Please mark the issue as a question and close. Thank you once again.
