### ISSUE TITLE
4.0.2 output breaks PowerShell extension problem matcher in VS Code.

### ISSUE THREAD

**Issue by rkeithhill** [pester/Pester#725]
The PowerShell extension for VSCode provides a task.json problem matcher that causes Pester test failures to appear in the VSCode Problems window.  And when it works, you can click on the entries to go to the line of script that failed.  

However with 4.0.2 I'm seeing a number of entries that have no filename:
```
        at line: 92 in 
```
Hopefully that is a bug and not by design.

**Comment by gerane** [comment]
This almost seems random for me. I was going to take a screenshot of one that did this for me, but now I can't seem to get it to omit the file.

I do still have the text output of one. There were 2 other failures that had the files in this output.

```
[-] Should call Write-EventLog 1 time 25ms
        Expected Write-EventLog to be called 1 times exactly but was called 2 times
        at line: 179 in
        179:             Assert-MockCalled -CommandName Write-EventLog -Times 1 -Exactly
```

**Comment by rkeithhill** [comment]
Here is what changed between 3.4.0 and 4.0.2, both utilizing the special property `-PesterOption @{IncludeVSCodeMarker=$true}` that @dlwyatt added for me last year.
3.4.0 output:
```
 [-] Processes multiple relative path via -Path param 61ms
   at <ScriptBlock>, C:\Users\Keith\GitHub\rkeithhill\vscode-powershell\examples\Tests\PathProcessing.Tests.ps1: line 83
   Expected: {C:\Users\Keith\GitHub\rkeithhill\vscode-powershell\examples\README.md C:\Users\Keith\GitHub\rkeithhill\vscode-powershell\examples\.vscode\launch.json2}
   But was:  {C:\Users\Keith\GitHub\rkeithhill\vscode-powershell\examples\.vscode\launch.json}
   84:             Should Be @("$WorkspaceRoot\README.md", "$WorkspaceRoot\.vscode\launch.json2")
   at <ScriptBlock>, C:\Users\Keith\GitHub\rkeithhill\vscode-powershell\examples\Tests\PathProcessing.Tests.ps1: line 83
 [+] DefaultParameterSet should be Path 116ms
```

v4.0.2 output:
```
v4.0.2
    [-] Processes multiple relative path via -Path param 74ms
      Expected: {C:\Users\Keith\GitHub\rkeithhill\vscode-powershell\examples\README.md C:\Users\Keith\GitHub\rkeithhill\vscode-powershell\examples\.vscode\launch.json2}
      But was:  {C:\Users\Keith\GitHub\rkeithhill\vscode-powershell\examples\README.md C:\Users\Keith\GitHub\rkeithhill\vscode-powershell\examples\.vscode\launch.json}
      at line: 84 in C:\Users\Keith\GitHub\rkeithhill\vscode-powershell\examples\Tests\PathProcessing.Tests.ps1
      84:             Should Be @("$WorkspaceRoot\README.md", "$WorkspaceRoot\.vscode\launch.json2")
    [+] DefaultParameterSet should be Path 26ms
```

Note that in v3.4.0 the file/line info is display right after the `[-]` line.  This was necessary to make the problem matcher in VS Code work properly.  I see the format of the line has changed as well but I can handle that with an updated regex.  However, having the `expected`  and `actual` lines appear **between** the two really messes up the problem matcher - particularly because the number of lines is not fixed.  Can you please fix this for `IncludeVSCodeMarker=$true`?

**Comment by Jaykul** [comment]
Is it just a matter of putting the stack trace above the error message? I can fix that...

**Comment by rkeithhill** [comment]
More or less.  Dave did this before in PR #479 but only when IncludeVSCodeMarker is specified in PesterOption which he added for this issue.  Details here https://github.com/pester/Pester/commit/a1e7ce27f31f3bcf3a1de824d9274b89f466ae52

**Comment by Jaykul** [comment]
Yeah, his code is all still there for the option, just the switch in the output got lost. I don't know how you're using this in VS Code, but it looks like this in the output:

```
  Scenario: Scope Should Still Be Easy
    [+] Given I initialize the variable Script:Two to "Uno" 0ms
    [+] When I set the variable Script:Two to "Hello World" 0ms
    [-] Then the variable Script:Two should be "Hello World" 4ms
      at <ScriptBlock>, C:\Users\Joel\Projects\Modules\Pester\Examples\Gherkin\VariableScope.Steps.ps1: line 34
      From C:\Users\Joel\Projects\Modules\Pester\Examples\Gherkin\Gherkin-Scope.feature: line 14
      Expected string length 11 but was 3. Strings differ at index 0.
      Expected: {Hello World}
      But was:  {Dos}
      -----------^
```

Obviously that's Gherkin, but the output is the same, which is why we rock 😉

**Comment by rkeithhill** [comment]
That is perfect - even uses the old syntax e.g. `... filename: line ##`.  I could have changed the regex to use the new syntax `at line: ## in filename` but folks with the newer PowerShell extension would be broken until they updated to Pester 4.0.3.

**Comment by Jaykul** [comment]
Oh, hmm. That's interesting. Apparently, I was wrong ... the RSpec runner is flipping the stacktrace around?

**Comment by Jaykul** [comment]
Ok, I think that needs to be fixed (in the RSpec output). The `at line: 2` is only on the front when it's a pester assertion failure, because those are being written in "by hand"

[Output.ps1#L167-L178](https://github.com/pester/Pester/blob/DevelopmentV4/Functions/Output.ps1#L167-L178)
```posh
        if ( -not ($ErrorRecord | & $SafeCommands['Get-Member'] -Name ScriptStackTrace) )
        {
            if ($ErrorRecord.FullyQualifiedErrorID -eq 'PesterAssertionFailed')
            {
                $lines.Trace += "at line: $($ErrorRecord.TargetObject.Line) in $($ErrorRecord.TargetObject.File)"
            }
            else
            {
                $lines.Trace += "at line: $($ErrorRecord.InvocationInfo.ScriptLineNumber) in $($ErrorRecord.InvocationInfo.ScriptName)"
            }
            return $lines
        }
```
If it's any _other_ sort of exception, then you'll get the normal stack trace format.

**Comment by nohwnd** [comment]
I'd say go with the same output as in v3 to avoid breaking the VSCode problem matcher, if the change is easy to make. Then, if needed, we can work with Keith to introduce format that will be accurate and will work for him.

**Comment by Jaykul** [comment]
Ok, I spent the evening looking into this and I'm torn. 

### Pester 3

Basically what's going on is that there's a function `Get-PesterResult` in [It.ps1](https://github.com/pester/Pester/blob/DevelopmentV4/Functions/It.ps1#L293-L351) which creates a result object with a `stackTrace` string on it which is _never actually used_ in v3.  Instead, in v3, the output is **recalculated** all over again using `ConvertTo-FailureLines` in [PesterState.ps1](https://github.com/pester/Pester/blob/master/Functions/PesterState.ps1#L314-L323)

### Pester 4

The `ConvertTo-FailureLines` function is still there (moved to Output.ps1), but it's never used. Instead, the error messages and stackTrace that was calculated by `Get-PesterResult` in [It.ps1](https://github.com/pester/Pester/blob/DevelopmentV4/Functions/It.ps1#L293-L351) is actually output.

My feeling is that this is the worst of both worlds.

We created the `Output.ps1` file to collect all the string formatting functions, but we didn't move `Get-PesterResult` into it (and I missed that in Gherkin, so I'm not calling it). Then we have this extra function in the Output.ps1 which we're no longer using.

Personally, I think that the algorithm used by `Get-PesterResult` to build the error message is elegant, but I will point out that the exception message in the stack trace is more likely to be localized. The nice thing about it is that most of the time it does not rely on a regex filter to remove lines from the ScriptStackTrace...

#### So: do we "improve" the output, or do we duplicate what's in Pester 3?

Duplicate Pester 3

#### Do we calculate the line, or use regex to capture the data from the ScriptStackTrace?

Use regex to capture the data. That's what worked before. It might even be localized text?

#### How do we clean up?

Can I remove `Get-PesterResult` if we're not using the text it calculates anyway? The easy answer is no; even though we don't present the text to the user, we have tests for it, so it's a big deal to remove it.

I pushed another commit to #725  -- I think that the output now matches Pester 3, except that we don't double-print things when `-PesterOption @{ IncludeVSCodeMarker = $true }`

**Comment by rkeithhill** [comment]
> I pushed another commit

Was that on your fork?  I'd like to test your fix.

**Comment by Jaykul** [comment]
Sorry, yeah @rkeithhill, I meant to say I pushed another commit to #726

**Comment by rkeithhill** [comment]
So when will PR #726 get merged and we get a 4.0.3?  Inquiring VSCode users want to know.  :-)

**Comment by rkeithhill** [comment]
Any update on this?  This does negatively impact the Pester / PowerShell integration experience on VS Code.  cc @daviwil

**Comment by Jaykul** [comment]
It's merged now, @rkeithhill (not released, but merged)

**Comment by rkeithhill** [comment]
@Jaykul  Thanks!

**Comment by Jaykul** [comment]
Please close.

**Comment by nohwnd** [comment]
@Jaykul  closed :)
