### ISSUE TITLE
BeOfType

### ISSUE THREAD

**Issue by davidwallis3101** [pester/Pester#729]
Certain assertions return the actual type.. but PesterBeOfTypeFailureMessage line 15..
https://github.com/pester/Pester/blob/630077a53bb974b775da0d79b920e438a18e969b/Functions/Assertions/BeOfType.ps1

doesn't contain the , but it's a [${Type}]" expression as in line 26..

is it feasible to add this in?

**Comment by nohwnd** [comment]
Sure:)

**Comment by davidwallis3101** [comment]
Thanks, I would offer to pick this up - but I'm scared of breaking your code.. 

Incidentally what is the roadmap for 3.x as I noticed you assigned this to 4.1 are no changes happening in this code base?

**Comment by nohwnd** [comment]
Currently I am focusing on make the v4 work and push it out the door, but if you want to add the feature, then add it to the v3, and I will merge it forward to v4. I assigned it to 4.1 milestone because it is a new feature.
