### ISSUE TITLE
Context not in nunitXml export

### ISSUE THREAD

**Issue by Stephanevg** [pester/Pester#733]
Hi,

Perhaps I am doing things wrong, but I do have a bunch of 'Context' blocks in my pester tests to seperate parts logically.

I was expecting that I would find the tests located in a Context block, would also be located in a node XML element 'Context' (or somethign similar). am I missing something or is this currently not implemented / supported?

Example:

```
Describe "Standard Server Compliancy tests" {

  Context 'Local User and Groups tests'{
    It "Should have local user account $($localAccountName)" {
      $Account = Get-LocalUser -Name $localAccountName
      $Account.Name | should match $localAccountName 
    }
    It "Account $($localAccountName) should be in administrators group " {
      (Get-LocalGroupMember -GroupName "administrators") -contains $localAccountName | should be $true
    }
  }
}
```

results in the following XML - Extracted from a larger XML file:
`<test-suite type="PowerShell" name="Pester" executed="True" result="Failure" success="False" time="13.9048" asserts="0">
    <results>
      <test-suite type="TestFixture" name="Standard Server Compliancy tests" executed="True" result="Failure" success="False" time="2.3968" asserts="0" description="Standard Server Compliancy tests">
        <results>
          <test-case description="Should have local user account woeadmin" name="Standard Server Compliancy tests.Should have local user account woeadmin" time="0.3414" asserts="0" success="True" result="Success" executed="True" />
      </results>
  </test-suite>
 </results>
          `

If I cannot use Context to organise the output of my test results (in the Nunit Export export, I would be curious to know what are you guys using to organize your results, and what approach would you recommend?

Thanks a lot !

**Comment by it-praktyk** [comment]
In the process of triage I add
- [NUnit XML Formats](https://github.com/nunit/docs/wiki/XML-Formats)

> Invoke-Pester parameters also let you save the test output in NUnitXml or 
    LegacyNUnitXml formats that are commonly used by reporting tools.

https://github.com/pester/Pester/blob/630077a53bb974b775da0d79b920e438a18e969b/en-US/about_Pester.help.txt

Based on both information I don't know what NUnit schema is considered by Pester as LegacyNUnitXml. The NUnit 2.x ?

**Comment by dlwyatt** [comment]
It's not referring to a version of NUnit schema, but rather how Pester originally did the XML export (not containing Context, etc.)  That way if people have some build automation written around the older versions of Pester, they can continue to use it without modification at first.

**Comment by Stephanevg** [comment]
Hi guys,

I am not sure I understood this thread correctly. Will this be added in the V4 version?

**Comment by nohwnd** [comment]
@Stephanevg  Running this command I get xml output that seems to have every block there is in the code. So everything seems to be working just fine. Are you using the same type of output?

```powershell
Invoke-Pester -Path .\ctx.tests.ps1 -OutputFile g.xml -OutputFormat NUnitXml
```
```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-results xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="nunit_schema_2.5.xsd" name="Pester" total="2" errors="0" failures="2" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2017-08-12" time="22:09:33">
  <environment user="nohwnd" cwd="C:\Users\nohwnd\Desktop" clr-version="4.0.30319.42000" user-domain="NDEV" platform="Microsoft Windows 10 Pro|C:\WINDOWS|\Device\Harddisk0\Partition4" nunit-version="2.5.8.0" os-version="10.0.15063" machine-name="NDEV" />
  <culture-info current-culture="cs-CZ" current-uiculture="en-US" />
  <test-suite type="TestFixture" name="Pester" executed="True" result="Failure" success="False" time="0.0591" asserts="0" description="Pester">
    <results>
      <test-suite type="TestFixture" name=".\ctx.tests.ps1" executed="True" result="Failure" success="False" time="0.0591" asserts="0" description=".\ctx.tests.ps1">
        <results>
          <test-suite type="TestFixture" name="Standard Server Compliancy tests" executed="True" result="Failure" success="False" time="0.0591" asserts="0" description="Standard Server Compliancy tests">
            <results>
              <test-suite type="TestFixture" name="Local User and Groups tests" executed="True" result="Failure" success="False" time="0.0591" asserts="0" description="Local User and Groups tests">
                <results>
                  <test-case description="Should have local user account " name="Standard Server Compliancy tests.Local User and Groups tests.Should have local user account " time="0.039" asserts="0" success="False" result="Failure" executed="True">
                    <failure>
                      <message>Cannot validate argument on parameter 'Name'. The argument is null. Provide a valid value for the argument, and then try running the command again.</message>
                      <stack-trace>at &lt;ScriptBlock&gt;, C:\Users\nohwnd\Desktop\ctx.tests.ps1: line 5
5:       $Account = Get-LocalUser -Name $localAccountName
</stack-trace>
                    </failure>
                  </test-case>
                  <test-case description="Account  should be in administrators group " name="Standard Server Compliancy tests.Local User and Groups tests.Account  should be in administrators group " time="0.0201" asserts="0" success="False" result="Failure" executed="True">
                    <failure>
                      <message>A parameter cannot be found that matches parameter name 'GroupName'.</message>
                      <stack-trace>at &lt;ScriptBlock&gt;, C:\Users\nohwnd\Desktop\ctx.tests.ps1: line 9
9:       (Get-LocalGroupMember -GroupName "administrators") -contains $localAccountName | should be $true
</stack-trace>
                    </failure>
                  </test-case>
                </results>
              </test-suite>
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>
```

**Comment by nohwnd** [comment]
@Stephanevg Closing this. We have it as blocker to v4 release, the output seems just fine. Feel free to reopen this issue if you need more assistance or clarification. 😄
