### ISSUE TITLE
It on Assert-MockCalled -Scope is case sensitive

### ISSUE THREAD

**Issue by sdecker** [pester/Pester#736]
If you say either of the following 
Assert-MockCalled -CommandName MyCommand -Times 0 -Exactly -Scope IT
Assert-MockCalled -CommandName MyCommand -Times 0 -Exactly -Scope it
The scope is ignored. It only works if the you use a capital I and lowercase t.

**Comment by nohwnd** [comment]
Thanks for reporting. Need to investigate that.

**Comment by dlwyatt** [comment]
I haven't been able to reproduce any case sensitivity problems, but while investigating this, I did come across another bug in v4.  (It assumes that mocks are only called from inside `It` blocks, which is not correct.)

@sdecker , what version of Pester were you using when you encountered this bug?

**Comment by sdecker** [comment]
I'm not sure what version it was at the time butI can no longer reproduce and am marking this closed. Sorry for the delay in responding.
