### ISSUE TITLE
Constructing a scriptblock for MockWith parameter

### ISSUE THREAD

**Issue by Glober777** [pester/Pester#737]
Hi!

I'm looking for a way to construct a script block for one of the mocks that I'm working on. I want to mock a function in a way that it should return a content of a particular file (to speed up the testing), a path to which is based on `$PSScriptRoot` of my test script, and obviously can only be resolved outside of the mocked function.

If I do it like this:
```
InModuleScope -ModuleName $ModuleName -ScriptBlock {
    Describe 'My Test' {
        $MyMockWithScript = [scriptblock]::Create(('Import-Clixml -Path "{0}" | Write-Output') -f "$PSScriptRoot\TestData\SomeDataThatTakesTooLongToGet.clixml")

        Mock -CommandName Get-SomeDataThatTakesTooLongToGet -MockWith $MyMockWithScript -ModuleName $ModuleName -Verifiable
    }
}
```

I get an error saying:
  [-] Error occurred in Describe block 59ms
    You cannot call a method on a null-valued expression.
    At C:\Program Files\WindowsPowerShell\Modules\Pester\4.0.2\Functions\Mock.ps1:180 char:9

If I do it like this:
```
InModuleScope -ModuleName $ModuleName -ScriptBlock {
    Describe 'My Test' {
        $MyMockWithScript = {Import-Clixml -Path "C:\ActualPathToTheTestFolder\TestData\SomeDataThatTakesTooLongToGet.clixml" | Write-Output}

        Mock -CommandName Get-SomeDataThatTakesTooLongToGet -MockWith $MyMockWithScript -ModuleName $ModuleName -Verifiable
    }
}
```

It works as expected, but that introduces a dependency on full path to the test data file, which I'd like to avoid.

Are there any suggestions?

If there's no way to generate scriptblocks for the Mock, is it at least possible to reach out to the TestDrive from within the mocked function as an alternative?

Thanks in advance!

**Comment by dlwyatt** [comment]
Ah, there's a bug with unbound script blocks.  Will fix, but in the meantime, you can probably work around it like this:

`$MyMockWithScript = $MyMockWithScript.GetNewClosure()`

**Comment by Glober777** [comment]
The workaround works like a charm. Thanks!

**Comment by dlwyatt** [comment]
Fix merged for next v4.x release.
