### ISSUE TITLE
Passthru does not include the test file path

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#739]
Passthru output does not include the path to the test file. which makes it difficult to use with appveyor `Add-AppveyorTest` cmdlets.

**Comment by dlwyatt** [comment]
Just need to add "TestActions" to the list of properties that get output with PassThru; my mistake for missing that.  TestActions is the new hierarchical view of arbitrary nested script blocks, while TestResult tries to be as backward-compatible as possible by calling the outermost (not script) block "Describe", and joins all the nested blocks' names into "Context".

**Comment by nohwnd** [comment]
Thanks for the info, will fix that.


Jakub Jareš

.NET, Pester, PowerShell
t 00420603800578<tel:00420603800578>
e me@jakubjares.com<mailto:me@jakubjares.com>
t @nohwnd

4. 3. 2017 v 16:39, Dave Wyatt <notifications@github.com<mailto:notifications@github.com>>:


Just need to add "TestActions" to the list of properties that get output with PassThru; my mistake for missing that. TestActions is the new hierarchical view of arbitrary nested script blocks, while TestResult tries to be as backward-compatible as possible by calling the outermost (not script) block "Describe", and joins all the nested blocks' names into "Context".

**Comment by dlwyatt** [comment]
Hmm, might want to add some code to scrub TestActions and get rid of things that aren't useful to the caller.  There's a lot of internal stuff in there right now.

**Comment by dlwyatt** [comment]
For example:

```
$pesterResult.TestActions.Actions[0].Actions[0]


Hint              : Describe
Time              : 00:00:00.6075905
SkippedCount      : 0
TotalCount        : 5
BeforeEach        : {}
Actions           : {@{ErrorRecord=; ParameterizedSuiteName=; Type=TestCase; Parameters=System.Collections.Specialized.OrderedDictionary; Passed=True; Show=All; FailureMessage=; Time=00:00:00.4730739; Name=adds positive numbers; Result=Passed; 
                    StackTrace=}, @{ErrorRecord=; ParameterizedSuiteName=; Type=TestCase; Parameters=System.Collections.Specialized.OrderedDictionary; Passed=True; Show=All; FailureMessage=; Time=00:00:00.0845443; Name=adds negative numbers; Result=Passed; 
                    StackTrace=}, @{ErrorRecord=; ParameterizedSuiteName=; Type=TestCase; Parameters=System.Collections.Specialized.OrderedDictionary; Passed=True; Show=All; FailureMessage=; Time=00:00:00.0159231; Name=adds one negative number to positive 
                    number; Result=Passed; StackTrace=}, @{ErrorRecord=; ParameterizedSuiteName=; Type=TestCase; Parameters=System.Collections.Specialized.OrderedDictionary; Passed=True; Show=All; FailureMessage=; Time=00:00:00.0201436; Name=concatenates 
                    strings if given strings; Result=Passed; StackTrace=}...}
Name              : Add-Numbers
Type              : TestGroup
AfterAll          : {}
PendingCount      : 0
InconclusiveCount : 0
BeforeAll         : {}
FailedCount       : 0
AfterEach         : {}
PassedCount       : 5
```

It's probably not necessary to leave things like BeforeEach / AfterEach / BeforeAll / AfterAll blocks in there in the output.

**Comment by dlwyatt** [comment]
Anyhow, working on this at some point.  Checking the issues log for more pressing things first.

**Comment by nohwnd** [comment]
The path is there in v5 because the block container is attached. The container can be scriptblock, or a file (or something else in the future as well, like a binary blob of encoded pester tests coming from the cloud :D ) and is accessible by either looking at the root block, or the link to root block that every block has. 
```powershell
$result = Invoke-Pester -Path 'C:\Projects\abc' -PassThru 

$result[0].BlockContainer.Content.FullName
$result[0].Blocks[0].Root.BlockContainer.Content.FullName
```
The object describes what type of block container we got so we can check against it to make sure it's a file and handle it properly.
