### ISSUE TITLE
Mock: `ParameterFilter` negates `MockWith`

### ISSUE THREAD

**Issue by VertigoRay** [pester/Pester#741]
I'm having issues implementing the Mock command with both `MockWith` and `ParameterFilter` parameters. It appears to me that using `ParameterFilter` negates the `MockWith` parameter. Maybe I'm doing something wrong, or I just don't understand that intended functionality based on the descriptions of the parameters [in the documentation](https://github.com/pester/Pester/wiki/Mock) (*Yes, I RTFM!*).

```powershell
Describe $sut {
    $Mock = @{
        'CommandName' = 'Rename-Item';
        'MockWith' = { Write-Warning "Not really doing anything ..." };
        'Verifiable' = $true;
        'ParameterFilter' = {
            ($Path -eq 'C:\WINDOWS\Logs\Winstall\Rename-WinstallLogFile 2017 test.log') `
            -and ($NewName -eq 'C:\WINDOWS\Logs\Winstall\Rename-WinstallLogFile 2017 test Foo.log')
        };
    }
    Mock @Mock

    Context "Rename: ' Foo'" {

        $global:Winstall = @{}
        $global:Winstall.Log = $global:WinstallStatic.Log.Clone()

        Rename-WinstallLogFile -Formatter ' Foo'

        It 'Should Call Rename-Item' {
            Assert-MockCalled 'Rename-Item' -Exactly 1 -Scope 'Context'
        }
    }
}
```

**Note:** This is just a snippet of the code. If it doesn't prove to be duplicatable, I'll post something in its entirety. 

Running that file give me calls to the original function; as shown:

![image](https://cloud.githubusercontent.com/assets/792482/23763649/833ae790-04c8-11e7-82e5-c545e1ab401d.png)

If I just comment out the `ParameterFilter` in the `$Mock` hashtable; as shown:

```powershell
$Mock = @{
    'CommandName' = 'Rename-Item';
    'MockWith' = { Write-Warning "Not really doing anything ..." };
    'Verifiable' = $true;
    # 'ParameterFilter' = {
    #     ($Path -eq 'C:\WINDOWS\Logs\Winstall\Rename-WinstallLogFile 2017 test.log') `
    #     -and ($NewName -eq 'C:\WINDOWS\Logs\Winstall\Rename-WinstallLogFile 2017 test Foo.log')
    # };
}
```

I get more desirable results; as shown:

![image](https://cloud.githubusercontent.com/assets/792482/23763735/c3f253ea-04c8-11e7-8357-12ce10bfe362.png)

# Expected Results

I expect `MockWith` to work whether I'm supplying `ParameterFilter` or not.

Otherwise, I expect an error to be thrown if the `Mock` command isn't applying anything.

# Versions

```powershell
Get-Module -ListAvailable | ?{ $_.Name -eq 'Pester' }
```

> Script     3.4.3      Pester                              {Describe, Context, It, Should...}

```powershell
$PSVersionTable
```

> Name                           Value
> 
> ----                           -----
> 
> PSVersion                      5.1.14393.693
> 
> PSEdition                      Desktop
> 
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
> 
> BuildVersion                   10.0.14393.693
> 
> CLRVersion                     4.0.30319.42000
> 
> WSManStackVersion              3.0
> 
> PSRemotingProtocolVersion      2.3
> 
> SerializationVersion           1.1.0.1

**Comment by dlwyatt** [comment]
What parameters are actually being passed to your function?  Odds are the filter did not pass, so the original command was invoked instead.  This is the correct behavior.

(It looks a bit odd to me that you're using the full path in your test of `$NewName`; typically when I call Rename-Item, I do it like this:  `Rename-Item -Path 'C:\WINDOWS\Logs\Winstall\Rename-WinstallLogFile 2017 test.log' -NewName 'Rename-WinstallLogFile 2017 test Foo.log'`)

**Comment by it-praktyk** [comment]
I assume that the issue can be closed now. Feel free to reopen if you need more assistance.
