### ISSUE TITLE
Remote test execution

### ISSUE THREAD

**Issue by dcuomo** [pester/Pester#742]
In a number of situations, in would be useful to be able to run pester context or It statements against a remote node.  For each node in configuration data nodelist, verify a group of windows features are installed.

**Comment by dlwyatt** [comment]
You probably want this:  https://github.com/PowerShell/Remotely

We discussed this with Microsoft before they released it as a separate module, and decided that because it had no dependencies on anything else internal to Pester, it was better to release it on its own.  (Less confusion in Pester to people who don't need it, and also can be used in other contexts than just Pester.)

**Comment by dcuomo** [comment]
Thanks Dave - I modified Remotely to accept a -SystemName parameter that I can iterate through a list of system accounts; that works well enough for my purposes.  The challenge is that the syntax gets complicated for other team members to read through requires bunch of "Remotely" blocks e.g. one per test.  It would be great for integration testing purposes if there was some form of support to "remotely" execute context or describe blocks.  

Is a Remotely command per test how you recommend integration testing a remote node with Pester/PoshSpec?

**Comment by dlwyatt** [comment]
If Pester exists on the remote system, you could just run `Invoke-Pester -Passthru` via `Invoke-Command`, and process the results locally.  The reason Microsoft didn't go that route with `Remotely` is that they need to be able to test systems that can't run Pester (ARM devices running in constrained language mode, mostly.)  So the Pester tests run on a full Windows machine, and they just execute commands against the more limited target machines.

**Comment by it-praktyk** [comment]
I assume that the issue can be closed now. Feel free to reopen if you need more assistance.

**Comment by bergmeister** [comment]
Thanks for the info, I came across this problem today and found this discussion very useful.

**Comment by rchaganti** [comment]
You may want to check out PSRemotely by @dexterPosh https://github.com/DexterPOSH/PSRemotely
