### ISSUE TITLE
Import-LocalizedData : Cannot find the Windows PowerShell data file 'RSpec.psd1'

### ISSUE THREAD

**Issue by justinconnell** [pester/Pester#756]
I install pester as part of a build process using:

if (!(Get-Module -Name Pester -ListAvailable)) { Install-Module -Name Pester -Scope CurrentUser -Force }

When running Invoke-Pester, the following error is generated:

Import-LocalizedData : Cannot find the Windows PowerShell data file 'RSpec.psd1' in directory 'C:\Users\Justin.Connell\Documents\WindowsPowerShell\Modules\Pester\4.0.2\en-GB\', or in any parent
culture directories.
At C:\Users\Justin.Connell\Documents\WindowsPowerShell\Modules\Pester\4.0.2\Pester.psm1:674 char:9
+         Import-LocalizedData -BindingVariable Script:ReportStrings -B ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Justin...n-GB\RSpec.psd1:String) [Import-LocalizedData], PSInvalidOperationException
    + FullyQualifiedErrorId : ImportLocalizedData,Microsoft.PowerShell.Commands.ImportLocalizedData

If I copy the content of the en-US directory to a new directory 'en-GB' everything works fine

**Comment by it-praktyk** [comment]
It should be resolved now by
https://github.com/pester/Pester/commit/c28597bb2438db69509ebb21cadcb98af391b8ab

Please provide data like describe in [Contributing to Pester](https://github.com/pester/Pester/wiki/Contributing-to-Pester) - the section 'Reporting a bug'.

**Comment by nohwnd** [comment]
@justinconnell the fix is merged but the new version is not published yet (it will be 4.0.3) I need to do one more fix, so I will publish it this evening. 

thanks @it-praktyk  for the fix.

**Comment by nohwnd** [comment]
Fixed by https://github.com/pester/Pester/pull/711
