### ISSUE TITLE
ScriptOutput is appending \r\n to the value.

### ISSUE THREAD

**Issue by nikhilmutkekar** [pester/Pester#767]
ScriptOutput is appending \r\n to the $status variable, returned from Invoke-VMScript.
Sample :
$status = get-vm -Name $vmname | Invoke-VMScript -ScriptText $scriptText

$a = "test"
It "Shoudl Match" {
$status.ScriptOutput | Should be $a
}

Output :
Expected: {test}
But was: {test\r\n}

**Comment by dlwyatt** [comment]
Are you certain $status.ScriptOutput doesn't actually have those characters?  Try this to be sure: `[System.Text.Encoding]::ASCII.GetBytes($status.ScriptOutput)`

**Comment by nikhilmutkekar** [comment]
When i do write-host $status.ScriptOutput , It just prints value as it is, without displaying \r\n on the terminal.

Executing [System.Text.Encoding]::ASCII.GetBytes($status.ScriptOutput) returned this output.
116 101 115 116 13 10

13 and 10 Ascii values indicate CR(\r) and LF(\n) respectively.

**Comment by nohwnd** [comment]
You can see the hidden characters in the output, because Pester post-processes the output to print the characters that are normally not visible (at least for `\n`, `\r` and `\r`) to make it easier to see why strings do not match.

**Comment by nikhilmutkekar** [comment]
Yes, Under "But Was : {Actual string}" I can see the hidden characters, but not when i print using write-host.
How do i get rid of hidden characters, which were not actually assigned.

**Comment by nohwnd** [comment]
When you print it using Write-Host it prints them in their normal (invisible) form. To get rid of them you need to replace them: 

``$status.ScriptOutput -replace "(`n|`r)"``

**Comment by dlwyatt** [comment]
Then pester is working as intended. It shows you the \r\n to let you know that the white space characters are there. PowerShell doesn't do that when you print the string to the console; it just writes the blank line.

**Comment by nikhilmutkekar** [comment]
-Replace option sounds good. Solved the issue ..Thanks
