### ISSUE TITLE
Why doesn't Parameter Filter based on InputObject type work?

### ISSUE THREAD

**Issue by markwragg** [pester/Pester#772]
Hi,

I'm trying to do a Mock parameter filter based on inputobject type but the Mock doesn't get called. Can you help me understand why?

```
Describe 'Mocking stop-process' {
    
    Mock Stop-Process { 
        Write-Host "InputObject is: $InputObject"
    } -ParameterFilter { $InputObject -is [System.Diagnostics.Process] }

    It 'Should mock stopping the notepad process' {
        { Get-Process 'notepad' | Stop-Process } | Should Be $null
    }

}
```

Without the ParameterFilter it returns: 

> InputObject is: System.Diagnostics.Process (notepad)

Thanks!

**Comment by dlwyatt** [comment]
It's a problem with your filter.  On the Stop-Process command, `-InputObject` is an array of processes, so `$InputObject -is [System.Diagnostics.Process]` returns false.  `$InputObject -is [System.Diagnostics.Process[]]` works, but you could probably just go with `-ParameterFilter { $InputObject }` (which will be true any time it's not null/empty.)

**Comment by markwragg** [comment]
You guys rock. :)
