### ISSUE TITLE
Test empty environment variable

### ISSUE THREAD

**Issue by glachancecmaisonneuve** [pester/Pester#773]
This is a simple test i tried.  It fails.  What am I missing?
```powershell
Describe "EMPTY" {
	BeforeAll {
	  $ENV:EMPTY = ""
	}
	Context "Test-Empty-EnvVar" {
		It "Checks that $ENV:EMPTY set in BeforeAll is EMPTY" {
		  $ENV:EMPTY | Should be ""
		}
	}
}
```

**Comment by nohwnd** [comment]
The `env` variable is not set to the empty string value, that is why it does not work, try running simply: 
```powershell
$env:a = "" 
$env:a -eq "" #<-- False
```

**Comment by glachancecmaisonneuve** [comment]
I think what had me confused was the error message that said Expected: {} But was:  {}
Fixed it with "$ENV:EMPTY" | Should be "" (instead of $ENV:EMPTY | Should be "")

**Comment by nohwnd** [comment]
Ok, but now you are not testing anything, you are just saying `"$null" -eq ""`, since you are setting the `env:EMPTY` to empty string that variable has no significance in the test, but maybe your example is just too simplified for me to see the whole picture.
