### ISSUE TITLE
Allow test code access to TestGroup names

### ISSUE THREAD

**Issue by dbroeglin** [pester/Pester#780]
In some cases it would help test readability and reduce duplication to allow for patterns like:

```
Describe "something" {
    BeforeEach {
        $Arg = (Get-TestGroupMetadata -Parent 1).Name -replace 'with argument (.*)','$1'
        $Subject = Invoke-Something -Arg $Arg
    }

    Context "with argument :10" {
        it "test 1" {
            $Subject.Max | Should Be ...
        }
        # other tests on subject
    }

    Context "with argument @:10" {
        it "test 1" {
            $Subject.Max | Should Be ...
        }
       # other tests on subject
    }
}
```

The idea here is that subject can be completely initialized by the context description thus reducing boilerplate code to setup the subject in each context. It is kind of a complementary approach to the one provided by 'It -TestCases' but where only context initialization is generic, "It" blocks on the other hand might be very different from one context to another. 

`Get-TestGroupMetadata` could return test group names, type (Describe, Context, It),  tags and even "test cases" and current "test case".

What do you think ?

**Comment by nohwnd** [comment]
@dbroeglin I think I missed the point of what your proposal does, I don't get what `$Arg` is supposed to be. :) Are you saying that we should allow the test code to parse the description of the test to extract the values for the test? 

What is the code that we are required to type now, and what do you propose to change?

**Comment by it-praktyk** [comment]
@dbroeglin, can you extend a description of your request?

**Comment by it-praktyk** [comment]
Is https://github.com/pester/Pester/issues/447 partially related?

**Comment by it-praktyk** [comment]
@dbroeglin, due to lack of additional information your request is marked now as 'Feature - refused' and closed. Feel free to reopen it if you can provide more data as requested. Thank you for understanding.

**Comment by dbroeglin** [comment]
@nohwnd My apologies for the _very_ delayed answer, I'm afraid I did not see the GitHub notification until today. 

Yes, you are right, what I had in mind is that `Get-TestGroupMetadata` returns information about the current test context. This would allow the test to parameter itself based on the context or test case description.

Without this feature, I would have to duplicate the argument in each context's BeforeEach block, and would have to create a new identical BeforeEach block for each context, like that:

```
Describe "something" {
    Context "with argument :10" {
        BeforeEach {
          $Subject = Invoke-Something -Arg ":10"
        }
        it "test 1" {
            $Subject.Max | Should Be ...
        }
        # other tests on subject
    }

    Context "with argument @:10" {
        BeforeEach {
          $Subject = Invoke-Something -Arg "@:10"
        }
        it "test 1" {
            $Subject.Max | Should Be ...
        }
       # other tests on subject
    }
}
```
 
Actually (heavily drawing on Ruby's rspec lib here). A method called Subject could make things even drier, for tests that rely heavily on preparing a $Subject object for the It blocks to validate. But maybe this would be too much.
```
Describe "something" {
    Subject {
        $Arg = (Get-TestGroupMetadata -Parent 1).Name -replace 'with argument (.*)','$1'
        Invoke-Something -Arg $Arg
    }

    Context "with argument :10" {
        it "test 1" {
            $Subject.Max | Should Be ...
        }
        # other tests on subject
    }

    Context "with argument @:10" {
        it "test 1" {
            $Subject.Max | Should Be ...
        }
       # other tests on subject
    }
}
```

An alternative to `Get-TestGroupMetadata -Parent 1` (which would be generic but quite ugly) could be to introduce some _automatic variables_ like `$PesterContext.Name`, `$PesterDescribe.Name`, etc.

What do you think ?
