### ISSUE TITLE
Do away with the opening block when calling new-fixture

### ISSUE THREAD

**Issue by TofuBug** [pester/Pester#783]
Well this STARTED as a fairly simple change (Still think it's fairly simple, but expanded it out to cover more use cases that I had not considered in my original change).

So on to the "issue" (Definitely don't consider this something broken rather just not as concise as I normally like)

Right now a standard Script.Tests.Ps1 looks like this after new-fixture is called

```PowerShell
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path) -replace '\.Tests\.', '.'
. "$here\$sut"

Describe "junk" {
    It "does something useful" {
        $true | Should Be $false
    }
}
```
The top block here:

```PowerShell
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path) -replace '\.Tests\.', '.'
. "$here\$sut"
```
Is just plain ugly to look at (Yeah it's code that generates a path to the Tests Directory, and the ps1 file but its code that is essentially copied and pasted verbatim and that's pretty close to hard coding values that don't need to be hard coded) and worse if you are writing unit test for existing scripts new-fixture doesn't really help you and you have to type all that out yourself

So on my development system I modified Pester.psm1 (2 new functions, 2 lines added to the Invoke-Pester function, and a final line added towards the end of the file).

I also added Tests in Pester.Tests.ps1 for the 2 new functions

The First Function takes a path (could technically be ANY path) and returns a hashtable that has that paths: File Name (Name), Full path to the file (FullName) and parent directory (Directory)

It also accepts no path or a "" path and returns a default hashtable with default properties

```PowerShell
function Set-FileProperties {
    param ([string] $Path = "")
    
    # If we actually have a path and it is a valid path set specific values. Otherwise set Default values
    if ($Path -ne "" -and (Test-Path -Path $Path)) { @{FullName = $Path; Name = Split-Path -Leaf $Path; Directory = Split-Path -Parent $Path; Exists = $true} } 
    else { @{FullName = "Default Full Name"; Name = "Default Name"; Directory = "Default Directory"; Exists =  $false} }
}
```

And the Unit Tests to go with Set-FileProperties

```PowerShell
Describe 'Set-FileProperties' -Tag "Set-FileProperties" {
    Setup -File "Directory\SomeFile.ps1"

    It "Should return `"Default Name`", `"Default Full Name`" and `"Default Directory`" with no parameters (-Path = `"`")" {
        $DefaultFileProperties = Set-FileProperties
        $DefaultFileProperties.Name | Should Be "Default Name"
        $DefaultFileProperties.FullName | Should Be "Default Full Name"
        $DefaultFileProperties.Directory | Should Be "Default Directory"
        $DefaultFileProperties.Exists | Should Be $false
    }

    It "Should return properly parsed and populated paths for `"SomeFile.ps1`"" {
        $FileProperties = Set-FileProperties -Path (Join-Path "TestDrive:" "Directory\SomeFile.ps1")
        $FileProperties.Name | Should Be "SomeFile.ps1"
        $FileProperties.FullName | Should Be "TestDrive:\Directory\SomeFile.ps1"
        $FileProperties.Directory | Should Be "TestDrive:\Directory"
        $FileProperties.Exists | Should Be $true

    }
}

```

Finally Test Results for running these Tests ```Invoke-Pester .\Pester.Tests.ps1 -Tag Set-FileProperties```

```PowerShell
Executing all tests in .\Pester.Tests.ps1 with Tags Set-FileProperties

Executing script .\Pester.Tests.ps1

  Describing Set-FileProperties
    [+] Should return "Default Name", "Default Full Name" and "Default Directory" with no parameters (-Path = "") 72ms
    [+] Should return properly parsed and populated paths for "SomeFile.ps1" 16ms
Tests completed in 89ms
Tests Passed: 2, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0 
```

Second function takes the fully qualified path to the Tests.ps1 file provided down in Invoke-Pester function and it Creates a PSObject with properties corresponding to each of the 7 different PowerShell file extensions (created by calling Set-FileProperties on each path) Finally this "helper" object is added to the global scope to be available when the tests are run.

```PowerShell
function Set-CurrentSUT {
    param ([string]$Path = "")

    # Load up CurrentSUT's properties
    # Convert path to Tests file to all possible PowerShell files (.ps1, .psd1, .psm1, .pssc, .psrc, .ps1xml, and .cdxml)    
    $CurrentSUT = New-Object -TypeName "System.Management.Automation.PSObject" -Property @{
        TestFile = Set-FileProperties -Path $Path
        ScriptFile = Set-FileProperties -Path $Path.Replace(".Tests.",".")
        ModuleFile = Set-FileProperties -Path $Path.Replace(".Tests.ps1",".psm1")
        DataFile = Set-FileProperties -Path $Path.Replace(".Tests.ps1",".psd1")
        SessionConfigurationFile = Set-FileProperties -Path $Path.Replace(".Tests.ps1",".pssc")
        RoleCapabilityFile = Set-FileProperties -Path $Path.Replace(".Tests.ps1",".psrc")
        Ps1XmlFile = Set-FileProperties -Path $Path.Replace(".Tests.ps1",".ps1xml")
        CdXmlFile = Set-FileProperties -Path $Path.Replace(".Tests.ps1",".cdxml")
    }
    
    & $SafeCommands['New-Variable'] -Name CurrentSUT -Scope Global -Value $CurrentSUT -force
}
```

And the Tests for this function

```PowerShell
Describe 'Set-CurrentSUT' -Tag "Set-CurrentSUT" {
    Setup -File SomeFile.ps1
    Setup -File SomeFile.psm1
    Setup -File SomeFile.psd1
    Setup -File SomeFile.Tests.ps1
    
    # Save CurrentSUT Test Script Full Path to restore to loaded values after this Describe block is run
    $TestFileFullName = $CurrentSUT.TestFile.FullName

    Context "No Parameters" {
        Set-CurrentSUT | Out-Null
        $CurrentSUT | Get-Member -MemberType NoteProperty | % { 
            It "$($_.Name) Should Contain Default Values" {
                $CurrentSUT."$($_.Name)".Name | Should Be "Default Name"
                $CurrentSUT."$($_.Name)".FullName | Should Be "Default Full Name"
                $CurrentSUT."$($_.Name)".Directory | Should Be "Default Directory"
                $CurrentSUT."$($_.Name)".Exists | Should Be $false
            }
        }
    }

    Context "Passing in a Test File" {
        Context "Should Have Information for the Test, Module, Module Manifest and Script files for SomeFile.Tests.ps1" {
            $TestPath = Join-Path "TestDrive:" "SomeFile.Tests.ps1"
            Set-CurrentSUT -Path $TestPath
            $FileProperties = $CurrentSUT | Get-Member -MemberType NoteProperty | ? { $CurrentSUT."$($_.Name)".Name -ne "Default Name" }
            It "Should have 4 File Types with populated properties" {
                $FileProperties.Count| Should Be 4
            }

            It "Should have Information for SomeFile.Tests.ps1" {
                $CurrentSUT.TestFile.Name | Should Be "SomeFile.Tests.ps1"
                $CurrentSUT.TestFile.FullName | Should Be "TestDrive:\SomeFile.Tests.ps1"
                $CurrentSUT.TestFile.Directory | Should Be "TestDrive:\"
            }
            It "Should have Information for SomeFile.ps1" {
                $CurrentSUT.ScriptFile.Name | Should Be "SomeFile.ps1"
                $CurrentSUT.ScriptFile.FullName | Should Be "TestDrive:\SomeFile.ps1"
                $CurrentSUT.ScriptFile.Directory | Should Be "TestDrive:\"
            }
            It "Should have Information for SomeFile.psm1" {
                $CurrentSUT.ModuleFile.Name | Should Be "SomeFile.psm1"
                $CurrentSUT.ModuleFile.FullName | Should Be "TestDrive:\SomeFile.psm1"
                $CurrentSUT.ModuleFile.Directory | Should Be "TestDrive:\"
            }
            It "Should have Information for SomeFile.psd1" {
                $CurrentSUT.DataFile.Name | Should Be "SomeFile.psd1"
                $CurrentSUT.DataFile.FullName | Should Be "TestDrive:\SomeFile.psd1"
                $CurrentSUT.DataFile.Directory | Should Be "TestDrive:\"
            }
        }

        Context "Remaining File Types have Default Properties" {
            $DefaultFileProperties = $CurrentSUT | Get-Member -MemberType NoteProperty | ? { $CurrentSUT."$($_.Name)".Name -eq "Default Name" }
            It "Should have 4 File Types with default properties" {
                $DefaultFileProperties.Count| Should Be 4
            }
            $DefaultFileProperties | % {
                It "$($_.Name) Should have Default Values" {
                    $CurrentSUT."$($_.Name)".Name | Should Be "Default Name"
                    $CurrentSUT."$($_.Name)".FullName | Should Be "Default Full Name"
                    $CurrentSUT."$($_.Name)".Directory | Should Be "Default Directory"
                    $CurrentSUT."$($_.Name)".Exists | Should Be $false
                }
            }
        }
    }
    
    # Reset CurrentSUT back to loaded values for running these tests in case it is used later
    Set-CurrentSUT -Path $TestFileFullName
}

```

Finally the results of running ```Invoke-Pester .\Pester.Tests.ps1 -Tag Set-CurrentSUT```

```PowerShell
Executing all tests in .\Pester.Tests.ps1 with Tags Set-CurrentSUT

Executing script .\Pester.Tests.ps1

  Describing Set-CurrentSUT

    Context No Parameters
      [+] CdXmlFile Should Contain Default Values 122ms
      [+] DataFile Should Contain Default Values 12ms
      [+] ModuleFile Should Contain Default Values 11ms
      [+] Ps1XmlFile Should Contain Default Values 14ms
      [+] RoleCapabilityFile Should Contain Default Values 17ms
      [+] ScriptFile Should Contain Default Values 16ms
      [+] SessionConfigurationFile Should Contain Default Values 12ms
      [+] TestFile Should Contain Default Values 14ms

    Context Passing in a Test File

      Context Should Have Information for the Test, Module, Module Manifest and Script files for SomeFile.Tests.ps1
        [+] Should have 4 File Types with populated properties 57ms
        [+] Should have Information for SomeFile.Tests.ps1 13ms
        [+] Should have Information for SomeFile.ps1 14ms
        [+] Should have Information for SomeFile.psm1 12ms
        [+] Should have Information for SomeFile.psd1 16ms

      Context Remaining File Types have Default Properties
        [+] Should have 4 File Types with default properties 32ms
        [+] CdXmlFile Should have Default Values 15ms
        [+] Ps1XmlFile Should have Default Values 11ms
        [+] RoleCapabilityFile Should have Default Values 14ms
        [+] SessionConfigurationFile Should have Default Values 14ms
Tests completed in 425ms
Tests Passed: 18, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0 
```

Now to the 2 lines in the Invoke-Pester functions

Line 1 Setup CurrentSUT for current Test file based on each $testScript in the $testScripts collection

```PowerShell
foreach ($testScript in $testScripts)
{
    try
    {
        Set-CurrentSUT -Path $testScript.Path

```

Line 2 (The finally block to the try block above) Resets CurrentSUT back to the default values  (for cleanup but also for future test authoring)

```PowerShell
finally
{
    Set-CurrentSUT | Out-Null

```

Last but not least towards the bottom of Pester.psm1 is one final line this sets up so when you explicitly call Import-Module pester (or after the first time you tab complete the First Describe keyword and pester is implicitly imported) $CurrentSUT will be available in the global scope with all file types present but with default values (Basically allowing for me and anyone else who like to be lazy and use intellisense in the ISE while writing my Tests)

```PowerShell
Set-CurrentSUT | Out-Null

& $script:SafeCommands['Export-ModuleMember'] Describe, Context, It, In, Mock, Assert-VerifiableMocks, Assert-MockCalled, Set-TestInconclusive

```
That's basically it just a relatively simple concise helper object with the kind of testing meta information you might want to easily reference when writing tests

So now if we go back to our original Tests.ps1 script we can rewrite something like this

```PowerShell
Describe "Testing $($CurrentSUT.ScriptFile.Name) using Tests in $($CurrentSUT.TestFile.Name)" {
    It "does something useful" {
        $true | Should Be $false
    }
}
```

And the output looks like this

```PowerShell
Executing all tests in .\Junk.Tests.ps1

Executing script .\Junk.Tests.ps1

  Describing Testing Junk.ps1 using Tests in Junk.Tests.ps1
    [-] does something useful 93ms
      Expected: {False}
      But was:  {True}
      at <ScriptBlock>, C:\Users\tofub_000\Desktop\Junk.Tests.ps1: line 3
      3:         $true | Should Be $false
Tests completed in 93ms
Tests Passed: 0, Failed: 1, Skipped: 0, Pending: 0, Inconclusive: 0 
```

Or you can use $CurrentSUT for more advanced Testing imagine needing to Validate that a .psm1 file has a matching .psd1 file

```PowerShell
Describe "Testing $($CurrentSUT.ScriptFile.Name) with $($CurrentSUT.TestFile.Name) Tests" {
    if ($CurrentSUT.ModuleFile.Exists) {
        Context "Has a Module" {
            It "Found Module File $($CurrentSUT.ModuleFile.Name) does it have a matching Module Manifest (psd1) file?" {
                $CurrentSUT.DataFile.FullName | Should Exist
            }
        }
    }
}

```

if there is no .psm1 file in that directory the test results look like this

```PowerShell
Executing all tests in .\Test.Tests.ps1

Executing script .\Test.Tests.ps1

  Describing Testing Test.ps1 with Test.Tests.ps1 Tests
Tests completed in 0ms
Tests Passed: 0, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0 
```

If there IS a .psm1 file but no .psd1 file in that directory the same test's result looks like this now

```PowerShell
Executing all tests in .\Test.Tests.ps1

Executing script .\Test.Tests.ps1

  Describing Testing Test.ps1 with Test.Tests.ps1 Tests

    Context Has a Module
      [-] Found Module File Test.psm1 does it have a matching Module Manifest (psd1) file? 117ms
        Expected: {Default Full Name} to exist
        at <ScriptBlock>, C:\Users\tofub_000\Desktop\Test.Tests.ps1: line 5
        5:                 $CurrentSUT.DataFile.FullName | Should Exist
Tests completed in 117ms
Tests Passed: 0, Failed: 1, Skipped: 0, Pending: 0, Inconclusive: 0 
```

So with the ability to not only easily reference all the potential powershell file types that might be part of a system under test but the ability to use that information to write tests that can handle various complicated testing scenarios like the module is missing a module manifest example above

Now I am admittedly VERY new to using pester and I'm learning as I go but this seemed like a pretty easy feature to add that saves the need for extra code in each tests.ps1 file.

I did not take the time to dig into the New-Fixture function one because most of the test's i'm writing right now are for existing scripts, and 2 because if other people like having that same script block at the top of ALL of their test scripts this little change doesn't break that.

Zip file attached is my modified Pester.psm1 and Pester.Tests.ps1

[Pester.zip](https://github.com/pester/Pester/files/1034515/Pester.zip)

**Comment by TofuBug** [comment]
Decided to go ahead and makes some more changes from my initial post

Added the following to Pester.psm1

```PowerShell
function Set-CurrentSUT {
    param ([string]$Path = "")

    $CurrentSUT = New-Object -TypeName psobject -Property @{
        FullName = if ($Path -eq "") { 
            "This will be the full Path to the Current System Under Test Script File."
        } 
        else { 
            Resolve-Path ($Path.Replace(".Tests.", ".")) 
        }
        Name = if ($Path -eq "") {
            "This will be just the name of the Current System Under Test Script File."
        } 
        else { 
            Split-Path -Leaf (Resolve-Path($Path.Replace(".Tests.", ".")))
        }
        Directory = if ($Path -eq "") {
            "This will be the Directory the Current System Under Test Script File is in."
        } 
        else {
            Split-Path -Parent (Resolve-Path($Path.Replace(".Tests.", ".")))
        }
    }
    
    & $SafeCommands['New-Variable'] -Name CurrentSUT -Scope Global -Value $CurrentSUT -force
}
```

And now down in Invoke-Pester


```PowerShell
foreach ($testScript in $testScripts)
{
    try
    {
        Set-CurrentSUT -Path $testScript.Path
```
And down in the that try's finally block

```PowerShell
finally
{
    Exit-MockScope
    $pester.LeaveTestGroup($testScript.Path, 'Script')
    Set-CurrentSUT | Out-Null
}
```

And finally at the bottom of the file

```PowerShell
# Setup CurrentSUT object with dummy info for ISE to pick it up as intellisense

Set-CurrentSUT | Out-Null

& $script:SafeCommands['Export-ModuleMember'] Describe, Context, It, In, Mock, Assert-VerifiableMocks, Assert-MockCalled, Set-TestInconclusive
```


So now when I'm writing tests after I hit Tab (because I'm lazy) to Tab Complete that first Describe the module creates the `$CurrentSUT` object with all three of its dummy variables so now I have intellisense access to the CurrentSUT "object" when writing my tests.

As each Tests.ps1 runs it recreates CurrentSUT with the applicable values and at the end resets it back to the generic values

So this

```PowerShell
Describe "$($CurrentSUT.Name) Tests" {
    It "$($CurrentSUT.Directory) Exists" {
        $CurrentSUT.Directory | Should Exist
    }
    It "Run $($CurrentSUT.FullName) and asset true" {
        . $CurrentSUT.FullName
        $true | Should Be $true
    }
}
```

Executes as

```PowerShell
Executing all tests in .\junk.Tests.ps1

Executing script .\junk.Tests.ps1

  Describing junk.ps1 Tests
    [+] C:\Users\a-rjs39534\desktop Exists 89ms
    [+] Run C:\Users\a-rjs39534\desktop\junk.ps1 and asset true 24ms
Tests completed in 113ms
Tests Passed: 2, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0 
```

And $CurrentSUT is back to its defaults

```PowerShell
PS >$CurrentSUT | fl 


FullName  : This will be the full Path to the Current System Under Test Script File.
Name      : This will be just the name of the Current System Under Test Script File.
Directory : This will be the Directory the Current System Under Test Script File is in.
```

Little cleaner than what I started out with and more useful than a single property helper object

[Pester.zip](https://github.com/pester/Pester/files/1032701/Pester.zip)

**Comment by it-praktyk** [comment]
@TofuBug, please read @nohwnd's decision in #57.

**Comment by nohwnd** [comment]
@TofuBug I re-read you code but I always got lost in the middle. If you want to propose a change then please send Pull Request, it will show the changes in code and that I can understand. :) I think your are solving a non-issue. From what I saw, people mostly put `. $PSScriptRoot\MyCode.ps1` on top of their test script, unless they need PSv2 compatibility, and that's it.

**Comment by TofuBug** [comment]
I tried to do a pull request back when I first submitted it and for some reason it would not let me.

My whole thing (and this may JUST be me) is I don't like to have to retype things especially things like a manual setup to be sure my pathing is correct for the tests to run correctly I believe that kind of scaffolding should be built into the testing system itself. You shouldn't need to put extra stuff at the top of your tests just to simply run them.

The other side of it is the multiple kinds of powershell files you can have, i.e. having the testing framework itself parse out and identify all potential files the test might relate to and returning that information in a collection that exposes a "Does this test test this kind of file?" boolean along with the pathing for said file, gives you  at least sudo-metadata that's directly usable in your tests. Also it's metadata that can be used to make conditional branching in the same test file to handle multiple types of tiles to test.

To me this is way more clean feeling

```
Describe "$($CurrentSUT.ScriptFile.Name)" {
    It "Test a PS1 file" {
        $true | Should Be $false
    }
}
Describe "$($CurrentSUT.DataFile.Name)" {
    It "Test a PSD1 file" {
        $true | Should Be $false
    }
}
Describe "$($CurrentSUT.ModuleFile)" {
    It "Test a PSM1 file" {
        $true | Should Be $false
    }
}
Describe "$($CurrentSUT.TestFile)" {
    It "Test the Test File (probably more likely use it for some kind of reference)" {
        $true | Should Be $false
    }
}
```


than this
```
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path) -replace '\.Tests\.', '.'
. "$here\$sut"

Describe ".\Untitled3.ps1" {
    It "does something useful" {
        $true | Should Be $false
    }
}
```

even though the first set of code has more lines each Describe block clearly tell you what you are testing, and each could independently be cut out of the script without affecting the others. and the best part no having to remember either to run New-Fixture or Heaven forbid having to manually type out and remember the $here and $sut lines at the top of your file because you started writing your tests BEFORE you wrote you powershell script as TDD properly dictates. The information to get to the test AND the Systems under test are all part of the testing system itself.

Sorry to run on with it. I feel like it's a pretty simple idea, and one that isn't really to fix anything broken just to make it a little simpler and more flexible to write tests. it's funny how much it takes to spell out even a simple idea when you are asked to.

**Comment by nohwnd** [comment]
@TofuBug I am still not convinced, sorry. 

I never had problems with importing functions to my tests, either they are in a file right next to my test file, or I need to load them from module, and that I do in a single place anyway. 

I don't recall ever importing more that one code file to my tests, so having to navigate through an object that lists every possible file type seems like an overkill. And I don't want Pester to import all files it finds, so I would have to tell it what to load anyway.

You could write a function `Import-File` and do `$sut = Import-File -FileType Module -PassThru`, which would return `FileInfo` object. That would solve the problem with PSv2 compatibility quite nicely. And you could use it in your test desctiption as `"testing in file $($sut.BaseName)"`, but I also don't recall ever needing the path of the code file.

So unless you need to support v2, importing most files is really as easy as `$PSScriptRoot\MyFile.ps1`.

**Comment by it-praktyk** [comment]
> I tried to do a pull request back when I first submitted it and for some reason it would not let me.

I think that you tried to push your changes directly to Pester\Pester repository. The first you need fork Pester\Pester repository to yours GitHub namespace.

Please let me know if do you need detailed how to. If you have implemented changes on your computer please don't revoke them or so. Everything can be reused in an almost easy way - git is super.

**Comment by TofuBug** [comment]
@nohwnd I'm sorry but i'm confused about two points in your retort

First you keep mentioning 2.1 compatibility

I made this modification to help me out writing test on a system with Pester 4.0.3 which STILL has the need to manually type out pathing scaffolding at the begining of your test file 


Second you seem to be confused about that this is doing.

This is **NOT** importing whole files into the testing system

This is (based on the general rules of pester i.e. that File.PS1 matches File.Tests.PS1) just an expansion of that to cover all types of PowerShell files

and ALL it is doing is sticking 3 strings, and 1 boolean for each potential type of PowerShell file you could test into an object and adding it to a simple hash table

the physical files are themselves never imported this just gives you easy consistent access to all you need to 

- Tell if a particular type of PowerShell file exists that matches to the Test file
- Get the path of any previously existing files

that's it.

Also you keep talking about how its easy to just write Import-file and all that and that's fine and yes it is easy, my point is i shouldn't HAVE to do that to just write a test.

Now you also mentioned never needing the path to the code file then what is 

```
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path) -replace '\.Tests\.', '.' 
```

? That seems an awfully lot like the path to the code file (unless i'm missing something here)

Now granted I have not used pester as long as other people here (LONG time C#er) but I have used powershell quite a lot, so my views on this might not line up with others but I feel like this does at least add value to the testing system by giving you flexibility that does not rely on having to hard code pathing into every test you write

Say for instance you want to have a test that validates DSC resources on the most basic level - Does the DSC code file have a properly formed DSC resource?

```
Describe "DSC Validations" {
    Context "Validating is proper DSC Resource" {
        It "Is $($CurrentSUT.ScriptFile.Name) valid DSC?" {
            $Content = Get-Content -Path $CurrentSUT.ScriptFile.FullName
            (Validate-DSC $Content) | Should Be $true
        }
    }
}
```

Now imagine I want to test potentially hundreds of DSC resources

with my code like this NOTHING about the files under test are hard coded in my tests I can reuse this code over and over and over either through a code generation template system or a CI/CD process and it looks neat and concise it's human readable 


Or consider wanting to test that all the necessary files for a module are there 


```
Describe "Module Testing" {
    Context "Supporting Files for $($CurrentSUT.ModuleFile.Name)" {
        it "Module is Valid Power Shell" {
            $ModuleContent = Get-Content -Path $CurrentSUT.ModuleFile.FullName
            (Validate-Module $ModuleContent) | Should Be $true
        }
        It "Should have a PSD1 file" {
            $CurrentSUT.DataFile.Exists | Should Be $true
        }
    }
}
```

Again human readable and reusable.

Maybe i'm going at this the wrong way but as a personal rule I never develop something with JUST that task or that test in mind. I have lots of VERY similar things I have to deal with so i'm ALWAYS thinking in terms of re-usability of my code.

And not just re-usability, but re-usability that is easily conveyed to someone new (we have a lot of turn over in some areas that pester is useful) and to me 

```
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path) -replace '\.Tests\.', '.'
. "$here\$sut"

Describe ".\Untitled3.ps1" {
    It "does something useful" {
        $true | Should Be $false
    }
}
```

"Well the actual test is down here in the describe box and the helpful system has hard coded the file we are testing into the describe block but to actually DO something on that file e.g. import, read content, etc we have to have this $here and $sut variables which basically convert the file path of the test file (this file you are writing) into the path of the file you want to test. Unless of course you don't want to test a regular PS1 file and say a Module or a run a test using the Role Based Administration or using Session Configuration files, well then you have to do some more manual modification"

vs


```
Describe "$($CurrentSUT.ScriptFile.Name)" {
    It "does something useful" {
        $true | Should Be $false
    }
}
```

"So your tests are organize by Describe blocks (and sometimes Context blocks) and It blocks. The $CurrentSUT object gives you quick human readable (and intellisense) access to all the potential types of PowerShell files you can test against. Want to test a module? Just call import-module $CurrentSUT.ModuleFile.FullName.  Need to know if you should test a particular type of PowerShell file (say along with a Session Configuration File)

```
if ($CurrentSUT.SessionConfigurationFile.Exists) {
    Describe "With Session Config" {
        Context "Testing $($CurrentSUT.ScriptFile.Name) with Session Config $($CurrentSUT.SessionConfigurationFile.Name)" {
            It "Test Something" {
                $true | Should Be $false
            }
        }
    }
}
else
{
    Describe "Without Session Config" {
        Context "Testing $($CurrentSUT.ScriptFile.Name)" {
            It "Test Something" {
                $true | Should Be $false
            }
        }
    }
}
```

That will do you."

With my modifications I can much easier describe how to not only write tests but how to write tests but how to write test for different scenarios, AND the code itself basically spells out what it is doing

In the end I just hate seeing what is essentially hard coded repetitive code that should be refactored into a more reusable generic code. To me that's ALL i'm doing with this.

Though to be clear I'm perfectly fine with this just being something only I find useful, and I do find it VERY useful both in terms of readability and re-usability and teach-ability and consistency 

It's just something I felt like sharing for anyone that might think like me when it comes to how they code

**Comment by nohwnd** [comment]
@TofuBug 

>First you keep mentioning 2.1 compatibility

If we put this into the framework we need to keep it Powershell 2 compatible. If you are just sharing your thoughts, then this is a good place to discuss, but not a good place to publish, the issue will be closed sooner or later, and then it will be very unlikely to be discovered by anyone. Write a blog post, and tweet to @pspester, I will happily retweet.

>This is (based on the general rules of pester i.e. that File.PS1 matches File.Tests.PS1) just an expansion of that to cover all types of PowerShell files
> and ALL it is doing is sticking 3 strings, and 1 boolean for each potential type of PowerShell file you could test into an object and adding it to a simple hash table

There are a lot of assumptions you are making. We do not enforce any of those rules about placements of files or naming. You only need to name your files *.Tests.ps1 if your want to autodetect them, and even that can be parametrized if someone asks for it, and posts PR.

> $here = Split-Path -Parent $MyInvocation.MyCommand.Path
> $sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path) -replace '\.Tests\.', '.' 

You are not required to use the `$sut` & `$here` code, how you import your code in your tests is up to you. Mostly people just use `. $PSScriptRoot\MyFile.ps1`. That piece of code only contains general Powershell concepts, nothing Pester specific, and does not impose any limits on how people name their code, or where they place it. If someone wants to put all of their tests in one file and store it locally, and put all of his production code on a network share, he is free to do so.

I am sorry, but we won't be adding this.
