### ISSUE TITLE
Why are these Pester-internal commands exported?

### ISSUE THREAD

**Issue by alx9r** [pester/Pester#784]
Invoking

    Get-Command -Module Pester | % { help $_.Name } | ? {$_.Synopsis -like '*You do not need to call it directly*' } | % Name

yields this list of Pester internal commands that are exported:

* `Get-MockDynamicParameters`
* `Invoke-Mock`
* `SafeGetCommand`
* `Set-DynamicParameterVariables`

Why are these commands exported?  Can their exposure in the public API be deprecated so that we don't have to worry about breaking user test code that uses those functions but probably shouldn't be?

**Comment by dlwyatt** [comment]
They're all used when you call a mocked command.  When Pester tests are executing, scopes jump back and forth all over the place between the test script, Pester's internal stuff, and sometimes other modules as well (if you've imported things to test.)

**Comment by alx9r** [comment]
Ok.  That makes sense.  Thanks @dlwyatt.

**Comment by nohwnd** [comment]
I want to revisit this, based on the usage of the command it should be possible to either pass the command  object as a parameter to a scriptblock invoked in user scope. e.g.:

```powershell
function Describe ($Name, $ScriptBlock) {
    $wrapper = { 
        param ($sb, $callback)   
        & $sb
        & $callback 
    }
    $userSessionState = Get-ScriptBlockScope $ScriptBlock
    Set-ScriptBlockScope $wrapper $userSessionState

    & $wrapper $sb (Get-Command InternalPesterFunction)

}    
```

Or if the code is called from a generated function, like Invoke-Mock we should be able to lookup Pester module and invoke the internal function via the `&($pesterModule) {}`. 

I also experimented with dynamically publishing functions from a module but it does not work, not sure if I am doing something wrong or it just does not work.

**Comment by nohwnd** [comment]
Okay looked into this a bit deeper, and found what seems to be a great solution. When creating the function we have it's session state. So that sesionstate gives me the function info, on that info I attach an object. This object points to command object of Invoke-Mock, and also to safe Get-Variable. In the function body I then use $MyInvocation.MyCommand to reach this object and Pester and invoke the functions via & as usual.  I can also add more properties to this object so no local (and hence conflicting) variables are needed. The here an excerpt from the mock prototype that would use this: 
```powershell 

        if ($canCaptureArgs) {
            `$MyInvocation.MyCommand.Pester.Args = `$MyInvocation.MyCommand.Pester.Get_Variable -Name args -ValueOnly -Scope Local -ErrorAction `$MyInvocation.MyCommand.Pester.ErrorAction
        }

        if (`$MyInvocation.MyCommand.Pester.PSCmdlet = `$MyInvocation.MyCommand.Pester.Get_Variable -Name PSCmdlet -ValueOnly -Scope Local -ErrorAction `$MyInvocation.MyCommand.Pester.ErrorAction) {
            if (`$null -ne `$MyInvocation.MyCommand.Pester.PSCmdlet) {
                `$MyInvocation.MyCommand.Pester.SessionState = `$MyInvocation.MyCommand.Pester.PSCmdlet.SessionState
                `$MyInvocation.MyCommand.Pester.PSCmdlet = `$null
            }
        }
    }
    `$MyInvocation.MyCommand.Pester.Invoke_Mock -CommandName '$commandName' -ModuleName '$moduleName' -BoundParameters $PSBoundParameters -ArgumentList `$MyInvocation.MyCommand.Pester.Args -CallerSessionState `$MyInvocation.MyCommand.Pester.SessionState -FromBlock '$block' -MockCallState `$MyInvocation.MyCommand.Pester.MockCallState
}
```

**Comment by nohwnd** [comment]
They are not anymore, the state is passed on the MyInvocation object as described above.
