### ISSUE TITLE
Allow specifying run only one It inside a Describe

### ISSUE THREAD

**Issue by rebro-msft** [pester/Pester#787]
I would like the ability to run a particular It inside a Describe.  
For example:  Invoke-Pester [fileName] -TestCase DescribeName -It ItName

My scenario:  I am developing a new feature using Test-Driven Development.  I don't want to have to run all the It's in a Describe block just to see if one of them passed.  I would like to run only the It I am using as part of that TDD iteration.

**Comment by it-praktyk** [comment]
Please read: 
- https://github.com/pester/Pester/issues/721
- https://github.com/pester/Pester/issues/461

**Comment by it-praktyk** [comment]
@rebro-msft, is it your question answered?

**Comment by rebro-msft** [comment]
Thanks for pointing to the open issues on this topic.  It sounds like this will be coming in v4.0 (if I read it all correctly), which is awesome.  I will close this issue.
