### ISSUE TITLE
is there an equiv to -whatif

### ISSUE THREAD

**Issue by davidwallis3101** [pester/Pester#788]
I'm using pester to do some integration testing and I would like to see which tests would run when using tags, is there something similar to -what if so I can see what tests would run?

(ps I wasn't really looking to re-write all my tests to support a whatif param before anyone suggests that!)

Thanks

**Comment by nohwnd** [comment]
There is not, the code needs to run to actually discover the tests. It could work if the tests were following some strict rules ( I think I described them in the "run single test" issue. ), which would allow us to run the code without actually running the tests ( we would be able to split test discovery from test run) but with the current implementation and how people write tests it's not really possible.

Jakub Jareš

.NET, Pester, PowerShell
t 00420603800578<tel:00420603800578>
e me@jakubjares.com<mailto:me@jakubjares.com>
t @nohwnd

8. 6. 2017 v 14:16, David Wallis <notifications@github.com<mailto:notifications@github.com>>:


I'm using pester to do some integration testing and I would like to see which tests would run when using tags, is there something similar to -what if so I can see what tests would run?

(ps I wasn't really looking to re-write all my tests to support a whatif param before anyone suggests that!)

Thanks

**Comment by davidwallis3101** [comment]
Thanks - Ill think of something else :)

**Comment by it-praktyk** [comment]
I assume that the issue can be closed now. Feel free to reopen if you need more assistance.
