### ISSUE TITLE
Allow Mock scope to be limited to an It block

### ISSUE THREAD

**Issue by b4tt1enet** [pester/Pester#789]
The example below demonstrates the behavior I'm describing and wish to change.

Running unit tests against this script file "TestMockScope.ps1":

```PowerShell
Function Test-MyFunction {
    Param($Param)

    $Value = Mock-Function -Param $Param

    Return $Value
}
    
Function Mock-Function {
    Param($Param)

    Return "Default return value of Mock-Function with parameter $Param"
}
```

...with this test file:

```PowerShell
. "$(Split-Path -Parent $MyInvocation.MyCommand.Path)\TestMockScope.ps1"

Describe "Testing Mock Scope" {

    Context 'Test-MyFunction' {
        
        It 'UNIT TEST 1' {
            Mock -CommandName Mock-Function -MockWith { return 'Return value of first mock' } -ParameterFilter { $Param -eq 'ABC' }

            $ReturnValue = Test-MyFunction -Param 'ABC'

            $ReturnValue | Should Be 'Return value of first mock'
        }

        It 'UNIT TEST 2' {
            Mock -CommandName Mock-Function -MockWith { return 'Return value of second mock' }

            $ReturnValue = Test-MyFunction -Param 'ABC'

            $ReturnValue | Should Be 'Return value of second mock'
        }

    }

}
```

...produces this output:

```PowerShell
Describing Testing Mock Scope

    Context Test-MyFunction
      [+] UNIT TEST 1 1.49s
      [-] UNIT TEST 2 38ms
        Expected string length 27 but was 26. Strings differ at index 16.
        Expected: {Return value of second mock}
        But was:  {Return value of first mock}
        ---------------------------^
        at <ScriptBlock>, ...\TestMockScope.Tests.ps1: line 20
        20:             $ReturnValue | Should Be 'Return value of second mock'
Tests completed in 1.53s
Tests Passed: 1, Failed: 1, Skipped: 0, Pending: 0, Inconclusive: 0 
```

Notice that UNIT TEST 2 failed, and the actual result of UNIT TEST 2 returned the mocked return value of the Mock that was declared in UNIT TEST 1. I know this is happening because, as it says in the Mock documentation, "[Mock] creates new behavior for any existing command within the scope of a **Describe** or **Context** block." So the first Mock declaration still applies within the execution of my second unit test because the scope of the Mock is at the Context level.

I would expect though, based on my unit testing intuition, that Mocks declared in one It block should not affect the execution of other It blocks. However, in this case, UNIT TEST 1 actually affects the result of UNIT TEST 2.

I can see this in that doing any of the following will make UNIT TEST 2 pass:
1. Commenting out UNIT TEST 1
2. Moving UNIT TEST 1 below UNIT TEST 2 in the test script file
3. Removing the -ParameterFilter parameter in the Mock declaration of UNIT TEST 1

But to me it doesn't make sense that one unit test should affect the result of another unit test. Sure, I could make separate Context blocks for each of my unit tests, but that seems like a workaround to fix  behavior that is not intuitive. I think Mock declarations should be allowed to be limited to an **It** scope, as well as a **Describe** or **Context** scope. This would make it consistent with other unit testing frameworks and just make more sense logically.

**Comment by dlwyatt** [comment]
I agree, and made that change briefly during the development of v3.0.  However, it was a breaking change from how mocking was originally implemented, and after discussion with @nohwnd , we left the behavior alone with mocks only scoping to Context / Describe.

**Comment by b4tt1enet** [comment]
That makes sense. It would change the behavior of people's existing Mocks. How do you recommend working around this - just creating new Contexts for each test?

Or what if we added a -Scope parameter to Mock or something similar to how you can scope Assert-MockCalled?

Thanks for your response.

**Comment by alx9r** [comment]
@b4tt1enet FWIW I almost always use a `Context{}` for each mock.  I have found that I'm testing at least a return value and a mock invocation per invocation of the function-under-test.  In that case the `Context{}` is not superfluous anyway because it serves to group the `It{}` blocks for that invocation.  Here's a (somewhat contrived) example of that pattern:

```PowerShell
function g {
    param ( $Seed );    
    [System.Random]::new(123).Next()
}
function Invoke-G {
    param ( $Seed = 1 );
    1 + (g -Seed $Seed)
}

Describe 'Invoke-G' {
    Context 'no seed specified' {
        Mock g { 999 }
        It 'returns correct value' {
            $r = Invoke-G
            $r | Should be 1000
        }
        It 'correctly invokes g' {
            Assert-MockCalled g -Times 1 {
                $Seed -eq 1
            }
        }
    }
    Context 'seed specified' {
        Mock g { 999 }
        It 'returns correct value' {
            $r = Invoke-G -Seed 42
            $r | Should be 1000
        }
        It 'correctly invokes g' {
            Assert-MockCalled g -Times 1 {
                $Seed -eq 42
            }
        }
    }
}
```

This pattern has served me well enough that I've rarely been want for better control of mock scope since I adopted it.
