### ISSUE TITLE
Is it possible skip all tests in Describe/Context block if Before operations fail?

### ISSUE THREAD

**Issue by alexlyss** [pester/Pester#790]
Hi, I'm using pester for functional testing. Is it possible skip or fail all tests if Before operations fail (throw some exception)

**Comment by it-praktyk** [comment]
You can try use 

```powershell
$Global:PSDefaultParameterValues["It:Skip"]=$true
```

An example
https://github.com/equelin/Format-Pester/blob/master/tests/unit/Format-Pester.tests.ps1#L47-L67

**Comment by it-praktyk** [comment]
I assume that the issue can be closed now. Feel free to reopen if you need more assistance.
