### ISSUE TITLE
Mocking Modules with Custom Classes

### ISSUE THREAD

**Issue by hrboyceiii** [pester/Pester#792]
I'm trying to mock commands from a module that depend upon a PS class that is defined within that module; when I mock the commands, Pester throws an error saying the class is not accessible whenever the tests are run.

This may be a design flaw in our module that is breaking testability -- because the exported functions have a parameter typed to class, pester can't mock it.  Here's an example:

Module:
```
Class X {
}

function New-ClassX {
return [X]::new()
}

function Invoke-UsingX {
params([X] $abc)
}
Export-ModuleMember New-ClassX, Invoke-UsingX
```
Script importing module
```
Import-Module .\ModuleWithClass.psm1

$instance = New-ClassX

#Cannot mock this using Pester
Invoke-UsingX -abc $instance
```
Should this be possible?  Could I be writing the test wrong?
```
Mock -CommandName Invoke-UsingX -ParameterFilter {
$abc -eq $null #(or instance)
}

& .\ScriptCallingModule.ps1
```
Appreciate the help...

**Comment by alx9r** [comment]
I'm pretty sure what you are trying to do is possible.  I wasn't able to reproduce the failure you described.  Here's a working example that demonstrates mocking a function using a PowerShell class defined inside a module:

```PowerShell
$guidFrag = [guid]::NewGuid().Guid.Split('-')[0]

$module = New-Module "module$guidFrag" {
    Class X {
    }

    function New-ClassX {
    return [X]::new()
    }

    function Invoke-UsingX {
    params([X] $abc)
    }
    Export-ModuleMember New-ClassX, Invoke-UsingX
}

function f {
    param($x)
    Invoke-UsingX -abc $x
}

Describe 'mock function that uses class inside module' {
    Context 'invoke mock from a function outside module' {
        Mock Invoke-UsingX -Verifiable { 'mock result' }
        It 'returns correct value' {
            $x = New-ClassX
            $r = f -x $x
            $r | Should be 'mock result'
        }
        It 'correctly invokes function' {
            Assert-MockCalled Invoke-UsingX -Times 1 -Exactly
        }
    }
}
```

In case you are not aware, developing using PowerShell classes is still pretty dodgy because of [this known issue](https://stackoverflow.com/a/42878789/1404637).  It could be that you are running into PowerShell using a stale class definition on account of that issue.

**Comment by it-praktyk** [comment]
@hrboyceiii is it your question answered?

**Comment by it-praktyk** [comment]
Due to lack of additional information, the issue is closed now. Please feel free to open when you feel that your question or request was not handled correctly.
