### ISSUE TITLE
What (if anything) is blocking an official final Pester 4.0?

### ISSUE THREAD

**Issue by Jaykul** [pester/Pester#793]
I'm sure my team isn't the only one that's uncomfortable moving to 4 on the build server while it's RC... and I really want the mocking scope changes! 😉

If there's anything that really *needs* to be fixed before we call 4 "done," can we make a list?
Maybe use the "Projects" tab, or list them in a meta issue the way the PowerShell team was doing?

**Comment by alx9r** [comment]
If there are blocking issues that are identified, I can probably allocate some of my time to resolving them.

**Comment by it-praktyk** [comment]
From my point of view before release 4.0.x RTM should be

## Issues

- #687 - completed
- #699 - completed
- #710 - completed
- #714 - reviewed
- #712 - at least triaged
- #733 - at least triaged
- #768 - at least triaged
- #770 - at least triaged, if only documentation need to be updated than completed
- #781 - completed - related PR #786 

## Pull requests

- #763 - merged (trivial)
- #765 - reviewed, merged
- #766 - reviewed, merged - at least ebfbdad505a92e9918ba91649de671afa454e4d3 , @Jaykul answer for  https://github.com/pester/Pester/pull/766#issuecomment-290829140 needed
- #777 - reviewed, merged
- #778 - merged (trivial)
- #779 - reviewed, merged
- #782 - reviewed, merged
- #786 - reviewed, merged

**Comment by dlwyatt** [comment]
I'll be off work for a few days next week, which tends to be my best time for knocking out Pester stuff.  Will review these asap.

**Comment by alx9r** [comment]
@it-praktyk I think #785 should be investigated and understood for 4.0.  It seems unlikely that whatever is causing the call depth overflow affects only XML objects.

**Comment by mrboring** [comment]
I'm confused! I hope you can help. The releases tab shows that 3.4.3 was the "Latest release". However, PSGallery shows relases after that, but does not state that they are beta/rc. Also, if I do update-module I get 4.0.3.

What is the official release?
If it's 3.4.3, why do I get 4.0.3 from PSGallery/update-module?
Should I not only get the latest official release from PSGallery/update-module?
Can I assume that, as 4.0.3 is an rc, I'm safe using it?

Thanks.

**Comment by nohwnd** [comment]
PsGallery does not support beta releases, so the 4.0.3 is a realy a full release, even though we still consider it rc. But it has been in the wild for so long that I am not sure if that distinction still has any meaning.


Jakub Jareš

.NET, Pester, PowerShell
t 00420603800578<tel:00420603800578>
e me@jakubjares.com<mailto:me@jakubjares.com>
t @nohwnd

30. 6. 2017 v 10:13, mrboring <notifications@github.com<mailto:notifications@github.com>>:


I'm confused! I hope you can help. The releases tab shows that 3.4.3 was the "Latest release". However, PSGallery shows relases after that, but does not state that they are beta/rc. Also, if I do update-module I get 4.0.3.

What is the official release?
If it's 3.4.3, why do I get 4.0.3 from PSGallery/update-module?
Should I not only get the latest official release from PSGallery/update-module?
Can I assume that, as 4.0.3 is an rc, I'm safe using it?

Thanks.

**Comment by alx9r** [comment]
@it-praktyk I think #794 should be considered for 4.0 RC as well.

**Comment by mrboring** [comment]
@nohwnd Thanks for your response.

**Comment by nohwnd** [comment]
Thanks for putting the list together. I've made all of the issues and tickets part of [milestone v4](https://github.com/pester/Pester/milestone/1) so we can track them more easily. We can still keep this list up to date, but it's easier if it's done automatically in the milestone. 

If there are more things popping up please add them to the bottom of their respective list so it's easier to keep the milestone in sync with this list.

**Comment by nohwnd** [comment]
@Jaykul "and I really want the mocking scope changes!" Did not see anything related to this in the listed issues, what exactly are you referring to? :)

**Comment by Jaykul** [comment]
@nohwnd That's the stuff that Dave did with regard to making mocks be scoped to Describe (and Context). Not something that needs to be done, just one of the main things I want to start using, that are in 4.0 😀

**Comment by nohwnd** [comment]
So only readme and release notes are missing from this milestone, I am building 4.0.6-rc so people can try it and report back before we finish the documentation, and finally release :)

**Comment by nohwnd** [comment]
@dlwyatt I think #826 has a good point, `It` should fail when no test cases are provided, and this is probably the best time to change the behavior. Do you agree to put it in v4?

**Comment by nohwnd** [comment]
I set the v4 milestone to be due this Friday. I will be on work trip the whole week, which usually means a lot of time for coding during the travel and evenings. I hope I will merge all the PRs, write all the help and fix all issues.

**Comment by it-praktyk** [comment]
Please review issues labeled as [need to be triaged](https://github.com/pester/Pester/issues?q=is%3Aissue+is%3Aopen+label%3A%22Need+to+be+triaged%22) too. Thank you.

**Comment by nohwnd** [comment]
Nothing anymore 🍾 🎈 🍰
