### ISSUE TITLE
CI Test against PowerShell 5.1

### ISSUE THREAD

**Issue by alx9r** [pester/Pester#794]
I'm guessing that the CI server is probably using PowerShell 5.0.10586.51 for the v5 tests.  I'm inferring this from the ToolFoundations project whose CI is on the same server.  From the admin pages of that project I have not found any signs of PowerShell 5.1.  (I'm a TeamCity noob, so I apologize if I have this wrong.)

It seems like at least late version(s) Pester should be tested against PowerShell 5.1.

**Comment by it-praktyk** [comment]
I'm not sure if I understand what is a subject of your request.

Would you like extend continues integration tests of Pester to PowerShell v. 5.0.10586.51 also?

**Comment by alx9r** [comment]
@it-praktyk I mean the opposite: I think Pester

**Comment by alx9r** [comment]
@it-praktyk The other way around:  I would like to extend the coninuous integration tests of Pester to PowerShell *5.1*.  Currently the latest seems to be 5.0.10586.51.

**Comment by it-praktyk** [comment]
Yes, exactly I thought about that - means test Pester with/under new version of PowerShell.

IMHO, extending CI workflow is not needed before publishing v.4 RTM - probably most of use use this version on development machines. The person who can do it is @dlwyatt but I think that his knowledge/time/involvement is more required for other tasks.

**Comment by dlwyatt** [comment]
I patched the build agents today; it's running 5.1 now.
