### ISSUE TITLE
Exclude tests and samples from the package

### ISSUE THREAD

**Issue by mnivet** [pester/Pester#795]
I'm wondering why the samples and self tests of Pester are provided in the NuGet package ?

It's great to have them in the source repository, but why do we need to download them when we want to use Pester through NuGet ?

For scenario where we install Pester as a Module through the PSGallery it's not a big issue, but when install pester as a package on a Visual Studio project it start to be more awkward. In particular because when executing `Invoke-Pester` at the root of a solution it run the tests of Pester itself (found in the packages folder) in addition to the tests of the projects :/

To simplify usage inside Visual Studio I've written a little package which in part overcome that issue: https://github.com/mnivet/PesterForPackageManagerConsole

But it could be better if the official Pester package is cleaned.

**Comment by nohwnd** [comment]
@mnivet Thanks for reporting. I removed the examples and all `*.Tests.ps1` files from the final packages on PSGallery, nuget and choco in version 4.0.5. Please give it a try and reopen this issue if it does not work as expected.

**Comment by mnivet** [comment]
versions 4.0.5 and 4.0.4 are available only on PSGallery, is that normal ? Hard to test back my scenario if the package is not available for it...

**Comment by nohwnd** [comment]
@

**Comment by nohwnd** [comment]
@mnivet done. Re-released as [4.0.5-rc on Nuget](https://www.nuget.org/packages/Pester/4.0.5-rc)
