### ISSUE TITLE
Mocking a cmdlet that is being splatted

### ISSUE THREAD

**Issue by davebrannan** [pester/Pester#796]
I'm trying to mock calls to Invoke-SqlCmd in a function. It works unless the parameters to Invoke-SqlCmd are splatted. I'm presuming mock is having a problem due to how Invoke-Sqlcmd handles parameters? Is there a workaround?

**Comment by dlwyatt** [comment]
Splatting makes no difference to how PowerShell binds parameters, and mock filtering doesn't kick in until after that binding takes place.  I'd need to see the working and non-working code to try to understand why it's failing.

**Comment by davebrannan** [comment]
Ok thanks Dave. In that case it could be the way I've implemented splatting, I'll test some more and close this issue.
