### ISSUE TITLE
Mocking a function that is call by a method in a PowerShell class works on first run, but not on second run

### ISSUE THREAD

**Issue by johlju** [pester/Pester#797]
We have created a Pester test that tests a class-bases resource, that do work on the first run. The problem we are seeing is that the mocks only works on first run. On any subsequent run the mocks doesn't get hit, but instead the original function is called. This could be solved by running a new session for each run during development. But now we are starting to see problems in AppVeyor where we can't control that as easily.

We are hoping someone can shed a light on this problem.

Running Pester 4.0.3 on PS 5.1.16232.1000.

I have put together a minimal example scenario (repository) here;  https://github.com/johlju/PesterTestClassBasedResource

### 1. Clone the repository

To run this example, do the following.

```powershell
git clone https://github.com/johlju/PesterTestClassBasedResource
cd PesterTestClassBasedResource
```

#### First run

```powershell
Invoke-Pester .\MyDscResource.Tests.ps1
```

Gives expected successful result.

```plaintext
Executing all tests in .\MyDscResource.Tests.ps1

Executing script .\MyDscResource.Tests.ps1

  Describing MyDscResource\Get()

    Context When the Get method is called
      [+] Should not throw an error 1.13s
Tests completed in 1.13s
Tests Passed: 1, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0
```

#### Second run

```powershell
Invoke-Pester .\MyDscResource.Tests.ps1
```

The test throws an error.

```plaintext
Executing all tests in .\MyDscResource.Tests.ps1

Executing script .\MyDscResource.Tests.ps1

  Describing MyDscResource\Get()

    Context When the Get method is called
      [-] Should not throw an error 179ms
        Expected: the expression not to throw an exception. Message was {Test-HelperFunction throw an error!}
            from V:\Source\_Random\PesterTestClassBasedResource\HelperFunctions.psm1:6 char:5
            +     throw 'Test-HelperFunction throw an error!'
            +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        at <ScriptBlock>, V:\Source\_Random\PesterTestClassBasedResource\MyDscResource.Tests.ps1: line 17
        17:                 { $databaseMembershipClass.Get() } | Should Not Throw
```

**Comment by dlwyatt** [comment]
That is consistent with the problems I had when trying to test PS classes originally as well.  PowerShell was caching class definitions in such a way that the first module to load the class would be the active one, even if you removed the module or changed the class.  My recommendation at the time was to run your Pester tests in a fresh session every time; this is simple to do with Start-Job.  I have this proxy function in my PowerShell profile to help with that:

```posh
function Invoke-PesterJob
{
[CmdletBinding(DefaultParameterSetName='LegacyOutputXml')]
    param(
        [Parameter(Position=0)]
        [Alias('Path','relative_path')]
        [System.Object[]]
        ${Script},

        [Parameter(Position=1)]
        [Alias('Name')]
        [string[]]
        ${TestName},

        [Parameter(Position=2)]
        [switch]
        ${EnableExit},

        [Parameter(ParameterSetName='LegacyOutputXml', Position=3)]
        [string]
        ${OutputXml},

        [Parameter(Position=4)]
        [Alias('Tags')]
        [string[]]
        ${Tag},

        [string[]]
        ${ExcludeTag},

        [switch]
        ${PassThru},

        [System.Object[]]
        ${CodeCoverage},

        [switch]
        ${Strict},

        [Parameter(ParameterSetName='NewOutputSet', Mandatory=$true)]
        [string]
        ${OutputFile},

        [Parameter(ParameterSetName='NewOutputSet', Mandatory=$true)]
        [ValidateSet('LegacyNUnitXml','NUnitXml')]
        [string]
        ${OutputFormat},

        [switch]
        ${Quiet}
    )

    $params = $PSBoundParameters

    Start-Job -ScriptBlock { Set-Location $using:pwd; Invoke-Pester @using:params } |
    Receive-Job -Wait -AutoRemoveJob
}

Set-Alias ipj Invoke-PesterJob
```

I _think_ they've fixed that problem in PS v6, but haven't tested it recently.

**Comment by johlju** [comment]
Yes, it does work in PowerShell 6.0 beta 3 on macOS! Need to verify that on a Windows build as well.

**Comment by johlju** [comment]
And the mockup does work on PowerShelll 6.0 beta 3 on Windows Server as well. 

Tried to run the full test on PowerShell 6.0 beta 3.0 -  but got errors not related to this, but I thought I share them since I had them available

```
      [-] Should add the specified databases to the availability group 178ms
        Expected: the expression not to throw an exception. Message was {Cannot
retrieve the dynamic parameters for the cmdlet. Could not compare "6.0.0-beta" t
o "5.0.10586.122". Error: "Cannot convert value "5.0.10586.122" to type "System.
Management.Automation.SemanticVersion". Error: "Cannot process argument because
the value of argument "version" is not valid. Change the value of the "version"
argument and run the operation again.""}
```

So to early to use the 6.0 beta 3. But then I know there is a solution in the near future! Thanks @dlwyatt!

**Comment by it-praktyk** [comment]
I quoted part of @dlwyatt explanation on [Pester wiki page](https://github.com/pester/Pester/wiki/Mocking-with-Pester).

CC: @adbertram - something to include in your book ?

**Comment by alx9r** [comment]
@johlju If you're eagerly awaiting a solution to PowerShell 5's stale class problem (as I am), [per Joey Aiello](https://github.com/PowerShell/PowerShell/issues/2505#issuecomment-303185005) it looks like it's slated for 6.1.0:

> This is super-annoying, obviously, but given our desire to postpone classes work until 6.0.0 is stable, I'm moving this out to 6.1.0.

Note that [the solution to the problem seems to be piece-wise](https://github.com/PowerShell/PowerShell/issues/2505#issuecomment-264569217), so we may see the problem cured early in some cases, but not others.  In the meantime, I've been able to be more-or-less productive developing with classes using [the workaround described here](https://stackoverflow.com/a/42878789/1404637).

**Comment by johlju** [comment]
@alx9r Yes, I saw Joey comment about moving this to 6.1. I guess "All good things come to those who wait.". :smile: 

Since we are seeing this breaking in AppVeyor with the automated tests we are refactoring the resource to mof-based. My plan now (but that can change), at least for this resource module, is that we can take up class-based resource once PowerShell 6.0 has been release and we see that it works better with the automated tests.

Thanks all for your answers! It so awesome that we in the community help each other!

**Comment by johlju** [comment]
Closing this as this problem was not Pester.

**Comment by LethiferousMoose** [comment]
@johlju Do you know if this issue is reoccurring on the latest release of PowerShell (6.2.4) I was seeing this same issue today with my tests.

**Comment by johlju** [comment]
I haven’t tested. I stopped trying to use Class-based resources as they didn’t bring any more value, and just harder to test.
