### ISSUE TITLE
Can't Mock Find-AzureRmResource when called from PowerShell Class

### ISSUE THREAD

**Issue by CtrlDot** [pester/Pester#805]
I'm probably doing something completely wrong, but I can't seem to mock the Find-AzureRmResource when I am calling it from a class that I create.

Essentially, I am creating a Mock like so:

`Mock Find-AzureRmResource { return @{Name = "blahblah"}}`

When I call it directly in a test, it works fine:

`It "Should return blahblah"{
			(Find-AzureRmResource -ResourceNameContains "blah").Name | Should be "blahblah"
		}`

However, when I create a class using New-Object, call a method on that class which calls Find-AzureRmResource I get prompted to run "Login-AzureRMAccount"

`		It "Should return blahblah"{
			$customer = New-Object MyObject("blahblah")
			$customer.test().Name | Should be "blahblah"
		}`

`	[string]test(){
		return Find-AzureRmResource -ResourceNameContains blah -ResourceNameEquals blah
	}`

I'm assuming I'm just doing something wrong, and was hoping to get some direction.

**Comment by alx9r** [comment]
@CtrlDot There are two known issues you might be encountering:

1. Pester #339 about problems mocking cmdlets with dynamic parameters.
2. [PowerShell's stale class bug](https://github.com/PowerShell/PowerShell/issues/2505#issuecomment-263105859) which causes old versions classes to persist in-memory.  (See also [stackoverflow](https://stackoverflow.com/a/42878789/1404637).)

I can't tell for sure.  Based on your description, though, it seems likely you're running into one or both of those issues.

**Comment by CtrlDot** [comment]
@alx9r I had taken a look at #339, I'm not getting the same error message (Mine complains that I need to login to azure to run the command).  As for the powershell state issue, I am manually dropping the reference to the module that contains the class prior to running pester (which then reloads it).  

I'd like to draw attention to the fact that it works just fine when I run everything inline, but fails when I run a method on a class in a separate powershell module (that then executes the find statement).  Another note is that i'm using the "using" syntax to load the module into my test.  Not sure if that matters or not.

Thanks for the quick response!

**Comment by CtrlDot** [comment]
Just to add to this, I experience this issue on first run (in a new powershell prompt) or when I follow the information in the stackoverflow response about using powershell.exe to launch the command.

Are the debugging steps that I could do to help track down the problem?

**Comment by alx9r** [comment]
@CtrlDot If you post a [MCVE](https://stackoverflow.com/help/mcve) here reproducing the problem that would definitely help to track down the problem.

**Comment by AlexKeySmith** [comment]
Hi @CtrlDot 

I found that if I'm testing a module, which is using a AzureRm module that I need to mark start my tests with InModuleScope.

e.g. 

Import-Module MyModule

InModuleScope MyModule {
    Describe "My Test" {
      #tests here

    }
}

**Comment by AlexKeySmith** [comment]
Hi @CtrlDot 

Learning more about pester, I could also get this to work, by ensuring I used -ModuleName parameter on both Mock and Assert-MockCalled functions. Pay close attention to the -ModuleName documentation, it's the name of your module, not the AzureRm module you are mocking.
