### ISSUE TITLE
Allow Pester To Reconstruct It's Results Object by Re-Reading It's own nunit XML output

### ISSUE THREAD

**Issue by DarwinJS** [pester/Pester#809]
My scenario:
- I remotely run pester and gather the results.
- I use AWS SSM to run the command and collect results to an S3 bucket (using winrm remoting would be inordinately more complex for reasons that would require me to write a small book in this issue - suffice it to say I can't do that)
- in this scenario it is only possible to collect stdout to the bucket - so I emit the nunit output to make it easy to ingest into CI test results.
- however, I would also like to be able to quickly identify the number of failures and specific failing tests - just like the pester results object allows.

If pester could re-ingest it's own nunit xml and create a new status object for me - that would neatly handle my case.

Otherwise, I am down to parsing the XML manually to get this data - the painful scenario that I believe inspired the pester results object in the first place :(

**Comment by it-praktyk** [comment]
You can use commands like below to store Pester results to file and reread them after file transfer.

```powershell
Invoke-Pester -PassThru | Export-Clixml -Path .\Test-Result.xml
Import-Clixml -Path .\Test-Result.xml | Format-Pester -Format .\ -BaseFileName Test-Result -Format HTML -FailedOnly
```

To create reports from tests results (in a human friendly form) you can use [Format-Pester](https://github.com/equelin/format-pester).

**Comment by DarwinJS** [comment]
@it-praktyk - I was just working on that.

But i was trying to get the XML object to output as nunit XML for CI ingestion.

Does pester or format-pester allow me to export the pester  object?  Something like:

```
Invoke-Pester -PassThru | Export-Clixml -Path .\Test-Result.xml
Import-Clixml -Path .\Test-Result.xml | Format-Pester -Format nunitXML | out-file TestResultsInNunit.xml
```

**Comment by nohwnd** [comment]
Not at the moment, but we should be able to dig the function that does the conversion out of the module to give you quick but hacky workaround. Will have a look later.


Jakub Jareš

.NET, Pester, PowerShell
t 00420603800578<tel:00420603800578>
e me@jakubjares.com<mailto:me@jakubjares.com>
t @nohwnd

2. 8. 2017 v 20:44, Darwin <notifications@github.com<mailto:notifications@github.com>>:


@it-praktyk<https://github.com/it-praktyk> - I was just working on that.

But i was trying to get the XML object to output as nunit XML for CI ingestion.

Does pester or format-pester allow me to export the pester object? Something like:

Invoke-Pester -PassThru | Export-Clixml -Path .\Test-Result.xml
Import-Clixml -Path .\Test-Result.xml | Format-Pester -Format nunitXML | out-file TestResultsInNunit.xml

**Comment by DarwinJS** [comment]
I'm just realizing that the one system that needs to ingest is lambda python - so it can only deal with the straight nunit XML - I don't have the opportunity to manipulate the pester object before that system does the ingest.

So I need a way to go from nunit XML ==back to ==> Pester results object.

**Comment by it-praktyk** [comment]
@DarwinJS, sorry I didn't understand you correctly previously. Additionally, I copped an example from Format-Pester README exact - I should skip pipe to Format-Pester in the second line. 

The part of Pester code what is responsible for creating NUnit you can find [here](https://github.com/pester/Pester/blob/master/Functions/TestResults.ps1). 

I'm also interested to add support for NUnit to Format-Pester so ... pull request will be welcomed ;-)

**Comment by nohwnd** [comment]
@DarwinJS  Hmm the conversion from pester object to test result xml is lossy, how about you convert the whole object to JSON and parse that in the lambda?

**Comment by DarwinJS** [comment]
@nohwnd - I found a way to read enough detail from the nunit xml with the below code.

I can get a failure count and a list of failed tests.

```
[xml]$PesterNUnitTestResults = get-content $env:temp\pesternunitresults.xml
$PesterNUnitTestResults.{test-results}.{test-suite}.results.{test-suite}.results.{test-suite}.results.{test-suite}.results.{test-case} | where {$_.result -ieq "Failure"} | ft result, description
```

**Comment by nohwnd** [comment]
@DarwinJS thanks for the info, I am glad you found a solution. Feel free to reopen if you need more asistance.
