### ISSUE TITLE
Get-Command SomeMockedFunction returns less complete object in Pester 4

### ISSUE THREAD

**Issue by alx9r** [pester/Pester#810]
## Repro

```PowerShell
foreach ( $version in '3.4.3','4.0.5' )
{
    Remove-Module Pester -ErrorAction Ignore
    Get-Module Pester -ListAvailable | ? {$_.Version -eq $version} | Import-Module
    Describe "Pester $version : Get-Command for mocked function" {
        It "using Pester $version" {
            (Get-Module Pester).Version |
                Should be $version
        }
        function f
        {
            [CmdletBinding()]
            param
            (
                [Parameter(Mandatory=$true)]
                $x
            )
        }
        It 'f has 1 parameter set' {
            $r = Get-Command f
            $r.ParameterSets.Count | Should be 1
        }
        Context 'mock' {
            Mock f
            It 'mock of f has 1 parameter sets' {
                $r = Get-Command f
                $r.ParameterSets.Count | Should be 1
            }
        }
    }
}
```

## Implications

It seems like any tests that relied on invoking Get-Command for a mocked command under Pester 3 are prone to failure under Pester 4.  It seem like the object returned by Get-Command for a mocked object under Pester 4 is less complete than that returned under Pester 3.

**Comment by dlwyatt** [comment]
Mocks recently changed from being implemented as a function named `WhateverYouAreMocking` to being an alias with that name instead (and a randomly-named function).  That's a breaking change we'll have to live with; the older function code had some scoping nightmares happening with the new Pester internals.

**Comment by alx9r** [comment]
Thanks @dlwyatt.  I'm fine with that.  Could this sort of thing be published in release notes?  I don't see any release notes on [the releases page](https://github.com/pester/Pester/releases).  Are there release notes for Pester that I've missed somewhere?

I was surprised by a few scope-related changes that probably also ought to also be referenced in the release notes.

**Comment by dlwyatt** [comment]
Sort of.  It's in the release notes as "Fix mocking functions in two consequitive contexts [GH-744]" (in 4.0.3).  I never expected the implementation details to be a problem for users.
