### ISSUE TITLE
Summary of scope-related differences for mocks between Pester 3 and 4

### ISSUE THREAD

**Issue by alx9r** [pester/Pester#812]
I've encountered a few scope-related edge cases for mocks that behave differently between Pester 3 and 4.  Here are suites of mock-scoping tests for [Pester 3](https://github.com/alx9r/ToolFoundations/blob/a7ad54074594a9cdf519fc253e8193675b170f4e/EnvironmentTests/pester3InModuleScopeTests.ps1) and [Pester 4](https://github.com/alx9r/ToolFoundations/blob/a7ad54074594a9cdf519fc253e8193675b170f4e/EnvironmentTests/pester4InModuleScopeTests.ps1).  Most of the scope-related mock behavior is identical between Pester 3 and 4, however, there are a handful of notable differences which are consolidated in [this gist](https://gist.github.com/alx9r/56bbc9077b39e5693b08821183d89c21).  Vaguely-speaking there are scope-related differences for mocks between Pester 3 and 4 in the following circumstances:

1. Indirectly invoking mocked commands without using InModuleScope at all when using F5 in ISE.
2. Indirectly invoking mocked commands from a module that doesn't import the module where the mocked command resides.

## Implications

Each of these are definitely edge cases but have the potential to be confusing (especially to new users).  

(1) is a new circumstance where Pester behaves differently when pressing F5 versus using `Invoke-Pester`.  
(2) is a new circumstance wherein a call to `Mock` succeeds, but the resulting mock is not invoked.

I don't think these warrant any action other than awareness.  I am creating this issue mainly as a reference for future users who also run into these edge cases.

**Comment by nohwnd** [comment]
Linked to this in migration guide, closing so we can close the milestone.
