### ISSUE TITLE
Pester 4.0 undoes PR #426

### ISSUE THREAD

**Issue by alx9r** [pester/Pester#815]
Pester 4.0 undoes PR #426.  Invoking [@nohwnd's test](https://github.com/pester/Pester/pull/426#issuecomment-162291254) outputs only one line of the stack trace:

![image](https://user-images.githubusercontent.com/11237922/29241569-50f2abe0-7f31-11e7-9dec-283151636197.png)

[This diff shows](https://github.com/pester/Pester/compare/3.4.3...master#diff-e5946304f985e30d847577bbe188a9b9L185) that somewhere between 3.4.3 and c3d84de (HEAD of today's master) the changes from PR #426 (including the tests) were removed.

**Comment by nohwnd** [comment]
gotta have a closer look, there was quite a few changes when forward merging 3 to 4, so possibly your changes got lost. Sorry about that.

**Comment by nohwnd** [comment]
So I put the code back in, it was omitted when there was confusion about what output to use. There are some errors, still, but the above tests looks exactly as in the #426 thread, so I am on a good path.
