### ISSUE TITLE
Invoking remote PSSession to run Pester test causes "The script failed due to call depth overflow"

### ISSUE THREAD

**Issue by ChrisLynchHPE** [pester/Pester#822]
I'm not sure where to turn for this particular issue.  I have a Windows 10 VM that I'd like to use as a worker PC for when I want to run manual Pester tests as a PowerShell job.  I have a script that essentially does the following:

```PowerShell
#Start a new remote session to POSH-Worker
$POSHWorkerRemoteSession = New-PSSession -ComputerName POSH-51-Worker-1.test-lab.local -Credential $ClynchCreds -Authentication Credssp
$JobName = 'Module Test {0}.{1} Test - {2}' -f $Major, $Minor, [DateTime]::Now.ToString("yyyy-MM-ddTHH-mm-ss-ff")
$ParameterSetName = $PSCmdlet.ParameterSetName

$ScriptBlock = {

	$CentralLibraryDestinationPath = $Using:CentralLibraryDestinationPath
	$Major                         = $Using:Major
	$Minor                         = $Using:Minor
	$LibraryRootName               = $Using:LibraryRootName
	$CentralLibraryRootSource      = $Using:CentralLibraryRootSource #Is a UNC path
	$ParameterSetName              = $Using:ParameterSetName
	$JobName                       = $Using:JobName
	$TestTags                      = $Using:TestTags    

	$Job = Start-Job -Name $JobName -ScriptBlock { 

		'Job Started' | Write-Host -ForegroundColor Magenta
		$PSetName       = $Using:ParameterSetName
		$Tags           = $Using:TestTags
		$UnitTestSource = $Using:CentralLibraryRootSource

		$Params = @{
			
			"$PSetName" = $true;
			TestTags    = $Tags

		}

		'Executing unit tests' | Write-Host -ForegroundColor Magenta

		# Execute the parent script, which updates file versions and then calls Invoke-Pester $PathToTestScript
		& "$UnitTestSource\Start-FunctionTest.ps1" @Params
		
		'Unit tests completed' | Write-Host -ForegroundColor Magenta
	
	}

	Start-sleep -Seconds 2

	while ($Job.HasMoreData -or $Job.State -eq "Running") 
	{

		Receive-Job -Job $Job # -Keep

		Start-Sleep -Seconds 1

	}

	Get-Job -Id $Job.Id | ConvertTo-Json -Depth 99

}

'Executing remote job' | Write-Host -ForegroundColor Cyan

$Results = Invoke-Command -Session $POSHWorkerRemoteSession -ScriptBlock $ScriptBlock

'Saving PowerShell job results' | Write-Host -ForegroundColor Cyan

$Results | Out-File (Join-Path -Path $CentralLibraryRootSource -ChildPath "$JobName.log")

if (Get-Variable -Name Tot -Scope Global -ErrorAction SilentlyContinue) 
{
	
	Remove-Variable -Name Tot -Scope Global -ErrorAction SilentlyContinue

}

'Disconnecting remote PSSession' | Write-Host -ForegroundColor Cyan

Remove-PSSession $POSHWorkerRemoteSession.Id
```
When I execute the above, the first 37 It tests within the first 9 Contexts (a single Describe block), I get the following error:

```PowerShell
      [-] Will create and download Backup 927ms
        Expected: the expression not to throw an exception. Message was {The script failed due to call depth overflow.}
            from \\fileserver\software\AppVeyor\pester\POSH_3.10_FunctionTesting.ps1:998 char:43
            + ... kupFileResults = New-HPOVBackup -Location $TestDrive } | Sho ...
            +                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        at <ScriptBlock>, \\fileserver\software\AppVeyor\pester\POSH_3.10_FunctionTesting.ps1: line 998
        998:             { $Script:BackupFileResults = New-Backup -Location $TestDrive } | Should Not Throw
```
If I initiate a remote session to that worker PC, and execute the Cmdlet I'm trying to test manually, it does not fail.  I am stuck trying to figure out where this issue is.  Is this an issue with Pester, or PowerShell 5.1?  I read in some forums that the Stack Depth in 4.0 and newer is "supposed" to be greater than 1000, but I'm not sure if PSRemoting enforces a different runspace with a different stack depth.  Has anyone attempted or successfully implemented this?

Yes, my project is integrated with a CI tool (AppVeyor), but I only want to test certain test cases before I commit a change for a full CI test to be executed, which is why I have a parameter/variable for `$TestTags`.

Here are the details about the remote Windows 10 PC:

```PowerShell
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.15063.502
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.502
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

PS C:\> Get-Module pester

ModuleType Version    Name   
---------- -------    ----   
Script     4.0.5      pester
```

**Comment by it-praktyk** [comment]
@ChrisLynchHPE, could you try use Pester downloaded directly from the GitHub repository?

My first idea is that your issue can be resolve by the pull request #818.

**Comment by ChrisLynchHPE** [comment]
I can and will report back.  Do know that none of my unit tests are validating for IEnumerable objects.

**Comment by NOAHSARKNET** [comment]
I'm not sure that pull request #818 is going to resolve your issue. Let us know.

**Comment by it-praktyk** [comment]
> I'm not sure ...
Me too ;-)

**Comment by ChrisLynchHPE** [comment]
It did not.

**Comment by alx9r** [comment]
I'm pretty sure the message

``` PowerShell
Expected: the expression not to throw an exception. Message was {The script failed due to call depth overflow.}
```

is the message produced by `Should not throw` by design when the thing inside `{}` throws.  Based on that, I _think_ the call depth overflow is occurring inside `New-Backup`.

**Comment by ChrisLynchHPE** [comment]
@alx9r Yes, I'm aware of that `Should Not Throw` condition in the unit test. The call shouldn't generate an error message.  When I execute `New-Backup` outside of this, or not within a PowerShell job, I never see this error.  Only when I attempt to execute the pester test within a remote PowerShell job does this happen.  I have no idea on how to troubleshoot this further, and since it happens with these conditions, I figured I would reach out here.

Some background on this `New-Backup` Cmdlet:

* It makes an API call to request a backup file be created
* When the request is accepted, there is another call to a Cmdlet that waits for the task to complete (called `Wait-TaskComplete`).
* When that task is complete, I then use an internal function to download the file that the task tells me is available, called `Download-File`.  Within `Download-File`, I use `System.Net.WebClient` to download the binary stream within a `Do/While` loop, which saves the file locally.

The exception is thrown almost immediately, right after the API request is accepted.  Again, if I run this anywhere else, I never see the `call depth overflow` exception.

**Comment by nohwnd** [comment]
You can measure the call depth simply by calling a function recursively till it fails, and write a counter on each call.

```powershell
function f ($i=0) { write-host $i; f (++$i) }

f
```
```powershell
# and in job
start-job { function f ($i=0) { write-host $i; f (++$i) }

f } | wait-job | receive-job
```
On my computer the normal execution reaches ~5100 in job it reaches ~239. 

If I debugged this I would, first validate that the call depth is roughly the same as the values posted. Then I would work hard to get the whole exception from the code, because that will likely explain what exactly is happening. If that did non help me I would bi-sect the problem. Does it fail when you don't call `New-Backup`? Does it fail when you call only `New-Backup? Does it fail when you capture output of `New-Backup` and then use rest of your code? A wild guess is that the conversion to json fails with the 99 conversion depth.

**Comment by it-praktyk** [comment]
@ChrisLynchHPE, any new information?

**Comment by ChrisLynchHPE** [comment]
@nohwnd The `New-Backup` Cmdlet uses the very same core Cmdlet all of my other Cmdlets use to interact with the API endpoint.  The unit tests I mentioned early on do not fail.

> Then I would work hard to get the whole exception from the code, because that will likely explain what exactly is happening.

There are multiple `Try{} Catch{}` blocks within the call stack when the unit test invokes `New-Backup`.  What is interesting behavior I noticed in my tests yesterday is that when I pass `-Verbose` to the Cmdlet in question, I don't see the `call depth overflow' exception with that unit test.  Which, I do handle the `-Verbose` parameter in that I bypass `Write-Progress`, so I wonder if that may have anything to do with this issue.

> A wild guess is that the conversion to json fails with the 99 conversion depth.

I only call `ConvertTo-Json` when a POST, PUT or PATCH operation is requested.

**Comment by nohwnd** [comment]
@ChrisLynchHPE Thanks for the info. So did you manage to get the whole exception? Did you try to bi-sect it? Does it still fail if you don't call new backup? It's really difficult for me to give you any good advice without being able to debug it myself. :/

**Comment by ChrisLynchHPE** [comment]
Sorry to get back to this so late.  But I did some major code refactoring, moving HttpWebRequest into a custom C# class my library uses.  Making that change appears to have fixed my issue, so closing this one.
