### ISSUE TITLE
Mock is always loading module in $env:PSModulePath

### ISSUE THREAD

**Issue by adbertram** [pester/Pester#823]
Summary: I have a copy of a script module not in $env:PSModulePath AND I have an older copy of that module in $env:PSModulePath. I want to test the changes I make to the one NOT in a folder in $env:PSModulePath. However, when a mock is created, it's always loading the old copy in $env:PSModulePath when it should be looking at the other one.

Here's the repo: https://gist.github.com/adbertram/45cff33d2036e366d3b694d43444e9a4

I think the issue is right here: https://github.com/pester/Pester/blob/668080725ecb45b5c676c221611f6c4f0d3ba7a1/Functions/InModuleScope.ps1#L104

Get-Module is just using the module name without a specific path.

**Comment by alx9r** [comment]
I just tried to reproduce this on 3.4.3 and 4.0.5.  I get

```
Executing all tests in '.\MyModule.Tests.ps1'

Executing script .\MyModule.Tests.ps1

  Describing callfoo
    [-] calls foo 148ms
      CommandNotFoundException: Could not find Command foo
      at Validate-Command, C:\Users\un1\Documents\WindowsPowerShell\Modules\Pester\Functions\Mock.ps1: l
ine 851
      at Mock, C:\Users\un1\Documents\WindowsPowerShell\Modules\Pester\Functions\Mock.ps1: line 168
      at <ScriptBlock>, C:\Users\un1\Documents\WindowsPowerShell\Modules\MyModule\MyModule.Tests.ps1: li
ne 14
Tests completed in 148ms
Tests Passed: 0, Failed: 1, Skipped: 0, Pending: 0, Inconclusive: 0 
```

on 4.0.5 and something similar on 3.4.3.

I traced from 

```
Import-Module -Name 'C:\MyModule.psm1' -Force -ErrorAction Stop
```

all the way to the throw in `Validate-Command`.  I called `Get-Module MyModule` as I went.  `Get-Module MyModule` output

```
ModuleType Version    Name                                ExportedCommands                             
---------- -------    ----                                ----------------                             
Script     0.0        MyModule                                                                         
```

the whole way.  Note that `ExportedCommands` is empty.  Can you do the same trace and find where `ExportedCommands` gets populated?  Assuming it does at some point.

**Comment by adbertram** [comment]
I checked for ExportedCommands inside of the test script before the describe block, in the describe block before and after the mock. The only time the function showed up was after the mock was created. 

Odd.

**Comment by nohwnd** [comment]
@adbertram Are you able to reproduce the issue? The code in Pester selects the module from the currently loaded modules, and fails if there is more than one with the given name. If you load the module from your ModulePath and run the tests without force importing the other module it will use the module that was already loaded. So maybe that happened?

I don't see any other way this could break, but I will wait for confirmation that you cannot reproduce 🙂

**Comment by adbertram** [comment]
I cannot reproduce it now. I'm not sure what state it was in.
