### ISSUE TITLE
Parameterized Tests don't get marked as Inconclusive when empty

### ISSUE THREAD

**Issue by Remco-74** [pester/Pester#833]
When using an empty parameterized test, the test does not get marked as 'Inconclusive'. It does get marked as 'Passed'.

    Describe 'Defect: Parameterized Tests do not get marked as Inconclusive when empty.' {

        BeforeAll {
            $testCases = @{ Name = 'a' }
        }

        It 'will mark an empty test method as Inconclusive' {

        }

        It 'will mark an empty parameterized test method as Inconclusive' -TestCases $testCases {
            param($Name)

        }
    }

Results in:

    Executing script .\Empty.tests.ps1

      Describing Defect: Parameterized Tests do not get marked as Inconclusive when empty.
        [?] will mark an empty test method as Inconclusive 31ms
        [+] will mark an empty parameterized test method as Inconclusive 11ms
    Tests completed in 42ms
    Tests Passed: 1, Failed: 0, Skipped: 0, Pending: 1, Inconclusive: 0

It would be expected that a parameterized test case is evaluated in the same way as a normal test case.

**Comment by it-praktyk** [comment]
@Remco-74, IMHO, it's strictly related to #826. I think that a one of these should not be processed. 

@nohwnd, are you agree?

**Comment by nohwnd** [comment]
We should keep both. 
- #826 describes what should happen when no test cases are provided. 
- This describes what happens if you provide test cases but keep the _body_ of the test "empty" (just having the parameter block and nothing else).

**Comment by it-praktyk** [comment]
OK, thx for a clarification.

**Comment by Remco-74** [comment]
Correct, these are two diffrent issues. 

I could not locate the code that marks testcases inconclusive when empty, otherwise i could try to submit a pr. Can anyone point me in the right direction?

**Comment by nohwnd** [comment]
@Remco-74 Sure [here it is](https://github.com/pester/Pester/blob/23eaf10c354eb4fbebc9d44f960bec89b24b5976/Functions/It.ps1#L161).

**Comment by Remco-74** [comment]
I've changed the test to:

    #mark empty Its as Pending
    #[String]::IsNullOrWhitespace is not available in .NET version used with PowerShell 2
    **$scriptIsEmpty = (($null -EQ $script.Ast.BeginBlock) -and ($null -EQ $script.Ast.ProcessBlock) -and ($null -EQ $script.Ast.EndBlock))
    if ($PSCmdlet.ParameterSetName -eq 'Normal' -and $scriptIsEmpty)**
    {
        $Pending = $true
    }

resulting in the expected result:

    Executing all tests in .\Empty.tests.ps1

    Executing script .\Empty.tests.ps1

      Describing Defect: Parameterized Tests do not get marked as Inconclusive when empty.
        [?] will mark an empty test method as Inconclusive 42ms
        [?] will mark an empty parameterized test method as Inconclusive 5ms
    Tests completed in 48ms
    Tests Passed: 0, Failed: 0, Skipped: 0, Pending: 2, Inconclusive: 0

**Comment by Remco-74** [comment]
I've changed the detetion of an empty test to the following (using the Ast of the scriptblock):

    #mark empty Its as Pending
    #[String]::IsNullOrWhitespace is not available in .NET version used with PowerShell 2
    $testIsEmpty = 
        [String]::IsNullOrEmpty($test.Ast.BeginBlock.Statements) -and 
        [String]::IsNullOrEmpty($test.Ast.ProcessBlock.Statements) -and 
        [String]::IsNullOrEmpty($test.Ast.EndBlock.Statements)

    if ($PSCmdlet.ParameterSetName -eq 'Normal' -and $testIsEmpty)
    {
        $Pending = $true
    }

using the following tests (positive and negative):

    Describe 'Defect: Parameterized Tests do not get marked as Inconclusive when empty.' {

        BeforeAll {
            $testCases = @{ Name = 'a' }
        }

        It 'will mark an empty test method as Inconclusive' {
            # i am empty
        }

        It 'will mark an empty parameterized test method as Inconclusive' -TestCases $testCases {
            param($Name)
            # i am empty
        }

        It 'will not mark a not empty test method as Inconclusive' {
            Write-Verbose 'i am not empty'
        }

        It 'will not mark a not empty parameterized test method as Inconclusive' -TestCases $testCases {
            param($Name)
            Write-Verbose 'i am not empty'
        }
    }

delivers the following (desired) results:

    Executing all tests in .\Empty.tests.ps1

    Executing script .\Empty.tests.ps1

      Describing Defect: Parameterized Tests do not get marked as Inconclusive when empty.
        [?] will mark an empty test method as Inconclusive 35ms
        [?] will mark an empty parameterized test method as Inconclusive 7ms
        [+] will not mark a not empty test method as Inconclusive 8ms
        [+] will not mark a not empty parameterized test method as Inconclusive 9ms
    Tests completed in 61ms
    Tests Passed: 2, Failed: 0, Skipped: 0, Pending: 2, Inconclusive: 0

**Comment by nohwnd** [comment]
Hmm, could you post a PR or it really does not permit you to do that?

**Comment by Remco-74** [comment]
I created a PR (is my first), I hope this works!

**Comment by nohwnd** [comment]
The related PR was merged a year ago, closing this.
