### ISSUE TITLE
PSCore - escaping lines and other special chars can cause compatibility issue (?)

### ISSUE THREAD

**Issue by it-praktyk** [pester/Pester#838]
After of series of improvements for compatibility with PSCore I stack.

On Windows 10, PowerShell v6.0.0-beta.6 I've failed test

```
  Describing ConvertTo-FailureLines
    [+] produces correct message lines. 51ms
    [-] failed should produces correct message lines. 50ms
      Expected string length 53 but was 98. Strings differ at index 53.
      Expected: {String lengths are both 3. Strings differ at index 0.}
      But was:  {String lengths are both 3. Strings differ at index 0.\nExpected: {Two}\nBut was:  {One}\n-----------^}
      ----------------------------------------------------------------^
      206:             $r.Message[0] | Should be 'String lengths are both 3. Strings differ at index 0.'
      at Invoke-LegacyAssertion, <FOLDER_PATH>\Pester\Functions\Assertions\Should.ps1: line 190
      at <ScriptBlock>, <FOLDER_PATH>\Pester\Functions\Output.Tests.ps1: line 206
```

The code responsible for creating lines about errors tries split message using [System.Environment]::NewLine] - https://github.com/it-praktyk/Pester/blob/dcd862c1476e12fa16ffa800bc9fd31ff9f6abc2/Functions/Output.ps1#L397 but in some other places are used special chars: '\n', '\r' etc. 

For the query `Get-ChildItem *.ps1 -Recurse | Select-String -Pattern '\\n'` I see results

```
<RESULTS_MANUALLY_CLEANED>

Functions\Assertions\Be.ps1:172:        $InputObject -replace "`n","\n" -replace "`r","\r" -replace "`t","\t" -replace "`0", "\0" -replace "`b","\b"
Functions\Assertions\Be.Tests.ps1:134:            PesterBeFailureMessage "`n`r`b`0`tx" "`n`r`b`0`ty" | Should Be "String lengths are both 6. Strings differ at index 5.`nExpected: {\n\r\b\0\ty}`nBut was:  {\n\r\b\0\tx}`n---------------------^"
Functions\Assertions\Be.Tests.ps1:135:            PesterBeFailureMessage "`n`r`b`0`tx" "`n`r`b`0`ty" | Should -Be "String lengths are both 6. Strings differ at index 5.`nExpected: {\n\r\b\0\ty}`nBut was:  {\n\r\b\0\tx}`n---------------------^"
Functions\Assertions\Be.Tests.ps1:139:            PesterBeFailureMessage "123`n456" "123`n789" | Should Be "String lengths are both 7. Strings differ at index 4.`nExpected: {123\n789}`nBut was:  {123\n456}`n----------------^"
Functions\Assertions\Be.Tests.ps1:140:            PesterBeFailureMessage "123`n456" "123`n789" | Should -Be "String lengths are both 7. Strings differ at index 4.`nExpected: {123\n789}`nBut was:  {123\n456}`n----------------^"
Functions\Assertions\Be.Tests.ps1:144:            PesterBeFailureMessage "abcd`n123" "abc!`n123" | Should Be "String lengths are both 8. Strings differ at index 3.`nExpected: {abc!\n123}`nBut was:  {abcd\n123}`n--------------^"
Functions\Assertions\Be.Tests.ps1:145:            PesterBeFailureMessage "abcd`n123" "abc!`n123" | Should -Be "String lengths are both 8. Strings differ at index 3.`nExpected: {abc!\n123}`nBut was:  {abcd\n123}`n--------------^"
Functions\Assertions\PesterThrow.ps1:61:    $positionMessage = $info.PositionMessage -split '\r?\n' -match '\S' -join "`r`n"
Functions\Coverage.Tests.ps1:80:                $jaCoCoReportXml = $jaCoCoReportXml -replace '\n',''
Functions\Describe.ps1:166:        $firstStackTraceLine = $_.InvocationInfo.PositionMessage.Trim() -split '\r?\n' | & $SafeCommands['Select-Object'] -First 1
Functions\Gherkin.ps1:212:            Microsoft.PowerShell.Utility\Add-Member -MemberType NoteProperty -Name Features -Value (Microsoft.PowerShell.Utility\New-Object System.Collections.Generic.List[Gherkin.Ast.Feature]) -PassThru |
Functions\Gherkin.ps1:426:        $firstStackTraceLine = $_.ScriptStackTrace -split '\r?\n' | Microsoft.PowerShell.Utility\Select-Object -First 1
Functions\Gherkin.ps1:480:        $firstStackTraceLine = $_.ScriptStackTrace -split '\r?\n' | Microsoft.PowerShell.Utility\Select-Object -First 1
Functions\Output.ps1:129:            $Describe.Description -split '\n' | ForEach {
Functions\Output.ps1:153:            $Context.Description -split '\n' | ForEach {
```

Generally, it can be (?) inconsistency for special chars usage.

What do you think, how should it be handled in the whole module? Should we switch to something that can be more .Net Core "checkable" per OS?

Additionally especially "suspicious" for me is the function [Assertions\Be.ps1\Expand-SpecialCharacters](https://github.com/it-praktyk/Pester/blob/dcd862c1476e12fa16ffa800bc9fd31ff9f6abc2/Functions/Assertions/Be.ps1#L166-L174).

The related issue: #639

**Comment by nohwnd** [comment]
@it-praktyk  Well who could have forseen that there will be Powershell on Linux 😃 Imho the way to handle this is to use the `[System.Environment]::NewLine` in all the places where we produce messages that include  new lines. And then also in places where we validate those messages.

The Expand-SpecialCharacters is fine, it just replaces incoming invisible characters with their printable verisons and accounts for the changes in length, it is system independent, if the character does not come it won't be produced.

**Comment by it-praktyk** [comment]
@nohwnd, thank you for confirming what I expected. I'll try to do it under resolving the PSCore compatibility issue.

I think that we should start writing something like Pester development guide. It could you be a part of contribution guide - the related issue #636.

What do you think?

**Comment by nohwnd** [comment]
Maybe, the development team is limited to handful of devs at a time. Me and Dave are the ones merging PRs, and we usually catch those "errors" if they are discovered already, or sever breaking of the "rules". The functional problems will be caught by failing build. And the rest can always be fixed later. We all have limited amount of developer time, so I would rather spend it on developing stuff and fixing bugs.

**Comment by it-praktyk** [comment]
I've created the new section in the wiki - Contributing to Pester - and I've started to write [Developement rules - technical](https://github.com/pester/Pester/wiki/Developement-rules---technical).

For other articles in the section, I'll divide existing Contributing to Pester to be more readable and to allow a direct reference to them e.g. in [an issue template](https://help.github.com/articles/creating-an-issue-template-for-your-repository/).

**Comment by Jaykul** [comment]
For what it's worth, it's not necessarily the right thing to just replace everything with Environment.Newline, because _other module authors_ aren't going to do that. 

Authors don't need to change their line endings for scripts to run across platforms, so you're still going to have to deal with source code (and presumably, therefore, trace messages) that have a mix. Especially since <code>&#96;n</code> works pretty much everywhere, and a lot of people who *do* change their behavior are going to use that.

I think when we're splitting things, it's almost always the right thing to use `-split '\r?\n'` 

But when we're outputting, although it's probably always the right thing to use `[Environment]::NewLine` ... it's not necessarily worth inserting `$([Environment]::NewLine)` everywhere instead of using actual line breaks in the source code if we're making a multi-line message using here-strings, or just simply multi-line quoted strings.

Also, is the output field separator (`$OFS`) set to `[Environment]::NewLine` now? Everywhere?

**Comment by it-praktyk** [comment]
I just added information about that to [Development rules - technical](https://github.com/pester/Pester/wiki/Developement-rules---technical)
