### ISSUE TITLE
Pester v4 - the function Describe - parameter CommandUsed - question

### ISSUE THREAD

**Issue by it-praktyk** [pester/Pester#840]
I work to update missed help description for parameters e.g. the `CommandUsed` for the Describe function.

I analyzed the code and tested the function Describe behavior. Based on that I assume that the parameter `CommandUsed` is needed because the function Context calls the Describe with the parameter `CommandUsed` set to "Context" and based on that values output header and indentation is made e.g. [Output.ps1\Write-Describe](https://github.com/pester/Pester/blob/bbc09cf069d3611d2a941f96846c50b6307280bf/Functions/Output.ps1#L107-L134).

Am I right?

I propose to add 
- to the function Describe a parameter validation using ValidateSet('Describe','Context')
- help text: "The parameter CommandUsed is an internal parameter used by Pester and not need to be set directly by you"

The related issue: #648

**Comment by dlwyatt** [comment]
That's my bad, -CommandUsed shouldn't exist on a public-facing function.  Context should probably call `DescribeImpl` directly.  Describe and Context would become identical functions with the exception of the value passed to `DescribeImpl`'s `-CommandUsed` parameter.

I wouldn't limit the options for that parameter, though; my intent was for Gherkin and any other future extensions to be able to pass their user-facing command names to the other Pester internals, so we could make the output match and any other things where that info might be nice to have.

**Comment by dlwyatt** [comment]
Rather than duplicating this bit of code in multiple places:

```posh
    if ($null -eq (& $SafeCommands['Get-Variable'] -Name Pester -ValueOnly -ErrorAction $script:IgnoreErrorPreference))
    {
        # User has executed a test script directly instead of calling Invoke-Pester
        $Pester = New-PesterState -Path (& $SafeCommands['Resolve-Path'] .) -TestNameFilter $null -TagFilter @() -SessionState $PSCmdlet.SessionState
        $script:mockTable = @{}
    }
```

We could put it into a function, _but_, that function would have to be dot-sourced when we call it (so the assignment to the `$Pester` variable would happen in the caller's scope).  That code only matters when someone executes a test script directly instead of running Invoke-Pester.

**Comment by it-praktyk** [comment]
>  -CommandUsed shouldn't exist on a public-facing function.

Is it the last chance to update before releasing Pester v.4?

**Comment by dlwyatt** [comment]
We control when v4 gets released.  I'd say let's update it beforehand.

**Comment by it-praktyk** [comment]
I tried to implement direct call from `Context` to `DescribeImpl` but it causes that tests based on `Assert-MockCalled` fail.

**Comment by nohwnd** [comment]
Not sure what is happening, the CommandUsed does not seem to bind correctly when you pass it through PSBoundParameters, maybe there is a typo I don't see. Calling it directly works though. PR on it's way.

**Comment by it-praktyk** [comment]
Just stupid copy-paste mistake. Below comparison with your pull request. Thx.

![2017-09-05 09_30_25-describe ps1 pester visual studio code](https://user-images.githubusercontent.com/4910261/30050203-da96e178-921d-11e7-8d8f-ec2fc8081108.jpg)
