### ISSUE TITLE
Execute mock even when parameters don't match

### ISSUE THREAD

**Issue by DarkLite1** [pester/Pester#843]
I'm very new to Pester so please be patient with me. The function below is used in a lot of our scripts.

```
Function Send-Mail {
    Param (
        [String]$To
    )

    Write-Host "Send an e-mail to '$To'"
}
```

In the `Describe` clause we have the following lines of code:
```
Mock Send-Mail {} -ParameterFilter {$To -eq 'Chuck@Norris.com'}
."$here\$sut" @Params
Assert-MockCalled Send-Mail -Exactly 1 -Scope it
```

Now every time the `ParameterFilter` matches Chuck Norris, the mail is not send. This is the desired behavior. However, when other users are defined in the `To` parameter of the function, the mail is sent nonetheless as the function isn't mocked anymore. Given that this is a test situation I would rather not have the mails sent to the users in the `To` parameter and have the function still being mocked or rather muted.

Is it possible to have this behavior? An extra switch like `-Mute` or `-Always` would be great. The test would still fail or course,  but the mails wouldn't be sent.

Thank you for your help.

**Comment by nohwnd** [comment]
Hi, you can define catch-all Mock by not specifying the Parameter filter. You can have multiple mocks at the same time.

**Comment by DarkLite1** [comment]
I tried your suggestion but it's not working.  If I understand you correctly, you suggest this:
```
Mock Send-Mail {} -ParameterFilter {$To -eq 'Chuck@Norris.com'}
Mock Send-Mail {}
."$here\$sut" @Params
Assert-MockCalled Send-MailHC -Exactly 1 -Scope it
```
or this:
```
Mock Send-Mail {}
Mock Send-Mail {} -ParameterFilter {$To -eq 'Chuck@Norris.com'}
."$here\$sut" @Params
Assert-MockCalled Send-MailHC -Exactly 1 -Scope it
```
In both cases no mail is sent, which is expected, but there's also no check performed if it is indeed Chuck@Norris.com. Am I missing something?

**Comment by nohwnd** [comment]
The micks with parameter filters should go first (the framework handles that), I'll have to try it to see where the problem is.

**Comment by nohwnd** [comment]
First of all you should import ( dot-source ) your functions at the top of the test script and after that you should define you mocks. With that I don't see why it should not fail. 

```powershell
function Send-Mail ($To) { 
}
describe "a" { 
    it "a" {
        Mock Send-Mail { "default mock" }
        Mock Send-Mail { "parametrized mock" } -ParameterFilter {$To -eq 'Chuck@Norris.com'}
            
        Send-Mail -To 'Chuck@Norris.com' | Write-Host
        Send-Mail | Write-Host

        Assert-MockCalled Send-Mail -Exactly 1 -Scope it -ParameterFilter {$To -eq 'Chuck@Norris.com'}
    }
}
```

**Comment by DarkLite1** [comment]
Thank you very much @nohwnd. Thanks to your example I found my problem. It wasn't really needed to add the function with an empty clause at the top of the test script. What did the trick was addressing the correct function with the `-ParameterFilter` included.

`Assert-MockCalled Send-Mail -Exactly 1 -Scope it -ParameterFilter {$To -eq 'Chuck@Norris.com'}`

I still believe it would be great to have a switch available for the `Mock` CmdLet that automatically changes the following duplicate code:

```
Mock Send-Mail { }
Mock Send-Mail {  } -ParameterFilter {$To -eq 'Chuck@Norris.com'}
```
to:
```
Mock Send-Mail {  } -ParameterFilter {$To -eq 'Chuck@Norris.com'} -Mute
```

The `-Mute` switch is here used as an example but can be named anything and avoids duplicate code.

**Comment by dlwyatt** [comment]
You don't need to have two separate mocks here;  `Mock Send-Mail` is sufficient.  You can still use the `ParameterFilter` on `Assert-MockCalled`

**Comment by DarkLite1** [comment]
OMG... This is one of these moments where I feel the most stupid IT'er on the planet. Thank you @dlwyatt  for the help. Figured it out now.

**Comment by nohwnd** [comment]
Don't worry I've been doing it with two mocks the whole time :D

**Comment by DarkLite1** [comment]
Pfiew... :P Feeling better now. Thanks guys, appreciate the help and tips. I'll close this issue.
