### ISSUE TITLE
Feature clean TestDrive

### ISSUE THREAD

**Issue by DarkLite1** [pester/Pester#844]
It would be great to have an extra parameter on `it` or `in` that allows for the `TestDrive` to be cleaned for each test.

An example:
```
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path) -replace '\.Tests\.', '.'

Function Do-Stuff {
    Param (
        [Parameter(Mandatory)]
        [String]$Path,
        [Parameter(Mandatory)]
        [String]$To
    )

    $Nr = Get-ChildItem -Path $Path | Measure-Object | Select-Object -ExpandProperty Count

    switch ($Nr) {
        1 {'One'; break}
        3 {'Three'; break}
        Default {'Nothing'}
    }
}

Describe 'Input' {
    In $TestDrive {
        it 'Three' {
            'Text' | Out-File -FilePath ".\File1"
            'Text' | Out-File -FilePath ".\File2"
            'Text' | Out-File -FilePath ".\File3"
            Do-Stuff -Path ./ -To me | Should Be 'Three'
        }
        it 'One' {
            Remove-Item -Path .\* -Force
            'Text' | Out-File -FilePath ".\File1"
            Do-Stuff -Path ./ -To me | Should Be 'One'
        }
        it 'No files' {
            Remove-Item -Path .\* -Force
            Do-Stuff -Path ./ -To me | Should Be 'Nothing'
        }
    }
}
```

It would allow boilerplate code like `Remove-Item -Path .\* -Force` to be removed.

Something like this:
```
Describe 'Input' {
    In $TestDrive {
        it 'Three' {
            'Text' | Out-File -FilePath ".\File1"
            'Text' | Out-File -FilePath ".\File2"
            'Text' | Out-File -FilePath ".\File3"
            Do-Stuff -Path ./ -To me | Should Be 'Three'
        }
        it 'One' {
            'Text' | Out-File -FilePath ".\File1"
            Do-Stuff -Path ./ -To me | Should Be 'One'
        }
        it 'No files' {
            Do-Stuff -Path ./ -To me | Should Be 'Nothing'
        }
    } -Clean
}
```

Or this would be great:
```
Describe 'Input' {
    In $TestDrive {
        it 'Three' {
            'Text' | Out-File -FilePath ".\File1"
            'Text' | Out-File -FilePath ".\File2"
            'Text' | Out-File -FilePath ".\File3"
            Do-Stuff -Path ./ -To me | Should Be 'Three'
        } -Clean
        it 'One' {
            'Text' | Out-File -FilePath ".\File1"
            Do-Stuff -Path ./ -To me | Should Be 'One'
        } -Clean
        it 'No files' {
            Do-Stuff -Path ./ -To me | Should Be 'Nothing'
        } -Clean
    }
}
```

I know it can be done with different `Describe` clauses, but sometimes things are grouped because they make better sense when you read it. Would this be possible?

**Comment by dlwyatt** [comment]
You could accomplish that using `BeforeEach { Remove-Item -Path .\* -Force }`

Not sure if it's worth adding new switches for this specific case when it's easily covered by another feature.

**Comment by it-praktyk** [comment]
Based on @dlwyatt's answer I assume that a feature request was refused and I can close the issue now. If you still think that something needs to be discussed please feel free to reopen it.

**Comment by DarkLite1** [comment]
Thx @dlwyatt for the info. I was looking actually at `Get-Help Describe` but couldn't find it in the parameter list as I was expecting something like `-BeforeEach` or `-AfterEach`.  This is the standard way of using CmdLets in PowerShell I believe.

Question, would it be possible to add `-BeforeEach` and `-AfterEach` parameters to `Describe` and `Context`? I think this would help a lot of people finding this utility. It would also make it clear to what scope it applies

https://github.com/pester/Pester/wiki/BeforeEach-and-AfterEach

**Comment by it-praktyk** [comment]
Please read `Get-Help about_BeforeEach_AfterEach` - the files are available in the subfolder en-US

**Comment by DarkLite1** [comment]
Yes I know, thank you. But I'm trying to suggest the following new feature:

```
Describe 'Input' {
    In $TestDrive {
        it 'Three' {
            'Text' | Out-File -FilePath ".\File1"
            'Text' | Out-File -FilePath ".\File2"
            'Text' | Out-File -FilePath ".\File3"
            Do-Stuff -Path ./ -To me | Should Be 'Three'
        }
        it 'One' {
            'Text' | Out-File -FilePath ".\File1"
            Do-Stuff -Path ./ -To me | Should Be 'One'
        }
        it 'No files' {
            Do-Stuff -Path ./ -To me | Should Be 'Nothing'
        }
    }
} **-BeforeEach {Remove-Item -Path .\* -Force}**
```

**Comment by DarkLite1** [comment]
So guys, it might have gotten lost, but the last post suggested am improved parameter feature. Is this now also refused? @dlwyatt  @it-praktyk

**Comment by it-praktyk** [comment]
@dlwyatt?

**Comment by it-praktyk** [comment]
I close this issue because you repeated your feature request directly as #898.
