### ISSUE TITLE
Calls to Write-Progress add significant performance overhead

### ISSUE THREAD

**Issue by Remco-74** [pester/Pester#846]
Write-Progress is called twice for every 'It' (before and after execution). The calls to Write-Progress add significant performance overhead to every testcase. 

**Results with Write-Progress as default (executed 4 times):**

    Tests completed in 76.82s
    Tests Passed: 871, Failed: 0, Skipped: 0, Pending: 15, Inconclusive: 0
    ....
    Tests completed in 64.22s
    Tests Passed: 871, Failed: 0, Skipped: 0, Pending: 15, Inconclusive: 0
    ...
    Tests completed in 63.29s
    Tests Passed: 871, Failed: 0, Skipped: 0, Pending: 15, Inconclusive: 0
    ...
    Tests completed in 64.63s
    Tests Passed: 871, Failed: 0, Skipped: 0, Pending: 15, Inconclusive: 0

**Results with Write-Progress disabled by setting $ProgressPreference (executed 4 times):**

    Tests completed in 52.55s
    Tests Passed: 871, Failed: 0, Skipped: 0, Pending: 15, Inconclusive: 0
    ...
    Tests completed in 53.02s
    Tests Passed: 871, Failed: 0, Skipped: 0, Pending: 15, Inconclusive: 0
    ...
    Tests completed in 53.19s
    Tests Passed: 871, Failed: 0, Skipped: 0, Pending: 15, Inconclusive: 0
    ...
    Tests completed in 52.04s
    Tests Passed: 871, Failed: 0, Skipped: 0, Pending: 15, Inconclusive: 0

**Results without Write-Progress (commented out)  (executed 4 times):**

    Tests completed in 52.95s
    Tests Passed: 871, Failed: 0, Skipped: 0, Pending: 15, Inconclusive: 0
    ...
    Tests completed in 52.01s
    Tests Passed: 871, Failed: 0, Skipped: 0, Pending: 15, Inconclusive: 0
    ...
    Tests completed in 52.03s
    Tests Passed: 871, Failed: 0, Skipped: 0, Pending: 15, Inconclusive: 0
    ...
    Tests completed in 52.58s
    Tests Passed: 871, Failed: 0, Skipped: 0, Pending: 15, Inconclusive: 0

These timings are based on the exact same testset. I used 

> Get-Module | Remove-Module -Force

Before the first call to be sure that the correct code is loaded and to prevent caching issues.

**Results:** 
- The default behavior of using Write-Progress adds roughly 15 seconds on a testrun that takes 50 seconds.
- Both methods for disabling (setting $ProgressPreference to SilentyContinue or removing the calls to Write-Progress) have the same effect of removing this overhead.

**Special considerations:**
- Good testing patterns encourages using many small unit tests. The overhead is greater when using larger numbers of smaller tests as it a cost _per test_.
- $ProgressPreference is set to  'Continue' by default, enabling Write-Progress. 
- Pester uses Write-Progress by default.
- Asking users to change this global setting just for using Pester is not really practical.

**Question:**
Perhaps using Write-Progress should not be the default as it adds significant overhead for every default usage?

**Comment by it-praktyk** [comment]
I agree with you. IMHO Write-Progress is not needed and should be removed.

**Comment by nohwnd** [comment]
I remember we added it because it was a request for long running tasks, I don't think there is a simple way of telling the progress bar to start appearing only after the task takes 1 second to run.

**Comment by it-praktyk** [comment]
Can we extend usage of the Show parameter for Invoke-Pester?

**Comment by nohwnd** [comment]
I was thinking about that as well, the default is `All` and the whole enum is about stuff printed on the screen. So the progress does not seem to belong there. But I guess we could rename `All` to `Default`, and add `Progress`, and then you would call `Invoke-Pester -Show All, Progress` if you wanted progress. Problem is that you won't get progress anymore if you run it directly from editor. (Which I would not miss, but other might miss it.) 
Another solution (that I like more), would be to add an option to PesterOptions, but for that I would like to have the options persistent and automatically picked up, and that needs a bit of thinking and design as well. Let's ask people.

**Comment by it-praktyk** [comment]
What about environmental variables what will be checked (for existence) under Pester start and can the next trigger e.g. set $ProgressPreference to SilentlyContinue for a time when Invoke-Pester is run?

Environmental variables users could set permanently in $Profile.

> Problem is that you won't get progress anymore if you run it directly from editor. (Which I would not miss, but other might miss it.)

My rough calculation is that with displayed progress overall time of tests is longer about 20% - I think that it's worth of "I miss my progress bar" feelings for some users - live is brutal ;-).

**Comment by Remco-74** [comment]
> Problem is that you won't get progress anymore if you run it directly from editor. (Which I would not miss, but other might miss it.)

The progress you see is not really "progress" as there is no progress bar / percentage increase.

**Comment by Remco-74** [comment]
Adding 'Progress' to the -Show options (while not enabled by default) seems to be a logical choice. It is backwards compatible and allows users that want to see the progress bar to still do that.

**Comment by nohwnd** [comment]
This also causes printing issues on Linux. The progress is not really showing any progress, and the original issue #321 was that Pester should show what it is running, which is also not happening very well. I am removing this functionality from 4.1 because it has very bad value to issues ratio. I think we will be replacing it with some verbose progress or something, but I don't want to add quick inconsistent solution under pressure.

**Comment by nohwnd** [comment]
workaround is in place, moves to #939

**Comment by nohwnd** [comment]
The issue is much more severe on TravisCI  😆 

![image2](https://user-images.githubusercontent.com/5735905/32698015-ec58e320-c79c-11e7-99c7-e9cd5fed2cdc.jpg)



![image](https://user-images.githubusercontent.com/5735905/32698012-cba7e7ca-c79c-11e7-8bd7-61510a67046e.png)
