### ISSUE TITLE
Unrecognized escape sequence \F.

### ISSUE THREAD

**Issue by DarkLite1** [pester/Pester#849]
The following code generates an error from within `Pester` v. 4.0.6:

```
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path) -replace '\.Tests\.', '.'
. "$here\$sut"


function DoStuff {
    Write-Host "Do stuff"
}

Describe "DoStuff" {
    Mock DoStuff
        
    it 'Missing stuff' {
        DoStuff
        Assert-MockCalled DoStuff -Exactly 1 -Scope it -ParameterFilter {
            #('Param' -match 'S:\Path') # ArgumentException: parsing "S:\Path" - Malformed \p{X} character escape.
            ('Param' -match 'S:\Folder') # ArgumentException: parsing "S:\Folder" - Unrecognized escape sequence \F.
        }
    }
}
```

I believe the fix can be found on [StackOverlflow](https://stackoverflow.com/questions/25186067/how-to-escape-characters-inside-of-a-parameter-in-powershell):

`[RegEx]::Escape($members)`
That will ensure that characters in strings get interpreted as literals and not as part of the RegEx.

It took me ages to figure out when this would happen. So happy I found it, really annoying bug this one.

**Comment by it-praktyk** [comment]
Sorry, the "bug" is not related to Pester itself.

`PS >'Param' -match 'am'
True
PS >'Param' -match 'S:\Folder'
parsing "S:\Folder" - Unrecognized escape sequence \F.
At line:1 char:1
+ 'Param' -match 'S:\Folder'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException
`

Please read [about_escape_characters](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_escape_characters?view=powershell-5.1&viewFallbackFrom=powershell-Microsoft.PowerShell.Core).

**Comment by DarkLite1** [comment]
Yes, you are correct. I've been looking at this too long... Thanks for pointing that out.
