### ISSUE TITLE
Consider adding Gherkin to readme

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#851]
As suggested in #837 Invoke-Gherkin should be added to the readme file. I am not 100 % sure it won't be confusing the users who see the repo for the first time, because we don't show Invoke-Pester anywhere. Maybe we could list it as "Pester supports two dialects", and show both ways of writing the same test.

**Comment by it-praktyk** [comment]
In my opinion, we need directly mention a Gherking-style tests notation as the new feature of Pester v4.

Unfortunately still is lack of
- fulfilled help - I did small progress but without support @Jaykul it's not easy - #808
- about_Gherkin 

The related issue [V4: Nice to have: Merge Invoke-Pester and Invoke-Gherkin to a single command #552](https://github.com/pester/Pester/issues/552).

**Comment by Jaykul** [comment]
Pretty much everything they say about [cucumber](https://cucumber.io/) applies to Pester's implementation of Gherkin, and their [reference documentation](https://cucumber.io/docs/reference#gherkin) is the starting point for the docs -- we're using their parser, but Pester doesn't do as many output formats as Cucumber does, and doesn't currently have a good way to re-test failures (does it?).

**Comment by nohwnd** [comment]
It does not.

**Comment by nohwnd** [comment]
This needs some good and simple examples, and would make nice article for someones blog article.
