### ISSUE TITLE
Suggestion: Alternative technique for working with parameterized testcases

### ISSUE THREAD

**Issue by Remco-74** [pester/Pester#854]
I would like to propose an alternative method of making testcases parameterizes (or: 'data driven'):

A test script written as follows:

    foreach($describe in (1..2)) { 

        Describe "Dynamic Describe $($describe)" {

            foreach($context in (3..4)) { 

            Context "Dynamic context $($describe).$($context)" {

                    foreach($test in (5..6)) { 

                        It "Dynamic test $($describe).$($context).$($test)" { $true | Should Be $true }

                    }

                } 
            }
        }
    }

results in these results:

    PS > Invoke-Pester -Script .\DataDriven.Tests.ps1
    Executing all tests in '.\DataDriven.Tests.ps1'

    Executing script .\DataDriven.Tests.ps1

      Describing Dynamic Describe 1

        Context Dynamic context 1.3
          [+] Dynamic test 1.3.5 66ms
          [+] Dynamic test 1.3.6 13ms

        Context Dynamic context 1.4
          [+] Dynamic test 1.4.5 43ms
          [+] Dynamic test 1.4.6 11ms

      Describing Dynamic Describe 2

        Context Dynamic context 2.3
          [+] Dynamic test 2.3.5 60ms
          [+] Dynamic test 2.3.6 10ms

        Context Dynamic context 2.4
          [+] Dynamic test 2.4.5 39ms
          [+] Dynamic test 2.4.6 11ms
    Tests completed in 258ms
    Tests Passed: 8, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0

This requires about as much work for the test writer, but does not require any special implementation by Pester. 

In this way, the user is also more in control over how empty test sets are handled (see for example issue https://github.com/pester/Pester/issues/833 and https://github.com/pester/Pester/issues/826 ).

Using this technique, the test writer is more in control over the order of execution of the tests.

When **BeforeAll { }** of **AfterAll { }** is required to collect relevant testdata, test writers can rely on a Nested Describe or Context scope.

**Comment by Remco-74** [comment]
For example, a test for environment validation using a dynamic list of servers, can be written as follows:


    Describe "Server validation" {

        BeforeAll { 
            # collect list of servers to validate, read from AD or file or ..
            $servers = ('server-1', 'server-2') 
        }

        foreach($server in $servers) { 
            Describe "Validate server '$($server)'" {

                BeforeAll {
                    # $session = New-PsSession -computerName $server
                }

                AfterAll {
                    # Remove-PsSession -Session $session
                }
                
                foreach($context in (1..2)) { 
                    Context "Dynamic context $($context)" {

                        foreach($test in (5..6)) { 

                            It "Dynamic test $($context).$($test)" { $true | Should Be $true }

                        }
                    }

                }
            }
        }
    }

**Comment by nohwnd** [comment]
I think people are already doing stuff like this. As you mention there is nothing extra needed from Pester. Personally I don't like this pattern because it is often used when lack of data should fail the test (there is more elaborate description of my thinking somewhere in the recent issues, but I can't find it). But if not running the tests does not cause you any problems I would say go for it :) If you describe it in an article I would be happy to retweet.

**Comment by it-praktyk** [comment]
Parameterized test cases are not described in the wiki. It could be nice have them there. @Remco-74 can ask you about it?

**Comment by Remco-74** [comment]
@it-praktyk considering i'm proposing sunsetting (fasing out) the parameterized testcases as they are now, I don't think it is in the best interest to start documenting them :-)

**Comment by Remco-74** [comment]
In case anyone is interested, here's another sample of using structured data for testing. In this case we prepare 'environments' containing 'servers' and iterate on this data structure with our tests;

    Describe 'Environment validation' {

        BeforeAll { 
            # a structured piece of data we can iterate - environments contain servers
            # typically you would collect this or read it from a configuration file
            $environments = @(
                @{ Name = 'development'; Servers = @('dev-srv-web', 'dev-srv-db') }
                @{ Name = 'staging';     Servers = @('tst-srv-web', 'tst-srv-db') }
                @{ Name = 'production';  Servers = @('prd-srv-web', 'prd-srv-db') }
            )
        }

        # ensure the test data is complete
        Context "Configuration validation" {

            It 'has loaded environment data' {
                $environments | Should Not Be $null
                $environments.Count | Should BeGreaterThan 0
            }

            foreach($env in $environments) {

                # assert environment settings
                Context "Configuration for Environment '$($env.Name)'" {

                    It 'must have a name' {
                        $env.Name | Should Not Be $null
                    }

                    It 'must have 1 or more servers' {
                        $env.Servers | Should Not Be $null
                        $env.Servers.Count | Should BeGreaterThan 0
                    }

                    foreach($server in $env.Servers) {

                        # assertions for all servers in an environment
                        Context "Configuration for Server '$($server)'" {
                            
                            It 'must have a name' {
                                $server | Should Not Be $null
                            }
                        }
                    }
                }
            }
        }

        foreach($environment in $environments) {

            # group tests per environment
            Describe "Environment '$($environment.Name)'" {

                foreach($server in $environment.Servers) {

                    # group tests per server in the environment
                    Describe "Server '$($server)'" {

                        # basic networking tests
                        Context 'Networking' {

                            BeforeAll { 
                                $ping = Test-Connection -ComputerName $server -Count 1 -ErrorAction SilentlyContinue
                            }
                            AfterAll { $ping = $null }

                            It 'can be reached on the network' { 
                                $ping | Should Not Be $null
                            }

                            It 'has Remote Desktop enabled' -Pending { }
                        }

                        # tests requireing remoting (will be skipped when not supported)
                        Context 'Remoting tests' {

                            BeforeAll { $session = Try { New-PsSession -ComputerName $server -ErrorAction SilentlyContinue } Catch { $null } }
                            AfterAll  { if($session) { Remove-PsSession -Session $session -ErrorAction SilentlyContinue }  }

                            # indicate an error with remoting
                            It 'does supports remoting' { 
                                $session | Should Not Be $null
                            }

                            # skips remoting tests when not enabled, to prevent hammering the servers
                            # testresults will indicate these tests were skipped
                            $skip = $true # ($null -EQ $session)

                            Context 'File system' {
                                It 'has the correct volumes' -Skip:$skip { <# ... #> }
                                It 'does not expose default admin shares' -Skip:$skip { <# ... #> }
                                It 'does  expose expected shares' -Skip:$skip { <# ... #> }
                            }

                            Context 'Machine sizing' {
                                It 'has the correct number of CPUs' -Skip:$skip { <# ... #> }
                                It 'has the correct amount of RAM' -Skip:$skip { <# ... #> }
                            }

                            Context 'OS Version' {
                                It 'has the correct Operating System' -Skip:$skip { <# ... #> }
                            }
                        }
                    }
                }
            }
        }
    }

**Comment by it-praktyk** [comment]
@Remco-74, I proposed you documenting this part of Pester because:
- I see that you analyzed that area
- good documentation of the current state allows understanding all that something needs to be done better.

No, I'm no joking.

**Comment by Remco-74** [comment]
Is there some .. documentation .. about writing documentation? where and how do i do that?

**Comment by it-praktyk** [comment]
No, just can edit the Pester wiki. Probably parameterized tests should have a separate article linked to `it`.

**Comment by it-praktyk** [comment]
Ping @Remco-74

**Comment by nohwnd** [comment]
There is nothing Pester should do to solve this, because this is external to it and removing `-TestCases` is not an option.
