### ISSUE TITLE
Detection of empty tests fails when specifying -Skip:$false or -Pending:$false

### ISSUE THREAD

**Issue by RemcoKapinga** [pester/Pester#855]
Skipping of tests is done using the switch parameter -Skip.

When a test should be skipped based on some expression, a variable containing a boolean value can be specified for the switch parameter.

When a test is not skipped, but empty, Pester marks the test incorrectly as succeeded. 

    Describe 'NotSkippedButEmpty' {
        $skip = $false
        It 'should be executed, but be marked inconclusive' -Skip:$skip { }
    }

results in this:

    PS > Invoke-Pester -Script .\SkipEmpty.tests.ps1
    Executing all tests in '.\SkipEmpty.tests.ps1'

    Executing script .\SkipEmpty.tests.ps1

      Describing NotSkippedButEmpty
        [+] should be executed, but be marked inconclusive 38ms
    Tests completed in 38ms
    Tests Passed: 1, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0

It was expected that the test should be marked as inconclusive (since the method is empty).

**Comment by Remco-74** [comment]
Same defect occurs when using -Pending:$false

    Describe 'NotPendingButEmpty' {
        $pending = $false
        It 'should be executed, but be marked inconclusive' -Pending:$pending { }
    }

results in:

    PS> Invoke-Pester -Script .\PendingEmpty.tests.ps1
    Executing all tests in '.\PendingEmpty.tests.ps1'

    Executing script .\PendingEmpty.tests.ps1

      Describing NotPendingButEmpty
        [+] should be executed, but be marked inconclusive 37ms
    Tests completed in 78ms
    Tests Passed: 1, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0

**Comment by nohwnd** [comment]
Thanks for the report. Will have a look in the next minor version.

**Comment by nohwnd** [comment]
Note to self, which test results should be available? And how is Pending different from Inconclusive? Should both be kept?

**Comment by nohwnd** [comment]
There is no Pending anymore, and I won't add it unless there is a really good reason.
