### ISSUE TITLE
Pester 3 to 4 Migration Guide

### ISSUE THREAD

**Issue by alx9r** [pester/Pester#857]
There are a variety of breaking changes between Pester 3 and 4.  I propose that those changes and their implications be documented and published somewhere.  I also propose that that information be entitled "Pester 3 to 4 Migration Guide" or similar.

There is [a related document from the Pester 3 release](https://github.com/pester/Pester/wiki/What's-New-in-Pester-3.0) in the wiki.  That seems like a good document.  A version of that document should probably also be prepared for Pester 4.  

I don't have a strong opinion about where, exactly, the "Pester 3 to 4 Migration Guide" should be published.  It could be a part of the related document mention in the last paragraph, it could be standalone.  I do feel strongly that it should exist in a permalinkable location somewhere. 

This sort of thing has been contemplated for Pester 4 in at least the following places:

* [the proposed release notes](https://github.com/pester/Pester/issues/853) (they currently contain placeholder links to this future document)
* [this (incomplete) list of breaking changes](https://github.com/pester/Pester/issues/811#issue-247560351)
* [this discussion leading to the release notes](https://github.com/pester/Pester/issues/811#issuecomment-323109553)

**Comment by nohwnd** [comment]
Would wiki be a good place to put it?

**Comment by it-praktyk** [comment]
Sounds good.

**Comment by alx9r** [comment]
Ok.  I'll do a first draft when I have a chance.

**Comment by nohwnd** [comment]
Basic [guide is in place](https://github.com/pester/Pester/wiki/Migrating-from-Pester-3-to-Pester-4). Closing.

**Comment by it-praktyk** [comment]
I've added the link to issues labeled as 'Pester migration 3 -> 4' to the migration guide.
