### ISSUE TITLE
Update documenation for Code coverage

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#872]
Update documentation for code coverage to include jacoco and describe how to set it up for VSTS

**Comment by derek-baker** [comment]
I see this was closed and re-opened. Is it still a thing that there's desire for? I could handle it for AzureDevops, but not for other CI/CD products. I'm assuming the place to add this is: https://pester.dev/docs/usage/code-coverage?

**Comment by fflaten** [comment]
Was fixed in pester/docs#39
