### ISSUE TITLE
Complete the "Installation and Update" Article

### ISSUE THREAD

**Issue by alx9r** [pester/Pester#874]
[The Installation and Update article](https://github.com/pester/Pester/wiki/Installation-and-Update) is unfinished and leaves an impression uncharacteristic of the rest of the Pester project.  I propose the following:

* In the short-term, omit the installation methods that are mentioned but not described.
* For all pre-PowerShell 5 installation, recommend that the .zip from the latest release's page be downloaded and its contents copied to `$PSModulePath`.
* In the long-term document and test the other installation methods.

I also propose that only those installation methods that the Pester team intends to test and support for each release be mentioned on that page.

**Comment by nohwnd** [comment]
@alx9r I knew I forgot about something! Do you happen to know if people still use PSGet to install modules on powershell that does not support `Install-Module`?

**Comment by alx9r** [comment]
@nohwnd I do not know.  In general I'm reluctant to recommend or support any deployment method for Pester for which there aren't automated tests that are part of CI.

**Comment by nohwnd** [comment]
@alx9r done. PSGet seems to be problem free ( I used it a lot and never had any problems with it), so I put it in as a convenient way of installing from psgallery on posh2. I don't think we have any tests for any deployment in our CI, but we can safely say that it's proven to work by usage.

**Comment by alx9r** [comment]
@Nohwnd Looks good.
