### ISSUE TITLE
Set-TestInconclusive does not fail the test when running in -Strict mode

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#885]
Setting test to inconclusive marks the test as inconclusive even when running in Strict mode, we are probably making the check first, and then running the test.

Related #529

**Comment by nohwnd** [comment]
Repro: 

```powershell
$path = "$env:TEMP\Strict.tests.ps1"
'describe "a" { it "b" { Set-TestInconclusive } }' | Set-Content $path

Invoke-Pester -Strict "$env:TEMP\Strict.tests.ps1"

# output: 
# Tests completed in 36ms
# Tests Passed: 0, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 1 
```

**Comment by bergmeister** [comment]
This one is going to be opinionated but the user should make a choice whether to mark inconclusive as failed or not. Therefore the current default to pass looks ok to me.
VSTS has this great behaviour that it marks the build as red in this case but the UI hides inconclusive tests by default...

**Comment by renehernandez** [comment]
@nohwnd I am checking this as possible first issue to contribute to, but is this still relevant since in the [docs](https://github.com/pester/Pester/wiki/Set%E2%80%90TestInconclusive) `Set-TestInconclusive` is already deprecated in favor of `Set-ItResult`. 

Or should the resolution for this should cover both `Set-TestInconclusive` and `Set-ItResult`? (in case that `Set-ItResult` has the same issue)

**Comment by nohwnd** [comment]
@renehernandez Yes this is still valid. The underlying mechanism of setting the test result is (I hope :)) the same for both `Set-ItResult` and `Set-TestInconclusive`. The former was deprecated because it does just a single thing and uses `Test` instead of `It` in the name. When this issue is solved the test in which we set a result, should be marked as failed in the result when running with the `-Strict` switch on `Invoke-Pester`, and not as inconclusive (or pending or skipped).

**Comment by renehernandez** [comment]
@nohwnd Sounds good, I am go to start working on it this weekend

**Comment by nohwnd** [comment]
Good, ping me if you need help:) twitter will get you faster response :)
