### ISSUE TITLE
Test Publishing to PowerShell Gallery Using Pre-release Semantics

### ISSUE THREAD

**Issue by alx9r** [pester/Pester#889]
Pester 4 release candidates (rc) were published to PowerShell gallery as though they were stable.  They weren't.  The public API changed from 4.0.6-rc to 4.07 and caused the pain in #877 (among other pain, I imagine).  The cause of that pain [was summed up by @nohwnd](https://github.com/pester/Pester/issues/877#issuecomment-329948805):

>  We cannot push pre-releases to PSGalllery, because it does not support it.

It turns out that there is [a draft RFC for PowerShell Gallery to support pre-release semantics](https://github.com/PowerShell/PowerShell-RFC/blob/master/1-Draft/RFC0013-PowerShellGet-PowerShellGallery_PreRelease_Version_Support.md) and that [@JKeithB is recruiting willing users to "try out a pre-release (of the pre-release support)".](https://github.com/PowerShell/PowerShell-RFC/issues/42#issuecomment-330357818)

This seems like a good way to start to get the Pester PowerShell Gallery release process working with pre-release semantics.

**Comment by it-praktyk** [comment]
I like it.

**Comment by it-praktyk** [comment]
[Prerelease Versioning Added to PowerShellGet and PowerShell Gallery](https://blogs.msdn.microsoft.com/powershell/2017/12/05/prerelease-versioning-added-to-powershellget-and-powershell-gallery/)

**Comment by nohwnd** [comment]
It's on my work list.
