### ISSUE TITLE
Assert-MockCalled's ParameterFilter no longer counts invocations when script block has no return value

### ISSUE THREAD

**Issue by brantb** [pester/Pester#894]
In Pester 3.x I frequently used the following pattern with `Assert-MockCalled`:

```powershell
Describe 'System under test' {
    It 'Does something useful' {
        Mock MockedCommand {}

        Invoke-Sut  # Calls MockedCommand internally

        Assert-MockCalled MockedCommand -ParameterFilter {
            $ActionType | Should Match 'Useful'
        }
    }
}
```

My reason for doing this was the improved error messages that `Should` would generate, i.e. `Expected: {NotUseful} to match the expression {Useful}`.

In Pester 4.x, this technique no longer works. `Assert-MockCalled` fails with the message `Expected MockedCommand to be called at least 1 times but was called 0 times`, whereas in 3.x the same test would have passed. Adding `return $true` to the end of the scriptblock reverts to the 3.x behavior.

Gist with demo: https://gist.github.com/brantb/2ee6bc26a2a98eb74fa729a76f636b9b

I'm not sure if this is a bug, but it *is* a change in behavior.

**Comment by alx9r** [comment]
@brantb I'm not in a place I can follow your repro right now.  Would you be able to create a test that reveals whether it is the behavior of `Should` or `Assert-MockCalled` that changed from Pester 3.x to 4.x?

**Comment by brantb** [comment]
@alx9r I updated the [gist](https://gist.github.com/brantb/2ee6bc26a2a98eb74fa729a76f636b9b), I hope that makes the change in behavior clearer. From what I can tell, the change in behavior lies in `Assert-MockCalled`, but I can't seem to figure out what caused it.

**Comment by dlwyatt** [comment]
I'm surprised it ever worked.  ParameterFilter has always been assumed to return a boolean value (true for match, false otherwise).  Technically any value can be converted to a boolean in PowerShell, so maybe something was leaking from the Should command's output stream in previous versions.

**Comment by dlwyatt** [comment]
Ah, there it is:  https://github.com/pester/Pester/blob/95c7af19c1366bd1bfba2b129e096ae025af6305/Functions/Assertions/Should.ps1#L79

`MoveNext()` returns a boolean value, and we were redirecting it anywhere.  No one noticed because the `It` command (where people would tend to call `Should`) does suppress output.

**Comment by dlwyatt** [comment]
Anyhow, old behavior was a bug.

**Comment by brantb** [comment]
Don't you just love those "I'm surprised this ever worked" moments? 😁 Thanks for looking into this @dlwyatt.

FWIW though, I don't find the error messages generated by `Assert-MockCalled` very helpful in troubleshooting test failures, which is why I combined them with `Should` assertions in the first place. If you folks decide to stick with the 3.x behavior, would you instead consider this a feature request to improve them?

**Comment by alx9r** [comment]
@brantb There's a thread about getting more information from `Assert-MockCalled` failures over on #376 that you might be interested in.

**Comment by nohwnd** [comment]
@brantb I am trying to figure out a way to process the predicate in a way that returns more info without the user having to do anything special either by rewriting the ast or doing some replacements via regex. Will continue the discussion in #376 join there please if you want to follow up :)
