### ISSUE TITLE
Chocolatey package failed verifier

### ISSUE THREAD

**Issue by majkinetor** [pester/Pester#896]
Last 2 packages are waiting for maintainer to fix them.

> Binary files (.exe, .msi, .zip) have been included without including a VERFICATION.txt file. This file is required when including binarie

Could you also please update `packageSourceUrl` so we know where is the code of this package.

**Comment by it-praktyk** [comment]
@IISResetMe, @nohwnd, does #957 resolve it?

**Comment by IISResetMe** [comment]
That's the intension, @majkinetor can you verify?

**Comment by it-praktyk** [comment]
Thank you!

**Comment by AdmiringWorm** [comment]
I take it that the metadata file used for the chocolatey package is the one in the root of the repo?
If so, it seems to missing the reference to the VERIFICATION.txt file in it.

**Comment by it-praktyk** [comment]
@AdmiringWorm, can you look at [an updated version](https://github.com/it-praktyk/Pester/blob/657273b4d4bb50e35dda7fd4241672161ac5ac6c/Pester.nuspec#L20) of Pester.nuspec?

**Comment by AdmiringWorm** [comment]
@it-praktyk LGTM

**Comment by it-praktyk** [comment]
Thx @AdmiringWorm!
