### ISSUE TITLE
Pester 4.0.8 Not Catalog Signed Error?

### ISSUE THREAD

**Issue by NeilBird** [pester/Pester#900]
Installing latest Pester 4.0.8 as part of a CI/CD Pipeline in Microsoft Visual Studio Team Services for PowerShell Unit Testing. Getting the error below:

PackageManagement\Install-Package : **The version '4.0.8' of the module 'Pester' being installed is not catalog signed.** Ensure that the version '4.0.8' of the module 'Pester' has the catalog file 'Pester.cat' and signed with the same publisher 'CN=Microsoft Root Certificate Authority 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US' as the previously-installed module '4.0.8' with version '3.4.0' under the directory 'C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0'. If you still want to install or update, use -SkipPublisherCheck parameter. At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1772 char:21 + ... $null = PackageManagement\Install-Package @PSBoundParameters + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception + FullyQualifiedErrorId : ModuleIsNotCatalogSigned,Validate-ModuleAuthenticodeSignature,Microsoft.PowerShell.Packa geManagement.Cmdlets.InstallPackage 

If I used "Install-Module -Name Pester -Force -Verbose -Scope CurrentUser -RequiredVersion **4.0.7**" - This error is NOT given.

Is this an issue with Pester 4.0.8?

Neil

**Comment by it-praktyk** [comment]
Please read the article [Installation and Update](https://github.com/pester/Pester/wiki/Installation-and-Update).

**Comment by NeilBird** [comment]
Great, thanks for info regarding known limitation when installing the latest version due to different Certificate / Signature. I will include the "**-SkipPublisherCheck**" parameter.
