### ISSUE TITLE
Extend Pester Gherkin Support to Write Test Stubs from Feature Files

### ISSUE THREAD

**Issue by RandomNoun7** [pester/Pester#906]
My employer has a use case where we want people to be able to write business scenarios as Gherkin files, and then automatically turn those files into test stubs that others can implement.

I found that Pester already has a Gherkin parsing dll that I leveraged to make writing the stubs possible. Since I am using Pester's dll for this, I think it would be nice if this functionality was within Pester itself so I am not forced to use the dll from outside of Pester, which would be very messy. 

The new function is called ```Import-FeatureFile```

It takes a path, recurses through the folder structure, and writes stubs for any Gherkin files that it finds. 

If someone then updates a Gherkin file with more tests, just invoke ```Import-FeatureFile``` again, and it will add the new stubs to the existing test file.

I am very much open to any criticism of how this code looks, functions, or any other suggestions required to get this code ready for inclusion in the project.

Thanks,
Bill

**Comment by it-praktyk** [comment]
> My employer has a use case where we want people to be able to write business scenarios as Gherkin files, 
> and then automatically turn those files into test stubs that others can implement.

Thank you for your contributions to Pester project. I hope that we will review it soon.

Can I ask you what resources do you use to learn employees write Gherkin tests? I'm asking because Gherkin is a relatively new feature of Pester and we still didn't complete documentation to it.

**Comment by RandomNoun7** [comment]
@it-praktyk 
Right now it's just me learning it. This project is in the very earliest stages, so it's up to me to create the process and then train others. 

My main resources are just Cucumber and Gherkin documentation and [this excellent blog post](https://kevinmarquette.github.io/2017-04-30-Powershell-Gherkin-advanced-features/#table-support) by Kevin Marquette.

**Comment by it-praktyk** [comment]
Feel free to contribute to the documentation too. Thank you in advance.

**Comment by Jaykul** [comment]
This is a great idea...

**Comment by nohwnd** [comment]
Pester v4 is maintenance only, and Pester v5 does not contain Gherkin anymore and won't add it in the future. It is up to the community around Gherkin to pick this up in a new module, or a fork of v4.
