### ISSUE TITLE
how to take action when 1 of It blocks inside Describe block failed?

### ISSUE THREAD

**Issue by simonfangyingzhang** [pester/Pester#909]
Hi Guru,

suppose I have 1 Describe and multiple It blocks inside it, when 1 It block failed, I need to collect support files for debug, how I should using pester? could you please share with me sample code?

or I have to using 1 Describe with single It blocks inside it? thanks in advance

**Comment by it-praktyk** [comment]
You can use switches to run your tests. 

Quotes from `Get-Help Invoke-Pester -Full`

> -PassThru [<SwitchParameter>]
>       Returns a custom object (PSCustomObject) that contains the test results.

>        By default, Invoke-Pester writes to the host program, not to the output stream (stdout).
>       If you try to save the result in a variable, the variable is empty unless you
>        use the PassThru parameter.

or

>    -EnableExit [<SwitchParameter>]
>       Will cause Invoke-Pester to exit with an exit code equal to the number of failed
>        tests once all tests have been run. Use this to "fail" a build when any tests fail.

**Comment by simonfangyingzhang** [comment]
thank you it-praktyk for your info,

I was expecting, if 1 It block failed, I can collect support files and then continue to run next It block,

looks like I have to using 1 Describe with single It blocks inside it?

**Comment by simonfangyingzhang** [comment]
Hi Guru,

is there a way in Pester for my testing request? thanks
