### ISSUE TITLE
Background scenario is executed more often than once for every scenario

### ISSUE THREAD

**Issue by RandomOff** [pester/Pester#911]
The Background scenario appears to execute as the background for itself. For example I expected a one scenario feature should only execute background once instead of 3 times.

### Reproduction Step

```
Describe "Defect Reproduction" {
    "
        Feature: Feature
        Background: Background 
            Given Background
        Scenario: Scenario
            Given Scenario
    " > TestDrive:\Background.feature

    'Given "(?<name>.*)" {Param($name); Write-Warning $name}' > TestDrive:\Background.steps.ps1
    
    Invoke-Gherkin -Path TestDrive:\Background.feature
}
```

### Expected Results

```
Describing Defect Reproduction
Testing all features in 'TestDrive:\Background.feature'

Feature: Feature

  Scenario: Background
    [+] Given Background 1ms

  Scenario: Scenario
WARNING: Background
WARNING: Scenario
    [+] Given Scenario 1ms
Testing completed in 2ms
Scenarios Passed: 1 Failed: 0
Steps Passed: 2 Failed: 0 Skipped: 0 Pending: 0 Inconclusive: 0 
```

### Actual Result

```
Feature: Defect Reproduction
Testing all features in 'TestDrive:\Background.feature'

Feature: Feature

  Scenario: Background
WARNING: Background
WARNING: Background
    [+] Given Background 0ms

  Scenario: Scenario
WARNING: Background
WARNING: Scenario
    [+] Given Scenario 4ms
Testing completed in 5ms
Scenarios Passed: 2 Failed: 0
Steps Passed: 2 Failed: 0 Skipped: 0 Pending: 0 Inconclusive: 0 
Test-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Users\Administrator\Documents\WindowsPowerShell\Modules\Pester\Functions\TestDrive.ps1:122 char:44
+     if (& $SafeCommands['Test-Path'] -Path $Path)
+                                            ~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathComm 
   and
```

### Note
Also discovered attempting to reproduce: 
- Null path parameter error after successful completion.
- Feature header instead of Describing header (fixed in latest version)

### Tested on

> Pester version     : 4.0.3 C:\Users\Administrator\Documents\WindowsPowerShell\Modules\Pester\Pester.psm1
> PowerShell version : 4.0
> OS version         : Microsoft Windows NT 6.2.9200.0

and

> Pester version     : 3.4.0 4.0.8 C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Pester.psm1 C:\Program Files\WindowsPowerShell\Modules\Pester\4.0.8\Pester.psm1
> PowerShell version : 5.1.14393.1532
> OS version         : Microsoft Windows NT 10.0.14393.0

**Comment by it-praktyk** [comment]
CC: @Jaykul

**Comment by Jaykul** [comment]
Bug confirmed. Will fix.

The things you "discovered attempting to reproduce" are caused by trying to run Pester-in-Pester.  You can't call `Invoke-Pester` nor `Invoke-Gherkin` from **inside** your tests. Notice the [Pester tests for Gherkin](https://github.com/pester/Pester/blob/master/Functions/Gherkin.Tests.ps1#L8) call Gherkin in a _job_ to avoid this.

**Comment by RandomOff** [comment]
Thanks!
