### ISSUE TITLE
Mock Get-ADGroupMember with ParameterFilter on Identity

### ISSUE THREAD

**Issue by DarkLite1** [pester/Pester#912]
Why does this work fine:

```
Describe 'My test' {
    Mock Get-ADGroupMember {
        1
    } -ParameterFilter {"MYGROUP"}

    it 'Test' {
        Get-ADGroupMember -Identity "MYGROUP" | Should -BeExactly 1
    }
}
```

And this doesn't:
```
Describe 'My test' {
    Mock Get-ADGroupMember {
        1
    } -ParameterFilter {$Identity -eq "MYGROUP"}
            
            
    it 'Test' {
        Get-ADGroupMember -Identity "MYGROUP" | Should -BeExactly 1
    }
}

ADIdentityNotFoundException: Cannot find an object with identity: 'MYGROUP' under: 'DC=xxx'
```

Did I miss something super obvious here?

**Comment by dlwyatt** [comment]
-ParameterFilter returns a Boolean value; “MYGROUP” is always true when cast to a bool.

**Comment by DarkLite1** [comment]
Thanks for the feedback. I was wondering how it's possible to return `user A` when `group A` is provided and return `user B` when `group B` is provided. I can't seem to get that right....

**Comment by DarkLite1** [comment]
@it-praktyk I'm ok closing the issue but I still haven't found an answer to the question:

> I was wondering how it's possible to return user A when group A is provided and return user B when group B is provided. I can't seem to get that right....

Is this even possible?

**Comment by it-praktyk** [comment]
Maybe you can use your own custom function for it? But I can be wrong.
