### ISSUE TITLE
Mock Get-ADUser : The input object cannot be bound to any parameters

### ISSUE THREAD

**Issue by DarkLite1** [pester/Pester#914]
Sorry guys for bothering you again, but can someone tell me why this isn't working properly?

```
Describe 'My test' {
    Mock Get-ADGroup {
        $GroupName = 'Group'
        [PSCustomObject]@{
            Description       = 'Quota group'
            CanonicalName     = 'contoso.com/EU/Groups/{0}' -f $GroupName
            CN                = $GroupName
            Name              = $GroupName
            SamAccountName    = $GroupName
            DisplayName       = $GroupName
            DistinguishedName = 'CN={0},OU=Groups,OU=EU,DC=contoso,DC=com' -f $GroupName
            GroupCategory     = 'Security'
            GroupScope        = 'Global'
            Mail              = ''
            ObjectClass       = 'group'
        }
    }
    Mock Get-ADGroupMember {
        [PSCustomObject]@{           
            DistinguishedName = "CN=Norris\, Chuck,OU=Users,OU=EU,DC=contoso,DC=com"
            Enabled           = $true
            GivenName         = 'Chuck'
            Name              = 'Norris, Chuck'
            ObjectClass       = 'user'
            ObjectGUID        = 'c1a3e1e7-cfc8-4569-885c-4d6bd2f6c433'
            SamAccountName    = 'norrisc'
            SID               = 'S-1-5-21-1078081533-261478967-839522115-138487'
            Surname           = 'Norris'
            UserPrincipalName = 'Norrisc@contoso.com'
        }
    }
    Mock Get-ADUser {
        [PSCustomObject]@{           
            DistinguishedName = "CN=Norris\, Chuck,OU=Users,OU=EU,DC=contoso,DC=com"
            Enabled           = $true
            GivenName         = 'Chuck'
            HomeDirectory     = '\\contoso.com\HOME\Norrisc'
            Name              = 'Norris, Chuck'
            ObjectClass       = 'user'
            ObjectGUID        = 'c1a3e1e7-cfc8-4569-885c-4d6bd2f6c433'
            SamAccountName    = 'norrisc'
            SID               = 'S-1-5-21-1078081533-261478967-839522115-138487'
            Surname           = 'Norris'
            UserPrincipalName = 'Norrisc@contoso.com'
        }
    }
    
    Describe 'test' {
        it 'test' {
            $QuotaUsers = Get-ADGroup -Filter "Name -like '$QuotaGroupName*'" | ForEach-Object {
                $Group = $_.SamAccountName
                Get-ADGroupMember $_.SamAccountName -Recursive | Get-ADUser -Properties HomeDirectory | 
                    where {$_.Enabled -and $_.HomeDirectory} | 
                    Select-Object SamAccountName, @{N='GroupName';E={$Group}}
            }

            ($QuotaUsers | Measure-Object).Count | Should -BeExactly 1
        }
    }
}
```

Within the `foreach` it appears that the mocked `Get-Aduser` doesn't seem to be able to accept pipeline input.

Thank you for your help.

**Comment by dlwyatt** [comment]
The pipeline input for Get-AdUser is a strict object type (`[Microsoft.ActiveDirectory.Management.ADUser]`), and your mock is outputting a PSCustomObject instead.  Working with commands like this is one of the challenges we have with mocking right now.

**Comment by it-praktyk** [comment]
@DarkLite1, please read #803, IMHO it's related to your case too.

**Comment by DarkLite1** [comment]
Thank you @it-praktyk for the link, but I can't seem to get it to work with piping objects to `Get-ADUser`. As I understand it from @dlwyatt it's currently not possible to `mock` the behavior of a `CmdLet` that receives pipeline input. 

I tried the following but still having the same issue:
```
    Mock Get-ADUser {
        Param (
            [Parameter(ValueFromPipeline)]$stuff
        )
        [PSCustomObject]@{           
            ...
        }
    }
```

**Comment by it-praktyk** [comment]
I assume that the issue can be closed now. Feel free to reopen if you need more assistance.

**Comment by DarkLite1** [comment]
I don't know if adding a `Name` property is a `Pester` issue. But it is nonetheless not possible to pipe to a mocked `Get-ADUser` function.

**Comment by DarkLite1** [comment]
I'm still struggling with this. Piping to `Get-ADUser` seems to be impossible when `Get-ADUser` is mocked. If anyone knows a way how to do this with an example that would be nice.

**Comment by nohwnd** [comment]
@DarkLite1 Could you give me an example of what is wrong please?

**Comment by DarkLite1** [comment]
Thank you for your help @nohwnd . In the code below I'm trying to get the filter correct for `Get-ADUser` in case a specific user object is piped to it. but I can't seem to get it right.

Describe 'disregarded users' {
    it "exclude users that are member of 'ExcludedGroups'" {
        Mock Get-ADGroupMember {
            New-Object Microsoft.ActiveDirectory.Management.ADUser Identity -Property @{
                SamAccountName = 'jlewis'
                GivenName = 'John'
                Surname = 'Doe'
                DistinguishedName = 'CN=Doe John,CN=Users,DC=contoso,DC=com'
            }
        }  
        Mock Get-ADUser {
            New-Object Microsoft.ActiveDirectory.Management.ADUser Identity -Property @{
                SamAccountName = 'jlewis'
                GivenName = 'John'
                Surname = 'Doe'
                DistinguishedName = 'CN=Doe John,CN=Users,DC=contoso,DC=com'
            }
            New-Object Microsoft.ActiveDirectory.Management.ADUser Identity -Property @{
                SamAccountName = 'mtyson'
                GivenName = 'John'
                Surname = 'Doe'
                DistinguishedName = 'CN=Doe John,CN=Users,DC=contoso,DC=com'
            }
            New-Object Microsoft.ActiveDirectory.Management.ADUser Identity -Property @{
                SamAccountName = 'norrisc'
                GivenName = 'John'
                Surname = 'Doe'
                DistinguishedName = 'CN=Doe John,CN=Users,DC=contoso,DC=com'
            }
        }
        Mock Get-ADUser {
            New-Object Microsoft.ActiveDirectory.Management.ADUser Identity -Property @{
                SamAccountName = 'jlewis'
                GivenName = 'John'
                Surname = 'Doe'
                DistinguishedName = 'CN=Doe John,CN=Users,DC=contoso,DC=com'
            }
        } -ParameterFilter {
            'jlewis' -eq $SamAccountName
        }

        (Get-ADGroupMember 'ExcludedGroups' -Recursive | Measure-Object).Count | Should -BeExactly 1
        (Get-ADUser 'bob' | Measure-Object).Count | Should -BeExactly 3


        $Excl = Get-ADGroupMember 'ExcludedGroups' -Recursive | Get-ADUser
        ($Excl | Measure-Object).Count | Should -BeExactly 1
        'jlewis' | Should -BeIn $Excl.SamAccountName
        'norrisc' | Should -Not -BeIn $Excl.SamAccountName
        'mtyson' | Should -Not -BeIn $Excl.SamAccountName
    }
}

**Comment by DarkLite1** [comment]
I think I found it now. stupid me. Closing issue.

```
Mock Get-ADUser {
    New-Object Microsoft.ActiveDirectory.Management.ADUser Identity -Property @{
        SamAccountName = 'jlewis'
        GivenName = 'John'
        Surname = 'Doe'
        DistinguishedName = 'CN=Doe John,CN=Users,DC=contoso,DC=com'
    }
} -ParameterFilter {
    'jlewis' -eq $Identity.SamAccountName
}
```

**Comment by Glober777** [comment]
> Thank you @it-praktyk and @dlwyatt, so it's currently not possible to `mock` the behavior of a `CmdLet` that receives pipeline input.
> 
> In #448 the following is suggested which seems to do the trick:
> 
> ```
> Describe 'Test identity parameter' {
>     Mock Get-ADGroup {
>         New-Object Microsoft.ActiveDirectory.Management.ADGroup Identity -Property @{
>             #Name          = 'My group'
>             GroupCategory     = 'Security'
>             GroupScope        = 'Universal'
>             distinguishedName = 'CN=Doe John,CN=Users,DC=contoso,DC=com'
>         }
>     }
>     
>     Mock Get-ADUser {
>         New-Object Microsoft.ActiveDirectory.Management.ADUser Identity -Property @{
>             GivenName = 'John'
>             Surname = 'Doe'
>             DistinguishedName = 'CN=Doe John,CN=Users,DC=contoso,DC=com'
>         }
>     }
> 
>     It 'should work' {
>         Get-ADGroup -Identity kiwi | Get-ADUser | Select -ExpandProperty SurName | Should -BeExactly 'Doe'
>     }  
> }
> ```
> 
> The only thing that doesn't seem to be possible is adding a `Name` property 😞 Then it complains about:
> 
> > Exception: The value supplied is not valid, or the property is read-only. Change the value, and then try again.

Hey @DarkLite1, I know this is an old post, but I've been struggling to add the `Name` property myself and found that it is actually possible:
```posh
Mock Get-ADGroup {
    $ADGroup = New-Object Microsoft.ActiveDirectory.Management.ADGroup Identity -Property @{
        #Name          = 'My group'
        GroupCategory     = 'Security'
        GroupScope        = 'Universal'
        distinguishedName = 'CN=Doe John,CN=Users,DC=contoso,DC=com'
    }

    $ADGroup.Item('Name').Add('My group') | Out-Null
    $ADGroup
}
```
What is important, is that the addition of the `Name` property happen after other properties are populated as otherwise, the ADPropertyCollection is not initialized yet. This same trick works for `ADUser` type objects as well.

I hope it may be helpful for other as well.

**Comment by Glober777** [comment]
Strangely though, this trick only works in Windows PowerShell, and doesn't in PS 7.2.3 (using AD module 1.0.1.0)
