### ISSUE TITLE
[Feature Request] Specify tags for test

### ISSUE THREAD

**Issue by f0rt** [pester/Pester#915]
Team,

Please implement Tag support for each test(It). Specifying tags for each test group (Describe) is very helpful but in some cases I need more flexibility and I don't want to create test groups with 1 test just to take advantage of the Tag functionality.

Thanks,
Nedko

**Comment by dlwyatt** [comment]
Right now, tags are only useful on the outermost test group, because Pester doesn't parse the whole test script to try to figure out an execution plan before running stuff.  We have some ideas of how to make that happen, but until that's ready, there's no benefit to putting tags on `It` blocks.

**Comment by it-praktyk** [comment]
Your requests it's a duplicate for #721 so I'm closing it now.
