### ISSUE TITLE
Assert-VerifiableMocks fails to assert uncalled mocks

### ISSUE THREAD

**Issue by mikeclayton** [pester/Pester#916]
I've inherited a project which uses Pester that correctly fails a test on our build agent using Pester 3.4.0 but incorrectly passes the same test locally using Pester 4.0.8. The difference seems to be that ```Assert-Verifiable``` does not detect an uncalled Mock in my Context when I use Pester 4.0.8, but *does* assert in Pester 3.4.0.

I've reduced it to the smallest reproducible example that I can below. Running Pester over these scripts results in version 3.4.0 correctly failing the test, but Pester 4.0.8 passes the test - I'm not sure if this a breaking change or a bug?

Interestingly, using ```Assert-MockCalled "Invoke-MyOtherFunction"``` instead of ```Assert-Verifiable``` fails the test in both versions of Pester.

**Invoke-MyFunction.ps1**
```
function Invoke-MyFunction
{
    param
    (
        [Parameter(Mandatory=$true)]
        [string] $MyParam
    )
    write-host "Invoke-MyFunction called with `$MyParam = '$MyParam'";
    return (Invoke-MyOtherFunction -MyOtherParam $MyParam);
}
```

**Invoke-MyOtherFunction.ps1**
```
function Invoke-MyOtherFunction
{
    param
    (
        [Parameter(Mandatory=$true)]
        [string] $MyOtherParam
    )
    write-host "Invoke-MyOtherFunction called with `$MyOtherParam = '$MyOtherParam'";
    return "aaa-$MyOtherParam-zzz";
}
```

**Invoke-MyFunction.Tests.ps1**
```
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path) -replace '\.Tests\.', '.'
. "$here\$sut"
. "$here\Invoke-MyOtherFunction.ps1"

Describe "Invoke-MyFunction" {

    Context "when Mocks are not called because ParameterFilter does not match" {
        Mock -CommandName "Invoke-MyOtherFunction" `
             -ParameterFilter { $MyOtherParam -eq "not a match" } `
             -Verifiable;
        It "should assert that mocks have not been called" {
            $result = Invoke-MyFunction -MyParam "test";
            Assert-VerifiableMocks;
        }
    }

}
```

**Output from Pester 3.4.0**
```
Describing Invoke-MyFunction
   Context when Mocks are not called because ParameterFilter does not match
Invoke-MyFunction called with $MyParam = 'test'
Invoke-MyOtherFunction called with $MyOtherParam = 'test'
    [-] should assert that mocks have not been called 922ms
      RuntimeException:  Expected Invoke-MyOtherFunction to be called with  $MyOtherParam -eq "not a match"
      at Assert-VerifiableMocks, C:\build\Pester\3.4.0\Pester\Functions\Mock.ps1: line 434
      at <ScriptBlock>, C:\build\Pester\test\scripts\Invoke-MyFunction.Tests.ps1: line 25
Tests completed in 922ms
Passed: 0 Failed: 1 Skipped: 0 Pending: 0 Inconclusive: 0
```

**Output from Pester 4.0.8**
```Executing all tests in '.'

Executing script C:\build\Pester\test\scripts\Invoke-MyFunction.Tests.ps1

  Describing Invoke-MyFunction

    Context when Mocks are not called because ParameterFilter does not match
Invoke-MyFunction called with $MyParam = 'test'
Invoke-MyOtherFunction called with $MyOtherParam = 'test'
      [+] should assert that mocks have not been called 927ms
Tests completed in 927ms
Tests Passed: 1, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0
```

**Comment by mikeclayton** [comment]
After a bit more testing it looks like the behaviour changed around version 4.0.6-4.0.8

**Output from Pester 4.0.6**
(correctly fails the test because my Verifiable Mock hasn't been called)
```
Executing all tests in '.'

Executing script C:\build\Pester\test\scripts\Invoke-MyFunction.Tests.ps1

  Describing Invoke-MyFunction

    Context when Mocks are not called because ParameterFilter does not match
Invoke-MyFunction called with $MyParam = 'test'
Invoke-MyOtherFunction called with $MyOtherParam = 'test'
      [-] should assert that mocks have not been called 948ms
        RuntimeException:  Expected Invoke-MyOtherFunction to be called with  $MyOtherParam -eq "not a match"
        at Assert-VerifiableMocks, C:\build\Pester\4.0.6\Pester\Functions\Mock.ps1: line 429
        at <ScriptBlock>, C:\build\Pester\test\scripts\Invoke-MyFunction.Tests.ps1: line 25
Tests completed in 948ms
Tests Passed: 0, Failed: 1, Skipped: 0, Pending: 0, Inconclusive: 0
```

**Output from Pester 4.0.7**
(looks like Pester has broken internals?)
```
Executing all tests in '.'

Executing script C:\build\Pester\test\scripts\Invoke-MyFunction.Tests.ps1

  Describing Invoke-MyFunction

    Context when Mocks are not called because ParameterFilter does not match
Invoke-MyFunction called with $MyParam = 'test'
Invoke-MyOtherFunction called with $MyOtherParam = 'test'
      [-] should assert that mocks have not been called 1.03s
        CommandNotFoundException: The term 'Assert-VerifiableMocks' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
        at <ScriptBlock>, C:\build\Pester\test\scripts\Invoke-MyFunction.Tests.ps1: line 25
Tests completed in 1.03s
Tests Passed: 0, Failed: 1, Skipped: 0, Pending: 0, Inconclusive: 0
```

**Output from Pester 4.0.8**
(incorrectly passes the test even though my Verifiable Mock hasn't been called)
```
Executing all tests in '.'

Executing script C:\build\Pester\test\scripts\Invoke-MyFunction.Tests.ps1

  Describing Invoke-MyFunction

    Context when Mocks are not called because ParameterFilter does not match
Invoke-MyFunction called with $MyParam = 'test'
Invoke-MyOtherFunction called with $MyOtherParam = 'test'
      [+] should assert that mocks have not been called 937ms
Tests completed in 937ms
Tests Passed: 1, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0
```

**Comment by mikeclayton** [comment]
Ok, I've worked out the problem - I didn't read the manual!

https://github.com/pester/Pester/wiki/Migrating-from-Pester-3-to-Pester-4

```rename all occurrences of Assert-VerifiableMocks to Assert-VerifiableMock```

However, can I suggest that at the bottom of Pester.psm1,

```function Assert-VerifiableMocks { [CmdletBinding()]param()  "This command has been renamed to 'Assert-VerifiableMock' (without the 's' at the end), please update your code. For more information see: https://github.com/pester/Pester/wiki/Migrating-from-Pester-3-to-Pester-4" }```

is changed to

```function Assert-VerifiableMocks { [CmdletBinding()]param()  throw "This command has been renamed to 'Assert-VerifiableMock' (without the 's' at the end), please update your code. For more information see: https://github.com/pester/Pester/wiki/Migrating-from-Pester-3-to-Pester-4" }```

so that old tests using ```Assert-VerifiableMocks``` (plural) throw an exception rather than silently swallow asserts if -Verifiable Mocks aren't actually called in the test.

**Comment by it-praktyk** [comment]
@mikeclayton, you are probably right. I just open the pull request #918.

Let's check what @nohwnd (I was assigned him as a reviewer) think about it.

**Comment by nohwnd** [comment]
@mikeclayton @it-praktyk throwing an exception is what I wanted to do all along, lol. must have been a long night when I wrote the update to 4.0.8
