### ISSUE TITLE
Ability to use variables declared outside of Describe or Context blocks

### ISSUE THREAD

**Issue by Draftkings** [pester/Pester#919]
I tried declaring a variable outside of any Describe or Context blocks in my Pester tests but it seems like when I attempt to consume them in my test, they are null. Am I missing something? 

Example

    $myVar = @{ key = 'value'; }

    Describe -Name 'MyFunction' {
        Context 'Given $myVar[key] = "abc" ' {
          # $myVar is null here
      }
    }

**Comment by it-praktyk** [comment]
Please read #895.

**Comment by it-praktyk** [comment]
I assume that the issue can be closed now. Feel free to reopen if you need more assistance.
