### ISSUE TITLE
AfterEach block how to take action when one of It blocks failed?

### ISSUE THREAD

**Issue by simonfangyingzhang** [pester/Pester#928]
Hi Guru,

suppose I have 1 Describe and multiple It blocks inside it, when 1 It block failed, I need to collect support files for debug, how I should do it inside AfterEach block?
could you please share with me sample code? many thanks

**Comment by it-praktyk** [comment]
Please read #909 once again.

**Comment by simonfangyingzhang** [comment]
looks like AfterEach block is the right place to collect support files, 

if AfterEach block can not support this kind of usage, could Pester consider it a feature request? thanks
