### ISSUE TITLE
Prevent multiple `Describe` blocks with the same name

### ISSUE THREAD

**Issue by mklement0** [pester/Pester#930]
It is currently possible to create multiple `Describe` blocks with the very same name.

It is easy to _accidentally_ create such duplicate names, and Pester then targeting _all_ duplicates with the given name can be confusing, if more tests than expected are being executed.

Ideally, Pester should either _fail_ when duplicate names are found or - if a potentially breaking change is to be avoided - at least issue a _warning_.

Example; assume that `./t.Tests.ps1` has the following content:

```powershell
Describe  foo {
  Write-Verbose -Verbose 'hi'
}
Describe  foo {  # Note the duplication of -Name 'foo'
  Write-Verbose -Verbose 'hi again'
}
```

Currently, invoking `Invoke-Pester ./t.Tests.ps1` doesn't complain about the duplicate names and instead executes _both_ blocks:

```none
> Invoke-Pester ./t.Tests.ps1
Executing all tests in './t.Tests.ps1'

Executing script ./t.Tests.ps1

  Describing foo
VERBOSE: hi

  Describing foo
VERBOSE: hi again
Tests completed in 0ms
Tests Passed: 0, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0
```

Ditto when passing the name explicitly _in full, literally_ (no wildcards) and when using `Run Tests` from Visual Studio Code from _either_ block:

```powershell
> Invoke-Pester -Script "./t.Tests.ps1" -TestName foo
Executing all tests in './t.Tests.ps1' matching test name foo

Executing script ./t.Tests.ps1

  Describing foo
VERBOSE: hi

  Describing foo
VERBOSE: hi again
Tests completed in 0ms
Tests Passed: 0, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0
```

**Comment by nohwnd** [comment]
I don't think we should assume anything about the names, duplicate names are possibly valid in some use cases, instead we should record the position of the test in the file and the full path and that would make the test uniquely identified.

**Comment by mklement0** [comment]
@nohwnd: What use cases require support for duplicate names? (There may be legitimate ones, I just can't think of any).

**Comment by nohwnd** [comment]
@mklement0 hard to say, environment tests most likely. :) I don't want to assume there are none and add restrictions that I don't know will hold. The uniqueness problem could be solved with the path and location in file, or we can look for a different solution. :)

**Comment by nohwnd** [comment]
I worked hard to keep this possible, the blocks are now uniquely identified by their container and position within it (where the opening curly brace is placed). There is also external Id that can be provided by test generator in case the sequence I am using internally would not be enough. 

Preventing duplicate blocks would fail especially in evironment tests. 

Closing, because I won't fix this.

**Comment by mklement0** [comment]
Just to satisfy my curiosity: what do you mean by _environment tests_? 

Do you mean blocks that test the same thing but target different platforms, via distinct `-Skip` criteria? 

If so, then the duplicate detection could be limited to identically named blocks that all have _no_ `-Skip` argument or the _same_ one (a literal comparison would be good enough, methinks).

**Comment by nohwnd** [comment]
Environment tests are tests that validate environment, eg. you have a server and you want to make sure everything on it is correctly setup, like DSC but without fixing the errors. Those tests are often generated from config files that are fed into foreach loops.

But generally I don't want to prevent anyone from generating few blocks with the same names if I don't have to. To two blocks with the same name are two different blocks, that just happen to have the same name.

**Comment by mklement0** [comment]
Thanks, @nohwnd - I know this isn't a big deal either way in the grand scheme of things, but I'm still struggling to see the _upside_ of allowing this - an automated way of generating tests _should_ use sequence numbers, for the authors' own benefit.

Given that there is no requirement for the _user_ to identify blocks with anything other than a name (even though Pester may assign IDs behind the scenes and there may be a way to _indirectly_ identify a specific instance after the fact), duplicate names seem to invite confusion; both `Describe` and `Context` happily accept duplicates.

On the flip side, I have no idea how costly such duplicate checks would be, and perhaps they're not worth entertaining for that reason alone.

I'm happy to leave it at that (and thanks for providing a crucial part of the PowerShell ecosystem).
