### ISSUE TITLE
Make build on Windows mandatory validation step

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#940]
Our code builds on TeamCity and TravisCI, but each integration works differently. On Travis we are running the build as a hook and waiting for it to complete, on TC we are pushing the details of build that we detect by pulling back to Github. The approach we use on TC makes the build on CI non mandatory, and when the TC server fails we are not notified that our tests were not run on any CI. 

Simply put we need our github to push the build to TC. Not TC pulling it from github.

**Comment by dlwyatt** [comment]
Looks like this is supported in TC now:  https://blog.jetbrains.com/teamcity/2016/09/installing-github-webhooks-from-teamcity/

**Comment by nohwnd** [comment]
@dlwyatt  Thx, I would have been very surprised if they did not have it. :) Will wait with this till we get license again so I can test it.

**Comment by dlwyatt** [comment]
Looks like the latest version of the github integration plugin also supports marking a build as Pending when it's added to the queue, rather than when it starts executing.  I've uploaded the webhooks plugin and updated the other one.

**Comment by nohwnd** [comment]
Added the hook, and changed the publish step to this: 
![image](https://user-images.githubusercontent.com/5735905/32699422-aa7b47a4-c7b5-11e7-8639-d02d99f8ea18.png)
Let's see if it works when the server runs again.

**Comment by nohwnd** [comment]
The builds are building fine, but when I merged to master I saw that it shown the checkmark quite fast, because the Travis build was fast, but the Windows build was not yet done. I would much rather see it yellow till both pass. At the moment I am not sure if that is config problem or just how it works. I will need to observe it a bit more on PRs and on merges.

**Comment by nohwnd** [comment]
I've set the detection to 10 minutes on both VCS roots we are using to see if the hook is working correctly or if we still rely on fetching the repository for the build.

**Comment by it-praktyk** [comment]
IMHO, it can be closed now. Am I right?
