### ISSUE TITLE
Getting boolean test result in the PS script

### ISSUE THREAD

**Issue by shurick81** [pester/Pester#946]
## 1. Provide a general summary of the issue in the Title above

I would like to incorporate test into a PS script but I don't know how.

## 2. Describe Your Environment

Operating System, Pester version and PowerShell version:

```
Pester version     :  
PowerShell version : 5.1.16299.64
OS version         : Microsoft Windows NT 10.0.16299.0
```

## 3. Expected Behavior

I tried to run test so I get a Boolean result in a variable and I expected that I can use this variable for the further script logic:

$res = .\Get-Planet.Tests.ps1
if ( $res ) { "Hello" }

## 4.Current Behavior

$res is always null

## 6. Context

Struggling to build a deployment script that consist of many steps and each step should be tested before moving to the next one.

**Comment by nohwnd** [comment]
Please see #360

**Comment by it-praktyk** [comment]
I assume that the issue can be closed now. Feel free to reopen if you need more assistance.
