### ISSUE TITLE
Get-ScriptModule error when no modules with given name imported

### ISSUE THREAD

**Issue by mikeclayton** [pester/Pester#949]
```powershell
Pester version     : 4.0.8 C:\src\github\pester\pester\Pester.psm1
PowerShell version : 5.1.15063.726
OS version         : Microsoft Windows NT 10.0.15063.0
```

When attempting to Mock a command in a module which is not loaded into scope, Get-ScriptModule throws an unclear error message:

```
 "Module 'MyNonExistentModule' is not a Script module.  Detected modules of the following types: ''".
```

Get-ScriptModule appears to be expecting PowerShell's built-in Get-Module to throw a terminating error if no modules match the name.

It attempts to ```catch``` the error, but it looks like Get-Module actually returns a $null object instead (which might be new behaviour in recent versions of PowerShell) so the ```catch``` block never runs..

One way to fix this is to add the following immediately after the ```try { ... } catch { ... }``` block in Get-ScriptModule:

```powershell
if ($modules.Count -eq 0)
{
    throw "No module named '$ModuleName' is currently loaded."
}
```

Here's some tests to validate current and proposed behaviour:

```powershell
Describe "Mock command" {

    Context "When attempting to mock a command in a non-existent module" {

        It "Current behaviour" {
            {
                Mock -CommandName "Invoke-MyMethod" `
                     -ModuleName  "MyNonExistentModule"
                     -MockWith    { write-host "my mock called!" };
            } | Should Throw "Module 'MyNonExistentModule' is not a Script module.  Detected modules of the following types: ''";
        }

        It "Proposed behaviour" {
            {
                Mock -CommandName "Invoke-MyMethod" `
                     -ModuleName  "MyNonExistentModule"
                     -MockWith    { write-host "my mock called!" };
            } | Should Throw "No module named 'MyNonExistentModule' is currently loaded.";
        }

    }

}
```

I can send a PR if this looks like a valid fix.

**Comment by it-praktyk** [comment]
@mikeclayton, thank you for your report and a proposed solution.

Please prepare a pull request based on the current master branch - what is now based on Pester 4.1.0.

Thank you.

**Comment by mikeclayton** [comment]
I've pushed some changes based on pester:master, but I can't work out how to open a second pull request from this branch while the first one is still open.

https://github.com/pester/Pester/compare/master...mikeclayton:feature/get-scriptmodule-error-message?expand=1

Any ideas how to do that?

**Comment by nohwnd** [comment]
@mikeclayton  That's why it is better to always make a topic branch (feature branch) for your changes, so you can keep your master and make more pull requests. :)  

BUT you can still make a new branch before your last commit. Looking at your changes, it looks like you are only one commit ahead of the original master. So you can simply checkout the commit that is the second newest `git checkout head~1` (you will get a message about detached head, but worry not, that is what you want), and then you create a new branch from that point by `git checkout -b"name-of-your-branch"`, at this moment you are on branch `name-of-your-branch`, and you can happily hack away.

**Comment by it-praktyk** [comment]
@mikeclayton, your previous contribution to Pester (the pull request #945).

Would you like prepare the new based on a proposal described above? 

Do you need support to clean/recreate the master branch in your fork or any git-related issues?

**Comment by nohwnd** [comment]
@mikeclayton Hello, are you still interested in getting your fix in Pester?
