### ISSUE TITLE
Missing folder when installing Pester via nuget

### ISSUE THREAD

**Issue by vgaltes** [pester/Pester#950]
I'm trying to setup a CI build using Pester and PSake. I'm getting errors executing Pester with some basic tests.

Environment:
Pester version: 4.1.0
PowerShell version: 5.1.16299.15
OS version: Microsoft Windows NT 10.0.16299.0

## Problem

I've created a psake script to run a build. What the script is doing is
- Downloading pester from nuget
- Importing the module
- Run the test

The problem is that the file Gherkin.ps1 has the following line on it
```
 & $SafeCommands["Import-Module"] -Name "${Script:PesterRoot}/lib/legacy/Gherkin.dll"
```

But the lib folder doesn't exist on the nuget package. If it switch to version 4.0.8 the folder exists and the build runs correctly

## Proposed solution

Add the lib folder to the nuget package

**Comment by nohwnd** [comment]
You are right something went wrong when I packaged 4.1.0. The build server got stuck on the package and I had to run the script locally. Not sure what exactly went wrong, since I used the same script. I am working on fixing it right now. It also affects chocolatey as they use the same nupkg.

**Comment by nohwnd** [comment]
The problem was that the libs has moved in one of the commits, and so our nuspec did not copy them. I am now testing updated build scripts so I can publish automatically again.

**Comment by nohwnd** [comment]
@vgaltes 4.1.1 is published that fixes this issue. Sorry it took so long, the build server broke down, and I needed to do a lot of changes to make it work again.
