### ISSUE TITLE
Set-StrictMode should be set for all Pester tests due to settings used by CI

### ISSUE THREAD

**Issue by it-praktyk** [pester/Pester#958]
Currently, the continues integration process uses strict mode but not all Pester tests have declared that at the beginning of the file.

As the result, some tests what pass run locally fails under CI due to e.g. non-existing parameters, undeclared variables etc.

You can see that behavior on the screenshot included below - I include it due that tests results are periodically cleaned at the CI server.

![pester_publish_status_to_github_3_ 15_dec_17_22_02 _overview_ _teamcity_-_2017-12-17_13 52 28](https://user-images.githubusercontent.com/4910261/34079630-a80eafaa-e331-11e7-832c-d31256aed637.png)

Screenshot is based on a pipeline results for #955.

Files which don't contain Strict-Mode at the first line (excluding the Examples folder)

```
PS Pester> Get-ChildItem -Include *.Tests.ps1 -Recurse | foreach { [String]$FileFirstLine = "{0} - {1}" -f $_.FullName, $(Get-Content $_ | Select-Object -First 1) ; If ( $FileFirstLine -notmatch 'StrictMode') { Write-Host $FileFirstLine } }

<DIRECTORY_PATH>\Functions\BreakAndContinue.Tests.ps1 - Describe 'Clean handling of break and continue' {
<DIRECTORY_PATH>\Functions\Environment.Tests.ps1 - InModuleScope -ModuleName Pester {
<DIRECTORY_PATH>\Functions\GlobalMock-A.Tests.ps1 - # This script exists to create and mock a global function, then exit.  The actual behavior
<DIRECTORY_PATH>\Functions\GlobalMock-B.Tests.ps1 - # This test depends on some state set up in GlobalMock-A.Tests.ps1.  The behavior we're verifying
<DIRECTORY_PATH>\Functions\New-MockObject.Tests.ps1 - describe 'New-MockObject' {
<DIRECTORY_PATH>\Functions\Output.Tests.ps1 - InModuleScope -ModuleName Pester -ScriptBlock {
<DIRECTORY_PATH>\Functions\SetupTeardown.Tests.ps1 - Describe 'Describe-Scoped Test Case setup' {
<DIRECTORY_PATH>\Functions\TestsRunningInCleanRunspace.Tests.ps1 - function Invoke-PesterInJob ($ScriptBlock, [switch] $GenerateNUnitReport, [switch]$UseStrictPesterMode)
<DIRECTORY_PATH>\Pester.Tests.ps1 - $here = Split-Path -Parent $MyInvocation.MyCommand.Path
```
I think that we should add ```Set-StrictMode -Version Latest``` at the beginning of any Tests.ps1 file.

Confirmed at

```powershell
Pester version     : 4.1.1 <FOLDER_PATH>\Pester\Pester.psm1
PowerShell version : 5.1.15063.786
OS version         : Microsoft Windows NT 10.0.15063.0
```

**Comment by it-praktyk** [comment]
The related issue: #870

**Comment by nohwnd** [comment]
Are you using `.\bin\pester.bat` to run the tests on your local computer?

**Comment by it-praktyk** [comment]
Nope, I just (re)import the module from the branch what I'm working on and type `Invoke-Pester`.

**Comment by nohwnd** [comment]
Could you try it with the bin\pester.bat? it gives you clean session, and I am using it to do pre-release checks on my computer, and I think the build server uses it as well. So maybe we could set the strict mode threre just once?
