### ISSUE TITLE
Pester 3.4.6 vs 4.1.1 NUnit schema ?

### ISSUE THREAD

**Issue by it-praktyk** [pester/Pester#967]
## 1. Provide a general summary of the issue

As a part of discussion about #888 @dlwyatt [mentioned](https://github.com/pester/Pester/issues/888#issuecomment-344923915)

> In Pester v4, we make use of that structure to allow for any number of nested Describe or Context blocks (plus we log a fixture per script file, and one root fixture for the entire run of Invoke-Pester.)

Because are opened issues related to [Output and CI](https://github.com/pester/Pester/issues?q=is%3Aopen+is%3Aissue+label%3A%22Output+and+CI%22), especially #663, I tried to dig in this change.

I've used tests those are a part of [Format-Pester](https://github.com/equelin/format-pester) and generated NUnit files using Pester v. 3.4.6 and 4.1.1. You can find files as parts of [the gist](https://gist.github.com/it-praktyk/9f85dc278de34b3e9868a11dd462d36f).

I realized that the structures of XML files are different - what I expected - but reference to NUnit schema xsd file in both cases is the same and looks like

Pester v. 3.4.6 NUnit XML - a part only
```
<test-results xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="nunit_schema_2.5.xsd" name="Pester" total="21" errors="0" failures="5" not-run="0" inconclusive="9" ignored="3" skipped="0" invalid="0" date="2017-12-21" time="06:34:16">
```

Pester v. 4.1.1 NUnit XML - a part only
```
<test-results xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="nunit_schema_2.5.xsd" name="Pester" total="21" errors="0" failures="5" not-run="0" inconclusive="9" ignored="3" skipped="0" invalid="0" date="2017-12-21" time="06:33:00">
```

## 2. Describe Your Environment

Operating System, Pester version and PowerShell version:

```powershell
Pester version     : 3.4.6 C:\Program Files\WindowsPowerShell\Modules\pester\3.4.6\Pester.psm1
and 
Pester version     : 4.1.1 C:\Program Files\WindowsPowerShell\Modules\pester\4.1.1\Pester.psm1

PowerShell version : 5.1.15063.786
OS version         : Microsoft Windows NT 10.0.15063.0

```

## 3. Expected Behavior

The other XSD schema will be used/referenced in Pester versions 3.4.6 and 4.1.1.

Information about changed NUnit file will be included in [the release notes for the version 4.0.7 of Pester](https://github.com/pester/Pester/releases/tag/4.0.7)

## 4.Current Behavior

The same XSD schema is used/referenced in Pester versions 3.4.6 and 4.1.1.

**Comment by it-praktyk** [comment]
CC: @bielawb, @smurawski, @chrislgardner

**Comment by dlwyatt** [comment]
Is the 2.5 xsd not valid for the output we’re creating now?  I don’t see why it would need to change otherwise.

**Comment by nohwnd** [comment]
The output is validated against the 2.5 schema that is included in the repo. There are tasks that propose the update to NUnit 3.0 e.g. #1087 that can be implemented as a new formatter. I don't see any action that needs to be taken here.
