### ISSUE TITLE
mock.ps1 - parameter not passed into scriptblock

### ISSUE THREAD

**Issue by dogleft** [pester/Pester#969]
## 2. Describe Your Environment
Operating System, Pester version and PowerShell version:
Pester version     :
PowerShell version : 5.1.14393.1944
OS version         : Microsoft Windows NT 10.0.14393.0

## 3. Expected Behavior

The mock should play out and return the substitute hash.

```powershell
function New-NewHireHash
{
    param($SmartSheetUserRow)
    @{'realkey' = 'realvalue'}
}
function Get-NewHiresFromSmartSheet
{
    New-NewHireHash "UserRow"
}
Describe "NewHire SmartSheet" {
    Context "User selection" {
        Mock New-NewHireHash {
            param ($NewUserObj)
            Write-Host "Mock New-NewHireHash $($NewUserObj["Name"])"
            @{'mockkey' = 'mockvalue'}
        }
        It "Retrieves all users from the master newhire SmartSheet" {
            Get-NewHiresFromSmartSheet | Should -Be 1
        }
    }
}
```

## 4.Current Behavior
Exception:
      [-] Retrieves all users from the master newhire SmartSheet 91ms
        Cannot index into a null array.
        at <ScriptBlock>, C:\Users\ansmith\Documents\WindowsPowerShell\Modules\Pester\Functions\Mock.ps1: line 1122
        1122:     & $scriptBlock @splat

## 5. Possible Solution
If you comment out line 14 - the Write-host, then the mock works as expected.

## 6. Context

How has this issue affected you? What are you trying to accomplish?
Just mocking, man. Just mocking.

**Comment by it-praktyk** [comment]
@dogleft,
thank you for the report and a proposed solution. We will verify it, I hope soon.

Please be aware that due to security reason I've removed attached zip file. Please share a code required for reproducing as a gist. Thank you for your understanding.

**Comment by dogleft** [comment]
You bet. Created public gist: "https://gist.github.com/dogleft/3ff3600b6f20c4002155a4156e977cd7.js" 
"Repro for pester issue 969 - parameter not passed into scriptblock"

For repro, set a breakpoint on mock.ps1 1122 for the command & $scriptBlock @Splat
Before this call, you'll see that the parameters to be passed are populated. 
Inside the scriptblock, the parameter is $null

Hope that helps. 
-Andy

**Comment by nohwnd** [comment]
I am not sure what you are trying to do in the repro code. But if you want to pass a hashtable in the mock you need to do it the same way as if you would call your normal function, the parameters of the original function will be defined by on the mock function. Like this: 

```powershell
Describe "NewHire SmartSheet" {
    Context "User selection" {
        # normal function that takes a parameter called 'someParameter'
        function f ($someParameter) { $someParameter }
        # the mock will have $someParameter defined as well, you can refer to it in your scriptBlock
        mock f { Write-Host "I am mock and I got '$someParameter'" }

        It "t" {
            # passing 1234 in the someParameter
            f -someParameter "1234"
        }
    }
}
```

**Comment by nohwnd** [comment]
@dogleft Were you able to resolve this issue? If so please respond and reopen the issue.

**Comment by Jeffrey-zhao** [comment]
@nohwnd  I try it out with your case, it works, Now I have an issue. the scenario: for an example: 
mytest.ps1
`
function A($p1,$p2)
{ 
   #some logic handling with paramters p1 and p2
   # i give an easy logic,but it is complext in fact,just make it easy.
   $p33=$p1+1;
   $p44=$p2+1;

   return B -P3 $p33 -P4 $P44
};
function B($p3,$p4)
{
 return $p3 +$p4
}
`
mytest.tests.ps1:
`
Describe "Tesing A" {
    Context "valid value" {
       # this two only differences are 'param()'
        mock B { return $p3+$p4 } -filterparamter {$p3 -eq 1}
        mock B { param($p3,$p4) return $p3+$p4 } -ParameterFilter{$p3 -eq 2}
        It "p3 -eq 1" {
           $ret= A -P1 0 -P2 1 # it means it passes 1 to B function's P3 
           $ret |should -Be 3
        }
        It "p3 -eq 2 " {
            # passing 1234 in the someParameter
            $ret=A -P1 1 -P2 1  # it means it passes 2 to B function's P3
            $ret |should -Be 4
        }
    }
}
`
when it executs in the line 1111   & ${Script Block} @___BoundParameters___ @___ArgumentList___ `
 or 1123 ` ` & $scriptBlock @splat `
in  mock.ps1 ,debuging get different parameters values
it mainly points at $___BoundParameters___ and  $___BoundParameters___
so how can i know these above two arguments 's differences?
very glad to get all of you help.
i test 'Its' all passed
