### ISSUE TITLE
Support for TRX test results format

### ISSUE THREAD

**Issue by heaths** [pester/Pester#977]
We have a large build/test/release workflow that standardizes on TRX for reporting. I propose (and am willing to implement) support for TRX as another report format.

Specifically, I propose:
- [x] Add a durable GUID to each group and test result in `PesterState` based on https://gist.github.com/heaths/7470fc582dcfcc9c87f65e013432d3c3. I could do this directly in the formatter but would require separate state that would be easier to manage in `PesterState` itself.
- [ ] Refactor out `Export-NUnitReport` to its own script just for more isolated diffs in any future maintenance.
- [ ] Create a separate `Export-TRXReport` script.
- [ ] Update existing scripts to support 'TRX' as a new optional format.
- [ ] Update Pester wiki with information about the new feature.

**Comment by it-praktyk** [comment]
@heaths,
I expect - a final decision will be made when we will see a code - that we will accept contribution what will fulfill your proposal.

Some questions/remarks - numbers based on your list
1. A durable GUID will be generated based on which tests parameters?
2. It shouldn't be a problem
3. Nothing to add
4. Nothing to add

Missed point "Update Pester wiki with information about the new feature"

**Comment by heaths** [comment]
I would at least like to know if accepting TRX as an optional format is something you would consider. Of course the code will have to stand up to scrutiny, but as your own [contribution docs](https://github.com/pester/Pester/wiki/Contributing-to-Pester) state,

> When we discuss new features we look at how useful it is to the majority of users, how difficult it would be to implement, if breaking changes to the API must be introduced to have it, and if it's too specialized or too general to put in the codebase. But again, don't let that scare you away.

I don't expect it will take long to implement, but once or twice I made a PR-first feature change only to have it summarily rejected on principal. It's a lost opportunity cost and I'm sure we all have too many projects in the hopper. :)

I've added the task to update the wiki. Good point.

**Comment by it-praktyk** [comment]
Your contribution will be welcomed.

Generally, we will accept any good prepared and reviewable (not based on the solution that we can't verify by us) extension in the area of integration with external systems.

**Comment by nohwnd** [comment]
@heaths Please implement it :)

**Comment by nohwnd** [comment]
@heaths are you still interested in implementing this?  If so please re-open this. At the moment it seems others are happy with NUnit and JaCoCo outputs but more formatters will be welcome.

**Comment by nohwnd** [comment]
I totally understand. Keeping the drive is a difficult thing to do :)

**Comment by MichaelGrafnetter** [comment]
TRX reports would be nice for projects containing MSTest/VSTest units tests together with Pester tests, so that a single run of a reporting tool can read them all at one and render a unified test report.
