### ISSUE TITLE
When using -ScriptBlock named parameter on a BeforeAll block at the same time as using test cases

### ISSUE THREAD

**Issue by johlju** [pester/Pester#979]
## 1. Provide a general summary of the issue in the Title above

So I hit a strange error. I was writing and It block using test cases, and the test cases are built in the BeforeAll block. I added the named parameter `-ScriptBlock` to the `BeforeAll`-block and all of the sudden the `It `-block using the test cases starting to fail.

## 2. Describe Your Environment

Operating System, Pester version and PowerShell version:

```powershell
Pester version     : 4.1.1 C:\Program Files\WindowsPowerShell\Modules\pester\4.1.1\Pester.psm1
PowerShell version : 5.1.15063.786
OS version         : Microsoft Windows NT 10.0.15063.0
```

## 3. Expected Behavior

I was expecting that using `BeforeAll -ScriptBlock {}` would work even when using test cases and building them inside the `BeforeAll`-block. But there might be a logic explanation to why this can't work. 🤔 😄 

### This fails using `BeforeAll -ScriptBlock {}`
```powershell
Describe -Name 'Something' -Fixture {
    BeforeAll -ScriptBlock {
        $testCases = @(
            @{
                Result = $true
            }
        )
    }

    Context -Name 'When' -Fixture {
        It -Name 'Should' -TestCases $testCases -Test {
            param
            (
                $Result
            )

            $true | Should -Be $Result
        } 
    }
}
```

### This works using `BeforeAll {}`
```powershell
Describe -Name 'Something' -Fixture {
    BeforeAll {
        $testCases = @(
            @{
                Result = $true
            }
        )
    }

    Context -Name 'When' -Fixture {
        It -Name 'Should' -TestCases $testCases -Test {
            param
            (
                $Result
            )

            $true | Should -Be $Result
        } 
    }
}
```

## 5. Possible Solution

The workaround is to not use named parameters in this particular case.

## 6. Context

Minor nuisance.

**Comment by dlwyatt** [comment]
That's a result of me getting too fancy.  When the Before/After Each/All feature was requested, the person who asked for it referred to equivalent features in another framework, commenting that they could be placed anywhere in the test definition (even after the test cases) and still work.

What I should have said was "Sure, I can implement this, but they have to go before the test cases because we're just sequentially executing PowerShell script blocks here."  What I actually said was "Hey, that sounds fun, I'll give it a whirl!"  :P  So I did my own quick and dirty parsing to do the actual work.

Short answer: it's meant to be used like a language element, not a cmdlet.  :)

**Comment by it-praktyk** [comment]
@dlwyatt, It's not a bug, it's a feature?

**Comment by it-praktyk** [comment]
It's probably required reviewing/updating documentation.

**Comment by dlwyatt** [comment]
More like a limitation of supporting PowerShell v2. In v3+ I’d just use the AST

**Comment by nohwnd** [comment]
Note to self: I am considering making the blocks a parameter on the respective keywords. That way we don't have to parse it (even if we could) and you can still place them before and after your block/test body, or both before it.

**Comment by nohwnd** [comment]
This is not a problem anymore, the blocks are collected during the Discovery phase and are run in the same way that other blocks are run (a function takes the provided scriptblock and shoves it into the interal tree of blocks and tests). During run the scriptblock is taken from that tree and Before* After* blocks do nothing. No AST.
