### ISSUE TITLE
travis-cs question

### ISSUE THREAD

**Issue by dfinke** [pester/Pester#985]
I used your `.travis.yml`. The macOS works with the line below, but the linux version says PowerShell requires an elevated rights. Do you know how to `sudo` for a script? 

```yaml
script:
  - pwsh -c 'Install-Module Pester -Force; Invoke-Pester'
```

**Comment by it-praktyk** [comment]
Installing in the current user scope isn't an option?

I assume that you try to install/run Pester on Linux so you can use [gosu - Simple Go-based setuid+setgid+setgroups+exec](https://github.com/tianon/gosu) for it.

**Comment by it-praktyk** [comment]
or [su-exec](https://github.com/ncopa/su-exec).

Disclaimer: My answers are written at 4:20 AM. ;-)

**Comment by dfinke** [comment]
Went with `-Scope`. Thank you.
