### ISSUE TITLE
Feature request for Project level Recursive Code Coverage metrics. 

### ISSUE THREAD

**Issue by Contramatter** [pester/Pester#989]
## 1. Provide a general summary of the issue in the Title above
The current -CodeCoverage parameter accepts only one path string with wildcards. This seems to work well enough to target one or more ps1 files within a give folder, but does not seem to offer a method to provide total recursive code coverage results for a project having a multi level folder structure. There also does not seem to be a way to exclude the *.Tests.ps1 files from the code coverage calculations. 

## 2. Describe Your Environment

Operating System, Pester version and PowerShell version:

Pester version     :  4.2.0
PowerShell version : 5.1.14409.1012
OS version         : Microsoft Windows NT 6.3.9600.0

## 3. Suggested Change/Improvement/Enhancement
It would be useful to get result statistics on all files of a given pattern recursively from a given path, and a method to filter out files that follow a given pattern, such as the pester test files. The file filters could use either a wild card or regex pattern.

Example: 
```$results = Invoke-Pester -Path $Path -RecursiveCodeCoverage $Path -IncludePattern "*.ps1" -ExcludePattern "*.Tests.ps1" -PassThru```

This feature would cover all files recursively from the provided **RecursiveCodeCoverage** path, applying inclusion and exclusion filters. The goal is to get an accurate estimate of total code coverage for a given powershell project. 

Example:
`$coverage = [math]::Round($(100 - (($results.CodeCoverage.NumberOfCommandsMissed / 
$results.CodeCoverage.NumberOfCommandsAnalyzed) * 100)), 2);
`
`Write-Output "Code Coverage: $coverage%"`

## 4. Context
We are trying to get metrics on total code covered by unit tests for projects with dozens of ps1 files across multiple folders and sub folders.

**Comment by nohwnd** [comment]
@Thilas sorry for bumping you again, but is this by any chance done in the recent changes to CC?

**Comment by Thilas** [comment]
@Contramatter, there is an easy way to do such recursve code coverage. Here is how I'm doing it:

```powershell
$files = Get-ChildItem $Path -Recurse -Include '*.ps1' -Exclude '*.Tests.ps1'
$results = Invoke-Pester -Path $Path -CodeCoverage $files -PassThru
```

**Comment by nohwnd** [comment]
@Contramatter  Okay that should solve it, if not please reopen :)
